### ISSUE TITLE
Provide way to use ConnPool together with sqlx

### ISSUE THREAD

**Issue by zamotivator** [jackc/pgx#100]
I like pgx, and I also like sqlx.
We need to some way use ConnPoll together with sqlx

**Comment by zamotivator** [comment]
So, sqlx has own connection pool. Probably, I should use sqlx implementation instead of pgx

**Comment by jackc** [comment]
I haven't looked closely at sqlx, but based on a quick examination I believe you are correct. i.e. The correct way for pgx and sqlx to work together is to use sqlx for connection pooling (which appears to internally use database/sql for pooling).

**Comment by zamotivator** [comment]
Moreover - the default sql/database has internal connection pool
We do not need one more
