### ISSUE TITLE
Can not find v4 package

### ISSUE THREAD

**Issue by maxsupermanhd** [jackc/pgx#1007]
When I am trying to import pgx without `v4` at the end it is kinda working but I can not check for ErrNoRows
After importing `v4` g can not find package anymore, says: `cannot find package "github.com/jackc/pgx/pgxpool/v4"`

**Comment by maxsupermanhd** [comment]
I solved issue with ErrNoRows but still can not import v4, what am I doing wrong?

**Comment by jackc** [comment]
> After importing v4 g can not find package anymore, says: cannot find package "github.com/jackc/pgx/pgxpool/v4"

That's the wrong import path. It should be `github.com/jackc/pgx/v4/pgxpool`.

**Comment by maxsupermanhd** [comment]
I tried a lot of different configurations, this one was first - I grabbed it from tutorial or example, don't remember that already. Error does not change:
```
main.go:25:2: cannot find package "github.com/jackc/pgx/v4/pgxpool" in any of:
	/usr/lib/go-1.13/src/github.com/jackc/pgx/v4/pgxpool (from $GOROOT)
	/home/max/go/src/github.com/jackc/pgx/v4/pgxpool (from $GOPATH)
```

**Comment by jackc** [comment]
I don't think this is specific to pgx, but I have run into problems like that that were resolved with `go mod tidy`.

**Comment by maxsupermanhd** [comment]
I don't have modules at all, it says can not find main module...
