### ISSUE TITLE
v3 pulled alongside v4

### ISSUE THREAD

**Issue by oakad** [jackc/pgx#1008]
Not sure if this is an issue, but sometimes those things indicate botched dependencies:

    # go get github.com/jackc/pgx/v4
    go: downloading github.com/jackc/pgx/v4 v4.11.0
    go: downloading github.com/jackc/pgx v3.6.2+incompatible 
    go: downloading github.com/jackc/pgconn v1.8.1
    go: downloading github.com/jackc/pgio v1.0.0
    go: downloading github.com/jackc/pgproto3 v1.1.0
    go: downloading github.com/jackc/pgtype v1.7.0
    go: downloading github.com/jackc/chunkreader v1.0.0
    go: downloading github.com/jackc/pgpassfile v1.0.0
    go: downloading github.com/jackc/pgproto3/v2 v2.0.6
    go: downloading github.com/jackc/chunkreader/v2 v2.0.1
    go: downloading github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b
    go get: added github.com/jackc/pgx/v4 v4.11.0

**Comment by jackc** [comment]
I think it is being pulled in because of test dependencies.

**Comment by cosmotek** [comment]
@jackc Is there any way we can fix this? This is causing my Snyk vuln scanner to fail in CI due to a handful of vulnerabilities in v3.6.2, but there is no upgrade path due to the lack of a module at the project root.

**Comment by cosmotek** [comment]
Nevermind my last comment, turns out we were importing the base package somewhere and just needed to use `go mod why ...` to find it.
