### ISSUE TITLE
error rise when send big batch after a while

### ISSUE THREAD

**Issue by alexlee85** [jackc/pgx#1009]
my prog often send 100+ thousands records to pg.
every thing is ok at first, but after a while error happens.

error msg:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x753629]

goroutine 1 [running]:
github.com/jackc/pgx/v4.(*Conn).SendBatch(0xc006a9e480, 0x913fb0, 0xc0000260b8, 0xc008af7890, 0xc000b9b9a0, 0xc000866000)
        /Users/alex/golang/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/conn.go:756 +0x129
github.com/jackc/pgx/v4/pgxpool.(*Conn).SendBatch(0xc00b596760, 0x913fb0, 0xc0000260b8, 0xc008af7890, 0x0, 0x0)
        /Users/alex/golang/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/pgxpool/conn.go:66 +0x6f
github.com/jackc/pgx/v4/pgxpool.(*Pool).SendBatch(0xc0001500e0, 0x913fb0, 0xc0000260b8, 0xc008af7890, 0xc0034f1220, 0xc000c78120)
        /Users/alex/golang/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/pgxpool/pool.go:482 +0x95
main.main()
```

**Comment by jackc** [comment]
Hmm... That's a very strange place for an error to occur. 

https://github.com/jackc/pgx/blob/00feeaa5c9e71688375ce0038f19b28e2703c091/conn.go#L756

`c.preparedStatements` is initialized when a connection is created. It should never be nil.

Have you run this with the race detector?

Do you have a case that can reproduce this?

**Comment by alexlee85** [comment]
tks @jackc 

I'm a golang freshman, I need learn race detector first and try to find why this happen.

**Comment by alexlee85** [comment]
@jackc 

after run with race detector, I find I Queue to batch in many goroutines.
my bad 😞

Appreciate!!

**Comment by alexlee85** [comment]
@jackc 

after run with race detecotr, I found I queue query to batch in many goroutines.
when I add Mutex to my code , everything is fine.

my bad 😞
Appreciate !!!

**Comment by alexlee85** [comment]
@jackc 
after use race detector I find
