### ISSUE TITLE
Question about getting a db connection from a pgx connection to use with sqlx

### ISSUE THREAD

**Issue by marcesher** [jackc/pgx#1015]
Hi folks,

Relatively middle-of-the-road Go developer here, seeking help figuring out exactly how to do something. Not sure if I should ask this here or in the `sqlx` repo but I'm starting here:

Our code already uses `pgx` successfully with standard `pool.Query` and `rows.Scan` semantics.

I'd like to try integrating `sqlx` for sql-to-struct mapping where possible.

Where I'm struggling is figuring out how to adapt a pgx Pool into a sqlx DB object in order to run sqlx commands such as `db.Select()`.

Can anyone point me to examples of doing something like this, or just in general how exactly to use `pgx` with `sqlx`?

Thanks so much!

**Comment by jackc** [comment]
I think `sqlx` would require using `database/sql` and the `pgx/stdlib` driver.

**Comment by marcesher** [comment]
thanks @jackc
