### ISSUE TITLE
go mod download: github.com/pierrec/lz4@v2.0.5+incompatible: unexpected EOF

### ISSUE THREAD

**Issue by patelsan** [jackc/pgx#1017]
Running into pgx v4.11.0 `go mod download` is causing error `github.com/pierrec/lz4@v2.0.5+incompatible: unexpected EOF`. Running the sample "Hello world from PostgreSQL" from https://github.com/jackc/pgx/wiki/Getting-started-with-pgx. No other code or dependencies. What might have started causing this? I am on `go version go1.16.4 darwin/amd64`. 

A couple of additional points: (a) Ran `go clean --modcache`, but that didn't make any difference. (b) The same error is observed while building docker image based on Alpine (c) Tried on a different computer, and it's working there! So, the root cause is probably unrelated to PGX, but any inputs are greatly appreciated.

**Comment by jackc** [comment]
I'm not sure what would cause that problem. The example predated the requirement to manually download / add module dependencies so I added `go get github.com/jackc/pgx/v4` to the instructions. But with that change I just ran through the example and it worked for me.

**Comment by segfault88** [comment]
Surely `unexpected EOF` is due to some problem with actually downloading the module? Are you using a module proxy that is having problems? Is it still a problem (maybe there was a temporary issue that is resolved now?)?
