### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by samstride** [jackc/pgx#1018]
Hi,

Thanks for maintaining this library.

I am using managed CRDB v21.1.1 on GCP and I have a GKE cluster running my services. I have a VPC setup between my GKE cluster and managed CRDB.

Using `github.com/jackc/pgx/v4 v4.11.0`

I have initilaized a connection pool as follows:

```go
package main

import (
	"context"
	"os"

	"github.com/jackc/pgx/v4/pgxpool"
)

// initDB - initialize a connection pool to DB.
func (instance *server) initDB() {
	// Connect to DB
	config, err := pgxpool.ParseConfig(instance.DBUrl)
	if err != nil {
		instance.logger.Fatal("error configuring the database: ", err)
	}
	config.MinConns = 1
	config.MaxConns = 4
	instance.dbpool, err = pgxpool.ConnectConfig(context.Background(), config)
	if err != nil {
		instance.logger.Fatalf("Unable to create connection pool: %v", err)
		os.Exit(1)
	}

	instance.logger.Info("Connected to DB ...")
}
```

After about 10 mins of inactivity (sometimes longer), the first query that runs throws an `unexpected EOF`. All other queries after that work without errors. 

Am I doing something wrong or missing something?

Cheers.

**Comment by segfault88** [comment]
I would guess idle connections are being dropped after a certain time with no traffic by an underlying layer. Try setting a `MaxConnIdleTime` less than 10 mins. For example:

```go
config.MaxConnIdleTime = 5 * time.Minute
```

Or try a `HealthCheckPeriod` which might be able to keep the connection alive by sending a health check:

```go
config.HealthCheckPeriod = 1 * time.Minute
```

**Comment by samstride** [comment]
@segfault88 , Thanks.

The default health check period is `time.Minute`.

```go
config.HealthCheckPeriod = defaultHealthCheckPeriod // var defaultHealthCheckPeriod = time.Minute
```

Looking deeper into the logs, I am seeing this:

```sh
tls error (EOF)
```

Seems to be similar to [issue 825](https://github.com/jackc/pgx/issues/825).

This started happening after upgrading to 21.1.1. Have raised an issue with CRDB support. Still waiting to hear back.

**Comment by samstride** [comment]
The CRDB cluster issue I was facing seems to have been resolved by [CRDB PR 65860](https://github.com/cockroachdb/cockroach/pull/65860).

**Comment by rizalgowandy** [comment]
I am seeing the same error from using YugabyteDB.
There are intermittent "unexpected EOF" error.
