### ISSUE TITLE
COPY Support

### ISSUE THREAD

**Issue by vinceprignano** [jackc/pgx#102]
Would be nice to have oob support for the COPY command, lib/pq has something similar https://godoc.org/github.com/lib/pq#hdr-Bulk_imports

**Comment by jackc** [comment]
I've never used copy outside of the psql tool. What is the desired use case?

Copy protocol support could require a fair amount of work depending on how exactly how it is implemented. According to the [docs](http://www.postgresql.org/docs/9.4/static/sql-copy.html), the entire copy has to be in text format or binary format. Normal queries support values in both formats in the same query. pgx type converters only support one format or the other. For example, `inet` only supports binary format and `json` only supports text format. So even though the copy protocol itself is relatively simple, full support would require making all types support the text or binary protocol.

On the other hand, if a `Copy` function disclaimed support for type conversion and required all data to come in as strings, it might not be too bad.

**Comment by atombender** [comment]
@jackc: Yes, please! The use case for `COPY` is fast batch imports; it's the fastest way to ingest data into PostgreSQL.

Binary would be my format of choice, and I think forgoing type conversion support is perfectly reasonable. Part of the idea, after all, is to prepare all your data beforehand.

How much work would this be, do you think?

**Comment by jackc** [comment]
A Copy function that did not do any type conversion would probably not be too much work. The question is how useful it would be -- it would definitely be harder to use than how lib/pq does Copy. For either binary or text format, the end-user would need to do a fair amount of pre-processing (binary in particular could be challenging -- the only documentation is the PostgreSQL source code)

**Comment by atombender** [comment]
I think the PostgreSQL JDBC driver for Java implements binary copy, and there are probably other libraries out there that do, so it shouldn't be too bad to reverse-engineer.

I took a look at the [documentation](http://www.postgresql.org/docs/9.1/static/protocol-message-formats.html), and it doesn't look too bad. Curiously, the exact format of the data is documented under the [`COPY` command](http://www.postgresql.org/docs/9.5/static/sql-copy.html).

I'm not intimately familiar with the PostgreSQL protocol (though I have once implemented it as part of a proxy) — isn't the binary tuple data format the same as that used for results? Isn't it sufficient for the client to provide the exact types that match whatever schema you are copying into? Since it's advanced functionality available for optimization purpose, making it slightly onerous for the client to implement would be okay.

I may be able to contribute some work here, if I can set aside some spare time.

**Comment by jackc** [comment]
The format for the copy protocol is documented. But the binary formats for the various data types are not. As you say, there are several places to find the binary format (and pgx already implements most types in binary). But it would be sub-optimal to make the user do that work, but I guess it's better than not having the feature at all. It _might_ not be that much work to make all pgx types support binary. Not sure.

If you want to tackle this, let's discuss the proposed interface before writing a lot of code.

**Comment by atombender** [comment]
If pgx doesn't implement all the types today (I don't know which ones you don't implement, but I'm guessing perhaps esoteric things like points, arrays or IP addresses?), then having `COPY` not support the same set would be perfectly acceptable — or did you mean something else?

Of course pgx should serialize the data for the user. In principle, the interface could be something like:

```go
conn.CopyToTable("users", []string{"id", "name", "created_at"}, [][]interface{}{
  []interface{1, "bob", time.Now()},
})
```

It'd be even nicer if you didn't have to materialize the input data beforehand, but instead provided an iterator to allow `CopyToTable` to stream it:

```go
func (d *MyData) NextRow() (interface{}, error) {
   ...
}
myData := &MyData{...}
conn.CopyToTable("users", []string{"id", "name", "created_at"}, mydata)
```

This way, you can implement streaming from file, for example.

Thoughts?

**Comment by jackc** [comment]
I like this interface. The interface could even fallback internally to insert if it couldn't copy for some reason.

**Comment by atombender** [comment]
I prefer abstractions like that to belong at a higher level. In my particular case, I would definitely want to know (through a special error, perhaps) if copying couldn't be done, so I could log a warning.

**Comment by jackc** [comment]
Fair enough.

**Comment by atombender** [comment]
Awesome, thanks, @jackc!

**Comment by jackc** [comment]
I finally got to implementing copy protocol support. I ended up going for an interface similar to the Rows struct.

```go
// CopyToSource is the interface used by *Conn.CopyTo as the source for copy data.
type CopyToSource interface {
	// Next returns true if there is another row and makes the next row data
	// available to Values(). When there are no more rows available or an error
	// has occurred it returns false.
	Next() bool

	// Values returns the values for the current row.
	Values() ([]interface{}, error)

	// Err returns any error that has been encountered by the CopyToSource. If
	// this is not nil *Conn.CopyTo will abort the copy.
	Err() error
}
```

I also provide a wrapper for `[][]interface{}` that implements this interface.

Wow! I am really surprised at how much faster it is. I tested with inserting rows one per insert statement wrapped in a transaction, multi-row inserts wrapped in a transaction, and the new CopyTo. CopyTo was faster with as little as 5 rows. At 10,000 rows it is ~10x faster than multi-insert and ~30x faster than insert per statement.

And this is connecting to a local unix socket, so round-trip time is as low as possible. Presumably round-trip time would make the results even more dramatic in non-localhost scenarios.

```
jack@hk-47~/dev/go/src/github.com/jackc/pgx$ go test -test.run=CopyTo -test.bench=Write
PASS
BenchmarkWrite5RowsViaInsert-4         	    2000	    595328 ns/op
BenchmarkWrite5RowsViaMultiInsert-4    	    2000	    595215 ns/op
BenchmarkWrite5RowsViaCopy-4           	    3000	    465630 ns/op
BenchmarkWrite10RowsViaInsert-4        	    2000	    970905 ns/op
BenchmarkWrite10RowsViaMultiInsert-4   	    2000	    723295 ns/op
BenchmarkWrite10RowsViaCopy-4          	    3000	    467747 ns/op
BenchmarkWrite100RowsViaInsert-4       	     200	   7756240 ns/op
BenchmarkWrite100RowsViaMultiInsert-4  	     500	   3146064 ns/op
BenchmarkWrite100RowsViaCopy-4         	    2000	    982194 ns/op
BenchmarkWrite1000RowsViaInsert-4      	      20	  80898592 ns/op
BenchmarkWrite1000RowsViaMultiInsert-4 	      50	  30278678 ns/op
BenchmarkWrite1000RowsViaCopy-4        	     300	   5403834 ns/op
BenchmarkWrite10000RowsViaInsert-4     	       2	 979629663 ns/op
BenchmarkWrite10000RowsViaMultiInsert-4	       3	 349942558 ns/op
BenchmarkWrite10000RowsViaCopy-4       	      50	  32960084 ns/op
```

**Comment by atombender** [comment]
The interface looks perfect. Those numbers are impressive. I knew it was fast, but 10x is more than I expected. Looking forward to trying it out!
