### ISSUE TITLE
Error installing pgx/v4

### ISSUE THREAD

**Issue by yasirkk** [jackc/pgx#1020]
![image](https://user-images.githubusercontent.com/23183716/120596500-76dd0480-c461-11eb-91ae-aa6c0fae1635.png)
help me to resolve this issue

**Comment by segfault88** [comment]
Something else in your project is causing this. With a clean `go.mod` it doesn't pull in anything to do with mysql.

For example:
```
▶ go mod init test
go: creating new go.mod: module test

▶ go get -u github.com/jackc/pgx/v4
go get: added github.com/jackc/pgproto3/v2 v2.0.7
go get: added github.com/jackc/pgx/v4 v4.11.0
go get: added golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
go get: added golang.org/x/text v0.3.6
```

You can use `go mod why github.com/go-sql-driver/mysql` to see what is pulling that in. Probably you need to upgrade some other dependency to get a valid version of  `github.com/go-sql-driver/mysql`.
