### ISSUE TITLE
Context misuse on the pgxpool Query/QueryRow/Exec

### ISSUE THREAD

**Issue by shekhirin** [jackc/pgx#1021]
## Problem

All pool methods like `Query`/`QueryRow`/`Exec` basically consist of three steps:
1. Acquire connection from the pool
2. Execute a command on the connection
3. Release the connection to the pool

When we acquire the connection, we use the same `ctx` that was passed to the command method (e.g. `Query`)
https://github.com/jackc/pgx/blob/3ab89419216bcaf306c930ce291ef2b63000ba08/pgxpool/pool.go#L441-L442
, create a new connection if needed (https://github.com/jackc/puddle/blob/master/pool.go#L304)
```go
value, err := p.constructResourceValue(ctx)
``` 
and call constructor which is defined on the pgxpool's side. The problem is that in this constructor we use the same `ctx` as was passed to the command method
https://github.com/jackc/pgx/blob/3ab89419216bcaf306c930ce291ef2b63000ba08/pgxpool/pool.go#L188

## Why I think it's a problem

1. Server receives new HTTP request, creates a context for it and passes that context to the handler.
2. In the handler we query the database using pgxpool with request's context. It turns out there's no free connections in the pool, so pgxpool creates a new connection with the passed context and leaves it in the pool afterwards.
3. Server cancels the context (or it's canceled because of the timeout).
4. We have a connection in the pool that was created with the context that's cancelled now.

## Solution

Use different contexts for pool connections creation and database querying.

**Comment by segfault88** [comment]
Apologies if I misunderstand what you're saying but what you're saying can be summarised as:

- the context passed into `pool.Aquire` is eventually passed down to connect if there are no free connections in the pool
- this context could be later canceled (say if the current request fails) while the connection should remain valid
- once the pool conn is `Release`d another context should be able to `Aquire` and use it independently of the first context

It seems to me that the context passed to connect is only used for cancelation of the connect and isn't used or even saved after that is done.

https://github.com/jackc/pgconn/blob/fb42201c18fcd016c235d4b613f76b2fc1599588/pgconn.go#L110-L117

is the comment `ctx can be used to cancel a connect attempt`.

Then lower down in connect here: https://github.com/jackc/pgconn/blob/fb42201c18fcd016c235d4b613f76b2fc1599588/pgconn.go#L218 passes the ctx to DialFunc

then here:
https://github.com/jackc/pgconn/blob/fb42201c18fcd016c235d4b613f76b2fc1599588/pgconn.go#L232-L239
uses the context watcher to call `SetDeadline` to `time.Date(1, 1, 1, 1, 1, 1, 1, time.UTC))` that is cause I/O during authenticating to immediately timeout if the context is canceled.

So, it seems that if the context is not canceled during `Aquire` (and thus connect) the connection is not attached to the context any more. Does this make any sense?

**Comment by shekhirin** [comment]
Hi @segfault88! Thanks for you response.

Yep, you understood me totally correctly. Seems like you're right, I checked the `DialFunc` and it uses context only to establish the connection and doesn't keep it afterwards.

I think the issue can be closed now 🙂

**Comment by segfault88** [comment]
Thanks @shekhirin happy that made sense
