### ISSUE TITLE
CopyFrom timestamp conversion error : "COPY from stdin failed: cannot convert 2021-06-13 04:52:51 +0000 UTC to Timestamptz"

### ISSUE THREAD

**Issue by yuyang08** [jackc/pgx#1024]
I am trying to use pgConn.CopyFrom to improve data insertion throughput. The code is as follows:

	    numCopiedRows, err := pgConn.CopyFrom(context.Background(), pgx.Identifier{"metrics"}, []string{"time", "field1", "field2", "field3"},
		pgx.CopyFromRows(rows))

The program reported errors like below: 

         COPY from stdin failed: cannot convert 2021-06-13 04:52:51 +0000 UTC to Timestamptz

Any suggestion on how to solve the problem?  There was one post earlier that suggested to set "timezone=UTC" runtime parameter. I tried with the following code, and got the same error: 

      psqlInfo := fmt.Sprintf("host=%s port=%s user=%s dbname=%s sslmode=disable timezone=UTC",
		psqlHost, psqlPort, psqlUser, psqlDB)
      pgx.Connect(ctx, psqlInfo)

**Comment by yuyangverkada** [comment]
Did not realize that Timestamptz is defined as a struct in pgx. pgx works beautifully after putting the right encoding for CopyFrom.  Below is the code that I used to construct Timestamptz struct: 

		timeVal := pgtype.Timestamptz{Status: pgtype.Null}
		timeVal.Set(theTime)

**Comment by yuyang08** [comment]
Did not realize that Timestamptz is defined as a struct in pgx. pgx works beautifully after putting the right encoding for CopyFrom. Below is the code that I used to construct Timestamptz struct:

	timeVal := pgtype.Timestamptz{Status: pgtype.Null}
	timeVal.Set(theTime)

**Comment by gkotian** [comment]
Thanks for pointing out how to fix the problem, that was really helpful. I guess this issue can be closed, right?
