### ISSUE TITLE
CopyFromReader alternative in v4

### ISSUE THREAD

**Issue by siyopao** [jackc/pgx#1026]
Hello 👋 

I am just wondering how to use `CopyFrom` on a file. I noticed that there is a `CopyFromReader` in v3, but there doesn't seem to be in v4. Is there an alternative way to do this?

Thank you!

I am sorry if my question is silly. I am quite new to Go.

**Comment by jackc** [comment]
In v4, the core, low level functionality was split into the https://github.com/jackc/pgconn package. pgx is now implemented with that package. 

You want this method: https://pkg.go.dev/github.com/jackc/pgconn#PgConn.CopyFrom

You can get a `*pgconn.PgConn` from a `*pgx.Conn` with the `PgConn()` method.

**Comment by siyopao** [comment]
Hello @jackc!

Thank you for the reply! Oh, that's awesome. I'll give it a shot. At first I was worried I was going to implement `CopyFromSource` for `Reader`.

Thanks again, and also thank you for the nice library!
