### ISSUE TITLE
unexpected behavior 

### ISSUE THREAD

**Issue by dubrovine** [jackc/pgx#1034]
Couple of months I am trying to understand where is the issue 

application can work well for a weeks but than something happened and pg connections started growing until I reload the app

here is the avg connection graph

<img width="1650" alt="Снимок экрана 2021-06-29 в 09 38 40" src="https://user-images.githubusercontent.com/23291485/123749683-5d8f7280-d8be-11eb-93da-72524c44f740.png">

everything is ok (first arrow) and some unexpected behavior (second arrow)

_______________________________________________________

here is the requests graph 

![Снимок экрана 2021-06-29 в 09 44 25](https://user-images.githubusercontent.com/23291485/123749957-ac3d0c80-d8be-11eb-9568-60625d0f385d.png)

seems like everything is stable (like days before and days after)

_______________________________________________________

here is the pgx code

```
func poolConfig(config *config.Config) *pgxpool.Config {
	ConnString :=
		"user=" + config.Pgsql.User +
			" password=" + config.Pgsql.Password +
			" host=" + config.Pgsql.Host +
			" port=" + config.Pgsql.Port +
			" dbname=" + config.Pgsql.DbName +
			" pool_max_conns=" + config.Pgsql.PoolSize +
			" pool_min_conns=" + config.Pgsql.MinPoolSize
	cnf, _ := pgxpool.ParseConfig(ConnString)
	cnf.HealthCheckPeriod = 60*time.Second
	cnf.MaxConnIdleTime = 120*time.Second
	cnf.MaxConnLifetime = 120*time.Minute
	return cnf

}
```

p.s:
"poolSize": "200",
"minPoolSize": "75" 

(per container) - 2 containers in prod env

pgx vsn - **github.com/jackc/pgx/v4 v4.11.0**

could someone show me the right direction to fix this issue ?

**Comment by jackc** [comment]
Have you looked at the `pg_stat_activity` view to see if there is any pattern to what these extra connections are doing?

Given you have `MaxConnLifetime` set, the only way I know for a connection to permanently leak is if the `Rows` returned from `Query` are not closed. Possibly there is an error path that leaks a connection. `pg_stat_activity` would show the last query in this case.

Also, unless you have an unusual use case a min pool size of 75 is far too high. That is probably much higher than the number of active connections your PG server should be handling. See https://www.cybertec-postgresql.com/en/tuning-max_connections-in-postgresql/.

**Comment by dubrovine** [comment]
> Have you looked at the `pg_stat_activity` view to see if there is any pattern to what these extra connections are doing?
> 
> Given you have `MaxConnLifetime` set, the only way I know for a connection to permanently leak is if the `Rows` returned from `Query` are not closed. Possibly there is an error path that leaks a connection. `pg_stat_activity` would show the last query in this case.
> 
> Also, unless you have an unusual use case a min pool size of 75 is far too high. That is probably much higher than the number of active connections your PG server should be handling. See https://www.cybertec-postgresql.com/en/tuning-max_connections-in-postgresql/.

thank you for your reply
I will check `pg_stat_activity`  and return to you with some extra data

**Comment by dubrovine** [comment]
You are totally right !

I am not closing rows here :
`rows, err := pgpool.Query(ctx, db.SelectBetween, start, end, limit, offset)`

thank you
