### ISSUE TITLE
Boss, should we sort out the dependency of the project?

### ISSUE THREAD

**Issue by pobearm** [jackc/pgx#1036]
I use a simple tools, generate a dependency diagram of this project , it looks terrible.
Maybe you can try it, thank your job!

[graph.zip](https://github.com/jackc/pgx/files/6753642/graph.zip)

Tool: https://github.com/poloxue/modv

**Comment by paudley** [comment]
Personally, I find the actual (non-test) dependency graph to be small and reasonable. YMMV

Google just released a new tool that lets you explore this nicely as well:

https://deps.dev/go/github.com%2Fjackc%2Fpgx
