### ISSUE TITLE
Can't use an argument in query because of quotes

### ISSUE THREAD

**Issue by GinkT** [jackc/pgx#1043]
i have a query:

```
                SELECT 	uuid
		FROM sources 
		WHERE options ->> 'assignedTo' = '$1';
```

When i'm trying to QueryRow and specifying an argument, i'm getting an error.

```
conn.QueryRow(r.DbHandler.GetCtx(), query, userUuid).Scan(&source.Uuid)
```

Error:
```
expected 0 arguments, got 1
```

**Comment by jackc** [comment]
You don't need quotes when using argument placeholders.

**Comment by GinkT** [comment]
> You don't need quotes when using argument placeholders.

The problem is i can't user this query without quotes, for example:

this query works:
```
SELECT 	uuid
FROM sources 
WHERE options ->> 'assignedTo' = 'dc2b62e0-c95b-4eb6-b826-42b7601ec2f6';
```

not works (without quotes):
```
SELECT 	uuid
FROM sources 
WHERE options ->> 'assignedTo' = dc2b62e0-c95b-4eb6-b826-42b7601ec2f6;
```

**Comment by SkipUFO** [comment]
Hello
this
`'$1'`

is a string, not a parameter, and you see error: 
`expected 0 arguments, got 1`
when you set parameters you must use just $1, $2, ...

when you set parameter it will proceed into query behind the scenes by code of this package

**Comment by GinkT** [comment]
> Hello
> this
> `'$1'`
> 
> is a string, not a parameter, and you see error:
> `expected 0 arguments, got 1`
> when you set parameters you must use just $1, $2, ...
> 
> when you set parameter it will proceed into query behind the scenes by code of this package

The query doesn't work if i use WHERE options ->> 'assignedTo' = $1. It works only if i wrap my value in quotes

**Comment by SkipUFO** [comment]
`
r.HandleFunc("/set", set).Methods("POST")
r.HandleFunc("/get", get).Methods("GET")

func set(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	//	vars := mux.Vars(r)

	var tx pgx.Tx

	uuidXXX = generateUUID()

	tx, _ = dbFast.Begin(ctx)
	if _, err := tx.Exec(ctx, `INSERT INTO test.test (test) VALUES ('{"values": "`+uuidXXX+`"}'::jsonb)`); err != nil {

	}
	tx.Commit(ctx)
}

func get(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	//	vars := mux.Vars(r)

	var u string
	err := dbFast.QueryRow(ctx, `SELECT test FROM test.test WHERE test ->> 'values' = $1`, uuidXXX).Scan(&u)

	fmt.Println(u)
	fmt.Println(err)
}
`
this is my code
db code
`
CREATE TABLE IF NOT EXISTS test.test
(
    test jsonb
)

TABLESPACE pg_default;

ALTER TABLE test.test
    OWNER to postgres;
`

log: 
`
{"level":"info","ts":1626444551.2903595,"caller":"v4@v4.11.0/conn.go:420","msg":"Exec","sql":"begin","args":[],"time":27444911,"commandTag":"QkVHSU4=","pid":17065,"x-request-id":null}
{"level":"info","ts":1626444551.318461,"caller":"v4@v4.11.0/conn.go:420","msg":"Exec","sql":"INSERT INTO test.test (test) VALUES ('{\"values\": \"af6089de-323c-40b0-b29b-289464f3b021\"}'::jsonb)","args":[],"time":27730944,"commandTag":"SU5TRVJUIDAgMQ==","pid":17065,"x-request-id":null}
{"level":"info","ts":1626444551.3492045,"caller":"v4@v4.11.0/conn.go:420","msg":"Exec","pid":17065,"sql":"commit","args":[],"time":30611029,"commandTag":"Q09NTUlU","x-request-id":null}
{"level":"info","ts":1626444552.874878,"caller":"v4@v4.11.0/rows.go:146","msg":"Query","rowCount":1,"pid":17065,"sql":"SELECT test FROM test.test WHERE test ->> 'values' = $1","args":["af6089de-323c-40b0-b29b-289464f3b021"],"time":56078128,"x-request-id":null}
{"values": "af6089de-323c-40b0-b29b-289464f3b021"}
<nil>
`

pgx version
`
github.com/jackc/pgx/v4 v4.11.0
`

**Comment by obitech** [comment]
I think I'm running into the same issue here, while trying to update a value via `jsonb_set`:

```
		UPDATE
			myTable
		SET
			data = jsonb_set(data, '{Foo,Bar}, $2')
		WHERE
			id=$1
```

Where `$1` is a string and `$2` is a bool, I'll get an error:

```
ERROR:  inconsistent types deduced for parameter $2 at character 166
DETAIL:  jsonb versus boolean
```

I've tried an explicit cast via `data = jsonb_set(data, '{Foo,Bar}', $2::jsonb)` which yields the same error. 

Enclosing it in quotes like `data = jsonb_set(data, '{Foo,Bar}', '$2')` will yield:

```
ERROR:  invalid input syntax for type json at character 227
DETAIL:  Token "$" is invalid.
```

Am I using it wrong?

I've hacked it without the parameter via `fmt.Sprintf`ing the query and setting  `data = jsonb_set(data, '{Foo,Bar}', '%t'`

**Comment by jackc** [comment]
Parameter substitution doesn't occur inside of string literals. This is a PostgreSQL level thing. You can experiment with this by using `psql` and doing `prepare` and `execute` statements. You will need to either `fmt.Sprintf` the entire the argument or use something like `jsonb_build_array`.

**Comment by Sitin** [comment]
This definitely should be documented. Our common sense tells that parameters should be substituted. That's it. If there is a good reason for changing this behaviour and introducing some magic, it should be explicitly mentioned in documentation.

**Comment by jackc** [comment]
> This definitely should be documented. Our common sense tells that parameters should be simply substituted. That's it. If there is a good reason for changing this behaviour, it should be explicitly mentioned in documentation.

This isn't pgx behavior. This is PostgreSQL behavior.

```
jack=# prepare s as select '$1 + $2' as a, $1 as b, $2 as c;
PREPARE
jack=# execute s(1,2);
    a    | b | c
---------+---+---
 $1 + $2 | 1 | 2
(1 row)
```

`a` is `$1 + $2` not `3`.
