### ISSUE TITLE
[Question] Is there a way to read *pgconn.ResultReader concurrently ?

### ISSUE THREAD

**Issue by flowHater** [jackc/pgx#1044]
Hello,
Currently I'm doing a ugly copy of `Values` to read them from an other goroutine, because without copy, `Values` are mutated. I think I miss something in documentation but can't figure out a way to read Result concurrently.
```
	bsonCh := make(chan *Row)
	go func() {
		defer close(bsonCh)
		rows := conn.Exec(ctx, fmt.Sprintf(QUERY, schema, table))

		for rows.NextResult() {
			fmt.Println("start reading")
			for rows.ResultReader().NextRow() {
				br := Row{
					FieldDescriptions: rows.ResultReader().FieldDescriptions()[:],
					Schema:            schema,
					Table:             table,
				}
				v := rows.ResultReader().Values()

				for i := range rows.ResultReader().Values() {
					br.Values = append(br.Values, v[i][:])
				}
				bsonCh <- &br
			}
		}
	}()
```

My use case is, i have to read all rows from many tables (that's why `conn.Exec(ctx, fmt.Sprintf(QUERY, schema, table))`) and do some serialization into Bson to write it in disk. serialization to Bson can be heavy i wanna use concurrency to speedup the process. And I have to do special `Scan` for `OID` Json/jsonb. So I'm writing in my chan `bsonCh` and process it in a Worker poll after.

**Comment by flowHater** [comment]
I have to specify, that just before using Pgx/pgconn, I was using `psql` by using a `psql -f myfile.sql | go run main.go` that was faster, because I could Scan `os.Stdin` and dispatch rows to my workers that were doing all the serialization job. But now, i have to copy a lot a data (`Values`) to go through the channel in a single Goroutine. Workers are under-pressurized  using only 40/50% of CPU.

**Comment by jackc** [comment]
No, as you noticed `Values` is only valid until the next call of `NextRow`. I don't know just how slow `bson` is in comparison, but I expect that a channel operation per row is going to be fairly expensive.

If your existing code was designed to simply parse text then you may find that https://pkg.go.dev/github.com/jackc/pgconn#PgConn.CopyFrom is more suited to your use case.

**Comment by flowHater** [comment]
Noticed, yeah 😄 .
Have to say, it's more https://pkg.go.dev/github.com/jackc/pgconn#PgConn.CopyTo in my case. I have to read data from Postgres and transform it to Bson/mongodb.
So I tried your tips by using  `PgConn.CopyTo`. But I have a remaining question, about the `io.Writer` that I have to pass as 2nd parameter, how can I wait that the Conn is writing on my `io.Writer` to start reading it.
```golang
func main() {
	ctx := context.Background()
	pg, err := pgconn.Connect(ctx, "")
	if err != nil {
		log.Fatalln(err)
	}

	buffer := &bytes.Buffer{}
	go func() {
		_, err = pg.CopyTo(ctx, buffer, `copy (select * from big_schema.big_table) to stdout;`)
		if err != nil {
			log.Fatal(err)
		}
	}()

	scanner := bufio.NewScanner(buffer)
	fmt.Println("start to scan")
	for scanner.Scan() {
		fmt.Println(scanner.Text())
	}
}
```
As you can see, I have to `go func() {} ()` the part of `CopyTo` because it's a blocking function.
Without the `go func() {} ()` I have to wait the query end to start scan.
But if you run the snippet above,  you will see that the `scanner.Scan()` don't wait that actual data are written on the buffer.
I can get this to work, by using `time.Sleep(time.Second)` just after the `go func() {} ()`. With this way, the `PgConn` can start receiving data before the end of the `Sleep`. So my `Scan` is working asynchronously.
But I think you may suggest something far more better than that.
In your tests I can only find case where `CopyTo` is used as blocking and, no test read asynchronously from it.
So maybe, it's a missed use case and so we can imagine something like:
`func (pgConn *PgConn) CopyToChan(ctx context.Context, ch chan []byte, sql string) (CommandTag, error)`.
It's maybe more expensive to use, but can fit perfectly with my use case, and can be a similar implementation with the current `CopyTo`. Actually, only the line https://github.com/jackc/pgconn/blob/13d454882b790b8a8fa00e049e9dc2c0e84318fc/pgconn.go#L1144 have to change. As I can see.
I cannot do it on my own, because `PgConn.lock` is unexposed, same for `PgConn.receiveMessage()` etc..
Maybe it's out of scope of this issue, I think it's not the good place.
We can be maybe discuss in `jackc/pgconn`, as you want. Initially, I started here because the visibility of `jackc/pgx` is far better.  So I though that maybe someone else than you can answer to my request.

**Comment by jackc** [comment]
I think https://pkg.go.dev/io#Pipe instead of `bytes.Buffer` would solve the issue.

**Comment by flowHater** [comment]
Oh nice, pretty neat. Thanks, that works perfectly.
But, I can't reach the same performance with `pgconn.CopyTo` and `os.Pipe` instead of  `exec("psql")`. For same data, same request. It's about 10 secs over 2mins of process. My whole process with `psql` take 1mins50 ~1sec and with `pgconn.CopyTo` it's about 2min02 ~2secs. I ran many times, it's pretty stable.

What I'm using around `pgconn.CopyTo`:
```golang
func readTable(schema, table string) io.ReadCloser {
	ctx := context.Background()
	pg, close := newConn()

	reader, writer := io.Pipe()
	go func() {
		defer close(pg)
		defer writer.Close()
		_, err := pg.CopyTo(ctx, writer, fmt.Sprintf(QUERY, schema, table))
		if err != nil {
			log.Fatal(err)
		}
	}()

	return reader
}
```
And what I'm currently using around `psql`:
```golang
func psql(s string, vars ...string) (io.ReadCloser, io.ReadCloser, func()) {
	args := []string{"-tAq"}
	if strings.HasSuffix(s, ".sql") {
		args = append(args, "-f", s)
	} else {
		args = append(args, "-c", s)
	}

	for _, v := range vars {
		args = append(args, "-v", v)
	}

	cmd := exec.Command("psql", args...)
	cmd.Env = os.Environ()
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		log.Fatal(err)
	}

	stderr, err := cmd.StderrPipe()
	if err != nil {
		log.Fatal(err)
	}

	if err := cmd.Start(); err != nil {
		log.Fatal(err)
	}

	return stdout, stderr, func() {
		if err := cmd.Wait(); err != nil {
			log.Fatalf("cmd.Wait(): %s\n", err)
		}
	}
}
```
As you can see, I get an `io.ReaderCloser` from both function, and use the same way to read them both. Which use https://pkg.go.dev/bufio#Reader.ReadLine to read big lines, many MB sometimes.

**Comment by jackc** [comment]
Huh. Not really sure what's going on there. The `CopyTo` is a pretty thin wrapper over reading directly from the network connection. If anything I would expect that with an `io.Pipe` to be faster because it does not involve any inter-process communication (IPC) like shelling out to psql does.

If I had to guess I would say it is something to do with the internal buffer sizes used by the pipe and by IPC -- especially with your extremely long lines. But that's really just a guess. You'd need to do some profiling to know for sure.

**Comment by flowHater** [comment]
I saw, I read your code and cannot understand what's going on. I'll profile and report on a new issue if I find something. For now we can close this one.
Thank you for your neat project and your useful help.
