### ISSUE TITLE
Execute statement without transaction block

### ISSUE THREAD

**Issue by dustyhoppe** [jackc/pgx#1047]
Is there support for executing a statement/batch without doing so within a transaction block.

When attempting to create an index concurrently, the following error is thrown. Any guidance would be much appreciated.
 
`ERROR: CREATE INDEX CONCURRENTLY cannot run inside a transaction block (SQLSTATE 25001)`

**Comment by jackc** [comment]
Yes... that is the default. There are only transactions when you explicitly request them.

However, my guess is you are sending a single string with multiple SQL statements. In that case PostgreSQL wraps it in an implicit transaction. Try sending your `CREATE INDEX CONCURRENTLY` statement by itself.

**Comment by dustyhoppe** [comment]
Thanks @jackc. Your guess was correct and I have a work around now. Appreciate the quick response here.
