### ISSUE TITLE
*pgx.connLockError using BeingTxFunc but not Query

### ISSUE THREAD

**Issue by kylelemons** [jackc/pgx#1048]
I feel like this is likely user error, but I can't figure out what I am doing wrong.  This is a very simple app that is just running a single query in main to stuff some test data in the database (for use in a kubernetes init container for an integration test), and all of the discussion around this error that I can find is related to concurrent use of a *pgx.Conn.  I tried to switch to a pgxpool and it has the same issue.

This code works just fine:

```go
func works(ctx context.Context, pool *pgxpool.Pool) error {
	conn, err := pool.Acquire(ctx)
	if err != nil {
		return fmt.Errorf("acquire conn: %w", err)
	}
	defer conn.Release()

	if _, err := conn.Query(ctx, `
			INSERT INTO mytable
				(id, data)
			VALUES
				($1, $2)
			ON CONFLICT (id)
				DO UPDATE SET data = $2
		`, 1234, testJSON); err != nil {
		log.Printf("Error in query: %v", err)
		return fmt.Errorf("inserting into database: %w", err)
	}
	return nil
}
```

However, if I run this in a transaction, I get a `*pgx.connLockError` ("conn busy"):

```go
func fails(ctx context.Context, pool *pgxpool.Pool) error {
	conn, err := pool.Acquire(ctx)
	if err != nil {
		return fmt.Errorf("acquire conn: %w", err)
	}
	defer conn.Release()

	return conn.BeginTxFunc(ctx, pgx.TxOptions{
		IsoLevel:   pgx.ReadCommitted,
		AccessMode: pgx.ReadWrite,
	}, func(tx pgx.Tx) error {
		if _, err := tx.Query(ctx, `
			INSERT INTO mytable
				(id, data)
			VALUES
				($1, $2)
			ON CONFLICT (id)
				DO UPDATE SET data = $2
		`, 1234, testJSON); err != nil {
			log.Printf("Error in query: %v", err)
			return fmt.Errorf("inserting into database: %w", err)
		}
		return nil
	})
}
```

I also don't have any issues if I use the `stdlib` package to run the equivalent code in a transaction, though it doesn't have the same convenient `BeginTxFunc` wrapper afaict.

If it helps, the logs for the `fails` code look like this:

```
2021/07/20 11:18:28 Acquired conn
2021/07/20 11:18:29 [info] Exec
2021/07/20 11:18:29 ... "pid" = (uint32) 20252
2021/07/20 11:18:29 ... "sql" = (string) begin isolation level read committed read write
2021/07/20 11:18:29 ... "args" = ([]interface {}) []
2021/07/20 11:18:29 ... "time" = (time.Duration) 90.188255ms
2021/07/20 11:18:29 ... "commandTag" = (pgconn.CommandTag) BEGIN
2021/07/20 11:18:29 [error] Exec
2021/07/20 11:18:29 ... "pid" = (uint32) 20252
2021/07/20 11:18:29 ... "sql" = (string) commit
2021/07/20 11:18:29 ... "args" = ([]interface {}) []
2021/07/20 11:18:29 ... "err" = (*pgconn.connLockError) conn busy
2021/07/20 11:18:29 [info] closed connection
2021/07/20 11:18:29 ... "pid" = (uint32) 20252
```

Versions:
```txt
go version go1.16.5 darwin/amd64
github.com/jackc/pgx/v4 v4.12.0
PostgreSQL 12.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
```

Is there something I am missing about correct usage of `BeginTxFunc`?

**Comment by jackc** [comment]
You need to read the results of `Query`. The connection is busy when `BeginTxFunc` tries to commit or rollback because the `Query` is still in progress.

But in your particular example you probably want to call `Exec` instead. Also, you might want to call `BeginTxFunc` directly on the pool instead of manually checking out and releasing a connection.

**Comment by arpanetus** [comment]
> You need to read the results of `Query`. The connection is busy when `BeginTxFunc` tries to commit or rollback because the `Query` is still in progress.
> 
> But in your particular example you probably want to call `Exec` instead. Also, you might want to call `BeginTxFunc` directly on the pool instead of manually checking out and releasing a connection.

It would be nice to have QueryFunc for BatchResults

**Comment by jackc** [comment]
> It would be nice to have QueryFunc for BatchResults

I agree. Done in 38cd1b40aab7244bd3d593d5153619e03b09edca.
