### ISSUE TITLE
Apache AGE - Query returns no rows

### ISSUE THREAD

**Issue by uriaash** [jackc/pgx#1053]
I'm trying to return graph data using the "age" extension (https://age.apache.org/) but no rows seem to be returned from the `Query` method. I verified that a regular select works.
Perhaps the special `agtype` type is not supported by the driver?

My code:
`rows, err := conn.Query(context.Background(), "SELECT * from cypher('graph1', $$ match (b:Book) return b $$) as (a agtype);")`

**Comment by jackc** [comment]
Unknown types should be returned in the text. Can you verify your Go query code works with another simple SQL statement?
