### ISSUE TITLE
RowsAffected, update

### ISSUE THREAD

**Issue by alifpay** [jackc/pgx#1059]
How to get reason of no rows affected? why not updated?

errors is nil.
but
RowsAffected() !=1

**Comment by alifpay** [comment]
c, err := d.conn.Exec(ctx, "updateSql", status, respid, errCode, errStr, id)
	if err != nil {
		return err
	}

	if ra := c.RowsAffected(); ra != 1 {
		return errors.New(c.String())
	}


is it correct?

**Comment by jackc** [comment]
PostgreSQL doesn't supply a reason why no rows are affected. It only tells you how many were affected.

Because it really can't. e.g.

```sql
update users set active = true where 1 = 0;
````

No rows will be affected. But there is no way PostgreSQL could give you a meaningful reason.
