### ISSUE TITLE
What is the correct way to implement the pgxpool function?

### ISSUE THREAD

**Issue by curiosport** [jackc/pgx#1064]
I don't remember which tutorials I followed but basically to use pgxpool this code works (it is quite simplified and just enough to get the idea across):

```
package util

import "github.com/jackc/pgx/v4/pgxpool"

func CustomConnect() (*pgxpool.Pool) {
  DATABASE_URL := "postgres://useradmin:password@localhost:5432/databasename?sslmode=verify-ca&pool_max_conns=10"
  config, _ := pgxpool.ParseConfig(DATABASE_URL)
  conn, _ := pgxpool.ConnectConfig(context.Background(), config)
  return conn
}
```

```
package main

import (
  "util"
  //...other libraries
)

func main() {
  conn := util.CustomConnect()
  defer conn.Close()
  //...intructions with conn
}
```

My doubt is with the line "**defer conn.Close()**" Isn't the pooling technique supposed to be used to conserve connections and not have to create new ones? then why would you want to close the connection? I thought the idea (instead of "Close()") was to free the resources and use the same connection for the next request.

I would appreciate any information, I am not sure which function I should use instead of "Close()" or if indeed everything is well implemented and pgx does the rest automatically.

**Comment by curiosport** [comment]
That's the question, I don't want to close the whole pool, so I just don't want to use Close(), but then the connection management is manual or automatic? If it is manual what function should I use when I finish the task of a connection? or should I do nothing more than just reuse the connections?

**Comment by jackc** [comment]
Connection management is automatic. Just call `Query`, `Exec`, `Begin`, etc. directly on the pool.

**Comment by curiosport** [comment]
So in the code I have shown I should only call "CustomConnect()" once and do the rest of the work with "conn" regardless if requests come from several clients? correct?

**Comment by jackc** [comment]
Yes. Though again, I would not call a `*pgxpool.Pool` `conn`.

**Comment by curiosport** [comment]
Ok, thanks for everything, and I will change the variable name to `dbpool` to avoid those confusions.

**Comment by G2G2G2G** [comment]
>Yes. Though again, I would not call a *pgxpool.Pool conn.


https://pkg.go.dev/github.com/jackc/pgx/v4@v4.13.0/pgxpool#Config
@jackc but you call all of the pool configs conns right? It is very confusing, upon initial look it seems it is talking about the individual conns per pool, but these are actually pools not conns..

**Comment by jackc** [comment]
> @jackc but you call all of the pool configs conns right? It is very confusing, upon initial look it seems it is talking about the individual conns per pool, but these are actually pools not conns..

I don't know what you mean.
