### ISSUE TITLE
Convert pgxpool conn to stdlib connection

### ISSUE THREAD

**Issue by aranw** [jackc/pgx#1065]
I was wondering if it's possible to convert a pgxpool Conn into a `*sql.DB` to pass to other libraries that don't support pgx or pgxpool?

**Comment by jackc** [comment]
No. But it can work the other way. You can use https://pkg.go.dev/database/sql#Conn.Raw to go from `*sql.Conn` to `*pgx.Conn`.

**Comment by aranw** [comment]
Ah I was really hoping to go from `pgxpool` to `sql.DB` as I want to use `pgxpool` as my main connection pool management and then pass `sql.Conn/DB` into libraries that don't support pgx properly. I've noticed odd behaviour with the default `database/sql` pooling

**Comment by milkiweed** [comment]
this issue is still relevant for me, the solution has not been found yet?

**Comment by owenthereal** [comment]
Any progress on this? I want to pass around the pgxpool object for queries but some libraries only work with *sql.DB

**Comment by owenthereal** [comment]
One solution is that we allow creating a *sql.DB from a pgxpool in stdlib

**Comment by RohanNg** [comment]
This PR [1] remove the ability to convert from pgxpool to sql.DB. Do we have any context into why it was removed?
[1] https://github.com/jackc/pgx/commit/ffae1b134596a9a111fdb89b1bd09febad7e2dae

**Comment by jackc** [comment]
It worked, but there were a lot of confusing edges with having two pools managing one set of connections. e.g. If both pools had the same number max connections then if the `*sql.DB` acquired all of them then the pgxpool would be starved of connections.

If the pgxpool to `*sql.DB` feature was to be resurrected it would probably make sense to limit the `*sql.DB` to a single connection. The API would be more like the pool's `Acquire()` / `Release()` only it would acquire and release a `*sql.DB` instead of a `*pgxpool.Conn`. i.e. It would explicitly be designed for a short lifetime.

**Comment by yufan-xue** [comment]
> No. But it can work the other way. You can use https://pkg.go.dev/database/sql#Conn.Raw to go from `*sql.Conn` to `*pgx.Conn`.

I tried the method, but it doesn't work and failed silently...
```
err := conn.Raw(func(driverConn interface{}) error {
  pgxConn, ok := driverConn.(*pgx.Conn)
  if !ok {
    return fmt.Errorf("super bad, expected a *pgx.Conn, but have %T", driverConn)
  }
  do thing with pgxConn   
})
``` @jackc

**Comment by jackc** [comment]
From the package docs -- https://pkg.go.dev/github.com/jackc/pgx/v4/stdlib.

```go
// Given db is a *sql.DB
conn, err := db.Conn(context.Background())
if err != nil {
	// handle error from acquiring connection from DB pool
}

err = conn.Raw(func(driverConn interface{}) error {
	conn := driverConn.(*stdlib.Conn).Conn() // conn is a *pgx.Conn
	// Do pgx specific stuff with conn
	conn.CopyFrom(...)
	return nil
})
if err != nil {
	// handle error that occurred while using *pgx.Conn
}
```

**Comment by StevenACoffman** [comment]
If it helps, our use case is different from what was assumed.

When our app starts up, we inject a pgxpool, which has a specific set of max database connections configured. 

At app startup, we detect if the schema migrations have been performed and autoupdate them (typically on a local developer machine, not in prod). However, the schema migrations tool (golang-migrate) requires a `*sql.DB` and we are stuck with a `pgx/v5/pgxpool` that cannot be converted.

Workaround for now is to reorder things so we first create `*sql.DB`, auto-migrate, close `*sql.DB`, and then create  `pgx/v5/pgxpool`.  That way we don't have a `*sql.DB` and a `*pgx/v5/pgxpool.Pool` at the same time eating double the max connections.

**Comment by bodokaiser** [comment]
This feature is really important!

We need to implement tracing (via pgx) but cannot because we use entgo, which requires a `*sql.DB`.

**Comment by redbaron** [comment]
Exposing pgxpoool as `*sql.DB` could help us as well. Thinking about it, it can be done reliably if `database/sql` doesn't try to maintain internal pool, that is max idle connections is set to 0  , max open cons to infinity and ignoring all other options (max lifetime, max idle time).  It should probably be implemented by a small `pgxpool://` driver which wraps pool and translates [Conn.Close](https://pkg.go.dev/database/sql#Conn.Close) to [Release](https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#Conn.Release)

**Comment by jackc** [comment]
>  Thinking about it, it can be done reliably if database/sql doesn't try to maintain internal pool, that is max idle connections is set to 0 , max open cons to infinity and ignoring all other options (max lifetime, max idle time).

That might be workable. I think the previous implementation of this feature predated database/sql exposing those knobs.

**Comment by kcgopal** [comment]
I haven't gone through the internal working fo pgxpool.  As per my understanding "Acquire" allots one entry from pool and marks it as unavailable and "Release" gives the resource back to the pool.  If that is the case Isn't it possible to have couple more function in pgxpool which is like Aquire & Release, but returns and releases *sql.DB from pool.  That way your concern about too pool managing one set of connections won't be there as the pgxpool will be in control of allocating  for both.

**Comment by lzakharov** [comment]
@redbaron literally now I'm implementing a similar scheme and so far it looks like a workable option. Just changed this [driver.Connector implementation](https://github.com/jackc/pgx/blob/master/stdlib/sql.go#L199) to work with `*pgxpool.Pool`. The only thing I don't like is the inability to return the correct `DBStats` from the pool `*sql.DB`, but it doesn't look like a problem, at least in my case.

**Comment by lzakharov** [comment]
@redbaron yeap, or it can also be added directly to the `pgx/v5/stdlib` with constructor like `OpenDBFromPool`. I'll try to provide this implementation soon.

**Comment by zcubbs** [comment]
this feature is a must!

**Comment by Estebmaister** [comment]
I'm having a similar issue when trying to use golang-migrate with pgx, is there a known fix for this?

**Comment by gluck1986** [comment]
guys, i'v found this 
```go
sql.OpenDB(stdlib.GetConnector(*pool.Config().ConnConfig))
```

**Comment by SimonWoidig** [comment]
> guys, i'v found this
> 
> sql.OpenDB(stdlib.GetConnector(*pool.Config().ConnConfig))

Even better would be to use:
```go
sql.OpenDB(stdlib.GetPoolConnector(pool))
```

**Comment by gonnafaraway** [comment]
github.com/jackc/pgx/v5/stdlib

pgxstdlib.GetPoolConnector(pool)
