### ISSUE TITLE
Scanning hierarchy based data into struct

### ISSUE THREAD

**Issue by Technerder** [jackc/pgx#1067]
I'm trying to retrieve comments from a database into a struct similar to this:
```go
type Comment struct {
	ID       string `db:"id"`
	Text     string `db:"text"`
	ParentID string `db:"parent_id"`
	Replies  []Comment
}
```

Does pgx support scanning child comments like mine recursively into a struct like this, and if so how?

**Comment by jackc** [comment]
If you mean automatically loading records from another table, then no, pgx does not have any ORM functionality.

**Comment by Technerder** [comment]
Oh sorry, I should've mentioned that the children are stored in the same table, where the child's ``parent_id `` is the parrent's ``id``
