### ISSUE TITLE
refactoring from pq to pgx

### ISSUE THREAD

**Issue by nitzanb-jfrog** [jackc/pgx#1068]
Hi, 
During my process of refactoring pq usages to pgx it all went pretty smooth apart of one thing, I'll be grateful if you can help.
Part of our code is migrating between mongo and postgres, using a dump to csv files and then copy command with these into postgres. 
In the past we've used psql to do so but using pq we've managed to make it a native golang process (no need for psql installed on the machine).
Using pq.CopyIn I was able to load csv files into postgres record by record with a csv reader + prepared statement (wanted to avoid reading it all into the memory), I did manage to do the same using your interface CopyFromSource:

```
type copyFromCSV struct {
	record []string
	reader *csv.Reader
	done   bool
	err    error
}

func (cp *copyFromCSV) Err() error {
	return cp.err
}

func (cp *copyFromCSV) Next() bool {
	cp.readNext()
	return !cp.done
}

func (cp *copyFromCSV) Values() ([]interface{}, error) {
	values := make([]interface{}, len(cp.record))
	for i, value := range cp.record {
		values[i] = value
	}
	return values, cp.err
}

func (cp *copyFromCSV) readNext() {
	if !cp.done {
		cp.record, cp.err = cp.reader.Read()
		cp.done = cp.err != nil
		if cp.err == io.EOF {
			cp.err = nil
		}
	}
}
```

My problem now is columns type conversions which pq handled for us, the loaded record from the csv comes as string, then I get lots of encoding errors running this migration process.

Thanks for your time!

**Comment by jackc** [comment]
If the CSV is such that you could use it directly in psql then you probably want to drop down to the pgconn level and use https://pkg.go.dev/github.com/jackc/pgconn#PgConn.CopyFrom. It will let you pipe copy data directly to the server.
