### ISSUE TITLE
[Feature Request] Define & Implement MarshalJSON for all type

### ISSUE THREAD

**Issue by AubSs** [jackc/pgx#1071]
Hi!

Since v5 is coming, can we discuss about implementing MarshalJSON for all type ? (Daterange, etc..)

Thx!

**Comment by jackc** [comment]
I'm open to this, but there is the issue of what the proper JSON format should be. pgtype has a design goal of being able to losslessly handle PostgreSQL values. This means supporting things like infinity, arrays that start at arbitrary indexes, etc. I suppose the natural thing would be to do what PostgreSQL does in `to_json`,  but PostgreSQL itself doesn't losslessly convert to json.

```
jack@[local]:5432 jack=# select to_json('[4:5][-2:1]={{1,2,3,4},{4,5,6,7}}'::int[]);
        to_json
───────────────────────
 [[1,2,3,4],[4,5,6,7]]
(1 row)
```

**Comment by jackc** [comment]
Okay, so if this is to be done it should:

1. Match PostgreSQL `to_json` behavior.
2. Document that it can be a lossy operation.

I think this would be fine, but I don't think that I will personally be tackling it. If someone else wants to tackle it - take a look at the `pgx-v5` branch on the pgtype repo.
