### ISSUE TITLE
[Feature Request] Add utilities on types

### ISSUE THREAD

**Issue by AubSs** [jackc/pgx#1072]
Hi!

Since v5 is coming, is it acceptable to add utilities on types ? (or at least discuss about it)
Like for daterange:
- pgtype.daterange.IsIn(date pgtype.Date): bool
- InOut(*): bool
- Overlap(*): bool
- ...

I think, well defined utilities are something a lot of users would appreciate, and since these functions only work with pgtype, there might be directly  included in pgx.

**Comment by jackc** [comment]
This brings up a bit of a question of the design goal of pgtype. Up to this point pgtype has been focused on losslessly decoding PostgreSQL types and converting to and from other Go types. In general, the types are used to carry data around, but no processing is done on them. Making these types useful beyond type conversion has not been a goal (#1071 also falls into this a little). In my applications it's very rare that I use them directly at all. They are used to convert to more useful Go types.

The problem with adding more functionality to these types is the Go type system and the PostgreSQL type system is quite different. 

I agree that ranges in particular would be useful to have Go side functions for, but even in your first example there are a number of difficulties. What if the date argument is a `NULL`? SQL says the result should be `NULL`, but Go could only return true. Or what if the daterange itself is `NULL`?

And the natural next step would be to have utility functions support normal Go types (e.g. `IsIn(time.Time)`). But Go doesn't support function overloading.

I think it would make more sense to keep pgtype focused strictly on transcoding values. A separate range package could be pretty useful though.

**Comment by jackc** [comment]
> If the idea of creating a separate repo is accepted, I’m willing to draft an RFC.

Go for it. It's all open source, it's not like you need anyone's permission to start a related project.
