### ISSUE TITLE
plugin: plugin was built with a different version of package

### ISSUE THREAD

**Issue by tfmeneses** [jackc/pgx#1076]
# go version
go version go1.15.1 linux/amd64

# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/go/kuiper/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build545065186=/tmp/go-build -gno-record-gcc-switches"

Main program should load plugin.so successfully.
I could not understand why it fails even though the referenced package version is same between main program and plugin.
Am I using plugin in wrong way?

[timescale.go.txt](https://github.com/jackc/pgx/files/7079095/timescale.go.txt)

`
cd /go/pkg/mod/github.com/jackc/pgx/v4@v4.13.0
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/b115/_pkg_.a -trimpath "$WORK/b115=>;/go/pkg/mod/github.com/jackc/pgx/v4@v4.13.0=>github.com/jackc/pgx/v4@v4.13.0" -dynlink -p github.com/jackc/pgx/v4 -lang=go1.13 -complete -installsuffix dynlink -buildid kukfhMl3Nd1Gaibgn5Z3/kukfhMl3Nd1Gaibgn5Z3 -goversion go1.15.1 -D "" -importcfg $WORK/b115/importcfg -pack ./batch.go ./conn.go ./copy_from.go ./doc.go ./extended_query_builder.go ./go_stdlib.go ./large_objects.go ./logger.go ./messages.go ./rows.go ./tx.go ./values.go
/usr/local/go/pkg/tool/linux_amd64/buildid -w $WORK/b115/_pkg_.a # internal
cp $WORK/b115/_pkg_.a /root/.cache/go-build/16/16457b14d571d9dc64da219bf7c0535b9cf9d9a6560065d86eb0724cdcb71f59-d # internal
mkdir -p $WORK/b041/
cat >$WORK/b041/importcfg << 'EOF' # internal
# import config
packagefile context=$WORK/b002/_pkg_.a
packagefile fmt=$WORK/b031/_pkg_.a
packagefile github.com/jackc/pgconn=$WORK/b042/_pkg_.a
packagefile github.com/jackc/pgproto3/v2=$WORK/b097/_pkg_.a
packagefile github.com/jackc/pgx/v4=$WORK/b115/_pkg_.a
packagefile github.com/jackc/puddle=$WORK/b121/_pkg_.a
packagefile runtime=$WORK/b007/_pkg_.a
packagefile strconv=$WORK/b030/_pkg_.a
packagefile sync=$WORK/b013/_pkg_.a
packagefile time=$WORK/b016/_pkg_.a
EOF
cd /go/pkg/mod/github.com/jackc/pgx/v4@v4.13.0/pgxpool
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/b041/_pkg_.a -trimpath "$WORK/b041=>;/go/pkg/mod/github.com/jackc/pgx/v4@v4.13.0/pgxpool=>github.com/jackc/pgx/v4@v4.13.0/pgxpool" -dynlink -p github.com/jackc/pgx/v4/pgxpool -lang=go1.13 -complete -installsuffix dynlink -buildid a-GxvcqQeZlYp3LIa_hy/a-GxvcqQeZlYp3LIa_hy -goversion go1.15.1 -D "" -importcfg $WORK/b041/importcfg -pack ./batch_results.go ./conn.go ./doc.go ./pool.go ./rows.go ./stat.go ./tx.go
/usr/local/go/pkg/tool/linux_amd64/buildid -w $WORK/b041/_pkg_.a # internal
cp $WORK/b041/_pkg_.a /root/.cache/go-build/8f/8f3d3dfe69250b8187293ae523fd4d94e92210dc14bd989d7d9f89dd06fcc9fc-d # internal
`

**Comment by jackc** [comment]
No idea. pgx doesn't use plugin, and I haven't personally used Go plugins on anything else either.

**Comment by tfmeneses** [comment]
Sorry,

It wasn't an issue of pgx. The problem was with go modules when I use with LF-Kuiper (stream alaytic). 

Thank you.
