### ISSUE TITLE
pgxpool is auto scalable?

### ISSUE THREAD

**Issue by curiosport** [jackc/pgx#1077]
In this configuration:
`DATABASE_URL := postgres://useradmin:password@localhost:5432/databasename?sslmode=verify-ca&pool_max_conns=10`

I understand that a connection to the database is generated and that connection will be used throughout the program, but what would happen if the `pool_max_conns` variable would increase to `10000`?

I did that and according to psql there is only one connection to the database, so if 10000 users make requests to the page it is obvious that one connection will noyht be enough and this is where my doubt comes in, pgxpool will generate new connections to the database to satisfy the demand? or it will continue using the only connection it has created at the beginning?

In the latter case I get the idea that I should create an array with several independent pgxpool items and access any of them that are available, if so, is each pgxpool connection still concurrency-safe?

I don't have the resources now to do this test and confirm it myself so I would appreciate any information.

**Comment by jackc** [comment]
pgxpool will automatically create and destroy connections as needed.

**Comment by curiosport** [comment]
Please confirm if I understood correctly: A single instance of pgxpoool will create more than one connection to the DB even more than a hundred connections when needed?

**Comment by jackc** [comment]
It can. See https://pkg.go.dev/github.com/jackc/pgx/v4@v4.13.0/pgxpool#Config for how to configure min and max pool size.
