### ISSUE TITLE
Scanning CITEXT into a sql.NullString causes spurious Valid: true

### ISSUE THREAD

**Issue by carlmjohnson** [jackc/pgx#1078]
Given a table like

```sql
CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE test (
    mytext citext
);
INSERT INTO test (mytext)
  VALUES (NULL);
```

And some query code to scan it into an sql.NullString like:

```go
func Test(ctx context.Context, db DBTX) ([]sql.NullString, error) {
	rows, err := db.Query(ctx,`SELECT  mytext FROM  test`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var mytext sql.NullString
		if err := rows.Scan(&mytext); err != nil {
			return nil, err
		}
		items = append(items, mytext)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

`mytext` is erroneously treated as `sql.NullString{ String: "", Valid: true}`.

I guess the solution to this is just to use pgtypes.Text, but I hadn't made the switch yet.

**Comment by jackc** [comment]
The problem was in the code path for unknown types. It was converting text formatted PostgreSQL values to a string without checking if the `[]byte` was `nil`. A `[]byte(nil)` converts to `""`.

Fixed in https://github.com/jackc/pgtype/commit/693c7c7f7d4fa9d306af6c9ba911c26a0e62bf3c.
