### ISSUE TITLE
Does pgx support querying with IN and passing in a slice to conn.Query()?

### ISSUE THREAD

**Issue by ARolek** [jackc/pgx#108]
When I try to execute the following code, I get the error: `Expected integer representable in int64, received []int64 [793661 133034] `

```go
func ByIds(ids []int64) (person []Person, err error) {
	query := fmt.Sprintf(`
		SELECT
			id,
			name
		FROM
			mytable
		WHERE
			id IN ($1)`)

	rows, err := pgx.Conn().Query(query, ids)
	if err != nil {
		return
	}
	defer rows.Close()

	//scan code here....

	return
}
```

Does pgx support querying with a slice and the IN operator? If not, is there a good work around?

**Comment by jackc** [comment]
That won't work due to how variables are bound in PostgreSQL. However, there is a simple alternative. Instead of using IN use ANY.

```sql
select id, name from mytable where id = any($1);
```

**Comment by ARolek** [comment]
Got it. That works perfectly. Thank you.

**Comment by alaska** [comment]
I don't recall anything about using `any` like this in the docs, it seems like a good thing to put in a wiki page, maybe?

**Comment by jackc** [comment]
Sure.
