### ISSUE TITLE
[question] Does batch combine inserts into a single statement?

### ISSUE THREAD

**Issue by switchupcb** [jackc/pgx#1082]
It's known that batch starts a `transaction` and subsequently `commits` one. Does it do anything else?

Given the following batch:
```sql
INSERT INTO users (name) VALUES ($1);
INSERT INTO users (name) VALUES ($1);
INSERT INTO users (name) VALUES ($1);
```

When a batch is sent with one network request, is its contents turned into a single statement (when possible)?
```sql
INSERT INTO users (name)
VALUES
    ($1),
    ($2),
    ($3);
```

**Comment by jackc** [comment]
No. It it does not merge statements. And to be clear, it does not explicitly begin or commit a transaction. It is an implicit transaction based on how the PostgreSQL extended protocol works.
