### ISSUE TITLE
initPostgresql for new connections in v4

### ISSUE THREAD

**Issue by dmitriy-dokshin** [jackc/pgx#1088]
Hi!
Is there some reason why you decided not to initialize ConnInfo like in v3?
https://github.com/jackc/pgx/blob/d7c42f0d3dd0b55e576608b85c80a871a4040a0c/conn.go#L657

**Comment by jackc** [comment]
pgx no longer needs to have read the catalog when connecting.

**Comment by dmitriy-dokshin** [comment]
But this way there will be some unresolved types.

**Comment by jackc** [comment]
They will be treated as unknown text types. There's not much else that can be done with them.
