### ISSUE TITLE
add pipline mode support

### ISSUE THREAD

**Issue by hochhaus** [jackc/pgx#1091]
With the release of postgres 14 today, the libpq library supports [pipeline mode](https://www.postgresql.org/docs/14/libpq-pipeline-mode.html).

To better support workloads with many small write operations would pgx consider adding pipline mode support?

**Comment by jackc** [comment]
pgx already has batch query support. I'm aware that pipelining is not exactly the same thing, but for most use cases they can have the same benefits.

What is the use case where the existing batch query support would not work?

Also, if there is a use case, what would the API look like? In particular context cancellation would be very messy.

**Comment by hochhaus** [comment]
Thanks @jackc. Let me explore the existing batch support and I'll open a more detailed issue if any limiting use cases present themselves.
