### ISSUE TITLE
Panic when using Next

### ISSUE THREAD

**Issue by j16r** [jackc/pgx#1100]
I'm trying to diagnose a panic that is occurring when calling `Next()`. The panic is happening here: https://github.com/jackc/pgx/blob/master/stdlib/sql.go#L763

At this point `r.rows.FieldDescriptions()` is returning an empty array, so we get a panic like so:

```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 108 [running]:
testing.tRunner.func1.2({0x60f13c0, 0xc0012f0b40})
	/Users/john/.asdf/installs/golang/1.17.2/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/Users/john/.asdf/installs/golang/1.17.2/go/src/testing/testing.go:1212 +0x3b6
panic({0x60f13c0, 0xc0012f0b40})
	/Users/john/.asdf/installs/golang/1.17.2/go/src/runtime/panic.go:1047 +0x266
github.com/jackc/pgx/v4/stdlib.(*Rows).Next(0xc00179ceb0, {0xc001355830, 0x9, 0x404b6e8})
	/Users/john/.asdf/installs/golang/1.17.2/packages/pkg/mod/github.com/jackc/pgx/v4@v4.13.0/stdlib/sql.go:763 +0x627
database/sql.(*Rows).nextLocked(0xc001e54b00)
	/Users/john/.asdf/installs/golang/1.17.2/go/src/database/sql/sql.go:2967 +0x21e
database/sql.(*Rows).Next.func1()
	/Users/john/.asdf/installs/golang/1.17.2/go/src/database/sql/sql.go:2945 +0x47
database/sql.withLock({0x67ecf90, 0xc001e54b30}, 0xc0015609e0)
	/Users/john/.asdf/installs/golang/1.17.2/go/src/database/sql/sql.go:3396 +0xb6
database/sql.(*Rows).Next(0xc001e54b00)
	/Users/john/.asdf/installs/golang/1.17.2/go/src/database/sql/sql.go:2944 +0x7e
```

It looks like this happens around the same time that we've closed the DB in another goroutine, as I'm seeing a couple of errors like `failed: driver: bad connection` or `conn busy`. Is it possible we're using something concurrently that is not safe to?

**Comment by samsondav** [comment]
I've been debugging this issue for several days now and I cannot see how we are using the library incorrectly. It really looks like a bug in pgx to me.

Any ideas @jackc

**Comment by j16r** [comment]
There is some discussion here which seems related: https://github.com/jackc/pgx/issues/785

I have run the race detector and haven't found any data races yet.

**Comment by samsondav** [comment]
Note that this also occurs even if I remove all the calls to `db.Close` so it seems like that may have been a red herring

**Comment by samsondav** [comment]
This turned out to be a bug in https://github.com/DATA-DOG/go-txdb.

Not a bug in pgx. This issue can be closed.

**Comment by tinoquang** [comment]
> This turned out to be a bug in https://github.com/DATA-DOG/go-txdb.
> 
> Not a bug in pgx. This issue can be closed.

Hi, can you explain more about this? I'm having the same error
