### ISSUE TITLE
pgx.Connect slow on certain databases

### ISSUE THREAD

**Issue by m1212e** [jackc/pgx#1104]
Hi,

I experience a slow initial connection with my database and pgx. This does not happen with the psql cli or Beekeeper(tool for database gui). They connect instantly. Coming from GORM I also tried to disable the initial ping, which just results in a slow query, the first time I actually query something. Other databases connect instantly.

My database uses pgBouncer as load balancer and pooler.
Do you have any idea what could cause this? Some configuration with pgx or my database?

Thanks!

**Comment by jackc** [comment]
Those TCP retransmissions indicate there is something going wrong lower in the stack. pgx doesn't directly do that. I don't think the Go stdlib/runtime is even doing that. I'm pretty sure that is actually OS level behavior. And if I'm reading it correctly, those packets aren't even application level packets, they are TCP SYN packets.

I suspect either nothing is listening at the other end or a firewall is dropping the packets. Possibly DNS is different and your host is being resolved differently where it works and where it doesn't (if round-robin DNS is being used maybe pgx and psql resolve in different order).

If you have a single machine that psql works on and pgx doesn't then a comparison of the packet captures of their connection attempts might be informative.

**Comment by m1212e** [comment]
Ok, thank you very much!

**Comment by shasderias** [comment]
Debugging hint for anyone who might stumble over this in the future.

If you are passing a host name to pgx (as opposed to an IP address), depending on your environment, that host name may resolve to an IPv6 address. This is a problem if your PostgreSQL server is not listening on the IPv6 interface. So try specifying an IP(v4) address and see if that solves your problem.

If you are running Docker desktop on Windows (and possibly Docker desktop on Mac, as they both run a Linux VM behind the scenes) to run PostgreSQL in a container, this has a good chance of being your culprit.

If this is your culprit, your Wireshark dumps will look something like that (see packets no. 315 and up).

![image](https://user-images.githubusercontent.com/614153/205062467-a2ab70ce-4641-4cd6-9dc6-2f963f3bd3e7.png)
