### ISSUE TITLE
ERROR: could not determine data type of parameter $2 (SQLSTATE 42P18)

### ISSUE THREAD

**Issue by Kaitou786** [jackc/pgx#1105]
Hello all,
I am trying to execute a query where I need pass the interval as a parameter to the query:
```
Conn.Query(context.TODO(), `SELECT * FROM check_statuses WHERE checkKey=$1 and (inserted_at > NOW() - Interval '$2') ORDER BY inserted_at DESC LIMIT $3`, checkKey, duration.Seconds(), count)
```

But on executing the above query it returns the error:
```
ERROR: could not determine data type of parameter $2 (SQLSTATE 42P18)
```

Not sure what could be the possible reason.

I saw the issue: https://github.com/jackc/pgx/issues/281 and thought of defining the type as $2::int. But doing that resulted in `Invalid syntax for interval` error

**Comment by jackc** [comment]
`$2` is quoted. That means PostgreSQL doesn't consider is a parameter placeholder. It considers it a string.

If you are using the native pgx interface you can instead use a time.Duration directly as the parameter (i.e. remove the `Interval` keyword and quotes from your query). If using `database/sql` interface, you may want to use the `make_interval` SQL function.

**Comment by Kaitou786** [comment]
Hello @jackc thanks for the reply. I am using the pgx library directly. I tried with your suggestion.
SO instead of 
`inserted_at > NOW() - Interval '$2'` 
I tried with:
`inserted_at > NOW() - $2` and passing in the time.Duration directly as a parameter.  This results in a new error:

```
ERROR: operator does not exist: timestamp without time zone > interval
```

**Comment by ivanduka** [comment]
The solution is to cast the parameter to interval, like here:
```
	DELETE
	FROM webhooks
	WHERE webhooks.created < (NOW() - $1::INTERVAL);
```
