### ISSUE TITLE
Isolate indirect (test) dependencies

### ISSUE THREAD

**Issue by cristaloleg** [jackc/pgx#1112]
Hi, thank you for the great library, it's a pleasure to work with it.

I have a proposal to isolate 3rd party dependencies in a submodule to cleanup `go.mod`. My case is based on a situation where we've tied on specific `shopspring/decimal` version (which is forked and replaced in go.mod but that's not important) and due to it's presence in `jackc/pgx` we had troubles to resolve those module requirements.

After checking `pgx` sources I have found that all dependencies (mentioned below) are used only in tests (`query_test.go`) and also are in `pgx_test` package, so depends only on exported `pgx` things. Looks like creating a submodule with a test of this dependencies should reduce direct dependencies for `pgx` and simplify other worflows.

The dependencies I'm talking about are:
- github.com/cockroachdb/apd
- github.com/gofrs/uuid
- github.com/shopspring/decimal
- github.com/Masterminds/semver (probably too)

Thanks.

PS: regarding submodules/multi-module repositories https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories

**Comment by jackc** [comment]
I've considered using multiple modules in a single repository. But I've run into problems with my projects and seen it with other projects where seemingly straightforward Go module changes have caused a lot of problems both for the project and its users.

This probably is a good idea, but I'm too nervous to try it in `v4`. One of my goals with `v5` is to finally resolve the messy dependency situation, both with internal pgx projects like `pgtype` and with external  ones like `shopspring/decimal`.

**Comment by cristaloleg** [comment]
Good enough :D Also haven't seen `v5` plans, maybe it's time to start an epic/umbrella issue or milestone?

Anyway, thanks for answering. Feel free to close the issue if you need so.

**Comment by jackc** [comment]
> Also haven't seen v5 plans, maybe it's time to start an epic/umbrella issue or milestone?

Good idea. I had been using a `v5` tag, but a milestone is a better categorization.
