### ISSUE TITLE
Support Postgres 14 Pipelining

### ISSUE THREAD

**Issue by johanbrandhorst** [jackc/pgx#1113]
Apparently Postgres 14 introduces the ability to pipeline queries, similar to batching, but, I think, with asynchronous results possible. See https://www.postgresql.org/docs/14/libpq-pipeline-mode.html for details.

It would be super cool if pgx could support pipelining of queries!

**Comment by jackc** [comment]
See  #1091.

**Comment by johanbrandhorst** [comment]
I'd be happy to leave this open in perpetuity just to have a discussion point, even if implementing it is not immediately planned. It sounds like something someone could contribute in time. Does that sound okay?

**Comment by jackc** [comment]
Sure, we can leave it open. Though as I mentioned in the other thread there are two significant issues that would need to be resolved for a pipeline mode to be added to pgx.

1. Identify the use case that cannot be handled by existing API's.
2. Find a workable API for that use case while handling things like context cancellation and hopefully not being too invasive of a change.

Also, as an aside, the pipeline mode is new in the libpq client library but it doesn't add anything different to the server. It is simply a different way of using the existing wire protocol. So this wouldn't be limited to PG 14.

**Comment by jackc** [comment]
The `v5-dev` branch now has a low-level pgconn pipeline mode as well as `SendBatch()` performance improvements using this new functionality.
