### ISSUE TITLE
don't support binary parameter?

### ISSUE THREAD

**Issue by shanjunmei** [jackc/pgx#1114]
get this error : unrecognized configuration parameter "binary_parameter"

**Comment by jackc** [comment]
`binary_parameter` is not a PostgreSQL configuration parameter nor is it a pgx configuration parameter. I'm guessing this was from a connection string for another driver. pgx automatically uses binary encoding when possible.

**Comment by shanjunmei** [comment]
> `binary_parameter` is not a PostgreSQL configuration parameter nor is it a pgx configuration parameter. I'm guessing this was from a connection string for another driver. pgx automatically uses binary encoding when possible.

sorry ,should be : `binary_parameters=yes` , The lib/pq driver I used earlier，after I add this parameter, the geometry data can be inserted normally. Without this parameter, it will not work. After changing the pgx driver, I add this parameter and directly connect to report an error. If this parameter is not added, an error will be reported when the geometry data is inserted.

**Comment by jackc** [comment]
I don't know what geometry types you are using or how you are trying to use them but [pgtype](https://github.com/jackc/pgtype) (the package that implements PG types for pgx) has support for box, polygon, etc. types that are in core PostgreSQL.

**Comment by shanjunmei** [comment]
> I don't know what geometry types you are using or how you are trying to use them but [pgtype](https://github.com/jackc/pgtype) (the package that implements PG types for pgx) has support for box, polygon, etc. types that are in core PostgreSQL.

i'm using  github.com/twpayne/go-geom/encoding/ewkb 


`func (g Point) Value() (driver.Value, error) {
	var x = geom.NewPoint(geom.XYZ).MustSetCoords(geom.Coord{g.X, g.Y, g.Z}).SetSRID(4326)
	data, err := ewkb.Marshal(x, binary.LittleEndian)
	if err != nil {
		return nil, err
	}
	return data, nil
}`

will got this issue 

`parse error - invalid geometry (SQLSTATE XX000)`
