### ISSUE TITLE
Thoughts on COPY and push vs. pull

### ISSUE THREAD

**Issue by atombender** [jackc/pgx#1115]
I have an application which imports data in multiple stages using big `INSERT` statements, and I'm about to rewrite it to use `CopyFrom()` so that the data can be streamed directly to Postgres with minimal buffering of the row data.

The problem is that this function takes an iterator interface to pull data into itself, which is rather awkward if the caller is fundamentally "push"-oriented, which my app is. My app receives each datum from a caller and needs to convert it to a row and feed it into the `COPY` statement.

I can of course "flip" this using channels. [Here](https://gist.github.com/atombender/d810d61e4fbb294aa1686c3cce420144) is my work-in-progress general-purpose adapter. It can be used like so (simplified):

```go
src := NewPushCopySource(ctx)
go func() {
  _, err := conn.CopyFrom(ctx, pgx.Identifier{"things"}, []string{"id", "id", "type", "payload"}, src)
  if err != nil { ... }
}()
for _, row := range rows {
  src.Add(row)
}
```

In other words, the copying runs in a separate goroutine, pulling new rows as they arrive, and the main goroutine pushes to it.

This is all fine, though it is more complicated than I was hoping for. Aside from needing an extra goroutine and forcing every row to go through a channel, the caller also has to monitor the copying for errors, and doing multiple consecutive `COPY` statements to different tables will require more complicated state management of the goroutines and sources. For example, I may sometimes get data intended for different tables mixed together, so if I am currently copying into table A, I have to first wrap up that copy before I can begin a new one to B. Not hard, just annoying.

I've looked at the copy-related code in pgx and pgconn, and maybe I'm missing something, but I don't see a particular reason why copying has to be pull-based. As far as I can see, to copy at the Postgres connection level, you basically just initiate a `COPY` and keep writing rows until done. So the whole operation could be deconstructed as an "imperative" push-based system:

```go
copy := conn.BeginCopy(ctx)
for _, row := range rows {
  err := copy.Send(row) 
  if err != nil { ... }
}
cmdTag := copy.End()
```

The current code needs to use channels because it's pull-based, but it just looks more complicated than it needs to be. It does seem like you need to monitor this `signalMessageChan`, and maybe that's why it's written to pull. I don't know much about how the protocol stream is managed, but I imagine it could be written to handle _signaling_ in a goroutine instead of the writing?

The benefit of the push-based system is that if the pipeline is push-based to begin with (and I would argue that most apps are written like this), then no channels or extra goroutines are needed (not sure about the signaling stuff, though).

Of course, a push-based system can always be adapted into a pull model and vice versa, but "inverting" the control will always require the use of channels and an extra goroutine. But I would argue that it's simpler to use push as the foundation, and then build pull on top of it.

Am I missing something obvious here? Thoughts?

**Comment by jackc** [comment]
You are correct it. It could be done either way.

> It does seem like you need to monitor this signalMessageChan, and maybe that's why it's written to pull.

It's been long enough since the original copy code was written that if it was a purposeful choice between push and pull I don't remember why. The `signalMessageChan` background read is very important though.

1. It stops sending data when the server sends an error back. This fail-fast behavior can be useful with large copies.
2. It is possible for a deadlock to occur if the client and server both do blocking sends of data larger than the network buffering capacity between them. Neither can finish sending and neither will read until they finish sending. This behavior is very difficult to produce (something like an insert trigger that causes a notice or listen/notify message) but can occur.

Obviously, they could also be handled in a push model if `BeginCopy` started a background reader.

**Comment by atombender** [comment]
Thanks for explaining. I'm going to try to set aside some time to experiment with writing a push-based copy implementation for pgconn.
