### ISSUE TITLE
How long can a pgxpool be used for connections?

### ISSUE THREAD

**Issue by sdxv** [jackc/pgx#1118]
Hello,

If I have a long running process (running continuously for months or more) keeping a connection to a database open this while time is likely a bad idea - it uses up resources, and the connection may time-out when not in use.

What about connection pools though? Is it safe to connect a pgxpool.Pool and use it indefinitely? If not, should the whole pool be closed and reopened on each request that needs database access?

Thanks.

**Comment by jackc** [comment]
A pool can be used indefinitely. You can configure it to close the underlying connections when not it use.

**Comment by sdxv** [comment]
Thanks!
