### ISSUE TITLE
url parsing "?" bug

### ISSUE THREAD

**Issue by diCagri** [jackc/pgx#1120]
When connection URL string has contains more "?", pgx can't parsing url . I guess it confuse "?" with query string

example:
"posgres://postgres:mehmet?@0.0.0.0:5432/mydb"

**Comment by cristaloleg** [comment]
Looks like it also cannot be parsed by stdlib `net/url` https://go.dev/play/p/sN9tdwM7Z7b which is used by pgx (pgconn to be precise (https://github.com/jackc/pgconn/blob/662ecb496ffc8c64f7bfa156694e0fe525a97685/config.go#L387)

**Comment by jackc** [comment]
Is `?` is a valid character for the password part of a URL? https://www.w3.org/Addressing/URL/url-spec.txt indicates it is forbidden but it appears https://www.ietf.org/rfc/rfc1738.txt allows it.

Node fail to parse it as well:

```
jack@glados ~ » node
Welcome to Node.js v16.2.0.
Type ".help" for more information.
> u = new URL("postgres://postgres:mehmet?@0.0.0.0:5432/mydb")
Uncaught TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:363:5)
    at onParseError (node:internal/url:537:9)
    at new URL (node:internal/url:613:5)
    at REPL1:1:5
    at Script.runInThisContext (node:vm:131:12)
    at REPLServer.defaultEval (node:repl:522:29)
    at bound (node:domain:416:15)
    at REPLServer.runBound [as eval] (node:domain:427:12)
    at REPLServer.onLine (node:repl:849:10)
    at REPLServer.emit (node:events:377:35) {
  input: 'postgres://postgres:mehmet?@0.0.0.0:5432/mydb',
  code: 'ERR_INVALID_URL'
}
```

... a few minutes later ...

Okay, I tracked it down a little further. This appears to be the underlying Go code:

https://github.com/golang/go/blob/1876b38263407ba51f9f3fa2e412ac3f84d3cb95/src/net/url/url.go#L1179-L1207

And it is using [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) which requires special characters like `?` to be percent encoded.

So I would say this is not a pgx bug nor a Go bug.
