### ISSUE TITLE
Batch reset method

### ISSUE THREAD

**Issue by cristaloleg** [jackc/pgx#1123]
Hi, have met a problem that it's not possible to reuse batches between queries (via sync.Pool by example) due to an unexported slices inside a batch. I'm talking about this field https://github.com/jackc/pgx/blob/master/batch.go#L18

I'm proposing to add a method like:
```go
func (b *Batch) Reset() {
	b.items = b.items[:0]
}
```

In other words, before putting batch in to the pool we do `Reset`, keeping it's memory in place but not allocation new memory later.

**Comment by jackc** [comment]
Hmm... would that actually make a difference? I'm not specifically opposed to it, but I'd need to be convinced the savings would be meaningful relative to the overall query. Do you have any benchmarks showing this as a problem?

**Comment by cristaloleg** [comment]
Closing because of `.Copy()` method so reset might be too specific.
