### ISSUE TITLE
PGX Greatly Increases Memory Usage (compared to pq)

### ISSUE THREAD

**Issue by noahschumacher** [jackc/pgx#1127]
I recently switched a couple of my services from PQ to PGX. The first service I switched over I didn't notice anything. For the second service however I quickly noticed a sharp increase in memory consumption. For awhile I thought this was a memory leak issue due to my implementation, however I noticed that if I let the service run long enough the memory would stabilize are 8x what it was with PQ. 

When I realized this wasn't a memory leak I checked the first smaller (less traffic) service and noticed it had experienced that same  rise in memory but less so (around 4x). Looking at the `pprof` `top` output:

```
Showing top 10 nodes out of 147
      flat  flat%   sum%        cum   cum%
   35.64MB 17.78% 17.78%    35.64MB 17.78%  google.golang.org/grpc/internal/transport.newBufWriter
   33.53MB 16.73% 34.51%    43.03MB 21.47%  google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders
   17.64MB  8.80% 43.31%    17.64MB  8.80%  github.com/jackc/chunkreader/v2.(*ChunkReader).newBuf
   15.50MB  7.73% 51.04%    15.50MB  7.73%  context.WithValue
   14.94MB  7.45% 58.49%    14.94MB  7.45%  bufio.NewReaderSize
    9.51MB  4.74% 63.24%     9.51MB  4.74%  runtime.allocm
    9.50MB  4.74% 67.98%     9.50MB  4.74%  bytes.(*Buffer).String
    8.54MB  4.26% 72.24%     8.54MB  4.26%  golang.org/x/net/http2/hpack.(*headerFieldTable).addEntry
       5MB  2.50% 74.73%        5MB  2.50%  github.com/grpc-ecosystem/go-grpc-middleware/tags.(*mapTags).Set
       4MB  2.00% 76.73%        4MB  2.00%  github.com/uber/jaeger-client-go.simpleSpanAllocator.Get
```

I noticed a few instances were mentioning buffer which led me to [this file](https://github.com/jackc/chunkreader/blob/master/chunkreader.go) and specifically this comment:
```
// ChunkReader is a io.Reader wrapper that minimizes IO reads and memory allocations. It allocates memory in chunks and
// will read as much as will fit in the current buffer in a single call regardless of how large a read is actually
// requested. The memory returned via Next is owned by the caller. This avoids the need for an additional copy.
//
// The downside of this approach is that a large buffer can be pinned in memory even if only a small slice is
// referenced. For example, an entire 4096 byte block could be pinned in memory by even a 1 byte slice. In these rare
// cases it would be advantageous to copy the bytes to another slice.
```

I then found this issue: https://github.com/jackc/pgx/issues/845 which seems to be describing nearly the same problem except the assumption is that this is a memory leak vs a large amount of memory usage. @jackc you mentioned a few things in this comment https://github.com/jackc/pgx/issues/845#issuecomment-760577057 to potentially minimize or fix the buffers blowing up.

My Questions:
1. Has anyone else experienced large increases in memory usage when switching to or using PGX (potentially proportional to the # of queries made)
2. We are using `pgxpool` like `pgxpool.ParseConfig(...)`, `pool.Exec(ctx, query, param1)`, `pool.Query(ctx, query, param1)`. How would we be able to apply the suggestions about modify `min_read_buffer_size` with this structure in the above linked comment to pools?
3. Does anyone have any other suggestions on how to manage memory while using `PGX`

Here are the images of the affected services:
![image](https://user-images.githubusercontent.com/26905830/146094690-e8a3bc7a-1c09-4059-a9a8-3ee28406dff9.png)
![image](https://user-images.githubusercontent.com/26905830/146094755-e0e07553-e26b-4d97-a9e5-d174f02d60f9.png)

It's worth noting that in both services the queries and structure remained nearly identical. The only changes were in conforming to the usage of PGX vs PQ.

**Comment by jackc** [comment]
> How would we be able to apply the suggestions about modify min_read_buffer_size with this structure in the above linked comment to pools?

`min_read_buffer_size=1` can be set in the connection string.

> Does anyone have any other suggestions on how to manage memory while using PGX

The read buffer is my first guess as for what is taking extra memory. If usage significantly goes down with `min_read_buffer_size=1` then the issue is finding where a reference is being maintained.

You could also set `SetConnMaxLifetime` to only a few seconds. If the references are being maintained by your application code this should have only a small effect. But if somehow pgx is holding onto the references internally this should have a large effect.

**Comment by noahschumacher** [comment]
Thanks for the quick response @jackc. I will go through the above and respond back with how it went.

**Comment by noahschumacher** [comment]
Hi @jackc. I did some testing with the above suggetions in my development environment, putting the service under load. While this is not a perfect replica of production I was able to gain some insights.

> Adjusting the `min_read_buffer_size`

When adjusting this to 1 I noticed a slight decrease in the rate at which the memory consumption was rising but it still seemed to following the above example. I then tried upping the `min_read_buffer_size` to 65536. The memory consumption with this set slightly increased allocation speed but still did not make much of a difference in the overall memory growth and usage shown in the charts.

> Setting `SetConnMaxLifetime`

When I adjusted this to a `2 second` period the memory growth and allocation was seemingly fixed! I was unable to grow the services memory consumption past `90Mi`. To contrast. In the same environment with similar load and a `30 minute` period the usage would grow to 150Mi+ and continue.

Next steps for me is to test the shorter `SetConnMaxLifetime` in the production environment and monitor + profile the memory usage.

It seems though that if this is the issue it would maybe pgx is somehow holding onto references internally? Is it also possible that with this very short lifetime is clearing the `read_buffers` on each connection?

**Comment by jackc** [comment]
> When adjusting this to 1 I noticed a slight decrease in the rate at which the memory consumption was rising but it still seemed to following the above example.

That's really interesting. That indicates that the problem is not the read buffers being pinned.

> > Setting SetConnMaxLifetime

> When I adjusted this to a 2 second period the memory growth and allocation was seemingly fixed!

> It seems though that if this is the issue it would maybe pgx is somehow holding onto references internally?

So it would seem. If this is the case the most likely culprit would be preallocated `Rows`.

To avoid allocating a new `Rows` object for every `Query` these are allocated in 64 element slices. This was in an attempt to minimize the number of allocations per `Query`. But this also means they could only get GC'd every 64 queries. `Rows` appears to hold onto a reference to the args and the last row data. With the right (or rather the wrong) query this might be the problem. I created a test that removes this. See PR #1134 and try branch `remove-rows-bulk-alloc` to see if this resolves the problem.

**Comment by noahschumacher** [comment]
I applied the changes found in #1134 to local pgx package but it, unfortunately, did not make a difference in the memory usage.

I also re-tested the `SetConnMaxLifetime` with it set to 2seconds and this again greatly reduced memory holding it at around 80Mi. Perhaps if I set the number of connections to 1 and the interval to 5 minutes I will be able to see consistent drops and rises that will clearly indicate the memory is being accumulated in a connection somewhere (or maybe we already feel confident in this).

> When adjusting this to 1 I noticed a slight decrease in the rate at which the memory consumption was rising but it still seemed to following the above example.
>> That's really interesting. That seems to indicate that the problem is not the read buffers being pinned.

I also re-tested this and did not notice the slower/faster memory I noticed the first time. The results are very qualitative here (plotting memory consumption) and in the context of rate of change probably mean very little.

**Comment by noahschumacher** [comment]
Following up here.

After testing reducing the connection lifetime to 30 minutes instead of 1 hour in our production environment I found a slight reduction in memory consumption. I may test by further reducing the MAX_CONNECTION_LIFETIME.

**Comment by noahschumacher** [comment]
@jackc SOLVED!

I traced this issue back to having over set our `max_connections` value. It was set at 200 which was way to large for what we needed. My hypothesis is that each connection is used and granted a row buffer. Since there are so many connections each one will slowly grow as it moves from an idle to active state. Eventually most of these connections will have ~8mb allocations before they are cleaned up.

Adjusting the max_connections to 10 immediately solved this issue and did not hurt latency or cpu usage.
