### ISSUE TITLE
Arrays of custom types via the stdlib interface

### ISSUE THREAD

**Issue by treuherz** [jackc/pgx#1128]
I'm trying to figure out how to take advantage of pgx's array decoding support but via the stdlib interface. I have a custom type that implements `Scan` (or `DecodeText`). With `lib/pq`, I could scan a query into an array of this type by using `pq.Array`, which would wrap the slice in a type that would decode the postgres array into a slice of anything that itself implemented `Scan`.

I've looked at #809 and some other places where you've discussed this, but what I can't see how to do is use the tools in pgtype for ad-hoc handling of an array like this. We're using pgx via the stdlib interface, so I'm not easily able to jump through the hoops of registering an `ArrayType` with the connection. I'm happy to take the performance hit if it means I can have something as straightforward to use as `pq.Array` was.

Is there something obvious I'm missing here, like a different way of using `CompositeFields`? Is this a small hole in the library? If the latter, is it something you'd be interested in a PR to fix?

**Comment by jackc** [comment]
I haven't used `pq`, but from a quick glance at the code I suspect `pq.Array` would work in pgx. If it's working exactly how you want maybe keep using it.
