### ISSUE TITLE
Expecting pgx.ErrNoRows but getting sql.ErrNoRows

### ISSUE THREAD

**Issue by donileo** [jackc/pgx#113]
Pretty much as the title says.. using sqlx and pgx as my driver to my postgres connection I am getting back sql.ErrNoRows for cases where I believe I should be getting pgx.ErrNoRows. I can see that when there are specific codes thrown out by postgres that i get back a pgx.PgErr but for cases where there are no rows its always a sql.ErrNoRows.

**Comment by jackc** [comment]
When using pgx with database/sql and sqlx, pgx is simply acting as a driver. The `sql.ErrNoRows` error is being returned from the database/sql library. `pgx.ErrNoRows` is only returned when calling a pgx function directly. As for why you do get the `pgx.PgErr` type errors returned sometimes, database/sql will bubble up some errors from the driver.
