### ISSUE TITLE
Scan custom enum into interface

### ISSUE THREAD

**Issue by emaborsa** [jackc/pgx#1133]
I have the following database (snippet):

    CREATE TYPE public.gender AS ENUM ('male', 'female');
    
    CREATE TABLE public.persons
    (
        id uuid NOT NULL DEFAULT uuid_generate_v1(),
        surname text,
        given_name text,
        gender gender NOT NULL
    )

In my project I defined a dynamic query builder, it works except for my custom enums. The example query is the following:

    SELECT DISTINCT (p.gender) FROM persons p  ORDER BY p.gender

The code:

	values := make([]interface{}, 0)
	for rows.Next() {
	    var value interface{}

	    err = rows.Scan(&value)
	    if err != nil {
	    	return nil, err <-- "unknown oid 25374 cannot be scanned into *interface {}"
	    }
	    values = append(values, value)
	}

If I use string instead of interface{} as following, it works:

	values := make([]string, 0)
	for rows.Next() {
	    var value string

	    err = rows.Scan(&value)
	    if err != nil {
	    	return nil, err
	    }
	    values = append(values, value)
	}

If I check the resultset, the values are read as a []uint8. 
Is this approach fixable?

As workaround I mixed the snippets:

	values := make([]interface{}, 0)

	for rows.Next() {
	    var value interface{}
	    err = rows.Scan(&value)
	    if err != nil {
		var s string
		err = rows.Scan(&s)
		if err != nil {
	            return nil, err
		}
		values = append(values, s)
	    }
	    values = append(values, value)
	}

**Comment by jackc** [comment]
The PostgreSQL type is unknown (`create type`) and the Go type is unknown (`interface{}`). It doesn't know how to interpret those bytes that came from the PostgreSQL server and it doesn't know what the desired format in Go is.

You can either specify the Go destination by scanning into a string or you can register the data type so pgx knows what OID 25374 is.

You could use [this helper function](https://pkg.go.dev/github.com/jackc/pgtype@v1.9.1/pgxtype#LoadDataType).

Something like this in an after connect hook:

```go
dataType, err := pgxtype.LoadDataType(ctx, conn, conn.ConnInfo(), "gender")
if err != nil {
	return err
}
conn.ConnInfo().RegisterDataType(dataType)
```

**Comment by emaborsa** [comment]
Works like a charm:


	config, err := pgxpool.ParseConfig(env.DbUrl)
	if err != nil {
		panic(err)
	}
	config.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
		dataType, err := pgxtype.LoadDataType(ctx, conn, conn.ConnInfo(), "gender")
		if err != nil {
			return err
		}
		conn.ConnInfo().RegisterDataType(dataType)

		return nil
	}

	pool, err := pgxpool.ConnectConfig(context.Background(), config)
	if err != nil {
		panic(err)
	}

Let's assume I have a `public.gender` and a `members.gender`, can I simply load a second gender including the schema like followings?


		dataType, err = pgxtype.LoadDataType(ctx, conn, conn.ConnInfo(), "members.gender")
		if err != nil {
			return err
		}
		conn.ConnInfo().RegisterDataType(dataType)

**Comment by jackc** [comment]
> Let's assume I have a public.gender and a members.gender, can I simply load a second gender including the schema like followings?

I don't think that helper function handles schemas. You could probably use the underlying code directly if you need schema support.

**Comment by emaborsa** [comment]
I tried it, adding schemas seams to work fine.
