### ISSUE TITLE
if the connection is broken, the rows.Next() will not return

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pgx#1136]
if the connection is broken, the rows.Next() will not return until the connect is connected again.
How to set the Next() timemout and what's the default timeout value?

**Comment by jackc** [comment]
I presume you mean the network connection hands while waiting for rows? Then using a context with a timeout / deadline when sending the query will do what you want.

**Comment by zhanghaiyang9999** [comment]
But if set the context timeout, for example:
ctx, _ := context.WithTimeout(context.Background(), 60*time.Second)
rows, err := conn.Query(ctx, "SELECT * FROM myschema.log  order by id asc;")
if the record number is big and handle all the records  need 10 minutes, then the rows.Next() will return timeout in one minute, but doesn't handle all the records.
But I hope if  the network is good and can handle all the records correctly and if the network is broken the rows.Next() can failed.

**Comment by krisdiano** [comment]
rows.Next() just return a bool, in the end, you must invoke rows.Err() to get a error which you need process
