### ISSUE TITLE
Missing Columns()  method in Rows implementation

### ISSUE THREAD

**Issue by elumalai** [jackc/pgx#114]
Thank you for the wonderful library. We are using pgx instead of database/sql package directly because we have to manage the connections ourselves. 

We are now trying to use a third party package for scanning sql row to struct. But pgx does not implement the Columns() method in Rows type. 

Is it possible to implement the Columns() method ?

**Comment by jackc** [comment]
Does FieldDescriptions() do what you need?

**Comment by elumalai** [comment]
@jackc Thank you for taking time to reply. Yes, I know we can use FieldDescriptions(). But if the Columns() method implemented in Rows type, we can use packages that are compatible with database/sql package. Otherwise we should write our own. Since it is available in the pgx/stdlib module, I thought it is possible to implement in the pgx package itself.

**Comment by jackc** [comment]
Do those packages expect the rows object to define an interface or do the strictly want a database/sql.Rows object? It would only work if the the former.

I'd rather not add another method to the public interface of pgx if it is possible to solve another way. I am presently looking into how to make pgx more extendable / wrappable such that this could be implemented in a layer on top of pgx and below the sql row to struct mapping library.

See #110 for some other discussion of another issue I hope to solve with better extendibility.

**Comment by elumalai** [comment]
`Do those packages expect the rows object to define an interface or do the strictly want a database/sql.Rows object? It would only work if the the former.`

Expects the Rows type implements the interface defined by the package for mapping the result and struct.

**Comment by jackc** [comment]
I just had a chance to look closer at sqlx. It looks like it relies on database/sql types directly. So even if we add this method I don't think it will work.

Can you vendor pgx, add the `Columns()` method, and see if it works?

**Comment by elumalai** [comment]
@jackc We have forked https://github.com/kisielk/sqlstruct and modified to compatible with pgx. We made use of rows.FieldDescriptions() for missing Columns() method.

**Comment by elumalai** [comment]
@jackc  Since Rows and Row are same type in pgx, we did cast and implemented scanning for Row too. But I am not sure we are doing right. 

Issue context   https://github.com/kisielk/sqlstruct/issues/5

**Comment by jackc** [comment]
Cool. I think that is the correct solution.

**Comment by xperiafan13-rom** [comment]
I use this code instead of colums method
cols := rows.FieldDescriptions()

		for rows.Next() {
			// Create a slice of interface{}'s to represent each column,
			// and a second slice to contain pointers to each item in the columns slice.
			columns := make([]interface{}, len(cols))
			columnPointers := make([]interface{}, len(cols))
			for i, _ := range columns {
				columnPointers[i] = &columns[i]
			}

			// Scan the result into the column pointers...
			if err := rows.Scan(columnPointers...); err != nil {

			}

			// Create our map, and retrieve the value for each column from the pointers slice,
			// storing it in the map with the name of the column as the key.
			m := make(map[interface{}]interface{})
			for i, colName := range cols {
				val := columnPointers[i].(*interface{})
				m[colName] = *val
			}

			// Outputs: map[columnName:value columnName2:value2 columnName3:value3 ...]
			fmt.Print(m)
		}

But i get: 17077 7 1043 -1 instead string result

**Comment by jackc** [comment]
I would guess that is the output of one of the underlying `pgtype` package types. Perchance you could use `Printf` to see the type of the scanned values.

Alternately, the `Values()` method is probably more appropriate than `Scan(...)` when you don't know what types to expect.
