### ISSUE TITLE
How to set rows.Next() timeout?

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pgx#1142]
I use the codes like the following:

rows, err := conn.Query(context.Background(), "SELECT * FROM myschema.log  order by id asc;")
defer rows.Close()
for rows.Next() {
//do something
}
if the network is broken when executing for rows.Next(), the rows.Next() will hang and never return.
How can I set the timeout for the rows.Next() or if the network is broken, rows.Next() can return error immediately?
conn.Query use context timeout is not practicable, because the total number of the records is huge, get all the records needs some time. if the timeout is too short, then can't get all the records. if the timeout is too long, when the network is broken, still need to wait long time.

Thanks!

**Comment by jackc** [comment]
So you need a way to catch a read blocked by a network connection that is severed but the OS doesn't know it. 

There are 3 options I can think of.

1. A shorter TCP keepalive. It defaults to 5 minutes. You could use a custom [DialFunc](https://pkg.go.dev/github.com/jackc/pgconn#DialFunc) when establishing the connection and set a shorter value. 
2. pgx provides escape hatches to the lower level components. From pgx you can get to pgconn and from pgconn you can get the underyling `net.Conn`. You can manage your own timeouts with `SetReadDeadline`.
3. A context can be canceled explicitly. You could pass in a context without a timeout into `Query`. Then run your own timeout logic in a goroutine and if the timeout occurs then cancel the query.

**Comment by zhanghaiyang9999** [comment]
Thank you very much! I will try these
