### ISSUE TITLE
pool.Acquire silently failing

### ISSUE THREAD

**Issue by rene-at-dell** [jackc/pgx#1144]
Hi,
Found an odd issue the connection pool where it's silently failing.

Here's the code snippet of where the failure is happening:
```Golang
	log.Printf("[INFO] Received message: %v", ret)

	// get a connection
	conn, err := d.pool.Acquire(context.Background())
	if err != nil {
		log.Printf("[ERROR] Could not create connection: %v", err)
		return dns.RcodeServerFailure, ErrNoDatabase
	}
	log.Print("[INFO] Acquired DB Connection from Pool")
	defer conn.Release()
```

I'm seeing the `Received message` in the logs, but then something is breaking right at the `conn, err := d.pool.Acquire(context.Background())` line and not returning an error.  In other words, neither the `Could not create connection` or the `Acquired DB Connection from Pool` log entries ever make it to the logs which has me completely stomped.

To make things worse, I can't reproduce this locally, meaning I can't step into the pgx code to pin point where it's breaking.  It only happens after running for a few days.

Am I missing something?  Has anyone seen this happen?  Any hints as to how I can get more info to narrow down the search radius?

Thanks

**Comment by jackc** [comment]
If `Acquire` is blocking then it would indicate that either the pool is empty and there is no capacity to add a new connection or creating a new connection is hanging. If it is the former then all other activity on the pool would hang. If it is the latter then other pool activity would continue normally.

Either way, it is advisable to use a content with a timeout. Certain network failures can cause a hang of indefinite duration.

**Comment by rene-at-dell** [comment]
Appreciate you taking the time to reply @jackc 

Yep, adding the following and passing along that context to the lib I was able to get an error locally:
```golang
	ctx, cancel := context.WithTimeout(ctx, 100*time.Millisecond)
	defer cancel()
```

Deployed it to PROD.... let's see what comes back the next time it happens.

Might be a good idea to add it to the quick start?  I copy pasted what's there....  I'll submit a pull request if you like.

**Comment by sovitacharya** [comment]
The following issue can be resolved by using the  pool.Release()  func as well so next time when you try to acquire u will get a connection from the pool itself.
