### ISSUE TITLE
Using Query and ignoring the Rows response causes lockup

### ISSUE THREAD

**Issue by ARolek** [jackc/pgx#115]
I have encountered a peculiar issue which might be just user error. I have the following block of code:

```
query := `
	UPDATE 
		mytable
	SET 
		wiki=$2
	WHERE 
		id=$1;`

_, err = connPool.Query(query, this.Id, this.Wiki)
```

Where `wiki` is of type `jsonb` and `connPool` is of type `*pgx.ConnPool`. 

In an isolated environment this block of code would consistently lock up the program on the 11th call. Everything executes fine for the first 10 calls, but the 11th would lock up the entire program.

After reviewing the code it appears `Query(...)` should actually be `Exec(...)`, and after making this change everything works fine. I'm not quite sure why the call to `Query(...)` was locking up the process though. I believe it might have to do with the `*Rows` value being returned but never scanned. 

If you have any insight, I'm interested in understanding why this would break the program.

**Comment by jackc** [comment]
You're exactly correct. connPool.Query is returning a *Rows object. The connection is not returned to the connection pool until the *Rows is closed (either explicitly or by Next'ing to the end). So I surmise that your conn pool was set to a max of 10 connections. When all those we're allocated it hung the 11th time waiting for an available connection.

Incidentally, if you have pgx configured to log at the warn level it will output a warning whenever acquiring a connection blocks (https://github.com/jackc/pgx/blob/master/conn_pool.go#L106). May be useful in the future.

**Comment by ARolek** [comment]
I just checked my config and you're correct my max config is set to 10. Thanks for the quick response as well as pointing out the log level. That will be helpful in the future. I think we can consider this issue closed. ;-)
