### ISSUE TITLE
I can be wrong but I think this line is a reason why i can't get pgx.ErrNoRows error when trying to use batchResults.QueryRow().Scan()

### ISSUE THREAD

**Issue by kibernetique** [jackc/pgx#1150]
https://github.com/jackc/pgx/blob/9fdaf7da810405df8360184341085defbcf79446/batch.go#L122

**Comment by jackc** [comment]
I added a test case in d02b2ed013c33fbb5795b55e52aad4a1fb658f62 for a batch with a `pgx.ErrNoRows` and it seems to work. You'll have to provide a failing test case or at least more information if you want help.

**Comment by kibernetique** [comment]
Thank you for your answer. Now I see I've used ErrNoRows not quite right.
Have already found a solution. Leaving it here for those who made same mistake as me. There is my code sample:

```
    batchResults := conn.SendBatch(ctx, batch)
    for{
        err := batchResults.QueryRow().Scan(...)
        if err!=nil {
            if errors.Is(err, pgx.ErrNoRows) {
                break
            }
            // do something with err
        }
        // do something with Scan results
    }
```
But this ErrNoRows check is used wrongly in my case. I need to check if there are any queries left in a batch. I've noted that Batch have Len() method and I can simply do like this:

```
    batchResults := conn.SendBatch(ctx, batch)
    for i:=0; i<batch.Len(); i++ {
        err := batchResults.QueryRow().Scan(&id, &name)
        if err!=nil {
            // do something with err
        }
        // do something with Scan results
    }
```
