### ISSUE TITLE
 can't scan into dest[0]: cannot assign postgres real into custom float type

### ISSUE THREAD

**Issue by not-rusty** [jackc/pgx#1151]
Hello there,

Having the following table:

```sql
create table test (
    price real
)
```

And a record inserted, the following code fails:

```go
...
row := db.Pool.QueryRow(context.Background(), `
    select price
    from test
`)

type test float32
var insertedPrice test
err = row.Scan(&insertedPrice)
// err is not nil, with a can't scan into dest[0]: cannot assign 1234 into *test

```

But this one doesn't:

```go

row := db.Pool.QueryRow(context.Background(), `
    select price
    from test
`)

type test int // <- Changed it to int
var insertedPrice test
err = row.Scan(&insertedPrice)
// err is nil
```

Apparently the driver has no problem deserializing the postgres real type to a custom int type, but it does to a custom float32 (or float64) data type.

Why? Am I doing something wrong?

**Comment by jackc** [comment]
Should be fixed by @collinforsyth in https://github.com/jackc/pgtype/pull/146.
