### ISSUE TITLE
Pass a composite object or record or JSON to a PL/pgSQL function

### ISSUE THREAD

**Issue by cuu508** [jackc/pgx#1159]
I have a PL/pgSQL function with a growing number of arguments, that I am calling from Go code with pgx. 

I would like to bundle the arguments into a single RECORD or JSON. Is that possible to do? Let's say I have a Go struct with my data, how should I prepare it before passing it off to QueryRow? 

Thanks, and sorry for the dumb question.

**Comment by cuu508** [comment]
I figured how to pass json or jsonb: on the Go side I have to use `map[string]string` (or other key and value types). And vice-versa, if the PL/pgSQL function returns a json datatype, I could scan it into a map on the Go side.

For records and composite fields, I came across examples in pgtype docs: https://pkg.go.dev/github.com/jackc/pgtype?utm_source=godoc

IIUC, they work by creating a custom type in Postgres, retrieving its OID, then registering the custom type with pgx. Is there a way to avoid that?

**Comment by jackc** [comment]
I often use json or jsonb as it is the most convenient way to get nested data back and forth. Note that you don't have to just use `map[string]string` though. You can use anything that the `encoding/json` package can marshal and unmarshal. e.g. structs.

> IIUC, they work by creating a custom type in Postgres, retrieving its OID, then registering the custom type with pgx. Is there a way to avoid that?

There are some circumstances where registering the custom type is not necessary, but in general it is best to register custom types. Or just use json like you mentioned above.
