### ISSUE TITLE
Rollback to savepoint should not close the savepoint

### ISSUE THREAD

**Issue by AndrewDK** [jackc/pgx#1161]
https://github.com/jackc/pgx/blob/b6b24f9e8a5d7422c229b0d35330347e6e913bdb/tx.go#L370

The following sql should be valid:
```sql
BEGIN;
SAVEPOINT sp_test;
ROLLBACK TO sp_test;
ROLLBACK TO sp_test;
```
However the implementation of `dbSavepoint::Rollback` closes the savepoint after the first rollback, preventing any further rollbacks.

The fix should be as simple as not closing the savepoint.

**Comment by jackc** [comment]
You're correct for how a savepoint should behave. But the savepoint is only an implementation detail of emulating nested transactions. This change would give some pgx.Tx implementations different behavior than others. I think that should be avoided.

Now maybe it would make sense to have explicit savepoint support. But I'm not sure exactly what that would provide over the emulated nested transactions that now exist or executing savepoint commands directly.

**Comment by AndrewDK** [comment]
Understood. Perhaps a rename from `dbSavepoint` to `dbNestedTx` would save someone the confusion of expecting savepoint behavior?

**Comment by jackc** [comment]
🤷 Okay. Renamed to `dbSimulatedNestedTx`.
