### ISSUE TITLE
handling "cached plan must not change result type" error in chinese environment

### ISSUE THREAD

**Issue by Xde1997** [jackc/pgx#1162]
I have recently been meeting the "cached plan must not change result type" error and I found some solutions in the issue #927. I have tried the test program(TestStmtCacheInvalidationConn) and tracked the source code. I found that the judge result error in the source code is using English strings. But for non-English speaking countries, PostgresSql uses the local language and throws errors containing the local language.
![3MV08K5 {EQD9XNOAFC}Z 9](https://user-images.githubusercontent.com/63779168/156501079-5f53c21f-a11d-4e4e-ba5e-b87b5e199eb1.png)
How can I solve this problem?

**Comment by jackc** [comment]
Unfortunately, error code "0A000" - "FEATURE NOT SUPPORTED" is used for many different errors and the only way to tell the difference is by the message. But all that happens on match is we clear a prepared statement. So a false positive should be safe. I changed it to only look at the error code.
