### ISSUE TITLE
Scan custom types (CREATE TYPE ... AS)

### ISSUE THREAD

**Issue by tmaxmax** [jackc/pgx#1165]
If I have a custom type defined in the database schema:
```sql
create type foo as (
  name text,
  value int
);
```
and a table:
```sql
create table foos (
  id uuid primary key,
  value foo not null
);
```
how can I scan using `pgx` together with `database/sql` a `foos` row?

**Comment by jackc** [comment]
When using `database/sql` pgx can't do as much automatic handling for composite types. You'll need to implement the `database/sql` `Scanner` interface and parse the text of the result. `CompositeTextScanner` might be able to help.

**Comment by tmaxmax** [comment]
Can pgx alone handle this better then?

**Comment by jackc** [comment]
> Can pgx alone handle this better then?

Yes. Though it still is a bit of work. See `composite_type_test.go` and `custom_composite_test.go` in the pgtype repo for examples.
