### ISSUE TITLE
No support for kerberos authentication with postgreSQL

### ISSUE THREAD

**Issue by sandeepcs7** [jackc/pgx#1166]
pgx does not provide kerberos authentication support with PostgreSQL as its provided by pq package
https://pkg.go.dev/github.com/lib/pq#hdr-Kerberos_Support

Kindly provide the support for Krb authentication

**Comment by aliotta** [comment]
Would love to know if this will get prioritized at some point.

**Comment by jackc** [comment]
Check out master on github.com/jackc/pgconn. Thanks to @otan GSSAPI / Kerberos support was just added.

**Comment by otan** [comment]
We'll need to bump the pgconn here for it to work. I can submit a PR for that, but did you want to publish a new version of pgconn?
