### ISSUE TITLE
logger per connection / transaction

### ISSUE THREAD

**Issue by mhamrle** [jackc/pgx#117]
In current implementation only one logger is supported. It becomes problematic when pgx is used in multiple go-routines at the same time. It is not possible to from the logs group lines belonging to one to one transaction, to one go-routine.
When it is possible to set logger per transaction, it is possible to add context into logs and it much more readable.

**Comment by jackc** [comment]
The logger includes the pid of the backend server. This handles separating log entries by connection.

Example log:
```
INFO[02-12|08:01:56] Query                                    module=pgx sql=getUserBySessionID args=[085433b0ff2e4c5456e54cfdae097c99] time=485.04µs rowCount=1 pid=73671
INFO[02-12|08:01:56] Query                                    module=pgx sql=getFeedsForUser args=[1] time=130.084111ms rowCount=1 pid=73671
INFO[02-12|08:01:56] Query                                    module=pgx sql=getUserBySessionID args=[085433b0ff2e4c5456e54cfdae097c99] time=614.201µs rowCount=1 pid=73671
INFO[02-12|08:01:56] Query                                    module=pgx sql=getUnreadItems args=[1] time=4.874236ms rowCount=1 pid=73671
```

As far as per transaction goes, begin, commit, and rollback are logged, so that, combined with the pid should allow grouping by transaction.

Can you give me an example of what else it is you are trying to do (and what you would like pgx to do)?

**Comment by mhamrle** [comment]
I would like to add into log lines more context. For example when I have http server and have two simultaneous requests to the same handler. I would like to track each request only by grepping.

```
INFO[02-12|08:01:56] http                                     httpRequestId=0a16653e-d1a6-11e5-ab30-625662870761 request=/user-state
INFO[02-12|08:01:56] http                                     httpRequestId=67433309-ee6b-41b5-8907-3e45fd5ccae8 request=/user-state
INFO[02-12|08:01:56] Query                                    httpRequestId=67433309-ee6b-41b5-8907-3e45fd5ccae8 module=pgx sql=getUserBySessionID args=[085433b0ff2e4c5456e54cfdae097c99] time=485.04µs rowCount=1 pid=73671
INFO[02-12|08:01:56] Query                                    httpRequestId=0a16653e-d1a6-11e5-ab30-625662870761 module=pgx sql=getUserBySessionID args=[085433b0ff2e4c5456e54cfdae097c99] time=428.51µs rowCount=1 pid=73678
```

If I use only PID it is not obvious if third log line belongs to first or to second http request. My solution is to add `httpRequestId` to all logs related to one specific http request.

I think that pid is a good hint how to do it. Problem is that when I use ConnPool.Begin() to start new transaction I have no way how to get Pid from Tx struct. If it is possible to get Pid I can implement Logger interface and attach more context into logs by pid there.

One possible solution is to export Tx.conn or make getter for Tx.conn.

**Comment by jackc** [comment]
I've added several hooks that may help with this. I've added `*Tx.Conn()`, so you can now get the connection from inside a transaction. In addition, `*Conn` now has `SetLogger` and `SetLogLevel` methods. This will let you easily change the logger without jumping through any hoops. `*Tx` also now has an `AfterClose` hook. You can use this to restore the original logger.

I'd picture this being used something like the following:

```go
tx, err := pool.Begin()
if err != nil {
  return err
}
defer tx.Rollback()

// assume requestLogger is setup with your additional context
oldLogger := tx.Conn().SetLogger(requestLogger)

// Restore old logger to conn regardless of what happens to tx
tx.AfterClose(func (tx *pgx.Tx) {
  tx.Conn().SetLogger(oldLogger)
})

// Do queries here...

if err := tx.Commit(); err != nil {
  t.Fatal(err)
}

// Old logger is back
```

The only caveat is the `begin` statement is executed before the new logger is in place. If that's a problem, I think it would be fairly easy to wrap ConnPool and add a a `BeginWithLogger` method that acquired a connection, set the new logger, added a AfterClose to restore the logger, and another AfterClose to release the connection back to the pool. But I'll leave that as the proverbial exercise for the reader ;)

These changes are only on `master`, I haven't merged them to the stable `v2` branch yet.

**Comment by mhamrle** [comment]
This is all I need. Thank you
