### ISSUE TITLE
Create User in postgres with pgx (SQLSTATE 42601)

### ISSUE THREAD

**Issue by Moulick** [jackc/pgx#1173]
I am trying to create a user in postgres. I have the below

```go
package main

import (
    "context"
    "fmt"
    "os"

    "github.com/jackc/pgx/v4"
)

func main() {
    ctx := context.Background()
    conn, err := pgx.Connect(ctx, "host=localhost port=5432 user=postgres password=postgres dbname=postgres")
    if err != nil {
        panic(err)
    }
    defer conn.Close(ctx)

    // create user
    _, err = conn.Exec(ctx, "CREATE USER $1 WITH PASSWORD $2", "moulick", "testpass")
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
    }
}
```

But I get this `ERROR: syntax error at or near "$1" (SQLSTATE 42601)`

I don't get what's the problem here ?

**Comment by jackc** [comment]
Prepared or parameterized statements are only possible with `SELECT`, `INSERT`, `UPDATE`, `DELETE`, and `VALUES`. (see https://www.postgresql.org/docs/current/sql-prepare.html). You will need to use string interpolation.

**Comment by Moulick** [comment]
@jackc though, now, how do I prevent against SQL injection attacks if I am using string interpolation?

**Comment by paudley** [comment]
You'll have to sanitize the strong yourself first.   There is a fairly long-running request for non-driver dependant quoting in [Go Issue #18478](https://github.com/golang/go/issues/18478) with a few potential solutions that might be helpful.

**Comment by Moulick** [comment]
@paudley  there seems to be a Santinize function in pgx, would that not be good enough ?

**Comment by jackc** [comment]
https://pkg.go.dev/github.com/jackc/pgx/v4#Identifier will do what you want.

**Comment by jackc** [comment]
@maxlengdell See earlier reply: https://github.com/jackc/pgx/issues/1173#issuecomment-1079727101
