### ISSUE TITLE
Does CopyFrom support INET type?

### ISSUE THREAD

**Issue by omsec** [jackc/pgx#1175]
I did some experiments like this:

table:
`CREATE TABLE just_testing
(
	event_ts TIMESTAMP NOT NULL,
	client INET NOT NULL,
	user_idVARCHAR(20)
);`

struct:
`type Request struct {
	Accessed      time.Time `json:"accessed"`
	Client        string    `json:"client"`
	UserId        string    `json:"userId,omitempty"``

work:
`var rows [][]interface{}

// range loop

rows = append(rows, []interface{}{
				value.Accessed,
				value.Client,
				value.UserId})

// passing
cnt, err := t.db.CopyFrom(ctx,
			pgx.Identifier{"just_testing"},
			[]string{"event_ts", "client", "user_id"},
			pgx.CopyFromRows(rows))`

>> ERROR: invalid address family in external "inet" value (SQLSTATE 22P03)

My code works well for basic types such as string or integers, so I wonder if this is a bug or a feature request.

**Comment by omsec** [comment]
Works if explicit casting via an inet variable is used.

**Comment by jflambert** [comment]
@omsec I would appreciate a clear example
