### ISSUE TITLE
Not possible to dynamically create a table?

### ISSUE THREAD

**Issue by patientplatypus6** [jackc/pgx#1180]
I want to dynamically create and delete tables with the exec function - is this not possible? If it is can you provide documentation on how to do this (there's no examples of dynamic table creation or deletion in either the examples directory [here](https://github.com/jackc/pgx/tree/master/examples) or in the getting started guide [here](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx). 

This is important for my use case. Yes, I can understand where there may be issues where you would want to prevent SQL injection, however when orchestrating multiple docker containers and using micro-services, it would be useful to have the following work - which at the moment doesn't:

```
func CreateTables() error {
        fmt.Printf("now in CreateTables")
        var testTable = `
          CREATE TABLE TEST(
            UserID int
          )
        `
        returnval, err := connGLOBAL.Exec(context.Background(), testTable)
        fmt.Printf("value of returnval %s", returnval)
        return err
}
// returnval is empty and the table does not show in the database.
```

I've searched the net, but have not found an example of dynamic table insertion/deletion. Can you consider adding it or documentation?

**Comment by patientplatypus6** [comment]
It's possible to create a table by opening a connection using "github.com/lib/pq" but that doesn't seem ideal as that's in maintenance mode and I don't want to have to open up two connections. In case anyone else comes across this and is new to the database here's how I handled it. Maybe it will be useful.


```
package db

import(
  "fmt"
  _ "github.com/lib/pq"
  "database/sql"
  "context"
  "os"
  "github.com/jackc/pgx/v4/pgxpool"
)

const (
  host     = "SECRET"
  port     =  "SECRET"
  user     =  "SECRET"
  password = "SECRET"
  dbname   =  "SECRET"
)

var connGLOBAL *pgxpool.Pool

func DB(){
  urlExample := "postgres://pixel:exploration@164.92.157.124:5432/lightchan"
  conn, err := pgxpool.Connect(context.Background(), urlExample)
  if err != nil {
        fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
                os.Exit(1)
        }
  defer conn.Close()
  connGLOBAL = conn
  fmt.Printf("value of connGLOBAL %v", connGLOBAL)
}

func CreateTables() error {
  psqlInfo := fmt.Sprintf("host=%s port=%d user=%s "+
    "password=%s dbname=%s sslmode=disable",
    host, port, user, password, dbname)
  db, err := sql.Open("postgres", psqlInfo)
  err = db.Ping()
  if err != nil {
    panic(err)
  }
  if err != nil {
    panic(err)
  }
  defer db.Close()
  fmt.Println("Successfully connected!")
  var testTable = `
        CREATE TABLE IF NOT EXISTS TEST(
                UserID int
        )
  `
  dbret, errret := db.Exec(testTable)
  fmt.Printf("value of db %v", dbret)
  return errret
}

```

**Comment by jackc** [comment]
Something else must be going on because you definitely can create tables in an `Exec` statement. The test suite does it scores of times.

**Comment by patientplatypus6** [comment]
Huh - I must be doing something wrong then. Thanks for pointing me in the right direction.

**Comment by kataras** [comment]
@jackc is right, I can create tables on the fly using Exec too.
