### ISSUE TITLE
Unable to scan result of SUM into pgtype.Int8 or sql.NullInt64

### ISSUE THREAD

**Issue by andrewpillar** [jackc/pgx#1181]
When attempting to scan the result of a `SUM` into a `pgtype.Int8` I get the following error,

```
can't scan into dest[0]: invalid length for int8: 12
```

the column that aggregate function is being performed on is of type `BIGINT`, and allows for `NULL` values too. According to the PostgreSQL [documentation][0] arround aggregate functions, `SUM` should return a `BIGINT` when a `BIGINT` is used.

[0]: https://www.postgresql.org/docs/11/functions-aggregate.html

I have also tried using `sql.NullInt64` for the scan destination, however this fails too when there are `NULL` values present in the sum. This is most likely because of the fact that this is trying to call `strconv.ParseInt` on the returned value that is suffixed with an `e0`, therefore failing.

```
can't scan into dest[0]: converting driver.Value type string ("56623104e0") to a int64: invalid syntax
```

In essence, it looks like I am unable to scan the result of a `SUM` aggregate function into either `sql.NullInt64` or `pgtype.Int8`. The code I have in place essentially looks something like this,

```
var size pgtype.Int8 // or sql.NullInt64

q := "SELECT SUM(size) FROM build_artifacts (WHERE user_id = $1 AND deleted_at IS NULL)"

if err := db.QueryRow(q, userId).Scan(&size); err != nil {
    return err
}
```

and the schema of the database table being queried is,

```
                                        Table "public.build_artifacts"
   Column   |            Type             | Collation | Nullable |                   Default
------------+-----------------------------+-----------+----------+---------------------------------------------
 id         | integer                     |           | not null | nextval('build_artifacts_id_seq'::regclass)
 user_id    | integer                     |           | not null |
 build_id   | integer                     |           | not null |
 job_id     | integer                     |           | not null |
 hash       | character varying           |           | not null |
 source     | character varying           |           | not null |
 name       | character varying           |           | not null |
 size       | bigint                      |           |          |
 md5        | bytea                       |           |          |
 sha256     | bytea                       |           |          |
 created_at | timestamp without time zone |           | not null | now()
 deleted_at | timestamp without time zone |           |          |
Indexes:
    "build_artifacts_pkey" PRIMARY KEY, btree (id)
    "build_artifacts_hash_key" UNIQUE CONSTRAINT, btree (hash)
Foreign-key constraints:
    "build_artifacts_build_id_fkey" FOREIGN KEY (build_id) REFERENCES builds(id) ON DELETE CASCADE
    "build_artifacts_job_id_fkey" FOREIGN KEY (job_id) REFERENCES build_jobs(id)
    "build_artifacts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
```

I do have a workaround in place however, I simply query the size column instead, and perform the sum operation in code from each row that is scanned. For example,

```
q := "SELECT size FROM build_artifacts WHERE (user_id = $1 AND deleted_at IS NULL)"

rows, err := db.Query(q, userId)

if err != nil {
    return err
}

var size int64

for rows.Next() {
    var tmp sql.NullInt64

    if err := rows.Scan(&tmp); err != nil {
        return err
    }
    size += tmp.Int64
}
```

This works for my use case, I'm simply raising this to see if this is a legitimate bug, or something I'm overlooking. I'm also curious to see whether or not other people have encountered a similar issue with the return types of aggregate functions.

**Files:**

* [build_artifacts.sql.gz](https://github.com/jackc/pgx/files/8404430/build_artifacts.sql.gz) - `pg_dump` of table being queried.

**Comment by jackc** [comment]
You're right about the expected result of `sum(int)`. However, both the size of 12 bytes and the string `56623104e0` indicate that it is getting a `numeric` not a `bigint`. Can you try `select sum(size)::bigint from...` to ensure you are getting a `bigint` from PostgreSQL?

**Comment by andrewpillar** [comment]
Tried casting to `bigint` via `SELECT SUM(size)::bigint` and that worked. The value returned could be scanned into both `sql.NullInt64` and `pgtype.Int8`.
