### ISSUE TITLE
Document default `max_connections` value

### ISSUE THREAD

**Issue by patrickdevivo** [jackc/pgx#1183]
Firstly, thank you for the work you've done on this project - I have been using it for some time and am very grateful for your open source work, thank you.

I was recently struggling with a deadlock issue in my application/db interaction. Looking [here](https://github.com/jackc/pgx/blob/master/pgxpool/pool.go#L284-L287) and [here](https://github.com/jackc/pgx/blob/master/pgxpool/pool.go#L16) in the source it becomes clear that the default `max_connections` value is either 4 or the number of CPUs available, and as pointed out on [this page](https://go.dev/doc/database/manage-connections): 
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/57259/162622077-1e8dfa3a-8a1f-469a-b75d-017e7667dc13.png">

I had encountered such a deadlock when using a `*pgxpool.Pool` from more goroutines than the implicit `max_connections` when none is specified, which took me a while to figure out 😅 .

My suggestion is that a note about this default value (and possibly similarly for the other config params?) could be valuable to other users. Either in the README or the go docs somewhere. I'd like to prevent folks from doing the digging I had to do to figure out this type of issue 😄 .

As I understand, the standard lib sql package will not cap the number of connections in a pool by default, which is different behavior from `pgxpool` - which could also cause confusion.

**Comment by jackc** [comment]
I added a comment to the `pgxpool` `Config.MaxConns` field specifying the default.

But with regards to a deadlock with too low a value, that should be impossible. It can block until a connection is released by another user, but it should never deadlock. If it does that is either a bug in the pool or the calling application.

**Comment by patrickdevivo** [comment]
@jackc cool! Appreciate the addition of the comment. Yes - it was an application-caused deadlock but took me a while to understand as I hadn't realized there was a default `MaxConns` value until I dug into the source a bit. Surfacing it via a doc comment I think would've saved the trouble, and hopefully can help future users!
