### ISSUE TITLE
Addition of multiple ip format for pool connection

### ISSUE THREAD

**Issue by sovitacharya** [jackc/pgx#1184]

**Comment by sovitacharya** [comment]
Hi @jackc  Could you please add some methods where could add multiple ips for connection to the database.As We can have multiple Nodes running for a single database, so if we can  add the following feature we can directly connect to the nodes without needing to use a load balancer for the cause.

**Comment by jackc** [comment]
I think it already does what you want.

From https://pkg.go.dev/github.com/jackc/pgconn#ParseConfig:

> ParseConfig supports specifying multiple hosts in similar manner to libpq. Host and port may include comma separated values that will be tried in order.
