### ISSUE TITLE
CopyFrom fails when source contains hstore

### ISSUE THREAD

**Issue by workanator** [jackc/pgx#1187]
Hello!

`CopyFrom` command fails when I fetch data from one table containing hstore columns and copying to another. The command fails with an error like `number of pairs (576791101) exceeds the maximum allowed (26843545) (SQLSTATE 54000)`.

To reproduce the issue you can do the next steps.

1. Create two tables with the same structure and populate one with data, e.g.

```sql
create table test (hs hstore, hs2 hstore);
create table test2 (hs hstore, hs2 hstore);
insert into test2 (hs, hs2) values ('a=>1','a=>2');
insert into test2 (hs, hs2) values ('b=>1','b=>2');
```

2. Do COPYing from the populated table to the empty, e.g.

```golang
package main

import (
	"context"
	"github.com/jackc/pgx/v4"
)

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, "dbname=test")
	if err != nil {
		panic(err)
	}
	defer conn.Close(ctx)

	conn2, err := pgx.Connect(ctx, "dbname=test")
	if err != nil {
		panic(err)
	}
	defer conn2.Close(ctx)

	rows, err := conn2.Query(ctx, "select * from test2")
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	_, err = conn.CopyFrom(
		ctx,
		[]string{"test"},
		[]string{"hs", "hs2"},
		rows,
	)
	if err != nil {
		panic(err)
	}
}
```

It should fail, e.g.

```
panic: ERROR: number of pairs (576791101) exceeds the maximum allowed (26843545) (SQLSTATE 54000)

goroutine 1 [running]:
main.main()
	.../main.go:38 +0x2ee
exit status 2
```

Thank you!

**Comment by jackc** [comment]
There's a few things going on here.

First, you will want to register the hstore type on each of your connections.

```go
func registerHstore(conn *pgx.Conn) {
	var hstoreOID uint32
	err := conn.QueryRow(context.Background(), "select t.oid from pg_type t where t.typname='hstore';").Scan(&hstoreOID)
	if err != nil {
		panic(err)
	}
	conn.ConnInfo().RegisterDataType(pgtype.DataType{Value: &pgtype.Hstore{}, Name: "hstore", OID: hstoreOID})
}
```

That will at least get a better error message.

Next, it appears `pgtype.Hstore` didn't handle one of the conversions necessary. Use the master branch of pgtype to pull in that fix.

At that point it should work.

But if what you are really trying to do is copy identically structured tables between servers than you could go even faster by using the lower level pgconn copy functionality and simply `io.Copy` the `CopyTo` on the source server to the `CopyFrom` on the destination server.

**Comment by workanator** [comment]
That works! Thank you very much!
