### ISSUE TITLE
Querier interface

### ISSUE THREAD

**Issue by jfyne** [jackc/pgx#1188]
I often find myself needing to change the connection type I am passing into my functions either from a `pgx.Conn` to a `pgxpool.Conn` to a `pgx.Tx`

Are there any problems with adding a `Querier` interface? Something like

```go
type Querier interface {
	Query(ctx context.Context, query string, args ...interface{}) (Rows, error)
        QueryRow(ctx context.Context, sql string, args ...interface{}) Row
        ...
}
```

All the mentioned above could implement this and make switching input to functions easier?

```go
func getThing(ctx context.Context, conn pgx.Conn, ID string) (*thing, error) {
```
could become

```go
func getThing(ctx context.Context, conn pgx.Querier, ID string) (*thing, error) {
```
which would allow me to pass in either a `pgx.Conn`, `pgxpool.Conn` or when I need to use it within a transaction a `pgx.Tx`

**Comment by davidspiess** [comment]
This would be very useful. We use the following interface in every codebase.

```golang
type Querier interface {
	Begin(ctx context.Context) (pgx.Tx, error)
	BeginFunc(ctx context.Context, f func(pgx.Tx) error) (err error)
	Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row
	QueryFunc(ctx context.Context, sql string, args []interface{}, scans []interface{}, f func(pgx.QueryFuncRow) error) (pgconn.CommandTag, error)
}
```

**Comment by jackc** [comment]
I do the same same thing in my projects. What's kept me from adding it to pgx is the general Go wisdom about not adding interfaces solely for external use.

I also want to be able to add methods if needed without breaking backwards compatibility. I suppose documenting it as potentially breaking like `Tx` is now would be sufficient. Or a private method could be added to prevent outside implementation. That's what `testing.TB` does. That would make it harder for anyone mocking a DB though.

If this is done I think it should include all the common methods of `pgx.Tx`, `*pgx.Conn`, and `*pgxpool.Pool`. Possible names: `DB`, `DBI`, `DBConn`.

**Comment by davidspiess** [comment]
@jackc your points are indeed valid. I am perfectly fine with the approach to define the interface myself.

**Comment by jfyne** [comment]
> the general Go wisdom about not adding interfaces solely for external use.

If anyone else wants reminding here is a good source: https://github.com/golang/go/wiki/CodeReviewComments#interfaces

I'll close this, cheers for the work
