### ISSUE TITLE
Are there configurable timeouts?

### ISSUE THREAD

**Issue by konstantin-dzreev** [jackc/pgx#119]
Hi,
We have an app that uses pgx. Everything works as expected except for one thing: we did not find how to configure connection open/read timeouts. Furthermore when all pool connections are consumed the app is hanging forever instead of returning an error or a timeout.

Is it by design or did we miss anything?

Thanks!

**Comment by jackc** [comment]
How are these timeouts occurring? The default pgx config sets a 5 minute keep alive (https://github.com/jackc/pgx/blob/master/conn.go#L163). I would have expected that to stop any forever hangs.

You can also replace the Dial function in ConnConfig. That would give you more control with anything net.Dialer (https://golang.org/pkg/net/#Dialer) can do.

**Comment by konstantin-dzreev** [comment]
Aha, a custom Dial function is what we need. Having that the only missing feature for us is a timeout or immediate error when all connection of a pool are taken and a new one cannot be allocated. But, I think, we can figure something out.
Thanks a lot!

**Comment by jackc** [comment]
Cool. I think we could add a acquire timeout to ConnPool without too much difficulty. Post an issue (or PR) for this if it proves necessary.

**Comment by konstantin-dzreev** [comment]
Will do, thanks you
