### ISSUE TITLE
Successful connections continuously increase until application restarted (pgxpool)

### ISSUE THREAD

**Issue by e1engineer** [jackc/pgx#1190]
![connections](https://user-images.githubusercontent.com/53655118/164547960-e14e2c7f-ff1d-420a-baaa-a86f222f913e.jpg)

Hello everybody, we're getting this issue where pgxpool gradually eats up the CPU over time due to increasing successful connections per unit of time. The screenshot above is found in our Azure metrics. We're also getting the occasional "conn busy" error.

Following is an example of how we connect the pool:

`	config, err := pgxpool.ParseConfig(clientOptions)
	config.MaxConns = Config.DB.MaxConnections

	if err != nil {
		log.Fatal("error configuring the database: ", err)
	}

	pool, err := pgxpool.ConnectConfig(context.Background(), config)

	if err != nil {
		log.Fatal("error connecting to the database: ", err)
	}

	log.Println("DB connected successfully")
	return pool`

And how we query the db:

`	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	conn, err := database.PostgreSQL.Acquire(context.Background())

	if err != nil {
		log.Println(err.Error())
	}
	defer conn.Release()

	var json string
	err = conn.QueryRow(ctx, "SELECT ...).Scan(&json)`

We have VERY minimal traffic. Certainly not enough to warrant all the many successful connections. Logs have been checked, and indeed, postgresql is connecting like crazy on our private server. However, active connections remain at 8-10. Any ideas?

**Comment by jackc** [comment]
Is the pool exceeding its max conns? Have you used  `Pool.Stats()` to see what things look like from the Go side? Have you tried setting max lifetime and max idle time for the pool?

But my guess is somewhere there is a missing `conn.Release()` and connections are being leaked. One thing is that you only need to manually acquire and release connections if you want to perform *multiple* queries on a single connection *without* using a transaction. Otherwise you should use call the query or transaction methods directly on the pool and let it handle releasing the connection.

**Comment by e1engineer** [comment]
I'll look into this a bit more and get back to you. Thank you for your help.

**Comment by e1engineer** [comment]
The pool isn't exceeding its max conns (currently set to 500).

I checked what happens when connections aren't properly closed, and it's the Active Connections that increase in that case. The Successful Connections metric is showing how many connections are connecting at any given unit of time. The PostgreSQL logs show connections connecting at an increasing rate over time until the application is restarted.

Since Active Connections range from 8-10, the connections are being properly closed with the new code update. However, the Successful Connections (which are being closed) metric still continues to increase.

**Comment by jackc** [comment]
I don't know. I have not seen anything like that myself.

**Comment by e1engineer** [comment]
We were using Go Fiber + Azure + pgxpool, with postgres max connections set to Azure's default (~1,700).

Now we're using Go Fiber + Azure + pgbouncer, with postgres max connections set to 100. 

The CPU ramping up problem has disappeared since switching to pgbouncer and reducing the postgres max connections, although now we're initiating and closing a database connection with every request, which is a little less efficient.

It's my understanding that pgbouncer might be better for our needs since we will have multiple application servers connecting to the database (pgbouncer).

Anyway, I thought I'd update you since there seems to be some unresolved issue here that doesn't happen for very many users.

**Comment by jackc** [comment]
> It's my understanding that pgbouncer might be better for our needs since we will have multiple application servers connecting to the database (pgbouncer).

Most likely, yes.

> Anyway, I thought I'd update you since there seems to be some unresolved issue here that doesn't happen for very many users.

Thanks. Yeah, it's really strange. I haven't reproduced it myself so I don't think we can do anything more until we get some more reports.

**Comment by e1engineer** [comment]
I guess I spoke too soon. This doesn't appear to be related to pgxpool at all. 

It's still happening.

I'm closing this issue until/unless I pinpoint that it's due to pgx itself, which seems less likely now.
