### ISSUE TITLE
v5.0.0-alpha.3: encode & decode uuid (2950) <-> string

### ISSUE THREAD

**Issue by kataras** [jackc/pgx#1191]
Hello @jackc,

Before v5.0.0-alpha.x I was able to bind a *string to a postgres uuid type and insert/update a column of uuid postgres type to a go string and directly compare ids using a select query and parameters as strings but now I am getting errors like: `invalid input syntax for type uuid: "f��x.�I޺"���S/�" (SQLSTATE 22P02)` when trying to set. There was an error on scanning too but, temporarly, I "fixed" it by setting the Format to TextFormatCode when the field.DataTypeOID == `github.com/jackc/pgx/v5/pgtype.UUIDOID`. Is there a solution that doesn't require huge refactoring on existing code bases? (e.g. string to google's uuid.UUID and ::text on selecting and e.t.c.).

Thanks!

**Comment by kataras** [comment]
The alternative I found is:

```go
c, err := pool.Acquire(queryCtx)
if err != nil {
	return nil, err
}

connInfo := c.Conn().TypeMap()
connInfo.RegisterType(&pgtype.Type{Name: "uuid", OID: pgtype.UUIDOID, Codec: pgtype.TextCodec{}})
// but this is useful too:
// return fmt.Sprintf("%x-%x-%x-%x-%x", src[0:4], src[4:6], src[6:8], src[8:10], src[10:16])

c.Release()
```

**Comment by jackc** [comment]
The intent was to use an actual UUID type directly instead of string. See https://github.com/jackc/pgx-gofrs-uuid and https://github.com/vgarvardt/pgx-google-uuid for the gofrs and google UUID libraries respectively. However, I suppose it likely people will want to treat it as a string some of the time. Just added scan to string support (strings as UUID values should have already been working).

> Another question, is there any way to get the connection based on "Rows" interface? 

There isn't right now. I'd have to think through what the implications of that would be.

> I need to use its connection's *pgtype.Map to manually scan per field

Can you explain this further what you are trying to do? I don't think that should be necessary.

**Comment by kataras** [comment]
Thanks @jackc.

Is there any way to export the `connRows.conn` type of `*pg.Conn` -> `typeMap *pgtype.Map` so I can access its `func (m *Map) Scan(oid uint32, formatCode int16, src []byte, dst any) error` method which I need in order to scan per field and not per slice value?

In-short I want to be able to pass the oid, format code, buffer and destination by myself so I can make validations and error checking per struct field->column binding and this can't be done with `rows.Scan` because it accepts a value of slice and that way I can't customize neither of the above. 

My current soltuion:

```go
	c, err := pool.Acquire(queryCtx)
	if err != nil {
		return nil, err
	}
	connInfo := c.Conn().TypeMap() // cache the connInfo so I have access to its pgtype.Map.
	c.Release()
	
	db.connInfo = connInfo
```

```go
fieldPtrs, err := definition.lookupStructFieldPtrs(elem, rows.FieldDescriptions()) // my code
values := rows.RawValues()
// ....

for _, f := range fieldPtrs {
  columnValue := values[f.ValueIndex]
  err := db.connInfo.Scan(f.DataTypeOID, f.Format, columnValue, f.Dest) // <- HERE. If err is not nil I can manage the error 
  // and decide what I should do, e.g. continue to the next field or break the whole execution.
  
  // ...more code
}
```

Unfortunally, this throws an error of concurrent map writes on v5.0.0-alpha.3 and it's OK because as I see this .Scan method should be called from the same connection the query is performed to .


This is really a blocker for me atm, I can't do much :/

**Comment by kataras** [comment]
Thanks @jackc.

Is there any way to export the `Rows` -> `*connRows.typeMap` so I can access its `func (m *Map) Scan(oid uint32, formatCode int16, src []byte, dst any) error` method which I need in order to scan per field and not per slice value?

In-short I want to be able to pass the oid, format code, buffer and destination by myself so I can make validations and error checking per struct field->column binding and this can't be done with `rows.Scan` because it accepts a value of slice and it does compare the `fieldDescriptions` and the length of the dest and that way I can't customize neither of the above. 

My current soltuion:

```go
	c, err := pool.Acquire(queryCtx)
	if err != nil {
		return nil, err
	}
	connInfo := c.Conn().TypeMap() // cache the connInfo so I have access to its pgtype.Map.
	c.Release()
	
	db.connInfo = connInfo
```

```go
fieldPtrs, err := definition.lookupStructFieldPtrs(elem, rows.FieldDescriptions()) // my code
values := rows.RawValues()
// ....

for _, f := range fieldPtrs {
  columnValue := values[f.ValueIndex]
  err := db.connInfo.Scan(f.DataTypeOID, f.Format, columnValue, f.Dest) // <- HERE. If err is not nil I can manage the error 
  // and decide what I should do, e.g. continue to the next field or break the whole execution.
  
  // ...more code
}
```

Unfortunally, this throws an error of concurrent map writes on v5.0.0-alpha.3 and it's OK because as I see this .Scan method should be called from the same connection the query is performed to .


This is really a blocker for me atm, I can't do much :/

**Comment by kataras** [comment]
Thanks @jackc.

Is there any way to export the `Rows` -> `*connRows.typeMap` so I can access its `func (m *Map) Scan(oid uint32, formatCode int16, src []byte, dst any) error` method which I need in order to scan per field and not per slice value?

In-short I want to be able to pass the oid, format code, buffer and destination by myself so I can make validations and error checking per struct field->column binding and this can't be done with `rows.Scan` because it accepts a value of slice and it does compare the `fieldDescriptions` and the length of the dest and that way I can't customize neither of the above. 

My current soltuion:

```go
	c, err := pool.Acquire(queryCtx)
	if err != nil {
		return nil, err
	}
	connInfo := c.Conn().TypeMap() // cache the connInfo so I have access to its pgtype.Map.
	c.Release()
	
	db.connInfo = connInfo
```

```go
fieldPtrs, err := definition.lookupStructFieldPtrs(elem, rows.FieldDescriptions()) // my code
values := rows.RawValues()
// ....

for _, f := range fieldPtrs {
  columnValue := values[f.ValueIndex]
  err := db.connInfo.Scan(f.DataTypeOID, f.Format, columnValue, f.Dest) // <- HERE. If err is not nil I can manage the error 
  // and decide what I should do, e.g. continue to the next field or break the whole execution.
  
  // ...more code
}
```

Unfortunally, this throws an error of concurrent map writes on v5.0.0-alpha.3 and it's OK because as I see this .Scan method should be called from the same connection the query is performed to as the `pgtype.Map.Scan` performs a map write to cache the "plan scans" (Map.PlanScan). The alternative is to initialize a pgtype.Map using `pgtype.NewMap` on each new query transaction I perform but this will reduce the performance a lot, the pgx library already does that.


This is really a blocker for me atm, I can't do much :/

**Comment by jackc** [comment]
It looks like you're bypassing a lot of pgx. It may or may not be useful in this case but you find it useful sometimes to use the underlying pgconn system directly. 

I gather this is for an ORM or struct mapping in some manner. I'm reluctant to add `Conn()` to the `Rows` interface based on the general desire to keep interfaces narrow and out of concern for creating foot-gun opportunities for the unwary. Though if there is no other way I am willing. But to be honest I can't shake the feeling that this is working around a more fundamental issue either in pgx or the calling code.

On the pgx side, maybe there needs to be something like a `RowScanner` interface. A value implementing this could be passed to `rows.Scan()` and be delegated responsibility for scanning the entire row. It would make sense for that to have access to `Map`. I could see something like that being useful for various struct mapping systems.

On the calling code side, I'm still not sure all you're trying to do but it seems like there might be a way to decouple the struct/field mapping and the scanning such that this wouldn't be a problem. I don't know. Either way, skipping the normal `rows.Scan` means missing the cached scan plan per column. You still have the `Map` cache (as you ran into), but there still will be a small performance hit (map lookup vs slice index on every row after the first). May not make any real world difference, have to measure to know for sure.

**Comment by kataras** [comment]
I see but I think a feature like this should be included to the library, cache can be still achieved even if reading per column and not per row. Note that I am using this library on production and as of today I just use a pool of pgtype.Map but I am not sure if I want to keep doing it

**Comment by kataras** [comment]
I see but I think a feature like this should be included to the library, cache can be still achieved even if reading per column and not per row. Note that **it worked on pre v5.0.0 releases without concurrent map write errors**. As of today I just use pgx.v5 and a pool of pgtype.Map but I am not sure if I want to keep doing it.

**Comment by jackc** [comment]
Well, believe it or not I didn't forget about this.

Ultimately, I did come around to adding it to the `Rows` interface. The only caveat is that not all `Rows` implementations actually have an underlying connection. e.g. `RowsFromResultReader` is used to create a `Rows` from a `*pgconn.ResultReader`. So in theory, you need to be able to gracefully handle `Conn()` returning `nil`. But if this is for ORM'ish code that wraps pgx and only calls `Query` it should always be available.
