### ISSUE TITLE
Query timeout context not throwing errors for certain durations

### ISSUE THREAD

**Issue by breakbuidl** [jackc/pgx#1198]
Below mentioned code works fine when I set context timeout duration to something like `~ 200 milliseconds`, but if I set set it to seconds say `2000 * time.Millisecond` or `2 * time.Second`, then it does not throw any error.

Here, pg_sleep(10) is used to simulate an actual query that takes a long time.

```
var DB *pgxpool.Pool
DB, err = pgxpool.Connect(context.Background(), fmt.Sprintf(...login credentials...))

ctx, cancelCtx := context.WithDeadline(context.Background(), time.Now().Add(2000 * time.Millisecond))
defer cancelCtx()
	
rows, err := database.DB.Query(ctx, `select pg_sleep(10)`)
if err != nil {
	fmt.Println(err.Error())
}
```
100ms   - Error
200ms   - Error
250ms   - No error
300ms   - No error
500ms   - No error
1000ms - No error
2000ms - No error

pgx version - `v4.14.1`

**Comment by jackc** [comment]
You need to read the results. The `err` returned from `Query` will only be non-nil if there was a problem sending the query. It doesn't wait to read the results.
