### ISSUE TITLE
Add support for Unix sockets on Windows

### ISSUE THREAD

**Issue by enocom** [jackc/pgx#1199]
Windows has added [support for Unix sockets](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/). Postgres also includes support for [Unix sockets on Windows](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS):

> On Unix, an absolute path name begins with a slash. On Windows, paths starting with drive letters are also recognized.

Right now, pgx (through pgconn) does not support using a Unix socket on Windows and instead assumes all Unix sockets begin with a forward slash. If pgx were to change this assumption, pgx would support Unix sockets on Windows. Using a forked copy of pgconn, I've verified this change works on Windows Server 2019. 

Here are the two places that would need to change:

1. https://github.com/jackc/pgconn/blob/beb4e2cfbcd7f41e6389254496cc5feae7d99d9c/pgconn.go#L190
2. https://github.com/jackc/pgconn/blob/84e8238fa074e88b15e2737f4d8a0a8abb1ae6bf/config.go#L106

Rather than:

``` golang
if strings.HasPrefix(fb.Host, "/") {
  // ...
}
```

The code could be:

``` golang
if strings.HasPrefix(fb.Host, "/") || isWindowsPath(fb.Host) {
  // ...
}
```

where `isWindowsPath` checks if the provided string begins with a capital letter A-Z followed by a colon and a backslash (e.g., `C:\`).

Would there be any interest in accepting this feature request?

**Comment by jackc** [comment]
Sounds good to me.

**Comment by enocom** [comment]
I'll send a PR.
