### ISSUE TITLE
Utility to replace parameters of queries with actual values?

### ISSUE THREAD

**Issue by tmaxmax** [jackc/pgx#1201]
Does this package have an utility that replaces PostgreSQL placeholders with actual values in queries? For example, given the query
```sql
SELECT * FROM tbl WHERE a = $1 AND b = $2 OR c = $1
```
and the arguments `["foo", 5]`, the utility returns
```sql
SELECT * FROM tbl WHERE a = 'foo' AND b = 5 OR c = 'foo'
```
If it doesn't have anything like this exported, is there some source code that can help me implement this? My use case is query logging - I want to implement a `pgx.Logger` that outputs the queries with the placeholders replaced with the actual arguments.

**Comment by jackc** [comment]
The `internal/sanitize` package is what you're looking for. It is what pgx uses to substitute placeholders when it can't use true parameterized queries.
