### ISSUE TITLE
Scaning array aggregates of type []integer into arrays via standard library interface

### ISSUE THREAD

**Issue by wbl** [jackc/pgx#1202]
I've been trying to fill a field of a struct  that is []uint64 with the values of an aggregate that postgress says is integer[]. However when I run the scan I get the following error: "sql: Scan error on column index 4, name "array_agg": unsupported Scan, storing driver.Value type string into type *[]uint64" and I'm very not sure what to do. I've tried using an []int instead and that didn't work either.

This is using the database/sql interface and the compatibility layer: perhaps that's the root of the issue.

**Comment by wbl** [comment]
Doesn't work with an []int32, which is the right matching numeric type according to the documentation. I will try doing it without database/sql via direct and see if that works.

**Comment by jackc** [comment]
It should work with the native interface. The `database/sql` does not provide the required hooks to transparently handle this case.

You can use `pgtype.Int4Array` to support `integer[]` in `database/sql`. In `v5` it is streamlined a bit more with `pgtype.Map.SQLScanner`. But `v5` is only in alpha and should only be used for testing (unless you are very brave).

**Comment by wbl** [comment]
Sure enough it worked with the direct interface. There were some go bugs that made me think the ``database/sql`` situation had been improved, but guess not.
