### ISSUE TITLE
How to use logging with stdlib

### ISSUE THREAD

**Issue by lzap** [jackc/pgx#1205]
Hello,

is it possible to configure logging when using database/sql (stdlib) interface? We are currently evaluating sqlx for our application and the lack of logging in the standard library is a bummer. I cannot figure this out, so I am asking if you could confirm this to me.

If that's the case, I am considering submitting a proposal to change to pgx native interface with scanny library for our application. It has less github stars but on the other hand it's more simple.

Thanks!

**Comment by jackc** [comment]
You can use the normal pgx logger with stdlib. An example of exactly that is near the top of the docs. https://pkg.go.dev/github.com/jackc/pgx/v4@v4.16.1/stdlib

**Comment by lzap** [comment]
Oh how could I miss it, amazing. Thanks for help and for such a fine library to work with! Cheers.

**Comment by gorjan-mishevski** [comment]
<img width="129" alt="Screenshot 2024-07-30 at 16 26 56" src="https://github.com/user-attachments/assets/d2f08f2c-c932-485d-84f0-a347ba458edf">
It seems this has been removed.

**Comment by lzap** [comment]
Some things were moved into a different library.

**Comment by jackc** [comment]
`stdlib.OpenDB` should still allow you to set whatever pgx config you want including logging, and use that to create a `*sql.DB`.
