### ISSUE TITLE
Batch transactions and Foreign key constraints

### ISSUE THREAD

**Issue by sheldondz** [jackc/pgx#1206]
we have just started using pgx for its simplicity,  we came across one issue with  Batch statements and transactions

Transactions are rolled back if a foreign key constraint fails, but the api does not return an error

```
ctx := context.Background()
	tx, err := t.DBpool.Begin(ctx)
	if err != nil {
		return nil, fiber.NewError(fiber.StatusInternalServerError, err.Error())
	}
	defer tx.Rollback(ctx)
	batch := &pgx.Batch{}
	batch.Queue("UPDATE public.assets SET pic = $1 WHERE id = decode($2,'hex')", true, "")
	batch.Queue("INSERT INTO public.asset_uploads(tx_id, asset_id, url) VALUES($1, $2, $3)",
		txn.TxId, txn.assetId, txn.url)
	br := tx.SendBatch(ctx, batch)
	_, err = br.Exec()
	if err != nil {
		return nil, err
	}
	br.Close()
	tx.Commit(ctx)

```
if there is a foreign key constraint failure here the transaction rolls back but this line does not return an error

```
br := tx.SendBatch(ctx, batch)
_, err = br.Exec()
```

**Comment by jackc** [comment]
It's hard to tell without the table schema but wouldn't the error be expected the second time you call `br.Exec`?

Also, you should check the result of `br.Close()`. It can return an error as well.

**Comment by sheldondz** [comment]
So when inserting a record the id set which depended on a foreign key constraint did not exist in the table, as a result the transaction was rolled back. I missed checking the error returned from ``` br.Close() ``` will run this and confirm.

**Comment by sheldondz** [comment]
as expected ```br.close()``` throws the error.
