### ISSUE TITLE
Does pgx support the use of sslpassword?

### ISSUE THREAD

**Issue by dbgreen** [jackc/pgx#1207]
sslpassword was introduced with pg13-- I have not been able to find any mention of it within the pgx library.  Is it supported by pgx?

**Comment by jackc** [comment]
Sorry, it does not.

**Comment by ericmack** [comment]
Jack , is this something you would accept as a pull request , if we did the heavy lifting>

Eric

**Comment by ericmack** [comment]
Sounds good, thanks will proceed accordingly.
