### ISSUE TITLE
BeforeAcquire role change

### ISSUE THREAD

**Issue by sheldondz** [jackc/pgx#1210]
we have setup up RLS for some of our tables, and also have some predefined roles in the DB. Is it possible to switch the user role in BeforeAcquire? right now the conn object contains the user thats part of the connection string.

**Comment by jackc** [comment]
Yes. `BeforeAcquire` receives the context that `Acquire` was called with. You could include the information about what role to change to in the context. Obviously, you will need to take care that this role information is always set or reset to avoid accidentally running a query with the wrong user. Presumably your `BeforeAcquire` would reset to a default role if no role was specified. You might also want to look at using `AfterRelease` to reset the role.

**Comment by sheldondz** [comment]
Yes i have added implementations for ``` BeforeAcquire ``` and ``` AfterRelease ```, to perform the cleanup after the request is completed. I am just a little confused as to what do i need to change in the context for this role switch to happen.

I tried executing a 

``` set_config('','', true) ``` but the roles does not seem to change.

**Comment by jackc** [comment]
> Is there a way to throw an error in beforeAcquire if an illegal role is passed

There's nothing special about `BeforeAcquire`. Whatever you would do normally with your connection to check if it worked can be done there. The only difference is if you return an error it checks out another connection and tries again.

> right now it just hangs

If you have a `BeforeAcquire` that always fails it will get stuck in an infinite loop. See

```go
func (p *Pool) Acquire(ctx context.Context) (*Conn, error) {
	for {
		res, err := p.p.Acquire(ctx)
		if err != nil {
			return nil, err
		}

		cr := res.Value()
		if p.beforeAcquire == nil || p.beforeAcquire(ctx, cr.conn) {
			return cr.getConn(p, res), nil
		}

		res.Destroy()
	}
}
```

Perhaps there should be a fail-safe limit on how many times to retry, but `BeforeAcquire` always failing is an application error.
