### ISSUE TITLE
Using a custom JSON encode/decoder in v5

### ISSUE THREAD

**Issue by pscott31** [jackc/pgx#1215]
Hi there, thanks for the great work.

I'm trying to port my code over to use v5 and have mostly wrapped my head around how the new codec system works and have got all our custom `enum`/`bytea` go types mapped by implementing the right interfaces. However I'm stuck when it comes to JSON.

We have some protobuf objects that need to us a custom json marshaller (protojson); in v4 I did this:

```
func (l MyProtoObject) EncodeBinary(_ *pgtype.ConnInfo, buf []byte) ([]byte, error) {
	protoBytes, err := protojson.Marshal(l)
	if err != nil {
		return buf, fmt.Errorf("failed to marshal MyProtoObject: %w", err)
	}
	return append(buf, protoBytes...), nil
}

func (l *MyProtoObject) DecodeBinary(_ *pgtype.ConnInfo, src []byte) error {
	return protojson.Unmarshal(src, l)
}
```

But as far as I can see in v5, there's no JSON/JSONB codec interface I can implement, like I did for my enum types by implementing `TextValue` and `ScanText`

**Comment by jackc** [comment]
Are you saying your types can't implement `MarshalJSON` and `UnmarshalJSON`? Can your type implement them and in that call your protojson functions.

I suppose we could add the JSON/JSONB type back if necessary, but I don't understand the problem at the moment.

**Comment by pscott31** [comment]
The trouble is the types are generated by protoc, so I don't have direct control over them.. though I was actually unaware of MarshalJSON and UnmarshalJSON (this is all a bit new to me, I'm from a world of python and SQLAlchemy :), I might be able to get around this by making a trivial container struct and doing as you suggest.. 

Though it seems slightly asymmetrical that for most of the other types you have separated out the codec from the marshalling to a value type.. but honestly it probably just needs me to figure things out a bit more. I'll have another bit of a play and re-open this issue if I can't figure out out.

**Comment by paulhobbel** [comment]
Hi I just found a solution, you can use this [protoc plugin](https://github.com/mfridman/protoc-gen-go-json) to generate the `MarshalJSON` and `UnmarshalJSON` functions. It will use `protojson` to generate the JSON.
