### ISSUE TITLE
Difference compared to `pgdriver`, why?

### ISSUE THREAD

**Issue by frederikhors** [jackc/pgx#1217]
I just found out [pgdriver](https://github.com/uptrace/bun/tree/master/driver/pgdriver) which has amazing benchmarks compared to `pgx`.

Can I ask you why such a difference?

And if **are there any plans to improve this in the future?**

Thanks.

- Benchmark project: https://github.com/go-bun/bun-benchmark

- Benchmark results (with `github.com/jackc/pgx/v4 v4.11.0`):

  ```
  BenchmarkInsert/pg-12 	    	    7254	    148380 ns/op	     900 B/op	      13 allocs/op
  BenchmarkInsert/pgx-12         	    6494	    166391 ns/op	    2076 B/op	      26 allocs/op
  BenchmarkSelect/pg-12          	    9100	    132952 ns/op	    1417 B/op	      18 allocs/op
  BenchmarkSelect/pgx-12         	    8199	    154920 ns/op	    3679 B/op	      60 allocs/op
  ```

**Comment by jackc** [comment]
> Can I ask you why such a difference?

Two big reasons.

1. It is using `database/sql` instead of the pgx native interface. The `database/sql` layer adds some overhead.
2. It forces pgx to use the simple protocol. This disables binary format support and automatic prepared statement caching. This significantly reduces pgx's performance.

**Comment by frederikhors** [comment]
Oh. Can you suggest changes so I can PR that project?

**Comment by jackc** [comment]
> Oh. Can you suggest changes so I can PR that project?

I haven't used bun, but a quick glance at the benchmark repo indicates that may be difficult.

bun targets `database/sql` so there is probably nothing that can be done about the first problem. It's probably not reasonable to expect it to make a special code path for pgx.

As for the simple protocol, there is this comment in the benchmark:

```
	// Bun does not work with prepared statements, because it formats query args itself
	// and passes nil args to drivers.
	config.PreferSimpleProtocol = true
```

It may be that bun's architecture is simply incompatible with the pgx's optimal mode of operation.
