### ISSUE TITLE
Wrong type when using named parameters

### ISSUE THREAD

**Issue by ecerichter** [jackc/pgx#1218]
Maybe I've found a corner case for named parameters, or perhaps, more than one.

Example 1:

Table structure:
create table provider (id integer primary key, description text, tag text, document varchar(14));

Query:
select id, description, tag, document from provider where left(document, 12) = left(@document, 12)

Results in error:
"cannot convert [00428307001836] to Text"

(note: 00428307001836 is of type string)

Example 2:

Table structure:
create table discriminator_text (id smallint primary key, description text, rounding_mode smallint);

Query:
select id, description, rounding_mode from discriminator where id = @id

Results in error:
"cannot convert [4] to int2"

(note: 4 is of type int)

**Comment by jackc** [comment]
Does this happen run the exact same query except using `$1` and normal arguments? That's all `NamedArgs` should be doing. So I don't see how it could be responsible for this type of error.

Do you have a test case?

**Comment by bfontaine** [comment]
Ping @ecerichter?

**Comment by ecerichter** [comment]
Hi. I've a complex code using interfaces and maps everywhere, and adapting the code to use type check and explicit casting made the error go away. I don't have a case anymore.
Thanks for your thoughs and for gently help :-)

Regards,

ER.
