### ISSUE TITLE
IPv4 networks converted to IPv4-mapped IPv6 networks when passed as a slice

### ISSUE THREAD

**Issue by horgh** [jackc/pgx#1219]
Hi!

I noticed an interesting behaviour when I passed a slice of IPv4 networks - I matched IPv6 networks that I did not expect. This lead me to finding that the networks were being translated to IPv4-mapped IPv6 networks.

For example, if I pass a paramer containing `[]string{"0.0.0.0/8"}`, then the parameter given to Postgres becomes `'{::ffff:0.0.0.0/8}'`.

I'm using pgx v4.16.1 and Go 1.18.2.

I have an example program demonstrating this:

```go
package main

import (
  "database/sql"
  "log"

  _ "github.com/jackc/pgx/v4"
  _ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
  db, err := sql.Open(
    "pgx",
    "database=snip user=snip password=snip host=localhost port=5432",
  )
  if err != nil {
    log.Fatal(err)
  }

  var o string
  err = db.QueryRow(
    `
      SELECT jsonb_build_object(
        'contained1', '0:0:ffff::/64'::inet <<= any($1::inet[]),
        'contained2', '0:0:ffff::/64'::inet <<= $2::inet,
        'contained3', '0:0:ffff::/64'::inet << any($3::text[]::inet[]),
        'input1',     $1::inet[],
        'input2',     $2::inet,
        'input3',     $3::text[]::inet[]
      )
    `,
    []string{"0.0.0.0/8"},
    "0.0.0.0/8",
    []string{"0.0.0.0/8"},
  ).Scan(&o)
  if err != nil {
    log.Fatal(err)
  }
  log.Printf("%s", o)
}
```

This outputs (reformatted for readability):

```json
{
    "input1": ["::ffff:0.0.0.0/8"],
    "input2": "0.0.0.0/8",
    "input3": ["0.0.0.0/8"],
    "contained1": true,
    "contained2": false,
    "contained3": false
}
```

I'm thinking the "input3" case would be the expected behaviour. What do you think?

Thank you! pgx is awesome by the way :-).

**Comment by horgh** [comment]
Thank you for looking at it! I tried to track this down and made https://github.com/jackc/pgtype/pull/166.

**Comment by horgh** [comment]
One issue with the PR so far is this kind of situation:

```
# select '0.0.0.0'::inet <<= '::ffff:0.0.0.0/104'::inet;
 ?column?
----------
 f
(1 row)
```

As the PR stands, we normalize the IPv4-mapped IPv6 input to IPv4, the above would become true from the perspective of Go code. I'm not sure there's a great way to avoid it. We could detect the string is IPv6 by looking for ":" and only doing the normalizing if it doesn't look like IPv6, but that seems a bit hacky. A colleague pointed out that `net/netip` wouldn't have these issues, so perhaps using that in the future would be an option?

**Comment by horgh** [comment]
Although for IP input (as opposed to CIDR input), we were already doing this (i.e., normalizing `::ffff:0.0.0.0` to `0.0.0.0`), so doing this with CIDRs as well seems consistent at least.

**Comment by jackc** [comment]
I must confess that I'm not very familiar with how exactly IPv4 should be handled in combination with IPv6. The existing normalization code may be wrong and I may not being seeing all the implications of this issue.

The existing code's  goal was to solve the problem of an IPv4 string being parsed into an IPv6 net.IP. The conversion of an IPv6 address that happens to be in the IPv4 space to IPv4 was unintentional.

```{source: "::ffff:0.0.0.0/104", result: pgtype.Inet{IPNet: &net.IPNet{IP: net.ParseIP("0.0.0.0").To4(), Mask: net.CIDRMask(8, 32)}, Status: pgtype.Present}},```

The above line from the tests in the PR definitely strikes me as unexpected behavior.

> We could detect the string is IPv6 by looking for ":" and only do the normalizing if it doesn't look like IPv6, but that seems a bit hacky.

That might not be a bad idea. But I would probably go so far as to say we never normalize it if it has a ":". If someone has an IPv4 address in IPv6 format then we should leave it there.

> A colleague pointed out that net/netip wouldn't have these issues, so perhaps using that in the future would be an option?

Yes. I definitely want to look into this at least for pgx v5. Not sure it could be integrated into v4 in a transparent, backward compatible way.

**Comment by horgh** [comment]
Thank you! I've updated my PR to leave IPv6 addresses as is.

One thing I noticed was there are a few other `To4()` calls in surrounding code - in `DecodeText()` and `DecodeBinary()`. It's possible we would want to do something similar to those uses. Although I'm not sure. We could probably do that in a separate change if so though.
