### ISSUE TITLE
Unable to connect to postgres using GSSAPI encrypted connection

### ISSUE THREAD

**Issue by Sireax** [jackc/pgx#1220]
I am using kerberos authentication to connect to postgres. In **pg_hba.conf** there is a separate host type `hostgssenc`, which enables secure data transport between client and server. If I use this line:

`host    all    all     0.0.0.0/0    gss include_realm=1 krb_realm=DOMAIN1.LOCAL`

everything works fine. However, the connection is not secure.
If I change `host` to `hostgssenc`, I get this error:

**failed to connect to host=postgres user=testuser@DOMAIN1.LOCAL database=vault: server error (FATAL: no pg_hba.conf entry for host "172.18.0.2", user "testuser@DOMAIN1.LOCAL", database "vault", no encryption (SQLSTATE 28000))**

If I connect to postgres via **psql**, the connection becomes secure along with authentication.

I suppose this error may be related to **gokrb5** library, but I'm not sure

**Comment by Sireax** [comment]
I tried to change **DisablePAFXFAST** and **AssumePreAuthentication** settings, but this makes no effect

**Comment by bfontaine** [comment]
I don’t understand how this issue has anything to do with pgx(?)
