### ISSUE TITLE
How to handle multiple DB connection pools in a single application?

### ISSUE THREAD

**Issue by pavinil** [jackc/pgx#1221]
Hi. I'm developing a Saas application in which each organization will have their own database within the same postgres server. At present I am using pgxpool to connect to a single database. I plan to implement multi db connections by using a map[string]*pgxpool.Pool and using a RWlock to access the pools for a specific database. 
Is this method acceptable? Or is there a better way to do this? Any input would be extremely helpful. Thanks!

**Comment by jackc** [comment]
That would work on the Go / pgx side, but if you have many tenants you will have *many* connections to the PostgreSQL server -- quite possibly more than the server can handle.

**Comment by pavinil** [comment]
Thank you Jack!

**Comment by pavinil** [comment]
Closing this issue
