### ISSUE TITLE
`conn busy` error on inserts

### ISSUE THREAD

**Issue by stokito** [jackc/pgx#1226]
Sorry but could you create a wiki page with basic usage examples? Probably for those who already know Go's sql package this is clear but I stared directly from the pgx.
For now I simply need to record visits and I wrote the following:
```go
// on app start connect to db
dbConn, dbErr = pgx.Connect(context.Background(), DatabaseUrl)
// on app shutdown disconnect
dbConn.Close(context.Background())
// on user visit
_, sqlErr := dbConn.Exec(context.Background(), "INSERT INTO visit ($1)", userId)
```
This works perfectly on my PC (Windows, PG14) but on prod (Ubuntu 22, PG14) this insert always fails with `conn busy` error. The load is about 3 RPS so this is not an overload.
Even more: I started locally the app and configured the remote DB and it works. But I didn't tested concurrent requests. I have no idea why this may happen. In the `pgconn.go` I found the error:
```
// lock locks the connection.
func (pgConn *PgConn) lock() error {
switch pgConn.status {
case connStatusBusy:
    return &connLockError{status: "conn busy"} // This only should be possible in case of an application bug.
```

I the `lock()` is called from the `Exec()` method.
Can anybody give me a hint how to fix this?

Also few another questions:
1. Should I manually open tx and commit it on each insert? Looks like the `Exec()` opens a tx itself.
2. How to use a prepared statement for the insert to make it faster?
3. I though that PG has some kind of binary protocol that can be used to perform an insert without explicit SQL `INSERT` statement. Or I mistaken? 

Thank you

**Comment by stokito** [comment]
I just noticed that first errors I see only after 3 minutes after server restart. Maybe there is some timeout.

**Comment by jackc** [comment]
A `*pgx.Conn` is not concurrency safe. You probably want a `*pgxpool.Pool`.

**Comment by stokito** [comment]
Thank you, looks like concurrent inserts are failing and all following inserts failing too. I checked logs and I again see the errors. I created the pool similarly as in the example https://github.com/jackc/pgx/blob/master/examples/url_shortener/main.go

And then wrote:

	dbConn, err := pool.Acquire(context.Background())
	dbConn.Exec(context.Background(), "INSERT INTO visit ($1)", userId)
	dbConn.Release()

Now it looks working. Now I need to understand how to prepare statement for the pool.
If you can improve documentation or examples that would be great. Thank you

**Comment by jackc** [comment]
> And after some time again I see the conn busy errors.

`conn busy` error should never occur. It means either a bug in the calling code or pgx.

> I don't know why it's happening again, maybe I should increase MaxConns for the pool.

At best that would only hide the problem.

> Instead of the pool.Acquire() to get a directly connection and then calling the dbConn.Execute I used the pool.Execute(). 

Right. In general it is simpler to use the pool methods when you only need to run one command at a time.

---

You also might want to run your application with the race detector on.

**Comment by krisdiano** [comment]
maybe you forget defer, `defer dbConn.Close(context.Background())`

**Comment by stokito** [comment]
Should I close the connection after each request? I.e. this is not a "close" but "release"?
Because now I opening the connection only once on start app and closing on shutdown

**Comment by hnimminh** [comment]
@stokito Does your issue solved?
