### ISSUE TITLE
Prepare query Statements ahead of time

### ISSUE THREAD

**Issue by tomasger** [jackc/pgx#1227]
I am currently building a load test, which will later essentially evolve into a service that is collecting large amounts of data points and inserts them into the DB by using `pgxpool.Pool` and moderately sized `pgx.Batch`.

In my specific case, I have around 250 tables, and each of them have a this exact query (only `table_name` is changing):
```sql
INSERT INTO table_name (time, id, metric_name, metric_value) VALUES ($1, $2, $3, $4);
```
My `pgx.Batch` contains around 1000 such queries and usually there's at least one insertion to all of the 250 tables I have.

When I first start the program, it takes around 30 seconds for every connection in the pool to insert the first batch, going down to below 1 second for subsequent ones. I've narrowed down the cause of this slowdown to `stmtcache.Cache` and `PREPARE` statement sent to the DB. 

Now since my use case consists of sending the same 250 static queries, I had these questions (I'm not too experienced in databases, so I do apologize if I missed something very basic here):

1. Is there a way to avoid querying the database to prepare these statements every time I run the service, but still utilize the extended protocol?
2. If it's necessary to have this preparation, is there a way to do it without inserting the data?
3. Can the `stmtcache.Cache` be shared across all the `pgxpool.Pool` connections?

**Comment by jackc** [comment]
> Is there a way to avoid querying the database to prepare these statements every time I run the service, but still utilize the extended protocol?

Yes, but it's not very convenient with the current version of pgx. `v5` may make it a bit easier.

> If it's necessary to have this preparation, is there a way to do it without inserting the data?

You could explicitly prepare statements, but that gets messy because prepared statements exist on the connection level not on the pool level.

> Can the stmtcache.Cache be shared across all the pgxpool.Pool connections?

No. Prepared statements, even the automaticly managed ones, are per connection.

---

I wouldn't expect it to be as slow as you are experiencing. Preparing a statement should be really fast. The primary cost is the network round trip. Do you have a high latency connection to the database?

**Comment by tomasger** [comment]
> I wouldn't expect it to be as slow as you are experiencing. Preparing a statement should be really fast. The primary cost is the network round trip. Do you have a high latency connection to the database?

That's a good catch, thank you, transmission was happening between US and EU, I ran it on the same region (as will be expected in production environment), and it effectively dropped from 30s to 4s. https://github.com/jackc/pgx/blob/a814153aebbd5fc8b037f535ff8d1e54209247a8/conn.go#L756

I do think it would be neat to have `stmtcache.Cache` in the code above to do all queries for unprepared statements in a single batch, definitely not as much of an issue when it takes 4s though.

> Yes, but it's not very convenient with the current version of pgx. `v5` may make it a bit easier.

If not too much trouble, could you give some pointers on how to go about it? From my initial code exploration it seemed like its an internal implementation and I can't do much if I continue using `pgx.Batch` and `conn.SendBatch`.

**Comment by jackc** [comment]
> I do think it would be neat to have stmtcache.Cache in the code above to do all queries for unprepared statements in a single batch, definitely not as much of an issue when it takes 4s though.

That would be a good improvement.

>> Yes, but it's not very convenient with the current version of pgx. v5 may make it a bit easier.

> If not too much trouble, could you give some pointers on how to go about it? From my initial code exploration it seemed like its an internal implementation and I can't do much if I continue using pgx.Batch and conn.SendBatch.

You can drop down to the pgconn layer and use `ExecBatch`. As I said, not very convenient.

**Comment by jackc** [comment]
I've just pushed code to `v5-dev` that uses new underlying pipeline mode functionality to optimize this case. `SendBatch` will now use a single round trip to prepare / describe all unique parameterized queries instead of one per each.
