### ISSUE TITLE
Issue scanning numeric into *string

### ISSUE THREAD

**Issue by xv-ethan-v** [jackc/pgx#1230]
Hi, 

I'm attempting to scan a numeric into a `*string`, but this results in an error:
```
err := row.Scan(..., &x.Amount, ...)

<pgx.ScanArgError>: {
    ColumnIndex: 5,
    Err: <*errors.errorString | 0xc00023ade0>{
        s: "unable to assign to *string",
    },
}
can't scan into dest[5]: unable to assign to *string
```

The wiki page (https://github.com/jackc/pgx/wiki/Numeric-and-decimal-support) leads me to believe that this should be possible.
As I'm not doing any calculations on the value, I'd prefer to avoid the shopspring dependency if possible and use a string.

**Comment by jackc** [comment]
It's possible when using the text format, but stringifying the binary format gets a little trickier. The functionality is in the v5 alpha but wasn't in v4. I just backported it. Try master of github.com/jackc/pgtype.
