### ISSUE TITLE
Parallel queries

### ISSUE THREAD

**Issue by lrweck** [jackc/pgx#1236]
Hi!
Is it possible to run two queries in parallel inside a transaction? I basically have to do a bunch of selects to check various things and it would be really useful if I could do them inside goroutines. I get that using the same connection to run the queries might make this hard (hopefully not impossible)

**Comment by jackc** [comment]
> (hopefully not impossible)

Sorry, PostgreSQL can only execute one query at a time on one connection. You could use a `Batch` to send all the queries at once to minimize network time but there is no way to run multiple queries in parallel on the same connection.
