### ISSUE TITLE
"unexpected message type" error

### ISSUE THREAD

**Issue by nagylzs** [jackc/pgx#1237]
Today I accidentally put a backslash at the end of my database password config. Suprisingly, pgx.Connect() call returned an error with this message:

"unexpected message type"

If the password does not end with a backslash, then it works just fine.

I think this might be some internal bug. You can easily test this by appending a backslash to the end of a password and trying to connect to a database.

**Comment by nagylzs** [comment]
I'm sorry I was mistaken. The password ended with a double quote, not a backslash.

**Comment by jackc** [comment]
Can you provide a complete example? I am unable to duplicate with the following:

```go
package main

import (
	"context"
	"log"

	"github.com/jackc/pgx/v4"
)

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, `host=localhost user=jack password="something\""`)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(ctx)

	var n int32
	err = conn.QueryRow(ctx, "select 1").Scan(&n)
	if err != nil {
		log.Fatal(err)
	}

	log.Println(n)
}
```

I get the expected error:

```
2022/06/30 20:37:09 failed to connect to `host=localhost user=jack database=pgx_issues`: failed SASL auth (FATAL: password authentication failed for user "jack" (SQLSTATE 28P01))
exit status 1
```

**Comment by jackc** [comment]
Ah. `v3` hasn't had any updates in a long time. `v4` is almost 3 years old at this point. I would recommend upgrading.

**Comment by nagylzs** [comment]
I still think that the error message is wrong, but if v3 is not supported anymore, then we can close this. I'm upgrading to v4.

**Comment by jackc** [comment]
I suppose I could still merge changes to `v3` if someone was submitted them, but the last PR for it was almost 2 years ago and I am not personally writing any code for `v3`.
