### ISSUE TITLE
Unexpected EOF when using with database/sql

### ISSUE THREAD

**Issue by numberZero** [jackc/pgx#1238]
Very similar to #1018, but happens on database/sql using pgx as the driver and regular PostgreSQL 14 as the server. Should the connection time out, or the server die unexpectedly (e.g. SIGKILL), DB.Begin returns the “Unexpected EOF” error. To my understanding, it’s pgconn returning that error instead of ErrBadConn (which would cause DB.BeginTx to reconnect), although in some cases it does return ErrBadConn.

**Comment by bfontaine** [comment]
Does it make sense to keep this issue open now that we have #1435?

**Comment by numberZero** [comment]
#1435 is a duplicate. But as it got way more attention than this one...
