### ISSUE TITLE
Making a wrapper for database access

### ISSUE THREAD

**Issue by conor-tread** [jackc/pgx#1239]
From all the stuff I read the way to get data from a database involves calling Query (or whichever method you like) and then doing rows.Next and calling scan on the row.

The problem I have with this is that at that point i need to know what fields I am looking for. So if I want to create a wrapper for database access I cant. I cant just make a wrapper, call Query from that and have an array of interface{}'s or even the typed struct passed back. Is my understanding correct in this? 

What I have to do now: 

```
rows, err := db.Query("select id, name from users where id = ?", 1)
if err != nil {
    log.Fatal(err)
}
defer rows.Close()
for rows.Next() {
    err := rows.Scan(&id, &name)
    if err != nil {
        log.Fatal(err)
    }
    log.Println(id, name)
}
```

What I would like: 

```
results, err := dbWrapper.Query("select id, name from users where id = &d", 1)
if err != nil {
    log.Fatal(err)
}
for i, v := range results {
   myObj := v.(myStruct)
   ///do what i need to with the struct value
}
```

The second way I dont need to know what fields im looking for in every query like i do with Scan.
The Wrapper would still need to iterate through the results probably but it shouldnt need to know what fields each query wants and it would return []interface{}.

Its also wildly innefficient to have to iterate through the results twice, so if that could be avoided that would be great.

Is something like this possible in anyway? I know im asking for a lot here but having to use Scan with all the fields already known jsut seems really awkward to me

**Comment by jackc** [comment]
You have a number of options.

1. Call `FieldDescriptions()` on rows. This will tell you the column names and types that were returned.
2. Use `Values()` instead of `Scan()`
3. For struct mapping maybe use https://github.com/georgysavva/scany

**Comment by conor-tread** [comment]
Can you tell me why something like this wont work?

```
        rows, _ := db.conn.Query(context.Background(), "Select * from products limit 10")
	defer rows.Close()

	fieldDescriptions := rows.FieldDescriptions()

	var cols []string
	for _, fieldDesc := range fieldDescriptions {
		cols = append(cols, string(fieldDesc.Name))
	}

	row := make([][]byte, len(cols))
	rowPtr := make([]interface{}, len(cols))

	for rows.Next() {
		err := rows.Scan(rowPtr...)
		if err != nil {
			fmt.Println(err.Error())
		}

		fmt.Println(rowPtr)
	}
```

Im trying to use just an array of interface{} to hold all the values from the Scan. When i run it though I jsut get nil for all the columns

**Comment by jackc** [comment]
`rows.Scan(rowPtr...)` won't work. You would need `rows.Scan(&rowPtr[0], &rowPtr[1], ...)`. But that does the same thing as calling `Values()`. And `Values()` is much easier.
