### ISSUE TITLE
syntax error with not in operator and positional parameters

### ISSUE THREAD

**Issue by zhughes3** [jackc/pgx#1240]
Man, I hate to leave this comment because I probably am making a silly mistake. I have been using this library for years and have nothing but great experience - looking forward to refactoring our code base to use v5 and named parameters soon.

Anyways, I have a simple table that has two fields: id1 and id2. Both are of type text.

The following query works as expected when using psql: 

`delete from table where id1 = 'foo' and id2 not in ('bar')`

Now, I am having problems getting this to work with pgx 3.6.2 with the following command:

`_, e := tx.Exec("delete from table where id1 = $1 and id2 not in $2", id, sliceOfIDs)`
In the above Go code, id is of type string and sliceOfIDs is of type []string

After executing the tx.Exec above, it responds with the following error:
**"syntax error at or near $2"**

I am not sure if I am trying to use pgx wrong. Any help would be greatly appreciated. Thanks in advnace.

**Comment by jackc** [comment]
You probably want `= any` instead of `in`. (https://www.postgresql.org/docs/14/functions-comparisons.html#id-1.5.8.30.16)

 e.g. something like:

```sql
_, e := tx.Exec("delete from table where id1 = $1 and not id2 = any ($2)", id, sliceOfIDs)
```

**Comment by zhughes3** [comment]
That did it. Thanks for your expertise.
