### ISSUE TITLE
[Q] Why do you need to call os.Exit() for program to shutdown when using pgx?

### ISSUE THREAD

**Issue by telephrag** [jackc/pgx#1241]
What exactly holds program from shutting down, say, with `^C`?

**Comment by jackc** [comment]
You do not need to call `os.Exit()` to quit a program using pgx.

If I had to guess you probably have a `defer pool.Close()` somewhere and are never releasing all the acquired connections. `pool.Close()` blocks until all connections are released.

**Comment by telephrag** [comment]
It indeed was the case. Thank you.
