### ISSUE TITLE
The option of handling NULL as zero values instead of pgx/sql.NullWhatnot

### ISSUE THREAD

**Issue by tucnak** [jackc/pgx#1242]
Hello,

I'm sure this have been brought up numerous, numerous times as it's quite an issue with how Go traditionally deals with NULL values as opposed to how it traditionally deals with zeroed values, and you don't need to have a 10-year perspective on Go like some of us do— to see that there's impediment to ergonomics, as well as memory allocation patterns whenever people have to deal (and we almost always do) with NULLs.

Naturally, these are the options:

```go
type Model struct {
	Field *string        `db:"field"`
	Field sql.NullString `db:"field"`
	Field pgx.NullString `db:"field"`
}
```

### Rationale

The pros and cons of the aforementioned forms are widely known.

We know that at least to some extent pointers are suboptimal in the view of memory allocation patterns, and give a great deal of grief whenever they need to be set up for primitive types such as bool, int, string. However, if you were to go with a special Null struct, you no longer would be able to interface with the column directly as-if it were a regular string, and this naturally leads to people writing somewhat ugly code, or resort to data mappings (when an SQL model is translated to the application model) to conceal the logic of nulls. I mean, this is everything but grave inefficiency, but the sheer amount of code resorting to pointer column representations is honestly, telling, or to put it bluntly— constantly having to deal with the consequence of this approach.

```go
if model.Field == nil {
	// this is obv. not possible:
	model.Field = &"value"

	// now, you end up writing these 
	model.Field = new(string)
	*model.Field = "value"

	// or, rather with the Null struct you get
	model.Field = sql.NullString{String: "value", Valid: true}
}
```

I've also seen people go to great lengths to improve ergonomics here.

```go
// I kid you not!
func String(s string) string {
    return &s
}
// IMHO, just about makes sense... (the despair!)
func String(s string) sql.NullString {
    return sql.NullString{Valid: s != "", String: s}
}

if model.Field == nil {
	model.Field = String(s)
}
```

And with strings— we're barely scratching the surface here. I like [pgx.Tstzrange](https://github.com/jackc/pgx/blob/v3.6.2/pgtype/tstzrange.go#L10) and [pgx.Bool](https://github.com/jackc/pgx/blob/v3.6.2/pgtype/bool.go#L10) in some cases where it's strictly required by the data model— as much as the next guy, and it's incredibly beneficial to have these types in our repertoire because when we need it, we need it— there's no way around it. However, is it truly justified in a lax setting that is reasonable to expect from a large variety of back-end, if not low-level system applications where we use dear Postgres so extensively? I'm talking where boolean columns would have `DEFAULT false` to a point of rule, and whenever you don't really want to differentiate between an empty string and a null string— null string indicating _absence_ of value in spite of an empty string, and having both introduces more ambiguity and urges you to be increasingly more careful in how you would write the requests. I think ones of us who employ `jsonb` scans are already familiar with the implications of null values there— nulls being unmarshaled exactly how you would expect them to— in any other piece of Go code dealing with JSON values.

### Proposal

I want to make a point that it's well-justified to at least have an option, opt-in ability to resort to and use zero values whenever nulls are encountered in scanning, if not in querying, although having both would certainly be beneficial to some users. The lax condition has to be totally compatible with the `pgx.Null*` types whenever the differentiation has to be made, as these are not primitive, but interface types, closing no doors in the process. Truly, this boils down to a single question.

Would @jackc be willing to allow such mode, and if yes, to what standard would he hold a corresponding PR?

I suggest to have the [pgconn.Config](https://pkg.go.dev/github.com/jackc/pgx/v5/pgconn#Config) accomodate said lax null mode in the opt-in fashion, with 100% reverse compatibility and zero consequence to the existing code:

```go
// ModeNulls specifies as to how SQL NULL is handled in primitive type zeros.
type ModeNulls int

const (
	// NULL primitive types can only be scanned as nil, producing error otherwise.
	NullsDefaultMode ModeNulls = iota
	// NULL resolves to zero values in scanning of the primitive types.
	NullsLaxScanMode
	// NULL resolves to zero values in both scanning and writing of the primitive types.
	NullsLaxMode
)

type Config struct {
	// ...

	// Nulls overrides the default (strict) behaviour to how SQL NULL is resolved in primitive types.
	Nulls ModeNulls
}
```

This would bring a set of changes to the internals, but to my knowledge— the area can be very limited, and as it were, I could as well spin a fork of it and do my own thing, but then keeping up with upstream `pgx` is one of those things that I have no interest in doing— ergonomics of my lax data model be damned. I would really appreciate if my proposal were accepted, and I feel like I've made a solid case for it in terms of a backwards-compatible, zero risk change that potentially wouldn't have to be maintained in any special manner, unless the low-level scanning/writing procedures were to be modified, and to my knowledge they are stable and have been for a long time, to which I must admit, is not particularly in favour of my proposal (it being a change to said procedures.)

Best regards
Ian

**Comment by paudley** [comment]
Just a note that you can get most of what you want without changes to the query layer by using COALESCE and NULLIF with the added benefit that you have case by case control on which PG types will convert to zero on NULL and under which specific conditions.  ie:  do you want a varchar("") to be null or not?

**Comment by jackc** [comment]
I'm not enthusiastic about adding a blanket `NULL` = zero value mode. The complexity it would add to pgx is definitely an issue. But beyond that, as a bit of a data integrity zealot, it strikes me as a bit of a foot-gun.

But I do find `NULL` = zero value behavior very useful on occasion. That's why I made the [zeronull](https://pkg.go.dev/github.com/jackc/pgtype@v1.11.0/zeronull) package. It has a few common types that have that behavior. It lets that behavior be used selectively.

And if you *really* want that behavior by default you could probably register them as the default data types in an `AfterConnect` hook as well. Not that I'd recommend it... but if that's what you want I think that is the way to do it.

**Comment by tucnak** [comment]
Hey, I totally understand it, there's nobody who's better versed in the pgx's complexity than you. Can you elaborate on `AfterConnect` please? I thought it was just a place where I would run arbitrary SQL, like prepared statements and stuff like that?

How exactly would it allow me to _remap_ the default primitive types?

**Comment by tucnak** [comment]
@paudley Hey thanks for the suggestion, obviously I am aware of both COALESCE and NULLIF but wrapping up every single SELECT column can get very, very tiresome at times. Especially, in joins. I might as well have ten or twenty columns joined with a set of another five to ten columns, and whereas I could simply say `SELECT T0.*, T1.*` I now have to go about coalescing these twenty columns because in a JOIN all of them may end up as NULL. Otherwise, in the case of `varchar('')` for example that you mentioned, you would have columns be `DEFAULT ''` almost exclusively unless it's all guaranteed to be set and you're not going to be doing any left/right joins on it, and this doesn't scale well due to obvious reasons.

Most of the time, I just want to write code like this:

```go
	var togetherForever []struct{
		Callsign string `db:"id"`
		Agent
		Duty
	}
	aloneTogether := sqlf.
		Select(`distinct u.callsign, a.*, pd.*`). // here it is 
		From("users u").
		LeftJoin("agent a", "u.id = a.user_id").
		LeftJoin("plea_duty pd", "u.id = pd.agent_id").
		Where("u.sus = false").
		Where("a.brigade_id = ?", u.AgentData.BrigadeId)
	switch err := brr.ScanAllf(aloneTogether, &togetherForever); err {
	case nil:
	case nix:
		return ø("no rows")
	default:
		return nosale(err)
	}
```

I mean it's sort of artificial how this request is build because I've kind of made it up of multiple other requests I work with these days, but it shows exactly how much easier it is to simply use the asterisk, instead of coalescing the joined column set completely to the tits. What would that code look like? Much owrse, in fact I probably wouldn't be able to fit the `SELECT` clause in one line, and would need to spell it out and break it beforehand out of chain. Bad, bad ergonomics, and not even because there's optional columns, but simply because there's LEFT JOIN.

However, @jackc having thought about it for a while, would you also care to elaborate your point on complexity please? I'm still not so sure how I would override `string` with `zeronull. Text` so my string columns can be joined effectively without having to box everything in the model to these nullable types? I can totally see that you're not a fan of this approach in general, if not for limited cases, but wouldn't you agree that at least having the option would be strictly beneficial?

**Comment by jackc** [comment]
The type conversion code is replaceable / configurable for each data type. See https://github.com/jackc/pgx/wiki/Numeric-and-decimal-support for an example of how to register a different numeric data type than default. The `zeronull` types can probably registered as is to replace the normal `int`, `text`, etc. handlers. They weren't written to be used that way but I think it should work without any changes. But regardless, registering data types is how pgx supports this -- and any other type handling replacement.

> However, @jackc having thought about it for a while, would you also care to elaborate your point on complexity please?

The complexity is because this touches a core function, converting values between Go and PostgreSQL representation and at the very least it adds a branching code path. This means that much of what pgx does now could be affected by which mode it was in. And that's assuming it even could be done in core type conversion system prior to the individual data types (I'm not sure if this would be possible or not). If it couldn't be done in a central place then every data type would need to be changed.

> but wouldn't you agree that at least having the option would be strictly beneficial?

Depends on your perspective. I don't think it would be beneficial for long-term maintenance and ongoing development of pgx.

But again, you can override the handling of all data types. The zeronull types will probably give you 95%+ of what you want.

**Comment by tucnak** [comment]
Thank you for the insight. I will take a closer look at https://github.com/jackc/pgx/wiki/Numeric-and-decimal-support never knew pgx could do this, at any rate it should be more than sufficient for what I'm trying to accomplish and quite a use-case for the connection hooks, too. Have a nice day!
