### ISSUE TITLE
column reference "id" is ambiguous but the query works fine in Postgres

### ISSUE THREAD

**Issue by conor-tread** [jackc/pgx#1246]
So im am implementing an upsert and I dynamically create the query. It comes to: 

```
INSERT INTO v2.products (id,company_id,name) VALUES (1,2,'foo6') ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id, company_id = EXCLUDED.company_id, name = EXCLUDED.name 
```

When i call Query or Exec I get 

```
ERROR: column reference "id" is ambiguous (SQLSTATE 42702)
```

But this query works fine in Postgres. Can anyone tell me what is going wrong?

**Comment by jackc** [comment]
pgx uses prepared statements / the extended protocol by default. Try using `prepare` and `execute` with your query in `psql` to see if you can duplicate the problem there.
