### ISSUE TITLE
Fix docs regarding pgxpool.Connect and cancel/lazy initial connection

### ISSUE THREAD

**Issue by bryanjhv** [jackc/pgx#1247]
Hi! First of all thank you so much for your hard work on this library.

Now, I'd like to bring into attention some part of the documentation:

https://github.com/jackc/pgx/blob/8b9b4055f3b679999adde4a0ab44eb6e1ea536c7/pgxpool/pool.go#L146-L147

Here it says that I can use `cancel` to prevent an initial connection, however after doing this:

```go
ctx, cancel := context.WithCancel(context.Background())
cancel()

pool, err := pgxpool.Connect(ctx, url)
if err != nil && err != context.Canceled {
	log.Fatal(err)
}

pool.Exec(context.Background(), "SELECT 1+1 AS s")
```

I just get a panic with the following content:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3b59cc]

goroutine 1 [running]:
github.com/jackc/pgx/v4/pgxpool.(*Pool).Acquire(0x0, {0x7138e8, 0x1526000})
	/home/bryan/go/pkg/mod/github.com/jackc/pgx/v4@v4.16.1/pgxpool/pool.go:414 +0x20
github.com/jackc/pgx/v4/pgxpool.(*Pool).Exec(0x0, {0x7138e8, 0x1526000}, {0x648d25, 0xf}, {0x0, 0x0, 0x0})
	/home/bryan/go/pkg/mod/github.com/jackc/pgx/v4@v4.16.1/pgxpool/pool.go:471 +0x5c
```

I found out that the right way to establish a lazy pool would be like in https://github.com/jackc/pgx/issues/989#issuecomment-986218861.

Maybe I'm just misusing the `cancel` function, would like it to be clarified if that's the case.

**Comment by jackc** [comment]
The intention of always establishing one connection is to return an error on invalid configuration where the pool is established, not where ever the first usage happened to be. The purpose of supporting context cancel was to avoid a deadlock if network activity was blocked or frozen.

But if any error occurs no pool is returned.  As you mentioned, the lazy connect feature is the way to do this, not context cancel. 

FWIW, I'll probably drop the eager connect feature from `v5`. Lazy connect actually is a better default for servers, and anyone who wants to test on startup can immediately call `Acquire()`.

**Comment by bryanjhv** [comment]
Thank you so much for your response, now I understand what's the difference between the two.
Effectively, my use case requires connections to be lazy because most of the time it starts when the server is not reachable (i.e. very bad network environment), and when the program was restarted it got stuck forever trying to connect and without doing anything else.
I think it would be a great move to default on lazy connections, given most of the libraries (at least in Node.js world) I've seen require you to `acquire()` a connection to check for errors.
Closing now as it's clarified. Keep the good work and thank you again!
