### ISSUE TITLE
bug: int64 param: "is greater than maximum value for Int4"

### ISSUE THREAD

**Issue by stokito** [jackc/pgx#1248]
I have a table with id column of `bigint` type and want to write a select that contains `$1 = 0`:

```go
	id, _ := strconv.ParseInt(idStr, 10, 64)
	//language=SQL
	querySql := `
		SELECT * FROM user
		WHERE $1 = 0 OR id = $1
		`
	rows, err := db.Query(context.Background(), querySql , id)
```

I.e. if the filter by id `idStr` is empty then the `id` is `0` and all records will be returned.
But if the filter by id was set then only a record with this id will be returned. This is hack to avoid concatenation of the query to construct a filter.

This works in PG but when I call the query from pgx the error is returned: `NUMBER is greater than maximum value for Int4`. Similarly the same error when just `WHERE $1 = 0`.

This is not related to #182 because here the problem is in the param itself

**Comment by stokito** [comment]
Just found that when first comparing with a column this it works:
`WHERE id = $1 OR $1 = 0`
Looks like not critical anymore for me, may be just mentioned in documentation

**Comment by jackc** [comment]
pgx uses the extended protocol by default. This means it is executed with the equivalent of a prepared statement.

Try that in psql and I think you will also get an error.

```
prepare s as select * from user where $1 = 0 or id = $1;
execute s (2^33);
```

When PostgreSQL parses the statement it has to decide what type `$1` is. It sees `$1 = 0` first. `0` is an `int` literal. So `$1` is a parameter of type `int`. You can override that with `::`. i.e.  `WHERE $1::bigint = 0 OR id = $1

**Comment by stokito** [comment]
Yes, I got an error
```
[22003] ERROR: integer out of range
```

And no any error when flipped. Thank you for the clarification

**Comment by emaborsa** [comment]
I have the same problem, but without $1 = 0

```
SELECT NULL
FROM hgv.companies
WHERE id = $1
```
`$1` is 2551565154

`failed to encode args[0]: unable to encode 2551565154 into binary format for int4 (OID 23): 2551565154 is greater than maximum value for int4`

**Comment by jackc** [comment]
What type is `hgv.companies.id`?
