### ISSUE TITLE
Some errors are not returned for Query, but available on rows.data.err

### ISSUE THREAD

**Issue by boindil** [jackc/pgx#1249]
Hi,
we noticed today that in one case we weren't getting an error from tx.Query but there clearly was one happening.

For some reason the error is not returned, even though we can see in the debugger that there is an error attached to rows.data.err as seen in the screenshot.

Since the query is obviously failing I would suspect this is a bug because the transaction will fail for obvious reasons.

Regarding the input params our fault was a violation of the constraint of the same line. It should be pretty simple to reproduce this behavior.
![pgx_error](https://user-images.githubusercontent.com/4290644/177797780-0bda058c-76cc-4790-8af5-3872ca7b9d1c.PNG)

In this case err was just nil after the method call.
![pgx_error_query](https://user-images.githubusercontent.com/4290644/177797787-201bb6dc-3e31-4b34-8a16-6468480dcb2b.PNG)

Maybe you can have a look and fix this?

**Comment by jackc** [comment]
From https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.Query:

> Err() on the returned Rows must be checked after the Rows is closed to determine if the query executed successfully as some errors can only be detected by reading the entire response. e.g. A divide by zero error on the last row.

**Comment by boindil** [comment]
Still this specific error should fire before the rows are read imho. You even see rowCount = 0 in the properties.

**Comment by jackc** [comment]
I'm not sure whether this particular error could be detected before reading from rows or not. But it is *always* an application error not to check `Rows.Err()`. And given that, I don't see the urgency in reporting the error earlier.
