### ISSUE TITLE
Insertion into bigint data type  results in error "cannot convert {2525} to Int2"

### ISSUE THREAD

**Issue by rv-nath** [jackc/pgx#1254]
I am an amaeteur for golang, so kindly excuse if this is a naive question.  I have been trying to fix an issue of insertion of data into a currency (postgresql bigint) but without success.

```go
110 ▏ // Add into txn table..
▎ 111 ▏ sql := `INSERT INTO user_txns (user_id, txn_code, description, txn_type, txn_amt) VALUES ($1,$2, $3, $4, $5)`
▎ 112 ▏ _, err = tx.Exec(context.Background(), sql,
▎ 113 ▏ ▏ ▏ ▏ ▏ ▏ claims["phone"],
▎ 114 ▏ ▏ ▏ ▏ ▏ ▏ recharge,
▎ 115 ▏ ▏ ▏ ▏ ▏ ▏ "User recharge",
▎ 116 ▏ ▏ ▏ ▏ ▏ ▏ credit,
▎ 117 ▏ ▏ ▏ ▏ ▏ ▏ recharge.Amount,
▎ 118 ▏ )
▎ 119 ▏ if err != nil {
▎ 120 ▏ ▏ log.Info().Msg("Landed into soup.")
▎ 121 ▏ ▏ c.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
▎ 122 ▏ ▏ return
▎ 123 ▏ }
```
It seems to be failing for recharge.Amount (line#117) in my code, with the error:
>cannot convert {2525} to Int2

The table structure is simple with around 6 fields, as below.
```
postgres=# \d user_txns
                       Table "public.user_txns"
   Column    |         Type          | Collation | Nullable | Default
-------------+-----------------------+-----------+----------+---------
 user_id     | character varying(15) |           | not null |
 txn_code    | smallint              |           | not null |
 description | character varying(64) |           | not null |
 txn_type    | smallint              |           | not null |
 voucher     | character varying(16) |           |          |
 txn_amt     | bigint                |           |          |
```

For the recharge.Amount, this is the json binding I am using.
```
44 type Recharge struct {
45 ▏ Amount int64 `json:"amount" binding:"required"`
46 }
```

I posted this qn on stackoverflow [here](https://stackoverflow.com/questions/73003096/inserting-into-postgresql-decimal-field-fails-with-error-cannot-convert-125-00?noredirect=1#comment128938207_73003096).  As there was no reply, I am  posting here.

I understand that I may be doing some very silly mistake here, but unable to fix it.  Internet search doesn't yield an example of inserting data into a numeric / bigint field.

Thanks for helping me out on this one.

**Comment by jackc** [comment]
The problem appears to be `txn_code` or `txn_type`. Note that it is complaining about an `Int2` (i.e. `smallint`).

Also, from the error message `{2525}` is not a number. It appears to be some sort of wrapper object. That is probably the issue.

If not, see if you can make a standalone reproduction case.

**Comment by rv-nath** [comment]
Thank you jackc.  Finally, I could nail the problem.  I used an enum to identify txn_codes.  One of the members of this had the same name as `recharge`.  That is why, the `recharge.Amount` was always pointing to {125}. Interestingly there is no compiler error and the name conflict.
