### ISSUE TITLE
Make generic function to call Select Statement

### ISSUE THREAD

**Issue by mingsterism** [jackc/pgx#1255]
hi guys, 
How can i turn this into a Generic function that accepts any argument. 

```
func SelectFromDb[T model.ToDoItem](db DbImpl, ctx context.Context, sqlStatement string, args ...interface{}) ([]model.ToDoItem, error) {

	dbPool := db.GetConnection()
	defer dbPool.Close()
	rows, err := dbPool.Query(ctx, sqlStatement)
	if rows != nil {
		defer rows.Close()
	}
	if err != nil {
		return nil, err
	}
	var results []model.ToDoItem
	for rows.Next() {
		var item model.ToDoItem
		err = rows.Scan(
			&item.ID, &item.Text, &item.IsDone, &item.CreatedOn, &item.UpdatedOn)
		if err != nil {
			return nil, err
		}
		results = append(results, item)
	}
	if rows.Err() != nil {
		return nil, err
	}
	return results, nil
}
```
This code works but i'm not sure how to make it Generic. 
This code line is tricky. 
`err = rows.Scan(&item.ID, &item.Text, &item.IsDone, &item.CreatedOn, &item.UpdatedOn)`
Thanks

**Comment by jackc** [comment]
Take a look at the `v5-dev` branch. In particular look at the functions `CollectAll`, `RowToStructByPos`, and `RowToAddrOfStructByPos`. I'm not sure how easy it would be to port them to pgx `v4`, but they at least ought to give you an idea of how to make generic functions that collect query results.

**Comment by bfontaine** [comment]
I’m closing the issue because I believe Jack answered the question. Feel free to reopen if you think it’s a mistake.
