### ISSUE TITLE
encoding array of composite type

### ISSUE THREAD

**Issue by fatholahi** [jackc/pgx#1257]
hi every one
I used this page :
https://pkg.go.dev/github.com/jackc/pgtype
to implement binary encoding/decoding composite types, encoding works fine but my real problem is that I don't know how to encode my "slice of struct" and pass it to postgres ...

**Comment by jackc** [comment]
Easiest way is to use `pgtype.NewArrayType()`. See `TestArrayTypeTranscode` for example usage.

**Comment by fatholahi** [comment]
> Easiest way is to use `pgtype.NewArrayType()`. See `TestArrayTypeTranscode` for example usage.

thank you for your answer
is it possible that I do this with implementing encoding/decoding function ? like the sample code ?

something like this maybe !

type PersonList []Person

func(models PersonList) EncodeBinary(...

by the way, I'm new to golang ...

**Comment by jackc** [comment]
> is it possible that I do this with implementing encoding/decoding function ? like the sample code ?

It's possible, but much more complicated. See the source code for `BoolArray` for example. It's simpler than what you want, but it is still over 500 lines of code. However, it is generated code so you might be able to reuse the generating files `typed_array.go.erb` and `typed_array_gen.sh`.

> by the way, I'm new to golang ...

Not to discourage you, but just as a fair warning, implementing a completely custom array of composite type is complicated. It requires a pretty deep knowledge of Go, pgx, and how PostgreSQL encodes values over the wire.

**Comment by fatholahi** [comment]
thank you @jackc, good enough for me ...
