### ISSUE TITLE
can't scan into dest[0]: cannot assign postgres date into custom time.Time type

### ISSUE THREAD

**Issue by liulinhuai** [jackc/pgx#1258]
The similar issue as [#1151](https://github.com/jackc/pgx/issues/1151)

create table test (
    date date
);

type Date time.Time
var d Date
err := row.Scan(&d)
// err: can't scan into dest[0]: unable to assign to *dt.Date

**Comment by liulinhuai** [comment]
It will be more convenient if it works like time.Time. It's a time.Time alias and it should like a float64 alias in bug #1151, right?

**Comment by jackc** [comment]
Unfortunately, it is not as simple as with float64. pgx uses reflection to determine the underlying type using https://pkg.go.dev/reflect#Kind. That can identify a something with an underlying type of float64, but something with an underlying type of time.Time is only identified as struct.
