### ISSUE TITLE
Why don't use `?` instead of `$1` `$2` 

### ISSUE THREAD

**Issue by mozhata** [jackc/pgx#1265]
it is encouraged at database/sql to use query like 
```
err := db.QueryRow("SELECT name FROM foo WHERE id=?", id).Scan(&s)
```
It will be a good idea to support this format

**Comment by jackc** [comment]
> it is encouraged at database/sql

AFAIK, that is not the case. The placeholder format is defined by the underlying database. It just so happens that the examples use `?` style.

The `$1`, `$2`, etc format is what PostgreSQL natively understands. Supporting `?` would require parsing and rewriting the query text.

**Comment by jflambert** [comment]
Sorry for dogpiling on the thumbs down but that is definitely not something I expect out of pgx anytime soon.
