### ISSUE TITLE
Copyfrom can't work

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pgx#1266]
I use the code from 
https://github.com/jackc/pgx/blob/3ab89419216bcaf306c930ce291ef2b63000ba08/copy_from_test.go
to test the copyfrom function, but it can't work, the error is:

**ERROR: insufficient data left in message (SQLSTATE 08P01)**

the postgresql version is:
**PostgreSQL 10.21 (Ubuntu 10.21-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit**

**Comment by jackc** [comment]
Well, the test works so presumably the error is elsewhere. You need to provide a runnable example for anyone to help you.

**Comment by zhanghaiyang9999** [comment]
duplicate with #1267
