### ISSUE TITLE
Can copyfrom support new data types such as box, bit , etc...

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pgx#1267]
Now copyfrom can't support data types such as box, bit ,etc..
is these new data types in plan to support ?
@jackc

**Comment by jackc** [comment]
> Now copyfrom can't support data types such as box, bit ,etc..

CopyFrom should support any type that implements the binary format -- which I believe those do. You will need to post a runnable example for anyone to be able to help you.

**Comment by zhanghaiyang9999** [comment]
@jackc 
I have a test table named testtable, the create script was:
CREATE TABLE IF NOT EXISTS public.testtable
(
    id bigint NOT NULL,
    fbox box,
    CONSTRAINT testtable_pkey PRIMARY KEY (id)
)
If I used the sql to insert the record ,it worked well with the following sql:

insert into public.testtable (id,fbox) values (1,'10,10,20,20'),(2,'0,0,100,100');

But If I Used the copyfrom, it will fail, the codes are:

```
conn, err := pgx.Connect(context.Background(), dsn)
	if err != nil {
		log.Println(err)
		return
	}
	conn.Exec(context.Background(), "truncate table public.testtable")
	defer conn.Close(context.Background())
	inputRows := [][]interface{}{
		{1, "0,0,100,100"},
		{2, "0,0,200,200"},
	}
	copyCount, err := conn.CopyFrom(context.Background(), pgx.Identifier{"public", "testtable"}, []string{"id", "fbox"}, pgx.CopyFromRows(inputRows))
	log.Println(copyCount, err)
```

the error is :


Severity:
"ERROR"
Code:
"08P01"
Message:
"insufficient data left in message"
Detail:
""
Hint:
""
Position:
0
InternalPosition:
0
InternalQuery:
""
Where:
"COPY testtable, line 1, column fbox"
SchemaName:
""
TableName:
""
ColumnName:
""

**Comment by jackc** [comment]
Use the `pgtype.Box` type instead of string.

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

	_, err = conn.Exec(context.Background(), "truncate table public.testtable")
	if err != nil {
		log.Fatal(err)
	}

	inputRows := [][]interface{}{
		{1, &pgtype.Box{P: [2]pgtype.Vec2{{X: 0, Y: 0}, {X: 100, Y: 100}}, Status: pgtype.Present}},
		{2, &pgtype.Box{P: [2]pgtype.Vec2{{X: 0, Y: 0}, {X: 200, Y: 200}}, Status: pgtype.Present}},
	}
	copyCount, err := conn.CopyFrom(context.Background(), pgx.Identifier{"public", "testtable"}, []string{"id", "fbox"}, pgx.CopyFromRows(inputRows))
	log.Println(copyCount, err)
}
```

Unlike queries, the COPY protocol is must be entirely in the text or entirely in the binary format. Binary is higher performance so that is what pgx uses. The copy from code in pgx isn't currently smart enough to notice that you've passed in a string for a non-text value so its getting passed all the way to PostgreSQL where it detects the invalid format.

**Comment by zhanghaiyang9999** [comment]
Thanks @jackc ,I will try this and try more postgresql data types.

**Comment by jackc** [comment]
> The copy from code in pgx isn't currently smart enough to notice that you've passed in a string for a non-text value so its getting passed all the way to PostgreSQL where it detects the invalid format.

There is now code on the `v5-dev` that automatically parses strings and encodes them in the binary format in the copy from stream.
