### ISSUE TITLE
v4: Golang + bytea storing in Postgresql

### ISSUE THREAD

**Issue by katerinachinnappan** [jackc/pgx#1268]
Struggling with storing `[]byte` data in my Postgresql DB with Golang. I am expecting a certain # of bytes, however, golang adds extra bytes when storing in Postgresql which makes my data invalid. I am wondering what I am doing wrong. 

Code is complicated so I simplified it as much as possible and included only the relevant parts. Everything works, query gets executed and stored in db, but the `raw_data` column contains more bytes than it should. The interesting thing is that when I print the `len(raw_data)` right before storing it, the # of bytes is correct. I also printed out the final query right before executing it and executed it manually in my db, and `raw_data` is stored correctly. I don't understand what happens during the query execution in go and why extra bytes are added.

Code:

```
func escapeString(value *string) string {
	if value != nil {
		return fmt.Sprintf("'%s'", *value)
	} else {
		return "NULL"
	}
}

func constructQuery()(*string, []byte){
    name := "ST_123"
    rawData := getRawData()// this fun returns []byte
    const Query = `INSERT into myTable (name, raw_data) VALUES (%s::text, $1)`

    finalQuery := fmt.Sprintf(Query, escapeString(&name),)
    return &finalQuery, rawData
}

func executeQuery(*string, []byte) {
    _, err := store.dbPool.Exec(context.Background(), *sql, rawData)
}

func processMessage() {
    // parse message logic
   // get appropriate sql query
   var rawData []byte
   var sql *string
   
   sql, rawData := constructQuery()
   // execute query
   executeQuery (sql, rawData)
}


```

**Comment by jackc** [comment]
It's hard to for sure from this example, but if I had to guess I would say your binary data is being escaped into the text format but it is being sent as binary.

Also, it appears you are doing some string interpolation for a SQL parameter. You really don't want to do that. Use `$` placeholders instead. pgx and PostgreSQL can handle that safely.
