### ISSUE TITLE
"Select ... For Update" in Transaction on a Pool Connection may not release the transaction when no rows are found

### ISSUE THREAD

**Issue by Howard3** [jackc/pgx#1269]
**Describe the bug**
When using `select ... for update skip locked` in a transaction on a pgx.Pool instance the connection may not be returned to the pool if there were no rows returned: `pgx.ErrNoRows`. This seems to be resolved by calling tx.Rollback(ctx) despite no data being returned.

What happens is the transaction/lock remain open and the connection is never returned to the pool. This seems to be resolved by calling `tx.Rollback(ctx)` but given that no rows were selected this seems, to me at least, an unexpected behavior.

The locks can be observed as still being held by the program in Postgres by running the following query:
```sql
select t.relname,l.locktype,page,virtualtransaction,pid,mode,granted from pg_locks l, pg_stat_all_tables t where l.relation=t.relid order by relation asc;
```

**To Reproduce**
Given the following query
```go
tx, _ := conn.GetPool().Begin(ctx)
err := tx.QueryRow(ctx, "SELECT col1, col1 FROM public.table FOR UPDATE SKIP LOCKED LIMIT 1").Scan(...)
if err != nil {
   // if you remove this .Rollback command you'll be left with perpetually open transactions on the pool.
   if err := tx.Rollback(ctx); err != nil {
	logger.Error("error rolling back transaction: %v", err)
   }
   return err // this may be pgx.ErrNowRows
}
```

**Expected behavior**
Given the observed behavior I would have expected the transaction to release the connection to the pool eventually, but this never happens. Connections seem to be returned to the pool after calling `.Commit(ctx)` as well, so perhaps the expectation is that the transactions need to have some finality and can't just be cleaned up.

**Actual behavior**
If you are no longer tracking the `tx` var that came from `tx, err := conn.GetPool().Begin(ctx)` you will be left with a permanently open connection in the pool that cannot be cleaned up. There remain locks in the database until the program is restarted.

**Version**
 - Go: `go version go1.17.9 windows/amd64`
 - PostgreSQL: `DBMS: PostgreSQL (ver. 14.2 (Debian 14.2-1.pgdg110+1))
Case sensitivity: plain=lower, delimited=exact
Driver: PostgreSQL JDBC Driver (ver. 42.2.22, JDBC4.2)
Ping: 27 ms
SSL: no`
 - pgx: `github.com/jackc/pgx/v4 v4.16.1 `

**Additional context**
This is possibly just a lack of understanding on my part on how pgx wants to use the transactions but the examples floating around do not seem to indicate a need to roll back transactions when nothing is returned.

**Comment by jackc** [comment]
> This is possibly just a lack of understanding on my part on how pgx wants to use the transactions but the examples floating around do not seem to indicate a need to roll back transactions when nothing is returned.

If those examples are in pgx let me know and I'll fix it -- because that is wrong. A tx must *always* be committed or rolled back.

**Comment by Howard3** [comment]
This is good to know! Thanks! I'll dig through where I found examples but I do not believe they were yours per-se. I was originally treating it like pool connections where you can just execute right on a pool connection and the connection is released to the pool after automatically, but in the case of transactions case without finality it just can be lost.

**Comment by Howard3** [comment]
@jackc Two things:

1. Is there a way to support this project?
2. Are you aware of any linters compatible with golangci-lint which can ensure tx's are completed in a function call, whether rollback or commit? I'm looking around for this currently. This would be a decent way of avoiding accidental failures.

**Comment by jackc** [comment]
1. Not at the moment.
2. I don't know of any linters, but `BeginFunc` is much harder to misuse. But if you use `Begin()` directly then usually you should `defer tx.Rollback()` immediately after. It is a no-op to call `tx.Rollback()` after the tx has already been committed or rolled back.

**Comment by Howard3** [comment]
Thanks! This is incredibly helpful!
