### ISSUE TITLE
 Can't convert OID 1700 to uint64.

### ISSUE THREAD

**Issue by giulioungaretti** [jackc/pgx#127]
Why is this happening ? A numeric postgres type could  be thrown inside a go uint64  ?

My use case is really simple in a way:
- one service stores uint64 into Postgres as numeric types
- another one needs to retrieve them

And I really need uint64 also I know they are exactly uint64 :D

**Comment by josephglanville** [comment]
If you know the values are 64 bits wide you should use the `bigint` type. `numeric` is a variable width type and not needed if you know for sure you are going to be storing unsigned 64 bit integers.

**Comment by giulioungaretti** [comment]
But isn't the range of bigint limited  to 9223372036854775807, whereas a unit64 can go up to 18446744073709551615 ? 

Maybe I am just retarded but I if I try to load my uint64 from psql to a bigint it complains about overflows .

**Comment by josephglanville** [comment]
Ahh yeah, bigint is signed my bad. You could probably write a marshaller for `numeric` if you wanted to but it would need to be custom for `uint64` and do validation etc.

**Comment by giulioungaretti** [comment]
Some thing along the lines of this : e40f08e1076338ada8017bc08b619bc1bfffebac  ?
Or what do you mean by marshaller ?

**Comment by jackc** [comment]
I suspect what @josephglanville is referring to is implementing the Scanner and Encoder interfaces. These allow you to implement any arbitrary conversions from Go to PostgreSQL types. That is also what I would recommend.

Here is a sample that I through together quick:

```go
package pgx_test

import (
	"errors"
	"fmt"
	"github.com/jackc/pgx"
	"strconv"
	"testing"
)

type Uint64Numeric uint64

func (n *Uint64Numeric) Scan(vr *pgx.ValueReader) error {
	if vr.Type().DataTypeName != "numeric" {
		return pgx.SerializationError(fmt.Sprintf("Uint64Numeric.Scan cannot decode %s (OID %d)", vr.Type().DataTypeName, vr.Type().DataType))
	}

	if vr.Len() == -1 {
		return pgx.SerializationError(fmt.Sprintf("Uint64Numeric.Scan cannot decode null"))
	}

	switch vr.Type().FormatCode {
	case pgx.TextFormatCode:
		s := vr.ReadString(vr.Len())
		var err error
		pn, err := strconv.ParseUint(s, 10, 64)
		if err != nil {
			return pgx.SerializationError(fmt.Sprintf("Received invalid uint64: %v", s))
		}
		*n = Uint64Numeric(pn)
		return nil
	case pgx.BinaryFormatCode:
		return errors.New("binary format not implemented")
	default:
		return fmt.Errorf("unknown format %v", vr.Type().FormatCode)
	}
}

func (p Uint64Numeric) FormatCode() int16 { return pgx.TextFormatCode }

func (p Uint64Numeric) Encode(w *pgx.WriteBuf, oid pgx.Oid) error {
	s := strconv.FormatUint(uint64(p), 10)
	w.WriteInt32(int32(len(s)))
	w.WriteBytes([]byte(s))

	return nil
}

func TestUintNumericScanner(t *testing.T) {
	t.Parallel()

	conn := mustConnect(t, *defaultConnConfig)
	defer closeConn(t, conn)

	var num Uint64Numeric

	err := conn.QueryRow("select '1234567'::numeric").Scan(&num)
	if err != nil {
		t.Fatalf("Scan failed: %v", err)
	}

	if num != 1234567 {
		t.Errorf("Expected num to be %v, but it was %v", 1234567, num)
	}

	ensureConnValid(t, conn)
}
```

@giulioungaretti e40f08e added automatic conversion to the core of pgx for uintX types. While we have such conversion code for integer conversions such as converting a Go `int32` into a PostgreSQL `bigint` and converting a `uint16` into a `integer`, I have very mixed feelings about it. It _is_ convenient, but it feels like it goes slightly against the strongly typed nature of Go. It means that a code path may work or not work depending on the values being read or written. Convenience (and backwards compatibility) won for integer types, but past that I'd like to hold the line on strong typing. So I suggest using something like the above code.
