### ISSUE TITLE
cannot use int(fd) (value of type int) as type syscall.Handle 

### ISSUE THREAD

**Issue by chbussler** [jackc/pgx#1274]
Hi - I just started with pgx (used pg before)

- go version go1.18.4 windows/amd64
- Windows version 21H2
- pgx v5@v5.0.0-beta.1

I have a routine that follows the instructions here on querying inside transactions: https://pkg.go.dev/github.com/jackc/pgx/v5#hdr-Transactions

When compiling and running I get the following errors:

```
# github.com/jackc/pgx/v5/internal/nbconn
..\..\go\pkg\mod\github.com\jackc\pgx\v5@v5.0.0-beta.1\internal\nbconn\nbconn.go:398:56: cannot use int(fd) (value of type int) as type syscall.Handle in argument to syscall.Write
..\..\go\pkg\mod\github.com\jackc\pgx\v5@v5.0.0-beta.1\internal\nbconn\nbconn.go:457:29: cannot use int(fd) (value of type int) as type syscall.Handle in argument to syscall.Read
```

Compilation finished with exit code 2

Please let me know if you need additional info.

**Comment by jackc** [comment]
The new version of pgx directly makes some syscalls for non-blocking IO. It appears that doesn't work on Windows (not a surprise in hindsight).

I don't have a Windows development system but I pieced together enough of one to test using build tags to separate out the unix specific code. It should compile now though I haven't tested it beyond that. 

It's on the `v5-dev` branch now. `v5.0.0-beta.2` will probably be released in a few days.

**Comment by chbussler** [comment]
Hi - upgraded to beta.2 and my code compiles and runs now. Very nice, thank you!
