### ISSUE TITLE
Loading to an INET column using CopyFrom and string data does not work

### ISSUE THREAD

**Issue by sjohnston-adapdix** [jackc/pgx#1277]
**Describe the bug**
Using the CopyFrom to load data into a table. The table contains an inet column. Our incoming data has an IP address in string form (e.g. '192.168.0.1'). This fails to load giving a PostgreSQL error.

**To Reproduce**
As above really. Create a table with an inet column. Attempt to load data using CopyFrom and provide a string variable with just an IP address as the data.

**Expected behavior**
The data should load OK.

**Actual behavior**
PostgreSQL error:
ERROR: invalid address family in external \"inet\" value (SQLSTATE 22P03)

**Version**
 - Go: 1.16
 - PostgreSQL: 11.2
 - pgx: 4.13.0

**Additional context**
Any string that would validly be insertable into an inet column should be supported in the CopyFrom interface. (e.g. both '192.168.0.1', '192.168.0.1/32'). (`INSERT INTO test_table(inet_val) VALUES ('192.168.0.1'),('192.168.0.1/32');`)

**Comment by sjohnston-adapdix** [comment]
We looked at converting out strings to pgtype.INET but the Set() method on that fails with simple IP addresses. We also looked at using net.IP but by contrast that doesn't handle strings with a mask in (e.g. '192.168.0.1/32'). Our data could be mixed so that doesn't work either.

**Comment by jackc** [comment]
> We also looked at using net.IP but by contrast that doesn't handle strings with a mask in (e.g. '192.168.0.1/32').

Works for me:

```go
package main

import (
	"fmt"

	"github.com/jackc/pgtype"
)

func main() {
	var inet pgtype.Inet
	err := inet.Set("192.168.0.1/32")
	fmt.Println(inet.IPNet, inet.Status, err)
}
```

Output:

```
192.168.0.1/32 2 <nil>
```

**Comment by jackc** [comment]
Also, just pushed a commit to the `v5-dev` branch that automatically parses strings and encodes them into the binary format.

**Comment by sjohnston-adapdix** [comment]
Looks like we were tied to an old version of the types library. Having upgraded that, explicitly using the pgtype.Inet gets us working. Looking forward to the automated string parsing though!
