### ISSUE TITLE
ErrNoRows mismatch with database/sql package

### ISSUE THREAD

**Issue by nicomie** [jackc/pgx#1280]
**Describe the bug**

Running unit tests using the database/sql package to check for require.EqualError using the result from pgx.Row.Scan and sql.ErrNoRows.Error() result in the following mismatch: 

Error:      	Error message not equal:
        	            	expected: "sql: no rows in result set"
        	            	actual  : "no rows in result set"
       

**To Reproduce**

`
account2, err := testQueries.GetAccount(context.Background(), account1.ID)
require.EqualError(t, err, sql.ErrNoRows.Error())
`

**Expected behavior**
Expected true for the require.EqualError method.

**Version**
go version go1.18.1 linux/amd64
 PostgreSQL 14.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
github.com/jackc/pgx/v4 v4.17.0

**Comment by jackc** [comment]
I'm not sure I understand. It sounds like you're saying the pgx native interface returns `pgx.ErrNoRows` instead of whatever `database/sql` returns. This is true. The pgx native interface doesn't run though `database/sql`.

**Comment by nicomie** [comment]
"The pgx native interface doesn't run though database/sql". 
Yes this is it. I'm new to the different drivers and interfaces and got them messed up. That is true so I'm closing the issue.
