### ISSUE TITLE
conn.Query() does not error on division by zero, but conn.QueryRow() does

### ISSUE THREAD

**Issue by v-from-meiro** [jackc/pgx#1284]
**Describe the bug**
conn.Query() does not error on division by zero, but conn.QueryRow() does

**To Reproduce**

```go
package main

import (
	"context"
	"log"

	"github.com/jackc/pgx/v4/pgxpool"
)

func main() {
	cs := "postgres://postgres:8BEtzxfZeZYW(jNt@cdp.meiro.space:5432/meiro_cdp?pool_max_conns=10&pool_min_conns=10"
	config, err := pgxpool.ParseConfig(cs)
	if err != nil {
		log.Fatal(err)
	}

	db, err := pgxpool.ConnectConfig(context.Background(), config)
	if err != nil {
		log.Fatalf("crdb_support connecting: %s", err)
	}

	sql := "SELECT 1/0"

	rows, err := db.Query(context.Background(), sql)

	log.Println(err)

	if err != nil { // this should throw an error, but does not
		log.Fatalf("err: %s", err)
	}

	for rows.Next() {
		log.Println("all good")
	}

	var r int
	err = db.QueryRow(context.Background(), sql).Scan(&r)
	if err != nil { // this throws error normally
		log.Fatalf("err: %s", err)
	}

	log.Println("end")
}

```

**Expected behavior**
Error on division by zero in Query() the same way as in QueryRow()

**Actual behavior**
QueryRow() returns `nil` and empty result set

**Version**
 - Go: go version go1.17.3 darwin/amd64
 - PostgreSQL: 14
 - pgx: v4.15.0

**Comment by jackc** [comment]
See https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.Query

> Err() on the returned Rows must be checked after the Rows is closed to determine if the query executed successfully as some errors can only be detected by reading the entire response. e.g. A divide by zero error on the last row.

**Comment by v-from-meiro** [comment]
Mea culpa, sorry for the report and thank you for the response. Apparently I can't read, because I was on that page and read the function description. Well, can I blame it on a bad case of Monday? Seriously, sorry for bothering and thank you!
