### ISSUE TITLE
Please help: Error using password in connect string 

### ISSUE THREAD

**Issue by JamesInform** [jackc/pgx#1285]
Hi,

I want to connect to my PostgreSQL server:
Host: 127.0.0.1
Port: 5432
User: postgres
Password: mypass12#
Database: postgres

When I use the following connect:
`conn, err := pgx.Connect(context.Background(), "postgres://postgres:mypass12#@127.0.0.1:5432/postgres")`

I get this error
`Unable to connect to database: cannot parse `postgres://postgres:xxxxxx@127.0.0.1:5432/postgres`: failed to parse as URL (parse "postgres://postgres:mypass12": invalid port ":mypass12" after host)`

The error seems to appear when using "#" as a character for the password.

The same connect string works just fine when using it with psql:
`psql postgres://postgres:mypass12#@127.0.0.1:5432/postgres`

**Comment by jackc** [comment]
That's the behavior of the Go URL parser. See https://go.dev/play/p/VDrGGZWm-vW.

You could use DSN style connection string instead.

```go
pgx.Connect(context.Background(), "user=postgres password=mypass12# host=127.0.0.1 port=5432 dbname=postgres")
```

**Comment by JamesInform** [comment]
Thanks, that works.

Are you judging the parser to buggy concerning this issue and will there be a fix?

**Comment by jackc** [comment]
After a little further research, both [PostgreSQL](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) and [Go](https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/net/url/url.go;l=8) claim to follow [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.1). But psql is not actually strictly following the RFC.

Your connection string is invalid. A `#` must be percent escaped. (e.g. https://go.dev/play/p/1WITfElDTgr)
