### ISSUE TITLE
windows 7 386 atomic panic error

### ISSUE THREAD

**Issue by Andvtr** [jackc/pgx#1288]
**Describe the bug**
Compiled in windows 10 x64 (GOARCH=amd64) everything works.
I compile under windows 7 386 (GOARCH=386) without errors. But after launching the application, it appears:

panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
        C:/Program Files/Go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Load64(0x11d20584)
        C:/Program Files/Go/src/runtime/internal/atomic/atomic_386.s:225 +0x10
github.com/jackc/pgx/v4/pgxpool.(*Pool).Stat(0x11d20540)
        D:/YandexDisk/work/go/RestServer_GO_v4_pg/vendor/github.com/jackc/pgx/v4
/pgxpool/pool.go:576 +0x2a
github.com/jackc/pgx/v4/pgxpool.(*Pool).checkMinConns(0x11d20540)
        D:/YandexDisk/work/go/RestServer_GO_v4_pg/vendor/github.com/jackc/pgx/v4
/pgxpool/pool.go:490 +0x21
github.com/jackc/pgx/v4/pgxpool.ConnectConfig({0x905994, 0x11d160b8}, 0x11d8d200
)
        D:/YandexDisk/work/go/RestServer_GO_v4_pg/vendor/github.com/jackc/pgx/v4
/pgxpool/pool.go:266 +0x306

Version 3 compiles and works without errors.

**To Reproduce**

If possible, please provide runnable example such as:

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v4"
)

var PG *pgx.ConnPool
var err error

func main() {
	       conf, _ := pgxpool.ParseConfig(config.Config.DBConStr)
		conf.MinConns = 1
		conf.MaxConns = 10

		**PG, err = pgxpool.ConnectConfig(context.Background(), conf)**

		if err != nil {
			mlog.WErr(1, "Pool pg connect error ", err, "")
			os.Exit(1)
		}
}
```

**Version**
 - Go: go1.18.5
 - PostgreSQL: PostgreSQL 9.3 on x86
 - pgx: github.com/jackc/pgx/v4

**Comment by jackc** [comment]
I don't have convenient access to a 32-bit Windows environment, but I think bce26b8 will fix it. Can you try master?

**Comment by Andvtr** [comment]
I checked, bce26b8 fix it. Thanks.

**Comment by jackc** [comment]
Fix is in release v4.17.1.

**Comment by FelikZ** [comment]
it seems similar should be applied to v5 @jackc

**Comment by FelikZ** [comment]
I've rolled back from latest v5 to v4, to fix that.

**Comment by jackc** [comment]
@FelikZ Just cherry-picked it into `v5-dev`.
