### ISSUE TITLE
"Unexpected EOF" error after upgrading from 4.16 to 4.17

### ISSUE THREAD

**Issue by ceferrari** [jackc/pgx#1293]
**Describe the bug**
I work at a large company where we use pgx in production and we started to notice intermittent "Unexpected EOF" errors after upgrading from 4.16 to 4.17. We also updated to 4.17.1 after a few days, and the error is still happening.

We have been trying to reproduce the problem in a local environment for several days, but it is not possible due to the intermittent behavior of the error. We've also tried several different settings for Min/Max Conns and Max Life/Idle Time, but without success so far.

Our previous configuration, which worked perfectly for over a year, up to version 4.16,, was:
```
MinConns 2
MaxConns 10
MaxConnLifetime 1 hour (default)
MaxConnIdleTime 30 minutes (default)
```

I apologize for not being able to provide the necessary steps to reproduce the problem, we really couldn't reproduce it. The error is still happening at this very moment in our systems, but they were running perfectly, for a long time, until we decided to update the pgx version to 4.17

**Expected behavior**
No "Unexpected EOF" error happening intermittently

**Actual behavior**
"Unexpected EOF" error happens intermittently, after upgrading to pgx 4.17

**Version**
 - Go: `go version go1.18.1 linux/amd64`
 - PostgreSQL: `PostgreSQL [13.4
PostgreSQL 13.4 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit]`
 - pgx: `github.com/jackc/pgx/v4 v4.17.1`

**Comment by jackc** [comment]
That's very surprising. There weren't many changes between `v4.16.0` and `v4.17.0` and none that I would expect to be able to cause that type of error.

Maybe try `v4.16.1`. That could narrow down where the problem was introduced. Beyond that -- I know this would be onerous since the error only occurs on production -- but you could essentially try bisecting between v4.16.1 and v.4.17.0. There are only ~10 code commits.

**Comment by ankon** [comment]
@ceferrari have you ever been able to figure out whether this problem was caused by the update?

**Comment by ceferrari** [comment]
@ankon It wasn't exactly version 4.17 itself, but rather the conflict between versions 4.17 and 4.16. We have a shared lib that is at version 4.16 and recently we had another case like this in a different team here at the company. Again, the problem happened after they had updated to 4.17 in the application, while the shared lib was still at 4.16. Just like us, they rolled back the app to 4.16 and the issue was resolved.

**Comment by bfontaine** [comment]
Is this a bug in pgx or can we close the issue?

**Comment by ceferrari** [comment]
@bfontaine closing.
