### ISSUE TITLE
CopyFrom failed to insert double quoted string into jsonb column

### ISSUE THREAD

**Issue by munnik** [jackc/pgx#1294]
**Describe the bug**
The string `"value_with_quotes"` is a valid JSON object. The CopyFrom method can not insert this JSON object and returns an error `ERROR: unsupported jsonb version number 34 (SQLSTATE XX000)`

**To Reproduce**
```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgx/v4"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

	conn.Exec(context.Background(), "CREATE TABLE test (v JSONB)")

	_, err = conn.CopyFrom(
		context.Background(),
		pgx.Identifier{"test"},
		[]string{"v"},
		pgx.CopyFromRows([][]interface{}{{`"value_with_quotes"`}}),
	)
	if err != nil {
		fmt.Printf("Error using CopyFrom: %s\n", err.Error())
	}

	_, err = conn.Exec(
		context.Background(),
		"INSERT INTO test (v) VALUES ($1)",
		`"value_with_quotes"`,
	)
	if err != nil {
		fmt.Printf("Error using Exec: %s\n", err.Error())
	}

	rows, _ := conn.Query(context.Background(), "SELECT * FROM test")
	for rows.Next() {
		fmt.Println(rows.Values())
	}

	conn.Exec(context.Background(), "DROP TABLE test")
}
```

**Expected behavior**
```
[value_with_quotes] <nil>
[value_with_quotes] <nil>
```

**Actual behavior**
```
Error using CopyFrom: ERROR: unsupported jsonb version number 34 (SQLSTATE XX000)
[value_with_quotes] <nil>
```

**Version**
 - Go: `$ go version` -> go version go1.19 linux/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v4.17.1

**Additional context**
34 is the ascii code for the double quote symbol (")

**Comment by jackc** [comment]
`CopyFrom` requires all values to be in the binary format. If it is a `pgtype` type this will happen automatically. But strings are passed through directly. The `jsonb` type binary format is `x01` followed by the text.

You can use a `pgtype.JSONB` instead of a string to resolve the issue on pgx `v4`. In the upcoming `v5` it will automatically encode to binary.
