### ISSUE TITLE
v5 pgxpool docs should use NewWithConfig

### ISSUE THREAD

**Issue by wttw** [jackc/pgx#1306]
Trivial documentation bug.

[pgxpool/doc.go](https://github.com/jackc/pgx/blob/90b69c0ee006e7b43097cd393d0ccf31aaa02766/pgxpool/doc.go#L23) should use NewWithConfig() rather than NewConfig().

**Comment by jackc** [comment]
Thanks! Fixed.

**Comment by henvic** [comment]
Congrats on the release :)
