### ISSUE TITLE
windows 7 386 atomic panic error in version 5

### ISSUE THREAD

**Issue by Andvtr** [jackc/pgx#1307]
Compiled in windows 10 x64 (GOARCH=amd64) everything works.
I compile under windows 7 386 (GOARCH=386) without errors. But after launching the application, it appears:

panic: unaligned 64-bit atomic operation

goroutine 18 [running]:
runtime/internal/atomic.panicUnaligned()
        C:/Program Files/Go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Load64(0x121aa0a4)
        C:/Program Files/Go/src/runtime/internal/atomic/atomic_386.s:225 +0x10
github.com/jackc/pgx/v5/internal/nbconn.(*NetConn).isClosed(...)
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/internal/nbconn/nbconn.go:354
github.com/jackc/pgx/v5/internal/nbconn.(*NetConn).Write(0x121aa000, {0x121800e0, 0x8, 0x8})
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/internal/nbconn/nbconn.go:156 +0x2d
encoding/binary.Write({0x9bea30, 0x121aa000}, {0x9c3328, 0xcd08e8}, {0x8794c0, 0x121840c0})
        C:/Program Files/Go/src/encoding/binary/binary.go:442 +0xf80
github.com/jackc/pgx/v5/pgconn.startTLS(0x121aa000, 0x1209a0e0)
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/pgconn/pgconn.go:387 +0x8c
github.com/jackc/pgx/v5/pgconn.connect({0x9c2574, 0x1208a240}, 0x12096090, 0x1209f050, 0x0)
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/pgconn/pgconn.go:267 +0x2f5
github.com/jackc/pgx/v5/pgconn.ConnectConfig({0x9c2534, 0x12086000}, 0x12096090)
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/pgconn/pgconn.go:158 +0x3f0
github.com/jackc/pgx/v5.connect({0x9c2534, 0x12086000}, 0x12096090)
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/conn.go:230 +0x309
github.com/jackc/pgx/v5.ConnectConfig({0x9c2534, 0x12086000}, 0x12096000)
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/conn.go:120 +0xb9
github.com/jackc/pgx/v5/pgxpool.NewWithConfig.func1({0x9c2534, 0x12086000})
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/pgxpool/pool.go:209 +0x132
github.com/jackc/puddle/v2.(*Pool[...]).constructResourceValue(...)
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/puddle/v2/pool.go:600
github.com/jackc/puddle/v2.(*Pool[...]).CreateResource(0x12045200, {0x9c2534, 0x12086000})
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/puddle/v2/pool.go:501 +0x6b
github.com/jackc/pgx/v5/pgxpool.(*Pool).createIdleResources.func1()
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/pgxpool/pool.go:476 +0x78
created by github.com/jackc/pgx/v5/pgxpool.(*Pool).createIdleResources
        D:/YandexDisk/work/go/RestServer_GO_v6/vendor/github.com/jackc/pgx/v5/pgxpool/pool.go:474 +0x96

Version

Go: go1.91.1
PostgreSQL: PostgreSQL 9.3 on x86
pgx: github.com/jackc/pgx/v5

**Comment by jackc** [comment]
I don't have convenient access to to that environment but I think that d7c7ddc594209e641b6066b625973e8d7d711142 should resolve the issue.

**Comment by bfontaine** [comment]
@Andvtr did the change mentioned above and released in [v5.0.1](https://github.com/jackc/pgx/blob/master/CHANGELOG.md#v501-september-24-2022) fix your issue?

**Comment by bfontaine** [comment]
I’m closing this. Please reopen the issue if the bug is not resolved.
