### ISSUE TITLE
Update Getting Started Docs Hello World Example to v5

### ISSUE THREAD

**Issue by joncalhoun** [jackc/pgx#1309]
I'd love to submit this as a PR since it is so small, but I don't really know how with the wiki.

On this page: https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql/
The "Hello world from Postgresql" example has:

```go
import (
  // ...
  
  _ "github.com/jackc/pgx/v4/stdlib"
)
```

I believe this should be updated to v5.

**Comment by jackc** [comment]
Thanks! Fixed.
