### ISSUE TITLE
tx.afterClose is called twice

### ISSUE THREAD

**Issue by mhamrle** [jackc/pgx#131]
I found use case when tx.afterClose is called twice. When I have transaction
where commit ends up with error 
		 ERROR: could not serialize access due to read/write dependencies among transactions (SQLSTATE 40001)
the commit method runs tx.afterClose, exit with error but does not change state.
In my code I am calling Rollback as cleaning transaction on any error. The
problem is that Rollback call tx.afterClose again because tx status is still
TxStatusInProgress.
The result is that one transaction is twice in ConnPool.availableConnections and
later it is used two different independent requests / transactions that ends up
on conflict.

I think it is needed to change state here https://github.com/jackc/pgx/blob/410a7646bcf03a1ad5fc98709b10d1f50b231c19/tx.go#L89

**Comment by jackc** [comment]
Thanks! Should be fixed now.
