### ISSUE TITLE
Unable to set null value if struct implements fmt.Stringer

### ISSUE THREAD

**Issue by faulkner** [jackc/pgx#1311]
I'm not sure if this is a bug introduced in v5 or if I'm failing to understand how to use v5, but it looks like https://github.com/jackc/pgx/blob/4fc4f9a60337af3bd7c6abdf6c71460712d112fc/pgtype/pgtype.go#L1463-L1464 causes `driver.Valuer` implementations to be ignored such that any struct implementing `fmt.Stringer` won't be able to set values to `null`. This appears to only happen when using  `github.com/jackc/pgx/v5/stdlib`.

**To Reproduce**

```go
package main

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
)

type String struct {
	v       string
	present bool
}

func NewString(v string) String {
	return String{v: v, present: true}
}

func NilString() String {
	return String{"", false}
}

func (v String) String() string {
	return v.v
}

// Value implements the driver.Valuer interface
func (v String) Value() (driver.Value, error) {
	if !v.present {
		return nil, nil
	}
	return v.v, nil
}

// Scan implements the sql.Scanner interface
func (v *String) Scan(src interface{}) error {
	if src == nil {
		*v = String{present: false}
		return nil
	}
	switch t := src.(type) {
	case []byte:
		*v = String{present: true, v: string(t)}
		return nil
	case string:
		*v = String{present: true, v: t}
		return nil
	}
	return fmt.Errorf("cannot scan value %v to a string", src)
}

func main() {
	cfg, err := pgx.ParseConfig(os.Getenv("DATABASE_URL"))
	if err != nil {
		panic(err)
	}
	db, err := sql.Open("pgx", stdlib.RegisterConnConfig(cfg))
	if err != nil {
		panic(err)
	}
	defer db.Close()

	var v interface{}
	// this should return a nil but returns an empty string
	db.QueryRow("SELECT $1", NilString()).Scan(&v)
	fmt.Printf("expected <nil>, returned %T: %#v\n", v, v)

	// these are just to show that other cases still work as expected
	db.QueryRow("SELECT $1", nil).Scan(&v)
	fmt.Printf("expected <nil>, returned %T: %#v\n", v, v)

	db.QueryRow("SELECT $1", NewString("test")).Scan(&v)
	fmt.Printf("expected \"test\", returned %T: %#v\n", v, v)

	db.QueryRow("SELECT $1", "test").Scan(&v)
	fmt.Printf("expected \"test\", returned %T: %#v\n", v, v)
}
```

**Expected behavior**
If a struct implements `driver.Valuer` and returns `nil, nil` pgx should send a `null`.

**Actual behavior**
An empty string is being sent instead.

**Version**
 - Go: `1.19.1 darwin/arm64`
 - PostgreSQL: `PostgreSQL 11.14 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit`
 - pgx: `5.0.0`

If this change isn't a bug but rather a v5 design choice then please let me know if there's a recommended way to work around the issue. Thanks!

**Comment by jackc** [comment]
> If this change isn't a bug but rather a v5 design choice then please let me know if there's a recommended way to work around the issue. Thanks!

I don't think it is a bug so much as an inherent issue when supporting multiple approaches to encode and decode types. If a type supports multiple approaches one must be chosen. I don't think there is a general rule pgx could use that would satisfy all cases.

But there are a couple approaches that could solve this particular issue.

1. Implement `pgtype.TextValuer` on your type. This will have priority over `fmt.Stringer` and `driver.Valuer`. This is the simplest approach if you can modify the type.
2. Add a `TryWrapEncodePlanFunc` to the beginning of `pgtype.Map.TryWrapEncodePlanFuncs` that wraps or renames your value to a type that only implements `pgtype.TextValuer` or `driver.Valuer`.

**Comment by mpoindexter** [comment]
While I agree that a heuristic approach to encoding and decoding types can never satisfy all cases, this one seems suboptimal to me. IMO, the preference should go in increasing order of specificity. For example, in this case, `pgtype.TextValuer` should take precedence over `driver.Valuer` should take precedence over `fmt.Stringer`. This most clearly maps to intent: one could implement `fmt.Stringer` for display only, but implementing `driver.Valuer` much more clearly expresses an intent to control how a value is mapped to the DB, and `pgtype.TextValuer` most clearly indicates intent to control how the value is mapped to a PostgreSQL DB specifically.

**Comment by jackc** [comment]
This is tricky due to `driver.Valuer` returning `any`. For example, we can plan for `fmt.Stringer` because it always returns a `string`. But we actually have to execute `Value()` to know what type we are trying to encode.

Because of this `driver.Valuer` was always handled as the last option. But with pgx v5 now having the ability to find underlying types like a `string` and supporting `fmt.Stringer` it meant that `driver.Valuer` was often not getting called because something else was found first.

This change tries `driver.Valuer` immediately after the initial `PlanScan` for the `Codec`. So a type that directly implements a pgx interface should be used, but `driver.Valuer` will be preferred before all the attempts to handle renamed types, pointer dereferencing, etc.

I think this should resolve the issue without breaking anything else.

See also: https://github.com/jackc/pgx/issues/1319
