### ISSUE TITLE
net.IP IPv4 behavior change with v5

### ISSUE THREAD

**Issue by oschwald** [jackc/pgx#1317]
**Describe the bug**

When using `stdlib`, I am seeing IPv4 addresses stored in the `net.IP` type converted to IPv6 addresses in Postgres.

**To Reproduce**

If possible, please provide runnable example such as:

```go
package main

import (
	"database/sql"
	"fmt"
	"log"
	"net"
	"os"

	_ "github.com/jackc/pgx/v5/stdlib"
)

func main() {
	db, err := sql.Open("pgx", os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	ip := net.ParseIP("1.1.1.1")

	var str string
	err = db.QueryRow(
		`SELECT $1::inet`,
		ip,
	).Scan(&str)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(ip, str)
}
```

**Expected behavior**

For it to print:

```
1.1.1.1 1.1.1.1
```

**Actual behavior**

```
1.1.1.1 ::ffff:1.1.1.1
```

**Version**
 - Go: `go version go1.19.1 linux/amd64`
 - PostgreSQL: `PostgreSQL 14.5 (Ubuntu 14.5-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, 64-bit`
 - pgx: `5.0.1`

**Additional context**

I can work around this behavior by doing something like:

```
if v4 := ip.To4(); v4 != nil {
    ip = v4
}
```

However, it isn't possible to do this with confidence in a large codebase.

I assume this is related to the switch to `net/netip` as the internal type. This does seem like an improvement, but if possible, I think doing something like the above workaround in `pgx` when dealing with `net.IP` would lead to the expected behavior in most cases.

**Comment by jackc** [comment]
AFAICT, this behavior has not changed. I took your example and ran it with `v4` and `v5` and get the same results.

```go
package main

import (
	"database/sql"
	"fmt"
	"log"
	"net"
	"os"

	_ "github.com/jackc/pgx/v5/stdlib"
)

func main() {
	db, err := sql.Open("pgx", os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	ip := net.ParseIP("1.1.1.1")
	fmt.Println("Before", ip, ip.String(), len(ip))

	var str string
	err = db.QueryRow(
		`SELECT $1::inet`,
		ip,
	).Scan(&str)
	if err != nil {
		log.Fatal(err)
	}

	ip2 := net.ParseIP(str)
	fmt.Println("str", str)
	fmt.Println("After", ip2, ip2.String(), len(ip2))
}
```

Output:
```
Before 1.1.1.1 1.1.1.1 16
str ::ffff:1.1.1.1
After 1.1.1.1 1.1.1.1 16
```

Also, I think this is correct behavior. `net.ParseIP()` *is* returning a IPv4-mapped IPv6 address. pgx and PostgreSQL are correctly preserving this through the round trip (this was actually a feature request: 4db2a33562c6d2d38da9dbe9b8e29f2d4487cc5b).

**Comment by oschwald** [comment]
Interesting. You are correct that my test case does not capture the difference that I am seeing in a larger application between v4 and v5 around `net.IP` handling. I'll try to come up with something better.

As far as whether this behavior is correct, I am not sure. Most users of `net.IP` expect `net.ParseIP("1.1.1.1")` to behave like `1.1.1.1` in Postgres. `net.IP` is fundamentally broken in this regard though, and I am definitely not asking for a behavior change from v4.

**Comment by oschwald** [comment]
Ah, I see the difference. We have a domain defined as:

```
CREATE DOMAIN public.inet_address AS inet
        CONSTRAINT not_a_network CHECK ((((family(VALUE) = 4) AND (masklen(VALUE) = 32)) OR ((family(VALUE) = 6) AND (masklen(VALUE) = 128))));
```

In `v4`, we didn't have to register this type for it to work with something like `net.IP`. I _think_ `pgx` just treated unknowns (at least when using `stdlib`) as text types and would stringify the `net.IP`. In `v5`, we need to specifically register this type and we used `&pgtype.InetCodec{}`, introducing the behavior change.

I am not sure if the handling of unknown types and stringification was an intentional change. It did end up causing quite a bit of churn in our code base that almost exclusively uses `stdlib` (+640 -593 as it currently stands). That said, the original issue above is mistaken and I'll close it.
