### ISSUE TITLE
Listen and Notify documentation correction

### ISSUE THREAD

**Issue by JamesInform** [jackc/pgx#1318]
I just came across the documentation of listen/notify:
![image](https://user-images.githubusercontent.com/38714600/192954392-ab6067ec-671c-416f-b5c7-e250e887d293.png)

The "// do something with notification" will only be executed, if an error occures (err != nil). So I think it needs to be "err == nil" or the notification handling should begin after the brackets.

**Comment by jackc** [comment]
Thanks! Fixed.
