### ISSUE TITLE
v5 behavior change with types implementing driver.Valuer

### ISSUE THREAD

**Issue by nick-jones** [jackc/pgx#1319]
It's unclear to me if this change in behaviour was intentional - apologies if it is. I've scanned the changelog, and can't find anything pertinent, though I don't doubt I might have missed something.

Say I've defined a type that uses `string` as the underlying source type. With that type I've implemented `driver.Valuer` with the intention of augmenting things such only the length of the underlying string is ever inserted (this is a contrived example, but hopefully easy to follow). Previously it has been possible to achieve that with the following code:

```go
package main

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"log"

	_ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
	if err := run(context.Background()); err != nil {
		log.Fatal(err)
	}
}

func run(ctx context.Context) error {
	// postgres must be running: docker run -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:14.5-alpine
	db, err := sql.Open("pgx", "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable")
	if err != nil {
		return err
	}

	if _, err = db.ExecContext(ctx, "CREATE TABLE test ( id serial PRIMARY KEY, foo text DEFAULT NULL )"); err != nil {
		return err
	}

	if _, err = db.ExecContext(ctx, "INSERT INTO test VALUES (1, $1)", Foo("test")); err != nil {
		return err
	}

	var value string
	row := db.QueryRowContext(ctx, "SELECT foo FROM test WHERE id = 1")
	if err = row.Scan(&value); err != nil {
		return err
	}

	log.Printf("value = %q", value)

	return nil
}

type Foo string

func (f Foo) Value() (driver.Value, error) {
	log.Printf("Foo.Value() called")
	return fmt.Sprintf("%d", len(f)), nil
}
```

Running the above yields..

```
2022/09/29 14:09:13 Foo.Value() called
2022/09/29 14:09:13 value = "4"
```

However, if you change the import to be v5:

```diff
--- a/main.go
+++ b/main.go
@@ -7,7 +7,7 @@ import (
 	"fmt"
 	"log"

-	_ "github.com/jackc/pgx/v4/stdlib"
+	_ "github.com/jackc/pgx/v5/stdlib"
 )

 func main() {
```

Then `Foo.Value()` is no longer called - instead the underlying string value is inserted:

```
2022/09/29 14:09:51 value = "test"
```

Would it be possible to get some clarification over whether this was an intentional change?

**Comment by jackc** [comment]
The underlying issue appears to be the same as #1311.
