### ISSUE TITLE
Query the bytea data, but return the wrong result

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pgx#1320]
If the table has the bytea column, I use the following sql query string:
select * from table
and scan the result like the following:
               value := make([]interface{}, len(cls))
		for i := 0; i < len(cls); i++ {
			value[i] = &sql.NullString{}
		}
		err := rows.Scan(value...)
the len(cls) means the length of the columns.
if the column type is bytea, the value is wrong, for example, the column data is '\xDEADBEEF', but the return value in sql.NullString is 
"ޭ\xbe\xef", the "DEAD" is lost.
@jackc

**Comment by jackc** [comment]
If you are selecting a bytea you will get binary data back. You are seeing the string representation of raw binary data.  `\xDEADBEEF` is the hex encoding of that binary data *not* the data itself. If you want the hex encoding you will need to read it into a `[]byte` and hex encode it.

**Comment by zhanghaiyang9999** [comment]
> If you are selecting a bytea you will get binary data back. You are seeing the string representation of raw binary data. `\xDEADBEEF` is the hex encoding of that binary data _not_ the data itself. If you want the hex encoding you will need to read it into a `[]byte` and hex encode it.

Can support sql.NullString type? because in most cases, I query the record is dynamically, I don't know the column type.

**Comment by jackc** [comment]
> Can support sql.NullString type?

You could configure the pgx connection to always use the simple protocol which always uses the text format -- though that will cost you some performance. See https://pkg.go.dev/github.com/jackc/pgx/v5#ConnConfig -> `DefaultQueryExecMode`.

> I query the record is dynamically, I don't know the column type.

https://pkg.go.dev/database/sql#Rows.ColumnTypes.

**Comment by zhanghaiyang9999** [comment]
> > If you are selecting a bytea you will get binary data back. You are seeing the string representation of raw binary data. `\xDEADBEEF` is the hex encoding of that binary data _not_ the data itself. If you want the hex encoding you will need to read it into a `[]byte` and hex encode it.
> 
> Can support sql.NullString type? because in most cases, I query the record is dynamically, I don't know the column type.

Thanks!
