### ISSUE TITLE
[Request] Add conflict handler to CopyFrom

### ISSUE THREAD

**Issue by jflambert** [jackc/pgx#1328]
**Is your feature request related to a problem? Please describe.**
I would like to ignore specific conflicts when using `CopyFrom`

**Describe the solution you'd like**
Credit goes to [raratiru on stackoverflow](https://stackoverflow.com/a/49836011/651980) but I believe this is a somewhat standard pattern.

Basically the COPY statement is preceded by a temp table creation, and followed by an INSERT/SELECT statement. Ideally I would customize the `ON CONFLICT (xxx) DO yyy;` part through pgx.

**Describe alternatives you've considered**
Before adding them to `CopyFromRows`, I am currently inspecting records and determining if they could cause a violation. If so I add them to an `INSERT .. ON CONFLICT` batch, otherwise I use `CopyFrom`.

I suppose I could also create the table first, call CopyFrom on it, do the insert/select then and finally drop the temp table. But I think it would be a great feature to have.

**Additional context**
![image](https://user-images.githubusercontent.com/11539524/194145959-7d1d2de8-3dc6-4eed-af8f-eb2088454325.png)

**Comment by jackc** [comment]
I don't know of any way to ignore conflicts in the copy protocol. AFAIK, copying to a temp table and inserting from there with `on conflict do nothing` is the only option.
