### ISSUE TITLE
Connect to AppEngine & use contexts

### ISSUE THREAD

**Issue by marwan-nwh** [jackc/pgx#1329]
To connect to Google Cloud SQL you can use pgx through the standard sql package like [this](https://cloud.google.com/sql/docs/postgres/connect-app-engine-standard#connect_to).  This method works, but you can't use contexts with it. And the method in the readme here doesn't work. So what is the optimal way here?

**Comment by StevenACoffman** [comment]
Hi. 
1. A `*sql.DB` isn't really connecting to the DB until you do something with it (it is just a managed pool of potential connections). You can use context with *sql.DB methods: 	`Conn`, `ExecContext`, `QueryContext`.
2. We use AppEngine and the method in the readme works fine for us. Maybe you can specify what part of what readme didn't work for you and what your error message was?

**Comment by marwan-nwh** [comment]
Sorry, I don't recall the issue. It was last year. Please ignore it.
