### ISSUE TITLE
Return BeginFunc like method of pgx.Conn and pgx.Tx

### ISSUE THREAD

**Issue by ilya-korotya** [jackc/pgx#1333]
Previously, I could describe the universal interface for the database driver. This interface looked like the interface of a million other repositories that I have seen.
```go
// Querier common interface for pgx connection.
type Querier interface {
	Begin(ctx context.Context) (pgx.Tx, error)
	BeginFunc(ctx context.Context, f func(pgx.Tx) error) (err error)
	Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row
}
```
And my entire level of the repository depended only on this interface.

Now all my repository level depends on pgx library. It is a lousy pattern of programming.

I was trying to create a wrapper for the new BeginFunc, but all time got some error or bad solution.
For example:
```go
func (s *Storage) BeginFunc(ctx context.Context, fn func(s *Storage) error) (err error) {
	var tx pgx.Tx
	tx, err = s.Begin(ctx)
	if err != nil {
		return err
	}

	defer func() {
		rollbackErr := tx.Rollback(ctx)
		if rollbackErr != nil && !errors.Is(rollbackErr, pgx.ErrTxClosed) {
			err = rollbackErr
		}
	}()

	fErr := fn(tx) // types error here // Storage{*pgxpool.Pool}
	if fErr != nil {
		_ = tx.Rollback(ctx)
		return fErr
	}

	return tx.Commit(ctx)
}
```

**Comment by ilya-korotya** [comment]
The old conversation about the common `Querier` interface. https://github.com/jackc/pgx/issues/1188

**Comment by jackc** [comment]
> And my entire level of the repository depended only on this interface.

> Now all my repository level depends on pgx library. 

It already depended on pgx. All of the methods in your `Querier` interface have a pgx type in their signature. And the function passed to `BeginFunc` includes a `pgx.Tx` in its signature.

One reason `BeginFunc` was changed from a method to a function is it really is a function implemented in terms of `Begin`. There is nothing specific to any implementer.

The change is simple and mechanical. Here's a change from one of my projects:

Before:

```go
err := db.BeginFunc(ctx, func(db pgx.Tx) error {
```

After:

```go
err := pgx.BeginFunc(ctx, db, func(db pgx.Tx) error {
```

**Comment by ilya-korotya** [comment]
Resolved
