### ISSUE TITLE
CollectOneRow returns ErrNoRows on unique violation error

### ISSUE THREAD

**Issue by ysomad** [jackc/pgx#1334]
HI! Moving from v4 to v5.

I'm updating a table, returning all field values from it and scanning received row into struct but `pgx.CollectOneRow` returns `pgx.ErrNotRows` on unique violation error unlike using `pgxpool.Pool.Query.Scan`.

Error handling in both cases is the same:

```go
// pgxpool.Pool.QueryRow.Scan or pgx.CollectOneRow call
if err != nil {
  if errors.Is(err, pgx.ErrNoRows) {
    return nil, errors.new("account not found")
  }

  var pgErr *pgconn.PgError
  if errors.As(err, &pgErr) && pgErr.ConstraintName == "account_email_key" {
    return nil, errors.New("email taken")
  }

  return nil, err
}
```

### Steps to reproduce the behavior:

1. Try to update unique column with value already exist in the table using `pgxpool.Pool.Query`
2. Scan rows with `pgx.CollectOneRow` into struct using `pgx.RowToStructByPos`
3. Handle errors as above

### Expected behavior:
`pgx.CollectOneRow` returns `*pgconn.PgError` on unique violation errors

### Actual behavior:
`pgx.CollectOneRow` returns `pgx.ErrNoRows` on unique violation errors

### Versions:

 - Go: go version go1.19.2 darwin/arm64
 - PostgreSQL: PostgreSQL 14.5 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
 - pgx: v5.0.2

**Comment by jackc** [comment]
Thanks for the clear report. Fixed.
