### ISSUE TITLE
CopyFrom no longer knows how to encode strings as enum values in V5

### ISSUE THREAD

**Issue by davidmdm** [jackc/pgx#1338]
**Describe the bug**
When using CopyFrom in V4 you could use string values for column fields of type enum.
This behaviour is broken in V5.

**To Reproduce**
Wrote a simple program to demonstrate:
```go
package main

import (
	"context"
         "os"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.GetEnv("DB_URL"))
	panicMaybe(err)

	_, err = conn.Exec(
		context.Background(),
		`
		create type my_enum as enum('yes','no','toaster');

		create table example(
			value my_enum
		)`,
	)
	panicMaybe(err)

	_, err = conn.CopyFrom(context.Background(), []string{"example"}, []string{"value"}, pgx.CopyFromRows([][]any{{"yes"}}))
	panicMaybe(err)
}

func panicMaybe(err error) {
	if err != nil {
		panic(err)
	}
}
```

Which results in output:
```
panic: ERROR: COPY from stdin failed: unable to encode "yes" into binary format for unknown type (OID 16386): cannot find encode plan (SQLSTATE 57014)
...
```

**Expected behavior**
CopyFrom should write the string to the target enum column if value satisfies enum. (Same behaviour as pgx/v4)

**Actual behavior**
CopyFrom returns an error if the target column is an enum.

**Version**
 - Go:  go1.19.1 darwin/amd64
 - PostgreSQL: postgres 13.3
 - pgx: 5.0.3

**

**Comment by jackc** [comment]
`COPY` is a little tricky. A query can have some values encoded in text and some in binary. Strings parameters are automatically passed in the text format so unknown types are fine. But `COPY` requires all values be encoded in the same format. pgx currently only uses the binary format. v5 is a bit stricter in this case than v4. v4 would just send `string` bytes over the wire and hope for the best. This actually works for enums as the binary format is the same as the text format.

But it could lead to unexpected errors if the PostgreSQL type had a different binary than text representation.

---

Your example can be made to work by registering your enum type with pgx.

```go
	t, err := conn.LoadType(context.Background(), "my_enum")
	panicMaybe(err)
	conn.TypeMap().RegisterType(t)
```

---

As far as a general solution, I'm not sure. I don't think going back to the lax approach of v4 is correct. If the Go and PostgreSQL types are mismatched in a particularly bad way silent data corruption could occur.

The other solution would be to check all columns for binary and text format support and fall back automatically to the text format if there is an unknown type. But this adds a bit of complication and leads to a silent performance loss. I'm not against this change, but given the application registering the enum is the best solution for correctness and performance I'm not sure it is a clear win either.

**Comment by davidmdm** [comment]
I don't mind this new more performant approach. Maybe I missed documentation around this. I saw the documentation around the `pgtype.Map`, but didn't see examples like the above on how to register custom types. Perhaps I missed it, or new documentation on the subject could help.

Which also leads to another thought. It can be slightly tedious to keep track of all custom types and make sure they are registered. If all that needs to be done is loading them by name and registering them, perhaps some kind of API to discover and load custom types could be useful.

**Comment by davidmdm** [comment]
Also when trying this myself, I have been loading types using their `"schema"."name"` and noticing that this is what is being registered as the key on the type map.  However if I do it like you did in the example above, only the `name` is used as the key in the type map. 

What format needs to be used so that CopyFrom will be able to auto detect the correct codec? It feels a little off that the same type can be registered using different keys on the global type map.

**Comment by jackc** [comment]
> I don't mind this new more performant approach. Maybe I missed documentation around this. I saw the documentation around the pgtype.Map, but didn't see examples like the above on how to register custom types. Perhaps I missed it, or new documentation on the subject could help.

No examples, but it is briefly mentioned here: https://pkg.go.dev/github.com/jackc/pgx/v5@v5.0.3/pgtype#hdr-Enum_Support

> Which also leads to another thought. It can be slightly tedious to keep track of all custom types and make sure they are registered. If all that needs to be done is loading them by name and registering them, perhaps some kind of API to discover and load custom types could be useful.

For enums anyway, yes, all that needs to be done is load them by name. At one point pgx (back in v3 maybe) automatically scanned the `pg_type` table and did as much type registration as it could. However, that caused a problem because some people had databases with an enormous number of types such that it would take several seconds to establish a connection.

I usually end up with something like this that gets called in an `AfterConnect` hook:

```go
func RegisterDataTypes(ctx context.Context, conn *pgx.Conn) error {
	tm := conn.TypeMap()
	pgxdecimal.Register(tm)
	pgxuuid.Register(tm)

	dataTypeNames := []string{
		// my type names
	}

	for _, typeName := range dataTypeNames {
		dataType, err := conn.LoadType(ctx, typeName)
		if err != nil {
			return err
		}
		tm.RegisterType(dataType)
	}

	return nil
}
```

> Also when trying this myself, I have been loading types using their "schema"."name" and noticing that this is what is being registered as the key on the type map. However if I do it like you did in the example above, only the name is used as the key in the type map.

The name is used to lookup the OID. If you don't have any name collisions you don't need the schema. If you do, then you do. After the OID is found the name is just for reference.

> Lastly it seems that TypeMaps are not shared between connections in a pool, which makes it much harder to use custom types with pgxpool. It would make sense to me that connections in a pool should share a pointer to the same TypeMap.

It's very unlikely that this will change. The Map has an internal cache of ScanPlans. This cache can be updated on any query. The synchronization would be a problem. Typically, all type registration is done in an AfterConnect hook.
