### ISSUE TITLE
Can CopyFrom support like  pq.CopyIn()?

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pgx#1346]
hi @jackc 
Use pq.CopyIn() is very easily and faster, it doesn't depend on the pgx or sql types in most cases, just put sql.nullstring or string, but CopyFrom depends on the pgx types, it's difficult to use this powerful feature, because must convert the sql data to pgx types before using it, but postgresql's types are too many to convert and may bring new data types in future.
Can copyFrom support the literal string format? thanks!

**Comment by jackc** [comment]
I've never used this pq feature. So I don't really know what you are asking for.

**Comment by zhanghaiyang9999** [comment]
> I've never used this pq feature. So I don't really know what you are asking for.
For example, there is test table, the create sql is:
CREATE TABLE IF NOT EXISTS public.testtable
(
    id bigint NOT NULL,
    fbox box,
    ids bigint[],
    CONSTRAINT testtable_pkey PRIMARY KEY (id)
)

pq.CopyIn is same CopyFrom function, if use CopyFrom, the codes like this:

inputRows := [][]interface{}{
		{2, &pgtype.Box{P: [2]pgtype.Vec2{{X: 0, Y: 0}, {X: 200, Y: 200}}, Status: pgtype.Present}, []int{1, 2, 3}},
	}
	copyCount, err := conn.CopyFrom(context.Background(), pgx.Identifier{"public", "testtable"}, []string{"id", "fbox", "ids"}, pgx.CopyFromRows(inputRows))

it requires the right pgtypes to meet the table column type, please see the codes above, the types such as Vec2, []int ,etc.

But For pg.CopyIn, it doesn't depend the sql type in most cases, the codes like this:

stmt, _ := transaction.Prepare(pq.CopyIn(
		"testtable",
		"id", "fbox", "ids",
	))
	_, err = stmt.Exec(
		1, "0,0,100,100", "{1,100}",
	)

the "0,0,100,100" behalf of the Box and the string "{1,100}" means the array [1,100],

Can CopyFrom support this  string format (means ignore the actual data type)? it can reduce much time from database to another database conversion and use this feature easily,

**Comment by jackc** [comment]
Text mode copy protocol is possible where strings are passed through without processing is possible. But I don't want to match the `pq` interface (its requirement to fit in database/sql distorts the interface).

I suppose this could also be a solution to #1338.

**Comment by zhanghaiyang9999** [comment]
> Text mode copy protocol where strings are passed through without processing is possible. But I don't want to match the `pq` interface (its requirement to fit in database/sql distorts the interface).
> 
> I suppose this could also be a solution to #1338.
no need to match the pq interface, but can support like the following code are great!!

inputRows := [][]interface{}{
{1, "0,0,100,100", "{1,100}"},
}

**Comment by jackc** [comment]
I've closed this issue in favor of #1362 which directly specifies the feature desired.
