### ISSUE TITLE
Regression from v4: can't store uint64

### ISSUE THREAD

**Issue by punkeel** [jackc/pgx#1357]
**Describe the bug**

pgx/v4 was able to write `uint64` to a `number` column, but this broke with v5.

The column is of type `numeric`, the variable passed to Exec/Query is a `uint64`.

**To Reproduce**

1. Create table with `numeric` column.
2. Try to insert a "large" value in this table, eg: `uint64(16947563853626821303)`.

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

_, err = tx.Exec(`
UPDATE my_table
SET a_number = $1,
WHERE id = $2
`,
		bigNumber,
		id,
	)
	if err != nil {
		return err
	}

}
```

**Expected behavior**
No errors, the query should run. If the value fits in a Go `uint64`, it should fit in a `numeric` column.

**Actual behavior**
An error is thrown:  `failed to encode args[0]: unable to encode 0xeb31d78867ad4ab7 into binary format for numeric (OID 1700): 16947563853626821303 is greater than maximum value for int64`

**Version**
 - Go: `$ go version` -> `go version go1.19.2 darwin/arm64`
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> `PostgreSQL 14.4 (Debian 14.4-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> `github.com/jackc/pgx/v5 v5.0.4`

Not using `jackc/pgtypes`.

**Comment by punkeel** [comment]
https://github.com/jackc/pgx/blob/987de3874e0fc18b8c468d27cb9de9b2cd67540c/pgtype/builtin_wrappers.go#L250

Looks like the error comes from this line, and I presume `func (w *uint64Wrapper) ScanInt64(v Int8) error {` would fail as well.

I'm not sure why the code assumes that an `uint64` fits in an `int64`, as that's not true?

```
uint64 : 0 to 18446744073709551615 
int64  : -9223372036854775808 to 9223372036854775807
```

**Comment by jackc** [comment]
Fixed.

**Comment by punkeel** [comment]
Thank you! I confirm our tests now pass with this fix 👍
