### ISSUE TITLE
Only first call to a stored procedure works

### ISSUE THREAD

**Issue by cjheath** [jackc/pgx#1358]
**Describe the bug**

Using conn.Query(context.Background(), query_string, parameters...); to call a stored procedure that inserts a row into a database table, the first call works, but subsequent calls get silently ignored. My `query_string` is "CALL my_procedure $1,$2,$3,$4,$5" with five parameters provided (time.Time, two strings, two integers).

**To Reproduce**
Steps to reproduce the behaviour:

With this table:
```sql
CREATE TABLE test (
    value varchar,
    primary key(value)
);
```

and this stored procedure:
```sql
CREATE OR REPLACE PROCEDURE my_procedure(v varchar)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO test(value) VALUES(v);
END
$$;
```

Run this with multiple arguments:
```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v4"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

        for i, val := range os.Args {
                if i > 0 {
	                conn.Query(context.Background(), "CALL my_procedure $1", val);
                }
        }
}
```

**Expected behavior**

I expect to see one row inserted for each program parameter (each call to the stored procedure)

**Actual behavior**

The first call succeeds - the first program parameter value is inserted into the table. All subsequent calls on the same connection silently do nothing. Re-running the program allows one more call to work each time (assuming primary key uniqueness isn't violated).

**Version**
 - Go: `go version go1.18.2 darwin/amd64
 - PostgreSQL: PostgreSQL 14.0 on x86_64-apple-darwin18.7.0, compiled by Apple clang version 11.0.0 (clang-1100.0.33.17), 64-bit
 - pgx: github.com/jackc/pgx/v4 v4.17.2

**Additional context**

**Comment by cjheath** [comment]
Using QueryRow, and scanning the result row, seems to prevent this. So I assume that the subsequent calls are queued up behind the first one which has not been finalised.

Perhaps this should be viewed as a documentation bug. This behaviour is not obvious, and doesn't appear to be adequately documented.

**Comment by jackc** [comment]
See https://pkg.go.dev/github.com/jackc/pgx/v4#hdr-Query_Interface. 

The returned Rows must be closed before the connection can be used again. In addition, I suspect if you checked the err from the Query call you would be receiving "conn busy" errors.

**Comment by cjheath** [comment]
Fair enough. It's not at all clear that calling a stored proc (which has no return) returns a rowset which must be closed.
And the documentation of Query and friends doesn't mention that the result must be processed:
https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.Query
That requirement should be documented right where those methods are.

**Comment by jackc** [comment]
> It's not at all clear that calling a stored proc (which has no return) returns a rowset which must be closed.

If no rowset is expected then `Exec` should be used instead.

**Comment by cjheath** [comment]
Ok. But I still regard this as a documentation bug.

Where is the documentation that a SELECT returns rows that *must* be fetched and closed before a new query can be issued? Is it so difficult to add that information where the Query method is documented?

Essentially this means that the connection object is modal, depending on actions performed on a different object (the Rows). Is this modality documented here, and if not, is it important to keep that a secret? https://pkg.go.dev/github.com/jackc/pgx/v4#Conn?

**Comment by jackc** [comment]
Ah. The v4 docs for Query. The v5 docs are more explicit: https://pkg.go.dev/github.com/jackc/pgx/v5#Conn.Query

> Query sends a query to the server and returns a Rows to read the results. Only errors encountered sending the query and initializing Rows will be returned. Err() on the returned Rows must be checked after the Rows is closed to determine if the query executed successfully.

> The returned Rows must be closed before the connection can be used again. It is safe to attempt to read from the returned Rows even if an error is returned. The error will be the available in rows.Err() after rows are closed. It is allowed to ignore the error returned from Query and handle it in Rows. 

I backported the docs to v4.

**Comment by cjheath** [comment]
Excellent result. Thank you.
