### ISSUE TITLE
"Scan cannot decode into *int"

### ISSUE THREAD

**Issue by atombender** [jackc/pgx#136]
This surprised me:

```go
var id int
row := tx.QueryRow("SELECT COALESCE(MAX(some_int), 0) FROM some_table")
err := row.Scan(&id)
```

This errs with `can't scan into dest[0]: Scan cannot decode into *int` even though it can never be null — it will always return 0 even if the table is empty. So I have to scan it into a temporary `*int` and dereference it.

I suspect that internally, in the Postgres protocol, there's a difference between int columns that may be null and those that don't. As a client I don't really care about semantics — I wonder if is there a way to force Postgres to return a non-nullable int? A cast doesn't work.

**Comment by jackc** [comment]
I don't think the problem is the null, I think it is the Go `id` variable being of type `int`. Try `int64` or `int32` according to what the type of the PostgreSQL data is.

**Comment by atombender** [comment]
But an `*int` does work. `int32` doesn't. Didn't try `int64` yet, because the column is a PostgreSQL `int`, not `bigint`.

**Comment by atombender** [comment]
Dang, it actually worked with `int32`. With `int64` I actually got a weird error:

```
can't scan into dest[0]: Cannot decode oid 23 into int8
```

**Comment by jackc** [comment]
That's to be expected -- pgx is usually strict about using the correct size integers. Though I suppose it would always to be safe to read a 32-bit integer into a 64-bit one.

**Comment by atombender** [comment]
I can see that. Still, note the `int8` — shouldn't it be `int64`? Also it's notable that it's a completely different error than the earlier one, `Scan cannot decode into *int`.

**Comment by atombender** [comment]
Oh, `int8` is the Postgres type. 8 bytes, 64 bits.
