### ISSUE TITLE
Doc still mentions pgx.QueryFuncRow, which was removed in v5

### ISSUE THREAD

**Issue by fgm** [jackc/pgx#1360]
**Describe the bug**

In `doc.go`, the `ForEachRow` example still refers to `pgx.QueryFuncRow`, which no longer exists in pgx v5.

**To Reproduce**

1. read https://github.com/jackc/pgx/blob/v5-dev/doc.go#L43
2. there is no second step

**Expected behavior**

The example explains how to use a callback with the v5 API instead of the v4 `QueryFuncRow` mechanism. 

**Actual behavior**

The example explains how to use a callback with the v4 `QueryFuncRow` mechanism. 

**Version**
 - Go: any version
 - PostgreSQL: any version
 - pgx: `v5.0.4` also v5-dev HEAD today.

**Additional context**

I was trying to convert v4 code using a `QueryFuncRow` mechanism but the changelog says nothing about the removal of that type, but it still appears in that example.

**Comment by jackc** [comment]
Fixed.
