### ISSUE TITLE
Registered domain type throws error in v5

### ISSUE THREAD

**Issue by davidspiess** [jackc/pgx#1373]
I have the following domain type:
```sql
CREATE DOMAIN score AS integer CHECK (VALUE BETWEEN 0 AND 100);
```

Before initializing the connection i registered this custom type
```go
conn.TypeMap().RegisterType("score")
```

When selecting this datatype i get the following pgx error: `unknown typtype`.
I looked the typtype up in the  `pg_type` table, it has the `typtype` `d`, which is not handled in conn.go
https://github.com/jackc/pgx/blob/6f90866f58807873816ae69f1e37d4a0fbcc8ddd/conn.go#L1156-L1180

Is `d` intentionally missing?
Thank you!

**Comment by jackc** [comment]
It's not intentional. Just was never implemented.

Done now.
