### ISSUE TITLE
Add support for an ID or similar "tag" for pgproto tracing

### ISSUE THREAD

**Issue by neophenix** [jackc/pgx#1375]
When using pgproto tracing, it often becomes hard to correlate the trace output lines with one another when multiple requests are happening, since unless I'm missing something there is nothing on the lines to relate them to others.

To remedy that locally, I've been modifying pgproto3's trace.go adding:
```
ID string
```
to the TracerOptions struct.  And:
```
if t.ID != "" {
    t.buf.WriteString(t.ID)
    t.buf.WriteByte('\t')
}
```
to the beginTrace function right after the SuppressTimestamps check.
Then typically I'll do something like set the ID in my options to PGConn().PID(), then when checking the log its easy to see what is happening on each connection.

Long term this isn't ideal since I'd like to keep up with lib changes.   So wanted to request it here in hopes you find it useful, or have an alternative method.

**Comment by jackc** [comment]
What about using a separate writer for each tracer? You could log them into separate files that way.

Or you could wrap your writer with a prefix writer such as https://github.com/abiosoft/lineprefix to trace to one file. I haven't used this library before but it looks like it would do what you want.

**Comment by neophenix** [comment]
You could do a separate writer I suppose.  Personally I like having it all in one so I can see what else is going on around the same time instead of reconstructing it all.  As for another lib I'd definitely prefer not to pull in extra deps for something so simple.

**Comment by jackc** [comment]
It would still be one underlying writer with the lineprefix library approach. Every connection would make a new io.Writer wrapping the original. I like the approach that library uses. A prefix function instead a prefix string allows more flexibility such as timestamping the lines.

Personally, I think that using a library like https://github.com/abiosoft/lineprefix is good enough. But if you (or anyone else) wants to make a PR that adds a `PrefixFunc` to `TracerOptions` I'd accept the feature.
