### ISSUE TITLE
Is there any way to set MaxIdleConns?

### ISSUE THREAD

**Issue by mroobert** [jackc/pgx#1376]
Is there any way to limit the max idle conns? I can see that `pool.Config().MaxConns` and `pool.Config().MaxConnIdleTime` are available but something like `pool.Config().MaxIdleConns` not.

**Comment by jackc** [comment]
There is not, but I think you should be able to get similar behavior with a combination of `MinConns` and `MaxConnIdleTime`. That should be able to ensure there are always at least N conns in the pool but ensure that idle conns are closed after a while.
