### ISSUE TITLE
Error sanitizing unicode replacement character when `PreferSimpleProtocol` is set to `true`

### ISSUE THREAD

**Issue by jamescmartinez** [jackc/pgx#1380]
**Describe the bug**
`pgx` fails to parse a query string with a unicode replacement character (�) when `PreferSimpleProtocol` is set to `true`.

**To Reproduce**
1. Run a query with a where statement, like `SELECT * FROM table WHERE name = 'hello w�rld'`

Note that I added additional details in the context section below.

**Expected behavior**
The string is parsed correctly, and the query executes as expected.

**Actual behavior**
An error is returned. `*pgconn.PgError: ERROR: unterminated quoted string at or near "'hello w�" (SQLSTATE 42601)`

**Version**
 - Go: `1.19.2`
 - PostgreSQL: `14.5`
 - pgx: `4.17.2`

**Additional context**
Look at the results of `sanitizeForSimpleQuery` and note that the sanitized string from the above example is `SELECT * FROM table WHERE name = 'hello w`

**Comment by jackc** [comment]
Fixed in 3edc1b5b (and ba4bbf92 on v5).

It turns out that when `DecodeRuneInString()` returns `utf8.RuneError` it doesn't actually mean there is an error 🤦 .

**Comment by jamescmartinez** [comment]
Amazing, thanks @jackc!
