### ISSUE TITLE
TraceLog doesn't implement PrepareTracer interface

### ISSUE THREAD

**Issue by mcdoker18** [jackc/pgx#1383]
**Is your feature request related to a problem? Please describe.**
The `tracelog.TraceLog` doesn't implement the `pgx.PrepareTracer` interface. So there are not prepare logs when using tracelog package.

**Describe the solution you'd like**
The `tracelog.TraceLog` implements the `pgx.PrepareTracer` interface.

**Describe alternatives you've considered**

**Additional context**

I have a PR that fixed this problem. If you confirm this issue then I can send it.

**Comment by jackc** [comment]
> I have a PR that fixed this problem. If you confirm this issue then I can send it.

Sure. 👍
