### ISSUE TITLE
Interface to avoid Prepare in CopyFrom

### ISSUE THREAD

**Issue by cevian** [jackc/pgx#1387]
**Is your feature request related to a problem? Please describe.**
Right now CopyFrom requires a [Prepare](https://github.com/jackc/pgx/blob/master/copy_from.go#L108) and as far as I could tell this is just used to get type information.

**Describe the solution you'd like**
I think the default CopyFrom interface should stay as-is but I would like an alternative "Power User" API that allows me to avoid the Prepare on every call to CopyFrom. Using a cache would work as well. 
 
I am happy to submit a PR if I can get some guidance on how you would like me to implement this.

**Comment by cevian** [comment]
Oh I missed that this is a duplicate of https://github.com/jackc/pgx/pull/1085, closing.

**Comment by alejandrodnm** [comment]
This will be solved in #1387 by passing either `QueryExecModeExec` or `QueryExecModeSimpleProtocol` as the last argument of `CopyFrom`. Instead of doing the prepare statement it will use the type map between golang and postgresql data types.
