### ISSUE TITLE
Public methods in Connection struct returning statement and description cache (as in v4 version)

### ISSUE THREAD

**Issue by iClaus21** [jackc/pgx#1389]
Hi!

In the previous PGX version "v4" I faced the problem
`ERROR: cache lookup failed for type 24572 (SQLSTATE XX000)`

In "v4" version we solved this problem via calling `Clear()` method for connection statement cache
`tx.Conn().StatementCache().Clear(context.Background())`

Today I have faced the same problem in the service which use "v5" version of PGX. 
I want to use the same method for statement or description cache, but found out that public method `StatementCache()` was removed from `Conn` structure.

I want to add 2 new public methods `StatementCache()` and `DescriptionCache()` returning `Conn.statementCache` and `Conn.descriptionCache` accordingly. And then call `InvalidateAll()` method for caches.

I see that you add `Conn.DeallocateAll()` method to the connection structure, but it makes a `deallocate all` call to the database. I don't want to make an extra call to the database because I use `cache_describe` query mode (pgbouncer) and don't have prepared statements in database.

**Comment by jackc** [comment]
>  I don't want to make an extra call to the database

How often does this situation occur? If it happens enough that the extra call to the database for `DeallocateAll()` has a meaningful performance impact then you would probably get better performance by not using statement caching at all (i.e. use the simple protocol instead).

I suppose we could expose the statement cache again if there is no other way, but I was trying to reduce the public API surface area.

If it does have a measurable performance impact another option would be for `DeallocateAll()` to be smarter and not send the `DEALLOCATE ALL;` to the server if there are no explicitly prepared or cached statements. It could just clear the describe cache.

**Comment by iClaus21** [comment]
Hi Jack,
Sure, this situation not so often occurs.
So I think it will be better for us to use `DeallocateAll()` instead of extending the public API.
