### ISSUE TITLE
Is pgx through the standard Go database/sql interface safe for concurrent use?

### ISSUE THREAD

**Issue by StarpTech** [jackc/pgx#1392]
Hello, when using [Getting-started-with-pgx-through-database-sql](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql) is the database connection safe for concurrent use? I want to use [SQLBoiler](https://github.com/volatiletech/sqlboiler) with pgx in a go HTTP handler. SQLBoiler requires db.SQL.

Thanks.

**Comment by jackc** [comment]
Yes. database/sql provides a concurrency safe connection pool.

**Comment by StarpTech** [comment]
Thank you.
