### ISSUE TITLE
How to parse result to JSON?

### ISSUE THREAD

**Issue by MohammadArik** [jackc/pgx#1395]
A query I make receives 38 columns of data. I want to organize the result in a JSON object. How to do that?

**Comment by jackc** [comment]
In Go , you could scan it into a struct with 38 fields and use the normal json package Marshal functionality.

In PostgreSQL, you could use `row_to_json`, `json_build_object` or other functions to build the json document.

**Comment by MohammadArik** [comment]
@jackc can you show some code?

**Comment by MohammadArik** [comment]
Ok thanks...
