### ISSUE TITLE
`RowToStructByName` issues with nested structs and optional result columns

### ISSUE THREAD

**Issue by danicc097** [jackc/pgx#1396]
**Describe the bug**

Up until now I've been successfully scanning structs and slices of structs for conditional joins via `json` tags with `row_to_json` and `json_agg`. I wanted to give the new `RowToStructByName` a try to have proper camel cased JSON for my responses and not depend on column names.

However, right now it doesn't seem possible to scan a selected record
```go
type UserAPIKey struct {
	UserAPIKeyID int       `json:"user_api_key_id" db:"user_api_key_id"` 
	APIKey       string    `json:"api_key" db:"api_key"`               
	ExpiresOn    time.Time `json:"expires_on" db:"expires_on"`         
	UserID       uuid.UUID `json:"user_id" db:"user_id"`               

	User *User `json:"user" db:"user"` 
}

type User struct {
	UserID     uuid.UUID  `json:"user_id" db:"user_id"`      
	Username   string     `json:"username" db:"username"`              

	OtherPossibleJoinTable *OtherPossibleJoinTable `json:"other_possible_join_table" db:"other_possible_join_table"` 
}
```
```sql
SELECT user_api_keys.user_api_key_id,
user_api_keys.api_key,
user_api_keys.expires_on,
user_api_keys.user_id,
(case when $1::boolean = true then users.* end) as user
FROM public.user_api_keys
left join users on users.user_id = user_api_keys.user_id 
WHERE user_api_keys.api_key = $2
```

`pgx.CollectRows(rows, pgx.RowToStructByName[UserAPIKey])` leads to an error scanning the resulting `user` select record tuple: `(4153bf46-d88f-4809-98a7-ea17065d2fa,user_1,...`
getting: `can't scan into dest[4]: cannot scan unknown type (OID 3119015) in text format into **db.User` coming from:

https://github.com/jackc/pgx/blob/8ad1394f4c8aa044ddcade4064d421ee3688f7fc/rows.go#LL259C8-L259C8

Apart from that, regarding the `db` tag, even if the above would work, `RowToStructByName` attempts to scan all fields regardless if they're present or not. In this user join, the `other_possible_join_table` result column is inexistent so it would yield `cannot find field other_possible_join_table in returned row` when scanning `UserAPIKey`'s `User`.
On the other hand, if we were to use `row_to_json(users.*)`, `User` scans correctly with `Scan` and `OtherPossibleJoinTable ` is `nil`

**Expected behavior**
Nested structs are scanned and zero value is used for inexistent selects, mimicking JSON support

**Version**
 - Go: go version go1.19.1 linux/amd64
 - PostgreSQL: PostgreSQL 13.7 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
 - pgx: v5.1.1

**Additional context**

**Comment by hiendaovinh** [comment]
Bump for visibility.

**Comment by george-steel** [comment]
I'm wondering if this was meant to be a check that all coulmns are assigned fields to scan into (which is not checked, but is by sqlx) instead of a check that all struct fields are assigned to (what is actually checked here, but not by sqlx).

**Comment by jackc** [comment]
The new `pgx.RowToStructByNameLax` on master might be closer to what you want.

**Comment by danicc097** [comment]
@jackc I believe I found some issue with JSON support in ``RowToStructByNameLax``, please see #1565. Apart from that it seems to solve this so I'll tentatively close it
