### ISSUE TITLE
Error handling doesn't work

### ISSUE THREAD

**Issue by mileusna** [jackc/pgx#1397]
**Describe the bug**
I don't know am I doing something wrong, but I can't get *pgconn.PgError from err returned from query using errors.As()

Below is basically the example from pgx documentation on error handling wrapped into main(). 

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/jackc/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

func main() {
	pool, err := pgxpool.New(context.Background(), fmt.Sprintf("user=%s password=%s host=%s port=%d dbname=%s", "user", "pass", "127.0.0.1", 5432, "db"))
	if err != nil {
		log.Fatal(err)
	}

	var greeting string
	err = pool.QueryRow(context.Background(), "select 1 +").Scan(&greeting)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) {
			fmt.Println(pgErr.Message) // => syntax error at end of input
			fmt.Println(pgErr.Code)    // => 42601
		} else {
			log.Println("Not PgError")
		}
	}
}
```

**Expected behavior**
It should detect PgError and print error message and code.

**Actual behavior**
The program outputs "Not PgError"

**Version**
 - Go: go version go1.19.3 darwin/arm64
 - PostgreSQL: PostgreSQL 15.1 (Homebrew) on aarch64-apple-darwin21.6.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit
 - pgx: github.com/jackc/pgx/v5 v5.0.4

**Additional context**
I got the same output using pgx.Connect instead of pgxpool.New, but I use pgxpool in example since I used that in my application when I bumped into this problem.

**Comment by jackc** [comment]
Your imports are mixing v4 and v5. Change `"github.com/jackc/pgconn"` to `"github.com/jackc/pgx/v5/pgconn"` and it will work.
