### ISSUE TITLE
Connections are slow on databases with a large number of tables

### ISSUE THREAD

**Issue by j16r** [jackc/pgx#140]
Hi there!

I'm using both pgx version 2.5.0 and master (master seems to be getting stuck and I don't have any idea why yet), and I'm having a problem using it against my particular database. When pgx first connects, it appears to do this query:

    select t.oid, t.typname from pg_type t where t.typtype='b'

Problem is that on my database, there are 249811 types. Tables seem to be included in this list of types, so each connection takes around 5s to finish this query.

There doesn't appear to be a good property on the table to distinguish tables from the normal types you'd want to do conversions from, so for now I've just set this to only get up to `3927 _int8range`. Any thoughts on how to reduce the number of types reduced here in a sensible / portable way?

Also each connection in a pool needs to do this query, is it possible perhaps to share the list of types at the pool level to avoid having to repeat this? I could write a pull request for this if it'd be acceptable.

Anyway, thanks for your hard work.

**Comment by jackc** [comment]
Wow! That's a lot of types. So your database has a lot of tables? If you don't mind my asking what's the domain?

As far as a solution, your suggestion of sharing the type map between connections in a pool would probably work.

However, another solution might be to make loading the type map lazy. `Prepare()` could be altered to look at the oids of parameters and column responses and lazily look them up. That would also solve the initial 5s connection time. As an added bonus, types added at run time would become visible. On the down side, this would be a slight behavior change in that the public Conn.PgTypes variable would not contain all the types on the server.

**Comment by j16r** [comment]
Perhaps an API like:

    fn (c *Conn) PgType(oid Oid) PgType // Lazily fetch the specified oid
    fn (c *Conn) PgTypes() ([]PgType, error) // Fetch the whole set of types... beware!

Would be better - but this would be a breaking change to the API :/

**Comment by jackc** [comment]
I like it, though the first function would also need to return an error.

I had to look back in the git log to see why Conn.PgTypes is even public at all. It's so users or extensions can set the default transit format for types to text or binary. Can't really change this now that it would be a breaking change. :(

Something like the hack you mentioned in your first post of only fetching low OIDs might actually be a good solution. We could have a field in ConnConfig that somehow limits the types that are fetched. If the field is blank we preserve existing behavior. Possibly a max OID, max number of records, or list of type names.

Wait a second, I think I might have another solution. The query `select t.oid, t.typname from pg_type t where t.typtype='b'` actually does filter table types. It is the automatically created table array types that are getting included. If we changed the loadPgTypes query to filter array types that we are already filtering the base type, that should solve issue.

```sql
select t.oid, t.typname
from pg_type t
  left join pg_type base_type on t.typelem=base_type.oid
where t.typtype='b'
  and (base_type.oid is null or base_type.typtype='b')
;
```

What do you think?
