### ISSUE TITLE
DropReplicationSlot hung

### ISSUE THREAD

**Issue by zhanghaiyang9999** [jackc/pgx#1401]
Hi, when execting the function DropReplicationSlot, it hungs at  err := conn.Exec(ctx, sql).ReadAll()

func DropReplicationSlot(ctx context.Context, conn *pgconn.PgConn, slotName string, options DropReplicationSlotOptions) error {
	var waitString string
	if options.Wait {
		waitString = "WAIT"
	}
	sql := fmt.Sprintf("DROP_REPLICATION_SLOT %s %s", slotName, waitString)
	**_, err := conn.Exec(ctx, sql).ReadAll()**
	return err
}

**Comment by bfontaine** [comment]
Could you share a small program that replicates the issue?

**Comment by bfontaine** [comment]
I’m closing this as not reproducible; please reopen once you have a small program that anybody can run to reproduce the bug.
