### ISSUE TITLE
cannot convert -infinity to Timestamptz

### ISSUE THREAD

**Issue by tuxaanand** [jackc/pgx#1404]
I'm using https://pkg.go.dev/github.com/jackc/pgx#Conn.CopyFrom to copy data from pgx.Rows retrieved from a query into a target table.

When I tried copying into a table with a `timestamp with time zone default '-infinity'::timestamp with time zone` column, it fails with the message `cannot convert -infinity to Timestamptz`.

```go
query := fmt.Sprintf(CopyOutTableData, strings.Join(columns, ","), schema, table, strings.Join(keyColumns, ","), offset, limit)
			dataRows, err := sourceConn.Query(query)
			if err != nil {
				log.Fatalf("error - %s", err.Error())
				resChan <- Response{CopyErr: err}
				return
			}
			log.Println("Start Copying chunk", offset)
			_, err = targetConn.CopyFrom(pgx.Identifier{schema, table}, columns, dataRows)
			if err != nil {
				log.Fatalf("error - %s", err.Error())
				resChan <- Response{CopyErr: err}
				return
			}
```

Is there any way around this?

Thank you

**Comment by jackc** [comment]
Can you provide a reproducible example someone else can run?

**Comment by bfontaine** [comment]
I’m closing this as not reproducible; please reopen once you have a small program that anybody can run to reproduce the bug.
