### ISSUE TITLE
Getting error "number of field descriptions must equal number of destinations"

### ISSUE THREAD

**Issue by rishavs** [jackc/pgx#1406]
**Describe the bug**
I am using the row.Scan function to scan by query result into a slice of structs. However, the Scan function keeps throwing the error 
`number of field descriptions must equal number of destinations, got 3 and 1` 

**To Reproduce**

This is my query function;
```go
func Get_data_for_all_posts() ([]models.Post, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	rows, _ := conn.Query(ctx, "select * from posts limit 10")
	posts, err := pgx.CollectRows(rows, func(row pgx.CollectableRow) (models.Post, error) {
		var post models.Post
		err := row.Scan(post)
		return post, err
	})

	return posts, err
}

```
which refers to my model defined as such;
```go
package models

type Post struct {
	Id          int
	Title       string
	Description string
}
```
and the table was defined as such;
```sql
create table posts (
  id serial primary key,
title text not null,
  description text not null
)
```
The number of fields in both my model and my table are the same and I am not sure why I am getting this error.
I am very new to golang and pgx and I am sure there is some mistake on my part rather than a bug in pgx, but I am not able to find where it is

**Expected behavior**
The query should return correct data

**Actual behavior**
Getting Error `number of field descriptions must equal number of destinations, got 3 and 1`

**Version**
 - Go: go1.19.3
 - PostgreSQL: PostgreSQL 11.5 (Ubuntu 11.5-3.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit
 - pgx: v5.1.1
**Additional context**

**Comment by bfontaine** [comment]
Maybe try with `select id, title, description` instead of `select *`?

**Comment by rishavs** [comment]
@bfontaine , that was my first thought as well. Unfortunately, that still gives me the same error.

**Comment by bfontaine** [comment]
When reading your code I see that you use `row.Scan(post)` instead of `row.Scan(&post)`. That’s probably related to your bug.

**Comment by rishavs** [comment]
Thanks, I tried that but I am still having the error. My code is here, https://github.com/StudioMockingbird/freya
Its a small web app skeleton. Maybe you can see what I am doing wrong in my code

**Comment by acim** [comment]
https://github.com/jackc/pgx/blob/24c53259f8814110863f406de86e24af709d4ef0/rows.go#L490

Also take a look at rows_test.go

**Comment by jackc** [comment]
Your query is returning 3 columns so you need to pass `Scan` 3 arguments. e.g. `row.Scan(&post.Id, &post.Title, &post.Description)`.

But see `RowToStructByPos` as @acim mentioned if you want a simpler approach.

**Comment by rishavs** [comment]
Thank you. That fixed it for me. I wonder if the example in the doc should be changed from a number to a struct so that others don't get confused with this.

**Comment by acim** [comment]
I guess we should all contribute to this project, including writing documentation.
