### ISSUE TITLE
Support DEFAULT special value in INSERTS

### ISSUE THREAD

**Issue by DerGut** [jackc/pgx#1421]
**Is your feature request related to a problem? Please describe.**
I would like to run an INSERT where I specify `DEFAULT` to trigger Postgres to use the default value of a column. Something like:
```sql
CREATE TABLE table (
  id text NOT NULL,
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

INSERT INTO table (id, timestamp) VALUES ('test', DEFAULT);
```

I want to run a query to insert multiple rows where some do and some don't have a value set. All `VALUES` need to have the same length, so I need a way to fill that gap. From what I have learnt, using the special word `DEFAULT` is a way to fill this gap.

*You get `ERROR: VALUES lists must all be the same length (SQLSTATE 42601)` otherwise

However, if I hand over a string `"DEFAULT"` with the arguments to `Exec` like
```go
query := "INSERT INTO table (id, timestamp) VALUES ($1, $2)"
tx, err := conn.Exec(query, "test", "DEFAULT")
```
it will be serialized to `"DEFAULT"` instead of the special value `DEFAULT`.

**Describe the solution you'd like**
I don't think `pgtype` provides this special value (correct me if I'm wrong). I would probably define one for this and then use that instead. À la
```
tx, err := conn.Exec(query, "test", pgtype.DefaultValue)
```
This would then need to be added to https://github.com/jackc/pgx/blob/v4.17.2/messages.go or it would need to be a var of a type which defines the Valuer functions.

**Describe alternatives you've considered**
There is probably a workaround for using `DEFAULT`. But I feel like this is something that should be added if it isn't there already.

~~**Additional context**~~

**Comment by jackc** [comment]
AFAIK, this is impossible at the PostgreSQL protocol level. There is no way to specify `DEFAULT` as a parameter, it must be part of the SQL text.

```
jack@[local:/private/tmp]:5432 mydb=# prepare s as insert into events (id) values ($1);
PREPARE
jack@[local:/private/tmp]:5432 mydb=# execute s (default);
ERROR:  42601: DEFAULT is not allowed in this context
LINE 1: execute s (default);
                   ^
```

The only way this could possibly work would be for pgx to rewrite the query when it detected that special parameter value. But it wouldn't just need to rewrite the `$N` to `DEFAULT`, it would also need to renumber all other parameter placeholders. This would not be practical.

**Comment by DerGut** [comment]
Oh, I didn't realize this. Thanks for the additional info!
