### ISSUE TITLE
Implementing sql commenter plugin for pgx v5

### ISSUE THREAD

**Issue by kostyay** [jackc/pgx#1423]
Hey all
I would like to implement the [sqlcommenter](https://google.github.io/sqlcommenter/spec/) support for pgx v5.
Sqlcommenter is basically a post processor that adds some comments to queries that later can be identified by the server to tag queries with some extra metadata.

Example:
`select 1`
-> Enriched from context:
`select 1 /*tracespan=xxxxx,route=xxx,action=yyy*/`

There is already an implementation that works with `database/sql` library, but I want to add it for native pgx.
What is the right hook for me if I want to run some code right before the sql is sent to the server?
I see there is `QueryRewriter`  interface.. can that work?

Thanks in advance.

**Comment by jackc** [comment]
`QueryRewriter` works on a per query basis. No way to rewrite all queries automatically.

TBH, I don't think there is a way to easily do this with pgx. I think it could be done by building wrappers around all the pgx types, but that would be quite a bit of work.

But regardless of how it could be done, this would have significant negative performance implications. By default pgx automatically prepares and caches statements. Changing the SQL text for each query would make prepared statements and caching counter productive. You'd have to disable caching.

---

If you are looking for more detailed logging or instrumentation I recommend looking at `QueryTracer` instead.

**Comment by kostyay** [comment]
Is it possible to hook pgx after the cache is loaded just before its sent to the server?

**Comment by jackc** [comment]
No. When using prepared statements the SQL text isn't sent to the server -- only the prepared statement name.

**Comment by jackc** [comment]
@tcolgate I don't think this is showing what that message implies. If I understand correctly, what is really happening is you don't have to actually use all the arguments to a prepared statement.

Yes, this works:

```sql
PREPARE test_prepared (text, integer) AS /*$1*/ SELECT $2;
```

But so does this:

```sql
PREPARE test_prepared (text, integer) AS SELECT $2;
```

The comment is irrelevant.

Now perhaps a system could be devised that always added an unused prepared statement argument that could include tracing info and perhaps some sort of middleware could inspect that but I think such a system would involve a non-trivial change.

**Comment by tcolgate** [comment]
@jackc the pg_tracing dev implies that 
```
PREPARE test_prepared (text, integer) AS /*$1*/ SELECT $2;
EXECUTE test_prepared('dddbs=''postgres.db'',traceparent=''00-00000000000000000000000000000009-0000000000000009-01''',
1);
```
is actually expanding the comment in the EXECUTE rather than stripping it out when parsing the PREPARE .

testing against pg locally...

```
postgres=# PREPARE q(text,text) AS /*$1*/ select pg_sleep(5),$2;
postgres=# select * from pg_prepared_statements;
 name |                    statement                    |         prepare_time          | parameter_types |  resu
lt_types  | from_sql | generic_plans | custom_plans 
------+-------------------------------------------------+-------------------------------+-----------------+------
----------+----------+---------------+--------------
 q    | PREPARE q(text) AS /*$1*/ select pg_sleep(5),$2; | 2024-01-15 16:29:50.249425+00 | {text}          | {void
,integer} | t        |             0 |            3
(1 row)
```
suggests that the comment is preserved in the prepared statement (on pg 16 at least).

That said, if I execute it and check the slow query log...

```
Jan 15 16:47:08 malbec postgres[61736]: 2024-01-15 16:47:08.290 GMT [61736] LOG:  duration: 5004.922 ms  statement: EXECUTE q('hello','world');
Jan 15 16:47:08 malbec postgres[61736]: 2024-01-15 16:47:08.290 GMT [61736] DETAIL:  prepare: PREPARE q(text) AS /*$1*/ select pg_sleep(5),$2;
```
which really doesn't imply one way or another, but doesn't rule out the expansion. 

In the case of proposed `pg_tracing` extension, if he dev wasn't mistaken, then it looks like passing a dynamic comment in this way (which can contain the traceparent), would be compatible with the prepared statement cache.

In the case of google cloud sql (the case I'm attempting to work with), I've not actually managed to get their supposed traceparent comment magic working at all, regardless of prepared statements. This is the whole point of sqlcommenter, so I can only assume I'm doing something wrong, or google didn't actually implement what they wrote up (increasingly less impossible that it seems).

**Comment by tcolgate** [comment]
By way of further investigate:
- There an extra button to click in the UI to support query tags
- Their traceparent tag works on regular queries, but doesn't seem to work on prepared and exec'd statements (regardless of whether it's put in the prepare or exececute statement)

As such, even if I could get a sqlcommenter equivalent working, I don't think it would work for cloudsql without disabling prepared statements anyway.

**Comment by kostyay** [comment]
@tcolgate Did you end up getting this to work?
We were are using sqlcommenter with PGX which doesn't use prepared statements and its really useful.
Would love to have it work with PGX

**Comment by StevenACoffman** [comment]
See https://github.com/google/sqlcommenter/issues/245
