### ISSUE TITLE
Potential password leak in console when parsing url/dsn string

### ISSUE THREAD

**Issue by punitarani** [jackc/pgx#1428]
`ParseConfigWithOptions` and functions that implement `parseConfigError` can print the password to the console if the child functions raise an error.
While this can help with debugging, I think it can be problematic if the goal is to keep the password hidden and secure.

Example output:
`failed to connect database cannot parse 'postgresql://user:xxxxxx@host:port/db': failed to parse as URL (parse "postgresql://user:PASSWORD@host:port/db": net/url: invalid userinfo)`

**Comment by bfontaine** [comment]
See also #1271.
