### ISSUE TITLE
v5 Migration Guide

### ISSUE THREAD

**Issue by bradleygore** [jackc/pgx#1429]
First, thanks for this suite of tools and giving of your time/knowledge :)

I'm kind of struggling to upgrade to v5, and it may just be due to how we're using pgx. My setup is that I use `pgx/stdlib` for the driver, and then use `sqlx` on top for doing things like named parameter queries, binding back to structs, etc... I see that v5 has some (maybe all?) of that functionality now, but it would be pretty heavy for me to switch totally over. So, that kind of is what it is.

With v4, we only had to implement `driver.Scanner | Valuer` interfaces to override how custom types transform from/to the db. Now, it seems quite a bit more complex and I'm really hoping that I'm missing something that makes it less so.

The v4 mechanism allowed something like this:

```go
// ID is a custom type that corresponds to the foo_id custom type in postgres.
type ID string

// IDs is a slice of ID
type IDs []ID

// Scan implements sql.Scanner
func (ids *IDs) Scan(src interface{}) error {
	pgArr := pgtype.TextArray{}
	if err := pgArr.Scan(src); err != nil {
		return err
	}
	*ids = []ID{}
	for _, id := range pgArr.Elements {
		*ids = append(*ids, ID(id.String))
	}
	return nil
}

// Value implements valuer for db/sql
func (ids IDs) Value() (driver.Value, error) {
	pgArr := pgtype.TextArray{}
	if err := pgArr.Set(ids); err != nil {
		return nil, err
	}
	return pgArr.Value()
}
```

Here's how I am trying it in v5 (just showing the Scan/Value funcs for brevity):

```go
// Scan implements sql.Scanner.
func (ids *IDs) Scan(src interface{}) error {
	var srcStr string
	switch v := src.(type) {
	case string:
		srcStr = v
	default:
		return errs.NewInternal(fmt.Sprintf("IDs unable to Scan from %T", v))
	}
	pgArr := pgtype.FlatArray[string]{}
	m := pgtype.NewMap()
	if err := m.SQLScanner(&pgArr).Scan(srcStr); err != nil {
		return err
	}
	*ids = []ID{}
	for _, id := range pgArr {
		*ids = append(*ids, ID(id))
	}
	return nil
}

// Value implements valuer for db/sql
func (ids IDs) Value() (driver.Value, error) {
	pgArr := pgtype.FlatArray[string](utils.Map(ids, func(id ID) string { return string(id) }))
	return pgArr, nil
}
```

This data type maps to a custom type in postgres, so the driver isn't aware of its `OID`. So I get this error:
```
failed to encode args[4]: unable to encode currency.IDs{"USD"} into text format for unknown type (OID 20474): unable to encode []string{"USD"} into text format for unknown type (OID 20474): cannot find encode plan
```

However, if a type implements custom scan/value funcs, why does the driver need `OID` information? Apologies if that's a dumb question - this project is working at a much lower level than I normally work, so I'm learning a lot (and not understanding a lot) along the way 😄 

Is there some migration guide that explains how these work that doesn't involve mapping `OID` and writing a whole custom `Codec` and all that, or is that the only way?

**Comment by bradleygore** [comment]
Interesting note: If I write a test that just uses `TEXT[]` column and go fields of this `IDs` type, then the v5-specific mechanism shown above works. It's only when it's running against column of the custom type.

**Comment by bradleygore** [comment]
I just tried this, and it worked:

```
dbConn.Raw(func(driverConn any) error {
	stdLibConn, ok := driverConn.(*pgx.Conn)
	cTyps := []string{
		"currency_id",
		"currency_id[]",
	}
	pxConn := stdLibConn.Conn()
	for _, ct := range cTyps {
		cTyp, err := pxConn.LoadType(context.Background(), ct)
		pxConn.TypeMap().RegisterType(cTyp)
	}
	return nil
})
```

So, I think I just need to register _all_ of the custom types we define. That said, do I still need to implement the `Scan | Value` funcs as shown above, or am I doing this incorrectly?

**Comment by jackc** [comment]
> However, if a type implements custom scan/value funcs, why does the driver need OID information? Apologies if that's a dumb question - this project is working at a much lower level than I normally work, so I'm learning a lot (and not understanding a lot) along the way 😄

It's not `Scan()` and `Value()` that requires it to have the types registered. It's the use of `pgtype.FlatArray[T]` and `Map.SQLScanner()` inside of them. If the `Scan()` and `Value()` functions parsed and produced strings without them it would work fine. 

> So, I think I just need to register all of the custom types we define.

It may not be *strictly* necessary, but it's usually a good idea with pgx.

> do I still need to implement the Scan | Value funcs as shown above

The preferred approach is to register types and then pass slices directly. No `Value()` method is needed for arguments. e.g.

```go
var n int64
err := db.QueryRow("select cardinality($1::text[])", []string{"a", "b", "c"}).Scan(&n)
```

For scanning, the preferred approach is to use the `Map.SQLScanner()` method. e.g.

```go
var a []int64
err := db.QueryRow("select '{1,2,3}'::bigint[]").Scan(m.SQLScanner(&a))
```

However, since you are using sqlx you probably do need to make your named type that implements `Scan()` and possibly `Value()`.

**Comment by bradleygore** [comment]
Ok, I'll continue on with `Scan|Value`. Thanks for taking the time to walk through that 😄

**Comment by bradleygore** [comment]
So, I've encountered an interesting situation. It seems that the custom OID mapping gets lost somehow at random times.

I have a test suite for directly testing db-held code (triggers, functions, complex constraints, etc...). This is in `db/tests` directory. I have one singular place, for all tests in the entire suite, where the connection gets created and it looks like this (using Ginkgo test setup):

```go
var _ = BeforeSuite(func() {
	defer GinkgoRecover()

	var err error
	if apiConfig, err = config.Get(); err != nil {
		fmt.Println("Error retrieving apiConfig ", err)
		return
	}

	conn := testutils.EnsureTestDBConnectionString(apiConfig.Postgres)
	fmt.Println("CONNECTING TO " + conn)
	db, err = sqlx.Connect("pgx", conn)
	if err != nil {
		fmt.Println("Error connecting to DB ", err)
		db = nil
		return
	}
	// register custom types with driver per https://github.com/jackc/pgx/issues/1429
	repos.MustRegisterCustomPgTypes(db)
	testutils.CleanMainDatabaseTables(db)
})
```

And here's the func to register the custom types with the driver (we have a lot, so truncated the type name strings for brevity):

```
func MustRegisterCustomPgTypes(db *sqlx.DB) {
	dbConn, err := db.Conn(context.Background())
	if err != nil {
		logger.Crit("error opening a connection to the db", "err", err)
		panic(err)
	}
	defer dbConn.Close()
	_ = dbConn.Raw(func(driverConn any) error {
		stdLibConn, ok := driverConn.(*pgx.Conn)
		if !ok {
			panic("repos expected driver connection to be of type *pgx.Conn")
		}
		// This is absolutely required for pgx v5 to work.
		// I found this in an issue: https://github.com/jackc/pgx/issues/1338#issuecomment-1289767790
		// and while it links to the docs at https://pkg.go.dev/github.com/jackc/pgx/v5@v5.0.3/pgtype#hdr-Enum_Support
		// I did not find it obvious from said docs that this was required.
		// See also https://github.com/jackc/pgx/issues/1429 that I opened.
		cTyps := []string{
			"auth_request_outcome",
			"auth_request_status",
			...
		}
		pxConn := stdLibConn.Conn()
		for _, ct := range cTyps {
			cTyp, err := pxConn.LoadType(context.Background(), ct)
			if err != nil {
				logger.Crit("Error loading a type", log15.Ctx{
					"type": ct,
					"err":  err,
				})
				panic(err)
			}
			pxConn.TypeMap().RegisterType(cTyp)
		}
		return nil
	})
}
```

And every test in this suite uses this one db session, and this custom type registration works fine. Except that every time I ran the full suite of tests, at some random point it would seemingly forget the custom types registered and would give the error about encoding into unknown OID `...into text format for unknown type (OID 24838): cannot find encode plan` However, if I execute the custom type registration in `BeforeEach` then I no longer see this issue happening at random times when running the entire suite.

Are there known times where it is necessary to register the custom types again, or am I doing something wrong with my setup?

**Comment by bradleygore** [comment]
I'm finding some issue around registering custom types. I actually posted a comment on this earlier, then deleted it as I thought I had made a mistake. Now, I'm pretty confident in what I'm seeing 😅 

First, let's start out with a custom type - enum named `currency_id`. It has its OID, and it is also used as array `currency_id[]` which that has its own OID. Here's what this looks like from the db:

![Screen Shot 2022-12-21 at 12 43 32 PM](https://user-images.githubusercontent.com/5077928/208980101-4fff8014-b21f-411a-a655-784195248c58.png)

I am registering this, and all other, custom types in a `BeforeSuite` for a singular suite of tests that hit the db, and all test in the suite use a singular db session:

```go
var _ = BeforeSuite(func() {
	defer GinkgoRecover()

	var err error
	if apiConfig, err = config.Get(); err != nil {
		fmt.Println("Error retrieving apiConfig ", err)
		return
	}

	conn := testutils.EnsureTestDBConnectionString(apiConfig.Postgres)
	fmt.Println("CONNECTING TO " + conn)
	db, err = sqlx.Connect("pgx", conn)
	if err != nil {
		fmt.Println("Error connecting to DB ", err)
		db = nil
		return
	}
	repos.MustRegisterCustomPgTypes(db)
	testutils.CleanMainDatabaseTables(db)
	for _, bs := range beforeSuiteHooks {
		bs()
	}
})

// repos.MustRegisterCustomPgTypes (types truncated for brevity)
func MustRegisterCustomPgTypes(db *sqlx.DB) {
	dbConn, err := db.Conn(context.Background())
	if err != nil {
		logger.Crit("error opening a connection to the db", "err", err)
		panic(err)
	}
	defer dbConn.Close()
	_ = dbConn.Raw(func(driverConn any) error {
		stdLibConn, ok := driverConn.(*pgx.Conn)
		if !ok {
			panic("repos expected driver connection to be of type *pgx.Conn")
		}
		// This is absolutely required for pgx v5 to work.
		// I found this in an issue: https://github.com/jackc/pgx/issues/1338#issuecomment-1289767790
		// and it links to the docs at https://pkg.go.dev/github.com/jackc/pgx/v5@v5.0.3/pgtype#hdr-Enum_Support
		// See also https://github.com/jackc/pgx/issues/1429 that I opened.
		cTyps := []string{
			"currency_id",
			"_currency_id", // array type of currency_id: SELECT * FROM pg_type WHERE typname ILIKE '%currency%';
			// ... truncated for brevity
		}
		pxConn := stdLibConn.Conn()
		for _, ct := range cTyps {
			cTyp, err := pxConn.LoadType(context.Background(), ct)
			if err != nil {
				logger.Crit("Error loading a type", log15.Ctx{
					"type": ct,
					"err":  err,
				})
				panic(err)
			}
			pxConn.TypeMap().RegisterType(cTyp)
		}
		return nil
	})
}
```

It looks like the custom OID mapping is getting lost somehow. If I run the entire suite, it will run a while and eventually I'll get the error stating it doesn't know how to handle an unrecognized OID (note, the OID it references is `20474` which is the OID for `_currency_id` which is registered):

```
failed to encode args[4]: unable to encode currency.IDs{\"USD\"} into text format for unknown type (OID 20474): unable to encode pgtype.FlatArray[string]{\"USD\"} into text format for unknown type (OID 20474): cannot find encode plan
```

However, if I make the tests such that `BeforeEach` test runs, it does `repos.MustRegisterCustomPgTypes(db)` then the entire suite passes.

This kind of concerns me - if my application is running for a long while, will there be some point where the mapping of custom OIDs gets lost? Or am I just setting all this up wrong?

**Comment by jackc** [comment]
> This kind of concerns me - if my application is running for a long while, will there be some point where the mapping of custom OIDs gets lost? Or am I just setting all this up wrong?

There's no guarantee that you tests are getting the same connection from the database/sql pool that you registered the types on.

I suggest using `stdlib.OpenDB` to establish your connection with a `stdlib.OptionAfterConnect` function that that does the type registration.

**Comment by bradleygore** [comment]
Oh ok - so the pool can't use a common registry? I'll try the `OptionAfterConnect` hook approach, that may do the trick. Sorry to have bombarded w/ so many questions, but really appreciate your taking the time to respond 😄

**Comment by jackc** [comment]
> Oh ok - so the pool can't use a common registry?

Correct. The type map caches what plan is used for what Go type + PG OID pair. Using a shared type map would require significant synchronization overhead.

**Comment by bradleygore** [comment]
@jackc - this is working with the `OptionAfterConnect` mechanism! Thanks again for all the handholding - much appreciated 😄 

In case any others are using sqlx, here's how I've got the wiring working:

```go
import(
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/jmoiron/sqlx"
)

pgxCfg, err := pgx.ParseConfig("connection string here")
if err != nil {
	panic(err)
}

sqldb := stdlib.OpenDB(*pgxCfg, stdlib.OptionAfterConnect(func(ctx context.Context, c *pgx.Conn) error {
	// register custom types with the connection
}))

sqlxdb := sqlx.NewDb(sqldb, "pgx")
```
