### ISSUE TITLE
v5 Encoding for types mapping to json fields ignores Scan/Value implementation

### ISSUE THREAD

**Issue by bradleygore** [jackc/pgx#1430]
I may be doing this in a less than ideal way... but I have a custom type that implements the following:
- `MarshalJSON` for how the structure should get sent to client (it's a read-only structure derived from other stuff)
- `Scan` for how the structure should get read in from the db data
- `Value` for how the structure should get put into the db (after being compiled in the application layer - so this output is different than the `MarshalJSON` output)

In v4 this type worked as desired. In v5 the type's `Value` func is not used but its `MarshalJSON` func is used when going into the db.

**To Reproduce**

*Note*: Not sure this will run exactly, but I think it will convey what's going on.

```go
package main

import (
	"context"
	"log"
	"os"
	"encoding/json"
	"github.com/jackc/pgx/v4"
	"database/sql/driver"
)

type CustomThing {
  json.RawMessage
}

func (t CustomThing) MarshalJSON() ([]byte, error) {
  fmt.Println("MarshalJSON called")
  return nil, nil
}

func (t CustomThing) Value() (driver.Value, error) {
  fmt.Println("Value called")
  return nil, nil
}

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

	err = conn.QueryRow(context.Background(), "select $1::jsonb", &CustomThing{RawMessage: json.RawMessage(`{}`)})
	// MarshalJSON called would get printed
}
```

**Expected behavior**
Some way to override the encoding so that we can control which mechanism is used to send to db vs to consumer.

**Version**
 - Go: `go version go1.18.8 darwin/arm64`
 - PostgreSQL: `PostgreSQL 12.8 (Debian 12.8-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`
 - pgx: `5.2.0`

**Comment by jackc** [comment]
I think this was fixed a few days ago in 279c3c0a20e0dbee3c4b644f58e5e3b3de8e051f. Try master and see if that resolves the issue.

**Comment by bradleygore** [comment]
Oh ok - I'll take a look at this next time I'm working on my v5 upgrade branch.

**Comment by mai00cmi** [comment]
279c3c0 seems to only fix the scanner but not the valuer.

**Comment by bradleygore** [comment]
@mai00cmi is correct. I've ran my test suite against master and the custom valuer func is not called, only the `MarshalJSON` func.

**Comment by jackc** [comment]
Should be fixed now in e66ad1bcecedaa3032a16f0f71b1878502f9cb8b.

**Comment by bradleygore** [comment]
Awesome - will try again soon on my v5 upgrade branch! Thanks!!

**Comment by a631807682** [comment]
@jackc This problem has been fixed for a long time, but the latest version does not seem to include it, are there plans to release a new version?

**Comment by jackc** [comment]
`v5.3.0` was released today.
