### ISSUE TITLE
`MaxConnLifetimeJitter` setting doesn't actually jitter

### ISSUE THREAD

**Issue by benweint** [jackc/pgx#1437]
We're seeing an issue wherein the `MaxConnLifetimeJitter` doesn't actually splay out DB reconnections as intended. Under high enough throughput, connections within the pool wind up being marked as expired at pretty much `MaxConnLifetime`, meaning that they all get closed and re-created in quick succession, which can have performance impacts for clients using the pool

## To reproduce

Run the following program, which sets both `MaxConnLifetime` and `MaxConnLifetimeJitter` to 10s, and issues queries every 10ms:

```go
package main

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"os"
	"time"
)

func main() {
	// urlExample := "postgres://username:password@localhost:5432/database_name"
	ctx := context.Background()

	cfg, err := pgxpool.ParseConfig(os.Getenv("DATABASE_URL"))
	if err != nil {
		panic(err)
	}

	cfg.MinConns = 5
	cfg.MaxConns = 5
	cfg.MaxConnLifetime = 10 * time.Second
	cfg.MaxConnLifetimeJitter = 10 * time.Second

	lastNewConn := time.Now()
	cfg.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
		elapsed := time.Since(lastNewConn)
		lastNewConn = time.Now()
		fmt.Printf("new conn after %v\n", elapsed)
		return nil
	}

	pool, err := pgxpool.NewWithConfig(context.Background(), cfg)
	if err != nil {
		panic(err)
	}
	defer pool.Close()

	ticker := time.NewTicker(10 * time.Millisecond)
	secondTicker := time.NewTicker(1 * time.Second)

	for {
		select {
		case <-ticker.C:
			runOnce(ctx, pool)
		case <-secondTicker.C:
			fmt.Printf("\n")
		}
	}
}

func runOnce(ctx context.Context, pool *pgxpool.Pool) {
	result, err := pool.Query(ctx, "SELECT 1")
	if err != nil {
		fmt.Printf("got error: %v\n", err)
		return
	}
	result.Close()
}
```

## Expected behavior

Given the description of `MaxConnLifetimeJitter`, I would expect the log lines noting the creation of new DB connections to be uniformly distributed over a 10s window.

## Actual behavior

Even after running for a long time, new connection creations remain tightly clustered together, for example:

```
new conn after 10.65846325s
new conn after 62.371459ms
new conn after 1.070083ms
new conn after 1.649ms
new conn after 2.122417ms
```

## Version

 - Go: `go version go1.19 darwin/arm64`
 - PostgreSQL: `PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`
 - pgx: `5.1.0`

## Notes 

I believe the issue here lies in the `isExpired` [method](https://github.com/jackc/pgx/blob/4fc4f9a60337af3bd7c6abdf6c71460712d112fc/pgxpool/pool.go#L366-L378). This method calculates a new value for `jitterSecs` every time it is invoked (which is on each release, so each time a query is issued). With a high enough rate of queries, the likelihood that it will pick a `jitterSecs` value near zero within a given span of time approaches 1, which results in the effective behavior being the same as if no jitter had been specified..

**Comment by jackc** [comment]
I believe you are correct. I can see two ways of correcting it.

1. `*connResource` could contain a `maxAgeTime time.Time` field which would be creation time + max conn lifetime + random jitter amount. `isExpired` would simply become a check for now() > maxAgeTime.
2. `*Pool` could have a "next jitter amount" atomic field. Every time a conn is closed because of max age it would be reset.

1 is probably best.

**Comment by benweint** [comment]
Yes, I think approach 1 sounds great! It has the added benefit of avoiding frequent calls to Rand.

**Comment by benweint** [comment]
Awesome, thank you!
