### ISSUE TITLE
pgx/v5 does not support scanning to/from Go arrays

### ISSUE THREAD

**Issue by eandre** [jackc/pgx#1442]
**Describe the bug**
We recently [migrated the Encore runtime's underlying database driver](https://github.com/encoredev/encore/pull/543) to pgx/v5 (from pgx/v4). After doing so we got bug reports from some of our users that pgx/v5 that were processing coordinates as `[3]float` and it seems that pgx/v5 doesn't handle scanning from/to Go arrays like this. This worked correctly in pgx/v4.

**To Reproduce**

With the following table:
```sql
create table pgx_test (val double precision[] not null);
insert into pgx_test values ('{1.2, 3.4, 5.6}');
```

Run the following:
```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(ctx)

	var arr [3]float64

	err = conn.QueryRow(ctx, "SELECT val FROM pgx_test LIMIT 1").Scan(&arr)
	if err != nil {
		log.Printf("SELECT failed: %v", err)
	} else {
		log.Println("SELECT successful")
	}

	arr = [3]float64{1.1, 2.2, 3.3}
	_, err = conn.Exec(ctx, "INSERT INTO pgx_test (val) VALUES($1)", arr)
	if err != nil {
		log.Printf("INSERT failed: %v", err)
	} else {
		log.Println("INSERT successful")
	}
}
```

**Expected behavior**
```bash
$ go run main.go
2022/12/19 12:19:08 SELECT successful
2022/12/19 12:19:08 INSERT successful
```

**Actual behavior**
```bash
$ go run main.go
2022/12/19 12:19:33 SELECT failed: can't scan into dest[0]: cannot scan _float8 (OID 1022) in binary format into *[3]float64
2022/12/19 12:19:33 INSERT failed: failed to encode args[0]: unable to encode [3]float64{1.1, 2.2, 3.3} into binary format for _float8 (OID 1022): cannot find encode plan
```

**Version**
 - Go: `$ go version` -> go version go1.19.2 darwin/arm64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` ->  PostgreSQL 14.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.2.0

**Additional context**

If you replace the import with `github.com/jackc/pgx/v4` then the code snippet works as expected.

**Comment by jackc** [comment]
Fix in f42af358847797376847ffa58d105d8373fbddaf.
