### ISSUE TITLE
Relation does not exist when executing  pgx.CopyFrom   even grant Full access to the a3 schema to a non-admin user.

### ISSUE THREAD

**Issue by cfeng-wm** [jackc/pgx#1447]
**Describe the bug**
Relation does not exist when executing  pgx.CopyFrom   even grant Full access to the a3 schema to a non-admin user, works for QueryRow, but not for CopyFrom

**To Reproduce**

If possible, please provide runnable example such as:

```go
package main

import (
	"context"
	"log"
	"os"
	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

count, cer := tx.CopyFrom(ctx, pgx.Identifier{"a3.user"}, []string{"id", "user_name", "status"}, &rowSrc)
	if cer != nil {
log.Fatalf("Error when tx.CopyFrom-->%s", cer.Error()) logged error as  Error when tx.CopyFrom-->ERROR: relation "a3.user" does not exist (SQLSTATE 42P01)
		tx.Rollback(ctx)
}
```

**Expected behavior**
data should insert into the a3.user table from csv file.

**Actual behavior**
Got relation "a3.user" does not exist (SQLSTATE 42P01)

**Version**
 - Go: `$ go version` -> go1.19.1 windows/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> "PostgreSQL 14.4 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 7.4.0, 64-bit", 
 - compiled by Windows 11 Pro, 64-bit]
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.2.0

**Additional context**
Verify connection string point to correct database and  manually grant access to the schema a3.

Thank you in advance.

**Comment by jackc** [comment]
Assuming `a3` is a schema then `pgx.Identifier{"a3.user"}` should be `pgx.Identifier{"a3", "user"}`.

**Comment by cfeng-wm** [comment]
Thank Jack,  this is not a bug, closing it.
