### ISSUE TITLE
Can't assign NULL to JSON Field

### ISSUE THREAD

**Issue by mankyd** [jackc/pgx#145]
Scanning across a JSON field that contains a null value causes the scan to abort.

I have a query that looks like the following:

```
    rows, err := service.db.Query(
        `SELECT id, name, answers, token
        FROM question_set
        ORDER BY id
        LIMIT $1 OFFSET $2`, limit+1, offset)
```

I try to scan over it using:

```
    var id *int64
    var name *string
    var token *string
    var answers *map[string]Answer
//...
        err = rows.Scan(&id, &name, &answers, &token)
```

Where `Answer` is a simple struct with two members.

The `answers` field is nullable. When my scan comes across such a field, it results in a fatal error and my scan stops.

**Comment by jackc** [comment]
I tried to reproduce this in https://github.com/jackc/pgx/commit/6fb0c7c00e03f89157aa827932194bbe0fc21873 but I was unable to get a failure.

Do you have a reproducible test case?
