### ISSUE TITLE
Checking if pgx.Rows are empty (without scanning)

### ISSUE THREAD

**Issue by kamikazechaser** [jackc/pgx#1460]
**Is your feature request related to a problem? Please describe.**

In some cases e.g. scrolling through ranges with the help of a cursor such as when looking for gaps in large sequences ,it should be possible to test whether pgx.Rows is empty without reading the potential rows into a struct.

It is somehow possible doing something like:

```go
    rowsProcessed := 0
    for rows.Next() {
	var n uint64
	if err := rows.Scan(&n); err != nil {
		return err
	}

        // some processing here

	rowsProcessed++
    }

    if rowsProcessed == 0 {
        // empty rows/no result
    }
```

**Describe the solution you'd like**

Would it be possible to have a neater solution?

**Describe alternatives you've considered**

See above

**Additional context**

Discussed previously in #465

**Comment by jackc** [comment]
You don't have to call `Scan` at all.

e.g. 

```go
rowsProcessed := 0
for rows.Next() {
	rowsProcessed++
}

if err := rows.Err(); err != nil {
	// handle err
}

if rowsProcessed == 0 {
		// empty rows/no result
}
```

---

You could also simply close the `Rows`, check `Err`, and then read the `RowsAffected` from the `CommandTag` if you want to accept the row count from PostgreSQL instead of counting yourself.

**Comment by kamikazechaser** [comment]
Thanks, I think that would work!
