### ISSUE TITLE
FATAL: unrecognized configuration parameter \"statement_cache_mode\" 

### ISSUE THREAD

**Issue by qinxin0720** [jackc/pgx#1463]
**Describe the bug**
connect to database error, database reply server error (FATAL: unrecognized configuration parameter \"statement_cache_mode\" (SQLSTATE 42704))"

**To Reproduce**

just update pgx from version v4.17.2 to version v5.2.0

**Expected behavior**
none.

**Actual behavior**
none.

**Version**
 - Go: `go version go1.19.4 darwin/amd64`
 - PostgreSQL: `PostgreSQL 15.1`
 - pgx: `'github.com/jackc/pgx/v5.2.0' go.mod`

**Additional context**
database connStr just like `postgres://%s:%s@%s/%s?statement_cache_mode=%s&sslmode=prefer&connect_timeout=%d`.

**Comment by jackc** [comment]
In v5 you will need to use `default_query_exec_mode` instead.
