### ISSUE TITLE
Comma-separated list of hostnames does not work if the IP of one of them cannot be resolved

### ISSUE THREAD

**Issue by nanomoomug** [jackc/pgx#1464]
**Describe the bug**
If a DNS string is passed to the pgx.Connect function of the form

`user=user password=password host=host1,host2 port=5432 dbname=dbname`

and the IP of host2 cannot be resolved, then the connection fails, even if host1 is correct.

**To Reproduce**

The following does not work if host1 is correct but host2 cannot be resolved:

```go
package main

import (
	"context"
	"log"

	"github.com/jackc/pgx/v5"
)

func main() {
	_, err := pgx.Connect(context.Background(),
		"user=user password=password host=host1,host2 port=5432 dbname=dbname")
	if err != nil {
		// We will reach this point, if host2 cannot be resolved to an IP, even if host1 is correct
		// and a connection could be established with it.
		log.Fatal(err)
	}
}
```

**Expected behavior**

The documentation (https://pkg.go.dev/github.com/jackc/pgx#ConnConfig) says:

```
// A comma-separated list of host names is also accepted,
// in which case each host name in the list is tried in order;
// an empty item in the list selects the default behavior as explained above.
// @see https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-MULTIPLE-HOSTS
```

As we understand it, this implies it should connect to host1.

**Actual behavior**

No connection is established and the following error is returned:

`hostname resolving error (lookup host2 on 127.0.0.1:53: no such host)`

**Version**
 - Go: go1.18 linux/amd64
 - PostgreSQL: PostgreSQL 11.11 (Debian 11.11-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
 - pgx: v5.2.0

**Additional context**

We found the provenance of the error. In the file `pgx/v5@v5.2.0/pgconn/pgconn.go` in the function `expandWithIPs` an error is returned if any call to `lookupFn` fails. The following change fixes the issue (even if it swallows the error message):

```diff
diff --git a/pgconn/pgconn.go b/pgconn/pgconn.go
index 59fa35c6..1b71558c 100644
--- a/pgconn/pgconn.go
+++ b/pgconn/pgconn.go
@@ -217,7 +217,7 @@ func expandWithIPs(ctx context.Context, lookupFn LookupFunc, fallbacks []*Fallba
 
                ips, err := lookupFn(ctx, fb.Host)
                if err != nil {
-                       return nil, err
+                       continue
                }
 
                for _, ip := range ips {
```

**Comment by jackc** [comment]
Fixed. `expandWithIps` now only returns an error if none of the hostname lookups succeed.
