### ISSUE TITLE
Case insensitive table name in CopyFrom

### ISSUE THREAD

**Issue by Thomasdezeeuw** [jackc/pgx#1468]
**Is your feature request related to a problem? Please describe.**

We're currently in the progress of moving from lib/pq to pgx and we're hitting a problem with `CopyFrom`. For our code we need to able to use the table name in a case insensitive way. However because `CopyFrom` uses `Identifier` it always adds quote to the table name, e.g. `table` becomes `"table"`. This makes sense for 99% of the use cases, but we're in the other 1%.

**Describe the solution you'd like**

Ideally we can get a version of `CopyFrom` that does the same thing expect for sanitising the table name (and column names). I know this has security implications, but we already sanitize our input elsewhere.

**Describe alternatives you've considered**

I've tried looking at the implementation and doing it manually, but it's a bit of a hassle. I prefer not have to write raw bytes to the connection, e.g. for the `PGCOPY\n\377\r\n\0` tag required by Postgres.

**Comment by jackc** [comment]
I don't know if we are going to be able to support this case. I'd rather not add a function that purposely bypasses sanitization.

Would it be possible for you to run a query before the copy to get the correctly cased name? e.g. `select 'mYtAbLe'::regtype`. Presumably this could be cached to avoid any performance implication.

> I've tried looking at the implementation and doing it manually, but it's a bit of a hassle. I prefer not have to write raw bytes to the connection, e.g. for the PGCOPY\n\377\r\n\0 tag required by Postgres.

As an alternative it might be worth considering exposing helper functions that build the binary copy stream. That may have uses for others who need more control of the copy protocol.

**Comment by Thomasdezeeuw** [comment]
> I don't know if we are going to be able to support this case. I'd rather not add a function that purposely bypasses sanitization.

I understand.

> Would it be possible for you to run a query before the copy to get the correctly cased name? e.g. `select 'mYtAbLe'::regtype`. Presumably this could be cached to avoid any performance implication.

I prefer not to do that since we a setup where we connect to many different databases so we don't cache anything, we don't even reuse connections.

> > I've tried looking at the implementation and doing it manually, but it's a bit of a hassle. I prefer not have to write raw bytes to the connection, e.g. for the PGCOPY\n\377\r\n\0 tag required by Postgres.
> 
> As an alternative it might be worth considering exposing helper functions that build the binary copy stream. That may have uses for others who need more control of the copy protocol.

That would work for us. We're currently using `lib/pq` and allows us to define the copy query ourselves, then all we have to do is call `Exec` on the statement with the rows we want to insert. Basically the example shown here: https://pkg.go.dev/github.com/lib/pq#hdr-Bulk_imports, but we don't use `pq.CopyIn`, but our own version (that doesn't add quotes around the table name, but it otherwise the same).

**Comment by jackc** [comment]
I assume you already are aware of https://pkg.go.dev/github.com/jackc/pgx/v5@v5.2.0/pgconn#PgConn.CopyFrom. Presumably that plus a copy stream builder is what you want. Not sure exactly what the copy stream builder interface would look like. It would probably be initialized with a `pgtype.Map` and an `io.Writer` and have a method to write a row. Not sure what else it might need.

It will probably be a while before I might have a chance to look closer at this feature.

**Comment by Thomasdezeeuw** [comment]
> I assume you already are aware of https://pkg.go.dev/github.com/jackc/pgx/v5@v5.2.0/pgconn#PgConn.CopyFrom. Presumably that plus a copy stream builder is what you want. Not sure exactly what the copy stream builder interface would look like. It would probably be initialized with a `pgtype.Map` and an `io.Writer` and have a method to write a row. Not sure what else it might need.

Thanks for the pointer to `PgConn.CopyFrom`. I did know about the `pgconn` module, but when I saw it expected OIDs I deemed it to low level for what we're doing. However `CopyFrom` is perfect for what we need because we get our data in CSV format, which PostgreSQL supports out of the box in `COPY`.

For people finding this issue in the future: we created the `COPY table ( ... ) FROM STDIN` query ourselves and passed CSV input as `io.Reader`.

> It will probably be a while before I might have a chance to look closer at this feature.

`PgConn.CopyFrom` is good enough for us, so we don't need any additional features. I'm ok with closing this as resolved, I'll leave it open if do want to add anything more. Thanks for the feedback!
