### ISSUE TITLE
Query stops receiving results from database and does not return any errors on timeout

### ISSUE THREAD

**Issue by ericreis** [jackc/pgx#1474]
**Describe the bug**
When performing a query that does not fully complete, no error is returned on the `rows.Values()`, it just stops receiving data from the database and returns an inconsistent result. The same occurs with the `rows.Err()` and `rows.Scan()` methods. I'm using a context timeout on the query to reproduce this scenario, but it also occurs on production scenarios, even with Background context

**To Reproduce**

If possible, please provide runnable example such as:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), "postgres://postgres:postgrespw@localhost:55000")
	if err != nil {
		log.Fatalln(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	rows, err := conn.Query(ctx, "select n from generate_series(1, 1000000) n")
	if err != nil {
		log.Fatalln(err)
	}

	defer rows.Close()

	var values []any
	for rows.Next() {
		values, err = rows.Values()
	}

	log.Println(values, err)
}
```
Sometimes `1000000` is not enough to reproduce the behavior. We need to come use a value that is big enough so it won't complete within the 1 second timeout and small enough that the query won't timeout before the `for rows.Next()` loop.

Result:

```
➜  pgx-query-timeout go run main.go                    
2023/01/20 21:30:55 [794075] <nil>
```

Here is some of the logs from the PostgreSQL side:
```
2023-01-21 00:30:55.180 UTC [128] LOG:  could not send data to client: Broken pipe
2023-01-21 00:30:55.180 UTC [128] STATEMENT:  select n from generate_series(1, 1000000) n
2023-01-21 00:30:55.180 UTC [128] FATAL:  connection to client lost
2023-01-21 00:30:55.180 UTC [128] STATEMENT:  select n from generate_series(1, 1000000) n
2023-01-21 00:32:03.973 UTC [1] LOG:  received fast shutdown request
2023-01-21 00:32:03.977 UTC [1] LOG:  aborting any active transactions
2023-01-21 00:32:03.979 UTC [67] FATAL:  terminating connection due to administrator command
2023-01-21 00:32:03.979 UTC [67] STATEMENT:  select n from generate_series(1, 1000000000) n
```

**Expected behavior**
To return the proper error while reading the response.

**Actual behavior**
The for loop is just interrupted without returning any errors.

**Version**
 - Go: go version go1.19 darwin/amd64
 - PostgreSQL: 14.5
 - pgx: v5.2.0

**Additional context**

**Comment by drakkan** [comment]
You are not checking for errors correctly, use this

```
log.Println(values, err, rows.Err())
```

**Comment by ericreis** [comment]
Oh I see, the error should be checked after the `for rows.Next()` loop. I understood that the check needed to be done inside the for loop, after reading the row values. Thanks for the help!
