### ISSUE TITLE
row.Scan needs to support valid postgres types (NaN, Infinity, -Infinity)

### ISSUE THREAD

**Issue by ghstahl** [jackc/pgx#1475]
**Describe the bug**
I can create a postgres record where a double can be a NaN, Infinity, -Infinity.
Once these values are in the table rows.Scan fails if it detects them.

**To Reproduce**
[Reference Issue](https://github.com/jackc/pgtype/issues/198) 

Create a postgres table that has a double
```
create table if not exists point_series
(
    point_id varchar(36) not null,
    timestamp_utc timestamp with time zone not null,
    timestamp_local timestamp not null,
    double_value double precision
);
```
Create a record where the double can be NaN, Infinity, -Infinity

Do a rows.Scan() and it will error out when it hits a record that has these.  
These are valid.
 

**Expected behavior**
A library that interacts with postgres needs to support valid postgres types.

**Comment by jackc** [comment]
Works for me...

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(ctx)

	_, err = conn.Exec(ctx, `create temporary table point_series (
	id int primary key,
	double_value double precision
);

insert into point_series values (1, 'NaN'), (2, 'Infinity'), (3, '-Infinity');
`)
	if err != nil {
		log.Fatal(err)
	}

	rows, _ := conn.Query(ctx, `select id, double_value from point_series order by id asc`)

	for rows.Next() {
		var id int32
		var d float64
		err := rows.Scan(&id, &d)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(id, d)
	}

	if err := rows.Err(); err != nil {
		log.Fatal(err)
	}
}
```

Output:

```
1 NaN
2 +Inf
3 -Inf
```

**Comment by ghstahl** [comment]
Ugh. V4 vs V5.
Let me try my tests with the upgraded library.
My bad for not pointing that out!

**Comment by ghstahl** [comment]
All good with v5.
Sorry for adding confusion with this.
Thanks again.
