### ISSUE TITLE
Add support for "time with time zone" (OID = 1266)

### ISSUE THREAD

**Issue by zapateo** [jackc/pgx#1479]
The PostgreSQL type "time with time zone" (documented [here](https://www.postgresql.org/docs/current/datatype-datetime.html)) is currently not supported by pgx.

The OID returned by PostgreSQL for this type is 1266.

Would it be possible to add support for this type?

Thanks 🙂

**Comment by jackc** [comment]
From the doc page you linked:

> We do not recommend using the type time with time zone (though it is supported by PostgreSQL for legacy applications and for compliance with the SQL standard).

`time with time zone` is weird. I'm not even sure how it could be used correctly or what would be correct type to map it to in Go.

But I guess if someone wants to build support for it in a clean way we could add it.

**Comment by zapateo** [comment]
Ok, got it! As far as I'm concerned, this issue can be closed. Thanks :)
