### ISSUE TITLE
QueryError: cannot encode Go []string into oid 25

### ISSUE THREAD

**Issue by xeger** [jackc/pgx#148]
I'm trying to run a Query that uses an IN constraint, like so:
```
	stmt := "SELECT id FROM widgets WHERE color IN ($1)"
        colors := []string{"blue", "red"}
	rows, err := conn.Query(stmt,colors)
```

However, this results in a complaint from pgx that it doesn't know how to encode a string-array into oid 25 (which is `TextOid`).

Based on my reading of the source, it seems like maybe postgres is in the wrong here, because pgx delegates prepared-statement parsing and arg detection to the server; however, as a humble user of pgx, I'm quite taken by surprise!

Even more strange: if I manually convert my constraints to a string, my query fails to find rows ... I'm not quite sure what's going wrong; all I know is that this finds 0 rows:
```
	rows, err := conn.Query(stmt,"'blue', 'red'")
```

Whereas this finds two rows:
```
SELECT id FROM widgets WHERE color IN ('blue', 'red');
```

**Comment by jackc** [comment]
PostgreSQL is correct for this query: `SELECT id FROM widgets WHERE color IN ($1)` An array is not a valid `$1` (unless `color` were an array, of course).

Here's a test widgets table.
```
jack=# create table widgets(id serial primary key, name text not null, color text not null);
CREATE TABLE
Time: 62.773 ms
jack=# insert into widgets (name, color) values ('foo', 'blue'), ('bar', 'green'), ('baz', 'red');
INSERT 0 3
Time: 7.311 ms
```

Note we cannot use an array as the `in` parameter.

```
jack=# select * from widgets where color in ('{blue,red}'::text[]);
ERROR:  operator does not exist: text = text[]
LINE 1: select * from widgets where color in ('{blue,red}'::text[]);
                                          ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
What you really want is `= any` (https://www.postgresql.org/docs/current/static/functions-comparisons.html#AEN20327)

```
jack=# select * from widgets where color = any ('{blue,red}'::text[]);
 id | name | color
----+------+-------
  1 | foo  | blue
  3 | baz  | red
(2 rows)

Time: 1.499 ms
```

So if you `in` to `= any` in `stmt` it should work.

This may be surprising if you are used to something like Ruby on Rails. Rails automatically expands Ruby arrays into multiple parameters. i.e. It expands the single substitution parameter into `$1`, `$2`, `$3`, etc. automatically.

As for why the second attempt fails, 
```
rows, err := conn.Query(stmt,"'blue', 'red'")
```
is searching for a single string of `"'blue', 'red'"` not either of `blue` or `red`.

You would need to do it this way:

```
 stmt := "SELECT id FROM widgets WHERE color IN ($1, $2)"
 rows, err := conn.Query(stmt, "blue", "red")
```

**Comment by xeger** [comment]
In my case, `color` is the primary key of the table, and I'm searching for a range of primary keys. This works from the `psql` command line as a simple `IN ('blue', 'red')` constraint but it seems that positional parameters must be scalar-valued and there's no way to natively represent a variable number of replacement params without building a new query every time to specify $1 to $N.

I think your trick of representing the keys as a string with psql list notation, then casting them in-language to an array, will work nicely. Thanks for the tip!
