### ISSUE TITLE
LastInsertId is not supported by this driver

### ISSUE THREAD

**Issue by mozhata** [jackc/pgx#1483]
**Is your feature request related to a problem? Please describe.**

I am beginer for postgres. When I worked with pgx using the method `Exec()`, an error is occured
```
LastInsertId is not supported by this driver
```
and I foud a some issue in https://github.com/lib/pq/issues/24 closed by a workaround

the workaround mentioned in the comments is odd:
```
var id int
err := db.QueryRow("INSERT INTO user (name) VALUES ('John') RETURNING id").Scan(&id)
if err != nil {
...
}
```
**Describe the solution you'd like**

I think the best way is totally support the `Result` interface defined in database/sql

**Describe alternatives you've considered**

even implement `Exec()` using the `QueryRow()` in the underline is better than using `QueryRow` directly

**Comment by jackc** [comment]
Sorry, this is not possible. PostgreSQL doesn't have the concept of last insert ID. You have to use `QueryRow` with `RETURNING`.
