### ISSUE TITLE
Slices of any are no longer encoded after switching to v5

### ISSUE THREAD

**Issue by hashibuto** [jackc/pgx#1488]
**Describe the bug**
When passing data to a query, slices of any ie. []any{1, 2, 4} were accepted for escaping into an ANY() clause.  Instead now we get an error.

**To Reproduce**

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

        sql := `SELECT foo FROM bar WHERE id ANY($1)`
        args := []any{
                []any{1, 2, 3},
        }
	rows, err := conn.Query(context.Background(), sql, ...args)
}
```

**Expected behavior**
Typically the query would have no problem encoding the `[]any{1, 2, 3}`.

**Actual behavior**
We get this error message:
```
Failed to encode args[0]: unable to encode []interface {}{1, 2, 3} into binary format for _int4 (OID 1007):
```
However, if we supply this as `[]int{1, 2, 3}`, the query does not fail.  The problem is that a lot of automated data deserialized from JSON produces these `[]any{}` structures.

**Version**
 - Go: `go version go1.19.2 linux/amd64`
 - PostgreSQL: `PostgreSQL 11.18 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit`
 - pgx: `v5.2.0`

**Additional context**

**Comment by jackc** [comment]
Should be fixed on master now. (c875abea84ee9b6564787192e7150129d275a14d)

**Comment by hashibuto** [comment]
@jackc Thanks, very much appreciated!

**Comment by r3-gabriel** [comment]
@jackc Ran into this one as well - thanks for the fix!
