### ISSUE TITLE
pgtype.Numeric.MarshalJSON() returns incorrect negative values

### ISSUE THREAD

**Issue by jos-** [jackc/pgx#1491]
**Describe the bug**
[pgtype.Numeric.MarshalJSON()](https://github.com/jackc/pgx/blob/766d2bba4f32968bc71846240e9e5574d80aedf0/pgtype/numeric.go#L231]) returns for numeric values of e.g. `-0.05` an output of `0.-5`.

**To Reproduce**

```go
package main

import (
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

func main() {
	var num pgtype.Numeric
	if err := num.Scan("-0.05"); err != nil {
		fmt.Println(err)
		return
	}

	output, err := num.MarshalJSON()
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("output: %s", output)
}
```

**Expected behavior**
Expected behavior is that the code above outputs `-0.05`.

**Actual behavior**
Actual behavior is that the code above outputs `0.-5`.

**Version**
 - Go: `1.19`
 - pgx: `v5.2.0`

**Additional context**
Seems to be a bug in the `numberTextBytes()` function. By the way, thanks for pgx 👍

**Comment by jackc** [comment]
Already fixed on master (37c6f97b114bd00604a1ee5b283e8ae4541ba4ab). Will be part of upcoming `5.3.0` release.
