### ISSUE TITLE
Balance connection between readers instances

### ISSUE THREAD

**Issue by ismaelvacco** [jackc/pgx#1496]
First of all, I would like to thank you for this project.

I have a pool of reader instances balanced by DNS. So, when my connection pool is created, it is not homogenous, i.e., I have many connections to an instance and few or zero connections to other instances.

I would like to know if it's possible to balance the connection pool using some hook function or any other way.

Thanks

**Comment by jackc** [comment]
The `ValidateConnect` field of `pgconn.Config` might do what you need. https://pkg.go.dev/github.com/jackc/pgx/v5@v5.2.0/pgconn#Config

It is used to implement high availability behavior such as `libpq` does with `target_session_attrs`.

**Comment by ismaelvacco** [comment]
Thanks for answering my question

I solved this problem by writing my own `LookupFunc` func.

The DNS rotates each IP at 5 sec (AWS Aurora implementation). So, I wrote a function that controls the valid IPs, adding and removing them after some time.

I know the better solution would be to use an AWS RDS proxy, but I wanted to solve it in the database connection layer.

**Comment by basilveerman** [comment]
@ismaelvacco Are you able to share your solution? Anyone using Aurora read replicas w/out a middle tier (pgpool-ii, HA Proxy) will have this issue.
