### ISSUE TITLE
Release 5.3.0 breaking scanning

### ISSUE THREAD

**Issue by sknick** [jackc/pgx#1500]
Upgrading from 5.2.0 to 5.3.0 appears to be breaking my scanning code as I get this error:

```
pq: unable to parse array; expected '{' at offset 0
```

Of relevance I'm sure is how I implemented scanning for my custom types. Hopefully this code snippet will clarify what I need to adjust to accommodate the new pgx version:

```
type series struct {
	Name           string         `json:"name,omitempty"`
	Description    string         `json:"description,omitempty"`
	IsEsports      bool           `json:"is_esports,omitempty"`
	VehicleClasses []vehicleClass `json:"vehicle_classes,omitempty"`
	Id             string         `json:"id,omitempty"`
}

type vehicleClass struct {
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Id          string `json:"id,omitempty"`
}

func scan(value interface{}, dest interface{}) error {
	var data []byte

	switch val := value.(type) {
	case string:
		data = []byte(val)
	case []byte:
		data = val
	}

	return json.Unmarshal(data, dest)
}

func (s *series) Scan(value interface{}) error {
	return scan(value, s)
}

func (v *vehicleClass) Scan(value interface{}) error {
	return scan(value, v)
}
```

I declare the value to be scanned into as follows:

```
var seriesVal []series
```

Then in the `Scan()` call, I pass:

```
pq.Array(&seriesVal)
```

Examples values to be scanned are as follows:

```
 {"{\"id\": \"0cf7511b-b76d-4b9f-8602-a21acf7f1e3f\", \"name\": \"Test Series 1\", \"is_esports\": false, \"description\": \"This is a description of Test Series 1.\", \"vehicle_classes\": null}"}
 {"{\"id\": \"e13b8253-6439-44cd-8389-60b4a2b0d3ec\", \"name\": \"Test Series 3\", \"is_esports\": false, \"description\": \"This is a description of Test Series 3.\", \"vehicle_classes\": null}","{\"id\": \"398128a3-25f4-4058-bd93-e4c6b2f91faf\", \"name\": \"Test Series 2\", \"is_esports\": false, \"description\": \"This is a description of Test Series 2.\", \"vehicle_classes\": null}","{\"id\": \"b47510c6-cb54-4bd0-98f3-26ad78689277\", \"name\": \"Test Series 4\", \"is_esports\": false, \"description\": \"This is a description of Test Series 4.\", \"vehicle_classes\": null}","{\"id\": \"0cf7511b-b76d-4b9f-8602-a21acf7f1e3f\", \"name\": \"Test Series 1\", \"is_esports\": false, \"description\": \"This is a description of Test Series 1.\", \"vehicle_classes\": null}"}
 {"{\"id\": \"0cf7511b-b76d-4b9f-8602-a21acf7f1e3f\", \"name\": \"Test Series 1\", \"is_esports\": false, \"description\": \"This is a description of Test Series 1.\", \"vehicle_classes\": null}","{\"id\": \"398128a3-25f4-4058-bd93-e4c6b2f91faf\", \"name\": \"Test Series 2\", \"is_esports\": false, \"description\": \"This is a description of Test Series 2.\", \"vehicle_classes\": null}"}
 {"{\"id\": \"0cf7511b-b76d-4b9f-8602-a21acf7f1e3f\", \"name\": \"Test Series 1\", \"is_esports\": false, \"description\": \"This is a description of Test Series 1.\", \"vehicle_classes\": null}","{\"id\": \"b47510c6-cb54-4bd0-98f3-26ad78689277\", \"name\": \"Test Series 4\", \"is_esports\": false, \"description\": \"This is a description of Test Series 4.\", \"vehicle_classes\": null}","{\"id\": \"e13b8253-6439-44cd-8389-60b4a2b0d3ec\", \"name\": \"Test Series 3\", \"is_esports\": false, \"description\": \"This is a description of Test Series 3.\", \"vehicle_classes\": null}","{\"id\": \"2af4ded1-0633-4a65-98f9-7187e82e7632\", \"name\": \"Test Series 5\", \"is_esports\": false, \"description\": \"This is a description of Test Series 5.\", \"vehicle_classes\": null}","{\"id\": \"398128a3-25f4-4058-bd93-e4c6b2f91faf\", \"name\": \"Test Series 2\", \"is_esports\": false, \"description\": \"This is a description of Test Series 2.\", \"vehicle_classes\": null}"}
 {"{\"id\": \"398128a3-25f4-4058-bd93-e4c6b2f91faf\", \"name\": \"Test Series 2\", \"is_esports\": false, \"description\": \"This is a description of Test Series 2.\", \"vehicle_classes\": null}","{\"id\": \"0cf7511b-b76d-4b9f-8602-a21acf7f1e3f\", \"name\": \"Test Series 1\", \"is_esports\": false, \"description\": \"This is a description of Test Series 1.\", \"vehicle_classes\": null}","{\"id\": \"e13b8253-6439-44cd-8389-60b4a2b0d3ec\", \"name\": \"Test Series 3\", \"is_esports\": false, \"description\": \"This is a description of Test Series 3.\", \"vehicle_classes\": null}"}
```

Go: `go1.20 linux/amd64`
PostgreSQL: `PostgreSQL 10.14 (Debian 10.14-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit`
pgx: `5.3.0`

**Comment by jackc** [comment]
What type is the PostgreSQL column?

`v5.3.0` fixed an issue where certain array types were using the text format instead of the binary format (binary is preferred as it can be significantly faster). My guess is this change is somehow triggering the problem.

It would be much easier to diagnose if you could provide an example I could run that showed it working on `v5.2.0` and not working on `v5.3.0`.

Also, while this does appear to be a pgx regression and I would like to get it fixed, and it's not clear to me all your custom scanning logic may be doing, my guess is that there is a better / simpler way to do your array handling. I would not expect you to need `pq.Array` or to call `json.Unmarshal` directly.

**Comment by oottinger** [comment]
There's definitely something breaking the way arrays work. I'm not doing a scan, just a simple exec where I provide an array and getting odd behavior.  My failure happens on this line:

https://github.com/jackc/pgx/blob/master/pgtype/builtin_wrappers.go#L751

With a message `test panicked: reflect: call of reflect.Value.IsNil on struct Value`

What makes this behavior odd is that when I run the full test suite I get the failure, but individually running the failing test it passes every time. If I comment out a simple select count query that runs before query with an array, the full test suite runs without issue. I've also tried to comment out another test in the suite, and the one failing test starts to work. Is there some sort of caching, sharing of memory, or race condition that could be occurring in the changes in `5.3.0`?

**Comment by sknick** [comment]
> What type is the PostgreSQL column?

It's being built in a view like so:

```
array_agg(
    jsonb_build_object(
        'id',              series_with_vehicle_classes.id,
        'name',            series_with_vehicle_classes.name,
        'description',     series_with_vehicle_classes.description,
        'is_esports',      series_with_vehicle_classes.is_esports,
        'vehicle_classes', series_with_vehicle_classes.vehicle_classes
    )
)
```

**Comment by jackc** [comment]
@sknick I tried to duplicate your issue but was unable to.

I did discover one issue with the Scan and fixed it in a9ff98853cf950cd8186a8346ace334c537c2df7, but I don't think it relates to your problem.

It's really hard to determine what is going on from these incomplete code snippets -- especially when I'm not sure why most of the code even exists. pgx can automatically unmarshal json columns. AFAICT, your `Scan` implementations and apparent usage of `pq.Array` are completely unnecessary. Return a single json blob from the database (you should use `jsonb_agg` instead of `array_agg`) and scan it directly into your variable.

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

type Fruit struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(ctx)

	_, err = conn.Exec(ctx, `create temporary table fruits (
	id int primary key generated by default as identity,
	name text not null,
	color text not null
);

insert into fruits (name, color) values
	('Apple', 'Red'),
	('Banana', 'Yellow')
;`)
	if err != nil {
		log.Fatal(err)
	}

	var result []Fruit

	err = conn.QueryRow(ctx, `select jsonb_agg(
		jsonb_build_object(
			'id', id,
			'name', name,
			'color', color
		)
	)
from fruits`).Scan(&result)
	if err != nil {
		log.Fatal(err)
	}

	log.Println(result)
}
```

Assuming there is a bug, I'd still like to get it fixed, but I can't do anymore without a complete example I can run.

**Comment by jackc** [comment]
@oottinger I suspect your problem is probably #1502.

**Comment by jackc** [comment]
@sknick You also could bisect between pgx `v5.2.0` and `v5.3.0` to narrow down the problem.

**Comment by sknick** [comment]
So it took me a fair amount to find a solution to scanning things properly... I have switched things out and it indeed scans fine by not using `pq.Array()` or the custom scanning code. I also switched to `jsonb_agg()` in the views. Thanks for the tips. I think you can consider this issue closed.
