### ISSUE TITLE
Panic after upgrading from 5.2.0 to 5.3.0 when using stdlib

### ISSUE THREAD

**Issue by oschwald** [jackc/pgx#1502]
**Describe the bug**

`reflect: call of reflect.Value.IsNil on struct ` after upgrading to 5.3.0.

**To Reproduce**

I am still trying to narrow this down to a small runnable example outside of our codebase.

**Expected behavior**

The query to work.

**Actual behavior**
```
stderr: net/http/server.go:3228: http: panic serving 127.0.0.1:44974: reflect: call of reflect.Value.IsNil on struct Value
goroutine 159 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1850 +0xbf
panic({0x1306980, 0xc0004ccae0})
	runtime/panic.go:890 +0x262
reflect.Value.IsNil(...)
	reflect/value.go:1554
github.com/jackc/pgx/v5/pgtype.anySliceArrayReflect.Dimensions({{0x13d6c40?, 0xc0004ccab0?, 0x33000184b200?}})
	github.com/jackc/pgx/v5@v5.3.0/pgtype/builtin_wrappers.go:751 +0x117
github.com/jackc/pgx/v5/pgtype.(*encodePlanArrayCodecBinary).Encode(0xc000eb09c0, {0x13d6c40?, 0xc0004ccac8}, {0xc0005e4800, 0xd, 0x100})
	github.com/jackc/pgx/v5@v5.3.0/pgtype/array_codec.go:175 +0x7b
github.com/jackc/pgx/v5/pgtype.(*wrapSliceEncodeReflectPlan).Encode(0xc001487fe0, {0x13d6c40?, 0xc0004ccab0?}, {0xc0005e4800, 0xd, 0x100})
	github.com/jackc/pgx/v5@v5.3.0/pgtype/pgtype.go:1964 +0x117
github.com/jackc/pgx/v5/pgtype.(*wrapSliceEncodePlan[...]).Encode(0xc001487fc0?, {0x12a35c0, 0xc0004cca50?}, {0xc0005e4800?, 0xd, 0x100})
	github.com/jackc/pgx/v5@v5.3.0/pgtype/pgtype.go:1950 +0x118
github.com/jackc/pgx/v5/pgtype.(*Map).Encode(0x12a35c0?, 0x4cca50?, 0xc0?, {0x12a35c0, 0xc0004cca50}, {0xc0005e4800, 0xd, 0x100})
	github.com/jackc/pgx/v5@v5.3.0/pgtype/pgtype.go:2066 +0x8a
github.com/jackc/pgx/v5.(*ExtendedQueryBuilder).encodeExtendedParamValue(0xc001ab0540, 0x0?, 0x16e6600?, 0x0?, {0x12a35c0, 0xc0004cca50})
	github.com/jackc/pgx/v5@v5.3.0/extended_query_builder.go:126 +0xdd
github.com/jackc/pgx/v5.(*ExtendedQueryBuilder).appendParam(0xc001ab0540, 0xc0014f4480?, 0xb87?, 0x1, {0x12a35c0?, 0xc0004cca50?})
	github.com/jackc/pgx/v5@v5.3.0/extended_query_builder.go:76 +0x16a
github.com/jackc/pgx/v5.(*ExtendedQueryBuilder).appendParam(0xc001ab0540, 0xc000b76000, 0x206be7a8?, 0x7fdd?, {0x12a35c0?, 0xc0004cca50})
	github.com/jackc/pgx/v5@v5.3.0/extended_query_builder.go:56 +0xe5
github.com/jackc/pgx/v5.(*ExtendedQueryBuilder).Build(0xc001ab0540, 0xc000b76000, 0xc0009786e0, {0xc0004bcf10?, 0xf, 0xf})
	github.com/jackc/pgx/v5@v5.3.0/extended_query_builder.go:37 +0x409
github.com/jackc/pgx/v5.(*Conn).Query(0xc001ab0480, {0x1839b68?, 0xc000a651a0?}, {0x152b5bc, 0xb63}, {0xc0004bcf00?, 0x10, 0x10})
	github.com/jackc/pgx/v5@v5.3.0/conn.go:738 +0xd0f
github.com/jackc/pgx/v5/stdlib.(*Conn).QueryContext(0xc0014de9a0, {0x1839b68, 0xc000a651a0}, {0x152b5bc, 0xb63}, {0xc000dab400, 0xf, 0xc000bd9538?})
	github.com/jackc/pgx/v5@v5.3.0/stdlib/sql.go:418 +0x20e
database/sql.ctxDriverQuery({0x1839b68?, 0xc000a651a0?}, {0x7fdd20485b88?, 0xc0014de9a0?}, {0x0?, 0x0?}, {0x152b5bc?, 0xc000bd95e8?}, {0xc000dab400, 0xf, ...})
	database/sql/ctxutil.go:48 +0xe5
database/sql.(*DB).queryDC.func1()
	database/sql/sql.go:1757 +0x175
database/sql.withLock({0x1831af8, 0xc0008c25a0}, 0xc000bd9758)
	database/sql/sql.go:3439 +0x8c
database/sql.(*DB).queryDC(0x40f301?, {0x1839b68, 0xc000a651a0}, {0x0, 0x0}, 0xc0008c25a0, 0xc001487fa0, {0x152b5bc, 0xb63}, {0xc000bd9a90, ...})
	database/sql/sql.go:1752 +0x211
database/sql.(*DB).query(0xc001585500?, {0x1839b68, 0xc000a651a0}, {0x152b5bc, 0xb63}, {0xc000bd9a90, 0xf, 0xf}, 0x0?)
	database/sql/sql.go:1735 +0xfd
database/sql.(*DB).QueryContext(0x0?, {0x1839b68, 0xc000a651a0}, {0x152b5bc, 0xb63}, {0xc000bd9a90, 0xf, 0xf})
	database/sql/sql.go:1708 +0xda
database/sql.(*DB).QueryRowContext(...)
	database/sql/sql.go:1813
```

**Version**
 - Go: go version go1.19.5 linux/amd64
 - PostgreSQL: PostgreSQL 14.6 (Ubuntu 14.6-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
 - pgx: v5.3.0

**Additional context**

**Comment by oschwald** [comment]
Although the initial report on https://github.com/jackc/pgx/issues/1500 sounds different, there is a [comment reporting a similar panic](https://github.com/jackc/pgx/issues/1500#issuecomment-1427620445). I am not sure if this should be closed as a dupe or not.

**Comment by prochac** [comment]
imo the guard is wrong
https://github.com/jackc/pgx/issues/1501#issuecomment-1428442392

**Comment by oschwald** [comment]
I've spent some time trying to reproduce it outside of our test suite and I haven't been successful so far.

**Comment by jackc** [comment]
> Although the initial report on https://github.com/jackc/pgx/issues/1500 sounds different, there is a https://github.com/jackc/pgx/issues/1500#issuecomment-1427620445. I am not sure if this should be closed as a dupe or not.

This appears to be happening in the encoding path. #1500 is while scanning so I think these are different.

The comment in that issue you mention refers to difficulty reproducing the issue when running the test alone and asked about any new cache behavior.

There is indeed new caching behavior. pgx now remembers the EncodePlan for a given Go type into a PostgreSQL OID instead of replanning every time. This behavior was already in place for scanning, but it is new on the encode path.

Since it appears you can reproduce the issue locally, just not in an isolated fashion, maybe you could git bisect between `v5.2.0` and `v5.3.0`. IIRC, there aren't any large commits so that would probably track it down to just a handful of lines of code.

**Comment by oschwald** [comment]
Bisecting this leads me to 42a47194a238c4951cc87c063a7c4d5167d06ad6.

**Comment by oschwald** [comment]
This query has quite a number of parameters. Here is a high level overview:

1 x an `int64` type into `int`
13 x a `string` into `citext`
1 x a `[]string` into `uuid[]`

The `[]string` obviously does not contain any `nil` values, but it could be `nil` itself.

**Comment by jackc** [comment]
It would seem likely it is the `[]string` to `uuid[]`. Though when I created a test I was unable to make that fail.

**Comment by oschwald** [comment]
Yeah, I did try to make an isolated test case with that and other variations the other day, but I was not able to make it fail either.

How long does the cache live? Is it tied to the life of the connection, the life of the pool, or something else?

**Comment by jackc** [comment]
The cache is per connection.

**Comment by oschwald** [comment]
Thanks. That eliminates the only hypothesis I had. These tests run using fixture databases created for the test, and it seemed possible that the pool might end up getting used for two separate databases in this case. However, if it is per connection, that should not be an issue.

If there is any other additional information that I could provide, please let me know.

**Comment by jackc** [comment]
I've got some more ideas, but they would be somewhat more difficult to try.

---

Presumably, when you run the test alone and it succeeds it is using a different `EncodePlan` than when it fails. It would be interesting to add some logging to `Map.PlanEncode` to see what the different plans actually are. Then add a breakpoint to when the bad plan gets cached. That should allow determining what sequence of queries causes the problem.

Obviously, that's getting pretty in the weeds to modify pgx and step through in the debugger though...

---

Another approach would be to change the order of execution of your tests. I assume that it would work if it was run first. The test could be moved back and forth until it was clear what preceding test causes the failure. That would be less complicated than the preceding idea, but is a bit laborious.

---

Once we have what sequence of queries causes the problem it should be easier to find the root issue.

**Comment by oschwald** [comment]
After reflecting a bit more on the issue, I've managed to reduce it to a small test case:

```
package main

import (
	"database/sql"
	"log"
	"os"

	"github.com/google/uuid"
	_ "github.com/jackc/pgx/v5/stdlib"
)

func main() {
	db, err := sql.Open("pgx", os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}

	_, err = db.Exec(
		`SELECT null = ANY($1::uuid[])`,
		[]uuid.UUID{uuid.MustParse("7e6dfa1e-b236-11ed-87c4-d34bf7fc00d7"), uuid.MustParse("829946ca-b236-11ed-b543-6fe435fd9723")},
	)
	if err != nil {
		log.Fatal(err)
	}
	_, err = db.Exec(
		`SELECT null = ANY($1::uuid[])`,
		[]string{"7e6dfa1e-b236-11ed-87c4-d34bf7fc00d7", "829946ca-b236-11ed-b543-6fe435fd9723"},
	)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by jackc** [comment]
Thanks for producing the test case. I'm not sure I ever would have been able to track it down without it.

The particular combination of types on the Go and PostgreSQL side needed to trigger the issue is unusual and the system that figures out what to do with types that don't directly implement a pgx or database/sql interface like `driver.Valuer` is fiendishly complex. Well, the code actually isn't too bad, but makes heavy use of recursion and reflection to trying figure out what that arguments are and how they can be handled. Difficult to follow the execution path even in a debugger.

Anyway, this actually revealed a bug in a certain path of the array encoding logic. Without the EncodePlan cache system it only manifested as a more complicated than necessary plan. But with the cache system part of that more complicated than necessary plan was cached by the previous plan with an incompatible plan. 

38e09bda4c68fc87967b50455640e308bda6a959 should fix it in addition to providing a small performance improvement to certain array encoding paths.

**Comment by oschwald** [comment]
I tested out the fix with our codebase and it seems to fix the issue. Thank you!
