### ISSUE TITLE
Whether it is a bug ?

### ISSUE THREAD

**Issue by Jay-deng** [jackc/pgx#1505]
**Describe the bug**
When I use Uber's goleak to run the test function TestContextWatcherMultipleWatchPanics() in https://github.com/jackc/pgx/blob/master/pgconn/internal/ctxwatch/context_watcher_test.go, I got the following output information. I was wondering if it is a bug ?
<img width="1254" alt="1" src="https://user-images.githubusercontent.com/37053493/218683902-0473623d-04bf-4118-809f-177db846d43e.png">

**To Reproduce**
 run TestContextWatcherMultipleWatchPanics() with goleak.

**Comment by jackc** [comment]
I don't have goleak setup but it looks like that test isn't cleaning up after itself. (it is purposely panicking after all...) Anyway, I think f17c743c3cda91e72c870f93a79c33567e2969bb should placate goleak.

**Comment by Jay-deng** [comment]
Thank you for reply. Such goroutine leak is hard to catch.  Maybe we can avoid this by calling `defer ` and doing more tests.
