### ISSUE TITLE
Add MarshalJSON/UnmarshalJSON methods to v5/pgtype.Array

### ISSUE THREAD

**Issue by carlmjohnson** [jackc/pgx#1509]
pgtype.Array is a useful type, but it marshals to/from JSON poorly. If there is any interest, I can open a PR to add MarshalJSON/UnmarshalJSON methods to it.

**Comment by jackc** [comment]
You specifically mean `pgtype.Array` no `pgtype.FlatArray`? It's fine with me, but it might be a little awkward to round trip the array dimensions.

**Comment by carlmjohnson** [comment]
See https://github.com/kyleconroy/sqlc/issues/2083 for why I want to change pgtype.Array. :-) FlatArray has basically fine JSON serialization other than the usual Go "nil slice becomes null JSON" thing.

**Comment by jackc** [comment]
I don't know the context for the sqlc thing, but I'm a little surprised whenever I see `pgtype.FlatArray` or especially `pgtype.Array` used directly. Typically, pgx can directly work with `[]T`, `[][]T`, etc. I only anticipated `pgtype.Array` being used directly if the application actually needed to work with non-standard starting indexes.

**Comment by carlmjohnson** [comment]
sqlc used []T directly in its pgx/v4 generator, so maybe the change to pgtype.Array with v5 is a regression that they should fix.

**Comment by kyleconroy** [comment]
I posted this comment on https://github.com/kyleconroy/sqlc/pull/2090, but thought this would also be a good place to discuss.

@jackc If I have a nullable text column, I'm assuming that scanning those values into a `[]string` will work, but if there's a null value, the scanning will fail.

**Comment by carlmjohnson** [comment]
I don't think those can be scanned into a pgtype.Array either:

```
$ go doc pgtype.Array
package pgtype // import "github.com/jackc/pgx/v5/pgtype"

type Array[T any] struct {
        Elements []T
        Dims     []ArrayDimension
        Valid    bool
}
    Array represents a PostgreSQL array for T. It implements the ArrayGetter and
    ArraySetter interfaces. It preserves PostgreSQL dimensions and custom lower
    bounds. Use FlatArray if these are not needed.
```

The elements are `[]T`. ArrayDimensions lets you have multidimensional arrays and starting offsets other than 0, but don't have anything for null.

**Comment by jackc** [comment]
Neither `[]T`, `pgtype.FlatArray[T]`, or `pgtype.Array[T]` have any effect on whether `T` can be `NULL`. When `T` is `string` none of them will work if a `NULL` element is scanned.

In this case, to support `NULL` for elements `T` should either be `*string` or `pgtype.Text`.

**Comment by jackc** [comment]
> I don't know the context for the sqlc thing, but I'm a little surprised whenever I see pgtype.FlatArray or especially pgtype.Array used directly. Typically, pgx can directly work with []T, [][]T, etc. I only anticipated pgtype.Array being used directly if the application actually needed to work with non-standard starting indexes.

Just a little more information on this. _Technically_, `pgtype.FlatArray[T]` can be faster than `[]T`, at least for unusual types. `[]T` may use reflection which `pgtype.FlatArray[T]` will not. Common types like `int32` and `string` are special cased and should have equivalent performance either way. On current master anyway -- I just fixed a bug that was preventing this from triggering sometimes. It was reviewing that code that reminded me why `pgtype.FlatArray[T]` might be useful on occasion.

But practically speaking, it's unlikely the difference between `pgtype.FlatArray[T]` and `[]T` will be meaningful unless the `T` is not a simple type and the array is large. I would still recommend using `[]T` unless a performance issue was measured.
