### ISSUE TITLE
Conflicting pgconn package names

### ISSUE THREAD

**Issue by Robbie-Perry** [jackc/pgx#1510]
Hi,

I spent some time trying to figure out why the following type assertion was not working:

```go
res := tx.Take(&f, "id = ?", id)
if res.Error != nil {
    if pqErr, ok := res.Error.(*pgconn.PgError); ok {
        // does not reach here
    } else {
        fmt.Printf("Error type: %T\n", res.Error)
        // Output: "Error type: *pgconn.PgError"
    }
}
```

It turns out both `github.com/jackc/pgconn` and `github.com/jackc/pgx/pgconn` exist, and both have `PgError` types. I had imported the wrong one for my type assertion.

How come there are 2 packages with the same name, containing the same type? Was this intended? Thanks

**Comment by Robbie-Perry** [comment]
Ah I see what was happening. Even though I had imported `jackc/pgx/v5` into my project, a dependency was using `v4` which had the different returned error type.

**Comment by jackc** [comment]
In v5 a number of related packages were brought into the main repo. See https://github.com/jackc/pgx/issues/1054 for more info.
