### ISSUE TITLE
[pgproto3] error while writing data row with more than one row

### ISSUE THREAD

**Issue by mhkarimi1383** [jackc/pgx#1514]
**Describe the bug**
when I run a query to a server that is made with pgproto3 lib (github.com/jackc/pgx/v5/pgproto3) it will fail if it wants to return multiple rows

```sql
postgres=> select *
from (
   values (1)
) as t(id);
 id
----
  1
(1 row)
```

```sql
postgres=> select *
from (
   values (1), (1)
) as t(id);
unexpected field count in "D" message
```

**To Reproduce**

checkout here: https://github.com/mhkarimi1383/pg_pro/blob/main/main.go

**Expected behavior**
Just return the query result

**Actual behavior**
`unexpected field count in "D" message`

**Version**
 - Go: `$ go version` -> go version go1.20 linux/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> github.com/jackc/pgx/v5 v5.2.0

**Comment by jackc** [comment]
I believe the problem is in your code here:

https://github.com/mhkarimi1383/pg_pro/blob/563a475d1f51caa7855d69b07a106a3bf84d6d46/connection/connection.go#L53-L62

```go
	for rows.Next() {
		values, rowValuesErr := rows.Values()
		if rowValuesErr != nil {
			return nil, rowValuesErr
		}
		for _, value := range values {
			byteValue := utils.GetBytes(value)
			result.DataRow.Values = append(result.DataRow.Values, byteValue)
		}
	}
```

It seems to appending all results to a single `DataRow`. Each result row is a separate `DataRow` message.

**Comment by mhkarimi1383** [comment]
Oh thanks
I will fix that...

**Comment by mhkarimi1383** [comment]
Worked
Thanks
