### ISSUE TITLE
pgx.RowToStructByName: skip unknown struct fields

### ISSUE THREAD

**Issue by DmitriyVTitov** [jackc/pgx#1515]
Func `RowToStructByName[T any](row CollectableRow)` requires that: "T must have the same number of named public fields as row has fields".
That means that I must define different Go types for different requests to the same DB table. I might have table `books` with columns: `id, name and synopsis`. Sometimes I want to query synopsis and sometimes I don't. Hence I would like to define type as:
```
type book struct {
	Id        int
	Name string `db:"name"`
	Synopsis     string `db:"synopsis"`
}

```

And my query could be `SELECT id, name FROM books` or `SELECT id, name, synopsis FROM books` depends on place in application.
So I would like to have an option or a wrapper function that allows to scan row to struct and silently skip unknown fields.

**Comment by jackc** [comment]
@pashagolub Any thoughts on this? ⬆️

**Comment by pashagolub** [comment]
I think `func CollectRows[T any](rows Rows, fn RowToFunc[T]) ([]T, error)` is exactly for that. If you need full control, just write your function to collect rows. Or one can use `func RowToMap(row CollectableRow) (map[string]any, error)`.

Or even define types like

```go
type book struct {
	Id        int
	Name string `db:"name"`
}

type bookEx struct {
        book 
	Synopsis     string `db:"synopsis"`
}
```

**Comment by DmitriyVTitov** [comment]
> I think `func CollectRows[T any](rows Rows, fn RowToFunc[T]) ([]T, error)` is exactly for that. If you need full control, just write your function to collect rows. Or one can use `func RowToMap(row CollectableRow) (map[string]any, error)`.
> 
> Or even define types like
> 
> ```go
> type book struct {
> 	Id        int
> 	Name string `db:"name"`
> }
> 
> type bookEx struct {
>         book 
> 	Synopsis     string `db:"synopsis"`
> }
> ```

I'm not sure that is a solution. If I need to write scanner function for every type that would be the same amount of work as using `for rows.Next() { rows.Scan( ... ) }` but more complicated code.
I'm quite happy with pgx/v4 except the lack of struct scan. And in my opinion that should be easy to use feature that handles struct fields that has no match.
You types example works in simple situation like the one i've described. But I have complicated structs with tens of fields for queries with joins. And rewriting them in that manner would be a great problem also.
There is an ongoing discussion whether we should use different struct types for storage and for business logic, I use the same and would like to simplify my code replacing `rows.Scan( ... )` calls with struct scan.
I really don't see any reasons to return an error in the case of fields number mismatch. We have `db` tag which removes any ambiguity. In the case of multiple composition of same type we can choose the first field with matching name if this is the problem (like sqlx).

**Comment by pashagolub** [comment]
There is a reason. Backward compatibility. My code relies on the fact that for every public field there is a column in a result set. 
I want to get an error if the database output changes. Instead of guessing why my public field non initialized silently.

The same way you will have an error raised by `RowToAddrOfStructByPos()` if the number of struct fields less than number of row columns. If we want to change one, we should change another as well.

**Comment by DmitriyVTitov** [comment]
> There is a reason. Backward compatibility. My code relies on the fact that for every public field there is a column in a result set. I want to get an error if the database output changes. Instead of guessing why my public field non initialized silently.
> 
> The same way you will have an error raised by `RowToAddrOfStructByPos()` if the number of struct fields less than number of row columns. If we want to change one, we should change another as well.

That is a logical requirement. That's why I ask for a wrapper func or option that must be explicitly set to change this behavior. That would keep backward compatibility.
Also that is not the case with `RowToAddrOfStructByPos()` that essentially relies on number of fields and therefore cannot handle ambiguity.

**Comment by jackc** [comment]
What about a function `RowTo(AddrOf)StructByNameLax` or `RowTo(AddrOf)StructByNameOptional`  for the skip unknown fields functionality?

Then there's the question of should which mismatches should be allowed. There is struct field exists but query result doesn't and there is query result exists and struct field doesn't.

IMO, struct field exists but query result doesn't would be allowed, as that is the expected optional behavior, but a query result without a corresponding struct field should be an error.

**Comment by DmitriyVTitov** [comment]
> IMO, struct field exists but query result doesn't would be allowed, as that is the expected optional behavior, but a query result without a corresponding struct field should be an error.

That is what I would expect too. Every query result must have corresponding struct field but not otherwise.

**Comment by jackc** [comment]
👍 on the new function then (probably not something I will personally implement any time soon though.)

**Comment by hiendaovinh** [comment]
> What about a function RowTo(AddrOf)StructByNameLax or RowTo(AddrOf)StructByNameOptional for the skip unknown fields functionality?

Would love to see this shipped soon
