### ISSUE TITLE
Ability to run meta or backslash commands

### ISSUE THREAD

**Issue by sumanthkumarc** [jackc/pgx#1516]
**Is your feature request related to a problem? Please describe.**
It would be great if we can run postgres meta commands using pgx. like \d+  or \l etc

**Describe the solution you'd like**
User should be able to pass in "\d+ <TABLE_NAME>" as query and should be able to get the output text for the backslash command.

**Describe alternatives you've considered**
Tried running this as query and gives out SQL error.

```
ERROR: syntax error at or near "\" (SQLSTATE 42601)
```

**Additional context**
FWIW, the https://github.com/xo/usql project does this using multiple individual queries.

**Comment by jackc** [comment]
Sorry, I think that's a bit out of scope for this project. Even in the PostgreSQL project itself, that logic is in `psql` (a CLI client) not `libpq` (a C driver library). pgx is a Go analog to `libpq`.
