### ISSUE TITLE
package net/netip is not in GOROOT error while building

### ISSUE THREAD

**Issue by chaithanya-hr-apna** [jackc/pgx#1518]
Getting this error while trying to run the below command in our Jenkins pipeline:
```GOBIN=`pwd`/bin GONOSUMDB="<module>" GO111MODULE=on GOSUMDB=off GOPROXY=direct GOPRIVATE="<module>" bash -c 'go install -v'```

error:
`../../go/pkg/mod/github.com/jackc/pgx/v5@v5.1.1/pgtype/builtin_wrappers.go:9:2: package net/netip is not in GOROOT`

We are using casbin-psql-watcher (https://github.com/IguteChung/casbin-psql-watcher) in our code which uses `"github.com/jackc/pgx/v5/pgxpool"`

We are using go version 1.17.10

**Comment by ubiuser** [comment]
I ran into this on our GitLab pipeline:
`/go/pkg/mod/github.com/jackc/pgx/v5@v5.3.0/pgtype/builtin_wrappers.go:9:2: package net/netip is not in GOROOT (/usr/local/go/src/net/netip)`
We're on Go 1.20.

**Comment by jackc** [comment]
The earliest version of pgx/v5 requires Go 1.18+. The latest version requires Go 1.19+.

**Comment by chaithanya-hr-apna** [comment]
Yes updating to 1.18 fixed the issue. Thanks!
