### ISSUE TITLE
the performance of parallel query

### ISSUE THREAD

**Issue by sasakiyori** [jackc/pgx#1521]
When I do the parallel query with different counts of goroutines, I find the performance gaps of receiving data from pg server.

The bottleneck of performance  may come from IO, pg server, pgx or something else.  I am shame that I don't have a good way to figure it out.😞 (I check the IO w/r by `iostat` but there seems no much pressure on the system...)

Below is an example and its test result. Is the big gap of scan time is normal? What is the bottleneck of performance on it?
If you can give me some methods to figure it out that will be better. Thanks in advance.

```sql
-- table init
create table abc (a int, b text, c int);
insert into abc select a, 'b', 1 from generate_series(1, 60000000) as a;
```

```go
package main

import (
    "context"
    "fmt"
    "time"
    "github.com/jackc/pgx/v5"
)

func main() {
    ctx := context.Background()
    dsn := "host=127.0.0.1 port=5432 user=postgres password=*** sslmode=disable"
    for i := 1; i <= 10; i++ {
        go func(i int) {
            conn, err := pgx.Connect(ctx, dsn)
            if err != nil {
                fmt.Println(err.Error())
                return
            }
            row, err := conn.Query(ctx, "select * from abc")
            if err != nil {
                fmt.Println(err.Error())
                return
            }
            defer row.Close()

            now := time.Now()
            for row.Next() {
            }
            fmt.Println("elapsed", time.Since(now))
        }(i)
    }

    time.Sleep(time.Second * 1000)
}
```

Test Results: (From 1 query to 2 queries, the average scan time increases nearly 3 seconds, it is really normal?)
```
1 query:                 elapsed 40.06s
2 parallel queries:      elapsed 43.28s (avg)
3 parallel queries:      elapsed 57.35s (avg)
4 parallel queries:      elapsed 1m22.20s (avg)
5 parallel queries:      elapsed 1m34.01s (avg)
10 parallel queries:     elapsed 3m16.96s (avg)
```

**Comment by jackc** [comment]
> Test Results: (From 1 query to 2 queries, the average scan time increases nearly 3 seconds, it is really normal?)

Which is less than 10%...

Depending on your computer these results could be expected. For each query you have a goroutine and at least 1 PostgreSQL process (possibly more as modern PostgreSQL may parallelize some queries). So for your 10 query example you have at least 20 concurrent tasks. You probably don't have that many cores.

**Comment by sasakiyori** [comment]
Yes, my computer has only 8 cores, 10 parallel query example may beyond the capacity to process.  

> Depending on your computer these results could be expected. For each query you have a goroutine and at least 1 PostgreSQL process (possibly more as modern PostgreSQL may parallelize some queries). 

The performance of parallel query by go client is surely poor? The example has a large number of rows, it will make the problem more obvious. So what is the better practice if I want to provide a parallel query ability?

**Comment by jackc** [comment]
There's so many things that could be going on. It's impossible to draw any solid conclusions from one test like this. At the very least you would need a baseline to compare it to. For example, write a C program that uses libpq that does the same benchmark (have fun with the multithreading though...). That would presumably give you a best case. Or implement the same benchmark in any other language. Other languages may have different amounts of overhead but it would at least give you something to compare it to.

**Comment by sasakiyori** [comment]
Um it is a good idea to implement the same benchmark in different languages.
Thanks for you advice, it will try it out!

**Comment by sasakiyori** [comment]
I use the [libpqxx](https://github.com/jtv/libpqxx) to benchmark the same scenario in c++(libpqxx 7.7.4, c++17)

Then get the rough result below:
1. specific the column type
```
1 query:                  elapsed 40087ms      
2 parallel queries:       elapsed 42438ms(avg)     6%⬆️
5 parallel queries:       elapsed 69720ms(avg)     72%⬆️
10 parallel queries:      elapsed 165106ms(avg)    312%⬆️
```
2. ignore the column type just get the raw value (I think this matches the example from this issue)
```
1 query:                   elapsed 33179ms
2 parallel queries:        elapsed 36702ms(avg)     10%⬆️
5 parallel queries:        elapsed 68729ms(avg)     107%⬆️
10 parallel queries:       elapsed 130318ms(avg)    292%⬆️
```

The average elapsed time from single query to multiple queries has been increased obviously. And the percentage of increase is similar to the result from go(but the percentage of increase in go is bigger), though every query time is less than the time in go.

So maybe I can consider the performance of parallel query in go is normal(ignore the query efficiency)? I may take the result from `c++` as a baseline to do more researches...

Here is the code:
```c++
#include <iostream>
#include <chrono>
#include <thread>
#include <pqxx/pqxx>

void get_elapsed_time() {
    pqxx::connection c("host=127.0.0.1 port=5432 dbname=postgres user=postgres password=1");
    pqxx::work tx{c};

    auto begin = std::chrono::system_clock::now();

    // specific column type:
    // auto arr = tx.stream<int, std::string_view, int>("select * from abc");
    // for (auto [a, b, c] : arr) {}

    // ignore column type:
    auto st = pqxx::stream_from::query(tx, "select * from abc");
    while (st.read_row() != nullptr) {}

    auto end = std::chrono::system_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - begin).count();
    std::cout << "elapsed(ms) " << elapsed << std::endl;
}

int main() {
    int thread_num = 10;
    std::list<std::thread> list;

    auto begin = std::chrono::system_clock::now();

    for (auto i = 0; i < thread_num; ++i) {
        list.emplace_back(std::thread(get_elapsed_time));
    }
    for (auto &t : list) {
        t.join();
    }

    auto end = std::chrono::system_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - begin).count();
    std::cout << "total elapsed(ms) " << elapsed << std::endl;

    return 0;
}
```
