### ISSUE TITLE
Expose connection string parsing functions

### ISSUE THREAD

**Issue by johnrutherford** [jackc/pgx#1524]
**Is your feature request related to a problem? Please describe.**
I'm working on an internal package for managing multiple connection strings and connection pools. 

As part of this, I need to parse connection strings and modify some of the settings. For example, we want to store a connection string in a config file, but then load the username/password from a secret store. This requires parsing the original connection string and then generating a new connection string with the updated username and password.

It would be nice if the `parseURLSettings()` ([link](https://github.com/jackc/pgx/blob/master/pgconn/config.go#L438)) and `parseDSNSettings()` ([link](https://github.com/jackc/pgx/blob/master/pgconn/config.go#L438)) functions were exposed so they could be used by external code for parsing connection strings. 

**Describe the solution you'd like**
Ideally there would be a public function like this:

```go
func ParseConnectionString(connString string) (map[string]string, error) {
	// connString may be a database URL or a DSN
	if strings.HasPrefix(connString, "postgres://") || strings.HasPrefix(connString, "postgresql://") {
		return parseURLSettings(connString)
	} else {
		return parseDSNSettings(connString)
	}
}
```
Then we need to take the modified settings map and generate a new connection string with the updated values. This could be done with a new `FormatDSN(settings map[string]string) string` function.

**Describe alternatives you've considered**
Obviously we can write parsing functions ourselves, but there is some logic specific to pgx (e.g., renaming the 'dbname' key to 'database'). So it makes sense to re-use existing functions from pgx if possible.

**Comment by jackc** [comment]
https://pkg.go.dev/github.com/jackc/pgx/v5@v5.3.0/pgxpool#ParseConfig and https://pkg.go.dev/github.com/jackc/pgx/v5@v5.3.0/pgxpool#NewWithConfig?
