### ISSUE TITLE
Query not returning error on invalid UUID in where-clause

### ISSUE THREAD

**Issue by jjxxs** [jackc/pgx#1527]
**Describe the bug**
   - I have a table with an uuid-column (postgres-type uuid), e.g. ```id_uuid uuid unique not null default uuid_generate_v4()```. 
   - I query this table with ```any``` like: ```select my_cols from my_table where id_uuid = any ($1)```
   - ```$1``` is a ```[]string``` of uuids which are not validated to be in the correct uuid-format
   - If I manually run a query like this which contains a malformed uuid, e.g. ```select my_cols from my_table where id_uuid = any('{d7cebd72-6b72-458a-b8a3-0a9a2085eacf,not-a-uuid,db56fd07-f320-4f53-afd5-424da490a788}')``` (notice the ```not-a-uuid```) postgres will report an error ```[22P02] ERROR: invalid input syntax for type uuid: "not-a-uuid"```
   - PGX will not report this error and will return an empty result-set even tho the valid uuids might exist

**To Reproduce**
```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

        // my code below
        uuids := []string{"d7cebd72-6b72-458a-b8a3-0a9a2085eacf", "not-a-uuid", "db56fd07-f320-4f53-afd5-424da490a788"}
	var rows pgx.Rows
        if rows, err = conn.Query(context.Background(), `select my_cols from my_table where id_uuid = any( $1 )`, uuids); err == nil {
            // the usual Next() and Scan() here, the first call to Next() will return false, e.g. empty result-set
        }
}
```

**Expected behavior**
The ```Query```-call returns an error, e.g. ```[22P02] ERROR: invalid input syntax for type uuid: "not-a-uuid"```

**Actual behavior**
The ```Query```-call returns no error and the result-set is empty even tho there are valid uuids in the ```[]string```

**Version**
 - Go: ```go1.19.5 windows/amd64```
 - PostgreSQL: ```PostgreSQL 15.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit```
 - pgx: ```github.com/jackc/pgx/v5 v5.2.0```

**Additional context**
_none_

**Comment by jackc** [comment]
Are you checking `rows.Err()` at the end?

**Comment by jjxxs** [comment]
No, I wasn't testing for ```rows.Err()```, this will correctly reveal the error. I'm fairly new to ```pgx```, thanks for pointing this out and creating this great library.
