### ISSUE TITLE
Cannot scan int4range column into pgtype.Int4range

### ISSUE THREAD

**Issue by RoanBrand** [jackc/pgx#1528]
**Describe the bug**
Cannot scan int4range column into pgtype.Int4range

**To Reproduce**

Postgresql table:
```
CREATE TABLE IF NOT EXISTS "nft_clues" (
  "id" BIGSERIAL PRIMARY KEY,
  "nft_range" INT4RANGE CHECK ("nft_range" <@ INT4RANGE(1, 5000, '[]')),
  "clue" TEXT,
  "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  EXCLUDE USING GIST (nft_range WITH &&)
);
```
![image](https://user-images.githubusercontent.com/14920090/221936262-0424880f-b850-4847-b6dd-9d50b1f69435.png)

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

func main() {
	pool, err :=pgxpool.New(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer pool.Close(context.Background())

	rows, err := pool.Query(context.Background(), "select nft_range from nft_clues;")
	if err != nil {
		log.Fatal(err)
	}

	defer rows.Close()
	var testrange pgtype.Int4range

	for rows.Next() {
		err = rows.Scan(&testrange)
		if err != nil {
			log.Fatal(err)
		}

		fmt.Printf("res: %v\n%+v\n", testrange, testrange)
	}
}
```

**Expected behavior**
Succesfully scan into variable and print it out. Expecting to access inner members after scan.

**Actual behavior**
fails with log "can't scan into dest[0]: missing lower bound, instead got: x", where x is the control character 0x02

**Version**
 - Go: `$ go version` -> [e.g. go version go1.18.3 darwin/amd64]
go version go1.20 linux/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> [e.g. PostgreSQL 14.4 on x86_64-apple-darwin21.5.0, compiled by Apple clang version 13.1.6 (clang-1316.0.21.2.5), 64-bit]
PostgreSQL 14.6 (Ubuntu 14.6-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> [e.g. v4.16.1]
github.com/jackc/pgx/v5 v5.3.1
github.com/jackc/pgx/v4 v4.16.1 // indirect

**Additional context**

**Comment by jackc** [comment]
`github.com/jackc/pgtype` is used with pgx v4. In v5 you want `github.com/jackc/pgx/v5/pgtype`.

The new package now has ranges implemented with generics. For your example you should use `pgtype.Range[pgtype.Int4]` or `pgtype.Range[int32]` depending on if your range bounds will ever be `NULL`.

**Comment by RoanBrand** [comment]
Thanks! I was wondering why I still had v4 dependencies. 
Didn't see such an example anywhere. Guess all imports must have v5 added.
