### ISSUE TITLE
Nested transaction question

### ISSUE THREAD

**Issue by KorsakVlad** [jackc/pgx#1533]
Hello! 

I can't figure out with savepoint analogue
Let's imagine we have following situation:

1. create transaction 'tx'
2. insert something using 'tx'
3. create nested transaction 'ntx' (dbSimulatedNestedTx)
4. insert something using 'ntx'
5. commit 'ntx' changes   
6. insert something else using 'tx'
7. and then some error happened so we rollback on 'tx' 

And what I need is only insert from 4th point is applied. 
However I can't implement it so I'm wondering if it's even possible

Thanks in advance for your reply.

**Comment by jackc** [comment]
I don't think that is possible. pgx simulates nested transactions with savepoints. If a savepoint can't do it then pgx can't do it -- and AFAIK what you want can't be done with savepoints.

**Comment by KorsakVlad** [comment]
thanks for quick reply! Appreciate it.
