### ISSUE TITLE
failed to find embedded files of github.com/jackc/pgx/v5/internal/nbconn

### ISSUE THREAD

**Issue by dorian-y** [jackc/pgx#1534]
Hi team,

**Describe the bug**
We are successfully using this dependency since months.
But today we have this error when trying to get the dependency.
Any ideas?
Thanks

```
failed to find embedded files of github.com/jackc/pgx/v5/internal/nbconn: //go:build comment without // +build
```

**To Reproduce**

**Expected behavior**
We expect to be able to get and install the dependency

**Actual behavior**
We have the error described earlier 

**Version**
 - Go: 1.16

**Comment by jackc** [comment]
The earliest version of pgx v5 requires Go 1.18. The current version requires Go 1.19.

**Comment by dorian-y** [comment]
ok thanks for the quick answer

**Comment by dorian-y** [comment]
Hi,
I have moved to `Go 1.19` and I have the same issue described earlier.
Any ideas ?
Thanks

**Comment by drakkan** [comment]
You are still using an old Go compiler. `net/netip` was introduced in Go 1.18, the error above means you are using a version older than 1.18 and not 1.19. Issue this command `go version`
