### ISSUE TITLE
Empty `CommandTag` after `*pgxpool.Pool.Query`

### ISSUE THREAD

**Issue by mhkarimi1383** [jackc/pgx#1536]
**Describe the bug**
I'm using connection pool using `*pgxpool.Pool` but after running `Query` function `rows.CommandTag().String()` is empty

**To Reproduce**

```go
	rows, err := pool.Query(context.Background(), q)
	if err != nil {
		return
	}
	logger.Info(rows.CommandTag().String())
```

for more details checkout [here](https://github.com/mhkarimi1383/pg_pro/blob/main/connection/connection.go#L94)

**Expected behavior**
Accessing raw value of the `CommandTag`

**Actual behavior**
empty result

**Version**
 - Go: `$ go version` -> [go version go1.20.1 linux/amd64]
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> [PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit] (inside docker)
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> [v5.3.0]

**Comment by mhkarimi1383** [comment]
@jackc I'm doing something wrong or there is bug in this library?

**Comment by jackc** [comment]
See https://pkg.go.dev/github.com/jackc/pgx/v5#Rows

```go
	// CommandTag returns the command tag from this query. It is only available after Rows is closed.
	CommandTag() pgconn.CommandTag
```

**Comment by mhkarimi1383** [comment]
I have tried that after closing the rows I will try again...

**Comment by mhkarimi1383** [comment]
@jackc 
I moved that after `rows.Close()` but that's empty again

https://github.com/mhkarimi1383/pg_pro/commit/44817f83c9b59cb6e3a0336557480efb3a0932e0

**Comment by jackc** [comment]
Are you also checking `rows.Err()` after the rows is closed? There will not be a command tag if the server returned an error.

Also, it would be much easier to debug a standalone reproduction case rather than a link into a library.

**Comment by mhkarimi1383** [comment]
Thanks, Worked...
