### ISSUE TITLE
A couple of questions about pgx/stdlib

### ISSUE THREAD

**Issue by achiku** [jackc/pgx#154]
- When `*sql.DB` is created using `stdlib.OpenFromConnPool`, is it true that only one connection is used during its life cycle?
    * `stdlib.Open` checks if `*stdlib.Driver` has `pgx.ConnPool`, and if it does, acqires `*pgx.Conn`. This `*pgx.Conn` is not released until `stdlib.Conn.Close` is called (inside `stdlib.Conn.Close`, `ConnPool.Release` is called and `*pgx.Conn` is returned to `pgx.ConnPool`)
    * I may be wrong at all, so I wrote this piece of test case, but it seems like it uses multiple connections.
    * https://github.com/achiku/sample-golang-pgx-stdlib/blob/master/main_test.go#L302
- Is it possible to add `pgx.ConnPool.Acquire` type of method to `stdlib.Driver` or some other place that returns `*stdlib.Conn`? Since we are trying to use PostgreSQL session level advisory lock throughout the process, it is really helpful if we can acquire and release a connection from the pool, and execute query on the same connection (I know it is possible to keep using the same connection if we start transaction, but need to use normal connection in our case..).

**Comment by jackc** [comment]
The `database/sql` system has its own connection pool which it abstracts / hides from both the application and the underlying driver. It should use as many connections as it wants limited only by the max connections of the underlying pgx pool.

I'm not sure what the implications of handing out a `*stdlib.Conn` directly would be. At the minimum you would lose any behavior provided by the `database/sql` wrapper (but I'm not sure what that would entail). It might be viable, but it would take some careful inspection of `pgx/stdlib` and `database/sql` to check for side effects. Could you use access the underlying pgx pool and acquire a normal `*pgx.Conn` and do your advisory lock stuff there?

```go
if driver, ok := db.Driver().(*stdlib.Driver); ok && driver.Pool != nil {
	conn, err := driver.Pool.Acquire()
	// Do whatever needed with conn...
}

**Comment by achiku** [comment]
@jackc Thank you for your detailed explanations. I'll try `db.Driver().(*stdlib.Driver)`.
