### ISSUE TITLE
remote error: tls: bad record MAC

### ISSUE THREAD

**Issue by nvx** [jackc/pgx#1548]
**Describe the bug**
I've written a little application that does a lot of upserts using pgx via stdlib. It would run fine without issues for hours and hours. Unfortunately of course doing individual `INSERT ... ON CONFLICT ... DO UPDATE ...` style insert statements per row to be inserted is pretty slow. I can't easily use the `COPY` functionality as I need to do an upsert pattern, but I realised I could at least batch the inserts using unnest() and passing an array.

For example:
```
insert into test (id,data) values (unnest('{"some-id","some-id2"}'::text[]),unnest('{"some-data","some-data2"}'::text[])) on conflict (id) do update set data=EXCLUDED.data WHERE test.data!=EXCLUDED.data
```

Strangely though after doing so, after 15 seconds or so of running inserts (with up to 500 rows per insert statement) I'd start to get errors of `remote error: tls: bad record MAC`

The postgres server log would also indicate the same issue:
```
LOG:  SSL error: decryption failed or bad record mac
```

In practice the query is using placeholders instead of literal data. The pattern of the code is as follows:
Across up to 32 goroutines:
* Begin transaction
* INSERT between 100-9000 rows into a single table in batches of 500 (running as many INSERT statements as needed)
* Commit transaction
Each goroutine may be handling data for a different table, there is no overlap in primary keys between goroutines though as the data is already partitioned by table and primary key (the source of the data is coming from Kafka)
Once done for a given batch of data, the process repeats from the start.

One of the specific queries that failed is as follows:
```
INSERT INTO sf (sf_id,s_id,f_id,f_ver_id,data) VALUES (unnest($1::bigint[]),unnest($2::text[]),unnest($3::bigint[]),unnest($4::bigint[]),unnest($5::bytea[])) ON CONFLICT (sf_id) DO UPDATE SET data=EXCLUDED.data,updated=EXCLUDED.updated,s_id=EXCLUDED.s_id,f_id=EXCLUDED.f_id,f_ver_id=EXCLUDED.f_ver_id WHERE sf.data!=EXCLUDED.data
```

In this case sf_id is the primary key. The other tables are similar with one or more primary key columns, a bytea column, an updated column (timestamp with default value), and a few other non-key columns (usually bigints).

In desperation, I tried switching from pgx to lib/pq postgres driver (which required casting the arrays to the pq array types to work), and suddenly the issue went away. This leads me to believe there's a bug somewhere in the pgx driver (although I imagine both pgx and pq are using the Golang tls libraries, so the error is rather confusing to me)

Due to the intermittent nature and the large amount of rows required to be inserted before the issue appears I don't have a simple set of reproduction steps.

**Version**
 - Go: go version go1.20.2 windows/amd64
 - PostgreSQL: PostgreSQL 15.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
 - pgx: v5.3.1

**Additional context**
Note I initially ran into this issue against a PostgreSQL 10 server which as a part of troubleshooting was updated to PostgreSQL 15 and the same issue occurs.

The database DSN is using `sslmode=verify-full` and the server is configured with tls certificates that are trusted by the client.

**Comment by nvx** [comment]
Concurrency appears to be a factor, using 1 or even 2 goroutines the issue doesn't appear even after running for 5 minutes, while running with 4 goroutines I get the crash in under a minute. I can also let the number of goroutines be high but limit the number of database connections (via the database/sql `SetMaxOpenConns` option) to 1 and the issue also disappears (but slowing down considerably though)

Likewise making the insert batch size 1 (still with the unnest() statements, but passing the params as arrays with length of 1 every time) also doesn't crash (although runs much slower - but runs fine even for more total rows than when batching).

Note in my testing environment I've got ~40ms latency between the Go application and the postgres database which may or may not be a factor as well.

Happy to test anything needed to figure out where the issue is occurring.

**Comment by drakkan** [comment]
Hello,

if you update to the development version the 40ms latency should go away. Unfortunately the bad record MAC error will remain.

See #1525 for details

**Comment by nvx** [comment]
> if you update to the development version the 40ms latency should go away.

Sorry if I wasn't clear, the ~40ms is expected latency of the network connection I'm on (as measured by ping to the database server). I hadn't noticed latency in pgx on top of what was expected (although I haven't been looking either).

Will have a look at #1525

**Comment by drakkan** [comment]
#1555 was merged. To try it simply run `go get -u github.com/jackc/pgx/v5@master` from your project root folder

**Comment by nvx** [comment]
Sorry for taking so long to get around to testing this. I just tested current master (`v5.3.2-0.20230325152211-ca022267dbbf` as of writing) and the issue seems to be resolved. Cheers!
