### ISSUE TITLE
how to query with enum array ?

### ISSUE THREAD

**Issue by liweimeng1215** [jackc/pgx#1549]
hello! when i use query with arry of enums, i get an error: ` Query failed. err=failed to encode args[0]: unable to encode []main.Level{"low", "middle"} into text format for unknown type (OID 16408): cannot find encode plan`
first, i create a table of author and level is enum type
```
create table authors
(
    id    bigserial,
    name  text                         not null,
    bio   text,
    age   integer default 18           not null,
    level level   default 'low'::level not null,
    primary key (id)
);
```
then, i use query like this:

```
type Level string

const (
	LevelLow    Level = "low"
	LevelMiddle Level = "middle"
	LevelHigh   Level = "high"
)

func main() {
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, "postgres://postgres:123456@localhost:5432/postgres")
	if err != nil {
		log.Fatalf("init pgx failed. err=%v", err)
	}
	rows, err := conn.Query(ctx, `
SELECT id
FROM authors
WHERE level = ANY ($1::level[])
`, []Level{LevelLow, LevelMiddle})
	if err != nil {
		log.Fatalf("Query failed. err=%v", err)
	}
	defer rows.Close()
	var ids []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			log.Fatalf("scan failed. err=%v", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		log.Fatalf("rows.Err(). err=%v", err)
	}
	fmt.Println(ids)
}
```
Could you tell me how can i use []Level type to query the ids?

**Comment by liweimeng1215** [comment]
thank you, jack. it works

**Comment by viktorvoltaire** [comment]
@jackc can i ask why this is only a problem with pgx?

**Comment by jackc** [comment]
> @jackc can i ask why this is only a problem with pgx?

I do not know what other drivers may be doing, but if I had to guess I would say that they just assume that Go `[]string` matches to PostgreSQL `text[]` and encode it with that assumption. pgx doesn't do that. pgx uses the PostgreSQL type to determine the proper encoding. For example, if `[]string{"foo", "bar", "baz"}` is encoded into a PostgreSQL `text[]` then the proper encoding is `{foo,bar,baz}`. But if the PostgreSQL type is a `json` then the proper encoding is `["foo","bar","baz"]`. pgx does the right thing, but to do the right thing it has to know what the underlying PostgreSQL type is.

**Comment by viktorvoltaire** [comment]
> I do not know what other drivers may be doing, but if I had to guess I would say that they just assume that Go `[]string` matches to PostgreSQL `text[]` and encode it with that assumption. pgx doesn't do that. pgx uses the PostgreSQL type to determine the proper encoding. For example, if `[]string{"foo", "bar", "baz"}` is encoded into a PostgreSQL `text[]` then the proper encoding is `{foo,bar,baz}`. But if the PostgreSQL type is a `json` then the proper encoding is `["foo","bar","baz"]`. pgx does the right thing, but to do the right thing it has to know what the underlying PostgreSQL type is.

@jackc Thank you for the explanation!

**Comment by quinn** [comment]
if i'm using `pgxpool.New` instead of `pgx.Connect` how do I do `LoadType`

**Comment by quinn** [comment]
nevermind, found docs for `config.AfterConnect` i'm good to go 👍

**Comment by talksik** [comment]
this workaround worked for me ` ...rest of query...AND ($2::text[] is NULL or echo_state::text = any($2::text[]))`

**Comment by rainbow-bash** [comment]
example with AfterConnect
```go
// cfg is well, your config
config, err := pgxpool.ParseConfig(cfg)
if err != nil {
	panic(err)
}

config.AfterConnect = func(ctx context.Context, c *pgx.Conn) error {
		types := []string{
			"code_kind",
			"items_kind",
			"measure_unit",
			"presentation",
			"job_position",
			"scope",
			"products_category",
			"permissions_kind",
		}
		for _, ty := range types {
			t, err := c.LoadType(context.Background(), ty)
			if err != nil {
				return err
			}
			c.TypeMap().RegisterType(t)

			t, err = c.LoadType(context.Background(), fmt.Sprintf("_%v", ty))
			if err != nil {
				return err
			}
			c.TypeMap().RegisterType(t)
		}
		return nil
}

conn, err := pgxpool.NewWithConfig(context.Background(), config)

// ... rest fo your code 
```
