### ISSUE TITLE
Example parsing a record

### ISSUE THREAD

**Issue by RHavar** [jackc/pgx#155]
Hey, I love your library!

Would you be able to provide an example with parsing the values out of:

```sql
SELECT ROW(1, 'CAT', NOW())
```

I've been trying to implement a Scanner for it, but struggling quite a bit with it. I would appreciate any pointers on this. 

Thanks!

**Comment by jackc** [comment]
What are you trying to parse the row into? `[]interface{}` or arbitrary `struct`. Parsing a totally generic row structure could be _interesting_. Parsing a specific row structure would be easier.

Also important is whether you want to parse the text format or the binary format. A trick is that the format is set at the column level so the parser would need to understand the binary format or text format for _all_ the types in the row value.

In theory the binary format would be easier. I experimented a bit with the binary representation and this is the binary representation of your sample row value:

```
[0 0 0 3 0 0 0 23 0 0 0 4 0 0 0 1 0 0 2 193 0 0 0 3 67 65 84 0 0 4 160 0 0 0 8 0 1 216 79 99 113 178 114]
```
It looks like the binary row format is:

number of values in row - 4 bytes
Then for each value:
oid (value type) - 4 bytes
size - 4 bytes
data

So you can see the value has oid 23 (integer), a size of 4 bytes, and the value of 1.

In theory, we should be able to reuse the existing parsing logic, but I might need to make public a new interface to expose that low-level code for reuse.

**Comment by RHavar** [comment]
I think it would be amazing if pgx could (out of the box) support parsing a Record into a  `[]interface{}` and then from there, I could easily do the rest.

**Comment by jackc** [comment]
I added basic record decoding into a `[]interface{}`. It should handle simple / core types, but won't handle complex types like arrays, nested records, or custom types.

**Comment by RHavar** [comment]
Looks great, thanks for doing that!
