### ISSUE TITLE
The copy from function runs incorrectly on some machines

### ISSUE THREAD

**Issue by linlexing** [jackc/pgx#1552]
Some computers running the same version of the Windows operating system will prompt a 22P04 error when running copyfrom, indicating that the number of data fields received is not the number in the table, and the number of error fields prompted is different each time. Bad computers always go wrong, and good computers always work.
Spent a lot of time testing each version and found that version 898891a6eea762a65bb94b383fb9424ebbcc9d88 caused the problem.
It was found that the computer with the problem, with the earlier version, can run the copyfrom function, but the execution speed is obviously slower than normal. The submitted code is about time control. It is guessed that the death line time is too short, and the network data is not transmitted completely.

copy from source code:

```go
		conn, err := t.db.Conn(context.Background())
		if err != nil {
			return err
		}
		defer conn.Close()
		if err := conn.Raw(func(driverConn interface{}) error {
			pgxConn := driverConn.(*stdlib.Conn).Conn() // conn is a *pgx.Conn
			cnt, err := pgxConn.CopyFrom(context.Background(), pgx.Identifier{strings.ToLower(tabName)},
				cols, pgx.CopyFromRows(t.cacheRows))
			if err != nil {
				// saveErrorData()
				return err
			}
			if cnt != int64(len(t.cacheRows)) {
				return fmt.Errorf("copy from %d rec,but success %d rec", len(t.cacheRows), cnt)
			}
			return nil
		}); err != nil {
			return err
		}
```
**Version**
 - windows:windows2012 server r2 (6.3.9600)
 - Go: go1.20.2 windows/amd64
 - PostgreSQL: postgresql-15.1-1-windows-x64
 - pgx: 898891a6eea762a65bb94b383fb9424ebbcc9d88

**Comment by jackc** [comment]
Try the master branch. That has true non-blocking IO on Windows instead of the fake non-blocking IO in previous versions.

That said, I really can't figure how 898891a could cause the error you are receiving. A timeout or a deadlock perhaps, but that error implies a corrupted data stream.

**Comment by linlexing** [comment]
In this version c09ddaf4408eabc36322c8696cd93a646e93e976 , the first database operation hangs and does not respond.

**Comment by linlexing** [comment]
In this version c09ddaf4408eabc36322c8696cd93a646e93e976, the first database operation hangs and does not respond.
In this version 9ae852eb583d2dced83b1d2ffe1c8803dda2c92e(last master), the copy from operation hangs and does not respond.

**Comment by jackc** [comment]
@linlexing We may have found the issue in the discussion for #1525. No resolution yet though.

**Comment by codercms** [comment]
@linlexing could you try this PR - https://github.com/jackc/pgx/pull/1555 ?
Does it fix your problem?

**Comment by linlexing** [comment]
Yeah, it looks like it's fixed.
