### ISSUE TITLE
After migration from v4 to v5 errors began to appear frequently - ERROR: prepared statement "stmtcache_XXX" does not exist (SQLSTATE 26000)

### ISSUE THREAD

**Issue by nobuenhombre** [jackc/pgx#1561]
**Describe the bug**
After migration from v4 to v5 errors began to appear frequently - ERROR: prepared statement "stmtcache_XXX" does not exist (SQLSTATE 26000)

**To Reproduce**
the error appears randomly on different SQL queries

**Expected behavior**
SQL queries are executed stably without errors

**Actual behavior**
errors began to appear frequently - ERROR: prepared statement "stmtcache_XXX" does not exist (SQLSTATE 26000)
the error appears randomly on different SQL queries

**Version**
 - Go: `$ go version` -> [go version go1.20.1 linux/amd64]
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> [PostgreSQL 14.4 on x86_64-pc-linux-gnu, compiled by Debian clang version 12.0.1, 64-bit]
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> [github.com/jackc/pgx/v5 v5.3.1]

**Comment by nobuenhombre** [comment]
I found solution.

for pgbouncer

```
if externalConnectionPool {
	config.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol
}

connectPool, err := pgxpool.NewWithConfig(context.Background(), config)
if err != nil {
	return nil, err
}
```

**Comment by mattjohnsonpint** [comment]
Just a note for anyone that lands here while investigating using pgx with Supabase - you can switch to "session mode" or "direct connection mode" without adjusting pgx.

ie., `pgx.QueryExecModeSimpleProtocol` aligns with Supabase's "transaction mode".

https://supabase.com/docs/guides/database/connecting-to-postgres#choosing-a-connection-method
