### ISSUE TITLE
scanning Daterange fails

### ISSUE THREAD

**Issue by ernest-ag5** [jackc/pgx#1562]
**Describe the bug**
Upgrading from v4 to v5,  we found a problem with scanning Daterange values which now reports an error.

**To Reproduce**

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
         "github.com/jackc/pgtype"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

         row := conn.QueryRow(context.Background(), "select '[-infinity,infinity)'::daterange")
	var dr pgtype.Daterange
	log.Println(row.Scan(&dr))
}
```

**Expected behavior**
The variable dr is populated with the current Daterange value.

**Actual behavior**
It fails with the message:

    can't scan into dest[0]: missing lower bound, instead got: 

**Version**
 - Go:  1.20.2
 - PostgreSQL: AWS Aurora PostgreSQL engine 14.6
 - pgx: github.com/jackc/pgx/v5 v5.3.1
 - pgtype: github.com/jackc/pgtype v1.14.0

**Additional context**
This **is working** with github.com/jackc/pgx/v4 v4.17.2 and github.com/jackc/pgtype v1.13.0

A break down when debugging:

in the database column:

	[-infinity,infinity)

when scanning the value from that row:

	var dr pgtype.Daterange
	log.Println(row.Scan(&dr))

the pgx pkg eventually calls:	

	func (dst *Daterange) Scan(src interface{}) error

with value for src:

	interface {}([]uint8) [2,0,0,0,4,128,0,0,0,0,0,0,4,127,255,255,255]

and later calls:

	ParseUntypedTextRange(string(src))

with value for string(src):

	"\x02\x00\x00\x00\x04\x80\x00\x00\x00\x00\x00\x00\x04\x7f\xff\xff\xff"

which fails because it does not start with  ( or [

**Comment by ernest-ag5** [comment]
I believe to have found a fix for this issue.

In pgtype 1.14 package, `datarange.go:258` it calls `DecodeText` with srcCopy but when I change it to `DecodeBinary`
```
	return dst.DecodeBinary(nil, srcCopy)
```
then the scanning works as expected for the given example code.

Happy to create a PR for this, let me know.

**Comment by jackc** [comment]
The core issue is mixing v4 and v5 libraries. `github.com/jackc/pgtype` is used with pgx v4. In v5 `github.com/jackc/pgx/v5/pgtype` should be used instead. (It will usually work through database/sql compatibility but that has worse performance and there are sometimes issues with `string` vs `[]byte` which is possibly what you are running into).

In v5, range support is handled with generics so the v5 equivalent would be `pgtype.Range[pgtype.Date]`.

**Comment by ernest-ag5** [comment]
I just confirmed that using `github.com/jackc/pgx/v5/pgtype` is working for my issue. Let's close this
