### ISSUE TITLE
Possible Addition to 3rd Party Libraries with PGX Support

### ISSUE THREAD

**Issue by VinGarcia** [jackc/pgx#1568]
Hello, I have created this project called [KSQL][ksql] meaning "Keep it simple SQL client" which is an SQL data mapper that I wrote to be:

1. Easy to use and learn (it has basically 8 public functions, and this was a design goal)
2. Hard to make mistakes
3. Easy to test
4. As efficient as possible
5. And expressive, i.e. you can do anything with it since it just accepts pure SQL on most functions.

[ksql]: https://github.com/vingarcia/ksql

It has a very good test coverage and instead of implementing the communication with many different database technologies, I rely on using existing drivers such as PGX on the backend. Currently, I have one adapter for pgx4, another for pgx5, and others for MySQL, SQLServer and SQLite.

So to the point: since I am trying to make this project more popular and I noticed you do have a section for 3rd party libraries that integrate with PGX I was wondering if it would be ok for me to create a PR adding KSQL to that list.

If you don't think KSQL is a good candidate it is 100% ok, and thanks for your attention =].

Regards, Vinícius Garcia.

**Comment by jackc** [comment]
Sure, go ahead. 👍
