### ISSUE TITLE
Cannot scan NULL into pointer to struct

### ISSUE THREAD

**Issue by acim** [jackc/pgx#1569]
**Describe the bug**
I have the following code (actually, this is just extraction of the pieces):

```
type Settings struct {
  DisableWelcomeDialog bool json:"disableWelcomeDialog"
}

q := "SELECT settings FROM users WHERE id=$1"
row := r.db.QueryRow(ctx, q, userID)

var settings Settings

if err := row.Scan(&settings); err != nil {
  return nil, fmt.Errorf("scan: %w", err)
}
```

This throws an error "cannon scan NULL into *Settings" and should actually just return nil value for the pointer.

**Expected behavior**
Scan should work as pointers are nillable.

**Actual behavior**
Throws an error.

**Version**
 - Go: 1.20.3
 - PostgreSQL: 1.15 latest
 - pgx: v5 latest

**Comment by jackc** [comment]
I think you would need to scan a pointer to a pointer instead of a pointer.
