### ISSUE TITLE
quote escape needed?

### ISSUE THREAD

**Issue by emicklei** [jackc/pgx#157]
I was surpised to see that I needed to escape single quotes from string parameters when using prepared statements with bounded parameters.

In the example below, I apply such a modification to the errmsg value.
```
conn.Prepare("MessageProcessResult", "select set_message_process_result($1,$2,$3,$4,$5);")
w := common.NewStopwatch(metric)
row := conn.QueryRow("MessageProcessResult",
		queue,
		rowId,
		receiptHandle,
		errcode,
		strings.Replace(errmsg, "'", "''", -1)) // TODO this should not be needed ?
```

**Comment by jackc** [comment]
That should not be necessary. What happens if you don't do it?

**Comment by emicklei** [comment]
Solved. For our issue , we had an errmsg with the following value:

``` xml document has invalid value for 'name' ```

obviously, *set_message_process_result* is a stored function that takes a varchar parameter for $5

```n.a. - syntax error at or near "name"(42601)```

But that stored function uses dynamic sql to compose the select query and had the following line

```
                     ,      priority
                     ,      '''||p_errmsg||'''
                     ,      current_timestamp
```
This was causing the SQL error to appear.

We have changed that definition to take care of the escaping ( and removed the Replace call in Go)
