### ISSUE TITLE
`RowToStructByName` row collection with pointer to slice of structs error

### ISSUE THREAD

**Issue by danicc097** [jackc/pgx#1570]
**Describe the bug**
`RowToStructByName` doesn't seem to support scanning to a pointer to a slice of structs

**To Reproduce**
```go
	type Team struct {
		TeamID int    `json:"teamID" db:"team_id"`
		Name   string `json:"team" db:"team"`
	}
	type User struct {
		UserID  int       `json:"userID" db:"user_id"`
		Name    string    `json:"name" db:"name"`
		Teams   []Team    `json:"teams" db:"teams"`
		Strings *[]string `json:"strings" db:"strings"`
	}

	query := `
	WITH user_team AS (
		SELECT 1 AS user_id, 1 AS team_id
		UNION ALL
		SELECT 1 AS user_id, 2 AS team_id
	), users AS (
		SELECT 1 AS user_id, 'John Doe' AS name
	),teams AS (
		SELECT 1 AS team_id, 'team 1' AS name
		UNION ALL
		SELECT 2 AS team_id, 'team 2' AS name
	)
	SELECT users.user_id
	,joined_teams.teams as teams
	, string_to_array('a b c', ' ')::text[] as strings
	FROM users
	left join (
		select
			user_team.user_id as teams_user_id
			, array_agg(teams.*) as teams
			from user_team
			join teams using (team_id)
			group by teams_user_id
		) as joined_teams on joined_teams.teams_user_id = users.user_id
	`
	rows, _ := pool.Query(context.Background(), query)
	users, err := pgx.CollectRows(rows, pgx.RowToStructByNameLax[User])

```

returns `{"userID":1,"name":"","teams":[{"teamID":1,"team":"team 1"},{"teamID":2,"team":"team 2"}]}`.

However, using `*[]Team` or `*[]*Team` leads to `can't scan into dest[1]: cannot scan _record (OID 2287) in binary format into **[]main.Team or (**[]*main.Team)`. 

My use case is distinguishing nil from empty slice (table was not joined vs no rows) so I can work around this issue with an extra private field, but I was wondering if I'm missing something with the new syntax or need `pgtype`, etc. 

**Version**
 - Go: go version go1.19.1 linux/amd64
 - PostgreSQL: 13
 - pgx: v5 latest master

**Comment by jackc** [comment]
Try 847f888631e7356f88766bcb4986afd3c4b8fd76. The problem was in code that handled pointer to pointer to slice of struct scanning. It could happen in a regular scan, not just with `RowToStructByName`. But I think it should be fixed everywhere now.

**Comment by danicc097** [comment]
Working perfectly now, thanks a lot Jack
