### ISSUE TITLE
Acquiring connections deadlock at high parallelism

### ISSUE THREAD

**Issue by torkelrogstad** [jackc/pgx#1577]
**Describe the bug**
I'm seeing deadlocks in Puddle when acquiring connections from connection pools, specifically when running database queries through transactions. These occur when running at very high levels of parallelism (I think). I'm getting them pretty consistently when running a very high parallelism count on a moderately large test suite for a moderately large application (43k lines of Go, most-ish code is tested, most-ish code uses a database). This does _not_ trigger when running a standard `go test` on my M2 Macbook Pro. It does trigger rather often on CI (GitHub Actions), and it happens approx 20% of the time when I do `go test -count=1 -parallel 100_00`.

**To Reproduce**
I've sadly not been able to provide a reproduction I can share with you. I've tried creating a simple Go project, but not been able to get the bug to trigger. However, I can share a slightly edited stack dump from when my tests time out. https://gist.github.com/torkelrogstad/67b4e6bccc3ca69a8cafc1725e3d8cdd

**Expected behavior**
I expect pgx to be able to acquire connections.

**Actual behavior**
It seems like connection acquiring is somehow deadlocked. 

**Version**
 - Go: `$ go version` -> go version go1.20.1 darwin/arm64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` ->  PostgreSQL 14.7 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` ->         github.com/jackc/pgx/v5 v5.3.1

**Comment by jackc** [comment]
Is this code running multiple pools at the same time? I noticed that there are 4 `backgroundHealthCheck` in progress. The only way that should be possible is if there are multiple pools.

**Comment by torkelrogstad** [comment]
Yes. Is that a problem? Most tests connect to the same pool, but some tests create a brand new pool.

**Comment by jackc** [comment]
Multiple pools are fine if it is on purpose. I just wanted to ensure that it wasn't inadvertent, and something related to that was causing a problem.

It is very surprising though, that multiple pools would deadlock at the same time. Makes me wonder if maybe the underlying PostgreSQL server is out of connections or blocked somehow. Might be worth checking `pg_stat_activity` while the test is running and while it is blocked.

Also, the `pgxpool.Pool` type has a number stats available. Might be informative to monitor those while the test is running to see if there is a gradual exhaustion of resources or if it is sudden.

**Comment by jackc** [comment]
The "idle in transaction" states are a strong sign that the transactions are not being committed or rolled back in your Go code. Especially the "idle in transaction (aborted)" state. This implies that a SQL error occurred in the transaction. It would appear there is a `Begin` or a `BeginTx` call that does not have a corresponding `Rollback` when a query in that `Tx` encounters an error. Presumably, the query from `pg_stat_activity` would be a good place to start looking.

**Comment by torkelrogstad** [comment]
With the pointers you gave, I was able to figure this issue out. It wasn't an issue with pgx, but rather an issue with my Go code (of course!). If you're interested: I had a function where I opened a transaction, immediately deferred a rollback _(which was why I was certain I was rolling back all my open transactions)_, but I had a branch where I recursed into the function again, where a new transaction was opened. In this case a new transaction (and thereby a new connection) was created _before_ the deferred rollback executed. 

Thanks a lot for helping me figure this out. Sorry for taking up your time with an issue that is not related to pgx. pgx is a really great tool, and you're incredibly helpful to lots of people using your library. I appreciate that a lot!

**Comment by SavostinVladimir** [comment]
@jackc hi! I have the same issue, but the question is there any idiomatic way to detect such a behavior? I mean when I acquire conn through pool.Begin but then while this transaction I call pool.Exec (or something else, which lead to acquiring a new conn, instead of reusing the existing one in my transaction) before I commit/rollback the first one. If pool is busy it may cause the my initial transaction hangs because my code waits for a new conn. 

I've looked at BeforeAcuire and AfterRelease callbacks. The only solution I see is that I pass my transaction to context and then check if I already have conn, when try to Acuire new one

**Comment by jackc** [comment]
@SavostinVladimir There's no guaranteed way to prevent or detect this type behavior, but one approach I have used is to use `pgx.BeginTx` and purposely shadow the pool variable. For example:

```go
func DoAThing(ctx context.Context, db *pgxpool.Pool) error {
	return pgx.BeginFunc(ctx, db, func(db pgx.Tx) error {
		// Code here cannot reference the pool because the outside variable is shadowed.
	}
}
```

**Comment by bartlomiejswiecki-sonatus** [comment]
@jackc hi! Sorry to bring this up again but it looks like I can see similar issue in the project I'm working on ATM, the code explicitly only uses `BeginFunc` to avoid unmatched `Rollback`.

So the `ctx` passed to BeginFunc is used both to `BeginTx` and then `Rollback` in case things are not right. But what would happen if the context is cancelled while executing the inner function, e.g. if it took too much time? The `Rollback` call would in such case be executed with cancelled context as well. Wouldn't that mean that we'd end up with a connection without a closed transaction?

**Comment by jackc** [comment]
@bartlomiejswiecki-sonatus 

If the rollback fails the connection would be closed. See below:

https://github.com/jackc/pgx/blob/c911d86cff0f106829d1b209286f4d151347f986/tx.go#L209-L223
