### ISSUE TITLE
Problem with providing boolean values in different types as query parameters

### ISSUE THREAD

**Issue by lzakharov** [jackc/pgx#1580]
**Describe the bug**

I've faced with a problem of using `[]int64` parameters for Postgres boolean arrays (`OID 1000`) since pgx started using binary format for arrays (1f43e2e49077df1fe8aa7f8b21e3393d0980b219).

**To Reproduce**

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
	"github.com/lib/pq"
)

const prepare = `
CREATE TEMPORARY TABLE users (
	name TEXT PRIMARY KEY,
	is_active BOOLEAN NOT NULL
);

INSERT INTO users (name, is_active)
VALUES 
	('alice', true),
	('bob', false),
	('carol', true);
`

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

	if _, err = conn.Exec(ctx, prepare); err != nil {
		log.Fatal(err)
	}

	// args := []int64{1, 0} // unable to encode []int64{1, 0} into binary format for _bool (OID 1000): cannot find encode plan
	args := pq.Array([]int64{1, 0}) // interpreted as {false,false}
	// args := pq.Array([]string{"1", "0"}) // interpreted as {false,false}
        // args := []string{"yes", "no"} // ok
	// args := []string{"y", "n"} // ok
	// args := pq.Array([]string{"y", "n"}) // interpreted as {false,false}
	// args := pq.Array([]string{"yes", "no"}) // ok

	rows, err := conn.Query(ctx, "SELECT name FROM users WHERE is_active = ANY($1)", args)
	if err != nil {
		log.Fatal(err)
	}

	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			log.Fatal(err)
		}
		fmt.Println(name)
	}
}
```

**Expected behavior**

Expects that pgx translates values into Postgres format as it documented [here](https://www.postgresql.org/docs/11/datatype-boolean.html) and program prints three strings (`alice`, `bob`, `carol`) for each of `args := ...` line.

**Actual behavior**

Program prints only one string (`bob`) or fails as described in comments.

**Version**

 - Go: `go version go1.20.3 darwin/arm64`
 - PostgreSQL: `PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`
 - pgx: `5.3.1`
 
**Additional context**
Possible solution #1579.

**Comment by jackc** [comment]
Is there some reason not to use a `[]bool` directly? I'm not sure I would expect a `[]int64` to be automatically translated to `[]bool`.

**Comment by lzakharov** [comment]
Agree, it's better to use `[]bool`, and I would do just that. But I found such a case in the project and spend a lot of time looking for the problem (lucky that this logic was covered by tests). 

IMHO there are two options:
* return error in all such cases (as it works for `[]int{1, 0}`)
* convert types as it mentioned in docs

I prefer the second one cause it doesn't breaks backward compatibility and allowed in Postgres.

**Comment by jackc** [comment]
> return error in all such cases (as it works for []int{1, 0})

I'm surprised that works. But it's really hard to reason about some of these cases. In most working encodings of Go to PostgreSQL types there is no code that directly handles the encoding. pgx recursively tries a list of strategies such as dereference pointer, find underlying simple type, etc. until it finds a sequence of steps that can successfully encode the Go value. 

In this case it appears that the path is encode to the text format because that's all we can do with a database/sql `Valuer`, then scan it into the exactly matching Go type, then encode it back into the binary wire format. Unfortunately, just a bit convoluted...

Oh, well though. 🤷‍♂️ I merged your related PR.

**Comment by lzakharov** [comment]
Agree, and that's why I personally would prefer to use concrete types. Thanks for the quick response!
