### ISSUE TITLE
Update Wiki Error Handling

### ISSUE THREAD

**Issue by jimtsao** [jackc/pgx#1594]
The [Error Handling](https://github.com/jackc/pgx/wiki/Error-Handling) wiki page

The error handling code didn't work for me (errors.As was not returning true) and I spent some time trying to figure out what I did wrong.
Turns out there was an accidental import from
- `github.com/jackc/pgconn`, instead of
- `github.com/jackc/pgx/v5/pgconn`

If you search google you can find other people reporting similar issues.

Suggesting to add a little caveat at the end of wiki about using the right import path.

**Comment by jackc** [comment]
Thanks. I added the import to the example code with a comment explaining the reason.
