### ISSUE TITLE
Query is not logged correctly when using stdlib

### ISSUE THREAD

**Issue by krzysztofdrys** [jackc/pgx#160]
We are  using pgx wrapped using stdlib. Today I was trying to use pgx logger, especially as we are using `log15` anyway. We are seing logs like:
```
Query                                           sql="" args=[2016-06-23 09:31:23.969838693 +0000 UTC] time=3.706889ms rowCount=169 pid=27144
```
As you can see, `sql` parameter is empty. 

I think this is a bug. And here is my attempt to fix it: https://github.com/jackc/pgx/pull/159

As you can see, the solution is prety simple: populate `rows.sql` with query from prepared statement instead of one passed as an argument. 

I was also considering:
```
if rows.sql == "" {
   rows.sql = ps.SQL
}
```

Which one do you like better? Anyway, can you help me in merging this PR?

**Comment by jackc** [comment]
Merged. Thanks!
