### ISSUE TITLE
Problem with nbconn.NetConn

### ISSUE THREAD

**Issue by mhkarimi1383** [jackc/pgx#1605]
I know that this problem is not fully related to this project, but I need help with my problem

```go
func GetRawConnection() (net.Conn, error) {
	conn, err := writePools[rand.Intn(len(writePools))].Acquire(context.Background())
	if err != nil {
		return nil, err
	}
	return conn.Conn().PgConn().Conn(), nil
}
```

and use it as a normal `TCPConn` but I'm getting following error

```
panic: interface conversion: net.Conn is *nbconn.NetConn, not *net.TCPConn
```

Also I cannot use `nbconn.NetConn` since it's in internal module also conn property is not public

here is my code that is code that uses `GetRawConnection`

```go
func handleClient(cliConn *net.TCPConn) {
	defer cliConn.Close()

	serverConn, err := connection.GetRawConnection()
	if err != nil {
		log.Printf("Failed to connect to server: %s", err)
		return
	}
	defer serverConn.Close()
	fmt.Printf("Type of cliConn: %T\n", cliConn)
	fmt.Printf("Type of serverConn: %T\n", serverConn)
	// Proxy(serverConn.(*net.TCPConn), cliConn)
	Proxy(serverConn.(*net.TCPConn), cliConn)
}

func Proxy(srvConn, cliConn *net.TCPConn) {
	serverClosed := make(chan struct{}, 1)
	clientClosed := make(chan struct{}, 1)
	// backend := pgproto3.NewBackend(cliConn, cliConn)

	// startupMsg, err := backend.ReceiveStartupMessage()
	// if err != nil {
	// 	log.Fatal(err)
	// }
	// backend.SetAuthType(pgproto3.AuthTypeMD5Password)

	// switch startupMsg.(type) {
	// case *pgproto3.StartupMessage:
	//	_, err := cliConn.Write((&pgproto3.AuthenticationMD5Password{
	//		Salt: types.MD5AuthSalt,
	//	}).Encode(nil))
	//	if err != nil {
	//		log.Fatal(err)
	//	}
	//}

	go broker(srvConn, cliConn, clientClosed)
	go broker(cliConn, srvConn, serverClosed)

	var waitFor chan struct{}
	select {
	case <-clientClosed:
		srvConn.SetLinger(0)
		srvConn.CloseRead()
		waitFor = serverClosed
	case <-serverClosed:
		cliConn.CloseRead()
		waitFor = clientClosed
	}

	<-waitFor
}

func broker(dst, src net.Conn, srcClosed chan struct{}) {
	_, err := copyBuffer(dst, src, nil)
	if err != nil {
		log.Printf("Copy error: %s", err)
	}
	if err := src.Close(); err != nil {
		log.Printf("Close error: %s", err)
	}
	srcClosed <- struct{}{}
}
```

Thanks

**Comment by jackc** [comment]
I'm not sure exactly what you're trying to but at the very least directly using the underlying `net.TCPConn` is going to be tricky. For one thing it might be `net.UnixConn`, and if it is a `net.TCPConn` then it might have a `tls.Conn` wrapping it.

But regardless, I think what you can do is to set a custom `DialFunc` on https://pkg.go.dev/github.com/jackc/pgx/v5@v5.3.1/pgconn#Config. You'd need to save the reference somewhere and map it back to the `pgx.Conn` that was ultimately created. A little messy, but it should be possible.

**Comment by mhkarimi1383** [comment]
Thanks I will check it out
but that `copyBuffer` is the same as `io.Copy`

**Comment by mhkarimi1383** [comment]
I need this for my https://github.com/mhkarimi1383/pg_pro project

**Comment by hothanhloc68** [comment]
}

func Proxy(srvConn, cliConn *net.TCPConn) {
	serverClosed := make(chan struct{}, 1)
	clientClosed := make(chan struct{}, 1)
	// backend := pgproto3.NewBackend(cliConn, cliConn)

	// startupMsg, err := backend.ReceiveStartupMessage()
	// if err != nil {
	// 	log.Fatal(err)
	// }
	// backend.SetAuthType(pgproto3.AuthTypeMD5Password)

	// switch startupMsg.(type) {
	// case *pgproto3.StartupMessage:
	//	_, err := cliConn.Write((&pgproto3.AuthenticationMD5Password{
	//		Salt: types.MD5AuthSalt,
	//	}).Encode(nil))
	//	if err != nil {
	//		log.Fatal(err)
	//	}
	//}

	go broker(srvConn, cliConn, clientClosed)
	go broker(cliConn, srvConn, serverClosed)

	var waitFor chan struct{}
	select {
	case <-clientClosed:
		srvConn.SetLinger(0)
		srvConn.CloseRead()
		waitFor = serverClosed
	case <-serverClosed:
		cliConn.CloseRead()
		waitFor = clientClosed
	}

	<-waitFor
}

func broker(dst, src net.Conn, srcClosed chan struct{}) {
	_, err := copyBuffer(dst, src, nil)
	if err != nil {
		log.Printf("Copy error: %s", err)
	}
	if err := src.Close(); err != nil {
		log.Printf("Close error: %s", err)
	}
	srcClosed <- struct{}{}

**Comment by hothanhloc68** [comment]
> I know that this problem is not fully related to this project, but I need help with my problem
> 
> ```go
> func GetRawConnection() (net.Conn, error) {
> 	conn, err := writePools[rand.Intn(len(writePools))].Acquire(context.Background())
> 	if err != nil {
> 		return nil, err
> 	}
> 	return conn.Conn().PgConn().Conn(), nil
> }
> ```
> 
> and use it as a normal `TCPConn` but I'm getting following error
> 
> ```
> panic: interface conversion: net.Conn is *nbconn.NetConn, not *net.TCPConn
> ```
> 
> Also I cannot use `nbconn.NetConn` since it's in internal module also conn property is not public
> 
> here is my code that is code that uses `GetRawConnection`
> 
> ```go
> func handleClient(cliConn *net.TCPConn) {
> 	defer cliConn.Close()
> 
> 	serverConn, err := connection.GetRawConnection()
> 	if err != nil {
> 		log.Printf("Failed to connect to server: %s", err)
> 		return
> 	}
> 	defer serverConn.Close()
> 	fmt.Printf("Type of cliConn: %T\n", cliConn)
> 	fmt.Printf("Type of serverConn: %T\n", serverConn)
> 	// Proxy(serverConn.(*net.TCPConn), cliConn)
> 	Proxy(serverConn.(*net.TCPConn), cliConn)
> }
> 
> func Proxy(srvConn, cliConn *net.TCPConn) {
> 	serverClosed := make(chan struct{}, 1)
> 	clientClosed := make(chan struct{}, 1)
> 	// backend := pgproto3.NewBackend(cliConn, cliConn)
> 
> 	// startupMsg, err := backend.ReceiveStartupMessage()
> 	// if err != nil {
> 	// 	log.Fatal(err)
> 	// }
> 	// backend.SetAuthType(pgproto3.AuthTypeMD5Password)
> 
> 	// switch startupMsg.(type) {
> 	// case *pgproto3.StartupMessage:
> 	//	_, err := cliConn.Write((&pgproto3.AuthenticationMD5Password{
> 	//		Salt: types.MD5AuthSalt,
> 	//	}).Encode(nil))
> 	//	if err != nil {
> 	//		log.Fatal(err)
> 	//	}
> 	//}
> 
> 	go broker(srvConn, cliConn, clientClosed)
> 	go broker(cliConn, srvConn, serverClosed)
> 
> 	var waitFor chan struct{}
> 	select {
> 	case <-clientClosed:
> 		srvConn.SetLinger(0)
> 		srvConn.CloseRead()
> 		waitFor = serverClosed
> 	case <-serverClosed:
> 		cliConn.CloseRead()
> 		waitFor = clientClosed
> 	}
> 
> 	<-waitFor
> }
> 
> func broker(dst, src net.Conn, srcClosed chan struct{}) {
> 	_, err := copyBuffer(dst, src, nil)
> 	if err != nil {
> 		log.Printf("Copy error: %s", err)
> 	}
> 	if err := src.Close(); err != nil {
> 		log.Printf("Close error: %s", err)
> 	}
> 	srcClosed <- struct{}{}
> }
> ```
> 
> 
> Thanks
>

**Comment by jackc** [comment]
`nbconn.NetConn` has been removed from pgx so this should no longer be relevant.
