### ISSUE TITLE
A `pgxpool.Conn`'s underlying `pgx.Conn` can be cleared before it is released back to the pool

### ISSUE THREAD

**Issue by ecordell** [jackc/pgx#1607]
**Describe the bug**
In testing how pgxpool performs against a cockroach db cluster that is upgrading (so lots of connection failures / closures), I noticed that sometimes accessing the underlying connection with `pgxpool.Conn.Conn()` will fail.

I believe this is because of these lines: 
https://github.com/jackc/pgx/blob/8ceef73b8437ee97f9f96b0c50e8700096fcb843/tx.go#L176-L178

When a `Commit()` fails, the `pgx.Conn` is closed immediately, leaving a `pgxpool.Conn` with no underlying connection.

I suspect this isn't hit in most usage of `pgxpool` since it may be common to immediately release a connection after a commit failure. 

**To Reproduce**
I don't have a concise reproducer yet. But roughly:

1. Start a pgpool against a CockroachDB cluster
2. Trigger a node drain (i.e. via a rolling upgrade)
3. Attempt to use `pgxpool.Conn.Conn()` on a connection checked out from the pool.

I think that proxying the connection and killing the proxy during the commit could repro more directly.

**Expected behavior**

I expect that the connection is always non-nil if I have successfully acquired it from the pool, until I release it. (Is there some reason that this isn't a good expectation to have?)

**Actual behavior**

Connection is sometimes nil.

**Version**
 - Go: `go version go1.20.4 darwin/arm64`
 - PostgreSQL: CockroachDB 22.2 (though I think this applies generally)
 - pgx: `v5.3.2-0.20230515231020-8ceef73b8437` (head as of writing)

**Comment by jackc** [comment]
Is the problem that the underlying `net.Conn` is closed automatically or that after it is closed that `Conn()` returns `nil`?

The automatic closing of the connection when the `commit` fails is expected. It's unclear what the state of the PG connection would be at that point so I don't think it is possible to reliably recover.

But I would not expect `Conn()` to return `nil`.

**Comment by ecordell** [comment]
> Is the problem that the underlying net.Conn is closed automatically or that after it is closed that Conn() returns nil?

I'll have to do some more tests to find out. 

> The automatic closing of the connection when the commit fails is expected. It's unclear what the state of the PG connection would be at that point so I don't think it is possible to reliably recover.

The problem is that I still need to use the connection after the Commit for tracking purposes. I don't send any further statements on the connection, but I do need to access the pointer to look it back up in a table. 

I'm not 100% sure I've tracked down the root cause correctly, but I don't seem to get panics when using the connection after a failed `Commit()` if I comment those lines out. 

How important is it to close the connection automatically immediately? What about just marking it in some way and then the let the pool notice it needs to be closed when it gets released?

**Comment by ecordell** [comment]
False alarm - I tracked this down to a stray `release` that just happened to always run right after a failed `Commit`. I don't think this is a real issue anymore, closing.
