### ISSUE TITLE
batch.Queue.Query doesn't call callback on first query

### ISSUE THREAD

**Issue by tony-spark** [jackc/pgx#1617]
**Describe the bug**
When I use Queue().Query on Batch to register callbacks, callback of first query in batch doesn't called

**To Reproduce**

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), "postgres://postgres:postgres@localhost:5432/postgres")
	if err != nil {
		log.Fatalf("Unable to connect to database: %v\n", err)
	}
	defer conn.Close(context.Background())

	batch := &pgx.Batch{}

	batch.Queue("insert into names values('John') returning name").Query(func(rows pgx.Rows) error {
		fmt.Println("insert john")
		return nil
	})
	batch.Queue("insert into names values('Tom') returning name").Query(func(rows pgx.Rows) error {
		fmt.Println("insert tom")
		return nil
	})
	batch.Queue("insert into names values('Jack') returning name").Query(func(rows pgx.Rows) error {
		fmt.Println("insert jack")
		return nil
	})

	batchResults := conn.SendBatch(context.Background(), batch)
	if _, err = batchResults.Exec(); err != nil {
		log.Fatalf("failed to exec batch query: %s", err)
	}

	if err = batchResults.Close(); err != nil {
		log.Fatalf("failed to close batch results: %s", err)
	}

	fmt.Println(err)
}
```

**Expected behavior**
3 calls a printed, e.g.:
insert john
insert tom
insert jack

**Actual behavior**
2 calls printed:
insert tom
insert jack

**Version**
 - Go: `$ go version` -> go version go1.20.2 windows/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> PostgreSQL 14.7 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.3.1

**Comment by jackc** [comment]
Registering callbacks when queuing queries and handling results by calling `Exec` or `Query` on `BatchResults` are mutually exclusive operations. They both read the data from off the wire. It can't be read twice. The `batchResults.Exec` call consumes the first result before the callbacks are called by `batchResults.Close`.

**Comment by tony-spark** [comment]
So I just call `batchResults.Close()` right after `SendBatch` to get all callbacks executed?

Is there any pitfalls not calling `batchResults.Exec()`?

**Comment by jackc** [comment]
> So I just call batchResults.Close() right after SendBatch to get all callbacks executed?

Yes. I typically do this:

```go
err := db.SendBatch(ctx, batch).Close()
```

> Is there any pitfalls not calling batchResults.Exec()?

No. Using callbacks is almost always simpler.

**Comment by tony-spark** [comment]
Thanks.
