### ISSUE TITLE
Add MarshalJSON/UnmarshalJSON methods to v5/pgtype.Timestamp

### ISSUE THREAD

**Issue by toqueteos** [jackc/pgx#1620]
**Is your feature request related to a problem? Please describe.**
`Timestamp` lacks `MarshalJSON/UnmarshalJSON` methods.

**Describe the solution you'd like**
Same, or similar, behavior to `Timestamptz`.

**Describe alternatives you've considered**
A custom type that embeds `Timestamp` and implements `MarshalJSON/UnmarshalJSON`.

**Additional context**
N/A

**Comment by jackc** [comment]
Added by @Klaushayan in #1639.
