### ISSUE TITLE
Context cancellation puts transaction state to idle in transaction (aborted)

### ISSUE THREAD

**Issue by miguelespinoza** [jackc/pgx#1623]
**Describe the bug**
Context cancellation puts transaction in `idle in transaction (aborted)` state. 
On production I have a query with a context timeout of 3 seconds, but reading the results from `pg_stat_statements`, the query maxes out around 103 seconds. So the query still runs. As I understand it from this [issue](https://github.com/jackc/pgx/issues/1313) there's no gurantee the query will terminate
> Query cancellation does signal to server to cancel the query. Unfortunately, there is no guarantee the signal will be honored and PostgreSQL doesn’t even provide any feedback regarding the state of the cancellation request.

Regarding the state `idle in transaction (aborted)`, that would indicate that the transaction never rolled back. In fact, when I catch the error from tx.Rollback(), the error returns with `conn closed`. Could this be the issue?

**To Reproduce**

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

	ctx, cancel := context.WithTimeout(ctx, 2*time.Second)
	tx, _ := conn.Begin(ctx)
	
	defer cancel()
	defer func() {
		rollbackErr := tx.Rollback(ctx)
		if rollbackErr != nil {
			fmt.Println("rollback.err: ", rollbackErr)
		}
	}()
	_, err := tx.Exec(ctx, `select 1, pg_sleep(60)`)
	if err == nil {
		log.Fatal("should have timed out")
	}

	fmt.Println("exec.err: ", err)
}
```
Logs
```
exec.err:  timeout: context deadline exceeded
rollback.err:  conn closed
```

**Expected behavior**
A reliable way to end long-running transactions on context cancellation

**Actual behavior**
Long-running transactions are not rolled back, causing `idle in transaction (aborted)` state

**Version**
 - Go: `$ go version` ->  go1.19.5 darwin/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> 14.1.0.76
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.2.0

**Additional context**
* Reason for idle in transaction (aborted) state: https://stackoverflow.com/questions/15036438/postgres-connection-leaks-idle-in-transaction-aborted

**Comment by jackc** [comment]
I think you might be running into the same issue as https://github.com/jackc/pgx/issues/1313#issuecomment-1266763227. That is, the cancel query request is run asynchronously. Put a time.Sleep(5 * time.Second) at the end of main and a suspect your example will work. Though as previously mentioned, canceling a query is only a suggestion to the PostgreSQL server, it may or may not actually stop.

**Comment by miguelespinoza** [comment]
Thanks for your response @jackc.
I'm curious is it the same behavior for pgxpool? and is a rollback necessary if pgx sends a cancel signal?

I was able to confirm in the logs that most connections do cancel properly `canceling statement due to user request`, but also getting a significant number of logs that timeout `canceling statement due to statement timeout`

I think the only option here is to reduce idle transaction timeout.

**Comment by miguelespinoza** [comment]
I've decided instead to set a short `statement_timeout` for this one particular transaction. The issue has to do with it being highly concurrent and high traffic spikes inevitably ends up with long-running transactions using context cancellation

`_, err := db.Exec(ctx, "set statement_timeout to $1", timeout.Milliseconds())`

---
Doing the above led to another discovery
This probably warrants another issue. But maybe it's a quick one.
This transaction I'm running is for a webhook. This webhook endpoint runs `select for no key update` inside a transaction. Within this transaction it makes a request to an external API to get webhook payload data. What I store at the end of a transaction is the payload API's `latestCursor`, which is used for the next session.  What I'm noticing due to it's high concurrent nature, that the next session that picks up (after the row-level lock) it pulls an outdated value from `select for no key update`. This seems to me that `tx.Commit()` is not successful. 
Does this make sense? I should have expected the next session to get the latest `latestCursor` value from the table. Reading through PostgresSQL docs, after commit, it's guaranteed to be durable and changes are immediately visible to other transactions.

Here's the the general workflow:
```
...
data, txErr := store.BeginDataFuncWithStatementTimeout(s.Context, s.db, 3*time.Second,
       func(ctx context.Context, a *store.Queries) (interface{}, error) {
              // select for no key update
              // do work, get webhook payload, which includes latestCursor
              // save latestCursor and BeginDataFuncWithStatementTimeout commits
       })
...

func BeginDataFuncWithStatementTimeout(ctx context.Context, db DbConn, timeout time.Duration, f TransactionDataFuncWithContext) (interface{}, error) {
	_, err := db.Exec(ctx, "set statement_timeout to $1", timeout.Milliseconds())
	if err != nil {
		return nil, errors.Wrap("BeginDataFuncWithStatementTimeout.SetTimeout.err", err)
	}

	tx, err := db.Begin(ctx)
	if err != nil {
		return nil, errors.Wrap("BeginDataFuncWithStatementTimeout.Begin.err", err)
	}

	defer tx.Rollback(ctx)
	defer func() {
		_, _ = db.Exec(ctx, "set statement_timeout to $1", DefaultStatementTimeout.Milliseconds())
	}()

	a := New(tx)

	data, fErr := f(ctx, a)
	if fErr != nil {
		return nil, fErr
	}

	commitErr := tx.Commit(ctx)
	if commitErr != nil {
		return nil, errors.Wrap("BeginDataFuncWithStatementTimeout.Commit.err", commitErr)
	}

	return data, nil
}
```

**Comment by miguelespinoza** [comment]
How embarrassing, I was using a variable that was initialized before the transaction began. That's where the outdated value came from 🤦 

Well, at least that solves my issue with that. I'm closing this issue now

Thanks @jackc for your response with the behavior on context cancellation
