### ISSUE TITLE
pgx.Conn can see uncommitted changes made from a pgx.Tx. | no read-committed isolation by default 

### ISSUE THREAD

**Issue by adamluzsi** [jackc/pgx#1627]
**Describe the bug**

If I create something within a transaction, I've noticed that the uncommitted record becomes visible to anyone utilising the same `*pgx.Conn`, which created the transaction.
Given that I plan to build an app that employs the connection across multiple goroutines through a repository, it would be desirable not to see uncommitted data on the `*pgx.Conn` connection which made the transaction.
I confirmed that making a new transaction with the same connection can also see 

**To Reproduce**

- connect with pgx to a postgres instance
- begin a transaction using the connection
- mutate the state in the database
  - for example, insert a record into a table
- confirm read-committed isolation level by
  - [ ] use an unrelated transaction made with the same connection to see if you can observe the mutation.
  - [ ] use the connection which made the transaction to see if you can observe the mutation.

```go
func Test_pgxTx(t *testing.T) {
	var (
		ctx   = context.Background()
		id    = "a-uniq-id"
		count int
	)

	conn, err := pgx.Connect(ctx, spechelper.DatabaseDSN(t))
	assert.NoError(t, err)
	defer func() { assert.NoError(t, conn.Close(ctx)) }()

	_, err = conn.Exec(ctx, `CREATE TABLE IF NOT EXISTS "foos" ("id" TEXT NOT NULL PRIMARY KEY, "foo" TEXT NOT	NULL);`)
	assert.NoError(t, err)

	defer func() {
		_, err = conn.Exec(ctx, `DROP TABLE IF EXISTS "foos";`)
		assert.NoError(t, err)
	}()

	assert.NoError(t, conn.QueryRow(ctx, `SELECT COUNT(*) FROM foos WHERE id = $1`, id).Scan(&count))
	assert.Equal(t, 0, count)
	
	tx1, err := conn.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.ReadCommitted})
	assert.NoError(t, err)
	defer tx1.Rollback(ctx)

	tag, err := tx1.Exec(ctx, `INSERT INTO foos (id, foo) VALUES ($1, $2)`, id, "foo/bar/baz")
	assert.NoError(t, err)
	assert.Equal(t, 1, tag.RowsAffected())

	tx2, err := conn.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.ReadCommitted})
	assert.NoError(t, err)
	defer tx2.Rollback(ctx)

	assert.NoError(t, tx2.QueryRow(ctx, `SELECT COUNT(*) FROM foos WHERE id = $1`, id).Scan(&count))
	assert.Equal(t, 0, count)

	assert.NoError(t, conn.QueryRow(ctx, `SELECT COUNT(*) FROM foos WHERE id = $1`, id).Scan(&count))
	assert.Equal(t, 0, count)
}
```

**Expected behaviour**

- Given I connect to a postgres instance using the pgx driver
  - And I insert a record using a transaction made with the pgx connection
    - [ ] Then using another transaction, I can't access uncommitted changes by default
    - [ ] Then using the pgx connection, which made the transaction that inserted the record, I can't access uncommitted changes by default

**Actual behavior**

- Given I connect to a postgres instance using the pgx driver
  - And I insert a record using a transaction made with the pgx connection
    - Then using another transaction, I can access uncommitted changes by default
    - Then using the pgx connection, which made the transaction that inserted the record, I can access uncommitted changes by default

**Version**
 - Go: `go version go1.20.1 darwin/arm64`
 - PostgreSQL: `PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`
 - pgx: `github.com/jackc/pgx/v5 v5.3.1`

**Additional context**
- Docker is used to run Postgresql
- Go is compiled and run from the host OS
  - `Darwin 22.4.0 Darwin Kernel Version 22.4.0 arm64 arm Darwin`
- I confirmed that uncommitted changes are not visible if I make a new `*pgx.Conn`.

**Comment by adamluzsi** [comment]
Could it be possible that I overlooked some configuration steps for `pgx.Conn` to enable the ReadCommitted isolation level by default?

**Comment by jackc** [comment]
> Given that I plan to build an app that employs the connection across multiple goroutines through a repository

You probably want to use a connection pool instead.

The transaction is only a handle to simplify transaction management. But all queries run on the Tx  are still running on the original connection and any queries run on that original connection while the Tx is in progress are still happening between the `BEGIN` and `COMMIT` on that connection.

**Comment by adamluzsi** [comment]
Are you suggesting that if I initiate two transactions, make alterations in one, rollback the other, and then commit the transaction where I made changes, it's anticipated that the transactions would influence each other because an actual transaction object was never present in the first place?

```go

func Test_pgxTx_thereIsNoSpoon(t *testing.T) {
	var (
		ctx   = context.Background()
		id    = "a-uniq-id"
		count int
	)

	conn, err := pgx.Connect(ctx, spechelper.DatabaseDSN(t))
	assert.NoError(t, err)
	defer func() { assert.NoError(t, conn.Close(ctx)) }()

	_, err = conn.Exec(ctx, `DROP TABLE IF EXISTS "pgx_tx_there_is_no_spoon";`)
	assert.NoError(t, err)
	
	_, err = conn.Exec(ctx, `CREATE TABLE IF NOT EXISTS "pgx_tx_there_is_no_spoon" ("id" TEXT NOT NULL PRIMARY KEY, "foo" TEXT NOT	NULL);`)
	assert.NoError(t, err)

	defer func() {
		_, err = conn.Exec(ctx, `DROP TABLE IF EXISTS "pgx_tx_there_is_no_spoon";`)
		assert.NoError(t, err)
	}()

	tx1, err := conn.Begin(ctx)
	assert.NoError(t, err)

	tx2, err := conn.Begin(ctx)
	assert.NoError(t, err)
	
	tag, err := tx1.Exec(ctx, `INSERT INTO "pgx_tx_there_is_no_spoon" (id, foo) VALUES ($1, $2)`, id, "foo/bar/baz")
	assert.NoError(t, err)
	assert.Equal(t, 1, tag.RowsAffected())
	
	assert.NoError(t, tx2.Rollback(ctx))
	assert.NoError(t, tx1.Commit(ctx))

	assert.NoError(t, conn.QueryRow(ctx, `SELECT COUNT(*) FROM "pgx_tx_there_is_no_spoon" WHERE id = $1`, id).Scan(&count))
	
	assert.Equal(t, 1, count) // fails because it was rolled back instead of commit
}

```

**Comment by adamluzsi** [comment]
Could you kindly provide guidance on utilising transactions with pgx in a multithreaded Go application?
Does pgx include any built-in pool implementation that I can employ?

**Comment by danp** [comment]
You likely want https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool.

**Comment by thilonel** [comment]
To me this is a surprising find! If this behavior is indeed intended then it could be better reflected in the API's design as well, as when I read adamluzsi's code I do expect the same behavior as he does.

**Comment by adamluzsi** [comment]
Maybe we could mention this behaviour in the BeginTx/Begin method's documentation.
> BeginTx modifies the state of Conn, serving mainly as syntactic sugar, and doesn't generate a segregated Tx instance as sql.DB does.

```
// BeginTx starts a transaction with txOptions determining the transaction mode. Unlike database/sql, the context only
// affects the begin command. i.e. there is no auto-rollback on context cancellation.
// BeginTx modifies the state of Conn, serving mainly as syntactic sugar, and doesn't generate a segregated Tx instance as sql.DB does.
func (c *Conn) BeginTx(ctx context.Context, txOptions TxOptions) (Tx, error) {
```

**Comment by jackc** [comment]
From the [package docs](https://pkg.go.dev/github.com/jackc/pgx/v5#hdr-Connection_Pool):

> `*pgx.Conn` represents a single connection to the database and is not concurrency safe. Use package github.com/jackc/pgx/v5/pgxpool for a concurrency safe connection pool. 

From the [getting started guide:](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx)

> The *pgx.Conn returned by pgx.Connect() represents a single connection and is not concurrency safe. This is entirely appropriate for a simple command line example such as above. However, for many uses, such as a web application server, concurrency is required. To use a connection pool replace the import github.com/jackc/pgx/v5 with github.com/jackc/pgx/v5/pgxpool and connect with pgxpool.New() instead of pgx.Connect().

From the [pgx.Conn docs](https://pkg.go.dev/github.com/jackc/pgx/v5#Conn):

> Conn is a PostgreSQL connection handle. It is not safe for concurrent usage. Use a connection pool to manage access to multiple database connections from multiple goroutines.
