### ISSUE TITLE
pgxpool hangs while normal pgx gives proper error information (nil pointer)

### ISSUE THREAD

**Issue by hoffax** [jackc/pgx#1628]
**Describe the bug**
When using normal pgx, if you commit a mistake and pass a nil pointer to a `Scan` it will print the error properly, but when using pgxpool, it just hangs there forever.

**To Reproduce**
small example

```go
var greeting *string
err = dbpool.QueryRow(ctx, "/..query../'").Scan(greeting) 
```
(no `&` on `greeting`)

runnable example:
```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5/pgxpool"
)

func main() {
	dbpool, err := pgxpool.New(context.Background(), os.Getenv("DB_URL"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to create connection pool: %v\n", err)
		os.Exit(1)
	}
	defer dbpool.Close()

	var greeting *string
	err = dbpool.QueryRow(context.Background(), "select 'Hello, world!'").Scan(greeting)
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Println(greeting)
}
```

**Expected behavior**
When running without the pgxpool, code below
```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DB_URL"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close(context.Background())

	var greeting *string
	err = conn.QueryRow(context.Background(), "select 'Hello, world!'").Scan(greeting)
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Println(greeting)
}

```
example output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7381ab]

goroutine 1 [running]:
github.com/jackc/pgx/v5/pgtype.scanPlanString.Scan(...)
```

**Actual behavior**
it just hangs forever.

**Version**
 - Go: go1.20.4 linux/amd64
 - PostgreSQL:  running on docker posgresql:15
 - pgx: v5.3.1

**Additional context**
i know its a mistake, but having a error would be nice, the process hanging there its just so hard to find the mistake, i lost so many hours navigating the source code yesterday to find where i forgotten to put a `$`

**Comment by jackc** [comment]
The `Scan` is not what hung. The `defer dbpool.Close()` was. The panic in `Scan` caused the connection to not be released and then `dbpool.Close` blocked waiting for all connections to be returned.

I've fixed `(*pgxpool.Pool).QueryRow(...).Scan(...)` to release the connection even if a panic occurs.

**Comment by hoffax** [comment]
that was fast, awesome.

**Comment by alexbozhkov** [comment]
> The `Scan` is not what hung. The `defer dbpool.Close()` was. The panic in `Scan` caused the connection to not be released and then `dbpool.Close` blocked waiting for all connections to be returned.
> 
> I've fixed `(*pgxpool.Pool).QueryRow(...).Scan(...)` to release the connection even if a panic occurs.

Hello, I had the same issue, can you please explain to me how this fixed the issue, is there something I'm missing fundamentally ?
(it worked for me as well btw)

**Comment by jackc** [comment]
@alexbozhkov The query methods called on a `*pgxpool.Pool` automatically acquire and release the underlying connection. A uncaught panic in `QueryRow` meant the release of connection never happened. That blocked the closing of the pool as it waits for all connections to be returned.
