### ISSUE TITLE
Failed to encode []string for `WHERE column IN ($1)`

### ISSUE THREAD

**Issue by bersace** [jackc/pgx#1630]
**Describe the bug**
pgx fails to encode string array when parameter is on the right of the `IN` operator.

**To Reproduce**

```go
package main

import (
	"context"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), "")
	if err != nil {
		panic(err.Error())
	}
	defer conn.Close(context.Background())

	ary := []string{"toto", "titi"}
	_, err = conn.Query(context.Background(), `SELECT TRUE WHERE 'toto' IN ($1)`, ary)
	if err != nil {
		panic(err.Error())
	}
}
```

**Expected behavior**
I expected the string array to be serialized as text array.

**Actual behavior**
pgx raises an error `failed to encode []string`.

**Version**
 - Go: `$ go version` -> go version go1.20.3 linux/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` ->  PostgreSQL 15.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.3.1

**Comment by jackc** [comment]
Your `IN ($1)` isn't expecting a `[]string`, it expecting a `string`. Use `= any ($1)` if you want a `[]string` parameter.

**Comment by bersace** [comment]
@jackc you're awesome. Where is this documented ? In PostgreSQL doc ?

**Comment by jackc** [comment]
@bersace 

https://www.postgresql.org/docs/current/functions-comparisons.html#id-1.5.8.30.16 is where `= any` is documented in PostgreSQL as taking a single array argument.

And https://www.postgresql.org/docs/current/functions-comparisons.html#FUNCTIONS-COMPARISONS-IN-SCALAR  is where `IN (...)` is documented as taking multiple scalar arguments.

**Comment by bersace** [comment]
You're awesome, thanks.

**Comment by DavidAbgaryan** [comment]
problem caused by things like this
where f.id in (@facility_ids) (problematic case )
where f.id = any (@facility_ids) (working version ) ANY is PostgreSQL-specific.
