### ISSUE TITLE
Cannot import stdlib when using via gopkg.in

### ISSUE THREAD

**Issue by ashb** [jackc/pgx#164]
pkgx/stdin/sql.go attempts to import github.com/jackc/pgx which if i did `go get gopkg.in/jackc/pkx.v2` I don't have:

```
../../../gopkg.in/jackc/pgx.v2/stdlib/sql.go:53:2: cannot find package "github.com/jackc/pgx" in any of:
        /Users/ash/.homebrew/Cellar/go/1.6.2/libexec/src/github.com/jackc/pgx (from $GOROOT)
        /Users/ash/code/go/src/github.com/jackc/pgx (from $GOPATH)
```

Is there any way around this, or is this unavoidable? If so let me know and I'll make a small doc fix PR.

**Comment by jackc** [comment]
I'd like if there was a way around it, but I don't know of any. Probably a doc fix is best.
