### ISSUE TITLE
single quoted query parameters not recognized

### ISSUE THREAD

**Issue by mortezadadgar** [jackc/pgx#1655]
**Describe the bug**
driver doesn't recognize single quoted query parameter and if I don't quote it I won't be able to full search with spaces in query parameter.

**To Reproduce**
```go
func Init(ctx context.Context) (*sql.DB, error) {
	db, err := sql.Open("pgx", os.Getenv("DSN"))
	if err != nil {
		return nil, fmt.Errorf("failed to open postgresql: %v", err)
	}

	err = db.PingContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to make connection to pg: %v", err)
	}

	return db, nil
}

func (p *ProductsStore) Search(ctx context.Context, name string) (*ecommerce.Products, error) {
	tx, err := p.db.Begin()
	if err != nil {
		return nil, fmt.Errorf(ErrBeginTransaction, err)
	}

	query := `
	SELECT * FROM categories
	WHERE to_tsvector('simple', name) @@ plainto_tsquery('simple', '$1');
	`

	var product ecommerce.Products
	args := []any{
		&product.CategoryID,
		&product.Name,
		&product.Description,
		&product.Price,
		&product.Quantity,
	}

	err = tx.QueryRowContext(ctx, query, name).Scan(args...)
	switch {
	case err == sql.ErrNoRows:
		return nil, fmt.Errorf("no product with name=%s", name)
	case err != nil:
		return nil, fmt.Errorf("failed to query product: %v", err)
	}

	err = ctx.Err()
	if err != nil {
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf(ErrCommitTransaction, err)
	}

	return &product, nil
}
```

**Expected behavior**
expecting to receive the row with parameter query in it.

**Actual behavior**
[ERROR]: GET /products/search: failed to query product: expected 0 arguments, got 1

**Version**
 - Go: `$ go version` -> go version go1.20.5 linux/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by x86_64-pc-linux-gnu-gcc (Gentoo Hardened 12.2.1_p20230428-r1 p2) 12.2.1 20230428, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.4.1

**Additional context**
I know that I'm doing sql query on categories table I'm just testing.

**Comment by jackc** [comment]
> driver doesn't recognize single quoted query parameter and if I don't quote it I won't be able to full search with spaces in query parameter.

That's not accurate. Bound query parameters can have spaces.

```sql
SELECT * FROM categories
	WHERE to_tsvector('simple', name) @@ plainto_tsquery('simple', '$1');
```

You can't put parameter placeholders in a string. It will be treated as a literal "$1" instead. This is how PostgreSQL works, it's not specifically a pgx issue. You will see the same behavior in psql if you run a `PREPARE` and `EXECUTE`.

**Comment by mortezadadgar** [comment]
yeah you're right I can remove single quotes.

**Comment by martingrzzler** [comment]
@jackc 

I do get an error when I use single-quoted phrases.

```sql
SELECT * FROM categories
	WHERE to_tsvector('simple', name) @@ to_tsquery('simple', $1);
```

```go
args := []string {"(example:*) & !(mars:* | space:* | ''artificial intelligence'')"}
```
ERROR:
```shell
ERROR: syntax error in tsquery: "(example:*) & !(mars:* | space:* | ''artificial intelligence'')" (SQLSTATE 42601)
```

**Comment by jackc** [comment]
I think the problem is using two single-quotes. You don't need to use two single quotes inside of bound text parameter like you do when embedding a string in the query.
