### ISSUE TITLE
pgxpool.Pool.SendBatch Doesn't Release Connections

### ISSUE THREAD

**Issue by sbaynham-gridwise** [jackc/pgx#1656]
**Describe the bug**
https://github.com/jackc/pgx/blob/master/pgxpool/pool.go#L636

SendBatch never releases connections, causing the method to freeze up when called repeatedly

**To Reproduce**
Steps to reproduce the behavior: Call pgxpool.Pool.SendBatch several times

**Expected behavior**
Connections are released after used

**Actual behavior**
Connection is not released

**Comment by jackc** [comment]
From https://pkg.go.dev/github.com/jackc/pgx/v5#Conn.SendBatch:

> The returned BatchResults must be closed before the connection is used again.

Are you calling `Close` on the returned `BatchResults`?

**Comment by sbaynham-gridwise** [comment]
Ah, no I wasn't. Thanks!
