### ISSUE TITLE
Can not retrieve a date without getting back a timestamp

### ISSUE THREAD

**Issue by jmunson** [jackc/pgx#166]
I have a table with dates stored in the date type (as opposed to timestamps, since I do not have times associated with these dates). 

I originally tried scanning them into a struct as a time.Time, but when I marshaled the results into json they had  timestamps added to them.  So for example instead of "1985-11-27" I got "1985-11-27T00:00:00-05:00".   

I understand thats more a limitation of time.Time and since the struct I was scanning to is just used to marshal back out, I tried changing the type to a string.  This still lead to the exact same formatting, unless I queried for `to_char(dt1, 'YYYY-MM-DD') as dt1`

I tried to make a test case, and came up with

```Go
func TestDateNoTime(t *testing.T) {
        t.Parallel()

        conn := mustConnect(t, *defaultConnConfig)
        defer closeConn(t, conn)

        var d string

        err := conn.QueryRow("select make_date(1999,09,09)").Scan(&d)

        if err != nil {
                t.Fatalf("Unexpected failure on QueryRow Scan: %v", err)
        }
        if d != "1999-09-09" {
                t.Errorf("Date did not come back in the right format: %v is not 1999-09-09", d)
        }

}
```  

This test does not pass, but weirdly it doesn't seem to scan anything into d at all there.

I assume the only way forward from here is to just create my own type to scan to and make my own MarshalJSON method, but I'd love to know if you have any other solutions, or if there is a commonly used third party type that does this that I should use instead

**Comment by jmunson** [comment]
I ended up making the type changes to get around the problem myself,  but thats very weird that the test passes for you, as it still fails for me. I believe I'm running the latest version of everything..
```
❯ go test -run TestDate
--- FAIL: TestDateNoTime (0.00s)
        values_test.go:28: Date did not come back in the right format:  is not 1999-09-09
FAIL
exit status 1
FAIL    github.com/jackc/pgx    0.014s

❯  git rev-parse HEAD 
558d5550cf5c08e7192eb2eb8635f21f4b700ff5
❯ go version
go version go1.6.2 linux/amd64
❯echo "select version();"  psql -U postgres |grep Postgre 
 PostgreSQL 9.5.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 6.1.1 20160501, 64-bit
❯ lsb_release -a -s 
1.4 Arch "Arch Linux" rolling n/a


```

At this point figuring out why it fails for me isn't a huge priority since I did work around it another way, but its definitely odd and if you have anything you'd like me to try to further diagnose this I'd be happy to help.

**Comment by jackc** [comment]
Now I'm wondering if I was seeing things before. I double-checked and I now get an error.

But I understand what the error is now. When the query is sent pgx has to tell PostgreSQL in what format to send the data back. pgx understands the binary format for `date` so it asks for the binary format. When we scan the value into a string it is reading the raw binary data. That is why the format is wrong. The solution is to cast the `date` to `text` in the query:

```go
err := conn.QueryRow("select make_date(1999,09,09)::text").Scan(&d)
```
