### ISSUE TITLE
Using a Postgres composite type in combination with a struct with an embedded struct fails

### ISSUE THREAD

**Issue by haarts** [jackc/pgx#1665]
**Describe the bug**

Consider the following structs:

```
type Model struct {
	ID        uuid.UUID 
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Account struct {
	Model
	Did      string            
	Name     *string   
}

type Session struct {
	ID      uuid.UUID 
	Account Account
}
```
(The real structs are slight more elaborate.)
The tables are relatively simple too. There's a `sessions` table and an `accounts` table, both have an `id`, `created_at`, `updated_at` column and then some. Nothing fancy.

I'm using the following query:
```
		SELECT
			sessions.id,
			row(
				accounts.*
			) as account
		FROM sessions, accounts
		WHERE sessions.account_id = accounts.id
```

Eventually, I do `pgx.CollectRows(rows, pgx.RowToStructByName[model.Session])`. This raises an error: 

```
can't scan into dest[1]: cannot scan uuid (OID 2950) in binary format into *model.Model
```

I know I'm pushing the limit here; the error isn't entirely unexpected. I'm guessing here; but what I think happens is that pgx gets an `id` field (from the accounts table), and it tries to map that to the embedded `Model`. That fails. 

I could get this to work with `RowToFunc` but that would be less elegant.

**To Reproduce**

If possible, please provide runnable example such as:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

type Model struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Account struct {
	Model
	Did  string
	Name *string
}

type Session struct {
	ID      uuid.UUID
	Account Account
}

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())
	rows, err := conn.Query(context.Background(), `
		SELECT
			sessions.id,
			row(
				accounts.*
			) as account
		FROM sessions, accounts
		WHERE sessions.account_id = accounts.id
        `)
	fmt.Println(err)
	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[Session])
	fmt.Println(err) // <- Error occurs here
	fmt.Println(result)
}
```

**Expected behavior**
I would have expected to get a slice of `Session`s.

**Actual behavior**
I got an error: `can't scan into dest[1]: cannot scan uuid (OID 2950) in binary format into *main.Model`

**Version**
 - Go: `$ go version` -> go version go1.20.4 linux/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` ->  PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> github.com/jackc/pgx/v5 v5.4.1

**Additional context**

For your convenience the table definitions:

```sql
CREATE TABLE public.accounts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    did text,
    name text,
    email text NOT NULL,
    otp text,
    settings json DEFAULT '{}'::json NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_id uuid NOT NULL,
    client integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    authorization_id uuid
);
```

**Comment by jackc** [comment]
> I know I'm pushing the limit here; the error isn't entirely unexpected. I'm guessing here; but what I think happens is that pgx gets an id field (from the accounts table), and it tries to map that to the embedded Model. That fails.

It is as you surmise. The first field of `Account` is `Model`, not `Model`'s first field. 

But a small change in the SQL query would allow your Go code to work unchanged:

```sql
SELECT
	sessions.id,
	row(
		row(accounts.id, accounts.created_at, accounts.updated_at), accounts.did, accounts.name
	) as account
FROM sessions, accounts
WHERE sessions.account_id = accounts.id
```

It *might* be possible to "flatten" the composite type scan target, we do that at the row level in `RowToStructByPos`. But a quick look at the code didn't reveal an obvious place for the change -- and it would be a behavior change -- not sure if that would be acceptable at this point as it would break anyone using it as suggested above.

**Comment by haarts** [comment]
I was so close! Thank you very much for the last nudge. Your suggestion worked.
