### ISSUE TITLE
package net/netip is not in GOROOT

### ISSUE THREAD

**Issue by ponyjackal** [jackc/pgx#1671]
**Describe the bug**
I am using github.com/jackc/pgx/v5 v5.3.1 in my go gin project
I dockerized the project and tried to build docker image on server through ci/cd

but I got the error below 

>  => ERROR [builder 7/7] RUN CGO_ENABLED=0 GOOS=linux go build -mod=readonly -v -o main .                                            0.4s
> ------
>  > [builder 7/7] RUN CGO_ENABLED=0 GOOS=linux go build -mod=readonly -v -o main .:
> #0 0.376 /go/pkg/mod/github.com/jackc/pgx/v5@v5.3.1/pgtype/builtin_wrappers.go:9:2: package net/netip is not in GOROOT (/usr/local/go/src/net/netip)
> ------
> failed to solve: executor failed running [/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -mod=readonly -v -o main .]: exit code: 1
>

**Comment by drakkan** [comment]
net/netip was added to Go 1.18, pgx requires Go 1.19. Please update your Go to a supported version

**Comment by ponyjackal** [comment]
Okay, thanks
