### ISSUE TITLE
"mismatched param and argument count" error  when using pgsql and db.Exec

### ISSUE THREAD

**Issue by sfreeman422** [jackc/pgx#1686]
**Describe the bug**
I am attempting to use pgsql to write a conditional that updates a given field if we can confirm that the item we want to update exists. I want to throw an error if the item does not exist. I have written the below SQL that I have confirmed works in PgAdmin with the placeholders filled in with actual values. 

**To Reproduce**
```
removeUserAndAssociatedItems := `
DO $$
BEGIN
	IF EXISTS(SELECT 1 from main.table1 WHERE id=$1 AND quarter=$2 AND year=$3 AND is_manually_added=true)
	THEN 
		UPDATE main.table1 SET is_deleted=true WHERE id=$1 AND quarter=$2 AND year=$3 AND is_manually_added=true;
		UPDATE main.table2 SET is_deleted=true WHERE id=$1 AND quarter=$2 AND year=$3;
	ELSE RAISE EXCEPTION 'Item Not Found';
	END IF;
END $$
`
_, err := r.db.Exec(context.Background(), removeUserAndAssociatedItems, id, quarter, year)
```

**Expected behavior**
The placeholder values are populated and my conditional behaves as it does in PGAdmin, meaning that the conditionals behave accordingly and the desired SQL or RAISE EXCEPTION is called dependent on the condition.

**Actual behavior**
A "mismatched param and argument count" error is thrown.

**Version**
 - Go: go version go1.20.4 darwin/arm64
 - PostgreSQL: Postgres 12.11 on AWS RDS Instance
 - pgx: github.com/jackc/pgx/v5 v5.4.1

**Additional context**
I stepped through the VSCode debugger and can see that the error is thrown here:https://github.com/jackc/pgx/blob/038fc448c1cc91b9372a6a0d151789f41536f033/extended_query_builder.go#L32

I can see in the debugger that my `len(arguments)`is 3 which is expected however, `len(sd.ParamOIDs)` is 0 hence my error.

`r.db` is a `*pgxpool.Pool`

**Comment by jackc** [comment]
A `DO` block cannot use placeholder parameters from the query.

**Comment by sfreeman422** [comment]
Ahh I see - so this is user error in the SQL itself? My bad!

**Comment by sfreeman422** [comment]
Is there any way for me to pass in dynamic values to a statement like this using pgx or should I be rethinking my approach here?

**Comment by sfreeman422** [comment]
Closing and rethinking my approach, thanks for the prompt response!!

**Comment by jackc** [comment]
Just for a little further info, the DO block is treated by PostgreSQL as `DO [ LANGUAGE lang_name ] code` where `code` is a string literal. That is why you can't use bound variables inside the code block.

Here are a few alternatives:

* You could run the 2 update statements without the if exists statement. Check the command tag(s) to see if any updates actually occurred. Use a batch to still do it in 1 round trip.
* The queries could be rewritten into 1 writable CTE query. Again, use the command tag to see if anything happened.
* You could make the DO block a server side function
