### ISSUE TITLE
Windows CI failure with TestPoolBackgroundChecksMinConns

### ISSUE THREAD

**Issue by jackc** [jackc/pgx#1690]
CI consistently fails for Windows on the test TestPoolBackgroundChecksMinConns. I do not have a working Windows development available so I am unable to reproduce locally.

Also, the test is failing in a way that should be impossible. The test runner is aborting after 10 minutes. However, there is a context timeout for 2 minutes in the loop that the stack trace reveals the execution was at.

**Comment by jackc** [comment]
I have disabled this test on Windows to "fix" CI. The problem started with c513e2e435dca8acde76a4a0ed4856b9946b14e0, but I have no idea how. See https://github.com/jackc/pgx/actions/runs/5562866651/jobs/10161439577 for the CI output.

**Comment by jackc** [comment]
Hmm... just saw it fail on Ubuntu -- https://github.com/jackc/pgx/actions/runs/5606168483/jobs/10256042300.

So I guess it's not just Windows. Unfortunately, it seems to be very rare outside of Windows so difficult to reproduce.

**Comment by jameshartig** [comment]
@jackc I'm trying to reproduce it hanging on windows but I haven't been able to thus far.

**Comment by jameshartig** [comment]
The only time I've been able to get it to hang was if `PGX_TEST_DATABASE` had an invalid configuration and the connections were failing.

**Comment by jameshartig** [comment]
One confusing part of both those failures is that it looks like it was being run in parallel with other tests, at least according to the stack traces, but that test didn't specify `t.Parallel()`. I don't see why it can't be run parallel though.

One of the fixes should be to fix the check on the context to be `&& ctx.Err() == nil` so that it stops looping after 120 seconds.

**Comment by jackc** [comment]
Thanks for the help. I merged your PR.

With regard to:

> One confusing part of both those failures is that it looks like it was being run in parallel with other tests, at least according to the stack traces, but that test didn't specify t.Parallel(). I don't see why it can't be run parallel though.

I believe this is a side effect of how parallel tests are implemented. As I understand it, tests are run serially but are paused by the `t.Parallel` call until the test runner allows it to continue. So there could be many blocked goroutines for the parallel tests in the stack trace even though none of them are running.
