### ISSUE TITLE
(*zeronull.Timestamptz).Scan uses pgtype.Timestamp as underlying nullable type

### ISSUE THREAD

**Issue by espadolini** [jackc/pgx#1694]
Unless there's something that I'm missing, scanning the text form of a non-null `timestamp with time zone` like that will result in either a parsing error or the wrong timezone; shouldn't that be `var nullable pgtype.Timestamptz`?

https://github.com/jackc/pgx/blob/88b49d48f647775ba8a69748bc29e7135daee725/pgtype/zeronull/timestamptz.go#L49C31-L49C31

**Comment by jackc** [comment]
Fixed.
