### ISSUE TITLE
Shouldn't fatal all the rows when one row is failed

### ISSUE THREAD

**Issue by ruopuzi** [jackc/pgx#1702]
This line will fatal all the rows by rows.Close() call. But we may prefer some fault tolerance to go on processing the rest rows.
https://github.com/jackc/pgx/blob/d626dfe94e250e911b77ac929e2be06f81042bd0/rows.go#L236

**Comment by jackc** [comment]
If a row can't be scanned that is almost certainly a bug. And even if it wasn't, that would get really tricky to report (e.g. there could be multiple errors - we would need to track the row number and accumulate the errors). This would also be a significant behavior change, probably not something that could be done outside of a major release.

Sorry, I don't think this should happen.
