### ISSUE TITLE
Wrong number of arguments in the cached statement

### ISSUE THREAD

**Issue by alexandrkara-outreach** [jackc/pgx#1704]
**Describe the bug**
We started getting errors like `expected 0 arguments, got 21`. It's very likely coming from https://github.com/jackc/pgx/blob/master/conn.go#L735.

**To Reproduce**
We are sharing connections between many goroutines and executing statements like:
```
SELECT a, b FROM X WHERE X.id IN ($1, $2, ..., $20);
```

and the number of arguments passed in varies.

The connection is opened using:
```golang
	connConfig, err := pgx.ParseConfig(connURL.String())
	if err != nil {
		...
	}

	db := pgxstdlib.OpenDB(*connConfig)
```

where the URL is like `postgres://user:pass@hostname:5432/dbname?application_name=appname&connect_timeout=20&search_path=global&sslmode=verify-full`.

**Expected behavior**
The query would be executed.

**Actual behavior**
The query is not even sent to the PostgreSQL server but fails with an error `expected 0 arguments, got 21` - the expectation is always 0, the actual number varies..

**Version**
 - Go: `$ go version` ->go version go1.19.11 linux/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> PostgreSQL 14.6 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 7.4.0, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.4.2

**Additional context**
We are getting approximately 2k to 3k such errors per day with approx 60 to 100M total number of queries per day. We don't do any writes (writes are done from a different process).

**Comment by alexandrkara-outreach** [comment]
A similar problem is on the "receiving" side, with errors like `expected 18 destination arguments in Scan, not 2`. Here, the first argument seems to be some discrete values (in our case 1, 5 or 18, which hare possibly argument counts from other queries?).

**Comment by jackc** [comment]
Here's a few things that might help identify the problem:

* Can you run with the race detector on?
* Is there any load balancer such as pgbouncer between your application and PostgreSQL? If so, can you duplicate the issue when connecting directly to PostgreSQL?
* Can you reproduce the issue using a different `default_query_exec_mode` in your connection string?

**Comment by brilliant-ember** [comment]
@jackc is there a way to change `default_query_exec_mode` while using pgx as driver for `database/sql`?

**Comment by brilliant-ember** [comment]
Nvm found out how to do it. I couldn't find it in the documentation anywhere, but when I read the source code I found exactly what I was looking for, with a neat example too!

this code is from [stdlib/sql.go](https://github.com/jackc/pgx/blob/master/stdlib/sql.go)

```
// Or a pgx.ConnConfig can be used to set configuration not accessible via connection string. In this case the
// pgx.ConnConfig must first be registered with the driver. This registration returns a connection string which is used
// with sql.Open.
//
//	connConfig, _ := pgx.ParseConfig(os.Getenv("DATABASE_URL"))
//	connConfig.Logger = myLogger
//	connStr := stdlib.RegisterConnConfig(connConfig)
//	db, _ := sql.Open("pgx", connStr)
//
```

The connection string is the DATABASE_URL env var was `postgres://YourUserName:YourPassword@YourHostname:5432/YourDatabaseName`

**Comment by alexandrkara-outreach** [comment]
Sorry for not reacting for so long, it has been very busy and I haven't seen these errors lately. Feel free to close the report if you cannot reproduce it.

**Comment by alexandrkara-outreach** [comment]
We have cut down on queries a lot, so this may be the reasons it's occurring much less - or could have been fixed, hard to tell for me now.

**Comment by jackc** [comment]
👍
