### ISSUE TITLE
pool support afterconnect run one time only

### ISSUE THREAD

**Issue by tsingson** [jackc/pgx#1705]
**Is your feature request related to a problem? Please describe.**

```
poolConfig.AfterConnect = afterConnect
```
when setup pool with afterconnect to prepare sql statement, and request new connect from pool, the afterconnect run every time, i think afterconnect should be run one time only ( all named sql statement runs when pool call first time)

**Comment by jackc** [comment]
It runs once for each new connection. And this is what you need for prepared statements as they exist at a connection level, not at the pool level.
