### ISSUE TITLE
Global `TypeMap` for all connections

### ISSUE THREAD

**Issue by martingrzzler** [jackc/pgx#1706]
I'm using the `simple_protocol` together with ORM `entgo`. In order to provide the type mappings I use the following code:
``` go
ctx := context.Background()
	db, err := sql.Open("pgx", "host=localhost port=5432 user=postgres dbname=simple password=postgres default_query_exec_mode=simple_protocol")
	if err != nil {
		panic(err)
	}

	conn, err := db.Conn(ctx)
	if err != nil {
		panic(err)
	}

	conn.Raw(func(driverConn interface{}) error {
		pgxConn := driverConn.(*stdlib.Conn).Conn()

		pgxConn.TypeMap().RegisterDefaultPgType(json.RawMessage{}, "jsonb")
		pgxConn.TypeMap().RegisterDefaultPgType([]byte{}, "jsonb")

		return nil
	})

	conn.Close()

	entDriver := entsql.OpenDB(dialect.Postgres, db)

	client := ent.NewClient(ent.Driver(entDriver))
```

The problem is that if a new connection is somewhere created it does not use the custom `TypeMap`. **Hence is there a way to set the `TypeMap` globally for all connections?**

**Comment by jackc** [comment]
There is not a way to use one `TypeMap` for all connections. What you can do instead is use [stdlib.OptionAfterConnect](https://pkg.go.dev/github.com/jackc/pgx/v5@v5.3.0/stdlib#OptionAfterConnect) to run your type registration for every connection.

Also, I would be careful about this line:

```
pgxConn.TypeMap().RegisterDefaultPgType([]byte{}, "jsonb")
```

If you ever need to also use `bytea` that could make things more difficult.
