### ISSUE TITLE
Pre-warming the statement cache

### ISSUE THREAD

**Issue by mdelah** [jackc/pgx#1716]
**Is your feature request related to a problem? Please describe.**
There are certain SQL statements that we know ahead of time the application will execute, but may only execute sporadically (thus the cost of preparation the first time they execute on a given connection may be significant). I was wondering if we could have a means of injecting them into the `Conn.statementCache` without actually executing them.

**Describe the solution you'd like**
One way would be to have a new `QueryExecMode`, say `QueryExecModeCacheOnly`. In said mode, the statement would be prepared and cached, but not executed. Any arguments given would be ignored, or alternatively it could be mandated that no arguments are provided.

**Describe alternatives you've considered**
Of course we can `Prepare()` them explicitly and supply the assigned statement IDs to `Exec` instead of the SQL (and that's what we've been doing so far). But it would be convenient to leave the prepared statement management up to the `stmtcache.Cache` and have the application deal exclusively with SQL strings, so for us, it would be a valuable feature.

Other options we considered were calling `Exec` in the usual mode but with the (deliberately) wrong number/type of arguments (which gets the job done but is fragile), or executing it within a transaction that's then rolled back (also works, but creates unnecessary work for the DB).

If you're open to the concept, happy to put up a PR for review.

**Comment by jackc** [comment]
> Of course we can Prepare() them explicitly and supply the assigned statement IDs to Exec instead of the SQL (and that's what we've been doing so far).

Even if the cache is pre-warmed there is no guarantee that any particular query will stay in the cache. If performance constraints are such that these statements really *must* be prepared, then this is the correct approach.

> Other options we considered were calling Exec in the usual mode but with the (deliberately) wrong number/type of arguments (which gets the job done but is fragile)

This does feel a bit icky, but it's actually not bad. By passing an arg that cannot be encoded you would guarantee that the SQL is only ever prepared and there is no attempted execution. I think this is the correct approach for the question of pre-warming the cache.

But I doubt that pre-warming the cache is the right question. I think a better question is how to make dealing with explicitly prepared statements easier. It's definitely a little awkward by default. I think some tooling around this is the right answer (not sure if that tooling should live in pgx, the application, or a 3rd party library).

**Comment by mdelah** [comment]
> Even if the cache is pre-warmed there is no guarantee that any particular query will stay in the cache.

Right, though in this particular case the number of statements in use is well below the capacity of the cache.

> This does feel a bit icky, but it's actually not bad. By passing an arg that cannot be encoded you would guarantee that the SQL is only ever prepared and there is no attempted execution.

Yeah, it seems appealing, but where it gets messy is

1. ensuring the chosen type cannot accidentally get encoded successfully - given the universe of possible OIDs, built-in codecs and `TryWrapEncodeFuncs`, plus our custom ones, this turns out to be surprisingly difficult to prove
2. working out what the set of "expected errors" are, so we can still detect real ones (e.g. problems with the preparation rather than the arguments) - at a minimum this would mean searching the error text for the "wrong number of arguments" and "no matching encode plan", plus any others where an encode plan is found but then fails during the encoding.

> But I doubt that pre-warming the cache is the right question. I think a better question is how to make dealing with explicitly prepared statements easier.

That fair, we don't specifically need/want the LRU stuff here, I think the main appeal of the statement cache right now is that we can pass the SQL itself to `Query()`, so on the application side we don't have to pass around prepared statement IDs alongside the SQL or do mappings between them. If there was a way to achieve the same with `Prepare()`, that would be just as good, e.g. a config option to key the `preparedStatements` by `sql` instead of/in additional to `name`, or a means to replace `preparedStatements` with a custom implementation.

**Comment by jackc** [comment]
> e.g. a config option to key the preparedStatements by sql instead of/in additional to name

That's not a bad idea. Though I'm not sure it would even need to be a config option. I don't see how keying by SQL in addition to the name would cause any issues so it probably could be always on.

The only changes for this that I can see would be:

Prepare detects `name == sql`. In that case it uses a ~~random name~~ digest such as SHA-256 of the SQL as the name (using a digest gives us stable prepared statement names which may be valuable for database logging or tracing).

Then there are a few ways it could be implemented internally.

1. Another separate `preparedStatements` map
2. The query paths automatically digest the SQL for every query for the prepared statements lookup (after they try it undigested).

Probably the first approach would be more efficient.

**Comment by mdelah** [comment]
Ah indeed, done that way it wouldn't really need to have a config option. I guess besides using a separate `preparedStatements` map it could also just reuse the same map (to avoid an extra hash lookup in `Query`), provided the mapped `Name` property is always used rather than the map key when communicating with postgres. But either way, that all sounds ideal - certainly a better solution than (ab)using the statement cache.

**Comment by jackc** [comment]
Done in https://github.com/jackc/pgx/commit/bbe2653bc51361e5d7607729356344ef979a9f5a.
