### ISSUE TITLE
ILIKE does not work with wildcard similarity operator %

### ISSUE THREAD

**Issue by gronka** [jackc/pgx#1731]
**Describe the bug**
Get no results when using ILIKE search with wildcard similarity operator %

**To Reproduce**
```
stmt := `SELECT name,
    FROM categories
    WHERE name ILIKE %$1%
    LIMIT 20`

rows, err := pile.Pool.Query(pile.Ctx, stmt, query)
```

**Expected behavior**
Expected wildcard ILIKE query

**Actual behavior**
Returns error:
ERROR: syntax error at or near "$1" (SQLSTATE 42601)

**Version**
go version go1.21.0 linux/arm64
 PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
github.com/jackc/pgx/v5 v5.4.3

**Additional context**
I can't find anything relevant in the repo nor docs.

I found this solution which seems to work:
`SELECT name FROM categories WHERE name ILIKE '%' || $1 || '%' LIMIT 20`

Maybe the solution is to add something to the docs explaining what's going on here so that I can anticipate this issue in the future.

**Comment by jackc** [comment]
It's not a pgx issue. It's a SQL syntax error. The same thing would happen if you used `PREPARE` directly from psql.

**Comment by gronka** [comment]
Thanks. I'll assume you're right and close
