### ISSUE TITLE
Unable to identify statement timeout occurred until entire tx commit attempt

### ISSUE THREAD

**Issue by milanaleksic** [jackc/pgx#1739]
**Describe the bug**
I searched all the issues and couldn't unfortunately find my answer. I hope I am doing something wrong, since it feels wrong what I noticed, but I need some guidance or at least docs need to be updated to reflect the need to be clear about this.

Basically, I would expect that my transaction fails before commit since the query executed fails and is cancelled by the server. How can I know if a query failed before I attempt to commit the full transaction, since the failure (imho) should happen before?

**To Reproduce**
Here is a verifiable explanation of my problem: I can't get error to happen or to bubble up before I try a commit:

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

	ctx := context.Background()
	tx, err := conn.Begin(ctx)
	if err != nil {
		log.Fatalf("fail1: %v", err)
		return
	}
	defer func() {
		if err := tx.Commit(ctx); err != nil {
			log.Fatalf("fail2: failed to commit a transaction: %v", err)
		}
	}()

	// language=postgresql
	rowsSt, err := tx.Query(ctx, "SET LOCAL statement_timeout=100") // set in ms
	if err != nil {
		log.Fatalf("fail3: %v", err)
	}
	rowsSt.Close()

	// language=postgresql
	st2 := ` SELECT pg_sleep(5)`

	rows, err := tx.Query(ctx, st2)
	if err != nil {
		log.Fatalf("expected fail1: %v", err)
	}
	defer rows.Close()

	if rows.Err() != nil {
		log.Fatalf("expected fail2: %v", err)
	}
	for rows.Next() {
		if rows.Err() != nil {
			log.Fatalf("expected fail3: %v", err)
		}

		// irrelevant here, mostly for output capturing
		var output string
		if err := rows.Scan(&output); err != nil {
			log.Fatalf("expected fail5: %v", err)
		}
		log.Println(output)
	}
}

```

**Expected behavior**
A clear way to detect failure to execute statement `pg_sleep(5)` since (within this transaction) 5 seconds sleep is not possible since the statement timeout is set to `100ms`. Neither `expected fail1`, `expected fail2` nor `expected fail3` happens.

**Actual behavior**
What I actually get is:

```
2023/09/18 07:37:12 fail2: failed to commit a transaction: commit unexpectedly resulted in rollback
```

On the server side, however, I see this, proving that indeed statement was cancelled:

```
2023-09-18 07:37:12.438 CEST [48224] ERROR:  canceling statement due to statement timeout
2023-09-18 07:37:12.438 CEST [48224] STATEMENT:   SELECT pg_sleep(5)
```

**Version**
 - Go: `$ go version` -> `go version go1.20.2 darwin/amd64`
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> ` PostgreSQL 14.3 on x86_64-apple-darwin17.7.0, compiled by clang version 7.1.0 (tags/RELEASE_710/final), 64-bit`
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> `github.com/jackc/pgx/v5 v5.3.1`

**Comment by jackc** [comment]
`rows.Err()` must be checked _after_ the rows is closed (i.e. `rows.Close()` is explicitly called or `rows.Next()` has returned false).

**Comment by milanaleksic** [comment]
OK, Thanks @jackc. I'll close this issue
