### ISSUE TITLE
stdlib/GetPoolConnector: Before/AfterAcquire

### ISSUE THREAD

**Issue by zekth** [jackc/pgx#1740]
In this commit: https://github.com/jackc/pgx/commit/18856482c4e1483597c1c637ccf7b4e16fdd7f53

this was removed:
```go
func OptionBeforeAcquire(ba func(context.Context, *pgxpool.Pool) error) OptionOpenDB {
	return func(c *connector) {
		c.BeforeAcquire = ba
	}
}

// OptionAfterAcquire provides a callback for after acquire. Used only if db is opened with *pgxpool.Pool.
func OptionAfterAcquire(aa func(context.Context, *pgxpool.Conn) error) OptionOpenDB {
	return func(c *connector) {
		c.AfterAcquire = aa
	}
}
```

What's the rational for it? Is there hopes to have this back?
Would it be possible to have also `AfterRelease` ?

**Comment by lzakharov** [comment]
You can set this callbacks right inside your `pgxpool.Pool`. See `BeforeAcquire` and `AfterRelease` in [pgxpool.Config](https://pkg.go.dev/github.com/jackc/pgx/v5@v5.4.3/pgxpool#Config).
