### ISSUE TITLE
Support for per-resource metadata...

### ISSUE THREAD

**Issue by sean-** [jackc/pgx#1746]
Howdy.  I'm working on a library that extends `pgxpool` to:

1. Use the `AfterConnect` to identify the CockroachDB node being used for a given connection
2. Store and roll-up per-node timing using `BeforeAcquire`/`AfterRelease`

I was hoping to embed `pgx.Conn` in my own custom type and wrap all of the existing `pgxpool` types with custom variants that support the various metadata that I want to keep track of, but this is pretty laborious and leading to a lot of code duplication.

I think if `pgx.Conn` were ever converted to an `interface`, there would be a pretty sizable hit for the general population, and therefore not a viable proposal.

Has there been any thought of adding an `interface{}`, like `Meta interface{}` to `pgxpool.Conn`, `pgxpool.Pool`, and `pgxpool.Config`?  It would be an extra pointer per resource, but I think would be the most clean way to store per-resource information.

For the sake of discussion, something like this comes to mind:

```go
diff --git a/pgxpool/conn.go b/pgxpool/conn.go
index 36f90969..4918490c 100644
--- a/pgxpool/conn.go
+++ b/pgxpool/conn.go
@@ -11,8 +11,9 @@ import (
 
 // Conn is an acquired *pgx.Conn from a Pool.
 type Conn struct {
-	res *puddle.Resource[*connResource]
-	p   *Pool
+	res  *puddle.Resource[*connResource]
+	p    *Pool
+	Meta interface{} // User-specified connection metadata
 }
 
 // Release returns c to the pool it was acquired from. Once Release has been called, other methods must not be called.
diff --git a/pgxpool/pool.go b/pgxpool/pool.go
index 9f74805e..2d93173e 100644
--- a/pgxpool/pool.go
+++ b/pgxpool/pool.go
@@ -97,6 +97,8 @@ type Pool struct {
 
 	closeOnce sync.Once
 	closeChan chan struct{}
+
+	Meta interface{} // User-specified pool metadata
 }
 
 // Config is the configuration struct for creating a pool. It must be created by [ParseConfig] and then it can be
@@ -145,6 +147,8 @@ type Config struct {
 	HealthCheckPeriod time.Duration
 
 	createdByParseConfig bool // Used to enforce created by ParseConfig rule.
+
+	Meta interface{} // User-specified configuration metadata
 }
 
 // Copy returns a deep copy of the config that is safe to use and modify.
@@ -154,6 +158,7 @@ func (c *Config) Copy() *Config {
 	newConfig := new(Config)
 	*newConfig = *c
 	newConfig.ConnConfig = c.ConnConfig.Copy()
+	newConfig.Meta = c.Meta
 	return newConfig
 }
```

Which would unlock the following:

```go
type MyConnInfo struct {
  NodeID int
}

cfg.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
  var nodeID int
  err := crdb.Execute(func() error {
    err := conn.QueryRow(ctx, `SELECT crdb_internal.node_id()`).Scan(&nodeID)
    if err != nil {
      return err
    }
  }

  connInfo := MyConnInfo{
    NodeID: nodeID,
  }
  conn.Meta = connInfo

  return nil
}
```

I realize this isn't useful for vanilla PG targets, but for non-PG targets where extra information is only available at runtime, this is particularly useful.

Also, I couldn't think of another better solution to this class of problem, so if I'm missing something obvious, I'm all ears.  Thanks in advance.

**Comment by jackc** [comment]
For connections managed through pgxpool this can already be done by using `AfterConnect` and `BeforeClose`. These can be used to manage metadata in an application owned map keyed by `*Conn` or `PID`.

If that's insufficient I'm open to the idea of adding meta/custom data attachment points. Not sure on the name or how this field would be valuable for `Pool` or `Config`. Also, it might make sense on `pgx.Conn` instead of `pgxpool.Conn`.

**Comment by sean-** [comment]
Drat, I was hoping you weren't going to say that.  I was considering doing something with `pointer.Unsafe()` to slice off the struct, but this is more idiomatic.

Using `*Conn` makes sense because `pg_backend_pid()` is likely to be reused across different servers behind a load balancer.  With `BeforeClose()` it's possible to cleanup the resource out of a `map[]`, so I don't have to worry about key-reuse.

At the end of the day, I was hoping to avoid using a per-Pool `map[*Conn]ConnMeta` because I want to minimize the per-query overhead, which is why I was thinking about trying to do something `Conn`-local and adding a new go routine that would wake up once a second and flush its stats to a per-pool handler.

As for `Config`, I wanted to push down config that could be used in the various `Before*`/`After*` handlers, but can do that with a closure.

And agreed re: `pgx.Conn` vs `pgxpool.Conn`.  Let me chew on this more, but that was the background for my inquiry.

**Comment by sean-** [comment]
FWIW, I ended up doing the following to avoid doing a runtime lookup through a `map` in a performance-sensitive area of code.  Hat-tip to @bobvawter for the idea.

```go
package mypkg

type MyConn struct {
   net.Conn
   myMeta int
}

func NewWithConfig(ctx context.Context, cfg *pgxpool.Config) (*pgxpool.Pool, error) {
  if cfg.ConnConfig.DialFunc != nil {
    // FIXME(seanc@) figure out how to avoid a default Dialer so this can be a useful check
    fmt.Printf("WARN: DialFunc already set\n")
  }

  dialer := &net.Dialer{ // TODO(seanc@): Make tunable from Config?
    KeepAlive: 5 * time.Minute,
    Timeout:   10 * time.Second,
  }

  cfg.ConnConfig.DialFunc = func(ctx context.Context, network, addr string) (net.Conn, error) {
    c := &MyConn{}
    var err error
    c.Conn, err = dialer.DialContext(ctx, network, addr)
    if err != nil {
      return nil, err
    }

  cfg.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
    netConn := conn.PgConn().Conn()
    myConn := netConn.(*MyConn)
    fmt.Printf("myMeta: %d\n", myConn.myMeta)
  }

  p, err := pgxpool.NewWithConfig(ctx, cfg.Config)
  if err != nil {
    return nil, err
  }

  return p, nil
}
```

PS: The alternative solution to avoid some of the perf hit of a lock is to snag an exclusive lock after a new connection is established, copy the existing `map[*MyConn]MyMeta` and populate the copy with my new connection slot, perform an `atomic.Pointer` `CompareAndSwap()` of the updated `map[]`, and then perform dirty reads through the pointer, which also feels gross and violates my sense of aesthetic.  Anyway, hopefully the above is useful to you or someone else.

**Comment by jackc** [comment]
Cool. Glad you found a good solution. Bundling extra data in a `net.Conn` is clever. And FWIW, as I mentioned above, I'm not opposed to adding a `Metadata` / `CustomData` field somewhere. It's just someone would need to work through where it would best fit and actually implement it.
