### ISSUE TITLE
build error with pgx/v5 - import cycle not allowed

### ISSUE THREAD

**Issue by ivamshky** [jackc/pgx#1751]
using Go version: 1.21

go.mod file
```
module github.com/ivamshky/rssaggregator-go

go 1.21

require (
	github.com/go-chi/chi/v5 v5.0.10
	github.com/go-chi/cors v1.2.1
	github.com/google/uuid v1.3.1
	github.com/jackc/pgx/v5 v5.4.3
	github.com/joho/godotenv v1.5.1
)

require (
	github.com/jackc/pgpassfile v1.0.0 // indirect
	github.com/jackc/pgservicefile v0.0.0-20221227161230-091c0ba34f0a // indirect
	github.com/lib/pq v1.10.9 // indirect
	golang.org/x/crypto v0.9.0 // indirect
	golang.org/x/text v0.9.0 // indirect
)
```

build error: 
```
package github.com/ivamshky/rssaggregator-go
        imports github.com/ivamshky/rssaggregator-go/users
        imports github.com/jackc/pgx/v5
        imports github.com/jackc/pgx/v5/pgtype
        imports database/sql
        imports github.com/lib/pq
        imports database/sql: import cycle not allowed
```

even though I try to remove pgx/v5 dependency along with indirect ones and run `go build` again, it pull the second set of dependency and fails the build.

I am not using lib/pq library anywhere and have spent hours now to figure this out.
Any help would be appreciated.

Thanks

EDIT: 
pushed my code to github and ran `go mod tidy` and `go build` in Github Codespace. It worked in Codespace env.
So I tried cleaning up the cache folder in my home directory under `C:\Users\<myuser>\go\pkg\mod\cache` , still no luck in my local system. 😞 

If anyone got a clue, please let me know.

**Comment by metaleap** [comment]
>         imports database/sql
>         imports github.com/lib/pq

Sounds exceedingly unlikely that the former imports the latter. Played with `go mod why`?

Furthermore, neither `pgx` nor its dependencies seem to import `github.com/lib/pq` AFAICT

>I tried cleaning up the cache folder in my home directory under `C:\Users\<myuser>\go\pkg\mod\cache` , still no luck in my local system. 😞

Sometimes there's more than that folder, a more nukish thing to try would be `go clean -cache -modcache -i -r`

**Comment by iewher** [comment]
> Sometimes there's more than that folder, a more nukish thing to try would be `go clean -cache -modcache -i -r`

thanks, this solved my problem
