### ISSUE TITLE
sdtlib adapter PrepareContext doesn't cache prepared queries

### ISSUE THREAD

**Issue by Thiht** [jackc/pgx#1753]
**Describe the bug**
When using the sdtlib adapter, the `PrepareContext` doesn't make use of the cache of prepared queries.

See: https://github.com/jackc/pgx/blob/master/stdlib/sql.go#L421-L422

I guess it could be replaced with something like this:

```diff
- 	name := fmt.Sprintf("pgx_%d", c.psCount)
-	c.psCount++
+	digest := sha256.Sum256([]byte(query))
+	name := fmt.Sprintf("pgx_%x", digest)
```

This would ensure we don't prepare a same query multiple times

**To Reproduce**

```go
package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
)

type Tracer struct{}

func (*Tracer) TraceQueryStart(ctx context.Context, conn *pgx.Conn, data pgx.TraceQueryStartData) context.Context {
	return ctx
}

func (t *Tracer) TraceQueryEnd(ctx context.Context, conn *pgx.Conn, data pgx.TraceQueryEndData) {
}

func (t *Tracer) TracePrepareStart(ctx context.Context, _ *pgx.Conn, data pgx.TracePrepareStartData) context.Context {
	fmt.Println(data.Name)
	return ctx
}

func (t *Tracer) TracePrepareEnd(ctx context.Context, conn *pgx.Conn, data pgx.TracePrepareEndData) {}

func main() {
	dsn := os.Getenv("PGX_TEST_DATABASE")
	config, err := pgx.ParseConfig(dsn)
	if err != nil {
		panic(err)
	}
	config.Tracer = &Tracer{}

	dsn = stdlib.RegisterConnConfig(config)

	db, err := sql.Open("pgx", dsn)
	if err != nil {
		panic(err)
	}

	db.Prepare("SELECT 1")
	db.Prepare("SELECT 1")
	db.Prepare("SELECT 1")
}
```

Prints:

```
pgx_0
pgx_1
pgx_2
```

**Expected behavior**
The cached prepared query should be reused

**Actual behavior**
A new prepared query is created on each call

**Version**
 - Go: `$ go version` -> [go version go1.21.1 darwin/amd64]
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> [PostgreSQL 16.0 (Homebrew) on x86_64-apple-darwin23.0.0, compiled by Apple clang version 15.0.0 (clang-1500.0.40.1), 64-bit]
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> [v5.4.3]

**Additional context**

**Comment by jackc** [comment]
I don't think this is feasible. What happens if you [Close](https://pkg.go.dev/database/sql#Stmt.Close) one of those three statements? The other two would be broken.

You could avoid explicit prepared statements altogether and rely on the automatic statement caching.

**Comment by Thiht** [comment]
You're right, I completely missed the Close issue.

Thanks for the reply!
