### ISSUE TITLE
Need help with registering custom types with pgx/v5

### ISSUE THREAD

**Issue by vamshiaruru** [jackc/pgx#1755]
Hi everyone, I have tried looking, but I am unable to find a totorial on how to register custom types. I make use of a lot of JSONB fields and use go structs while inserting them into DB. This worked until now, but in production I have to enable simple mode, because we are behind RDS proxy. Things have stopped working now because pgx doesn't know how to encode these custom structs. Documentation says I have to use `RegisterDefaultPgType` to register my types. But I don't know where or how to use this function. I am also using pgxpool as client side connection pooler.

Any help is sincerely appreciated. Thank you.

**Comment by vamshiaruru** [comment]
Is this how it is done?
```go
		config.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
			// do something with every new connection
			conn.TypeMap().RegisterDefaultPgType(map[string]any{}, "jsonb")
			conn.TypeMap().RegisterDefaultPgType(coremodels.ProductOrgSpecificData{}, "jsonb")
			conn.TypeMap().RegisterDefaultPgType(coremodels.ProductSortingField{}, "jsonb")
			return nil
		}
```
If this is how it is done, how do I keep this clean? Structs are defined in multiple places in my code, how do I collate all these structs together without getting into circular import issues and so on?

**Comment by binrebin** [comment]
how about this one. I didint test it though
`ParseConfig: config.BeforeAcquire = func(ctx context.Context, conn *pgx.Conn) bool { 		RegisterDataTypes(ctx, conn) 		return true 	} `

**Comment by jackc** [comment]
You've got the right idea with `RegisterDefaultPgType`. And, yes, it may be awkward if you have many types that need to be handled this way. But pgx needs some way of knowing how to handle unknown types.

One other option is to a define a json wrapper type and only register that. Then use that wrapper at every call site. That avoids the need to register each type in exchange for changes at every call site.

Another possibility is to try `QueryExecModeCacheDescribe`. I think you can still use the extended protocol with RDS proxy.

**Comment by vamshiaruru** [comment]
> Another possibility is to try QueryExecModeCacheDescribe. I think you can still use the extended protocol with RDS proxy.

Thanks for the reply. However, RDS proxy doesn't support extended protocol from my understanding. I remember reading that the aws documentation used to say that session pinning happens when extended protocol is used. Now documentation says (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html#rds-proxy-pinning)

> RDS Proxy doesn't multiplex connections when your client application drivers use the PostgreSQL extended query protocol.

which I imagine is the same thing. That said I'll close this issue if the approach is correct. Thank you :D
