### ISSUE TITLE
Build from sourcecode

### ISSUE THREAD

**Issue by highgozhangyc** [jackc/pgx#1761]
Hi,
  I modified the code according to my needs and I want to compile it using the source code in vscode. I would like to ask how to compile the source code. I executed the 'go build' command in the source code directory and no error was output, but I cannot find the compiled output file. What else do I need to do?

Thanks.

**Comment by jackc** [comment]
This is a general Go question, not a pgx question. That said, you probably want to use the `replace` directive in the `go.mod` of your application that is using your fork of pgx.

For example, if your fork is on Github:

```
replace github.com/jackc/pgx/v5 => github.com/highgozhangyc/pgx/v5
```

Or if you want to use your fork directly from your file system:

```
replace github.com/jackc/pgx/v5 => ../path/to/your/fork/of/pgx
```


See https://go.dev/ref/mod#go-mod-file-replace for more info.
