### ISSUE TITLE
What is the difference between pipeline and batch mode?

### ISSUE THREAD

**Issue by MarioIshac** [jackc/pgx#1774]
With pgx5, queries can be sent with pipelining on a single connection, not waiting for a server response in between each. However, `pgx.Batch` also seems to allow that, likewise on a single connection.

This reply: https://github.com/jackc/pgx/issues/1091#issuecomment-932748336 says they are slightly different, but I couldn't manage to find any differences. Could someone shed some light on when to use one vs. the other?

**Comment by jackc** [comment]
Batching lets you queue multiple queries and send them all at once, typically in one or two round trips. Batching is implemented on top of pipeline mode when using the extended protocol.

Pipelining is lower level. It lets you control exactly what messages are grouped together and when those messages are actually flushed to the server.

In almost all cases the batch interface is to be preferred. However, pipeline mode can be used to reduce latency at the expense of being much more verbose and error prone to use. For example, if you had 5 queries to run and the 4th query was dependent on results from the 1st query you could do the following.

1. Send the first 3 queries
2. Read the result from the 1st query
3. Send the 4th and 5th queries
4. Read the results of the remaining 4 queries

This could have less latency than using two batches as the 4th and 5th queries could be sent before the 2nd query had finished.

**Comment by MarioIshac** [comment]
Thank you, fantastic explanation! The below snippet aligns with your description.

```golang
batch := pgx.Batch{}
batch.Queue("select pg_sleep(2);")
batch.Queue("select pg_sleep(4);")

before := time.Now()
batchRes := conn.SendBatch(context.Background(), &batch)

if _, err = batchRes.Exec(); err != nil {
	panic(err)
}
println("After 1 -", time.Now().UnixMilli()-before.UnixMilli())

if _, err = batchRes.Exec(); err != nil {
	panic(err)
}
println("After 2 -", time.Now().UnixMilli()-before.UnixMilli())
```

Output:
```
After 1 - 6006
After 2 - 6006
```

Out of curiosity, could the batching implementation be changed such that `After 1` is printed after 2 seconds, not 6? That way, pipelining would no longer have an advantage to use directly. I would think the batch API can remain the same, since individual `Exec` / `Query` / `QueryRow` calls are already required by the user.

**Comment by jackc** [comment]
> Out of curiosity, could the batching implementation be changed such that After 1 is printed after 2 seconds, not 6? That way, I believe there would no longer be an advantage to using pipelining directly.

Batching _could_ be done that way. In the PostgreSQL wire protocol there is a "flush" message that tells the server to send results back immediately. If every query was followed by a "flush" it would behave as you suggest.

However, that means the server is no longer able to bundle the results of multiple queries into a single write. Consider the case where 50 queries are batched together and each query has a minimal result. At the present the results could be sent with a single syscall on the server and they could fit in a single network packet. If each query was flushed individually there would be 50 syscalls and 50 network packets. A great deal of efficiency would be lost in this common case.

**Comment by MarioIshac** [comment]
I understand, thank you! Last question: even with pipelining **under a single connection**, there is no way for a connection to execute the two queries above concurrently / in parallel such `After 2` is printed after 4 seconds, right?

**Comment by jackc** [comment]
Correct.
