### ISSUE TITLE
How should I scan bytea to []byte using sql.DB and pgtype.SQLScanner wrapper?

### ISSUE THREAD

**Issue by ig0rmin** [jackc/pgx#1777]
Sorry if this question was already asked somewhere. I was curious if it's possible to scan `bytea` column to `[]byte` variable using `database/sql` connection and `pgtype.SQLScanner` helper. I tried to do it like this:
```
func SelectBytea(conn *sql.DB) error {
	row := conn.QueryRow(
		`SELECT  '\xDEADBEEF'::bytea AS B`,
	)

	var b []byte
	m := pgtype.NewMap()
	err := row.Scan(m.SQLScanner(&b))
	if err != nil {
		return err
	}
	fmt.Printf("%v", b)
	return nil
}
```
but got 
```
sql: Scan error on column index 0, name "b": invalid hex format. 
```

**Comment by jackc** [comment]
At first glance I would have expected this code to work without error. ~~Nothing immediately jumps out at me.~~ There's probably some internal confusion between the text and binary formats.

However, the entire approach shouldn't be necessary. You can scan into a `[]byte` directly from a `*sql.DB`. `pgtype.SQLScanner` shouldn't be needed at all.
