### ISSUE TITLE
"conn busy" / "driver: bad connection" despite the usual reasons for that error being absent

### ISSUE THREAD

**Issue by metaleap** [jackc/pgx#1790]
(Last para is kinda the tl;dr =)

What's the way to avoid this? pgx 5.5.0, also occurred before just-now updating which was 5.4.3. Postgres 16.x, the standard Docker container (local dev).

Using via `pgx/stdlib` interfaces.

I am iterating through a `Rows` and do a SELECT from another table in each operation (an "exists" query really). Depending on its result, there's INSERT into yet another table. The usual caveats don't apply:

- `defer rows.Close()` **is** ensured
- `Scan`ning before doing that query **is** ensured
- no-`break`-conditions (incl `panic`s) in the iteration loop, ensured
- no parallelism: ensured

The whole issue is **entirely preventable** using a new conn (presumably — rather that explicitly doing so (I only have one shared global `*sql.DB`), I use a new `Context` (custom impl) that is then essentially not in the current `Tx`, thus I presume the query/exec impl then picks a different conn from the pool).

But doing that for each row wasn't the plan here really, ideally  =)  other than the above 4 checklist items, what else would I have to check? (The scenarios I'm dealing with tend to require the reads to already occur within a `Tx`.)

The error is with `LevelDefault` and `LevelRepeatableRead` and `LevelReadCommitted` and `LevelReadUncommitted`.

Experimentally, with `LevelSerializable` or `LevelSnapshot`, another error: "could not serialize access due to concurrent update". But was banking on `LevelDefault` anyway. Mistaken notion?

Essentially, afaict at this point there is no (driver-supported) `IsolationLevel` where one can, in a `Tx`:

- iterate through table 1
- per iteration, query table 2
- per iteration, occasionally write to table 3.

**Comment by metaleap** [comment]
The scenario really is stream-through-really-indeed-all-of-dozens-of-thousands-up-to-gazillions-of-records-unfiltered from table1 (with a long enough timeout), accumulate very slim batch-insert "todos" in a pre-`cap`ped slice depending on querying table2 per iteration, occasionally in the same block also invoke the batch insert onto table3 whenever `len(accumBuf) == cap(accumBuf)` (which also resets the latter then).

Now those inserts are to succeed-or-fail all together. Hence, Tx. Maybe there's a better pattern for this scenario? It is not the idea to pre-_allocate_ all those gazillions from table1 first (to then Close the Rows), or even just their IDs.

**Comment by jackc** [comment]
It is not possible to execute another query while reading the results of a previous query. This is true regardless of transaction isolation level (or for that matter whether you are in a transaction at all). In addition, this is PostgreSQL protocol level issue, not specific to pgx.

While it is possible to send an additional query to PostgreSQL while reading the results of a previous query, but the results of the second query would be sent back after _all_ the results from the first query. There is no way to interleave them. And even this would require using the very low level pgconn pipeline interface -- it's not possible from database/sql.

---

> Maybe there's a better pattern for this scenario? It is not the idea to pre-allocate all those gazillions from table1 first (to then Close the Rows), or even just their IDs.

Unless you also have logic in Go, this could probably be done entirely in a single SQL statement with a writable CTE.

**Comment by metaleap** [comment]
Thanks, good to know! I had no idea tbh, this is older code I'm adapting into my newer code base where the old stuff originally operated against MongoDB, and so this sort of interleaving emerged back then because it was seemingly supported by that driver. Whether it actually guaranteed anything assumed and configured by me was never truly put to the test, though  =)

I'll adapt the use-cases to the Postgres reality. Muchos gracias @jackc !
