### ISSUE TITLE
(minor) Outdated docs: PgBouncer now supports prepared statements

### ISSUE THREAD

**Issue by ftambara** [jackc/pgx#1793]
In this [wiki page](https://github.com/jackc/pgx/wiki/Automatic-Prepared-Statement-Caching) it's noted that pgx's automatic prepared statement caching feature is incompatible with PgBouncer. It seems that with their [1.21](https://www.postgresql.org/about/news/pgbouncer-1210-released-now-with-prepared-statements-2735/) they added support for that.

**Comment by jackc** [comment]
Unfortunately, I don't think it changes anything for pgx. See https://github.com/jackc/pgx/discussions/1784.

**Comment by ftambara** [comment]
Oh I see. Sorry, I didn't see that issue. Thanks for the info.
