### ISSUE TITLE
Cancel Running Queries on Context Canceled

### ISSUE THREAD

**Issue by asturm-fe** [jackc/pgx#1794]
### Description

I have a long running query that is triggered by an http request.
The requests context is passed into pgx' `QueryRow`. When the client cancels the request, the running query is still executed until it finishes but the result can no longer be sent to the client.

### Wanted behavior

When the context is canceled, any query running with this context is also canceled (An appropriate error may be returned).

### Status Quo

Currently `pgconn` uses a context watcher to catch the event of a context canceled and triggers the following function:

``` go
func() { conn.SetDeadline(time.Date(1, 1, 1, 1, 1, 1, 1, time.UTC)) }
```

From the `SetDeadline` docs: 

>  A deadline is an absolute time after which I/O operations
	fail instead of blocking. The deadline applies to all future
	and pending I/O, not just the immediately following call to
	Read or Write.

So apparently my running query is not considered "pending" and is thus not aborted.

### Proposal

Instead of relying on `SetDeadline` to cancel operations associated with a canceled context, can we use the `pgConn.CancelRequest` functionality to more reliably (I'm aware of the inherent limitations) cancel any running queries?

**Comment by jackc** [comment]
It already does. The deadline causes the blocked network request to return an error which causes the connection to be closed. As part of the close connection process a`CancelRequest` is called. See https://github.com/jackc/pgx/blob/96f5f9cd952eccb28ce575089953c8ba7d99d77b/pgconn/pgconn.go#L655.

Also, see the test for this behavior [TestConnContextCanceledCancelsRunningQueryOnServer](https://github.com/jackc/pgx/blob/96f5f9cd952eccb28ce575089953c8ba7d99d77b/pgconn/pgconn_test.go#L2259).

**Comment by asturm-fe** [comment]
Thank you for the quick response!
Is this behavior true for a connection via `pgxPool` as well?
When I run my application in the debugger and cancel a request to my http server, I reach a breakpoint in the contextWatcher calling `cw.onCancel()` thus telling me the context that I handed to the query method was indeed canceled and the cancellation has been noticed by the connection. However, a breakpoint in `pgconn.go#L655` is never reached and I can see that my query still returns its result after x seconds even though the context is clearly canceled.

Calling pg_stat_activity with another connection shows the query with 
```
wait event type = Client
wait event = ClientRead
status = idle
```

For testing purposes, I used `select 'Test', pg_sleep(30)` as the query. In my normal setup this is a long running query with lots of joins.

**Comment by jackc** [comment]
Yes, this behavior also applies to connections managed via pgxpool.

Hard to say exactly what is going on in a debugger, but when stepping through only one goroutine is run at a time. In addition, there is a timeout on the async CancelRequest to ensure that there are no orphaned goroutines (15 seconds if I remember correctly). If you are stopping execution in the debugger, then it may be canceled before it starts.

**Comment by adrian-sturm** [comment]
Okay while trying to set up an example to reproduce the behavior of uncanceled queries I found my problem:
I had connected to the database via ssh and this apparently prevented the connection to close on context canceled....
While this answers most of this issue, I would still like to understand why this happens exactly and how I can still use ssh while preserving cancellation functionality.

Below is my ssh-connection code. I would be happy if anyone has advice on this matter.
```go
         sshConfig := &ssh.ClientConfig{
		User:            params.SSHUser,
		Auth:            []ssh.AuthMethod{},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(), 
	}
	sshcon, err := ssh.Dial("tcp", fmt.Sprintf("%s:%d", params.SSHHost, params.SSHPort), sshConfig)
	if err != nil {
		return fmt.Errorf("Can not connect to database via ssh: %v", err)
	}

	connPoolConfig, err := pgxpool.ParseConfig(connString)
	if err != nil {
		return fmt.Errorf("Can not parse config: %v", err)
	}
	connPoolConfig.ConnConfig.DialFunc = func(ctx context.Context, network, addr string) (net.Conn, error) {
		return sshcon.Dial(network, addr)
	}
	connection, err := pgxpool.NewWithConfig(context.Background(), connPoolConfig)
	if err != nil {
		return fmt.Errorf("Can not create new connection pool: %v", err)
	}
```

**Comment by jackc** [comment]
Unfortunately, the Go SSH library doesn't truly support deadlines. See https://cs.opensource.google/go/x/crypto/+/refs/tags/v0.15.0:ssh/tcpip.go;l=460

**Comment by asturm-fe** [comment]
I found a way to achieve my goal now. I'm not all happy because I had to work around a layer of abstraction but it works for me now.
Here is what I did:
Instead of using `pgxpool.QueryRow`, I manually handle the connection from the pool with
```go
// manually acquire and release connection to be able to send CancelRequest() on context canceled by client
c, err := p.Acquire(ctx)
defer c.Release()
if err != nil {
  return err
}
// start a custom context watcher
stopChan := make(chan bool)
go cancelQueryOnContextCanceled(ctx, c, stopChan)

row := c.QueryRow(ctx, sql, args...)
err = row.Scan(receiver)
// stop custom context watcher
stopChan <- true
if err != nil {
  return fmt.Errorf("Can not query database: %w", err)
}
```
And the code for my custom context watcher:
```go
// cancelQueryOnContextCanceled is an async context watcher to send a CancelRequest() if the context is canceled by client
func cancelQueryOnContextCanceled(ctx context.Context, c *pgxpool.Conn, stopChan chan bool) {
	// block until context is done or query returned
	select {
	case <-stopChan:
		// stop goroutine to avoid call to c.Conn() after c.Release()
		return
	case <-ctx.Done():
		err := c.Conn().PgConn().CancelRequest(context.Background())
		if err != nil {
			// query cancellation failed
			log.Warn(fmt.Sprintf("CancelRequest failed: %s", err.Error()))
		}
	}
}
```

On a side note: I also had to use the `DialTCP` method instead of `Dial` from `crypto/ssh` because `Dial` sets the connection address to 0.0.0.0 and prevents me from sending `CancelRequest()` on the same `pgConn`.
I don't understand why it does this but switching to `DialTCP` does the trick for me.
