### ISSUE TITLE
Jsonb type in struct

### ISSUE THREAD

**Issue by justintv90** [jackc/pgx#180]
Hi

Which datatype can I use to create a struct. I tried

```
type A struct {
         ID int
         Data map[string]string
}
```

but when i used Scan(&A), it threw an error said it couldn't parse data into Data.

Please help me, thanks

**Comment by ARolek** [comment]
@justintv90 IIRC pgx will scan JSON directly into a struct as long as your query casts the column as `::jsonb`. 

For example:

```go
type Foo struct {
	Bar string `json:"bar"`
}

var mystruct Foo
id := 1

sql := fmt.Sprintf(`
	SELECT 
		bar::jsonb
	FROM
		mytable 
	WHERE
		id=$1`)

//	fetch a single record
err := conn.QueryRow(sql, id).Scan(
	&mystruct.Bar,
)
```

**Comment by justintv90** [comment]
Please help, i dont know why

`	query := `
	SELECT
	id,
	data->'name',
	data->'site',
	data->'type',
	data->'status',
	data->'device'
	FROM projects
	WHERE user_id=$1
	`
	userData := new([]projectData)
	err := session.QueryRow(query, uid).Scan(&userData)
`

It will give error
`ERRO[0036] Scan received wrong number of arguments, got 1 but expected 6`

Please help, thanks

**Comment by justintv90** [comment]
I solved it, array_to_json works
