### ISSUE TITLE
Panic in prepared statesment

### ISSUE THREAD

**Issue by maksymnevajdev** [jackc/pgx#1818]
**Describe the bug**
If prepared arguments in sql string started with 0 - finish with panic(out of range -1 )
https://github.com/jackc/pgx/blob/master/internal/sanitize/sanitize.go:41
**To Reproduce**
Select * from table where id = $0
**Fix**

add 
`			if argIdx < 0 {
				return "", fmt.Errorf("first sql argument must be > 0")
			}`
in 
https://github.com/jackc/pgx/blob/master/internal/sanitize/sanitize.go:38

**Comment by maksymnevajdev** [comment]
I can't push fix to create a pull request.

**Comment by jackc** [comment]
Merged #1819
