### ISSUE TITLE
int64 but show error pg:int4

### ISSUE THREAD

**Issue by justintv90** [jackc/pgx#182]
I have this struct

type User struct {
       ID int64 json:"id"
       .....
}

type Project struct {
      ID int64
      UserID int64 // References to user_id above
...
}

When i use query 'SELECT \* FROM projects WHERE user_id = $1) it showed error

`1341396671631721500 is greater than max pg:int4`

How to fix it, please help. Thanks

**Comment by jackc** [comment]
I'm guessing that projects.user_id is an int4 (32-bit) in Postgres. But the integers are int64 (64-bit) in Go. In general, that's fine -- pgx will translate between them automatically. But if that value in the 64-bit number is too big to fit in the 32-bit number. Then this type error will occur. Does the number `1341396671631721500 ` have any special meaning such as is it an ID of something?

**Comment by justintv90** [comment]
projects.user_id is bigint in postgres, so the users.id. `1341396671631721500` is user.id what was generated by my function in postgres but i'm sure it's bigint as the output of my function.

**Comment by jackc** [comment]
Can you run `\d projects` in `psql` and post the results. I'm kind of confused because the only way you should see that error message is if `projects.user_id` is a PostgreSQL int4.

**Comment by justintv90** [comment]
Here is my sql script. Everything seems good, right ?

`CREATE SCHEMA shard_1;
CREATE SEQUENCE midway_1.global_id_sequence;`

Function : 

 `CREATE OR REPLACE FUNCTION midway_1.id_generator(OUT result bigint) AS $$
 DECLARE
 our_epoch bigint := 1314220021721;
 seq_id bigint;
 now_millis bigint;

shard_id int := 1;
BEGIN
SELECT nextval('midway_1.global_id_sequence') % 1024 INTO seq_id;

 SELECT FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000) INTO now_millis;
   result := (now_millis - our_epoch) << 23;
   result := result | (shard_id << 10);
    result := result | (seq_id);
 END;
 $$ LANGUAGE PLPGSQL;`

Tables : 

`CREATE TABLE shard_1.users(
     id bigint not null PRIMARY KEY default shard_1.id_generator(),
     data jsonb not null,
     created_at timestamptz not null default now(),
     updated_at timestamptz not null default now()
 );

 CREATE TABLE midway_1.projects(
     id bigint not null PRIMARY KEY default midway_1.id_generator(),
     user_id bigint not null REFERENCES midway_1.users(id) ON DELETE CASCADE,
     data jsonb,
     created_at timestamptz not null default now(),
     updated_at timestamptz not null default now()
 )`;

**Comment by jackc** [comment]
It looks right. Are you using the latest version of pgx? Also, do you have any code I can run that  reproduces this problem?

**Comment by justintv90** [comment]
Here is it

		query := `
		SELECT
		array_to_json(array_agg(row_to_json(t)))
		FROM (
			SELECT
			id,
			created_at,
			data->'name' as name,
			data->'site' as site,
			data->'type' as type,
			data->'status' as status,
			data->'device' as device
			FROM projects
			WHERE user_id=$1
		) t
		`
		userData := new([]projectData)
		err := session.QueryRow(query, id).Scan(&userData)

**Comment by jackc** [comment]
I had to change the data structure a bit to get it to run. The references between `midway_1` and `shard_1` schemas didn't work. So I changed all `midway_1` to `shard_1`. I then created a user and project with the ID you gave in the original example.

```sql
CREATE SCHEMA shard_1;
CREATE SEQUENCE shard_1.global_id_sequence;


CREATE OR REPLACE FUNCTION shard_1.id_generator(OUT result bigint) AS $$
DECLARE
our_epoch bigint := 1314220021721;
seq_id bigint;
now_millis bigint;

shard_id int := 1;
BEGIN
SELECT nextval('shard_1.global_id_sequence') % 1024 INTO seq_id;

SELECT FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000) INTO now_millis;
result := (now_millis - our_epoch) << 23;
result := result | (shard_id << 10);
result := result | (seq_id);
END;
$$ LANGUAGE PLPGSQL;



CREATE TABLE shard_1.users(
id bigint not null PRIMARY KEY default shard_1.id_generator(),
data jsonb not null,
created_at timestamptz not null default now(),
updated_at timestamptz not null default now()
);

CREATE TABLE shard_1.projects(
id bigint not null PRIMARY KEY default shard_1.id_generator(),
user_id bigint not null REFERENCES shard_1.users(id) ON DELETE CASCADE,
data jsonb,
created_at timestamptz not null default now(),
updated_at timestamptz not null default now()
);

insert into shard_1.users(id, data) values(1341396671631721500, '{}');
insert into shard_1.projects(user_id) values(1341396671631721500);
```

Then I ran the following test program:

```go
package main

import (
	"github.com/jackc/pgx"
	"log"
)

var conn *pgx.Conn

func main() {
	config, err := pgx.ParseEnvLibpq()
	if err != nil {
		log.Fatalln("Unable to extract config from env:", err)
	}

	conn, err = pgx.Connect(config)
	if err != nil {
		log.Fatalln("Unable to connection to database:", err)
	}

	var projectID int64
	err = conn.QueryRow("SELECT id FROM shard_1.projects WHERE user_id = $1", int64(1341396671631721500)).Scan(&projectID)
	if err != nil {
		log.Fatalln("Query failed:", err)
	}

	log.Println("Succeeded:", projectID)
}
```

It works for me.

```
jack@edi:~/dev/go/src/github.com/jackc/pgx-182$ PGHOST=/var/run/postgresql PGDATABASE=pgx182 go run main.go 
2016/09/24 12:05:22 Succeeded: 1346509728796115969
```

Your sample code uses schemas, but the queries do not explicitly select a schema. Is it possible that there is a `projects` or `users` table earlier in the search path that is not the one you are expecting. Perhaps a table that has an `int` instead of `bigint`...
