### ISSUE TITLE
Panic during QueryRow

### ISSUE THREAD

**Issue by Hades32** [jackc/pgx#1827]
**Describe the bug**

We're encountering the following panic sever times per week although that exact call/query is performed millions of times a day.
The query is a simple select, but returns (and binds) 39 columns.

```
panic({0x2db5660?, 0x555c7e0?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/jackc/pgx/v5/pgconn.(*Pipeline).Sync(0xc00bdd60c0)
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.0/pgconn/pgconn.go:2000 +0x16
github.com/jackc/pgx/v5.(*Conn).deallocateInvalidatedCachedStatements(0xc007468d80, {0x3bded98, 0xc00bb8cf60})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.0/conn.go:1363 +0x1eb
github.com/jackc/pgx/v5.(*Conn).Query(0xc007468d80, {0x3bded98?, 0xc00bb8cf60?}, {0x339508c, 0x2d7}, {0xc0069e5b70, 0x1, 0x1})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.0/conn.go:697 +0x109
github.com/jackc/pgx/v5.(*Conn).QueryRow(...)
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.0/conn.go:874
github.com/jackc/pgx/v5/pgxpool.(*Conn).QueryRow(0x3bded98?, {0x3bded98?, 0xc00bb8cf60?}, {0x339508c?, 0x7f56fef93188?}, {0xc0069e5b70?, 0x10?, 0xc00007c800?})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.0/pgxpool/conn.go:91 +0x45
```

**To Reproduce**
unknown

**Expected behavior**
no panic

**Actual behavior**
panic

**Version**
 - Go: `golang:1.21.5-bookworm` Docker tag
 - PostgreSQL: actually CockroachDB `v23.1.11`
 - pgx: `v5.5.0` and `v5.5.1`

**Comment by Hades32** [comment]
@jackc could this happen when the connection get's killed on the DB end?

**Comment by jackc** [comment]
v5.5.1 includes a fix related to deallocating statements. I suspect it may resolve this.

**Comment by Hades32** [comment]
Great, thank you. Will update and let you know if it helped

**Comment by danthegoodman1** [comment]
@jackc we just hit it again

```
goroutine 6625702 [running]:
panic({0x2dbc560?, 0x556a870?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/jackc/pgx/v5/pgconn.(*Pipeline).Sync(0xc007b5f2c0)
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.1/pgconn/pgconn.go:2049 +0x16
github.com/jackc/pgx/v5.(*Conn).deallocateInvalidatedCachedStatements(0xc0079290e0, {0x3be88b8, 0xc001bf7d70})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.1/conn.go:1373 +0x1eb
github.com/jackc/pgx/v5.(*Conn).Query(0xc0079290e0, {0x3be88b8?, 0xc001bf7d70?}, {0x339ddf7, 0x2d7}, {0xc008746980, 0x1, 0x1})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.1/conn.go:706 +0x109
github.com/jackc/pgx/v5.(*Conn).QueryRow(...)
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.1/conn.go:883
github.com/jackc/pgx/v5/pgxpool.(*Conn).QueryRow(0x3be88b8?, {0x3be88b8?, 0xc001bf7d70?}, {0x339ddf7?, 0x7fcdcc0e5948?}, {0xc008746980?, 0x10?, 0xc003045800?})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.1/pgxpool/conn.go:91 +0x3c
```

**Comment by jackc** [comment]
@danthegoodman1 That is a very strange place for a panic to occur. Have you run with the race detector?

**Comment by Hades32** [comment]
@jackc this happens in our production system and only very rarely (compared to the number of calls). I don't think we can easily run there with the race detector and it didn't happen in tests so far

**Comment by jackc** [comment]
I assume the panic is for a nil reference? That's all I can see that could occur there. But looking at the call stack I don't see how that is possible either... 🤔

**Comment by Hades32** [comment]
Ah sorry, I did cut that part of the trace. Yes, it's a nil dereference.

I don't see an obvious reason either...

**Comment by Hades32** [comment]
@jackc seems like Ryan figured it out. Do you think their PR is good?

**Comment by jackc** [comment]
Yes. The PR should resolve the panic.

**Comment by Hades32** [comment]
thanks @jackc! Would you mind creating a new tag that includes the fix?

**Comment by jackc** [comment]
v5.5.2 was just released.
