### ISSUE TITLE
DO $$ Statement not working

### ISSUE THREAD

**Issue by makubit** [jackc/pgx#1829]
**Bug description**
Cannot use `DO` statement in Exec() call with passed arguments. It seems that `$$` passed in DO statement doesn't work correctly during query rewrite.

**To Reproduce**
```
q := `
DO
$do$
	BEGIN
        IF EXISTS (
            SELECT
                    pos-1 as elem_index
            FROM
                table,
                jsonb_array_elements(column) with ordinality arr(elem, pos)
            WHERE
		    elem->>'name' = $1 AND
                    id = $2;
        ) THEN
            UPDATE
                Table
            SET
                ...
            WHERE
                    id = $2;
        ELSE
            UPDATE
                table
            SET
                ...
            WHERE
                    id = $2;
        END IF;
    END
$do$
`
p, err := dbConn.Conn.Exec(ctx, q, "param1", "param2")
```
error is: `mismatched param and argument count`
I also tried to use this query without passed arguments, as a string only, and in that case it's also returning an error with mismatched param and argument count.

**Behavior**
Arguments should be inserted in $1 and $2 places, but are not. After quick debugging, it seems that none of the arguments was recognized and the query doesn't fail on this part when I pass 0 arguments (ofc it's still not working).

**Version**
 - Go: `go1.21.4 darwin/amd64`
 - pgx: `github.com/jackc/pgx/v5 v5.5.0`

**Comment by jackc** [comment]
This is a PostgreSQL limitation. See https://github.com/jackc/pgx/discussions/1652.
