### ISSUE TITLE
Type mapping table

### ISSUE THREAD

**Issue by ds0nt** [jackc/pgx#183]
It would be very helpful to have a table where I could see what postgres type maps to what go type.

I've wasted hours.

I think it deserves a spot in the readme.

**Comment by ds0nt** [comment]
Debugging the cannot scan[x] into OID whatever is the issue that's been bugging me. To be clear. And i usually end up trying 3 or 4 types in go before it works.

There is documentation, somewhere. But it certainly wasn't obvious to me where it is. from the bugs. Then the github. Then the scrolling over it in the midst of the super-long godoc because it has no linky titles. Etc etc.

**Comment by jackc** [comment]
I added a listing of the base type mappings to the godoc and moved it closer to the top.

https://godoc.org/github.com/jackc/pgx#hdr-Base_Type_Mapping

**Comment by ds0nt** [comment]
Thanks!
