### ISSUE TITLE
Statement Cache Invalidation causes "expected 0 arguments, got 2"

### ISSUE THREAD

**Issue by jacobmikesell** [jackc/pgx#1852]
**Describe the bug**
A connection can be dirtied when context is cancelled during the statement cache cleaning step. 
In the test below I am simulating a context cancel by aquired then passing in a pre cancelled context

**To Reproduce**

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {

config, err := pgxpool.ParseConfig(os.Getenv("DATABASE_URL"))
	require.NoError(t, err)
	config.ConnConfig.StatementCacheCapacity = 3
	config.ConnConfig.DescriptionCacheCapacity = 3
	pool, err := pgxpool.NewWithConfig(context.Background(), config)
	require.NoError(t, err)

	ctx, cancelFunc := context.WithTimeout(context.Background(), time.Second*100)
	defer cancelFunc()

	cancelled, c := context.WithCancel(context.Background())
	c()

	for i := 0; i < 1000; i++ {
		itoa := strconv.Itoa(i)
		rows, err := pool.Query(ctx, fmt.Sprintf(`select '%s' where $1 = $2`, itoa), itoa, itoa)
		if err != nil {
			panic(t, errors.Join(err, rows.Err()))
		}
		rows.Close()

		c, err := pool.Acquire(ctx)
		if err != nil {
			panic(t, errors.Join(err, rows.Err()))
			return
		}

		rows, _ = c.Query(cancelled, fmt.Sprintf(`select '%s', 'test' where $1 = ''`, itoa), itoa)
		rows.Close()
		c.Release()
	}
}
```

Please run your example with the race detector enabled. For example, `go run -race main.go` or `go test -race`.

**Expected behavior**
No errors, all queries are prepared and executed well despite context cancellation

**Actual behavior**
Subsequent calls on the messed up connection get unexpected behavior

**Version**
 - Go: `$ go version` -> go version go1.20.4 darwin/arm64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` ->  PostgreSQL 13.12 on x86_64-pc-linux-gnu, compiled by Debian clang version 12.0.1, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.5.1

**Additional context**

**Comment by jackc** [comment]
Can you try master? There are some fixes related to the statement cache there.

**Comment by jacobmikesell** [comment]
Master appears to allow my test to pass! Whats the timeline for cutting a new version?

**Comment by jacobmikesell** [comment]
@jackc any update?

**Comment by jackc** [comment]
v5.5.2 was just released.
