### ISSUE TITLE
why does BatchTracer not have TraceBatchQueryStart/TraceBatchQueryEnd?

### ISSUE THREAD

**Issue by mrkagelui** [jackc/pgx#1857]
I'm trying to implement datadog tracing support for pgx (https://github.com/DataDog/dd-trace-go/pull/1537 FYI), and the BatchTracer interface is

```go
// BatchTracer traces SendBatch.
type BatchTracer interface {
	// TraceBatchStart is called at the beginning of SendBatch calls. The returned context is used for the
	// rest of the call and will be passed to TraceBatchQuery and TraceBatchEnd.
	TraceBatchStart(ctx context.Context, conn *Conn, data TraceBatchStartData) context.Context

	TraceBatchQuery(ctx context.Context, conn *Conn, data TraceBatchQueryData)
	TraceBatchEnd(ctx context.Context, conn *Conn, data TraceBatchEndData)
}
```

I'm just wondering why don't we have the start/end of the individual query, and should we? I'm sorry if this is how batch query works in the protocol, kindly let me know. Without the end, I'm afraid it might be hard to know when the individual query ends.

**Comment by jackc** [comment]
That's how the batch system works with the PostgreSQL protocol. All queries are sent at once. We know when we send them all, and we know when we finish receiving any individual query. `TraceBatchQuery` lets you trace when a query is finished, but there is no way to know when a query started.
