### ISSUE TITLE
Omit column in go struct

### ISSUE THREAD

**Issue by justintv90** [jackc/pgx#186]
#Hi

I used this struct 
```go
type projectData struct {
	ID         string     `json:"id" db:"-"`
	CreateddAt   time.Time  `json:"created_at" db:"-"`
	Name       string     `json:"name"`
```

My table is

```go
id string not null,
data jsonb not null,
created_at timestamptz not null default now(),
```

I want to omit the CreatedAt and ID columns when inserting because it will be generated automatically, but after running the query, i got the result

```go
{
"id": "idstring",
"created_at": "generated time",
"data": {
         "id": ""          `<-- empty string`
         "name": "Name",
         "created_at": "time string"      ` <-- not generated one, i though it was default string because this field doesn't have value passed from query`
    }
} 
```

How to omit the created_at and id field in data?

**Comment by jackc** [comment]
You didn't include the code that is inserting the data, so I'm not sure what you are doing now.

But if you are just using normal pgx and SQL and don't want to provide a value for an column in an insert, don't include it in the values. The below example code would use default values for every column except `name`.

```go
_, err = conn.Exec("insert into projects(name) values($1)", "Example project")
if err != nil {
	return err
}
```

**Comment by jackc** [comment]
One more thought. It's hard to tell because the markdown backtick and go backtick usage are conflicting so it's really hard to read, but if what you are trying to do is insert the Go struct into a JSON field instead of inserting it to a row then pgx just uses the standard `encoding/json`. So if you don't want a field to be serialized to JSON you would use its functionality. In particular, look at the [Marshal](https://golang.org/pkg/encoding/json/#Marshal) documentation. I think what you would want is something like the following:

```go

type projectData struct {
	ID         string     `json:"-"`
	CreateddAt   time.Time  `json:"-"`
	Name       string     `json:"name"`
}
```

You need to configure the JSON encoder, not pgx -- pgx just passes the struct to the standard JSON encoder and sends the raw bytes to PostgreSQL.

**Comment by justintv90** [comment]
Hi
Here is my table:

```sql
id string not null,
user_id string not null,
data jsonb not null,
created_at timestamptz not null default now(),
```

Here is my projectData struct

```go
type projectData struct {
	ID         string     `json:"id" dt:"-"`
	CratedAt   time.Time  `json:"created_at" db:"-"`
	Name       string     `json:"name"`
	Name2      string     `json:"name2"` 
	Site       string     `json:"site"`
	Device     int        `json:"device"`      
	BrowserBar int        `json:"browser_bar"` 
	Type       int        `json:"type"`        
	Email      string     `json:"email"`
	Status     int        `json:"status"`
	Tasks      []taskData `json:"tasks"`
}
```
The insert script:
```go

	// Initialing draft project
	draftProject := projectData{
		Name: "",
		Site: "",
		//TrackSesstion: track/session?uid={id}
		Device: 1,  // Default: Desktop
		Type:   1,  // TODO default or from request
		Email:  "", // TODO default or from request
		Status: 1,
		Tasks:  []taskData{},
	}

	query := `
	INSERT INTO projects (id, user_id, data)
	VALUES ($1, $2, $3::jsonb )
	`

	hash := RandString(10) // Length: 10

	result, err := session.Exec(query, hash, uid, &draftProject)
	if err != nil {
		log.Error(err)
		rCode = http.StatusInternalServerError
		return
	}

```
The id would be generated by RandString function, the created_at filed would generated by database automatically, However, i also want to get the id and created for fetching data so have to use Json field

After running the above script, I got that data in my database

```sql
id vqwe9A
created_at 12/09/2016
user_id mqlA123
data {
        id vqwe9A  // I dont want it
        created_at 0/0/0 // I dont want it
        ...rest
        }

```

**Comment by jackc** [comment]
So I took your example and made it self-contained: https://github.com/jackc/pgx186

I don't know how you are getting that data in your JSON because when I run it id and created at are empty.

```
$ createdb pgx186
$ psql -f structure.sql pgx186
Expanded display is used automatically.
Timing is on.
Null display is "∅".
CREATE TABLE
Time: 16.140 ms
$ PGHOST=/tmp PGDATABASE=pgx186 go run main.go
$ psql -c 'select * from projects' pgx186
     id     |  user_id   |                                                                                  data                                                                                  |          created_at
------------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------
 84679d5109 | 28e20760c7 | {"id": "", "name": "", "site": "", "type": 1, "email": "", "name2": "", "tasks": [], "device": 1, "status": 1, "created_at": "0001-01-01T00:00:00Z", "browser_bar": 0} | 2016-09-27 08:39:38.827125-05
(1 row)
```

**Comment by justintv90** [comment]
Yer, @jackc . 
It's my fault, your returned data is what i got.
I want to omit the blank `id` and `created_at` in data column. Can I do that? I think the  `db:"-"` didn't help. Is there any another solution?

Thanks

**Comment by jackc** [comment]
It's not `db:"-"`, it's `json:"-"`.

pgx just uses the standard `encoding/json`. So if you don't want a field to be serialized to JSON you would use its functionality. In particular, look at the [Marshal](https://golang.org/pkg/encoding/json/#Marshal) documentation. I think what you would want is something like the following:

```go

type projectData struct {
	ID         string     `json:"-"`
	CreateddAt   time.Time  `json:"-"`
	Name       string     `json:"name"`
}
```

You need to configure the JSON encoder, not pgx -- pgx just passes the struct to the standard JSON encoder and sends the raw bytes to PostgreSQL.

See the current version of https://github.com/jackc/pgx186 for working code that excludes those fields.

```
$ dropdb pgx186
$ createdb pgx186
$ psql -f structure.sql pgx186
Expanded display is used automatically.
Timing is on.
Null display is "∅".
CREATE TABLE
Time: 21.978 ms
$ PGHOST=/tmp PGDATABASE=pgx186 go run main.go
$ psql -c 'select * from projects' pgx186
     id     |  user_id   |                                                          data                                                          |          created_at
------------+------------+------------------------------------------------------------------------------------------------------------------------+-------------------------------
 83a3abf636 | 5718da069a | {"name": "", "site": "", "type": 1, "email": "", "name2": "", "tasks": [], "device": 1, "status": 1, "browser_bar": 0} | 2016-09-27 17:29:33.238143-05
(1 row)
```

**Comment by justintv90** [comment]
Ok got it. Thanks so much for your help @jackc

**Comment by justintv90** [comment]
@jackc 
I found the way to deal with my problem. I modified my struct into

```go
type projectData struct {
	ID          string      `json:"id,omitempty"`
	CreatedAt   *time.Time  `json:"created_at,omitempty"`
	Name        string      `json:"name"`
	Description string      `json:"description"` 
	Site        string      `json:"site"`
	Device      int         `json:"device"`      
	BrowserBar  int         `json:"browser_bar"` 
	Type        int         `json:"type"`       
	Email       string      `json:"email"`
	Status      int         `json:"status"` 
	Tasks       []*taskData `json:"tasks"`
}
```
I got the result such as I expected
`
"GHxMPyuv6K";"9pNBBujDZt";"{"name": "", "site": "", "type": 1, "email": "", "tasks": [], "device": 1, "status": 1, "browser_bar": 0, "description": ""}";"2016-09-28 14:02:27.347443+00";"2016-09-28 14:02:27.347443+00"`
