### ISSUE TITLE
CollectRows returns empty slice

### ISSUE THREAD

**Issue by dmitryuck** [jackc/pgx#1866]
```
type MenuDto struct {
	Id   uint8  `json:"id"`
	Name string `json:"name"`
}

fmt.Printf("Rows: %+v\n", rows)

accounts, err := pgx.CollectRows(rows, pgx.RowToStructByName[MenuDto])
if err != nil {
	fmt.Printf("Error CollectRows: %s", err)
	return nil, err
}

fmt.Printf("CollectRows: %+v\n", accounts)
```

**Rows:** &{typeMap:0xc00006a000 resultReader:0xc000076090 values:[[0 1] [115 116 111 114 101 45 109 101 110 117]] commandTag:{s:SELECT 1} err:<nil> closed:true scanPlans:[{} {}] scanTypes:[0xcd6000 0xcd5c80] conn:0xc000066240 multiResultReader:<nil> queryTracer:<nil> batchTracer:<nil> ctx:{emptyCtx:{}} startTime:{wall:13933696176808306028 ext:172998405001 loc:0x1246640} sql:
                SELECT id, name
                FROM menus
                ORDER BY id DESC;
         args:[] rowCount:1}

**CollectRows:** []

**Comment by jackc** [comment]
It appears you have already read the rows based on `closed:true`. A closed `Rows` cannot be read again.

**Comment by dmitryuck** [comment]
Here is a full code, not sure I'm closing rows before...

```
// GetMenus
func (t menuStorage) GetMenus() ([]dto.MenuDto, error) {
	conn, err := t.pool.Acquire(context.Background())
	if err != nil {
		fmt.Printf("Error acquiring connection: %s", err)
		return nil, err
	}
	defer conn.Release()

	rows, err := conn.Query(context.Background(), `
		SELECT id, name
		FROM menus
		ORDER BY id DESC;
	`)
	if err != nil {
		fmt.Printf("Error query: %s", err)
		return nil, err
	}
	defer rows.Close()

	var currMenuDto dto.MenuDto
	var menuDto []dto.MenuDto = []dto.MenuDto{}

	_, err = pgx.ForEachRow(rows, []any{
		&currMenuDto.Id,
		&currMenuDto.Name,
	}, func() error {
		menuDto = append(menuDto, currMenuDto)
		return nil
	})
	if err != nil {
		fmt.Printf("Error ForEachRow: %s", err)
		return nil, err
	}

	fmt.Printf("Rows: %+v\n", rows)

	accounts, err := pgx.CollectRows(rows, pgx.RowToStructByName[dto.MenuDto])
	if err != nil {
		fmt.Printf("Error CollectRows: %s", err)
		return nil, err
	}

	fmt.Printf("CollectRows: %+v\n", accounts)

	return menuDto, nil
}
```

**Comment by jackc** [comment]
`pgx.ForEachRow` reads the entire `rows` object leaving it closed.

**Comment by UlasSAYGINIM** [comment]
pgx v5 i am getting count 0 for records because there is no recods but i still get CollectRows result : []
postgresql 18.
no error for norows... github.com/jackc/pgx/v5 v5.8.0


	repo.db.log.Info("Il.FindAll başlatıldı",
		"operation", "Il.FindAll",
		"timestamp", time.Now(),
	)
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	query := `SELECT id, adi FROM public.iller ORDER BY adi ASC`

	rows, err := repo.db.pool.Query(ctx, query)

	// === ERROR HANDLING PHASE ===
	if err != nil {
		repo.db.log.Error("Il.FindAll başarısız",
			"operation", "Il.FindAll",
			"timestamp", time.Now(),
			"error", err,
		)
		return nil, errors.New("iller listesi alınamadı, lütfen tekrar deneyiniz.")
	}

	// === POST-EXECUTION VALIDATION ===
	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[entities.Il])
	if err != nil {
		return nil, errors.New("iller listesi işlenemedi, lütfen tekrar deneyiniz.")
	}

	fmt.Printf("CollectRows result : %+v\n", result)

	// === SUCCESS LOGGING ===
	repo.db.log.Info("Il.FindAll başarılı",
		"operation", "Il.FindAll",
		"count", len(result),
		"timestamp", time.Now(),
	)

	return result, nil

`

**Comment by UlasSAYGINIM** [comment]
issue 899 explanation is solved my problem but there must be explanation about it in documentation. or examples..

https://github.com/jackc/pgx/issues/899
