### ISSUE TITLE
pool acquire takes 70 - 100 ms on V5 and 2.633µs  on V4

### ISSUE THREAD

**Issue by floringavrila** [jackc/pgx#1881]
Hello,
My app is an HTTP API and I am using a pool, and then I share it to multiple repositories.
I am using defaults and only changed: connect_timeout=1&pool_min_conns=5&pool_max_conns=10
ex:
conf, err := pgxpool.ParseConfig(connString)
V4: pool, err := pgxpool.ConnectConfig(ctx, conf)
or:
V5: 	pool, err := pgxpool.NewWithConfig(ctx, conf)

Then, In my repository i am calling Query() function from Pool and then I am printing the stats:

queryCtx, cancel := context.WithTimeout(ctx, readTimeout)
defer cancel()
repo.postgresClient.GetPool().Query(queryCtx, query, params...)
fmt.Println(r.postgresClient.GetPool().Stat().AcquireDuration())

for version 5 it prints :  72.769878ms or even 162.444856ms
and for version 4 it prints: 2.633µs

I am running the test on my laptop with  Rhino linux +VPN, and the postgres server is on company datacenter.

Any hints,? what I am doing wrong ?

**Comment by jackc** [comment]
Have you tried multiple queries? I suspect the subsequent ones would be identical. I think that v4 eagerly creates a connection when the pool is created and v5 does not. So really you are measuring the cost to establish a connection.

**Comment by floringavrila** [comment]
Hello @jackc 
the code below, outputs these values: 
can you run it on your machine ?

try 1
73.379443ms
[40153365]
<nil>
try 2
73.380266ms
[40153365]
<nil>
try 3
73.380954ms
[40153365]
<nil>
try 4
73.381753ms
[40153365]
<nil>
try 5
73.382708ms
[40153365]
<nil>
try 6
73.383346ms
[40153365]
<nil>
try 7
73.384168ms
[40153365]
<nil>
try 8
73.385237ms
[40153365]
<nil>
try 9
73.385949ms
[40153365]
<nil>



`
package main

import (
	"context"
	"fmt"
	"strconv"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

func main() {
	ctx := context.Background()
	connString := "postgres://user:pass@host:5432/dbname?connect_timeout=1&pool_min_conns=5&pool_max_conns=10"
	conf, err := pgxpool.ParseConfig(connString)
	if err != nil {
		fmt.Println(err)
	}
	pool, err := pgxpool.NewWithConfig(ctx, conf)
	if err != nil {
		fmt.Println(err)
	}
	for i := 1; i < 10; i++ {
		fmt.Println("try " + strconv.Itoa(i))
		query := "SELECT product_id FROM user_actions where customer_id=123 limit 1"
		rows, err := pool.Query(ctx, query)
		fmt.Println(pool.Stat().AcquireDuration())
		if err != nil {
			fmt.Println(err)
		}
		actions, err := pgx.CollectRows(rows, pgx.RowTo[int])
		fmt.Println(actions)
		fmt.Println(err)
	}
}
`

**Comment by floringavrila** [comment]
Hey @jackc, you are right. Acquire is very fast. It shows a total of 162.444856ms because it includes the connection time. 
 But there  two issues: 
I tested with queries containing  where, sorting and a join between two tables at a rate of  360  queries / second for 10 minutes and : 
1. Creating a new connection takes too much time. I had to start with all connections opened ( min=30, max= 30). 
2. Your driver is still slow comparing with go-pg. 

![test_v4_v5_master](https://github.com/jackc/pgx/assets/3042674/e595a9cf-64df-4687-bb1d-b4d89c31fbe4)
![test_v5-5conn_v5_master](https://github.com/jackc/pgx/assets/3042674/3c0f109e-d108-4e96-9b66-1f356f1e7720)


Currently I am trying to get a replacement driver for go-pg because it is in maintenance mode

**Comment by jackc** [comment]
> I am running the test on my laptop with Rhino linux +VPN, and the postgres server is on company datacenter.

I didn't notice this before. That means any benchmarks results are almost certainly going to be dominated by the network.

If you can use the Go standard library to make a benchmark that can be run by other people and demonstrates something that is slower than it should be then perhaps someone can offer more suggestions.
