### ISSUE TITLE
No spans created for calls to CopyFrom

### ISSUE THREAD

**Issue by HTechHQ** [jackc/pgx#1893]
**Describe the bug**
The method `CopyFrom` is not traced.

I instrumented pgx to trace all my queries. All SQL queries are traced, except the ones using `CopyFrom`. As best as I can tell it looks like the `QueryTracer` is not used within that method.

**To Reproduce**

I am using the following implementation of `QueryTracer` and assign it to `config.ConnConfig.Tracer` when creating a new `*pgxpool.Pool`

```go
const spanKey arrower.CTXKey = "otel_span"

var _ pgx.QueryTracer = (*pgxTraceAdapter)(nil)

type pgxTraceAdapter struct {
	tracer trace.Tracer
}

func (p pgxTraceAdapter) TraceQueryStart(
	ctx context.Context,
	conn *pgx.Conn,
	data pgx.TraceQueryStartData,
) context.Context {
	ctx, span := p.tracer.Start(ctx, "pgx", trace.WithAttributes(
		attribute.String("db_host", conn.Config().Host),
		attribute.Int("db_port", int(conn.Config().Port)),
		attribute.String("db_database", conn.Config().Database),
		attribute.String("db_user", conn.Config().User),
		attribute.String("sql", data.SQL),
		attribute.StringSlice("sql_args", anySliceToStrings(data.Args)),
	))

	return context.WithValue(ctx, spanKey, span)
}

func (p pgxTraceAdapter) TraceQueryEnd(ctx context.Context, _ *pgx.Conn, data pgx.TraceQueryEndData) {
	if span, ok := ctx.Value(spanKey).(trace.Span); ok {
		span.SetAttributes(attribute.Int64("sql_rows_affected", data.CommandTag.RowsAffected()))

		if data.Err != nil {
			span.SetStatus(codes.Error, data.Err.Error())
		}

		span.End()
	}
}

func anySliceToStrings(in []any) []string {
	s := make([]string, len(in))

	for i := 0; i < len(in); i++ {
		s[i] = fmt.Sprintf("%v", in[i])
	}

	return s
}

```

**Expected behavior**
A span created for all queries/commands/calls to the database, including queries using `CopyFrom`

**Actual behavior**
No span is created when a query is using `CopyFrom`
Other queries (using `Exec` or `Query`) have spans as expected

**Version**
 - Go: `$ go version` -> go version go1.21.6 linux/amd64
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> v5.5.1 and v5.5.2

**Comment by jackc** [comment]
You need to implement [CopyFromTracer](https://pkg.go.dev/github.com/jackc/pgx/v5#CopyFromTracer).

**Comment by HTechHQ** [comment]
Thank you! I'll check into that :+1:
