### ISSUE TITLE
Schema in CopyTo?

### ISSUE THREAD

**Issue by davidsonff** [jackc/pgx#190]
How do I specify a schema in CopyTo? It seems to quote the entire string so that "schema.table" doesn't work... I think it should be "schema"."table", or am I missing something?

**Comment by jackc** [comment]
Sadly, I overlooked this when adding `CopyTo`. At the moment there is no way to copy to a schema qualified table.

There are a few ways of fixing this, all of which have down sides.

1. Add a schema argument as you did in PR #191. This is probably the simplest solution. On the downside, it breaks backwards compatibility. It also feels a little awkward for the signature of the function to require schema (even though it can be blank).
2. Add a new `CopyTo` function with schema and keep the old one around for backwards compatibility.
3. Drop quoting altogether. Applications should not pass a table name directly from a user without application level checks. But even so, it still feels not to escape/quote the argument. This would not trigger a compile error, but does change behavior so would also be somewhat backward incompatible.
3. Parse the table name and only quote table name if it is not already quoted. So `"schema"."table"` would be passed through unmodified. The would only be backward incompatible if someone had a table name that started with a quote -- I can't imagine anyone would do this. The more serious downside is perfectly detecting quoted identifiers. Also it feels a little like a hack.
4. Create an identifier struct that includes schema and table fields. Use that as arg to `CopyTo`. This breaks backwards compatibility, but it avoids needing to specify schema if you don't need it.
5. Use `[]string` as identifier. 1 element slice is just table. 2 element slice is schema, table. Again, this breaks compatibility, but avoids specifying schema.

I'm leaning toward 5, but I don't want to make a backwards incompatible change lightly.

**Comment by davidsonff** [comment]
My preference would be for #1 & #2 because it's just easier for the user to see schema as an argument and know what should go there...

**Comment by jackc** [comment]
Schema support added in new `CopyFrom` method in #246.
