### ISSUE TITLE
empty sslkey-file causes panic in `pgx.Connect`

### ISSUE THREAD

**Issue by gabor** [jackc/pgx#1915]
**Describe the bug**
if i use an empty-file as the `sslkey`, pgx will panic.

**To Reproduce**
create an empty file named `key.key`
then run this program:

```go
package main

import (
	"context"

	"github.com/jackc/pgx/v5"
)

func main() {
	pgx.Connect(context.Background(), "host=localhost sslkey=key.key sslcert=key.crt")
}
```

**Expected behavior**

`pgx.Connect` should return an error, if the sslkey is an empty file, it should not panic.

**Actual behavior**
`pgx.Connect` panics when sslkey is an empty file.
A clear and concise description of what actually happened.

**Version**
 - Go: `go version go1.22.0 darwin/arm64`
 - PostgreSQL:  postgres is not running
 - pgx: `v5.5.3`

**Additional context**
i think the problem is here: https://github.com/jackc/pgx/blob/5c63f646f820ca9696fc3515c1caf2a557d562e5/pgconn/config.go#L723-L728

`pem.Decode()` will return an error, but it is not checked. then `x509.IsEncryptedPEMBlock()` panics.

**Comment by jackc** [comment]
Fixed in 8896bd697781ed4aee392daa90b90cde142319fe.
