### ISSUE TITLE
pgx / pgxpool Interceptors aka Middleware (for caching, circuit breakers, etc.)

### ISSUE THREAD

**Issue by StevenACoffman** [jackc/pgx#1935]
### Problem Statement: Generic Interceptor (e.g. Caching) 
The pgx interface is faster than the `database/sql` interface. The pgx interface is faster. Many PostgreSQL-specific features such as LISTEN / NOTIFY and COPY are not available through the `database/sql` interface.

However, [ngrok/sqlmw](https://github.com/ngrok/sqlmw) provides `database/sql` interface interceptors (middleware).

This has facilitated use cases like [prashanthpai/sqlcache](https://github.com/prashanthpai/sqlcache) which provides a nice declarative mechanism for caching individual queries to improve performance. Other use cases like circuit breakers, retry mechanisms, etc. are also facilitated by having generic interceptor interfaces.

Specifically, I want to write an interceptor using the pgx / pgxpool interface that would provide for sqlcache, so that when the cache misses it would still use the faster pgx interface, and allow PostgreSQL-specific features.

**Describe the solution you'd like**
A package like  [ngrok/sqlmw](https://github.com/ngrok/sqlmw) specific to pgx / pgxpool to facilitate a generic caching layer like [prashanthpai/sqlcache](https://github.com/prashanthpai/sqlcache)  without resorting to the `database/sql` interface.

[prashanthpai/sqlcache](https://github.com/prashanthpai/sqlcache) relies on query "annotations", like so:

```sql
-- name: GetUsers :many
-- @cache-ttl 30
-- @cache-max-rows 10
SELECT * FROM users;
```

**Comment by jackc** [comment]
I'm open to additional extension points, but the proposal would need to be more specific. 

There are already several extensions points that overlap with a generic middleware, the tracing interfaces and the QueryRewriter interface in particular. Any new system would need to play nice with the existing architecture.

In addition, it should be something that has significant advantages over a wrapper or container. For example, with caching in particular, I would usually assume that caching would be more effective at a higher layer. That is, the final domain objects are cached, not the low-level row data that needs to be reparsed.

**Comment by StevenACoffman** [comment]
That's actually two great points.

Moving caching/retry/circuit breaker decisions outside of the driver (e.g. sqlc generated Go code) would perform even better by avoiding reparsing of the SQL.

Also, it's probably a better pattern to make cache domain objects.

**Comment by atombender** [comment]
@jackc I have a use case that I think requires more extension points:

I'd like to automatically decorate all executed SQL statements with a header comment to make it easier for developers and administrators to identify the source of a query when looking at logs or `pg_stat_activity`.  This comment includes contextual informational, such as an application-level "query name", API route, security principal, and similar things.

A decorated query might look like this:

```sql
-- app="FizzBuzz" name="DeleteUser" route="/v:version/users/delete/:id"
DELETE FROM users WHERE ... etc.
```

The caller can provide this information out of band by using some functions that add values to `context.Context`.

At the moment, I accomplish this explicitly by wrapping a transaction:

```go
func TxWithTagging(tx pgx.Tx) pgx.Tx {
	return &taggingTx{
		Tx: tx,
	}
}

type taggingTx struct {
	pgx.Tx
}

func (t taggingTx) Exec(ctx context.Context, sql string, args ...any) (commandTag pgconn.CommandTag, err error) {
	sql = decorateSQL(ctx, sql)
	return t.Tx.Exec(ctx, sql, args...)
}
// ...
```

However, `*pgx.Conn` is not an interface and cannot be wrapped the same way, so this has to be done at the application level. 

As far as I can see, this can't be accomplished today using the trace interface, and I also can't use the `QueryRewriter`, because it's supposed to be transparent to the caller. So an interceptor-type interface would be really useful.

**Comment by StevenACoffman** [comment]
@atombender You might look at how SQL Commenter was implemented for the SQL driver (and how people were hoping to add it to otelpgx)

- https://github.com/exaring/otelpgx/issues/39
- https://github.com/XSAM/otelsql/issues/109 
- https://github.com/jbub/sqlcommenter

**Comment by atombender** [comment]
@StevenACoffman They don't seem to have been successful at doing this with Pgx, though. I can see that using SQL Commenter through `sql.Driver` works, but I use Pgx directly.

**Comment by atombender** [comment]
Makes sense, agreed!

**Comment by jackc** [comment]
> I was mentioning it more because it helps to build support for @jackc accepting a PR, not because it helps you implement one. 

As I mentioned above, I'm not against the idea. But that's all it is at this point. There hasn't been any interface proposed or PR submitted.

---

One additional concern I would have is that this could have a negative impact on performance. In particular, adding something like a request ID to the SQL text as a comment would make the prepared statement cache counterproductive. You would have to fall back to an exec mode that took two round trips or forego the binary format.

An ideal interface for this idea would have some way of working with QueryExecModeCacheDescribe such that the annotated query was sent to PostgreSQL but the unannotated query was used to find the query description.

**Comment by winmillwill** [comment]
@jackc can you elaborate on what viable approaches might look like for passing a requestID-alike for use in other parts of the system (outside the go process, and perhaps not trusting the go process), especially if there's an optimal way of achieving that without modification to accommodate middleware? I imagine we can't "just" make the ID in the SQL comment a param of the prepared statement? Alternatively, is it possible to recover the session metadata from the pgx connection so that some transaction identifier or similar can be logged by the application so that it can be used to locate relevant logs from eg pgaudit? Is this an issue of adding more statements to a transaction and then whatever layers need to allow the user to find eg transactions with requestID, and then find the "real" statement(s) for those transactions?

Also, should I open a new issue for this?

**Comment by jackc** [comment]
@winmillwill 

> I imagine we can't "just" make the ID in the SQL comment a param of the prepared statement?

It _may_ be possible in certain circumstances, but I suspect that it would be limited enough and awkward enough not to be worth it.

> Alternatively, is it possible to recover the session metadata from the pgx connection so that some transaction identifier or similar can be logged by the application so that it can be used to locate relevant logs from eg pgaudit?

It should be possible to use the tracer interfaces to log whatever you want. Not sure how easy it would be to connect the dots from that to other logging and analytic systems.

---

I haven't thought extensively about it, but my previous message is still what I think the correct solution would be:

> An ideal interface for this idea would have some way of working with QueryExecModeCacheDescribe such that the annotated query was sent to PostgreSQL but the unannotated query was used to find the query description.

**Comment by StevenACoffman** [comment]
@jackc Currently, the pgx driver does support adding a `QueryRewriter` interface which gets passed as an arg. `RewriteQuery` is called after `TraceQueryEnd` as seen [here](https://github.com/jackc/pgx/blob/e68ff102de88423a0ffd4aecbc28dced4077b99f/conn.go#L457-L498) so you could create a wrapper for `pgx.Conn` that inserts a `QueryRewriter` that injects trace information as the first arg to method calls to the underlying `pgx.Conn`. 

> this could have a negative impact on performance. In particular, adding something like a request ID to the SQL text as a comment would make the prepared statement cache counterproductive. You would have to fall back to an exec mode that took two round trips or forego the binary format.
>
> An ideal interface for this idea would have some way of working with QueryExecModeCacheDescribe such that the annotated query was sent to PostgreSQL but the unannotated query was used to find the query description.

I think you mean that there would need to be a mechanism _similar_ to QueryRewriter, but that instead it would operate _after QueryRewriter makes any substantial changes_. Then this `QueryDecorator` / `QueryAnnotator` / `QueryCommenter` would produce a modified copy of the `sql` which is purely "decorated" like how SQLCommenter adds comments with RequestID or OTEL TraceID, SpanID, and similar data. If there was no provided QueryDecorator, or it made no modification, then the string would just point to the same original sql string (no-op).

That would allow you to distinguish between the annotated query to send to PostgreSQL [here I think?](https://github.com/jackc/pgx/blob/e68ff102de88423a0ffd4aecbc28dced4077b99f/conn.go#L545) but the unannotated query could still used to find the query description [here I think?](https://github.com/jackc/pgx/blob/e68ff102de88423a0ffd4aecbc28dced4077b99f/conn.go#L528)

**Comment by jackc** [comment]
@StevenACoffman I haven't thought through all the details, but yes, some sort of `QueryAnnotator` that runs after `QueryRewriter` is the general idea. Might need some sort of restructuring to play nice with tracing. Presumably the annotated SQL is what should be traced.

Another idea that just occurred to me would be for the described query cache to strip comments and normalize the SQL text. Not sure what the performance implications of that would be though.

**Comment by StevenACoffman** [comment]
@jackc I don't think you are currently in the PostgreSQL Hacking Discord, but if you are willing to join, [here is an invite link](https://discord.gg/SdMguR8K). There's a discussion there in the PostgreSQL `#drivers` channel [about standardizing trace propagation for all drivers that references this issue](https://discord.com/channels/1258108670710124574/1266451169094668349/1441443196373569668).

**Comment by ringerc** [comment]
@jackc and @StevenACoffman I've just been doing some work on improving distributed tracing capabilities for PostgreSQL. I have a demo that gets rid of the reliance on the SQL comment hack (and its problems) or the round-trips added by  using `SET` / `SET LOCAL` in favour of a backwards-compatible protocol-level mechanism for propagating trace context.  You can find references to the various patches and examples here https://gist.github.com/ringerc/3f701267ba8d26625f0bc993ff30412d - I'm trying to update that as I work. You may find it interesting. I've [followed up on the discord](https://discord.com/channels/1258108670710124574/1266451169094668349/1513770337735802992).
