### ISSUE TITLE
Scan to struct does not working

### ISSUE THREAD

**Issue by marvinlnnx** [jackc/pgx#1938]
I have followed the documentation on `go.dev` to see how to implement scan to struct, I followed the same instruction provided in the example it is not working,  [Here](https://pkg.go.dev/github.com/jackc/pgx/v5#example-RowToStructByName)
I am using this version:

"github.com/jackc/pgx/v5"

**Comment by marvinlnnx** [comment]
I have also tried, pgxpool , it is also not working, check this screenshot:

<img width="2406" alt="image" src="https://github.com/jackc/pgx/assets/150104050/9cf97e35-f869-486d-a146-eb2b1e7ed4f8">

**Comment by jackc** [comment]
It should be `pgx.RowToStructByName[MyBundle]` -- square braces instead of parentheses.

**Comment by marvinlnnx** [comment]
Thank you it works !

**Comment by marvinlnnx** [comment]
so should I use pgxpool or pgx only ?

**Comment by jackc** [comment]
`pgx.RowToStructByName` should work with both pgxpool or pgx.
