### ISSUE TITLE
Int4.Scan can't handle int32 input

### ISSUE THREAD

**Issue by RolandvdH** [jackc/pgx#1939]
Trying to scan an int32 into an pgtype.Int4 results in error.

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	var a int32 = 10
	length := &pgtype.Int4{}
	err := length.Scan(a)
	if err != nil {
		return nil, err
	}
}
```

err = cannot scan int32

I would like to think scanning of this type was allowed. As the code converts the scanning input to an int32 before returning.

**Comment by jackc** [comment]
It is against the `sql.Scanner` interface to call `Scan` with an `int32`. See https://pkg.go.dev/database/sql#Scanner.

But beyond that, the `Scan` method is specifically designed to scan / decode values from the `database/sql` layer. Whatever you are trying to do, there is probably another approach that would be more appropriate.

**Comment by RolandvdH** [comment]
Ah, good to know, thx.

I'm using sqlc with pgx and I'm trying to not to let too much technical implementation details drip into my API code. The sqlc generated structs contain pgtypes, so I'm looking for an 'easy' way to fill them with my API-input Go typed values, before inserting into the db.

If there's a more idiomatic way to do this than by Int4{10, true} (and so on for different types), please let me know.

**Comment by jackc** [comment]
> If there's a more idiomatic way to do this than by Int4{10, true} (and so on for different types), please let me know.

You may want to consider writing an `func Assign(destination, value any) error` function. This function would contain type switches to handle whatever combinations of `destination` and `value` you will use. And maybe a `MustAssign` wrapper to avoid error handling when you know the types and values are acceptable.
