### ISSUE TITLE
Issuing LISTEN while waiting for notifications

### ISSUE THREAD

**Issue by atombender** [jackc/pgx#195]
I'd like to start a goroutine that uses `WaitForNotification` to wait for the next notifications on a single connection. In other goroutines, I want to issue arbitrary `LISTEN` commands on the same connection so that a single, dedicated connection is used for all notifications. Shouldn't this be theoretically feasible?

It seems that since connections aren't thread-safe, they cannot be safely shared between goroutines without adding locking. On the other hand, you can't realistically put a lock around `WaitForNotification` because that would prevent the `LISTEN` from being executed in the first place, unless you do use a short timeout.

If I actually try this, I get protocol errors such as `Received unknown message type: C`, which is pretty much what I excepted.

The reason I can't execute all my `LISTEN` requests _before_ `WaitForNotification` is that I need to be able to `LISTEN` and `UNLISTEN` on demand. I'd like random callers (on different goroutines) to be able to register themselves for listening at any time. And I'd like there to be a single worker waiting for notifications.

Thoughts?

**Comment by jackc** [comment]
I would suggest your `WaitForNotification` goroutine use channels to handle other goroutines listen and unlisten requests. Something like the following pseudo-code.

```
for {
  for keepReading := true; keepReading {
    select {
    case subscribe := <-subChan:
      // Do listen
    case unsubscribe := <-unsubChan:
      // Do unlisten
    case default:
      keepReading = false
    }
  }

  WaitForNotification(shortTime)

  // Handle notifications...
}
```

**Comment by atombender** [comment]
That's technically better than a lock, although it complicates error propagation — my consumer API is synchronous, in the sense that a consumer likes to know that when a `Listen()` succeeds, listening has successfully started. I could change it so that `Listen()` is effectively async, and the client gets back both a channel for events and a channel for errors. Not ideal from an API point of view, though.

**Comment by jackc** [comment]
Like #196, it's difficult to have a different API due to the underlying logic being a blocking Read that can only be interrupted by a already set deadline.

However, you wouldn't have to change your consumer API to deal with error propagation, just the internals of the Listen func.

Given your `WaitForNotification` loop was something like I described above, here is some pseudo code for a Listen helper function.

```go
type listenRequest struct {
	channel string
	errChan chan error
}

func (*lm ListenManager) Listen(channel string) error {
	errChan := make(chan error)
	lm.subscribeChan <- &listenRequest{channel: channel, errChan: errChan}
	return <-errChan
}
```

And the modified WaitForNotification loop:

```go
for {
  for keepReading := true; keepReading {
    select {
    case subscribe := <-subChan:
      err := conn.Listen(subscribe.channel)
      subscribe.errChan <- err
    case unsubscribe := <-unsubChan:
      // Do unlisten
    case default:
      keepReading = false
    }
  }

  WaitForNotification(shortTime)

  // Handle notifications...
}
```

**Comment by atombender** [comment]
Yes, that's how I imagined it would look like. Thanks, I will see how that works out.

**Comment by WGH-** [comment]
Is it even a good idea to interrupt a `Read`, though? In very unfortunate case, you may interrupt it mid-packet, leaving the connection in broken inconsistent state.

I think this is the place where https://github.com/lib/pq does a better job than pgx. It has a dedicated connection type for notifications. It solves the problem of concurrent queries by having a separate goroutine that reads the server replies.

https://github.com/lib/pq/blob/9e747ca50601fcb6c958dd89f4cb8aea3e067767/notify.go#L186-L244

As a bonus, the code to gracefully handle reconnections is also in place.

**Comment by jackc** [comment]
> Is it even a good idea to interrupt a Read, though? In very unfortunate case, you may interrupt it mid-packet, leaving the connection in broken inconsistent state.

It's safe. pgx already has to handle a partially read message.

**Comment by WGH-** [comment]
> > Is it even a good idea to interrupt a Read, though? In very unfortunate case, you may interrupt it mid-packet, leaving the connection in broken inconsistent state.
> 
> It's safe. pgx already has to handle a partially read message.

I didn't belive it at first, but no matter how hard I tried to break it - funnelling a TLS connection through 100 b/s proxy - I didn't succeed :). So yeah, I suppose it's safe.
