### ISSUE TITLE
Retrieve client warning

### ISSUE THREAD

**Issue by bersace** [jackc/pgx#1952]
Hi,

Thanks for pgx. It's awesome.

I wonder how to retrieve client warning. e.g. when revoking a role you're not the grantor:

``` sql
> REVOKE "writers" FROM "alain";
WARNING:  role "alain" has not been granted membership in role "writers" by role "ldap2pg"
REVOKE ROLE
>
```

I may fail to found how in the documentation. Can you give me pointer ?

Regards,
Étienne

**Comment by jackc** [comment]
You want to set `OnNotice` when you connect. https://pkg.go.dev/github.com/jackc/pgx/v5@v5.5.5/pgconn#Config
