### ISSUE TITLE
WaitForNotification cannot be canceled

### ISSUE THREAD

**Issue by atombender** [jackc/pgx#196]
This is really about convenience related to my tests: I have a barrage of tests that all set up a clean database and various connections at the beginning of the test, and tears everything down at the end. Since `WaitForNotification` isn't interruptible, it means that my "listen manager" has to wait at least the duration specified in the wait argument before it's able to safely close down and release its connection. Even if the timeout is short, it has a big impact: My tests normally take about 4 seconds to run and now take about 50 seconds to run because of this.

**Comment by jackc** [comment]
`WaitForNotification` boils down to a `Read` on the underlying `Conn`. A timeout is the only way I know to break out of a read (well, other than closing the connection). I don't know of a way to interrupt an already in progress read. Documented behavior for [net.Conn SetReadDeadline](https://golang.org/pkg/net/#Conn) is to affect _future_ reads, so it is too late once the read is in progress.

How short of a timeout are you using? You should be able to use much less than 100ms.

**Comment by atombender** [comment]
Indeed. I'm surprised/disappointed that Go apparently doesn't support the classic async patterns from C (`select()`, `epoll()` and so forth), which would make this stuff easier. I'm all for synchronous APIs, but they also make this sort of thing harder.

I've reduced my timeout to 100ms. There's something unaesthetic about waking up that often, but I suppose I can live with it. Thanks.
