### ISSUE TITLE
TLS errors are logged as errors even when fallback is enabled

### ISSUE THREAD

**Issue by atombender** [jackc/pgx#198]
If you connect to a PostgreSQL instance that doesn't use TLS, and using TLS fallback mode, you still get two misleading errors:

```
16:20:49.750 ERROR TLS failed: server refused TLS connection
16:20:49.750 ERROR server refused TLS connection
```

There are two problems here:

* This will be confusing to anyone who reads the log, because the connection actually worked. The duplicate message doesn't help, either.
* It's logged as `ERROR`, even though the connection did succeed. It ought to be `INFO`. (It doesn't really qualify as a warning, since the client _did_ say that non-TLS was just fine.)

I could submit a PR, but due to how logging is handled in `connect()`, the only clean way to fix this, that I can see, is to pass an argument to the connection logic to say whether to log the error as a warning or as an error.

**Comment by atombender** [comment]
Awesome, thanks!

**Comment by jackc** [comment]
It might not be a perfect solution, but 3734a92 should resolve this. It moves the logging up one level to control whether it is info or error.
