### ISSUE TITLE
Make error codes public

### ISSUE THREAD

**Issue by vitalyisaev2** [jackc/pgx#1984]
@jackc thanks for making error types public (#1773), but could you please export [constants](https://github.com/jackc/pgx/blob/a3d9120636fc263debce595f3ba05bcd9f4ee809/pgconn/pgconn.go#L182-L185) like `ERRCODE_INVALID_PASSWORD` too? This would be very helpful for correct error code matching on the side of the application. For instance, one might want to implement custom behavior if user provided incorrect credentials. This behavior will differ from the behavior in case of network unavailability.

**Comment by jackc** [comment]
See https://github.com/jackc/pgerrcode. It has all PostgreSQL error codes.
