### ISSUE TITLE
Support scanning time type into string

### ISSUE THREAD

**Issue by matthewmueller** [jackc/pgx#2002]
**Describe the bug**

In `pgx/v5`, you can no longer scan postgres `time` types into a `string`. While in a prior version, this was possible.

**To Reproduce**

In `pgx/v5`

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/jackc/pgx/v5"
)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	conn, err := pgx.Connect(context.TODO(), "postgres://localhost:5432/pogo?sslmode=disable")
	if err != nil {
		return err
	}
	defer conn.Close(context.TODO())
	result := ""
	if err := conn.QueryRow(context.TODO(), "SELECT '08:00'::time without time zone").Scan(&result); err != nil {
		return err
	}
	fmt.Println(result)
	return nil
}

```

Results in `can't scan into dest[0]: cannot scan time (OID 1083) in binary format into *string`.

While in `pgx` (`v3.6.2+incompatible`):

```go
package main

import (
	"fmt"
	"log"

	"github.com/jackc/pgx"
)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	cfg, err := pgx.ParseConnectionString("postgres://localhost:5432/pogo?sslmode=disable")
	if err != nil {
		return err
	}
	conn, err := pgx.Connect(cfg)
	if err != nil {
		return err
	}
	defer conn.Close()
	result := ""
	if err := conn.QueryRow("SELECT '08:00'::time without time zone").Scan(&result); err != nil {
		return err
	}
	fmt.Println(result)
	return nil
}
```

It returns `08:00:00`.

**Expected behavior**

It'd be nice to support scanning into a string. Currently the `time` type in `pgx/v5` supports scanning into `time.Time`, but that can be a bit unclear in Go because `time.Time` includes the date.

**Actual behavior**

I think it'd be great to support both options, scanning into a string to bring back the old behavior as well as scanning into a `time.Time`

**Version**
 - Go: `go version go1.22.0 darwin/arm64`
 - PostgreSQL: `PostgreSQL 14.11 (Homebrew) on aarch64-apple-darwin23.2.0, compiled by Apple clang version 15.0.0 (clang-1500.1.0.2.5), 64-bit`
 - pgx: `v5.5.5`

**Additional context**

Thanks!

**Comment by jackc** [comment]
You can also scan into a `pgtype.Time`.

I've added support to scan a binary `time without time zone` into a string in 48cdd7bab0eed40bd7b35b40f7946269b9e6da94. This logic is already in place for types like `integer`. It's not ideal as it requires parsing the binary and then encoding it into text, but I suppose it is more convenient. However, this may not give you exactly the same representation as directly selecting the value in the text format. That is, you may get `08:00:00.000000` instead of `08:00:00`.

**Comment by matthewmueller** [comment]
Thanks so much for this fix! This saved so much time in the upgrade from v3 to v5. I confirmed that time as strings come back with `.000000`. I can format this on my end.

If you also have a chance to bump the minor, I'd really appreciate it. Currently pulling this from master.

Thanks again!
