### ISSUE TITLE
Param overriding doesn't work for some fields

### ISSUE THREAD

**Issue by cat1s-smile** [jackc/pgx#2003]
**Describe the bug**
I'm trying to create Config by parsing empty conn string and getting auth error
`failed to connect to 'host=localhost user=test database=test_namespace': failed SASL auth (FATAL: password authentication failed for user "test" (SQLSTATE 28P01))`

**To Reproduce**
Create Config by parsing empty conn string, fill required params and try to connect to DB

If possible, please provide runnable example such as:

```go
package main

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

func main() {
	cfg, _ := pgxpool.ParseConfig("")
	cfg.ConnConfig.Host = "localhost"
	cfg.ConnConfig.Port = 5444
	cfg.ConnConfig.Database = "test_namespace"
	cfg.ConnConfig.User = "test"
	cfg.ConnConfig.Password = "test"
	pgp, err := pgxpool.NewWithConfig(context.Background(), cfg)
	if err != nil {
		log.Fatal(err)
	}
	rs, err := pgp.Query(context.Background(), "select 1")
	fmt.Println(err)
	fmt.Println(rs.Next())
	fmt.Println(rs.Values())
}
```

**However if I change exactly one line with config parsing**  
`cfg, _ := pgxpool.ParseConfig("port=5444 database=test_namespace")`
everything works properly

**Expected behavior**
successful run after soecifying all the params as `cfg.ConnConfig.ParamName = ...`

**Actual behavior**
`failed to connect to 'host=localhost user=test database=test_namespace': failed SASL auth (FATAL: password authentication failed for user "test" (SQLSTATE 28P01))`

**Version**
 - Go: go1.22.1 windows/amd64
 - PostgreSQL:  PostgreSQL 12.2 (Debian 12.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
 - pgx: v5.5.5

**Additional context**

**Comment by jackc** [comment]
From the docs for [pgconn.ParseConfig](https://pkg.go.dev/github.com/jackc/pgx/v5@v5.5.5/pgconn#ParseConfig):

> The returned *Config may be modified. However, it is strongly recommended that any configuration that can be done through the connection string be done there. In particular the fields Host, Port, TLSConfig, and Fallbacks can be interdependent (e.g. TLSConfig needs knowledge of the host to validate the server certificate). These fields should not be modified individually. They should all be modified or all left unchanged.

Some types of connection attempts such as multiple hosts (for HA) and the default PGSSLMODE=prefer are implemented via "fallback configs". A fallback config is a different `Host`, `Port`, and `TLSConfig`. This means it tries the connection with first with the base config and then it tries each fallback config and uses its `Host`, `Port`, and `TLSConfig`. 

Presumably, the connection config that actually works is one of the fallback configs and that is not changed by updating the top-level `Config.Port`.
