### ISSUE TITLE
Custom JSON marshal/unmarshal

### ISSUE THREAD

**Issue by mitar** [jackc/pgx#2005]
**Is your feature request related to a problem? Please describe.**

I have two use cases where I think custom function to do JSON marshal/unmarshal would help (instead of default `json.Marshal`/`json.Unmarshal`:

* I want to marshal with `SetEscapeHTML(false)` set, because there is no point in escaping HTML when storing into a database. Similarly, I want to set `KnownFields(true)` when unmarshal, to detect errors early.
* I want to store a polymorphic JSON into a database (one where depending on its `type` field it gets unmarshal into different structs), the type being an interface. So I would use a custom unmarshal function which first checks the type and then does the rest.

**Describe the solution you'd like**

Some easy way to specify the default `json.Marshal` and `json.Unmarshal` function to be used.

**Describe alternatives you've considered**

It seems I could remove the json codec and create my own copy of it, with only difference being that it does not call `json.Marshal`. I would like to avoid having to maintain such a copy where the only difference is in the function which gets called.

**Comment by jackc** [comment]
You could implement `json.Marshaler' and `json.Unmarshaler` on your types that need this special behavior.

I think you could also insert your own logic in `Map.TryWrapEncodePlanFuncs` and `Map.TryWrapScanPlanFuncs`.

`JSONCodec` could be changed in a similar manner to 33360ab479cc29dd23adb848504bad01b7ff25b3 to allow for adding configuration. I'm not sure exactly what the interface would be though. If such a change is to be made it should allow for using entirely different json encoders (such as the rumored json/v2 or entirely third party json libraries).

**Comment by mitar** [comment]
> You could implement `json.Marshaler` and `json.Unmarshaler` on your types that need this special behavior.

Sure, but then I have to do it on all types. It is a bit cumbersome.

> I'm not sure exactly what the interface would be though. If such a change is to be made it should allow for using entirely different json encoders (such as the rumored json/v2 or entirely third party json libraries).

Oh, that is easy: `func (input any) ([]byte, error)` For both `json/v2` and third party JSON libraries then you can provide a closure or a wrapper function which does any extra initialization or anything you want. See [example in zerolog](https://github.com/rs/zerolog/blob/master/globals.go#L86-L100).

If you are open, I can make a PR adding such configuration option?
