### ISSUE TITLE
change of tenant for multi tenancy using pgxpool is not working

### ISSUE THREAD

**Issue by yakkalabhargav235** [jackc/pgx#2007]
**Describe the bug**

I am working on multi-tenancy in postgres. I faced the issue when a tenant info is provided, the response is provided with respect to that tenant. When tenant is changed the response contains information of previous tenant 
**To Reproduce**
1> create a schema and table and enable row level security
2>  set one tenant (ex: "bmw") . Perform the Select query.
3> Response contains only bmw tenant rows
4> give another tenant (ex: "audi"), and perform select query
5>  Response has the rows of bmw tenant

If possible, please provide runnable example such as:

```go
package main

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

var db *pgxpool.Pool

type tenantdetails struct {
	tenantid  string
	projectid string
	iedtype   string
	iedname   string
}

func main() {
	// Initialize database connection pool
	connString := "postgres://golang:golang@localhost:5432/postgres"
	poolConfig, err := pgxpool.ParseConfig(connString)
	if err != nil {
		log.Fatal("error parsing connection string:", err)
	}
	ctx := context.Background()
	db, err = pgxpool.ConnectConfig(context.Background(), poolConfig)
	if err != nil {
		log.Fatal("error connecting to database:", err)
	}
	defer db.Close()

	for {
		query := "SET search_path='public,substation';"
		conn, err := db.Acquire(ctx)
		if err != nil {
			fmt.Println("error", err)
		}
		_, err = conn.Exec(ctx, query)
		if err != nil {
			
			return
		} else {
			log.Println("set search path to ", query)
		}

		var tenant string
		fmt.Println("Enter your tenant:")
		fmt.Scan(&tenant)
		sqlQuery := "SET app.current_tenant = '{ System, ?}'"
		sqlQuery = strings.ReplaceAll(sqlQuery, "?", tenant)
		fmt.Println("query is", sqlQuery)
		_, err = conn.Exec(ctx, sqlQuery)
		if err != nil {
			return
		} else {
			log.Println("set tenant id to ", tenant)
		}

		query = "SELECT * FROM substation.instance"
		rows, err := conn.Query(ctx, query)
		if err != nil {
			fmt.Println("Error executing query:", err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			details := tenantdetails{}

			if err := rows.Scan(&details.projectid, &details.tenantid, &details.iedtype, &details.iedname); err != nil {
				fmt.Println("Error scanning row:", err)
				continue
			}
			fmt.Println("response ", details) 

		}
		defer rows.Close()
		conn.Release()
	}

}

```

Please run your example with the race detector enabled. For example, `go run main.go`.

**Expected behavior**
output:
Enter your tenant:
bmw
query is SET app.current_tenant = '{ System, bmw}'
2024/05/09 18:36:37 set tenant id to  bmw
query SELECT * FROM substation_config_generator.iedinstance
response {bmw bmw bmw_ied bmw_iedname}
2024/05/09 18:36:37 set search path to  SET search_path='public,substation_config_generator';
Enter your tenant:
audi
query is SET app.current_tenant = '{ System, audi}'
2024/05/09 18:36:41 set tenant id to  audi
query SELECT * FROM substation_config_generator.iedinstance
response {bmw bmw bmw_ied bmw_iedname}

**Actual behavior**
Enter your tenant:
bmw
query is SET app.current_tenant = '{ System, bmw}'
2024/05/09 18:36:37 set tenant id to  bmw
query SELECT * FROM substation_config_generator.iedinstance
response {bmw bmw bmw_ied bmw_iedname}
2024/05/09 18:36:37 set search path to  SET search_path='public,substation_config_generator';
Enter your tenant:
audi
query is SET app.current_tenant = '{ System, audi}'
2024/05/09 18:36:41 set tenant id to  audi
query SELECT * FROM substation_config_generator.iedinstance
response  {audi audi audi_ied audi_iedname}

**Version**
 - Go: [ go1.22.2 windows/amd64]
 - PostgreSQL:  -> [PostgreSQL 16.2, compiled by Visual C++ build 1937, 64-bit]
 - pgx:  [github.com/jackc/pgx/v5 v5.5.5]

**Additional context**

**Comment by jackc** [comment]
I don't have any way of running that without the database structure, but I'm guessing that the problem is that the queries are somehow not being run on the connection you think they are. i.e. they are getting different connections from the pool. Your example looks correct, but as I said, I wasn't able to run it.

Do you get the same error when running directly with a single connection?

**Comment by yakkalabhargav235** [comment]
We observed few things after some more investigation. 
1. This issue is not observed when we use where condition with tenantId.
2. This issue is not observed in JDBC template with hikari 
3. We have removed the immutable tag in our tenantid extraction procedure
 As you requested I have provided the below details
 
CREATE SCHEMA IF NOT EXISTS substation;
CREATE TABLE IF NOT EXISTS substation.instance (ProjectId VARCHAR,TenantId VARCHAR,IEDType VARCHAR,IEDName VARCHAR) PARTITION BY LIST (TenantId);

CREATE POLICY tenant_isolation_policy_instance ON substation.instance USING ((TenantId)::text = ANY ( get_tenant_id_array('app.current_tenant')));


create or replace function get_tenant_id_array(setting text) returns text[] as $$
select current_setting(setting)::text[]
$$ language sql immutable;

This query is causing the issue which is working JDBC not in GO. If the procedure is changed to below query it is working.

create or replace function get_tenant_id_array(setting text) returns text[] 
language plpgsql  as 
$$
begin 
    	return current_setting(setting)::text[];
end;
$$; 

looks like tenantids are cached some where. We suspect immutable might have cached it, we would like confirm that this is the issue or is something need to be altered in pgx configuration setting since same works in JDBC template.

**Comment by jackc** [comment]
`immutable` is definitely incorrect. From https://www.postgresql.org/docs/current/xfunc-volatility.html:

> An IMMUTABLE function cannot modify the database and is guaranteed to return the same results given the same arguments forever. This category allows the optimizer to pre-evaluate the function when a query calls it with constant arguments.

`get_tenant_id_array()` is calling `current_setting()` and that is definitely not an `immutable` function. Regardless of whether it happens to work or not in some particular case that is incorrect.

I suspect the reason pgx manifests the error and JDBC does not is pgx creates and caches prepared statements by default.

**Comment by SakshiPrakashChalpe** [comment]
Downloading modules and running Go Coverage Test

[2024-05-19T06:55:51.706Z] Running Go Coverage Test with : go test ./... -cover

[2024-05-19T06:55:58.278Z] # github.com/jackc/pgconn

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/auth_scram.go:44:24: too many arguments in call to c.conn.Write

[2024-05-19T06:55:58.278Z] 	have ([]byte, error)

[2024-05-19T06:55:58.278Z] 	want ([]byte)

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/auth_scram.go:63:24: too many arguments in call to c.conn.Write

[2024-05-19T06:55:58.278Z] 	have ([]byte, error)

[2024-05-19T06:55:58.278Z] 	want ([]byte)

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/krb5.go:65:25: too many arguments in call to c.conn.Write

[2024-05-19T06:55:58.278Z] 	have ([]byte, error)

[2024-05-19T06:55:58.278Z] 	want ([]byte)

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/pgconn.go:314:33: too many arguments in call to pgConn.conn.Write

[2024-05-19T06:55:58.278Z] 	have ([]byte, error)

[2024-05-19T06:55:58.278Z] 	want ([]byte)

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/pgconn.go:419:29: too many arguments in call to pgConn.conn.Write

[2024-05-19T06:55:58.278Z] 	have ([]byte, error)

[2024-05-19T06:55:58.278Z] 	want ([]byte)

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/pgconn.go:831:8: assignment mismatch: 1 variable but (&pgproto3.Parse{…}).Encode returns 2 values

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/pgconn.go:832:8: assignment mismatch: 1 variable but (&pgproto3.Describe{…}).Encode returns 2 values

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/pgconn.go:833:8: assignment mismatch: 1 variable but (&pgproto3.Sync{}).Encode returns 2 values

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/pgconn.go:1005:8: assignment mismatch: 1 variable but (&pgproto3.Query{…}).Encode returns 2 values

[2024-05-19T06:55:58.278Z] /go/pkg/mod/github.com/jackc/pgconn@v1.14.0/pgconn.go:1079:8: assignment mismatch: 1 variable but (&pgproto3.Parse{…}).Encode returns 2 values.  
                                                                      
  getting above error, failing in the unit testing. can help mw with this. 

go version: 1.21.6
	"github.com/jackc/pgx/v5/pgxpool"

**Comment by yakkalabhargav235** [comment]
@jackc  Sorry for the late reply.
As you mentioned `using immutable is definitely is not correct`, I assume you mean we should not use immutable for this use case.
Our use case demands us to use `immutable`.
Is there any way to prevent `app.current_tenant` property from getting cached or to invalidate the cache containing the `app.current_tenant`.
Our use case is every time we invoke `get_tenant_id_array()`, and we get updated data?

**Comment by jackc** [comment]
> Our use case is every time we invoke get_tenant_id_array(), and we get updated data?

You are literally telling PostgreSQL that the function will always return the same data and PostgreSQL is believing you and returning the same data... The solution is not to tell PostgreSQL that the function is immutable when it isn't.

As mentioned above, the PostgreSQL docs are very clear on this. https://www.postgresql.org/docs/current/xfunc-volatility.html

>  An IMMUTABLE function cannot modify the database and is guaranteed to return the same results given the same arguments forever. This category allows the optimizer to pre-evaluate the function when a query calls it with constant arguments. For example, a query like SELECT ... WHERE x = 2 + 2 can be simplified on sight to SELECT ... WHERE x = 4, because the function underlying the integer addition operator is marked IMMUTABLE.

**Comment by yakkalabhargav235** [comment]
@jackc As I mentioned earlier we are using IMMUTABLE for procedure. When I consume postgres from JDBC it returns updated value. The issue I'm facing when I start consuming the same database using pgx , it does not work the same way.

As you also mentioned earlier

>  I suspect the reason pgx manifests the error and JDBC does not is pgx creates and caches prepared statements by default.

I'm wondering is there any way pgx can be configured to behave like jdbc for this scenario.

**Comment by jackc** [comment]
> I'm wondering is there any way pgx can be configured to behave like jdbc for this scenario.

You can probably get equivalent behavior by setting the `DefaultQueryExecMode` to `QueryExecModeSimpleProtocol`.

But as I've mentioned multiple times, according to the PostgreSQL docs, it is **literally wrong** to mark a function as immutable that isn't immutable. The fact that it *happens* to work in some cases does not make it right.

In any case though, this is not an issue with pgx.
