### ISSUE TITLE
time.Time and timestamp

### ISSUE THREAD

**Issue by marko995** [jackc/pgx#2032]
Hey guys, 

I am trying to figure out how to driver works. I am troubled with golang's time and postgres't timestamp (not timestamptz).

I have time:
`2023-11-21T01:31:00+02:00`

that I want to stop as timestamp to a table. Somehow, driver ignores offset. so in my case:
`2023-11-21T01:31:00+02:00`
`2023-11-21T01:31:00+01:00`
`2023-11-21T01:31:00Z`

are the same as when I stored them in database, and it is:
`2023-11-21T01:31:00Z`

Can someone explain to me why?

**Comment by jackc** [comment]
The PostgreSQL `timestamp` type does not have a time zone. The year, month, day, hour, minute, seconds, and microseconds are stored from the Go `time.Time` but the time zone is ignored.

**Comment by marko995** [comment]
Hmm ok. How does pgx convert time.Time to timestamp? Does it convert to milliseconds?

**Comment by jackc** [comment]
In binary it is the number of microseconds since Y2K. In text format it is YYYY-MM-DD HH:MM:SS.000000.

**Comment by marko995** [comment]
Why didn't you include the offset when formatting time.Time? I understand that PostgreSQL's timestamp doesn't support timezones, but when I create time.Time and store it, it appears different when I fetch it from the database. Logically, I expect the pgx driver to calculate the timestamp based on the time and timezone and create UTC from it before storing it in the database.

**Comment by jackc** [comment]
`timestamp` is not UTC. It has no time zone at all. It is just as correct for the application to assume local time is stored in a `timestamp` column as to assume UTC.
