### ISSUE TITLE
When using stdlib, Rollback is not sent to DB when transaction context times out

### ISSUE THREAD

**Issue by pedroreys** [jackc/pgx#2041]
**Describe the bug**

When you call `db.BeginTx(context.WithTimeout(context.Background(), 200 * time.Millisecond)`,  `database/sql` [starts a goroutine to monitor the transaction context](https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/database/sql/sql.go;l=1915). When the context timeout expires, this goroutine attempts [to rollback the transaction](https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/database/sql/sql.go;l=2197-2212).

The problem is that when using `pgx` with `pgx/stdlib`, the rollback triggered by `database/sql` when the tx context times out is not sent to the DB, because `pgx` returns [an `timeout: context already done: context deadline exceeded` error in the `tx.Rollback()` call](https://github.com/jackc/pgx/blob/master/pgconn/pgconn.go#L1088-L1092). 

**To Reproduce**

See runnable example below:

If possible, please provide runnable example such as:

```go
package main

import (
	"context"
	"database/sql"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/jackc/pgx/v5/tracelog"
	"log/slog"
	"os"
	"time"
)

func main() {
	traceLogger := tracelog.LoggerFunc(func(ctx context.Context, level tracelog.LogLevel, msg string, data map[string]interface{}) {
		var sLevel slog.Level
		switch level {
		case tracelog.LogLevelTrace,
			tracelog.LogLevelDebug:
			sLevel = slog.LevelDebug
		case tracelog.LogLevelInfo:
			sLevel = slog.LevelInfo
		case tracelog.LogLevelWarn:
			sLevel = slog.LevelWarn
		case tracelog.LogLevelError:
			sLevel = slog.LevelError
		}
		args := []any{}
		for k, v := range data {
			args = append(args, k, v)
		}

		slog.Log(ctx, sLevel, msg, args...)
	})

	connConfig, _ := pgx.ParseConfig(os.Getenv("DATABASE_URL"))
	connConfig.Tracer = &tracelog.TraceLog{Logger: traceLogger, LogLevel: tracelog.LogLevelTrace}
	connStr := stdlib.RegisterConnConfig(connConfig)

	db, err := sql.Open("pgx", connStr)
	if err != nil {
		slog.Error("Unable to connect to database", "error", err)
		os.Exit(1)
	}
       defer db.Close()

       // set up a timeout for the transaction
	txCtx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()

	tx, err := db.BeginTx(txCtx, nil)
	if err != nil {
		slog.Error("error opening tx.", "error", err)
		os.Exit(1)
	}

	var greeting string
	err = tx.QueryRowContext(txCtx, "select 'Hello, world!'").Scan(&greeting)
	if err != nil {
		slog.Error("error querying row", "error", err)
		os.Exit(1)
	}

        // force the transaction to timeout out before committing
	time.Sleep(210 * time.Millisecond)
	err = tx.Commit()
	if err != nil {
		slog.Error("error committing tx", "error", err)
	}
}
```

Please run your example with the race detector enabled. For example, `go run -race main.go` or `go test -race`.

**Expected behavior**
When the transaction context expires and the transaction is still active, i.e. it has not been Committed or Rolledbacked, I expect a Rollback to be sent to the database.

**Actual behavior**
No Rollback command is sent to the DB because `pgx` returns an `timeout: context already done: context deadline exceeded` error.

**Version**
 - Go: `$ go version` -> `go version go1.22.3 darwin/arm64`
 - PostgreSQL: `$ psql --no-psqlrc --tuples-only -c 'select version()'` -> ["PostgreSQL 14.10 (Debian 14.10-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit"]
 - pgx: `$ grep 'github.com/jackc/pgx/v[0-9]' go.mod` -> [v5.6.0]

**Additional context**

Output of running the program above, note second to last line with the `timeout: context already done` error [from pgx](https://github.com/jackc/pgx/blob/master/pgconn/pgconn.go#L1088-L1092):

```

2024/06/11 15:31:53 INFO Connect host=localhost port=5432 database=pgxtest time=139.808042ms pid=1051
2024/06/11 15:31:53 INFO Query sql=begin args=[] time=604.625µs commandTag=BEGIN pid=1051
2024/06/11 15:31:53 INFO Prepare name=stmtcache_b5f368d7a7e87f3a48797e6fc05da348c134b304b3ba9697 sql="select 'Hello, world!'" time=756.125µs alreadyPrepared=false pid=1051
2024/06/11 15:31:53 INFO Query commandTag="SELECT 1" pid=1051 sql="select 'Hello, world!'" args="[map[16:1 17:1 20:1 21:1 23:1 26:1 28:1 29:1 700:1 701:1 1082:1 1114:1 1184:1]]" time=1.512584ms
2024/06/11 15:31:53 ERROR Query err="timeout: context already done: context deadline exceeded" time=42.75µs pid=1051 sql=rollback args=[]
2024/06/11 15:31:53 ERROR error committing tx error="sql: transaction has already been committed or rolled back"
```

**Comment by jackc** [comment]
Unfortunately, the database/sql interfaces for `Commit` and `Rollback` do not include context. This means they can block indefinitely. The behavior you are seeing is a result of working around that. See https://github.com/jackc/pgx/issues/703 and https://github.com/jackc/pgx/commit/7738775417c9a83f77157f75207a454a88b2a9e7.

The current behavior is that a context timeout of the transaction will cause the connection to be closed which implicitly rolls back any changes. It's not ideal, but I don't see any better possibilities given the database/sql limitations.

**Comment by pedroreys** [comment]
Thank you for the quick response, @jackc
