### ISSUE TITLE
Timeout behavior

### ISSUE THREAD

**Issue by seanlindo** [jackc/pgx#205]
I'm consistently running into timeouts, but I'm not entirely sure why. If the application goes unattended for some length of time, the next API call that triggers a database operation will always fail with a timeout error. I checked `pg_stat_activity` and found a connection that had been idle for approximately 30 minutes. Refreshing the page triggered a new database operation, which always succeeds. Checking `pg_stat_activity` again now shows two connections-- there is the old one (which I assume is no longer a "good" connection) and a new "valid" one that was created when I refreshed the page. 

I'm using Compose.io, which is run on AWS, and it appears these connections are being forgotten when they've been idle for too long. Few questions so I can better understand what is happening behind the scenes...

* What happened on my initial "bad" request? Did the driver retry a number of times before "giving up"?

* Is the "bad" connection marked as such in any way? On the subsequent request, instead of erroring out, a new connection was obtained and the request was successful. Did it try the initial idle connection before creating a new one?

* Lastly, what can I do to mitigate this? I would like to have some idle connections that can be reused, is there a setting I can utilize which will "cull" idle connections after some amount of time? I've noticed that connections created by our Node application are destroyed after a few seconds of being idle, I believe node-postgres has some setting enabled by default-- curious if it's possible here as well. 

Thanks!

**Comment by jackc** [comment]
What exactly is the timeout error you are seeing and what call produces it?

If I had to guess I would say that somewhere in the networking layer idle connections are being dropped. There is no way for either end point to know if a connection is dead without attempting to send data. So the PG server could still think it has an open connection, but when pgx tries to send it fails.

> What happened on my initial "bad" request? Did the driver retry a number of times before "giving up"?

The driver does not retry automatically. Any errors are reported immediately. The reason for the no automatic retry policy is there is no way to know if the query was sent successfully, but the response was lost, or if the query never made it at all. Auto retry could cause destructive behavior. (see https://en.wikipedia.org/wiki/Two_Generals%27_Problem)

> Is the "bad" connection marked as such in any way? On the subsequent request, instead of erroring out, a new connection was obtained and the request was successful. Did it try the initial idle connection before creating a new one?

On any fatal error a connection is removed from the pool. 

> Lastly, what can I do to mitigate this?

The default dialer uses a TCP keep alive of 5 minutes. I would have expected that to keep the connection alive. But maybe try a dialer with a 30 sec keep alive (you can set a dialer in the ConnConfig).

> I would like to have some idle connections that can be reused, is there a setting I can utilize which will "cull" idle connections after some amount of time?

There currently is no automatic culling of connections. You can call `ConnPool.Reset` to flush all connections at any time though.

**Comment by seanlindo** [comment]
@jackc Thanks for the detailed follow up. I ended up going with `SetConnMaxLifetime` for now, but that's only a workaround to "cull" connections. 

I'm going to try playing with the dialer, as I would like to keep these connections alive. 

As an aside, is there any downside to keeping permanent connections open to the DB?

**Comment by jackc** [comment]
There's no problem from the application side. On the server side each (idle) connection has a cost, but it shouldn't be an issue unless you have 100s+ connections.

**Comment by seanlindo** [comment]
@jackc I think modifying the dialer will work. In an unrelated issue pertaining to Redis, I learned their HAProxy terminates connections after 5 minutes. If the default TCP Keep Alive for this library is also 5 minutes..well it explains that someone loses :)
