### ISSUE TITLE
Create `pgtype.Timestamptz` from `time.Time`

### ISSUE THREAD

**Issue by rpstw** [jackc/pgx#2050]
**Is your feature request related to a problem? Please describe.**
It's cumbersome while passing many `timestamptz` arguments to a sqlc  function which execute a `UPDATE` query, e.g.:
```golang
func doUpdate(ctx context.Context) error {
    var (
        ub = SomeUpdateBody{}
        err error
    )

    err = ub.CreateAt.Scan(time.Now())
    if err != nil {
        // passing a `time.Time` to `Scan` can never return a error but we don't want to risk it.
        return err
    }

    // as you can see it's getting cumbersome while quantity of these kind of columns increases
    err = ub.Expected.Scan(time.Now().Add(time.Hour))
    if err != nil {
        return err
    }

    // pass SomeUpdateBody to the sqlc update function
    q.do(ctx, ub)
}
```

**Describe the solution you'd like**
Maybe a `New`-ish to create a `pgtype.Timestamptz` like `pgtype.NewTimestampTz(time.Time)`, then the code can be simplified to:
```go
func doUpdate() {
    q.do(ctx, SomeUpdateBody{
        CreateAt: pgtype.NewTimestamptz(time.Now()),
        Expected: pgtype.NewTimestamptz(time.Now().Add(time.Hour)),
    }
}
```

**Describe alternatives you've considered**
`&pgtype.Timestamptz{Time: time.Now(), Valid: True}` can replace every 3 LOC above, but we shouldn't rely on a implementation detail, right?

**Additional context**
The above code is written like that because we use https://github.com/sqlc-dev/sqlc. 

It seems while using `pgx.Conn.Exec` passing `time.Time` for a `timestamptz` column is ok.

**Comment by rpstw** [comment]
`pgtype.Int8` and `pgtype.Numeric` and many I believe have the same problem

**Comment by jackc** [comment]
I'm not sure what sqlc is doing, but in normal pgx usage you don't need to create `pgtype.Timestamptz` for query arguments. You can use a `time.Time` directly. It's similar for other types.

> &pgtype.Timestamptz{Time: time.Now(), Valid: True} can replace every 3 LOC above, but we shouldn't rely on a implementation detail, right?

Actually, that is the correct approach. The struct and it's fields are part of the public interface.

**Comment by rpstw** [comment]
`&pgtype.Timestamptz{Time: time.Now(), Valid: True}`

We end up using this way. It's true creating structs without some kind of new func make sense.


As of why this functionality is useful using sqlc+pgx, here's an example:

First, a `UPDATE` sql `insert into a (ts,a,b) values ($1,$2,$3);` is parsed by a tool, and then go code will be generated like:
```go
const insert1 = `-- name: Insert1 :exec
insert into   a (ts,a,b) values ($1,$2,$3)
`

func (q *Queries) Insert1(ctx context.Context, ts pgtype.Timestamptz, a string, b string) error {
	_, err := q.db.Exec(ctx, insert1, ts, a, b)
	return err
}
```

To insert into table `a`,  create a `*Queries` and call `Query.Insert1`.


```golang
func (s *SomeService) someHandler(w http.ResponseWriter, r *http.Request) {
    var (
        ts = &pgtype.Timestamptz{Time: time.Now(), Valid: True}
        a = r.URL.Query().Get("a")
        b = r.URL.Query().Get("a")
    )

    err = s.q.Insert1(context.TODO(), ts, a, b)
    // ...
}
```

The main pattern difference here is that calling a fixed method instead of writing SQL every time. The benefits of this pattern allows better reuse of SQL and easy code-review.


Anyway if everything is clear I'll close the issue. I'm ok without some kind of new func.

**Comment by zyriab** [comment]
Howdy from the future!

If some SQLc enjoyer is passing by, you might want to add this to you `sqlc.yml` file and enjoy `time.Time` in your generated code.

```yml
overrides:
  - db_type: "timestamptz"
    go_type:
      type: "time.Time"
  - db_type: "timestamptz"
    nullable: true
    go_type:
      type: "time.Time"
```

**Comment by rainbow-bash** [comment]
this one worked for me

```go
    overrides:
      - db_type: "pg_catalog.timestamptz"
        nullable: true
        engine: "postgresql"
        go_type:
          type: "time.Time"
          pointer: true
      - db_type: "pg_catalog.timestamptz"
        engine: "postgresql"
        go_type:
          type: "time.Time"

```
