### ISSUE TITLE
No error returned from Query (Exec works)

### ISSUE THREAD

**Issue by leononame** [jackc/pgx#2052]
**Describe the bug**

I found this bug doing a query that gets an error on the postgres side. When inserting a record that has an invaild foreign key constraint, and executing the SQL through `Query` rather than `Exec`, the query returns no error and an empty `pgx.Rows`.

It does work when using `Exec`, there the error gets bubbled up correctly. But on `Query`, no error is returned at all.

**In `TraceQueryEnd`, I do receive a callback with `data.Error` set to the correct value.**

**To Reproduce**

Run these tests, the PGX test fails but the stdlib wrapper test succeeds.

```go
package db

import (
	"context"
	"database/sql"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
)

func mustExecPGX(t testing.TB, ctx context.Context, c *pgx.Conn, sql string) {
	t.Helper()
	_, err := c.Exec(ctx, sql)
	if err != nil {
		t.Fatalf("failed to exec sql: %s", err.Error())
	}
}
func mustExecStdlib(t testing.TB, ctx context.Context, c *sql.DB, sql string) {
	t.Helper()
	_, err := c.ExecContext(ctx, sql)
	if err != nil {
		t.Fatalf("failed to exec sql: %s", err.Error())
	}
}

func verifyErr(t testing.TB, err error) {
	t.Helper()
	msg := `ERROR: insert or update on table "t2" violates foreign key constraint "t2_id_fkey" (SQLSTATE 23503)`
	if err == nil {
		t.Fatalf("expected an error, but got nil\n")
	} else {
		got := err.Error()
		if got != msg {
			t.Fatalf("expected error message:\n%s\nreceived:\n%s", msg, got)
		}
	}
}

func TestPGX(t *testing.T) {
	ctx := context.Background()
	connString := "host=localhost port=5432 user=postgres password=postgres sslmode=disable"
	c, err := pgx.Connect(ctx, connString)
	if err != nil {
		t.Fatalf("failed to connect via pgx")
	}
	mustExecPGX(t, ctx, c, "DROP TABLE IF EXISTS t2;")
	mustExecPGX(t, ctx, c, "DROP TABLE IF EXISTS t1;")
	mustExecPGX(t, ctx, c, "CREATE TABLE t1 (id integer PRIMARY KEY);")
	mustExecPGX(t, ctx, c, "CREATE TABLE t2 (id integer NOT NULL REFERENCES t1(id));")
	// this returns an error correctly
	_, err = c.Exec(ctx, "INSERT INTO t2(id) VALUES(1)")
	verifyErr(t, err)
	// this does not return an error
	_, err = c.Query(ctx, "INSERT INTO t2(id) VALUES(1) RETURNING id")
	verifyErr(t, err)
}

func TestStdlib(t *testing.T) {
	ctx := context.Background()
	connString := "host=localhost port=5432 user=postgres password=postgres sslmode=disable"
	conf, err := pgx.ParseConfig(connString)
	if err != nil {
		t.Fatalf("failed to parse connstring")
	}
	c := stdlib.OpenDB(*conf)
	mustExecStdlib(t, ctx, c, "DROP TABLE IF EXISTS t2;")
	mustExecStdlib(t, ctx, c, "DROP TABLE IF EXISTS t1;")
	mustExecStdlib(t, ctx, c, "CREATE TABLE t1 (id integer PRIMARY KEY);")
	mustExecStdlib(t, ctx, c, "CREATE TABLE t2 (id integer NOT NULL REFERENCES t1(id));")
	_, err = c.ExecContext(ctx, "INSERT INTO t2(id) VALUES(1)")
	verifyErr(t, err)
}

```

Please run your example with the race detector enabled. For example, `go run -race main.go` or `go test -race`.

**Expected behavior**

The error should be returned for `Query`.

**Actual behavior**

No error was returned from `Query`.

**Version**
 - Go: `go version go1.22.0 linux/amd64` 
 - PostgreSQL: ` PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit`
 - pgx: `v5.6.0`

**Comment by jackc** [comment]
From the docs: https://pkg.go.dev/github.com/jackc/pgx/v5#Conn.Query

> Query sends a query to the server and returns a Rows to read the results. Only errors encountered sending the query and initializing Rows will be returned. Err() on the returned Rows must be checked after the Rows is closed to determine if the query executed successfully.
