### ISSUE TITLE
Conform UUID to Stringer interface

### ISSUE THREAD

**Issue by quinn** [jackc/pgx#2055]
**Is your feature request related to a problem? Please describe.**
I use sqlc, updated sql_package use pgx instead of previous version which used github.com/google/uuid. My code generally works as-is, except for some cases where I would pass an ID to something that expects a "stringer":

```
func (t T) String() string
```
For example, this makes it easy to tag logs with ID's:

```
logger = logger.With(zap.Stringer("thing", thing.ID))
```

**Describe the solution you'd like**
Add String method to UUID.

**Describe alternatives you've considered**

**Additional context**
here's the implementation from google's package:

```go
func (uuid UUID) String() string {
	var buf [36]byte
	encodeHex(buf[:], uuid)
	return string(buf[:])
}

func encodeHex(dst []byte, uuid UUID) {
	hex.Encode(dst, uuid[:4])
	dst[8] = '-'
	hex.Encode(dst[9:13], uuid[4:6])
	dst[13] = '-'
	hex.Encode(dst[14:18], uuid[6:8])
	dst[18] = '-'
	hex.Encode(dst[19:23], uuid[8:10])
	dst[23] = '-'
	hex.Encode(dst[24:], uuid[10:])
}
```

I can make a PR if that would help expedite this.

**Comment by jackc** [comment]
I guess we *could* add it, but `pgtype.UUID` isn't intended to be anything more that the minimum necessary to transfer UUIDs. I actually recommend using a 3rd party UUID type. Both the google one and the gofrs one work out of the box with pgx and there are extension packages for both that completely integrate them into pgx.

**Comment by quinn** [comment]
@jackc yep makes sense. thats what I ended up doing, the first example in the sqlc docs is for doing exactly this:

https://docs.sqlc.dev/en/stable/howto/overrides.html

**Comment by andradei** [comment]
@jackc Is this documented in this package? There's a vague documentation on sqlc as linked by @quinn but it would be great to have this mentioned in the docs since `pgtype.UUID` does not have good API for users of the driver and google/uuid and others are much better on higher levels like web apps.

**Comment by jackc** [comment]
@andradei The extension libraries are listed in the README. https://github.com/jackc/pgx/?tab=readme-ov-file#adapters-for-3rd-party-types. It's the same situation for decimal/numeric. pgx has a type whose sole purpose is to transfer values, but you really probably want to use shopspring/decimal.

**Comment by andradei** [comment]
@grachevko Finally! That's very helpful for users.

**Comment by jflambert** [comment]
Thank you @grachevko for doing it and @jackc for accepting!!!
