### ISSUE TITLE
Cannot work with custom domain based on JSON/JSONB

### ISSUE THREAD

**Issue by comdiv** [jackc/pgx#2062]
# Problem

1. Create table with an JSONB column
2. Create custom domain based on JSONB
3. Create table with column of domain from step (2)
4. Try insert `map[string]any` to column with JSONB type by parameters  - all works well
5. Try insert same map to custom domain, based on JSONB - **it's failed**

Error:

```
failed to encode args[1]: unable to encode &map[string]interface {}{"a":1, "b":"c"} into text format for unknown type (OID 55487)
```

So - here is the test where we found problem:

```go

	
	t.Run("jsonb support", func(t *testing.T) {
		_, err = conn.Exec(context.TODO(), `
		CREATE SCHEMA IF NOT EXISTS tests;
		DROP DOMAIN IF EXISTS tests.my_jsonb CASCADE;
		CREATE DOMAIN tests.my_jsonb AS jsonb;
		DROP TABLE IF EXISTS tests.usual_jsonb;
		DROP TABLE IF EXISTS tests.custom_jsonb;
	    CREATE TABLE tests.usual_jsonb (id int primary key, j jsonb);
		CREATE TABLE tests.custom_jsonb (id int primary key, j tests.my_jsonb);
		`)
		require.NoError(t, err)

		j := map[string]any{"a":1, "b":"c"} 

		_, err := conn.Exec(context.TODO(), "INSERT INTO tests.usual_jsonb (id, j) VALUES ($1,$2)", 1, j)
		require.NoError(t, err)

		_, err = conn.Exec(context.TODO(), "INSERT INTO tests.custom_jsonb (id, j) VALUES ($1,$2)", 2, j)
		require.NoError(t, err) // FAIL  HERE!!!
	})
```

# Workaround

1. do not use custom domains for JSONB
2. add explicit type map after parameter reference - `, err := conn.Exec(context.TODO(), "INSERT INTO tests.usual_jsonb (id, j) VALUES ($1,$2::jsonb)", 1, j)`
3. if using *pgx.Conn directly call LoadType for required types 
4. Use LoadType/RegisterType - should be called BUT it should be executed FOR EVERY connection
with DBPOOL case it's very ugly and it's not native
```go
var nconn = conn.(*pgxpool.Pool)
tx, err := nconn.Begin(context.TODO())
require.NoError(t, err)
defer func(){tx.Rollback(context.TODO())}()
c := tx.Conn()
tp, err := c.LoadType(context.TODO(),"tests.my_jsonb")
require.NoError(t, err)
c.TypeMap().RegisterType(tp)
_, err = c.Query(context.TODO(), "INSERT INTO tests.custom_jsonb (id, j) VALUES ($1,$2)", 2, j)
require.NoError(t, err)
tx.Commit(context.TODO())
```

# Expected behavior

1. Add some parameters to setup automatic load and registration
2. Provide automatic loading for pgx.Conn and pgxpool.Pool/Conn

**Comment by jackc** [comment]
> if using *pgx.Conn directly call LoadType for required types
> Use LoadType/RegisterType - should be called BUT it should be executed FOR EVERY connection
with DBPOOL case it's very ugly and it's not native

These aren't workarounds, these are how pgx supports custom types.

Without loading the type there is no way for pgx to have any idea what to do with custom types. All it gets in response to a query is an OID identifying the type. The types *have* to be registered.

You can use `AfterConnect` with pgxpool to load your types for every connection: https://pkg.go.dev/github.com/jackc/pgx/v5@v5.6.0/pgxpool#Config.

Alternately, if you are using stdlib you can use a https://pkg.go.dev/github.com/jackc/pgx/v5@v5.6.0/stdlib#OptionAfterConnect.

**Comment by comdiv** [comment]
Thx for answer
