### ISSUE TITLE
The type for "MONEY" isn't detected 

### ISSUE THREAD

**Issue by Vedadiyan** [jackc/pgx#2076]
The type of "MONEY" cannot be detected by PGX and it converts the value to "string".  It returns DataTypeOID of "790" which is not actually listed anywhere in the `pgtype` package and for that reason `pgtype.NewMap().TypeForOID()` cannot look it up.  Well, "MONEY" isn't string and must not be treated as string.

**Comment by zoltanbedi** [comment]
@Vedadiyan why did you close this?
