### ISSUE TITLE
get last insert id

### ISSUE THREAD

**Issue by araneta** [jackc/pgx#208]
How to get last insert id of the new record?
and thanks for this great library

**Comment by ARolek** [comment]
You can use the RETURNING keyword and scan the result into a variable. For example:

```go
	var err error
	var id int32

	//	build sql statement
	sql := fmt.Sprintf(`
		INSERT INTO table_name
			(first_name)
		VALUES
			($1)
		RETURNING
			id`)

	//	query and scan
	err = pg.driver.QueryRow(sql,
		"foo",
	).Scan(
		&id,
	)
	//	handle errors
}

```

The above code assumes that you have an id column that is of type `serial` so the ID is generated by the database.

**Comment by araneta** [comment]
thanks its working
