### ISSUE TITLE
Clarify ErrIsClosed return type in docs

### ISSUE THREAD

**Issue by redbaron** [jackc/pgx#2104]
Docs are a bit  unclear how `ErrTxClosed` is returned from `Rollback`.

Tx interface docs [uses](https://pkg.go.dev/github.com/jackc/pgx/v5#Tx.Rollback) wording `errors.Is(ErrTxClosed)` which implies it can be wrapped into another Error value. At the same time Tx from pgxpool explicitly [says](https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#Tx.Rollback) that returned error is `ErrTxClosed` exactly, implying it is not wrapped.

It is important distinction, because Go Error handling [guidelines](https://tip.golang.org/wiki/ErrorValueFAQ#how-should-i-change-my-error-handling-code-to-work-with-the-new-features)  make a point that if error is known to be unwrapped  (like `io.EOF` they talk about) then direct comparison should be used not `errors.Is`.

**Comment by jackc** [comment]
The error is not wrapped at the moment, but they documentation says to use `errors.Is` to allow for wrapping in the future.

I've updated the docs for pgxpool.
