### ISSUE TITLE
Running lib/pq and pgx in the same code base?

### ISSUE THREAD

**Issue by feketegy** [jackc/pgx#2106]
We're in the process of migrating a large code base from pq to pgx and in the meantime we would like to run both in parallel until the migration is complete.

Is this possible by using pgx connection pools and pq connections? (pq is using database/sql Open() function underneath)

**Comment by jackc** [comment]
You can use both in the same project. The only issue I know to be aware of is that the connection pools are independent so your application may consume more connections.
