### ISSUE TITLE
Potential bug / overshadowed error when decoding JSONB

### ISSUE THREAD

**Issue by ronaldslc** [jackc/pgx#212]
Hello, following my question recently in https://github.com/jackc/pgx/issues/200.

Our developers stumbled onto a potential error in pgx.

If we had set `pgx.DefaultTypeFormats["jsonb"] = pgx.TextFormatCode`, and then try to read JSONB field that contains a version number using scan, we would get an error along the lines of "Cause: can't scan into dest[0]: invalid character ':' after top-level value."

The cause was traced to pgx/values.go's decodeJSONB method, as we had specified `pgx.DefaultTypeFormats["jsonb"] = pgx.TextFormatCode`, the byte array after `bytes := vr.ReadBytes(vr.Len())` actually does not contain the version number, so the function will fail.

What made it a little more difficult to decipher is that the fail safe check:
`if bytes[0] != 1 {
		vr.Fatal(ProtocolError(fmt.Sprintf("Unknown jsonb format byte: %x", bytes[0])))
	}`

is thrown, but would be overwritten by the error coming out of `err := json.Unmarshal(bytes[1:], d)`

**Comment by jackc** [comment]
Thanks for the report. I fixed the overwritten error issue in c952d48. Also, I updated decodeJSONB to work with text or binary format. So it should be more convenient to work with jsonb when using text format now.
