### ISSUE TITLE
sample usage prepared statement

### ISSUE THREAD

**Issue by araneta** [jackc/pgx#213]
please give me the sample usage of prepared statement. I can see from this code https://github.com/jackc/pgx/blob/master/examples/url_shortener/main.go that you are using AfterConnect to creates the prepared statements that this application uses. So you want us to register all prepared statements in this AfterConnect event? but there will be hundreds in my applications. Is it possible to create prepared statement when we need it in the function?

**Comment by jackc** [comment]
You can prepare statements at any time (well, to be precise, any time the connection isn't is the middle of another operation). `AfterConnect` is simply one convenient place if you know upfront what all of your preapred statements will be. If you do it on demand you probably want to call `Prepare` on the `ConnPool`. See https://godoc.org/github.com/jackc/pgx#ConnPool.Prepare.

**Comment by araneta** [comment]
if i prepare all the sql statement in afterconnect event will it be slow?

**Comment by jackc** [comment]
The prepares themselves are cheap, but the round trip time to the server may make it measurable. If I had to guess I would expect it to add several hundred milliseconds to the process of creating a new connection. That said, if you are using a connection pool, creating a new connection should be a fairly rare event. There shouldn't be any problems with large numbers of prepared statements in `AfterConnect` or with `ConnPool.Prepare`.

**Comment by araneta** [comment]
thanks for your detailed explanation, i love this great library
