### ISSUE TITLE
v4.18.3  github.com/jackc/pgproto3 SQL injection 

### ISSUE THREAD

**Issue by konstantin-nizhinskiy** [jackc/pgx#2144]
**Describe the bug**
in AWS Inspector

Impact SQL injection can occur if an attacker can cause a single query or bind message to exceed 4 GB in size. An integer overflow in the calculated message size can cause the one large message to be sent as multiple messages under the attacker's control. ### Patches The problem is resolved in v2.3.3 ### Workarounds Reject user input large enough to cause a single query or bind message to exceed 4 GB in size.

**To Reproduce**
Name
github.com/jackc/pgproto3
Installed version / Fixed version
0:1.1.0 / 2.3.3
Package manager
GOMOD
File paths
go/pkg/mod/github.com/jackc/pgx/v4@v4.18.3/go.sum
go/pkg/mod/github.com/jackc/pgconn@v1.14.3/go.sum
go/pkg/mod/github.com/jackc/pgtype@v1.6.1/go.sum

Is it possible to fix this in version 4?
go/pkg/mod/github.com/jackc/pgx/v4@v4.18.3

**Comment by jackc** [comment]
> Is it possible to fix this in version 4?
> go/pkg/mod/github.com/jackc/pgx/v4@v4.18.3

pgx v4.18.3 already has the fix. This was fixed over 7 months ago. The vulnerable pgproto3 dependency was updated in 80e96622d64b9c4dcc7d78a2200c8eade1713118.
