### ISSUE TITLE
get pointer of the current row

### ISSUE THREAD

**Issue by araneta** [jackc/pgx#215]
how to get the current row in the loop like this
for rows.Next() {
  r, err := BindReligion((*pgx.Row)(rows))
}
the code above is not working

**Comment by jackc** [comment]
Sorry, I'm not sure what you mean by pointer to current row. You should call `rows.Scan(...)` inside the `rows.Next()` loop. See https://github.com/jackc/pgx/blob/master/examples/todo/main.go#L71 for an usage example.
