### ISSUE TITLE
fatal error: concurrent map writes in internal/stmtcache.(*LRUCache).Invalidate

### ISSUE THREAD

**Issue by ItsMeSamey** [jackc/pgx#2152]
**Describe the bug**
Program crashes due to concurrent map writes
[fatal.log](https://github.com/user-attachments/files/17450803/fatal.log)

**To Reproduce**
I was spamming with create and select quires, haven't produced a minimal example yet, will update this when i do

Race detector found races in `github.com/jackc/pgx/v5/internal/stmtcache.(*LRUCache).RemoveInvalidated()` and more [races.log](https://github.com/user-attachments/files/17450799/races.log)

**Expected behavior**
expect to able able to concurrently query the database

**Actual behavior**
program crashes

**Version**
 - Go: `go version go1.23.2 linux/amd64`
 - PostgreSQL: `PostgreSQL 16.4 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 13.3.1 20240522 (Red Hat 13.3.1-1), 64-bit`
 - pgx: `github.com/jackc/pgx/v5 v5.7.1`

**Comment by QuentinFAIDIDE** [comment]
I think I've run into this issue recently. Maybe it's also me doing something wrong.
```go
fatal error: concurrent map writes

goroutine 91 [running]:
github.com/jackc/pgx/v5/internal/stmtcache.(*LRUCache).Invalidate(0xc000578480, {0x112c5fa, 0x398})
        /home/quentin/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.1/internal/stmtcache/lru_cache.go:66 +0x6f
github.com/jackc/pgx/v5.(*baseRows).Close(0xc0006aeea0)
        /home/quentin/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.1/rows.go:178 +0xf9
github.com/jackc/pgx/v5.(*baseRows).Next(0xc0006aeea0)
        /home/quentin/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.1/rows.go:222 +0x85
github.com/jackc/pgx/v5.ForEachRow({0x12a8d80, 0xc0006aeea0}, {0xc0006af0e0, 0x12, 0x12}, 0xc0003aae18)
        /home/quentin/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.1/rows.go:391 +0x98
gitlab.com/myself/products-service/routes_implementation.GetAllMajorReleases({0x12a2d20?})
        /home/quentin/Documents/Dev/amy_project/routes_implementation/major_releases.go:381 +0x63d
gitlab.com/myself/products-service/routes_implementation.TestStress01.func1()
        /home/quentin/Documents/Dev/my_project/routes_implementation/stress_test.go:32 +0xb3
created by gitlab.com/myself/products-service/routes_implementation.TestStress01 in goroutine 117
        /home/quentin/Documents/Dev/my_project/routes_implementation/stress_test.go:22 +0xbd
```
(two of my goroutines have this trace)

What I did was running two goroutines that call the same procedure 100 times concurrently, the procedure being a  sequence of`client.Query()`  /  `pgx.ForEachRow` / `rows.Err()` on a few  different tables (no transaction).

The trace mention that the error occured during `pgx.ForEachRow`.
