### ISSUE TITLE
Why is first byte omitted in decodeJSONB

### ISSUE THREAD

**Issue by willtrking** [jackc/pgx#216]
Hey there, recently updated and noticed the extra \x01 byte at the beginning of my jsonb fields (not necessarily casted to jsonb in my queries, which is probably why I came across it) and was wondering if you had any insight as to why that byte is there. Took a look in the codebase and noticed that your decodeJSONB function omits it on purpose. 

I never had seen this before, so was just wondering what that byte is, version number or something along those lines?

**Comment by josephglanville** [comment]
I believe it's the JSONB binary format version number.

**Comment by jackc** [comment]
Correct, it's the JSONB binary format version number. We default to binary format whenever possible, even when the specific type doesn't benefit from it to enable it to be used in the `copy` protocol.

**Comment by willtrking** [comment]
Ahh I see, thanks for the explanation
