### ISSUE TITLE
ERROR: insufficient data left in message (SQLSTATE 08P01)

### ISSUE THREAD

**Issue by araneta** [jackc/pgx#217]
i got this error : ERROR: insufficient data left in message (SQLSTATE 08P01) when inserting new data to the table. what should i do? how do i get last executed sql query?

**Comment by jackc** [comment]
First, ensure you are on the latest version of pgx. Second, if you can extract a runnable sample that exhibits this problem I might be able to diagnose it further.

**Comment by araneta** [comment]
fixed now

**Comment by kdar** [comment]
I ran into this exact error when trying to use CopyFrom with a numeric column and sending a string type.

e.g. For a table with a numeric column `rate`, this works:

```
inputRows := [][]interface{}{
  {time.Now(), "USD", 6.6},
}

copyCount, err := conn.CopyFrom(
  pgx.Identifier{"rate"},
  []string{"timestamp", "currency", "rate"},
  pgx.CopyFromRows(inputRows))

fmt.Println(copyCount, err)
```

but not this

```
inputRows := [][]interface{}{
  {time.Now(), "USD", big.NewFloat(6.6).String()},
}

copyCount, err := conn.CopyFrom(
  pgx.Identifier{"rate"},
  []string{"timestamp", "currency", "rate"},
  pgx.CopyFromRows(inputRows))

fmt.Println(copyCount, err)
```

Where as the second example works fine if I use conn.Exec and INSERT (using a string as a numeric value). Does anyone know if there is a way around this?

**Comment by kdar** [comment]
Seems like this can be resolved in one way by pgtypes.Numeric supporting big.Float or by me converting big.Float to pgtypes.Numeric before inserting.
