### ISSUE TITLE
rows.Close() is not required

### ISSUE THREAD

**Issue by gromas** [jackc/pgx#2170]
https://github.com/jackc/pgx/blob/b9e2b20fb13a7eb8e6bf105c074c291b349b6dec/rows.go#L471

rows.Close() is not required while we have defer rows.Close() above

**Comment by jackc** [comment]
> rows.Close() may change the result of rows.Err() so this is not equivalent, rather with this an error may go unnoticed.

This is correct. From the docs for `Rows.Err()`:

> Err must only be called after the Rows is closed
