### ISSUE TITLE
Providing a type with the name `event_trigger` to `conn.LoadType()` results in an "unknown typtype" error. 

### ISSUE THREAD

**Issue by rubenhazelaar** [jackc/pgx#2175]
**Describe the bug**
Providing a type with the name `event_trigger` to `conn.LoadType()` results in an "unknown typtype" error. Following the logic of `conn.LoadType()`, an OID of 3838 and `typtype=p` are found, which seems to refer to a native Postgres type.

**To Reproduce**

1. Set up the environment with the provided `DATABASE_URL`.
2. Define a type named `event_trigger`.
3. Call `conn.LoadType()` with `event_trigger`.
4. Observe the "unknown typtype" error.

If possible, please provide a runnable example such as:

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

	poolConfig.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
		dataType, err := conn.LoadType(ctx, "event_trigger")
	        if err != nil {
		        return err // Error "unknown typtype" returned here
	        }
	        conn.TypeMap().RegisterType(dataType)

		return nil
	}

        // ...
}
```

**Expected behavior**
The type should be loaded without causing an "unknown typtype" error.

**Actual behavior**
The application fails to load the type and logs an "unknown typtype" error.

**Version**
- Go: `go version go1.23.0 darwin/amd64`
- PostgreSQL: `PostgreSQL 16`
- pgx: `v5.7.1`

**Additional context**
This issue is probably due to an (unintended) naming conflict with a native Postgres type. It would be helpful for other users to be aware that such conflicts can cause this error. However perhaps there also is something which can be done differently here, not sure though.

**Comment by jackc** [comment]
Does it work if you include the schema in the type name, e.g. `public.event_trigger`?

**Comment by rubenhazelaar** [comment]
Great this seems to work, didn't think of that. Thanks!
