### ISSUE TITLE
SendBatch doesn't execute queries in sequential order

### ISSUE THREAD

**Issue by mcosta74** [jackc/pgx#2182]
**Describe the bug**
`SendBatch`  doesn't execute queries in order.
This means that queries that modify data and/or the DB schema cannot reliably executed in batch.

This is, IMHO, a bug or a behaviour that shall be documented

**To Reproduce**
Steps to reproduce the behaviour:

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func CopyTable(conn *pgx.Conn, srcSchema, srcTable, dstSchema, dstTable string) (int64, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	b := &pgx.Batch{}
	b.Queue(fmt.Sprintf("CREATE TABLE %s.%s (LIKE %s.%s INCLUDING ALL);", dstSchema, dstTable, srcSchema, srcTable))
	b.Queue(fmt.Sprintf("INSERT INTO %s.%s (SELECT * FROM %s.%s);", dstSchema, dstTable, srcSchema, srcTable))

	br := conn.SendBatch(ctx, b)
	defer br.Close()

	tag, err := br.Exec()
	if err != nil {
		return 0, fmt.Errorf("error copying table: %w", err)
	}
	return tag.RowsAffected(), nil
}

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

       affectedRows, err := CopyTable(conn, "public", "foo", "public", "bar")
       if err != nil {
               log.Fatal(err)
       }
       fmt.Printf("Copied %d rows\n", affectedRows)
}
```

Please run your example with the race detector enabled. For example, `go run -race main.go` or `go test -race`.

**Expected behavior**
The program runs without error and the table and a new table "bar" has been created as exact copy of the table "foo"

**Actual behavior**
The program fails with this error
```
ERROR: relation "admin.foo" does not exist (SQLSTATE 42P01)
```

**Version**
 - Go: `go version go1.23.3 darwin/arm64` 
 - PostgreSQL: `PostgreSQL 16.6 on aarch64-apple-darwin24.1.0, compiled by Apple clang version 16.0.0 (clang-1600.0.26.3), 64-bit`
 - pgx: `v5.7.1`

**Additional context**
n/a

**Comment by jackc** [comment]
The actual problem is all queries are prepared / planned before any queries are executed. Preparing the `INSERT` fails because the table doesn't exist yet.

**Comment by mcosta74** [comment]
@jackc thanks for the explanation. 
Do you think would be worth to write something in the documentation?

**Comment by jackc** [comment]
> Do you think would be worth to write something in the documentation?

Yes, I just added a note the the SendBatch docs.
