### ISSUE TITLE
Add link to documentation on pkg.go.dev to GitHub About section and README.md

### ISSUE THREAD

**Issue by ecerulm** [jackc/pgx#2187]
There is no link to https://pkg.go.dev/github.com/jackc/pgx in the github homepage for this project https://pkg.go.dev/github.com/jackc/pgx

I think there should be added in both 
* the right sidebar (GitHub > About ) 
* the README.md , something like the "the API documentation can be found at"

**Comment by jackc** [comment]
The link to the Go package docs are at the very top of the README.

**Comment by ecerulm** [comment]
Yes, but it's not very discoverable it's an image that says "go reference". 

You can't find a link to documentation by searching. 

If you search at https://github.com/jackc/pgx for the following keywords you won't find anything
* doc
* documentation
* reference
* godoc

I think it would help newcomers if there was a section in the readme `# Documentation` with the links to `https://pkg.go.dev/github.com/jackc/pgx` with the words godoc, documentation, api reference.

**Comment by jackc** [comment]
> Yes, but it's not very discoverable it's an image that says "go reference".

🤷 As far as a can tell this *is* the standard way to link to Go docs from a README.md on Github. I just checked 4 popular projects I use and they all use the doc badge.

* https://github.com/spf13/cobra
* https://github.com/go-chi/chi
* https://github.com/rs/zerolog
* https://github.com/stretchr/testify 

---

I did add the docs as the project home page, though.
