### ISSUE TITLE
stuck rxMsg

### ISSUE THREAD

**Issue by bigdrum** [jackc/pgx#225]
I recently noticed the service I'm running had two stuck goroutine with the following stacktrace:

```
goroutine 21735 [IO wait, 31 minutes]:
net.runtime_pollWait(0x7fb15cd0a5e0, 0x72, 0x6)
    /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4229ea1b0, 0x72, 0xc423e30e08, 0xc42001e160)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4229ea1b0, 0x201b980, 0xc42001e160)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4229ea150, 0xc4229dd000, 0x1000, 0x1000, 0x0, 0x201b980, 0xc42001e160)
    /usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4229b82b0, 0xc4229dd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc4229b1c20)
    /usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc4229b1c20, 0x5, 0x19dd8b8, 0xc41fcc3cd7, 0x0, 0x8b5be5, 0xc41fcc3cda)
    /usr/local/go/src/bufio/bufio.go:129 +0x62
github.com/jackc/pgx.(*msgReader).rxMsg(0xc420c5dd58, 0x50, 0xc4267864b0, 0x0)
    /go/src/github.com/jackc/pgx/msg_reader.go:49 +0x57
github.com/jackc/pgx.(*Conn).rxMsg(0xc420c5d800, 0xc4267864b0, 0x71, 0x400, 0x71)
    /go/src/github.com/jackc/pgx/conn.go:1042 +0x5b
github.com/jackc/pgx.(*Conn).PrepareEx(0xc420c5d800, 0x0, 0x0, 0xc428c53020, 0x5c, 0x0, 0xc4267864b0, 0x0, 0x0)
    /go/src/github.com/jackc/pgx/conn.go:662 +0xa55
github.com/jackc/pgx.(*Conn).Prepare(0xc420c5d800, 0x0, 0x0, 0xc428c53020, 0x5c, 0xc423e31200, 0xbe8dba, 0xc4229d8128)
    /go/src/github.com/jackc/pgx/conn.go:598 +0x5c
github.com/jackc/pgx.(*Conn).Query(0xc420c5d800, 0xc428c53020, 0x5c, 0xc42eea0440, 0x2, 0x2, 0xc420020000, 0xc426833d70, 0xc423e31368)
    /go/src/github.com/jackc/pgx/query.go:448 +0x3b7
github.com/jackc/pgx.(*ConnPool).Query(0xc422907b80, 0xc428c53020, 0x5c, 0xc42eea0440, 0x2, 0x2, 0x5a1b9e, 0xc423e313c0, 0xc423e313d0)
    /go/src/github.com/jackc/pgx/conn_pool.go:362 +0x147
github.com/jackc/pgx.(*ConnPool).QueryRow(0xc422907b80, 0xc428c53020, 0x5c, 0xc42eea0440, 0x2, 0x2, 0x0)
    /go/src/github.com/jackc/pgx/conn_pool.go:377 +0x60
```

It is possible that somehow we had a networking glitch that caused this? It is possible to get a timeout error from such case?

**Comment by bigdrum** [comment]
I figured it is possible to pass a DialFunc to the connection so I can write a wrapper Dialer to set the read/write deadline.

I wonder if some official support for setting deadline will be considered though. Feel free to close this bug if it is working as intended.

**Comment by jackc** [comment]
If the timeout is on connection or acquisition from the pool then a custom dialer and/or ConnPoolConfig.AcquireTimeout should provide what you want.

If it is a per query timeout then there is no pgx API to handle that. As you mention, DialFunc can be used to a get a handle on the underlying net.Conn.

I think some sort of timeout and/or cancellation API would be a great improvement. I haven't thought much about what that API would look like. Could be a timeout or maybe use Context.

**Comment by tejasmanohar** [comment]
I'm running into similar "hangs" in production, and they're quite puzzling.

I think context would be ideal. I haven't used it yet, but I believe there is actually support for using context in db/sql in Go1.8 so that may come in handy here.

**Comment by tejasmanohar** [comment]
Moreover, is there any heartbeat in PGX? Somehow, I feel like manual intervention (e.g. ContextWithTimeout) is not the right solution here.

**Comment by jackc** [comment]
The default dialer includes a 5 minute keep-alive at the TCP level. At the moment that is the only built-in heartbeat.

**Comment by jackc** [comment]
pgx has context support for timeouts now.
