### ISSUE TITLE
Is there a way  to specify bytea format: "escape", "hex"?

### ISSUE THREAD

**Issue by mapaiva** [jackc/pgx#236]
I'm using bytea to store some information and notice that doesn't matter the `bytea_output` value on the db the pgx driver always use the `escape` format to convert the data.

Is there any way to enforce the `hex` format or perhaps check which format is being used?

**Comment by jackc** [comment]
Not sure I quite understand. pgx should use binary format for transmission of `bytea` data. Text encoding would not typically be used.

**Comment by mapaiva** [comment]
I'm talking about about this topic https://www.postgresql.org/docs/9.0/static/datatype-binary.html section 8.4.2 regarding the bytea external format that could be `escape` or `hex`.

F.Y:
![screenshot from 2017-02-16 16-23-27](https://cloud.githubusercontent.com/assets/8807694/23034899/838bea2e-f464-11e6-9dce-b8f0bb7f48f9.png)

In the sample above, all the records except the last one were inserted using the PostgreSQL function `decode('some string', 'hex')` and the last using the pgx driver through a golang program.

The format is globally set as `hex` as well.
```
SHOW bytea_output;
bytea_output 
--------------
hex
(1 row)
```

The point is that I don't know if the problem is on the PostgreSQL or pgx side. :disappointed:.
https://www.postgresql.org/docs/9.4/static/functions-binarystring.html
Am I approaching things wrong using the func `decode`?

**Comment by jackc** [comment]
The last entry appears to be twice as long as the other records and also only uses a subset of characters. That is what would happen if textual data was stored in a binary format.

e.g.

```
jack=# select '1a2b3c4d5e6f7a'::bytea;
             bytea              
--------------------------------
 \x3161326233633464356536663761
(1 row)
```

If I had to guess I would say you have a `string` of hex encoded data in Go and are sending that through pgx to PostgreSQL. You want to encode that `string` into `[]byte` before that. Check out https://golang.org/pkg/encoding/hex/.
