### ISSUE TITLE
Storing slice of string pointers

### ISSUE THREAD

**Issue by mpmlj** [jackc/pgx#242]
Hi,

Is this possible to work with
```Go
type Post struct {
    ...
    AttachedImageIDs   []*string `db:"attached_image_ids"`
   ...
}
```

( underlying type is varchar(36)[] ) ?

My attempts lead to the following error so far:

> panic: Cannot encode []*string into oid 1015 - []*string must implement Encoder or be converted to a string

Thank you!

**Comment by jackc** [comment]
`[]string` is supported, but `[]*string` is not. `string`s are already essentially pointers. Is there some reason not to just use `[]string`?

**Comment by mpmlj** [comment]
@jackc 
Just inherited a codebase with lots of []*string (hello to AWS SDK). No reason beyond that. OK, no problem, looks like some cleanup on my side ahead.

Thank you!
