### ISSUE TITLE
CopyTo or CopyFrom?

### ISSUE THREAD

**Issue by poopoothegorilla** [jackc/pgx#243]
The `CopyTo` method name makes it seem like it is meant to be...
```sql
COPY { table_name [ ( column [, ...] ) ] | ( query ) }
    TO { 'filename' | STDOUT }
    [ [ WITH ] ( option [, ...] ) ]
```
But the [documentation](https://github.com/jackc/pgx/blob/master/copy_to.go#L225) makes it seem more of a `CopyFrom`.
```sql
COPY table_name [ ( column [, ...] ) ]
    FROM { 'filename' | STDIN }
    [ [ WITH ] ( option [, ...] ) ]
```
https://www.postgresql.org/docs/9.5/static/sql-copy.html
Do I have a misunderstanding here? Also is there currently a way to handle the `CopyTo` Stdout scenario?

**Comment by jackc** [comment]
The naming is inconsistent with the SQL COPY command. Not sure how I overlooked that, aside from thinking the "to" or "from" referred to the server. There is currently no support for the `COPY TO STDOUT` command. I'm not sure if that would provide any performance advantage.

I think I'll fix the name for this at the same time as #190 given that both deal with copy and both are breaking changes (which probably means next major version).

**Comment by poopoothegorilla** [comment]
👍

**Comment by jackc** [comment]
I decided to not wait for a major version to resolve this. Added `CopyFrom` method in #246 which also includes schema support. Deprecated existing `CopyTo` but left in place for backwards compatibility.
