### ISSUE TITLE
Custom type point example

### ISSUE THREAD

**Issue by awsom82** [jackc/pgx#244]
I trying to setup my custom datatype, it's a just a point. And i found an [official example](https://github.com/jackc/pgx/blob/master/example_custom_type_test.go).  My code is not working, and example end with same error: `can't scan into dest[0]: Scan cannot decode into *main.NullPoint`

My environment is go v1.8, pgsql v9.6.2 running on OSX Sierra.

Can somebody to help my figure out with this issue?

**Comment by jackc** [comment]
That example is succeeding for me on both `master` and `v2`. I presume you are on the latest commit of one of those branches?

**Comment by awsom82** [comment]
Hi,

Yeah, very strange.

First I'm install it via glide, it's says.
```yaml
- package: github.com/jackc/pgx
  version: ^2.9.0
```

Now, i install latest with go get and `example_custom_type_test.go` looks working.
The return is 
```bash
null point
1.5, 2.5
```

A little disappointed with versions... But, cool it's work!
Many thanks, Jack!
