### ISSUE TITLE
Switch Left over Copy To to new Copy From

### ISSUE THREAD

**Issue by poopoothegorilla** [jackc/pgx#248]
There seems to be other instances of `Copy To` which do not point to or have `Copy From` alternatives ... would it make sense to also update these instances as well? or should we wait for a new release.

https://github.com/jackc/pgx/blob/master/tx.go#L161
https://github.com/jackc/pgx/blob/master/conn_pool.go#L508
https://github.com/jackc/pgx/blob/master/bench_test.go#L488

**Comment by jackc** [comment]
Sorry about missing that. You're right, they should be on Tx and ConnPool as well. I just added them (while leaving the old ones for backwards compatibility) and updated the benchmark as well.
