### ISSUE TITLE
Read/Write timeouts

### ISSUE THREAD

**Issue by georgysavva** [jackc/pgx#250]
I in the case of network failures tcp read or write operations can hang for a really long time. So if I override Dial function I will be able to set only connection timeout, but I need read/write too.

**Comment by jackc** [comment]
This is a shortcoming of the current release of pgx. 

If you want to jump on the bleeding edge you can checkout branch `v3` which has context support. The usual caveats apply to running on a development branch, there may be bugs and  there still are planned API changes.

For the current version, by using a custom dialer you could retain a handle to the underlying connection and directly set deadlines on that. But yes, that would be as ugly and hacky as it sounds.

**Comment by gazoon** [comment]
It's cool that you plan to add this functional in the feature. I hope I will see it in the stable version, soon.

**Comment by rafw** [comment]
I hope so. Timeout param is really helpful.

**Comment by jackc** [comment]
Timeouts via context are now is the stable release of pgx.

**Comment by georgysavva** [comment]
Hi. As I can see you did added query timeouts via context timeout. This approach gives a better control on timeouts to the user, but you should set timeout for each query. 
Maybe it will be good to add a setting for the entire pgx.Conn that you set only once during the initialisation with the default timeout for all queries, and library will use it for every call, if timeout isn't set in the current context. The standard http library works with timeout exactly the same way.
