### ISSUE TITLE
Params inside JSON ignored?

### ISSUE THREAD

**Issue by howesteve** [jackc/pgx#251]
Hello,

I must be doing something very stupid, because it seems query params inside json structs are being ignored.

```go
package main

import (
	"github.com/jackc/pgx"
	"log"
)

type N struct {
	Name string `json:"name"`
}

func main() {
	conn, err := pgx.Connect(pgx.ConnConfig{
		Host:     "localhost",
		User:     "howe",
		Database: "howe",
	})
	if err != nil {
		log.Fatal(err)
	}
	var res N

	err = conn.QueryRow(`select '{"name": $1}'::json`, "howe").Scan(&res)
	if err != nil {
		e := err.(pgx.PgError)
		log.Fatalf(`\n%s %s: %s:\n%s: %s`, e.Severity, e.Code, e.Message, e.Where, e.Detail)
	}
	log.Print("Done.")
}
```
This results in the following error:

```
2017/03/20 22:18:43 \nERROR 22P02: invalid input syntax for type json:\nJSON data, line 1: {"name": $...: Token "$" is invalid.
```
It looks like the $1 parameter is being ignored.

Any clues?

Thanks,
Howe

**Comment by jackc** [comment]
Placeholder variables can't be inside of PostgreSQL text literals. Use `json_build_object`.

Try: `err = conn.QueryRow("select json_build_object('name', $1::text)", "howe").Scan(&res)`

**Comment by howesteve** [comment]
Ah, thanks. That worked.
Perhaps a note on the Prepare() docs would be helpful.

Thanks again for the quick answer.
