### ISSUE TITLE
OpenFromConnPool contains results in a memory leak.

### ISSUE THREAD

**Issue by james-lawrence** [jackc/pgx#255]
everytime OpenFromConnPool is invoked it leaks memory.

```
openFromConnPoolCountMu.Lock()
name := fmt.Sprintf("pgx-%d", openFromConnPoolCount)
openFromConnPoolCount++
openFromConnPoolCountMu.Unlock()

sql.Register(name, d)
```

the invocation to sql.Register leaks the name + the driver + the pool.

**Comment by jackc** [comment]
I'd expect sql.Register to hold a reference to name, driver, and pool by necessity. But I also did not anticipate `OpenFromConnPool` typically being called more than once per program execution. What's the usage pattern for multiple calls to `OpenFromConnPool`?

At the time `OpenFromConnPool` was written, I didn't see any other way to connect a pre-existing pgx pool to a *sql.DB aside from registering a new driver. Looking at it with fresh eyes, it might be possible to avoid the multiple sql.Register call by doing something with db.Driver, but I'm not totally sure.

**Comment by james-lawrence** [comment]
There are a couple problems with OpenFromConnPool.

1) it was the only way to go from a ConnConfig to a sql.DB using ParseDSN. I do not think there is anything that can be done about this short of my other PR.

2) It doesn't document the fact it leaks memory.

3) not sure it really has a use case. sql.DB already does connection pooling. Why would we need to add a pool for something that already does connection pooling?

**Comment by james-lawrence** [comment]
Regarding the usage pattern: It was the only way to open a sql.DB connection using pgx and a DSN connection string. =) I naively assumed OpenFromConnPool was doing some internal conversion to sql.DB.

And the resulting sql.DB violated some basic promises of the sql.DB structure (such as calling db.Close() would shut down all the connections)

**Comment by jackc** [comment]
`v3` removes `OpenFromConnPool` and replaces it with `RegisterDriverConfig`. This entirely eliminates the structural problem with `OpenFromConnPool`. If golang/go#20268 gets resolved it should be simple to support that as well.
