### ISSUE TITLE
"Received unknown message type: C" using CopyFrom

### ISSUE THREAD

**Issue by liuyang1204** [jackc/pgx#258]
```
tx.CopyFrom([]string{"files"}, []string{"project", "path", "content"}, ...)
```

Can not execute CopyFrom because of the following error:

```
lvl=eror msg="Prepare `` as `select \"project\", \"path\", \"content\" from \"files\"` failed: Received unknown message type: C"
```
Related line:
https://github.com/jackc/pgx/blob/master/copy_from.go#L99

The error msg is quite difficult to understand. Anyone can help?

Update: the problem seems not only happening when CopyFrom, but for any PreparedStatement. The database logs:
```
unexpected EOF on client connection with an open transaction
```
I tried in Postgresql 9.6 and 9.5, same result.

**Comment by liuyang1204** [comment]
Found the reason:

I used the `RETURNING` feature:

```
INSERT INTO sometable (...) VALUES (...) RETURNING id
```
with `tx.Query` because I want to get the returning id from the result row.

But after this query, all `prepare` statements fail.

I changed this `tx.Query` to `tx.Exec` and then queried another select to get the id, then problem solved!

It seems `Query` with `INSERT ... RETURNING` is not working well.

**Comment by jackc** [comment]
`returning` clauses should work fine. Are you reading the entire result set back before running the copy command? Also, if you are only inserting a single row, you might find `QueryRow` more convenient as that is designed for single row responses.

**Comment by liuyang1204** [comment]
Thanks for reply!

I tested again, and exactly it was because `rows` was not closed before running `copy`.
I used `defer rows.Close()` and the `copy` command is in the same function.

It was my fault, but this error msg is really hard to indicate the actual reason.

Closing since it is solved.
