### ISSUE TITLE
ConnPool.Reset doesn't actually close connections

### ISSUE THREAD

**Issue by crewjam** [jackc/pgx#264]
The documentation for ConnPool.Reset seems to indicate that it will close connections, but it actually seems to just discard references to the connections. It seems like a loop like in `Close()` is needed, maybe something like this:

```
for _, c := range p.availableConnections {
	_ = c.Close()
}
```

We're experiencing connections retained after calling Reset(), which doesn't seem like what is intended. I can do a PR, but I wanted to touch base first and see if I'm missing something.

Thanks!

**Comment by jackc** [comment]
Hmm. That code is in ConnPool.Reset already: https://github.com/jackc/pgx/blob/master/conn_pool.go#L260

Any connections that are checked out will be closed when they are released to the pool: https://github.com/jackc/pgx/blob/master/conn_pool.go#L198.

Obviously, there could be a bug, but what you are wanting _should_ already be working.

**Comment by crewjam** [comment]
Oh, right you are. Looks like our vendored version is pretty old. 

https://github.com/jackc/pgx/commit/d398d957649de7b8958725bc73a42fac10e70e9b

Sorry for the spam.
