### ISSUE TITLE
CopyFrom with a Tx from ConnPool doesn't work

### ISSUE THREAD

**Issue by julianvmodesto** [jackc/pgx#265]
Hi, I implemented the CopyFromSource interface, and tested both Next and Values, but it seems that the call to CopyFrom indefinitely blocks. I'm invoking CopyFrom on a Tx acquired from a ConnPool. Is this a known issue?

**Comment by jackc** [comment]
This is the first I've heard of this issue. Is it only when run through a `Tx` or do you get the same behaviour when run directly on a `Conn`? Can you share example code?

**Comment by julianvmodesto** [comment]
Oh shoot, sorry false alarm :(

I opened a Tx, but I called CopyFrom on the ConnPool instead of on the Tx, which is what I actually wanted to do and works. Whoops.
