### ISSUE TITLE
pgtype protobuf support.

### ISSUE THREAD

**Issue by hsyed** [jackc/pgx#268]
The pgtype's in v3 are fantastic and will lead to a class of ORM that do not exist in go yet!

I am working on generating an ORM-microservice and I need the pgtypes to use in protobuf definitions. 

There are two approaches I can think of. Without copying the types into a separate package they would both create a proto dependency: 

**gogoproto custom type:**

[gogoproto](https://github.com/gogo/protobuf/blob/master/custom_types.md) can be used to set up custom types as first-class proto messages. 

Some manual code generation would still be needed for this approach.

**Kubernetes approach -- gengo:**
The gengo protobuf generator can be used for this. Here are the steps. step 1 would have to be done manually.

1. The pgtype structs would need the protobuf struct tags -- see [this kubernetes file](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L70-L217). 
2. [generated] An init block which registers with the types with the proto runtime. 
3. [generated] protobuf support methods.
4. [generated] A `proto` file for the package with the struct definitions.

The Kubernetes approach might be the least invasive. The types in the existing package would need to add protobuf struct tags and annotations for gengo. If these two are present a new package can be generated.

**Comment by jackc** [comment]
Glad you like it. I'm excited to see how `pgtype` will be used. As a small caveat I'll mention that `pgtype` isn't at a stable release yet. It works, and I don't anticipate any major changes, but there is no guarantee that it's interface won't still change.

I've never worked with protobuf so my perspective is limited. That said, here's my thoughts. First, it's unclear to me how far away from the database it makes sense to use `pgtype`. The undefined | null | present status column may or may not make sense. And some of the PostgreSQL types have values that may not be usable outside of `pgtype` such as infinite dates and times. But assuming it does make sense (and given my limited protobuf knowledge I really don't know), I definitely prefer an approach that doesn't add a hard dependency to the main package. Sub-packages per dependency are fine. That's what I'm doing for shopspring/decimal and satori/uuid. Adding annotations or struct tags to the main package would also be probably be okay.

I think an approach that generates the protobuf code from pgtype into a new package would probably work best. I'm guessing both of the above generators can do that...? I like separate packages to avoid dependencies in the main package and to avoid locking in one solution or library. For example, I support shopspring/decimal, but I don't preclude using `cockroachdb/apd` for numeric types. I don't know if there is any reason one would choose one protobuf solution over the other, but I'd rather not make it impossible for people to use something else if needed.

**Comment by jackc** [comment]
FWIW, `pgtype` has now been extracted to its own library (https://github.com/jackc/pgtype). If this is still an issue we can revisit it there.

**Comment by Rojuinex** [comment]
As pgx v5 has since brought pgtype back into this repo, can this ticket be reopened?  Or would it be better to create a new issue for this request?

**Comment by jackc** [comment]
@Rojuinex At this point I would suggest opening a new issue. However, my comment from 7 years ago still holds. pgtype types aren't really intended to be used very far from the database. So I'm not sure if it really makes sense. And we definitely don't want to add any dependencies to pgx.
