### ISSUE TITLE
JSONB Scanned into []byte Has Invalid First byte

### ISSUE THREAD

**Issue by theory** [jackc/pgx#269]
Scanning JSONB into a `[]byte` always have a leading `\x01` byte. The same is not true for text or JSON values. Sample program:

    package main

    import (
    	"encoding/hex"
    	"fmt"
    	"github.com/jackc/pgx"
    )

    func main() {
    	dsn := "postgres://postgres@localhost/postgres?sslmode=disable"
    	config, err := pgx.ParseURI(dsn)
    	if err != nil {
    		panic(err)
    	}

    	db, err := pgx.Connect(config)
    	if err != nil {
    		panic(err)
    	}

    	rows, err := db.Query(`SELECT '{"foo": 1}', '{"foo": 1}'::json, '{"foo": 1}'::jsonb`)
    	if err != nil {
    		panic(err)
    	}
    	defer rows.Close()

    	rows.Next()

    	// Scan the ID and JSON
    	var text []byte
    	var json []byte
    	var jsonb []byte
    	if err := rows.Scan(&text, &json, &jsonb); err != nil {
    		panic(err)
    	}
    	fmt.Printf("Text:  %s\n", text)
    	fmt.Printf("JSON:  %s\n", json)
    	fmt.Printf("JSONB: %s\n", jsonb)

    	fmt.Println("Text HEX:  " + hex.EncodeToString(text))
    	fmt.Println("JSON HEX:  " + hex.EncodeToString(json))
    	fmt.Println("JSONB HEX: " + hex.EncodeToString(jsonb))
    }

And the output:

    Text:  {"foo": 1}
    JSON:  {"foo": 1}
    JSONB: {"foo": 1}
    Text HEX:  7b22666f6f223a20317d
    JSON HEX:  7b22666f6f223a20317d
    JSONB HEX: 017b22666f6f223a20317d

Note the leading `01` in that last line. It should not be there.

**Comment by jackc** [comment]
This is an unfortunate interaction of two features.

1. Scanning into `[]byte` does not perform any translation of the underlying data.
2. pgx uses the binary format by default.

The binary jsonb format is prefixed by a version byte which is currently always '1'. The simplest solution for now is to change the default format for jsonb to text.

```
pgx.DefaultTypeFormats["jsonb"] = pgx.TextFormatCode
```

**Comment by theory** [comment]
Uh, so should that be done in the source or in any app that uses JSONB?

**Comment by theory** [comment]
I guess the proper fix for this, long-term, would be to create a binary format that ignores the first byte, yes?

**Comment by jackc** [comment]
It would be done in the application.

Long-term it is already resolved in the `v3` branch of pgx. However, `v3` is probably still probably a couple months out from release.

**Comment by twils0** [comment]
To clarify, if I use b := []byte, b[1:] to cutoff the first byte in my code when pulling from a jsonb column in the database (and vice versa when inputting into the database, adding the hex value for 1 to the byte slice), this work-around will not be necessary in v3?

**Comment by jackc** [comment]
That is correct.

**Comment by jackc** [comment]
`v3` was released today, so this should no longer be an issue in the stable release.
