### ISSUE TITLE
in v3 branch: query with large number of columns doesn't work anymore

### ISSUE THREAD

**Issue by volkmarbuehringer** [jackc/pgx#270]
a90 sql="select ads_id,ads_vorname,ads_name,ads_name2,ads_ankid,ads_atyid,ads_titid,ads_ianreti,ads_ianrbrief,ads_countryid,ads_plz,ads_str,ads_hausnr,ads_ort,ads_ortsteil,ads_zusatz,ads_ukzid,ads_updadr,ads_updnam,ads_postok,ads_korrexpdat,ads_expckid,ads_staid,ads_statusdat,ads_adsiddub,ads_tel,ads_anonym,ads_stkid,ads_outpaytypeid,ads_cr_uid,ads_cr_date,ads_upd_uid,ads_upd_date,ads_titel,ads_bewertung,ads_strnr,ads_potid,ads_umzug,ads_umzmaildat,ads_umzabrdat,ads_gebdat,ads_pvjid,ads_vjsid,ads_vjsdat,ads_limit,ads_limitdatum from edv.lt_ads order by ads_id limit $1 offset $2" args="[0xc420169330 0xc420169338]" time=1.673904ms rowCount=1
2017/05/01 14:44:32 http: panic serving 127.0.0.1:25413: runtime error: makeslice: cap out of range
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc4200d5cc0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xaed120, 0xc4201c4320)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/jackc/pgx/pgproto3.(*DataRow).Decode(0xc420076eb0, 0xc4201c2554, 0x139, 0xaac, 0xaac, 0x0)
	/home/prounix/go/src/github.com/jackc/pgx/pgproto3/data_row.go:28 +0x360
github.com/jackc/pgx/pgproto3.(*Frontend).Receive(0xc420076e00, 0x1a6809bf, 0xfc03e0, 0x0, 0x0)
	/home/prounix/go/src/github.com/jackc/pgx/pgproto3/frontend.go:111 +0x14f
github.com/jackc/pgx.(*Conn).rxMsg(0xc4200f4000, 0xf6d020, 0xc420076e28, 0x0, 0x0)
	/home/prounix/go/src/github.com/jackc/pgx/conn.go:1049 +0x45
github.com/jackc/pgx.(*Rows).Next(0xc4201146b8, 0xc4201c42f8)
	/home/prounix/go/src/github.com/jackc/pgx/query.go:119 +0x65
restfest/db.(*BaseCopy).Next(0xc4201029c0, 0xc4201c4200)
	/home/prounix/go/src/restfest/db/structs.go:83 +0x4d
main.getAllHandler(0xf6e660, 0xc420120540, 0xc42000bc00)
	/home/prounix/go/src/restfest/rester/handlerget.go:44 +0x2f6
net/http.HandlerFunc.ServeHTTP(0xc09560, 0xf6e660, 0xc420120540, 0xc42000bc00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
restfest/service.Logger.func1(0xf6e660, 0xc420120540, 0xc42000bc00)
	/home/prounix/go/src/restfest/service/listener.go:14 +0xae
net/http.HandlerFunc.ServeHTTP(0xc42015a870, 0xf6e660, 0xc420120540, 0xc42000bc00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42001ebe0, 0xf6e660, 0xc420120540, 0xc42000bc00)
	/home/prounix/go/src/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.serverHandler.ServeHTTP(0xc4200148f0, 0xf6e660, 0xc420120540, 0xc42000ba00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4200d5cc0, 0xf6ed20, 0xc420019dc0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2017/05/01 14:44:32 http: panic serving 127.0.0.1:25415: runtime error: makeslice: cap out of range
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc4201de000)
	/usr/local/go/src/net/http/server.go:1721 +0xd0

**Comment by jackc** [comment]
Fixed: ee001a7caebc75cc51d0068e9109b99d8a20755d
