### ISSUE TITLE
sslrootcert not being used

### ISSUE THREAD

**Issue by svkoskin** [jackc/pgx#277]
Hello,

It seems that sslrootcert parameter in DSNs and URLs is not being used. Based on the behaviour of github.com/lib/pq I was expecting to be able to provide an additional trusted root certificate file name in the parameter, but ConnConfig.TLSConfig.RootCAs remains empty. I can't find any code for reading that parameter, either. I'm afraid Amazon RDS only provides a self-signed certificate, and therefore providing additional root certificates would be useful.

Is there a reason to not parse the parameter, read the file and pass it to crypto.TLS, or has such feature had a low priority?

**Comment by jackc** [comment]
There's no reason not to support it. This is just the first time it has come up.

**Comment by andrewplunk** [comment]
This is an important security feature in my book. Are you accepting pull requests for this feature @jackc ?

**Comment by andrewplunk** [comment]
FYI @svkoskin, I believe you can work around this issue by providing your own tls.Config with a RootCA certpool set as a parameter to the pgx.ConnConfig.

**Comment by jackc** [comment]
Yes, a PR would be fine for this issue. And yes, the current solution is providing your own `tls.Config`.

**Comment by sylvainr** [comment]
AWS is in the process of forcing clients to use their root certificate (deadline is Oct 23rd), at least for Redshift:

> Beginning on this date, clients connecting to Amazon Redshift clusters will need an additional trusted certificate authority (CA). Clients use trusted certificate authorities to confirm the identity of the Redshift cluster when they connect to it. Your action is required to update your SQL clients and applications to use an updated certificate bundle that includes the new trusted CA.

This is a big deal. I assume the OP's question in regards to RDS may be related.

It would be great if someone could confirm that the workaround specified above will work out. It would be even better if someone could post a code snippet.

**Comment by danielevns** [comment]
Ideally `pgx.ParseEnvLibpq()` should parse and handle all libpq-style environment variables, but the workaround is painless:

```go
caCert, err := ioutil.ReadFile(os.Getenv("PGSSLROOTCERT"))
if err != nil {
	log.Fatal(err)
}
caCertPool := x509.NewCertPool()
caCertPool.AppendCertsFromPEM(caCert)

connConfig, err := pgx.ParseEnvLibpq()
if err != nil {
	log.Fatal(err)
}
connConfig.TLSConfig.RootCAs = caCertPool

// authenticate with a client certificate (optional)
keypair, err := tls.LoadX509KeyPair(os.Getenv("PGSSLCERT"), os.Getenv("PGSSLKEY"))
if err != nil {
	log.Fatal(err)
}
connConfig.TLSConfig.Certificates = []tls.Certificate{keypair}

db, err := pgx.Connect(connConfig)
if err != nil {
	log.Fatal(err)
}
```

**Comment by gyant** [comment]
Thanks @danielevns for the workaround. 

Where exactly would you drop this in?

**Comment by danielevns** [comment]
Wherever you connect to the database in your application. If you're using a connection pool, you'd substitute the call to `pgx.Connect` with something like:

```go
connPoolConfig := pgx.ConnPoolConfig{ConnConfig: connConfig}

pool, err = pgx.NewConnPool(connPoolConfig)
if err != nil {
	log.Fatal(err)
}
```

**Comment by urandom** [comment]
It seems that the above workaround does not work when the sslmode is "verify-ca" and no ssl certificites are being passed. Apparently the tls package does a full verification and fails. It seems like CA verification needs to be done by hand by pgx here, whenever a connection is open.

**Comment by kyle-ngrok** [comment]
I believe this has been fixed? https://github.com/jackc/pgx/blob/master/conn.go#L999

**Comment by jackc** [comment]
> I believe this has been fixed?

Correct.
