### ISSUE TITLE
Version 3 Beta

### ISSUE THREAD

**Issue by jackc** [jackc/pgx#278]
After many months in development the `v3` branch is ready for beta testing. Some of the new features include:

* Entirely revamped pluggable type system that supports approximately 60 PostgreSQL types.
* Types support database/sql interfaces and therefore can be used with other drivers
* Added context methods supporting cancellation where appropriate
* Added simple query protocol support
* Added single round-trip query mode
* Added batch query operations
* Added OnNotice
* github.com/pkg/errors used where possible for errors
* Added stdlib.DriverConfig which allows directly allows full configuration of underlying pgx connections without needing to use a pgx.ConnPool
* Added AcquireConn and ReleaseConn to stdlib to allow acquiring a connection from a database/sql connection. 

General release is planned for July. Please test this branch against new or existing projects and report any bugs or suggested API changes.

**Comment by jackc** [comment]
Released today! :tada:

**Comment by ARolek** [comment]
Congrats, and thanks for the great work on this driver!
