### ISSUE TITLE
Issue loading numeric types over Copy

### ISSUE THREAD

**Issue by lox** [jackc/pgx#284]
I'm having some problems getting my custom type to load across the Copy interface:

```
package pgxdecimal

import (
	"log"

	"github.com/jackc/pgx"
	"github.com/shopspring/decimal"
)

type Decimal struct {
	val    decimal.Decimal
	places int32
}

func NewDecimal(val decimal.Decimal, places int32) Decimal {
	return Decimal{val, places}
}

// func (d *Decimal) ScanPgx(vr *pgx.ValueReader) error {
// 	return errors.New("Not implemented")
// }

func (d Decimal) FormatCode() int16 {
	return pgx.BinaryFormatCode
}

func (d Decimal) Encode(w *pgx.WriteBuf, oid pgx.Oid) error {
	ds := d.val.StringFixed(d.places)
	w.WriteInt32(int32(len(ds)))
	w.WriteBytes([]byte(ds))
	return nil
}
```

When I load it with: 

```
	rows := [][]interface{}{}
	for _, price := range prices {
		rows = append(rows, []interface{}{
			price.x,
			price.x,
			price.x,
			price.x,
			price.x.UTC(),
			pgxdecimal.NewDecimal(price.Price, 7),
		})
	}
	return conn.CopyFrom(
		pgx.Identifier([]string{"spot_price"}),
		[]string{
			"x",
			"x",
			"x",
			"x",
			"x",
			"price",
		},
		pgx.CopyFromRows(rows),
	)
```

I get this error:
```
ERROR: invalid sign in external \"numeric\" value (SQLSTATE 22P03)
```

Any ideas?

**Comment by jackc** [comment]
The problem is the `Encode` method. That is not how you encode PostgreSQL `numeric` in the binary format. The binary format is decidedly non-trivial. See https://github.com/jackc/pgx/blob/v3/pgtype/numeric.go for an example.

I suggest trying the `v3` branch. It is still in beta, but it supports `numeric` binary format and includes an extra library that directly works with shopspring/decimal.

**Comment by lox** [comment]
Thanks @jackc, will checkout v3.

**Comment by lox** [comment]
To future me when I come back in another 5 years or so with the same problem (having forgotten about the previous time), the answer is now at https://github.com/jackc/pgx/wiki/Numeric-and-decimal-support.
