### ISSUE TITLE
difficult enum handling

### ISSUE THREAD

**Issue by rothskeller** [jackc/pgx#287]
I'm finding it quite difficult to use this library with tables whose columns have enumerated types.  I say that not to complain, but rather to ask whether there's an easier way that I've missed.  Currently the best way I've found is to set an AfterConnect hook that issues a query against pg_type to find the OID of the type, then calls conninfo.RegisterDataType to register it with pgtype.GenericText.  Is there an easier way?  (BTW, using v3.)

**Comment by jackc** [comment]
You're right, `enum` handling was way too inconvenient. I just pushed a change that should automatically map `enum` at `pgtype.GenericText`.
