### ISSUE TITLE
example url_shortener upsert

### ISSUE THREAD

**Issue by soulne4ny** [jackc/pgx#290]
Hi, Jack!

https://github.com/jackc/pgx/blob/01f261c71ca3cd4f360e569c1a7bf83a24dcf814/examples/url_shortener/main.go#L34
This upsert is a bit too long for pg9.5 and newer. With fresh PG it could be just this (and without race, if I'm not mistaken)
```sql
    INSERT INTO shortened_urls(id, url) VALUES ($1, $2)
    ON CONFLICT (id) DO UPDATE SET url=$2
```

**Comment by jackc** [comment]
Yeah, that example pre-dated PostgreSQL 9.5. I made the update.
