### ISSUE TITLE
nullable string insert fail

### ISSUE THREAD

**Issue by hellower** [jackc/pgx#292]
1. database schema
drop table if exists test;
drop table if exists target;
create table test(id int, name varchar(20), location varchar(30));
create table target(id int, name varchar(20), location varchar(30));
insert into test values(5,'test',null);
commit;

2. null data insert example
----------------------------------------------------------------
package main

import (
	"fmt"
	"os"

	"database/sql"

	"github.com/jackc/pgx"
	"github.com/jackc/pgx/pgtype"
)

func main() {
	var db *pgx.Conn

	// ------------- begin connection ---------------------------------
	var PgConBuilder pgx.ConnConfig

	PgConBuilder = pgx.ConnConfig{
		Host:     "10.xx.xx.xx",
		Port:     5445,
		User:     "mig",
		Password: "mig1234",
		Database: "perf",
	}

	var err error
	db, err = pgx.Connect(PgConBuilder)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connection to database: %v\n", err)
		os.Exit(1)
	}
	defer db.Close()
	//------------- end connection ---------------------------------
	rows, err := db.Query("select * from test")

	var id int
	var name string
	var location sql.NullString   // !!!!!!!!!!!!!!!!!!

	for rows.Next() {
		rows.Scan(&id, &name, &location)
		if !location.Valid {
			fmt.Println("locaion.value is null")
		}
	} // end for

	rows.Close()
	tx, err := db.Begin()
	
      // NO INSERT ERROR
	if _, err := tx.Exec("insert into target values($1, $2, $3)", id, name, location); err != nil {
		panic(err)  
	}
	tx.Commit()
	//------------------------------------------------------------------------
	rows, err = db.Query("select * from test")

	var g_id int
	var g_name string
	var g_location pgtype.Varchar // !!!!!!!!!!!!!!!!!!!
        // var g_location pgx.NullString -- old

	for rows.Next() {
		rows.Scan(&g_id, &g_name, &g_location)
		if g_location.Status == pgtype.Null {
			fmt.Println("locaion.value is null")
		}
	} // end for

	rows.Close()
	tx, err = db.Begin()
       // INSERT ERROR
	if _, err := tx.Exec("insert into target values($1, $2, $3)", g_id, g_name, g_location); err != nil {
		panic(err)  <---------------- PANIC HAPPNED !!!   IS RIGHT BEHAVIOR??
	}
	tx.Commit()
	//------------------------------------------------------------------------
}
---------------------------------------------------------------
3. output
locaion.value is null
----------------------------------------------------------------
locaion.value is null
panic: cannot convert { 1} to Text           <----------- PANIC ocurred
goroutine 1 [running]:
main.main()
        d:/0.GO_WORKSPACE/src/pgx_example/bug/pg.go:81 +0xad0

sorry for my poor english.

**Comment by jackc** [comment]
This line

```
if _, err := tx.Exec("insert into target values($1, $2, $3)", g_id, g_name, g_location); err != nil {
```

needs to be 

```
if _, err := tx.Exec("insert into target values($1, $2, $3)", g_id, g_name, &g_location); err != nil {
```

All `pgtype` types implement all their interfaces on pointer to struct, not struct.

Sorry about the unhelpful error message. I should probably figure out some way to detect this case and give a more helpful error.

**Comment by hellower** [comment]
Thank you !!!
