### ISSUE TITLE
database/sql: feedback for non-DSN DB opener

### ISSUE THREAD

**Issue by kardianos** [jackc/pgx#302]
Related Issue: golang/go#20268
CL: https://go-review.googlesource.com/c/53430

There are two general ways we are considering supporting non-DSN opens.

The current CL has a Connector that is separate from the driver instance. I have a suspicion that it might be better to have the Connector be part of the Driver interface (see the CL comments).

Your feedback on this issue, CL, or the Go issue would be appreciated.

**Comment by jackc** [comment]
For my use cases I don't think it would matter much either way. It doesn't look like it will take more than a handful of lines to support either one. Subjectively, I lean very slightly toward the separate Connector struct.
