### ISSUE TITLE
Why  pgx.Conn.WaitForNotification sometime return conn is busy  Error ? how to avoid it ?

### ISSUE THREAD

**Issue by toplinuxsir** [jackc/pgx#307]
When I call pgx.Conn.Ping method  to check if a connection is alive  or call WaitForNotification 
sometime return conn is busy  Error ? how to avoid it ?

**Comment by jackc** [comment]
ErrConnBusy occurs when the connection is busy (for example, in the middle of reading query results) and another action is attempted. This error indicates a bug in your application or in pgx. It should never occur in correct operation.

**Comment by Gurpartap** [comment]
You might have forgotten to `rows.Close()` or close a transaction.
