### ISSUE TITLE
Some types does not support MarshalJSON

### ISSUE THREAD

**Issue by jeromer** [jackc/pgx#310]
I noticed that types like `timestamptz` does not implement `MarshalJSON`. Is it on purpose ? Why ?

Thanks :)

**Comment by jackc** [comment]
The types that have `MarshalJSON` have been added on a as-needed basis. The main reason other types don't have it is no one has needed it enough to do it.

But for `timestamptz` and a few other types there is an additional issue of the lack of a canonical representation. It could be ISO 8601, milliseconds since Unix epoch, or one of several other "standards".

**Comment by jeromer** [comment]
Hi,

On Tue, Aug 29, 2017, at 09:47 PM, Jack Christensen wrote:
> The types that have MarshalJSON have been added on a as-needed basis.
> The main reason other types don't have it is no one has needed it
> enough to do it.
Ok

> But for timestamptz and a few other types there is an additional issue
> of the lack of a canonical representation. It could be ISO 8601,
> milliseconds since Unix epoch, or one of several other "standards".
Makes sense.

Thanks for replying :)

--
Jérôme Renard

**Comment by azamat-sharapov** [comment]
@jackc how can I implement MarshalJSON for `TimestampArray` type? I've tried following, but it doesn't work:

```
type TimestampArray struct {
  pgtype.TimestampArray
}

func (src *TimestampArray) MarshalJSON() ([]byte, error) {
  log.Println("this never called")
  return []byte(), nil
}
```

**Comment by jackc** [comment]
At first glance it looks fine to me. But whatever the issue is, I don't think it has to do with `pgtype.TimestampArray` -- given that your `MarshalJSON` is never called. Perhaps start with an empty struct and get `MarshalJSON` to be called, and then add `pgtype.TimestampArray` back in.

**Comment by azamat-sharapov** [comment]
@jackc Thanks. It worked after I added `UnmarshalJSON`, because it needs to implement json marshaller interface.
