### ISSUE TITLE
Using this pkg, how can I check whether a table exists or not?

### ISSUE THREAD

**Issue by rafw** [jackc/pgx#322]
Thanks.

**Comment by jackc** [comment]
You can query `information_schema.tables`.

Something like:
```
var n int64
err := conn.QueryRow("select 1 from information_schema.tables where table_name=$1", "users").Scan(&n)
if err == pgx.ErrNoRows {
// table doesn't exist
} else if err != nil {
// some error occurred
    return err
} else {
// table must exist if you got here
}
```

Naturally, you would want to wrap this in a function if this is something you did very often.

**Comment by rafw** [comment]
Let me try.

**Comment by rafw** [comment]
That's great. It works. Thanks a lot!

**Comment by canercetin-randomguy** [comment]
Doesn't work in 2022. Sorry for necromancy,

```go
if err == pgx.ErrNoRows {
			// no problem, table doesnt exist.
			break
		}
```
doesn't catch if there is table or not.

**Comment by canercetin-randomguy** [comment]
> Doesn't work in 2022. Sorry for necromancy,
> 
> ```go
> if err == pgx.ErrNoRows {
> 			// no problem, table doesnt exist.
> 			break
> 		}
> ```
> 
> doesn't catch if there is table or not.

@jackc sorry for pinging and bonging you mate.

**Comment by jackc** [comment]
Same idea still works for me... Slightly updated for v5 using `ctx` and `errors.Is`...

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(ctx)

	exists, err := tableExists(ctx, conn, "services")
	fmt.Println("services", exists, err)

	exists, err = tableExists(ctx, conn, "widgets")
	fmt.Println("widgets", exists, err)
}

func tableExists(ctx context.Context, conn *pgx.Conn, tableName string) (bool, error) {
	var n int64
	err := conn.QueryRow(ctx, "select 1 from information_schema.tables where table_name = $1", tableName).Scan(&n)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}
```

```
services true <nil>
widgets false <nil>
```

**Comment by canercetin-randomguy** [comment]
> Same idea still works for me... Slightly updated for v5 using `ctx` and `errors.Is`...
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"errors"
> 	"fmt"
> 	"log"
> 	"os"
> 
> 	"github.com/jackc/pgx/v5"
> )
> 
> func main() {
> 	ctx := context.Background()
> 
> 	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer conn.Close(ctx)
> 
> 	exists, err := tableExists(ctx, conn, "services")
> 	fmt.Println("services", exists, err)
> 
> 	exists, err = tableExists(ctx, conn, "widgets")
> 	fmt.Println("widgets", exists, err)
> }
> 
> func tableExists(ctx context.Context, conn *pgx.Conn, tableName string) (bool, error) {
> 	var n int64
> 	err := conn.QueryRow(ctx, "select 1 from information_schema.tables where table_name = $1", tableName).Scan(&n)
> 	if err != nil {
> 		if errors.Is(err, pgx.ErrNoRows) {
> 			return false, nil
> 		}
> 		return false, err
> 	}
> 
> 	return true, nil
> }
> ```
> 
> ```
> services true <nil>
> widgets false <nil>
> ```

Slightly updated version works, dunno how it didnt in the previous times.

thanks a lot, and thanks for this amazing project!
