### ISSUE TITLE
WaitForReplicationMessage returns nil, nil

### ISSUE THREAD

**Issue by dimpavloff** [jackc/pgx#327]
Hi! I'm just starting to use `pgx`, it has been very good so far, thanks for writing it!

I'm using pgx to consume logical replication logs via `WaitForReplicationMessage` . I've come across a case where it returns `nil, nil` -- is this intended behaviour and can it safely be ignored?

Details:
I'm using Postgres 9.6 with the `wal2json` plugin (https://github.com/eulerto/wal2json) . When changing a table with a TOASTed column, wal2json checks whether the data on disk has changed or not (https://github.com/eulerto/wal2json/blob/645ab69aae268a81c900671b5dfab7029384e9ff/wal2json.c#L508) and if not, emits a warning and then seems to skip emitting output. 
On the consumer side, I receive the mentioned `nil, nil` pair . Consuming the next message contains the expected change but without the TOASTed column name and value. OTOH, if the change does modify the TOASTed column, there is only one WAL message containing all data.

So it seems to me it's safe to ignore the `nil, nil` but I don't know enough about the replication protocol and the pgx codebase to be sure. The wal2json behaviour might also be at fault (not the omission of the column itself but doing something which is enough to make the consumer think there's a WAL message). 

Thanks

**Comment by jackc** [comment]
I'm not totally sure. I've only used replication log support enough to test it before merging the PR.

It looks like a (nil, nil) would be caused by a CopyBothResponse message: https://github.com/jackc/pgx/blob/master/replication.go#L232

Not sure if that is desirable or not though. It seems like WaitForReplicationMessage should either return a message or an error.

**Comment by dimpavloff** [comment]
Thanks for the info. I think I'll ignore the nil, nil for now, given the comment in the code handling `CopyBothResponse` . Happy to close the issue for now
