### ISSUE TITLE
Improve Scan error message

### ISSUE THREAD

**Issue by emicklei** [jackc/pgx#33]
In query.go, function Scan, it has the statement

```
err = errors.New("Scan received wrong number of arguments")
```

It can be improved when it also states how many it got and expected, such as

"Scan received wrong number of arguments, got 5 but expected 4"

**Comment by gerbenjacobs** [comment]
It appears the arguments are the other way around.

`err = fmt.Errorf("Scan received wrong number of arguments, got %d but expected %d", len(dest), len(rows.fields))`

should become

`err = fmt.Errorf("Scan received wrong number of arguments, got %d but expected %d", len(rows.fields), len(dest))`

**Comment by jackc** [comment]
Can you double-check this? dest is the arguments passed into Scan and rows.fields are the columns in the result set, so it looks right to me...

**Comment by gerbenjacobs** [comment]
I would assume that "got" is what you got from the database and "expected" is what you wrote down in your Scan code?

**Comment by jackc** [comment]
The error message is from the point of view of the Scan call. It got X arguments but expected Y arguments.
