### ISSUE TITLE
Variable support inside the IN clause?

### ISSUE THREAD

**Issue by matthewmueller** [jackc/pgx#334]
I couldn't find any documentation on how to support the IN clause. Is that possible in this library?

Looking for some way to do this:

 ```go
sids := []int{30, 26, 13, 7, 21}
rows, err := pg.Query(`select * from teammate_standups where standup_id in ($1)`, sids)

if err != nil {
	log.WithError(err).Fatalf("query error")
}
defer rows.Close()
```

**Comment by jackc** [comment]
That won't work due to how variables are bound in PostgreSQL. However, there is a simple alternative. Instead of using IN use ANY.

``` sql
select id, name from mytable where id = any($1);
```
See https://www.postgresql.org/docs/current/static/functions-comparisons.html#AEN21108

**Comment by matthewmueller** [comment]
Awesome, thanks for your help Jack!

**Comment by huehnerhose** [comment]
I ended up with the same question, but I don't get it to work


	vals := []int{54, 38140, 705}
	rows, err := db.Query(`SELECT email FROM users WHERE id = any($1)`, vals)

ends in

    cannot convert [54 38140 705] to Int4

any suggestions?

**Comment by jackc** [comment]
I don't think arrays automatically transcode between underlying integer types. Try `[]int32` instead of `[]int`.

**Comment by huehnerhose** [comment]
perfect! thanks

**Comment by el2e10** [comment]
The `id NOT IN $1` operation can by replaced by `id != ALL($1)`.
