### ISSUE TITLE
Query time logging calculates time since last activity, not duration

### ISSUE THREAD

**Issue by gimbalgambit** [jackc/pgx#341]
First: thanks for this great library, it's been really useful!

I noticed that the query logging (query.go, line ~83) uses the row start time to calculate duration, but the start time is set to the connection's last activity time (query.go, line ~341). This seems to mean the value is the time since the connection was last used to the end of the current query, not the duration of the query exec itself.  Updating the row start time to `time.Now()` results in what seems like a more useful measurement, unless I'm misunderstanding what this value is reporting.

Also, the duration property name ("time") collides with a large number of logging libraries' default timestamp field name... it might be worth changing that to "duration" or "queryTime", etc.

**Comment by jackc** [comment]
Good catch. That was a bug in the query path. I just pushed a fix.

As far as changing the name of the property, I like the idea, but I'm worried about it being a minor breaking change if anyone is doing any log analytics or relying on it in some way. I'm not sure what's best. If it's causing you problems open a new issue just for that rename.

**Comment by gimbalgambit** [comment]
Thanks for the fix! 

I think the duration prop name is fine as is: we got around it by embedding the pgx log object in the log JSON behind a key, instead of writing those props directly to it. It might be worth calling out the properties that are logged by default (forgive me if I missed them in the docs - which are great!).

**Comment by jackc** [comment]
I don't see anything in your code that should cause this issue. But I reviewed the relevant pgx source and don't see any likely culprits there either.

I tried the following trivial case and was unable to reproduce this. Do you have a sample case I can try?

``go
package main

import (
	"time"

	"github.com/jackc/pgx"
	"github.com/jackc/pgx/log/logrusadapter"
	"github.com/sirupsen/logrus"
)

func main() {
	logger := logrus.New()

	config, err := pgx.ParseEnvLibpq()
	if err != nil {
		logger.Fatal(err)
	}
	config.Logger = logrusadapter.NewLogger(logger)

	pool, err := pgx.NewConnPool(pgx.ConnPoolConfig{ConnConfig: config})
	if err != nil {
		logger.Fatal(err)
	}
	defer pool.Close()

	for i := 0; i < 3; i++ {
		var n int32
		err = pool.QueryRow("select 1").Scan(&n)
		if err != nil {
			logger.Fatal(err)
		}

		time.Sleep(time.Second)
	}
}
```

**Comment by ear** [comment]
I'm on a deadline right now as soon as I am done I'll whip up a complete reproducible small test case for you. Thanks for answering so promptly!
