### ISSUE TITLE
Performance issues with numeric values

### ISSUE THREAD

**Issue by sdressler** [jackc/pgx#345]
When using pgx to ingest data with very high throughput into PostgreSQL 9.6, then we experience performance breakdowns when using numeric values, e.g. NUMERIC(13,2). We tried to track down the problem and found out, that the conversion is rather slow. However, when using the `Numeric` type directly one has to also first create a `big.Int` which makes things also slow. By slow, we mean orders of magnitude slower plus when used in different go-routines scaling does not work anymore.

Therefore, we are seeking for advice on either how to use pgx with numeric values more optimal to reduce overhead or whether it is possible to do a manual conversion to the binary PG protocol and to pass this data to pgx.

**Comment by jackc** [comment]
Numeric is a bit tricky to handle efficiently. On the Go side the lack of a standard lib big decimal type complicates things. On the PostgreSQL side, the binary format is somewhat complex and is only documented in the source code (it was quite time-consuming to get it working at all).

I'm not sure what to suggest on the performance side without knowing a bit more about how it is being used. When you don't use `pgtype.Numeric` directly is the slowdown on the PostgreSQL server or in your Go code?

And what sort of volume and use case are we talking about? If creating a `big.Int` is enough to cause a substantial slowdown... that must be a pretty extreme amount of throughput.

Regarding directly building the binary format yourself, it definitely can be done. You can use a `pgtype.GenericBinary` type to pass binary formated values directly over the wire. Or you can have your decimal type implement `pgtype.Value`, `pgtype.BinaryEncoder`, and `pgtype.BinaryDecoder` (maybe only `pgtype.BinaryEncoder` if you only send values).

**Comment by sdressler** [comment]
> I'm not sure what to suggest on the performance side without knowing a bit more about how it is being used. When you don't use pgtype.Numeric directly is the slowdown on the PostgreSQL server or in your Go code?

It is definitely in the Go code, it does not scale with e.g. naively adding more go-routines for conversion. Likely there is something with malloc which does not scale up eventually.
 
> And what sort of volume and use case are we talking about? If creating a big.Int is enough to cause a substantial slowdown... that must be a pretty extreme amount of throughput.

Let's put it like this: with only integers we currently get roughly 25 million rows/sec where a row has 40 Bytes in our use case (so actually kudos to you for this library!).

As said above, the bottleneck is mostly with allocation of `big.Int`. So I think a possible solution would be to use a buffer pool but I wanted to avoid that to keep the use case generic.

> Regarding directly building the binary format yourself, it definitely can be done. You can use a pgtype.GenericBinary type to pass binary formated values directly over the wire. Or you can have your decimal type implement pgtype.Value, pgtype.BinaryEncoder, and pgtype.BinaryDecoder (maybe only pgtype.BinaryEncoder if you only send values).

Thanks for the pointers, I will have a look. We usually use numerics <= 8 Byte, so maybe we'd optimize for this case and thus get rid of `big.Int`.

**Comment by jackc** [comment]
Another thought: Does the PostgreSQL server performance suffer if you use the text protocol? Depending on the original format of the data maybe you could leave it as `string` or `[]byte` and let the PG server handle encoding. (The best way to do this with pgx would depend on the type of the original data).

Another related consideration is whether insertion is done with insert statements or the copy protocol.
