### ISSUE TITLE
Support connect_timeout.

### ISSUE THREAD

**Issue by mrxliu** [jackc/pgx#347]
unrecognized configuration parameter "connect_timeout" (SQLSTATE 42704)

postgres://postgres:123456@127.0.0.1:5432/dbname?sslmode=disable&connect_timeout=5&application_name=db-summary

**Comment by jhngrant** [comment]
Set the `Dial` field in the `ConnConfig` struct to use a custom dialer:
```
	cf := pgx.ConnConfig{Host: "db.example.com", User: "usr", Password: "pw"}

	cf.Dial = (&net.Dialer{KeepAlive: 5 * time.Minute, Timeout: 3 * time.Second}).Dial

	_, err := pgx.Connect(cf)

	if err != nil {
		log.Println(err)
	}
```

**Comment by adam-p** [comment]
Is this issue fixed now?
https://github.com/jackc/pgx/blob/a487caf45f558d59da60cc68cf0cd43c0ce048ce/conn.go#L696

**Comment by jackc** [comment]
Yes. This is fixed.
