### ISSUE TITLE
Unknown message type: w

### ISSUE THREAD

**Issue by wingedpig** [jackc/pgx#348]
We use pgx to continuously logical stream from a postgres database. Every day or so, we'll get one or more "unknown message type: w" errors. Tracking it down, it appears to be from backend.go:91. If I am reading the Postgres docs correctly, and I certainly may not be, it indicates a CopyBothResponse message. Do I treat it similarly to CopyOutResponse (ie. flush)? This is Postgres 9.6.

**Comment by jackc** [comment]
I'm not sure what the issue is, but I don't think it is in backend.go. IIRC that not directly used in pgx outside of the test suite. It is a protocol decoder that acts as a PostgreSQL backend.

The only other place that emits that error is the frontend protocol decoder in frontend.go:103.

Looking at the PostgreSQL docs, there are no lower-case 'w' messages. But lower-case 'w' is XLogData sub-messages of the replication CopyData messages.

Not sure how a sub-message would be getting parsed by the top level message parser though. It's a long shot, but could you run with the race detector on?

**Comment by wingedpig** [comment]
Thanks for the response. I will try running it with the race detector, although there's not much concurrency happening. Some additional information: we run 6 processes, each with their own logical decoding slot. When the error happens, some subset of these processes all fail at the same time time with the same error. That makes me think it isn't a race.

Also, when the processes then restart, they will often all receive the same error:

ERROR: got sequence entry 0 for toast chunk 20559150 instead of seq 5931 (SQLSTATE XX000)

(the numbers vary). The processes then restart again. This can happen up to 3 times, getting the same kind of error, then everything goes back to normal.

**Comment by wingedpig** [comment]
Finally got it to fail again with the race detector turned on, and it didn't detect a race. You are right in that it's in frontend.go. I have the message, as a series of bytes. How would you like me to get it to you? And is there anything else I should be looking at?

Here are the logs on the Postgres server when this happens (IPs obscured) (the esstreamer process exits and restarts when we get the 'unknown message' error):

2017-11-12 23:36:01.845 PST 5a08b7c6.13c7 app=esstreamer,client=XX.XX.XX.XX LOG:  could not receive data from client: Connection reset by peer
2017-11-12 23:36:01.845 PST 5a08b7c6.13c7 app=esstreamer,client=XX.XX.XX.XX CONTEXT:  slot "messages_201711061239", output plugin "test_decoding", in the
change callback, associated LSN 17EE/D366BEA8
2017-11-12 23:36:01.845 PST 5a08b7c6.13c7 app=esstreamer,client=XX.XX.XX.XX LOG:  unexpected EOF on standby connection
2017-11-12 23:36:01.845 PST 5a08b7c6.13c7 app=esstreamer,client=XX.XX.XX.XX CONTEXT:  slot "messages_201711061239", output plugin "test_decoding", in the
change callback, associated LSN 17EE/D366BEA8
2017-11-12 23:36:01.845 PST 5a08b7c6.13c7 app=esstreamer,client=XX.XX.XX.XX LOG:  disconnection: session time: 10:29:47.682 user=replicator database=archivedb host=XX.XX.XX.XX port=58758

**Comment by jackc** [comment]
I can take a look at it, but sadly the extent of my first-hand logical replication experience is keeping the tests passing. So I might be a little out of my depth.

You can send me the message via email (it's on my profile) or via keybase (jackc) if you want an encrypted channel.

**Comment by wingedpig** [comment]
fyi, I'm trying to get some more information when it fails, but I haven't run into the bug again. I will let you know when it does.

**Comment by wingedpig** [comment]
It failed again this afternoon and I have more information now. It seems the failure is trigged by a timeout error in frontend.go at line 106, for a CopyData message. So I think what that means is that the initial 5 header bytes are 'lost' and things get out of sync.

Perhaps I am calling WaitForReplicationMessage() with an incorrect context or timeout? Here's my code:

ctx := context.TODO()
ctx, _ = context.WithTimeout(ctx, time.Duration(1 * time.Second)
message, err = replicationConn.WaitForReplicationMessage(ctx)

The code seems to be timing out all the time, but I think that's by design?

**Comment by jackc** [comment]
I don't think you need to specifically need a timeout. I think you can just wait forever if you want. The context is just the mechanism to stop when you choose.

So if your assumptions are correct you could probably work around the issue by not using a timeout.

But if there really is an underlying problem in `pgproto3.Frontend.Receive` then that should definitely be fixed. It wouldn't just affect replication, it could be triggered by a timeout in any query.

**Comment by jackc** [comment]
Yuck, that was a nasty little bug. You were exactly right about the header bytes being lost. I was able to create a test case that reproduces this and then produce a fix.

I'm pretty confident this will resolve the issue, but if perchance it doesn't then feel free to reopen this issue.
