### ISSUE TITLE
NamedArg use in Query

### ISSUE THREAD

**Issue by huehnerhose** [jackc/pgx#351]
Hi,

I hope this doesn't fall in the same category as #294 but:
As far as I understood this answer at [stackoverflow](https://stackoverflow.com/a/47155628/3004786) I should use a syntax like this:

    rows, err := db.Query(
		"SELECT * FROM login WHERE username ILIKE '@user_name'",
		sql.Named("user_name", username),
	)

For creating the query. But I always get 

    Prepared statement \"\" requires 0 parameters, but 1 were provided

as error. Which doesn't make any sense to me.
Any ideas?

**Comment by jackc** [comment]
\@user_name should not be quoted. That is treating it as a literal string. Try this:

```go
rows, err := db.Query(
	"SELECT * FROM login WHERE username ILIKE @user_name",
	sql.Named("user_name", username),
)

**Comment by huehnerhose** [comment]
Thanks for you answer, unfortunately this doesn't work either

    rows, err := conn.Query(
		"SELECT user_id FROM login WHERE username ILIKE @user_name;",
		sql.Named("user_name", "company%"),
	)
	if err != nil {
		logrus.WithError(err).Fatal()
	}

Outputs

     FATA[0000]    error="ERROR: column \"user_name\" does not exist (SQLSTATE 42703)"

I tried a couple different things with and without escaping. Also tried `:user_name` since I read that `pq` seems to use this syntax (or at least discussed using it)

**Comment by jackc** [comment]
Sorry, it was off the top of my head. I haven't used named arguments with database/sql. Positional arguments should work:

```go
rows, err := db.Query("SELECT * FROM login WHERE username ILIKE $1", "company%")
```

**Comment by huehnerhose** [comment]
Thanks, this works and suffices for me.
But NamedArg aren't supported?

**Comment by jackc** [comment]
After looking into this more, named arguments are not supported. I had erroneously thought that database/sql  processed them prior handing off the query to the underlying driver. 

PostgreSQL only has support for positional parameters. This means to support named arguments pgx would need to parse the SQL string and rewrite it to use positional arguments. This is possible, but it feels like a high amount of complexity relative to the utility it provides.

See also https://github.com/lib/pq/issues/534 for pq's discussion of the issue. At the moment they have not implemented it either.

**Comment by huehnerhose** [comment]
ok, thank you very much for the clarification!
