### ISSUE TITLE
CopyFrom fails with "insufficient data left in message"

### ISSUE THREAD

**Issue by shariat** [jackc/pgx#355]
`CopyFrom` fails on `bit(1)`
```sql
CREATE TABLE test (
id smallint NOT NULL,
isparent bit(1)
);
```
```go
tx.CopyFrom(pgx.Identifier{"test"},
[]string{"id", "isparent"},
pgx.CopyFromRows([][]interface{}{
	[]interface{}{
		1, "0",
	},
}))
```

**Comment by jackc** [comment]
Nothing looks out of the ordinary. Any chance of a test case I can try?

**Comment by shariat** [comment]
https://gist.github.com/shariat/c9fbd4a36179b3be8fbf232df347debf

**Comment by shariat** [comment]
I reduced the problem to `bit(1)` type

**Comment by shariat** [comment]
@jackc is there quick solution for now?

**Comment by jackc** [comment]
Ah. pgx didn't directly support the `bit` type. It did support `varbar` and the internal formats are the same. I just added support to master. However, you need to use it a little differently. You need to explicitly use a *pgtype.Bit. 

Beyond that, if you really are using `bit(1)` then I strongly recommend using `bool` instead. `bit` and `varbit` are designed for bit strings. A single bit is much better represented as a `bool`.

```go
package main

import (
	"fmt"
	"log"

	"github.com/jackc/pgx"
	"github.com/jackc/pgx/pgtype"
)

func main() {
	config, err := pgx.ParseEnvLibpq()
	if err != nil {
		log.Fatal(err)
	}

	conn, err := pgx.Connect(config)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	n, err := conn.CopyFrom(pgx.Identifier{"test"},
		[]string{"id", "isparent"},
		pgx.CopyFromRows([][]interface{}{
			[]interface{}{
				1, &pgtype.Bit{Bytes: []byte{1}, Len: 1, Status: pgtype.Present},
			},
		}))
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(n)
}
```

**Comment by sanyamsinghal** [comment]
Hi @jackc i am facing a similar error. Actually what I want to do is load a CSV file(having data as rows of a table in Postgres) into database table.  

I was referring to this [medium blog](https://khanakia.medium.com/copy-with-go-and-postgresql-b349e35e60fc#:~:text=Usage%20example%20with%20pgx)

I am getting:
```
ERROR: insufficient data left in message (SQLSTATE 08P01)
panic: commit unexpectedly resulted in rollback

goroutine 1 [running]:
main.main()
	/home/centos/yb_migrate_projects/golang-drivers/postgres-pgx-copyFrom.go:85 +0x4c5
```

I am new to golang and pgx, not sure if i am doing something wrong.
Anytype of help/suggestions will be highly appreciated.

this is my sample program code
```
package main

import (
	"context"
	"encoding/csv"
	"fmt"
	"io"
	"os"
	"os/signal"

	"github.com/jackc/pgx/v4"
)

type copyFromSource struct {
	r       *csv.Reader
	nextRow []interface{}
	err     error
}

func (s *copyFromSource) Next() bool {
	s.nextRow = nil
	s.err = nil
	record, err := s.r.Read()
	fmt.Printf("Records: %v\n", record)
	if err == io.EOF {
		fmt.Println("EOF: ", err)
		return false
	} else if err != nil {
		s.err = err
		fmt.Println("Error: ", err)
		return false
	}

	s.nextRow = []interface{}{
		record[0], record[1],
	}
	return true
}

func (s copyFromSource) Values() ([]interface{}, error) {
	if s.err != nil {
		return nil, s.err
	}
	return s.nextRow, nil
}

func (s copyFromSource) Err() error {
	return s.err
}

// var _ pgx.CopyFromSource = &copyFromSource{}

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()
	f, err := os.Open("/path/to/data.sql")
	if err != nil {
		panic(err)
	}

	r := csv.NewReader(f)
	r.FieldsPerRecord = -1

	conn, err := pgx.Connect(context.Background(), targetConnectionURI)
	// conn, err := sql.Open("postgres", targetConnectionURI)
	if err != nil {
		panic(err)
	}

	txn, err := conn.Begin(ctx)
	if err != nil {
		panic(err)
	}

	n, err := txn.CopyFrom(ctx, pgx.Identifier{"employees"},
		[]string{"id", "empname"},
		&copyFromSource{r: r})
	fmt.Printf("Num of rows copied: %d\n", n)
	if err != nil {
		fmt.Println(err.Error())
	}

	err = txn.Commit(ctx)
	if err != nil {
		panic(err)
	}
}

```

**Comment by jackc** [comment]
@sanyamsinghal Nothing jumps out at me from that source code.

But if you are using sending a CSV then you would probably be better off using https://pkg.go.dev/github.com/jackc/pgconn#PgConn.CopyFrom. That lets you pipe an `io.Reader` directly to the server and the PostgreSQL COPY protocol natively supports CSV.

**Comment by sanyamsinghal** [comment]
@jackc i think i am using  CopyFrom() and reader in the main() function right? Do you mean i should

**Comment by jackc** [comment]
`pgx.CopyFrom` is a higher level function that runs through the pgx type system. It is built on top of `pgconn.CopyFrom` which is basically just a pipe to copy data. You can use `pgconn.CopyFrom` to copy files like with `\copy` in the `psql` CLI tool. Since your data is already formatted in CSV it might be simpler just to use the lower level `pgconn` function.

**Comment by sanyamsinghal** [comment]
Thanks a lot @jackc for clearing my doubts.
Adding sample code snippet for reference, in case someone wants to look at, later on
```
        freader, err := os.Open(csvFilePath)
	if err != nil {
		panic(err)
	}
	res, err := conn.PgConn().CopyFrom(ctx, freader, fmt.Sprintf(`COPY employees(id, empname) from STDIN (FORMAT CSV)`))
	if err != nil {
		panic(err)
	}
```

**Comment by sanyamsinghal** [comment]
@jackc the file reader we are using in CopyFrom() API, does that reader reads the complete data file first or it keeps reading a chunk of it and keep providing to the server?(becomes important if we have a large data file)

**Comment by jackc** [comment]
It works in chunks.
