### ISSUE TITLE
Question: Using Ex-versions of Exec, QueryRow, Query functions

### ISSUE THREAD

**Issue by nuqz** [jackc/pgx#362]
Hello.

I'm trying to compare `pgx` with a standard `database/sql` package. In the comparison process, I came across the fact that parameter with the `QueryExOptions` type is used to call the subj. functions. As I found out when reading the documentation, this parameter is a structure that has fields - `ParameterOIDs`, `ResultFormatCodes` and `SimpleProtocol`. The problem is that I do not understand how to correctly fill these fields to pass an instance of the structure to a function to use all `pgx` advantages. What documentation should I read?

In general, my final goal is to execute the query using the context that is passed to my function. Maybe I can just pass nil value (or new) as options?

**Comment by jackc** [comment]
Yes, if all you want is context you can pass `nil` for options. Those options are typically only applicable in very narrow use cases.
