### ISSUE TITLE
uuid cannot convert

### ISSUE THREAD

**Issue by umeike** [jackc/pgx#370]
func (dst *UUID) Set(src interface{}) error {
	if src == nil {
		*dst = UUID{Status: Null}
		return nil
	}

	switch value := src.(type) {
	case [16]byte:
		*dst = UUID{Bytes: value, Status: Present}
	case []byte:
		if value != nil {
			if len(value) != 16 {
				return errors.Errorf("[]byte must be 16 bytes to convert to UUID: %d", len(value))
			}
			*dst = UUID{Status: Present}
			copy(dst.Bytes[:], value)
		} else {
			*dst = UUID{Status: Null}
		}
	case string:
		uuid, err := parseUUID(value)
		if err != nil {
			return err
		}
		*dst = UUID{Bytes: uuid, Status: Present}
	default:
		if originalSrc, ok := underlyingPtrType(src); ok {
			return dst.Set(originalSrc)
		}
		return errors.Errorf("cannot convert %v to UUID", value)
	}

	return nil
}

var flag   pgtype.UUID

xxx := flag.Set(uuid.NewV4())

xxx:
cannot convert 8f54383e-0c20-4be2-a46d-34321721ccd6 to UUID

**Comment by jackc** [comment]
It looks like you are using `github.com/satori/go.uuid` with `pgtype.UUID`. `pgtype.UUID` doesn't work directly with `github.com/satori/go.uuid`. But pgx does come bundled with an extension that does. Try using the `UUID` type defined in `github.com/jackc/pgx/pgtype/ext/satori-uuid` instead.

**Comment by umeike** [comment]
ok
