### ISSUE TITLE
how can i copy table data to file?

### ISSUE THREAD

**Issue by weiboyiyou** [jackc/pgx#372]
Hi.
   I find copy method,but copy_to  and copy_from  only  copy data to table,how can I copy table data to a file?

**Comment by jackc** [comment]
pgx doesn't have any packaged functionality to dump a table to a file. There's no one file format that would be appropriate.

Simplest solution is just to run a query with `select * from table` and write it row by row to whatever format you need. pgx only loads a single row into memory at a time so it should work this way regardless of file size.
