### ISSUE TITLE
Support for bpchar

### ISSUE THREAD

**Issue by kwoodhouse93** [jackc/pgx#375]
I've noticed a lack of support for the `bpchar` type when using pgtype with a postgres database. `bpchar` is the name of the type used internally to represent `CHAR(n)` fields.

In the application I'm working on, I'm trying to dynamically determine the data type of the columns after connecting to a previously unknown database. To achieve this, I'm using the `FieldDescriptions()` on a `pgx.Rows`.

The `DataType` field in the `FieldDescription` returns the OID, which can be referred to using the constants specified in `pgtype/pgtype.go`.

The OID returned for a `CHAR(n)` column is `1042`, which is accompanied by the `DataTypeName` of `bpchar`.

For my particular use case, I'd like to add a constant to `pgtype/pgtype.go` that refers to the OID for `bpchar`, such as:
```go
BpcharOID = 1042
```

So I have a couple of questions:
* Is there any particular reason this hasn't been added yet?
* Would adding this constant also require adding further support for this data type?

_(For the avoidance of ambiguity, it might be worth mentioning that the type with the `DataTypeName` of `char` is actually postgres' internal `char` type, which is a single byte character)_

**Comment by jackc** [comment]
There was no reason it wasn't there other than no one had built it yet.

However, I just merged in #368 from @aka-rider which adds `bpchar` support.

See if that will work for you.

**Comment by kwoodhouse93** [comment]
Looks good. Thanks to both of you for getting this support in!
