### ISSUE TITLE
Invalid numeric format Postgresql

### ISSUE THREAD

**Issue by pifagor87** [jackc/pgx#378]
I used https://github.com/jackc/pgx, and
```
for rows.Next() {
        rowValues, err := rows.Values()
```
Tables field type character varying, json, integer - ok
But  numeric format field returns wrong values: 
![image](https://user-images.githubusercontent.com/5397541/34737031-8a4e2d66-f57d-11e7-8695-c9940d34019b.png)
id - ok, it is format integer
the rest of the fields are incorrect output because they are numeric.
The reason for using rows.Values() is because I get SQL dynamically, so rows.Scan() does not suit me.

**Comment by jackc** [comment]
I'm guessing you are marshalling the results to JSON? If so, the reason you are seeing that is `pgtype.Numeric` does not implement `MarshallJSON`. So each internal field is being dumped.

I'm open to adding a `MarshallJSON`, but we'd need to determine a format. I suppose it would have to be a string since it could overflow the JSON number type.

**Comment by pifagor87** [comment]
the problem is not in Jason, but in the fact that the wrong data type returns. `fmt.Print (val)` returns the same result. All other types work well.
How do I return the type (float64 / int) to the numeric column?

**Comment by jackc** [comment]
PostgreSQL `numeric` can contain values larger than `float64` or `int64`. That's why `Values()` can't return those types.

If you have control of the SQL and you know the values are small enough to fit in `float64` or `int64` then you can convert them in SQL.

e.g.

`select mynumericcolumn::float8 from mytable`

**Comment by pifagor87** [comment]
> select mynumericcolumn::float8 from mytable

this is not the best solution.
For example, I have code -  https://github.com/pifagor87/select_db_microservice/blob/master/select_db_microservice.go#L157
See line https://github.com/pifagor87/select_db_microservice/blob/master/select_db_microservice.go#L164
Values are obtained dynamically.
Is it possible to check the type and change the type? But how do I return the type (float64 / int) to the numeric column?

**Comment by jackc** [comment]
Well, `numeric` has a bigger range than `float64` or `int64` so any conversion has the potential to be out of range or lose precision. But if you _really_ need to do it this way, you could call the `Value()` method on `pgtype.Numeric` which will return a string. Then you can use the appropriate parse functions to convert that to a `float64` or `int64` as desired. (Or just use the string if this is just for reporting / display)

By the way, in my cursory look at the code you linked to I didn't see any query parameter sanitization -- as in it's probably vulnerable to SQL injection.

**Comment by pifagor87** [comment]
> By the way, in my cursory look at the code you linked to I didn't see any query parameter sanitization -- as in it's probably vulnerable to SQL injection.

My SQL is formed dynamically. What would you recommend for better protection?

**Comment by jackc** [comment]
Where ever you are directly interpolating a value you should instead be putting `$1`, `$2`, `$3`, etc. In a separate array you can accumulate the values. Then pass the SQL string and the values to Query and it will sanitize them for you.

See https://github.com/jackc/tpr/blob/master/backend/data/item.go#L175 and https://github.com/jackc/tpr/blob/master/backend/data/item.go#L208 for an example. The code is fairly complex but if you study the `buildNewItemsSQL` function you can see how it dynamically builds a SQL string and separately accumulates the query arguments.
