### ISSUE TITLE
Is there a way to create connection pool over ssh?

### ISSUE THREAD

**Issue by romanoff** [jackc/pgx#382]
Is there a way to create pgx connection pool over ssh? I found this example for pq:
https://gist.github.com/vinzenz/7b6b1bf8d0c2b2b1e0d69a15ba9f02c7

**Comment by romanoff** [comment]
Looks like this should work:
```

**Comment by Carson-JG** [comment]
I may be missing something, but I did have issues connecting to an AWS RDS through an EC2 bastion this way.

`ssh: tcpChan: deadline not supported`

the solution was to implement a wrapper around net.Conn that ignores deadline-related methods.

```
type noDeadlineConn struct{ net.Conn }

func (c *noDeadlineConn) SetDeadline(t time.Time) error      { return nil }
func (c *noDeadlineConn) SetReadDeadline(t time.Time) error  { return nil }
func (c *noDeadlineConn) SetWriteDeadline(t time.Time) error { return nil }
```

I then updated the dial function as such:

```
Dial: func(network, addr string) (net.Conn, error) {
	conn, err := sshConn.Dial(network, addr)
	if err != nil {
		return nil, err
	}
	return &noDeadlineConn{Conn: conn}, nil
},
```

This seems pretty hacky to me, so I welcome another solution, but this was the most simple one I could come up with.

**Comment by d-bytebase** [comment]
I'm encountering the same issue "ssh: tcpChan: deadline not supported". Hope there's a standard support.
