### ISSUE TITLE
Invalid Message Format in pgproto3 startup_message.go

### ISSUE THREAD

**Issue by avrono** [jackc/pgx#383]
I am debugging a msg sent by my nodejs postgres driver

  
  \x00\x00\x00\x40\x00\x03\x00\x00\x75\x73\x65\x72\x00\x70\x6f\x73\x74\x67\x72\x65\x73\x00\x64\x61\x74\x61\x62\x61\x73\x65\x00\x72\x6f\x74\x61\x5f\x6f\x70\x00\x63\x6c\x69\x65\x6e\x74\x5f\x65\x6e\x63\x6f\x64\x69\x6e\x67\x00\x27\x75\x74\x66\x2d\x38\x27\x00\x00

This is a valid startupMessage according to the spec, but your algorithm would always throw and InvalidMessage error, due to the \x00\x00 at the message end 

    dst.Parameters = make(map[string]string)
	    for {
		idx := bytes.IndexByte(src[rp:], 0)
		if idx < 0 {
			return &invalidMessageFormatErr{messageType: "StartupMesage"}
		}
		key := string(src[rp : rp+idx])
		rp += idx + 1

		idx = bytes.IndexByte(src[rp:], 0)
		if idx < 0 {
			return &invalidMessageFormatErr{messageType: "StartupMesage"}
		}
		value := string(src[rp : rp+idx])
		rp += idx + 1

		dst.Parameters[key] = value

		if len(src[rp:]) == 1 {
			if src[rp] != 0 {
				return errors.Errorf("Bad startup message last byte. Expected 0, got %d", src[rp])
			}
			break
		}
	}

Might need to change the loop to 
      for rp < len(src) - 1 { ... }

**Comment by jackc** [comment]
I'm unable to duplicate this:

```go
package pgproto3_test

import (
	"fmt"
	"testing"

	"github.com/jackc/pgx/pgproto3"
)

func TestBadMessage(t *testing.T) {
	t.Parallel()

	msg := []byte("\x00\x00\x00\x40\x00\x03\x00\x00\x75\x73\x65\x72\x00\x70\x6f\x73\x74\x67\x72\x65\x73\x00\x64\x61\x74\x61\x62\x61\x73\x65\x00\x72\x6f\x74\x61\x5f\x6f\x70\x00\x63\x6c\x69\x65\x6e\x74\x5f\x65\x6e\x63\x6f\x64\x69\x6e\x67\x00\x27\x75\x74\x66\x2d\x38\x27\x00\x00")

	dst := &pgproto3.StartupMessage{}
	err := dst.Decode(msg[4:]) // Decode takes message without length prefix 
	if err != nil {
		t.Fatal(err)
	}

	fmt.Println(dst)
}
```

Output:

```
jack@happy:~/dev/go/src/github.com/jackc/pgx/pgproto3$ go test
&{196608 map[user:postgres database:rota_op client_encoding:'utf-8']}
PASS
ok  	github.com/jackc/pgx/pgproto3	0.001s
```

**Comment by avrono** [comment]
Fair enough must be user error, I will check my end again ...
