### ISSUE TITLE
CopyFrom hangs on custom string-type values

### ISSUE THREAD

**Issue by mastercactapus** [jackc/pgx#384]
It seems that when passing a custom string-type to CopyFrom for an enum column, it hangs indefinitely. 

Possibly related to #335, though I have not observed any panic.

If CopyFrom is used directly after creating the table & type (same connection), an "unknown oid" error is returned.
Subsequent attempts result in the indefinite hang.

Steps to reproduce:

1. Start postgres (if not already)
    `docker run -it -p 5432:5432 --rm postgres:9.6`

2. Run the sample code below:

```go
package main

import "github.com/jackc/pgx"

type Test string

const Example = Test("hello")

func main() {
	c, err := pgx.Connect(pgx.ConnConfig{
		Database: "postgres",
		User:     "postgres",
	})
	if err != nil {
		log.Fatal(err)
	}
	c.Exec("create type test as enum ('hello')")
	c.Exec("create table example (value test)")

	src := pgx.CopyFromRows([][]interface{}{
		{Example},
	})
	_, err = c.CopyFrom(pgx.Identifier{"example"}, []string{"value"}, src)
	// never makes it here (after first attempt)
        fmt.Println("done")
	if err != nil {
		log.Fatal(err)
	}
	c.Close()
}
```

**Comment by jackc** [comment]
There are a few possibly intersecting issues here. First, pgx reads on the PostgreSQL type catalog when it first connects and builds a translation table of OID (type ID number) to conversion routine. pgx wouldn't know to handle a runtime created type (or rather it would treat it as generic text).  

In addition, the copy protocol requires all columns to be encoded in binary or text (normal queries allow mixing and matching). pgx only supports the binary copy protocol. PostgreSQL enum types are numbers internally and the PostgreSQL binary protocol reflects this. So PostgreSQL is expecting something like `[]byte{0,0,0,1}` and it would receive `[]byte("hello")` (or rather I think the pgx copy routine detects this problem and aborts before sending).

Ignoring the issue of creation of types at runtime, there are two potential solutions.

1. Enhance pgx's enum support such that it reads the internal mapping of enum int -> text so it could encode and decode enums in binary.
2. Support the text copy protocol in addition to the binary protocol and fall back to it automatically if not all columns can be encoded in binary.

**Comment by jackc** [comment]
I suspect the hang may be resolved in 20c02acd637eed8407fe5a77b49d0f5a459aba6e.

**Comment by bfontaine** [comment]
@mastercactapus did the fix mentioned above resolve your issue?

**Comment by bfontaine** [comment]
I’m closing this. Please reopen the issue if the fix above didn’t resolve the issue.
