### ISSUE TITLE
field some custom OR array TYPE has values on last field

### ISSUE THREAD

**Issue by ruslanBik4** [jackc/pgx#386]
Hello.Thank for fine lib!
 Work with pgx is very fast!
But, some problem.
If my query return filed with some type (I noticed on arrays and own types) and i get result in this way:
 
 rows, err := conn.Query(sql, args ...)
for rows.Next() {
 values, err := rows.Values
...
}
All fields that have a similar type have the same data!
Proc return:
volumes bigint[], total_volume integer, pnls double precision[], total_pnl double precision, nets double precision[]

Type data was pgtype.Float8ArrayOID, pgtype.Int8ArrayOID.

values for 'volumes', 'pnls', 'nets' has same data
I change my code:
				columns := rows.FieldDescriptions()
				row := make([]interface{}, len(columns) )
				for rows.Next(){
					for i, value := range columns {
						switch value.DataType {
						case pgtype.Float8ArrayOID:
							row[i] = &pgtype.Float8Array{}
                                               case pgtype.Int8ArrayOID:
							row[i] = &pgtype.Int8Array{}
...
and this way correct work.

I read code pgx and found this problem site:
.../github.com/jackc/pgx/query.go
line 289
		if dt, ok := rows.conn.ConnInfo.DataTypeForOID(fd.DataType); ok {
			value := dt.Value
this dt has type * Datatype and dt.Value is references of datatype !
Scannin put data from buffer in the same place.
 Imho, this is bug
 I replace method Get my custom types  that he should return value instand reference an d this work. 
But I don't think than this is good solution.
Bets regard
Ruslan

**Comment by jackc** [comment]
Sorry about that. Fixed by creating a new value each time.
