### ISSUE TITLE
Does pgx pass the compatibility test suite?

### ISSUE THREAD

**Issue by lpar** [jackc/pgx#391]
The Go wiki [imples that](https://github.com/golang/go/wiki/SQLDrivers) pq is the only Go PostgreSQL driver which passes the test suite. Does pgx pass the test suite? If so, it would be a good idea to mention it prominently in the README and get the wiki page updated.

**Comment by jackc** [comment]
It passed when I submitted a PR adding pgx 3 1/2 years ago (https://github.com/bradfitz/go-sql-test/pull/10). However, it never got a response and that repo hasn't had any subsequent commits -- so I presume it is abandoned.

**Comment by lpar** [comment]
Excellent. I've added an edit to the wiki page and will check out pgx for my projects. Thanks.

**Comment by dcu** [comment]
the wiki includes pgx now as compatible
