### ISSUE TITLE
driver.Valuer checked after fuzzy finding pgtype datatype?

### ISSUE THREAD

**Issue by mb0** [jackc/pgx#393]
i have a `type Time time.Time` that implements driver.Valuer.
however Time.Value  is never called instead `encodePreparedStatementArgument` looks up `pgtype.Timestamptz` by oid first and uses that.
there is a fallback on oid lookup error and a Valuer check after it.

i was surprised and want to check in if this is the expected behavior.

big thanks for a great project

**Comment by mb0** [comment]
just checked with `ConnConfig.PreferSimpleProtocol = true` and the Valuer is checked first then

so there is at least mismatch in behavior.

**Comment by jackc** [comment]
I have a very vague recollection that there might be some reason for that. Possibly something to do with types that implement both `database/sql` and `pgx`'s encoding and decoding interfaces. That along with the need to determine whether to use text or binary format sometimes leads to some complicated logic.

Let me make sure I understand the issue. What sort of error or visibly wrong behavior is happening (I presume something caused you to dig in and find this underlying issue)?

**Comment by mb0** [comment]
i had a wrapper `type Time time.Time` that converted zero times to sql nulls and back. it works for database/sql and it also worked with pgx v2 and pgx v3 PreferSimpleProtocol. but normal v3 will type check for {Text,Binary}Encoder then check the type chain for a pgtype compatible value and only as a fallback checks for driver.Valuer. this only poses a problem for renamed type (like my time wrapper) because the underlying type matches a pgtype supported type.

i suspected and now understand that this is an issue only for types like time.Time that provider a driver.Valuer, because pgx prefers to use the more flexible pgtype wrapper. so matching valuer is only a fallback option.

i now use the pgtype transcoders api instead. it is certainly better than driver.Valuer but like driver.Valuer the pgtype api also requires any package using it to pull in that dependency. but that is only a theoretical concern, because i will never use anything other than postgresql with pgx anyway :)

i would have been happy to either have a one-liner hinting at the issue in the docs or the source. i think at least the mismatch in behavior regarding the simple protocol option justifies a line in the package documentation in the custom type mapping section. it doesn't have to be a full explanation because it is an edge case, but a hint would help identifying the issue much faster.

thank you again. and consider that request for clarification closed on my end. have fun!

**Comment by jackc** [comment]
Sounds good. Added some docs in b931b56.
