### ISSUE TITLE
RunTime parameters are never copied in Conn connect() method

### ISSUE THREAD

**Issue by rupor-github** [jackc/pgx#397]
Looks like new c.RuntimeParams are created (= make(map[string]string) but old values from passed in config never copied or copied too late.

I was using pgx to work with Vertica which requires "simple protocol" and that as a result causes a check for 'client_encoding=UTF8' in sanitizeAndSendSimpleQuery(). When initializing connections using ConnPool it is not possible to pass in proper RuntimeParams and connection always fails in sanitizeAndSendSimpleQuery check.

**Comment by jackc** [comment]
I'm not able to duplicate this behavior in ad hoc testing. And there are already tests that cover what I think you are referring to. `TestConnect` tests the runtime parameters sent from the server to the client are correctly recorded and `TestConnectWithRuntimeParams` ensures that runtime params sent from the client to the server during connection are applied.

Perhaps I'm not understanding the issue correctly. Can you provide some example code demonstrating this problem.

**Comment by rupor-github** [comment]
Version 3.1.0, conn.go:345 - passed in parameters are properly copied into startupMsg from passed in config:

`
	// Copy default run-time params
	for k, v := range config.RuntimeParams {
		startupMsg.Parameters[k] = v
	}
`

However they never stored in connection itself. conn.go:305 
`
	c.RuntimeParams = make(map[string]string)
`
As the result parameters are properly passed on to server, but if simple protocol was specified later gueary.go:522 in sanitizeAndSendSimpleQuery() there is a check:

`
	if c.RuntimeParams["client_encoding"] != "UTF8" {
		return errors.New("simple protocol queries must be run with client_encoding=UTF8")
	}
`
It always fails - even if config has proper client_encoding set - because parameters where never preserved in connection itself. 

It may be that I misunderstood how it supposed to work and only Vertica behaves this way, however if I store a copy of config.RuntimeParams in connection.RuntimeParams - everything works properly.

**Comment by jackc** [comment]
This might be a behavior difference between PostgreSQL and Vertica. PostgreSQL sends the client its runtime parameters at connection time (so it's not necessary for the client to remember what it requested).

```
package main

import (
	"fmt"
	"log"

	"github.com/jackc/pgx"
)

func main() {
	config, err := pgx.ParseEnvLibpq()
	if err != nil {
		log.Fatal(err)
	}

	conn, err := pgx.Connect(config)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	for k, v := range conn.RuntimeParams {
		fmt.Println(k, v)
	}

}
```

When I run this I get a bunch of runtime params back from PostgreSQL - including `client_encoding` and including the runtime parameter I send to it `application_name`.

```
jack@happy:~/dev/go/src/github.com/jackc/pgx-397$ PGHOST=/var/run/postgresql PGAPPNAME=testparams go run main.go 
server_version 10.3 (Ubuntu 10.3-1.pgdg16.04+1)
standard_conforming_strings on
TimeZone localtime
IntervalStyle postgres
client_encoding UTF8
DateStyle ISO, MDY
integer_datetimes on
is_superuser on
server_encoding UTF8
session_authorization jack
application_name testparams
```

It'd be interesting to see what Percona does with this test.

**Comment by rupor-github** [comment]
We switched to using ODBC driver anyways - I just thought it may be of interest to you, since code to support different storage backends is there...

**Comment by jackc** [comment]
Thanks. Assuming that is a Percona issue I believe there is a simple workaround - use the AfterConnect hook to set the RuntimeParams that Percona should have sent.

Feel free to re-open this if this is proves unworkable.
