### ISSUE TITLE
Allow the configuration of demoting all logging levels to a chosen, highest log level

### ISSUE THREAD

**Issue by heedson** [jackc/pgx#398]
The logging for the conn package and the database calls is very useful and detailed but having it hardcoded with checks such as the following means that a query-heavy service will have fairly cluttered logs.
https://github.com/jackc/pgx/blob/a07b87eb8b695206914b6387082883fcce6f9913/conn.go#L1689
As there are other `LogLevelDebug` and `LogLevelWarn` used throughout the package, it would be interesting to allow the option to set all `Info` level to, at most, `Debug` level too.

Or, perhaps add a `QueryLogLevel` which allows a user of the package to tamper with the query log level without affecting anything else that may exist.

Other ideas appreciated, but I believe that a configurable log level would be useful with *any* reasonable implementation.

**Comment by jackc** [comment]
Can you elaborate further? I'm not sure what you mean by demoting log levels. Separating query logging from other log info sounds interesting though.

**Comment by heedson** [comment]
Sorry, demotion probably isn't the right word. When interacting with this library with my own code, I would like to remove `Info` query messages from my own logs and "demote" them to `Debug`.

Why I say demote and not anything else is because a common way of moving the level down would be to move the `Debug` to `Trace`, `Error` to `Warn` etc, etc and `Info` to `Debug`. I don't think that would be entirely useful for this issue. I think, as you pointed out, that separating query logging into a separate type of logging would be interesting and would allow users to customise how verbose your library would be.

Another way I've found to solve this, which might be more the intended way, is to write my own logrus adapter based on the logrusadapter you have. All I do is simply catch both `DebugLevel` and `InfoLevel` in the same `case` and output both as `LogLevelDebug`. To me, this sounds like a reasonable solution as I believe the idea is to write the adapters to suit your own needs.

However, modifiable/separate query logging could be neat :)

**Comment by graineri** [comment]
Why was this closed? Is there a way to log queries as `debug` instead of `info`?
