### ISSUE TITLE
Loss of precision for geometric data types

### ISSUE THREAD

**Issue by galdor** [jackc/pgx#399]
Various geometric data types (box, circle, line, lseg, path, point, polygon) currently use `%f` for text serialization. This causes a loss of precision because `%f` does not include more than 6 decimal digits.

There is AFAIK no way to include all decimal digits without using scientific notation in printf-style strings, but `float64` values can be correctly formatted using `strconv.FormatFloat(value, 'f', -1, 64)`.

**Comment by jackc** [comment]
Good catch! Fixed in  cb44310.

**Comment by galdor** [comment]
Thank you very much !
