### ISSUE TITLE
Question: Any way i can create test connection pool or mock connection pool?

### ISSUE THREAD

**Issue by vladyslav2** [jackc/pgx#404]
I have software that heavily based on pgx and i don't want to create an additional interface for testing

Can I create a test version of the connection where I can write/read from a simple buffer?

Thank you

**Comment by jackc** [comment]
That's somewhat tricky. pgx can't be mocked directly, you have to mock above or below it.

Above meaning you have a data access layer that lives above pgx and you mock at that level. That's the approach I prefer for applications.

The other approach is below it. Package `github.com/jackc/pgx/pgmock` contains functionality for a mock PostgreSQL server. pgx uses this package to test tricky edge or timing dependent cases. However, it is extremely low level -- as in it mocks at the level of the PostgreSQL wire protocol message. It would be quite difficult to use without an extensive knowledge of the PostgreSQL wire protocol, and even then it would be awkward to use for general purpose query mocking. It really would need an additional utility layer to be usable.

**Comment by jackc** [comment]
*If* you do want to go down the path of mocking a PG server then, yes, I would suggest a middle layer to make it easier to specify the mocks. But I still suspect that would be rather difficult.

From the other direction, even if you have no plans to use something other than pgx, decoupling the application layer from the data layer *can* make for cleaner code as well as the ability to test easier.

There is one other option we haven't discussed. That is integrating over the database. Rather than mock the PostgreSQL server, load it with the appropriate data for each test, then run the test against an actual server. This is the approach I take in the majority of the time I am testing application code. Here's one example: https://github.com/jackc/tpr/blob/master/backend/http_test.go#L80

**Comment by jackc** [comment]
This issue appears to be inactive, but FWIW pgx `v4` uses an interface for `Rows` and `Tx` instead of a pointer to struct as it used to. This means that the core query path is now mockable.

**Comment by enfipy** [comment]
I use `cockroachdb` and now setting up the test environment. Is it possible to start new database via code and then connect to it? With help of cockroach documentation I started new db and it returned `sql.DB` instance (or pq.Conn). Is it possible to create pgx instance from these kind of types?

**Comment by jackc** [comment]
pgx needs to actually dial the server to create a connection -- it can't consume a `sql.DB` or `pq.Conn`.

**Comment by enfipy** [comment]
> pgx needs to actually dial the server to create a connection -- it can't consume a `sql.DB` or `pq.Conn`.

So it's not possible to set up a connection with a database that was started via code? What is workaround of this issue?

**Comment by jackc** [comment]
I don't really understand what you mean...  "a database that was started via code". pgx doesn't have anything to do with starting a database. It's a database client not a server or something that controls a server. And the feature the original post was discussing is mocking i.e. not using a server at all.

**Comment by enfipy** [comment]
Started via code - download binary of database and start it from tests. There is a "testserver" from `cockroach` - [here](https://github.com/cockroachdb/cockroach-go/tree/master/testserver). I was wondering is it possible to do something similar to it but with pgx?

**Comment by jackc** [comment]
Well, at a quick glance I would say you use `NewTestServer()` then call `PGURL()` to get the connection string to. use with pgx.

**Comment by denghejun** [comment]
You guys also can take look at this repo, to mock pgxpools, it works for me: https://github.com/driftprogramming/pgxpoolmock

```
func TestName(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	// given
	mockPool := pgxpoolmock.NewMockPgxPool(ctrl)
	columns := []string{"id", "price"}
	pgxRows := pgxpoolmock.NewRows(columns).AddRow(100, 100000.9).ToPgxRows()
	mockPool.EXPECT().Query(gomock.Any(), gomock.Any(), gomock.Any()).Return(pgxRows, nil)
	orderDao := testdata.OrderDAO{
		Pool: mockPool,
	}

	// when
	actualOrder := orderDao.GetOrderByID(1)

	// then
	assert.NotNil(t, actualOrder)
	assert.Equal(t, 100, actualOrder.ID)
	assert.Equal(t, 100000.9, actualOrder.Price)
}
```
