### ISSUE TITLE
Logical replication TIMELINE argument

### ISSUE THREAD

**Issue by buoto** [jackc/pgx#405]
I was using logical replication API recently and I've noticed that [Postgres docs](https://www.postgresql.org/docs/current/static/protocol-replication.html) never mention `TIMELINE` as an argument for `START_REPLICATION ... LOGICAL`. That option is allowed only for `PHYSICAL` replication.
However [StartReplication](https://github.com/jackc/pgx/blob/606697ffdfe6603013560dbc171656de57b4f542/replication.go#L404) which uses only logical replication accepts `timeline` argument and adds it to query. Is that a bug or am I missing something?

**Comment by jackc** [comment]
It appears incorrect from the docs, but it is surprising that PostgreSQL would not return an error if the query message was incorrect. I don't have enough familiarity with the physical or logical replication protocols to speak with any confidence though.

**Comment by buoto** [comment]
A quick dive into [PostgreSQL source code](https://github.com/postgres/postgres/blob/9d4649ca49416111aee2c84b7e4441a0b7aa2fac/src/backend/replication/repl_gram.y#L306) shows that timeline argument is treated as one of decoding plugin options. If using pgoutput logical decoding (which is default in PostgreSQL10) this can lead to an error since it accepts ["proto_version" and "publication_names" arguments](https://www.postgresql.org/docs/current/static/protocol-logical-replication.html#PROTOCOL-LOGICAL-REPLICATION-PARAMS).

I haven't tested it out on real database yet but I also discovered that there are no [tests](https://github.com/jackc/pgx/blob/master/replication_test.go#L78) which use the TIMELINE argument (note that when `timeline == -1` we don't add this arg to query). That would explain why `StartReplication` function works.

I all of this appears to be true I think the `timeline` argument should be removed from `StartReplication` function since it's not used in default PostgreSQL decoding plugin.

**Comment by buoto** [comment]
Ok, so I've done a little experiment. I've run postgresql server in docker:
```
docker run --name psql10 -p 5432:5432 postgres:10 -c"wal_level=logical"
``` 
And then I've executed this code https://play.golang.org/p/vEAgIHcgswh

When passing timeline argument different than `-1` (which omits it) server returned `ERROR: syntax error (SQLSTATE 42601)`. I have tested both "test_decoding" and "pgoutput" logical decoding plugins. I've also tested that on PostgreSQL 9.5. Neither of combinations worked.

**Comment by jackc** [comment]
Well, that does seem fairly definitive that timeline doesn't belong in logical connections. 

Looking through the existing code it's not clear to me to what extent it is expected to work with physical replication. This should probably be clarified a bit. But I'm not sure what is best or what changes can be made without breaking backwards compatibility.
