### ISSUE TITLE
Create publication

### ISSUE THREAD

**Issue by buoto** [jackc/pgx#406]
Postgres 10 added new [Publication/Subscription](https://www.postgresql.org/docs/10/static/logical-replication-publication.html) mechanism. It would be great if pgx offered methods dedicated for publication management.

That would be useful while utilizing logical replication because `START_REPLICATION` command [requires passing of publication names](https://www.postgresql.org/docs/10/static/protocol-logical-replication.html#PROTOCOL-LOGICAL-REPLICATION-PARAMS) as options.

**Comment by jackc** [comment]
Sounds good to me. But as of now I haven't used logical replication so I don't have the background to know how this would best be done.

**Comment by buoto** [comment]
I could try working on a PR soon, since I am going to use that feature anyway.

**Comment by buoto** [comment]
Ok, after a second thought I realized that I was wrong. There is no reason to distinguish "CREATE PUBLICATION" query from the others. I assumed that pgx API operates on a higher level. What I wanted to achieve could be done with simple: `conn.Query("CREATE PUBLICATION ...")`.

Sorry for the confusion.
