### ISSUE TITLE
Cannot encode type when first in the argument list

### ISSUE THREAD

**Issue by jeromer** [jackc/pgx#407]
Given the following SQL:

    CREATE DOMAIN public.uint64 AS numeric(20,0)
            CONSTRAINT uint64_check CHECK (((VALUE >= (0)::numeric) AND (VALUE <= '18446744073709551615'::numeric)));

    CREATE TABLE public.test (
        a public.uint64 NOT NULL,
        b numeric(20,0) NOT NULL
    );

Inserting data containing a uint64 fails with the following error if the uint64
appears at the first position of the argument list in QueryRow():

    Cannot encode uint64 into oid xxxxx - uint64 must implement Encoder or be converted to a string

Given the following INSERT:

	INSERT INTO test(a, b) VALUES($1, $2) RETURNING *;

And the following code:

    b := uint64(1234)

    a2 := new(pgtype.Numeric)
	a2.Set(a)

	var x uint64
	var y pgtype.Numeric

	err = pool.QueryRow(stmt.Name, a2, b).Scan(&x, &y)

The line is inserted.

However, in `pool.QueryRow(stmt.Name, a2, b)...` if you swap `a2` and `b` then you will see the error described above.

Attached [pguint64.go.gz](https://github.com/jackc/pgx/files/1884943/pguint64.go.gz) which reproduces the problem.

Postgres 9.6 with pgx 3.0.1

:)

**Comment by jackc** [comment]
It appears that the issue isn't the location in the parameter list -- it is encoding a Go uint64 into an unknown PostgreSQL type. pgx uses type names and type OIDs to determine how to encode and decode values. Creating a domain means the an unknown name and an unknown OID for the new domain type.

It might be possible to inspect the `pg_type` table for domains and use `typbasetype` column to automatically map domain types properly...

... a while later ...

Master now has support for automatically handling domain types.

**Comment by bkeroackdsc** [comment]
> Master now has support for automatically handling domain types.
@jackc Is this documented anywhere? Composite types are documented but that doesn't seem to be applicable to simple domain types like this example.

**Comment by jackc** [comment]
@bkeroackdsc Do you have a case that is not working? I think it should "just work".

**Comment by bkeroackdsc** [comment]
Yes, I had a simple domain type modeling an enum (really just an unsigned int):

```sql
CREATE DOMAIN uint AS integer
CHECK( VALUE >= 0 );

CREATE TABLE foo (
-- ...
status uint,
-- ...
);
```

I was attempting to insert into the table with the fields of this struct:

```go
type FooStatus int

const (
	FooStatusUnknown FooStatus = iota
	FooStatusSuccess
	FooStatusFailure
)

type Foo struct {
// ...
Status FooStatus
// ...
}

func(ctx context.Context) {
  db.Exec(ctx,`INSERT INTO foo (status) VALUES ($1);`, FooStatusUnknown)
}
```

The result from pgx was this error:

```
Cannot encode int into oid 16819 - int must implement Encoder or be converted to a string
```

**Comment by jackc** [comment]
Ah. pgx can usually figure out what to do if it recognizes the Go type or the PostgreSQL type. But the problem in this particular example is both types are unknown. There is an unknown type `uint` on the PostgreSQL side and an unknown type `FooStatus` on the Go side.

You'll need to either implement `Encode*` and `Decode*` methods on `FooStatus` or register `uint` with the pgx `Conn`. See this test https://github.com/jackc/pgx/blob/11428bbc02a720cf612d528ae07ab7aa8422ba18/conn_test.go#L837 for an example of using `RegisterDataType()`. You would probably use `pgtype.Int4` as the type to handle your domain type.
