### ISSUE TITLE
can't scan into dest[0]: cannot assign 1 into []uint8

### ISSUE THREAD

**Issue by mcz** [jackc/pgx#413]
Hello

First of all thank you for this fantastic library. Truly the best PG client lib for Go. 

The problem I have found is that I have a table with a bigint primary key and some other columns, like text and timestamptz. I want to clone this table in a way that scan all column values into a []byte and transfer the raw bytes to another machine, than do an insert using []bytes. But the problem is I can't scan the bigint type column into a []byte. For rows.Scan() I get this error:

can't scan into dest[0]: cannot assign 1 into []uint8

Thanks
Peter

**Comment by jackc** [comment]
pgx supported scanning any arbitrary value into a `[]byte` in `v2` but `v3` does not. In `v3` the type conversion is stricter to prevent undetected errors when accidentally scanning into a mismatched type.

You now need to explicitly ask for the binary value with `pgtype.GenericBinary.

Sample code:

```go
package main

// create table t (
// 	n bigint
// );

// insert into t values(1);

import (
	"fmt"
	"log"

	"github.com/jackc/pgx"
	"github.com/jackc/pgx/pgtype"
)

func main() {
	config, err := pgx.ParseEnvLibpq()
	if err != nil {
		log.Fatal(err)
	}

	conn, err := pgx.Connect(config)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	var n1 pgtype.GenericBinary
	err = conn.QueryRow("select n from t").Scan(&n1)
	if err != nil {
		fmt.Println("pgtype.GenericBinary", err)
	}
	fmt.Printf("n1: %#v\n", n1)
}
```
Output:

```
jack@happy:~/dev/go/src/github.com/jackc/pgx-413$ go run main.go 
n1: pgtype.GenericBinary{Bytes:[]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1}, Status:0x2}
```

**Comment by mcz** [comment]
thanks so much, i will go this way!
