### ISSUE TITLE
How to convert pgx.Rows from Query() to json array?

### ISSUE THREAD

**Issue by grench** [jackc/pgx#417]
I tried func for sql.Rows, but it doesn't work for pgx.Rows

 ```
func PgSqlRowsToJson(rows *pgx.Rows) []byte {
	fieldDescriptions := rows.FieldDescriptions()
	var columns []string
	for _, col := range fieldDescriptions {
		columns = append(columns, col.Name)
	}

	count := len(columns)
	tableData := make([]map[string]interface{}, 0)
	values := make([]interface{}, count)
	valuePtrs := make([]interface{}, count)
	for rows.Next() {
		for i := 0; i < count; i++ {
			valuePtrs[i] = &values[i]
		}
		rows.Scan(valuePtrs...)
		entry := make(map[string]interface{})
		for i, col := range columns {
			var v interface{}
			val := values[i]
			b, ok := val.([]byte)
			if ok {
				v = string(b)
			} else {
				v = val
			}
			entry[col] = v
		}
		tableData = append(tableData, entry)
	}
	jsonData, _ := json.Marshal(tableData)

	return jsonData
}
```
The problem is that Scan() doesn't work with interface{} and it works with explicitly defined types only.
Can you help me how to fix it?

**Comment by jackc** [comment]
[Rows.Values](https://godoc.org/github.com/jackc/pgx#Rows.Values) should be easier to work with when you are dealing with arbitrary rows where you don't know the number of type of columns ahead of time.

Beyond that, consider building the JSON in PostgreSQL. Much simpler Go code and quite possibly superior performance as well. This [article](https://hashrocket.com/blog/posts/faster-json-generation-with-postgresql) is slightly dated but it covers the basics of the SQL.

**Comment by abhijitgujar86** [comment]
Hello @jackc , I am new to Golang after doing some research I concluded that pgx will be a good lib for my project although GROM is easy pgx seem to be good at performance .  I want to know how can we use Rows.Values .. can you add an example ? It will help many developers like me thanks .

**Comment by DrakoRod** [comment]
> Hello @jackc , I am new to Golang after doing some research I concluded that pgx will be a good lib for my project although GORM is easy pgx seem to be good at performance . I want to know how can we use Rows.Values .. can you add an example ? It will help many developers like me thanks .

I made two examples, for the new function with [Values](https://github.com/DrakoRod/pgx-rowstojson), but I consider is better make json in PostgreSQL directly as said jackc. I upload another example to do [this](https://github.com/DrakoRod/pgx-pgjsontogo) too. I hope it helps.
