### ISSUE TITLE
RegisterDataType with a connection pool

### ISSUE THREAD

**Issue by lzambarda** [jackc/pgx#418]
Hey there everyone!

I'm currently following [this example](https://github.com/jackc/pgx/blob/master/example_custom_type_test.go) to understand how to register custom data types with this library. However I'm currently using a connection pool, hence the `ConnInfo` object is not exported and available, impeding me from writing anything like:

`conn.ConnInfo.RegisterDataType(pgtype.DataType{`

Does anybody have a suggestion on how to solve this?
I'm currently digging in the documentation, but it looks sparse when it comes to custom types registration.
Thanks in advance for your help!

**Comment by lzambarda** [comment]
A quick and "dirty" fix is to make `connInfo` public in [https://github.com/jackc/pgx/blob/master/conn_pool.go](https://github.com/jackc/pgx/blob/master/conn_pool.go), but maybe that's not safe to do with pools?

**Comment by lzambarda** [comment]
Nevermind, I found out that one can use [https://github.com/jackc/pgx/blob/master/conn.go#L66](https://github.com/jackc/pgx/blob/master/conn.go#L66) to set up custom data type registration after the main connection is established.

**Comment by lummie** [comment]
This doesn't seem to point to a relevant line anymore, how did you register the data type for all connections in the pool?

**Comment by jackc** [comment]
> This doesn't seem to point to a relevant line anymore, how did you register the data type for all connections in the pool?

Use the `BeforeConnect` hook.

**Comment by ubiuser** [comment]
Isn't it `AfterConnect` instead? `BeforeConnect` uses `*pgx.ConnConfig`, whereas `AfterConnect` and `BeforeAcquire` both use `*pgx.Conn` that has the `*pgtype.ConnInfo` field. This is the Config struct: https://github.com/jackc/pgx/blob/master/pgxpool/pool.go#L90

I also found this repo that might be useful for those who ended up here with their search: https://github.com/sbowman/hermes-pgx/blob/master/hermes.go#L70

**Comment by jackc** [comment]
> Isn't it AfterConnect instead?

My mistake. You are correct.
