### ISSUE TITLE
Expose connection transaction state

### ISSUE THREAD

**Issue by erikgrinaker** [jackc/pgx#421]
It would be useful to know the state of the current transaction, e.g. if it is aborted due to a previous error.

As far as I can tell, this state is already tracked in `Conn.txStatus`, but not available through a public interface. If possible, it would be great to have this exposed through the relevant `Tx`, although a method on the `Conn` struct would be fine as well.

**Comment by jackc** [comment]
Does this do what you need? https://godoc.org/github.com/jackc/pgx#Tx.Status

**Comment by erikgrinaker** [comment]
I'm afraid not, it returns `TxStatusInProgress` when the transaction is aborted due to error. It looks like it only takes into account the final commit/rollback state, not the preceeding states such as those returned by `PQtransactionStatus`:

> The status can be PQTRANS_IDLE (currently idle), PQTRANS_ACTIVE (a command is in progress), PQTRANS_INTRANS (idle, in a valid transaction block), or PQTRANS_INERROR (idle, in a failed transaction block). PQTRANS_UNKNOWN is reported if the connection is bad. PQTRANS_ACTIVE is reported only when a query has been sent to the server and not yet completed.

**Comment by jackc** [comment]
Hmm. That would seem to be a design flaw in `Tx.Status`.

I just pushed branch `issue421` with a potential fix. It added a new Tx status `TxStatusInFailure`. Whenever `Tx.Status()` is called and the Tx is in progress it checks the underlying connection to see if it has failed. If so it records the failure state of the transaction.

**Comment by jackc** [comment]
Good catch. I was thinking the only possible actions were `commit` and `rollback`.

`rollback to savepoint` violates another assumption I was making that a transaction once broken would stay broken. But savepoints clearly violate that assumption.

Hmm...

**Comment by erikgrinaker** [comment]
Thanks, looks good now. 👍

**Comment by jackc** [comment]
Just merged it into master.
