### ISSUE TITLE
Question: Is sql.Out supported?

### ISSUE THREAD

**Issue by srikrsna** [jackc/pgx#422]
Is [this](https://golang.org/pkg/database/sql/#Out) feature that came out with Go 1.9 supported ?

**Comment by jackc** [comment]
No. I'm not sure how that would work with PostgreSQL functions. As I understand it, PostgreSQL functions with output params are simply another way of specifying a row return type.

**Comment by lafriks** [comment]
@jackc Can this be reopened?

Problem is that you can not use currently this library to call stored procedures that use some kind of internal transaction logic in them.

Example:

```go
	_, err = tx.Exec(`CALL test_proc($1, $2)`, sql.Named("pi_data", msg), sql.Named("po_data", sql.Out{Dest: &rec, In: false}))
	if err != nil {
		panic(err)
	}
```

Would result in error: `cannot convert {{} 0xc000099210 false} to Text`

If `tx.Query` is usded to get out value it fails with error: `2D000`, `invalid transaction termination` as plpgsql procedure calls with internal transaction managment can only be used in queries

Such funcionality does work in other language postgresql drivers.

**Comment by jackc** [comment]
You can use `QueryRow` instead.

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v4"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

	_, err = conn.Exec(context.Background(), `create or replace procedure testproc(inout foo int) language plpgsql as $$
	begin
		foo := 42;
	end;
	$$;`)
	if err != nil {
		log.Fatal(err)
	}

	var foo int
	err = conn.QueryRow(context.Background(), "call testproc(1)").Scan(&foo)
	if err != nil {
		log.Fatal(err)
	}

	log.Println("foo", foo)
}
```

Output:
```
2021/05/29 11:03:20 foo 42
```
