### ISSUE TITLE
Question: Listen/Notify demo

### ISSUE THREAD

**Issue by nkev** [jackc/pgx#43]
Could you please add a simple listen notify demo? It looks like your notify function times out and you have to keep polling the database  after each timeout... I'm not sure how that would work.

**Comment by GoodiesHQ** [comment]
Does this work using the stdlib API using the go sql driver or do you have to use the pgx API?

**Comment by jackc** [comment]
database/sql does not have an interface for listen / notify. You have to use the pgx API. However, you can retrieve a pgx connection from database/sql with https://pkg.go.dev/database/sql#Conn.Raw.
