### ISSUE TITLE
Needless fork: "github.com/jackc/fake"

### ISSUE THREAD

**Issue by onlyjob** [jackc/pgx#430]
[github.com/jackc/fake](https://github.com/jackc/fake) <sup>\[**[1]**\]</sup>, appears to be an unmaintained fork (lacking commits since 2015) of [github.com/icrowley/fake](https://github.com/icrowley/fake).

Needless forking is harmful. Please consider switching to `github.com/icrowley/fake`.

Thanks.

[1]: https://github.com/jackc/pgx/blob/master/stress_test.go#L14

**Comment by justinclift** [comment]
Hmmm, the last few commits of the jackc fork do appear different.

**Comment by brandonkal** [comment]
Opening needless issues on the wrong repository is harmful @onlyjob 

Please consider closing this.

Thanks.

**Comment by onlyjob** [comment]
This bug is valid as the obsolete fork is used by the code of this project, @brandonkal.

**Comment by brandonkal** [comment]
I see what you mean @onlyjob
