### ISSUE TITLE
no error returned from Query method

### ISSUE THREAD

**Issue by ikitiki** [jackc/pgx#432]
I wonder why I get no `ERROR #22012 division by zero` error from the Query method:

```go
package main

import (
	"log"

	"github.com/jackc/pgx"
)

func main() {
	config, err := pgx.ParseEnvLibpq()
	if err != nil {
		log.Fatal(err)
	}

	conn, err := pgx.Connect(config)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	_, err = conn.Query("select 1/0")
	if err != nil {
		log.Fatal(err)
	}
}
```

(lib/pq and go-pg do return expected error from the Query method)

**Comment by jackc** [comment]
The error is not returned until you try to read the results. Try `Next()`/`Scan()` and you will see the error.

**Comment by ikitiki** [comment]
thank you for the fast response.
I think that might be a small issue for the guys like myself who are switch from lib/pq

**Comment by jackc** [comment]
I suspect this may reflect a different approach to buffering results.

For example, what should happen with this query?

```sql
select 1 / (5 - n) from generate_series(1, 10) n;
```

Some clients / drivers buffer the entire result before returning the result. They will return an error without returning any rows. This can be convenient, but it also means the entire result set will be stored in memory at one time.

pgx avoids buffering and thereby only requires memory for 1 row at a time. pgx would yield rows until n = 5, then it would hit the divide by 0 error.

This example makes it more obvious what is happening, but the same underlying behavior is exhibited by `select 1/0`. The query is valid so pgx sends it to the server and the server successfully parses and begins executing it. It is only after the server is sending rows that the error occurs. It just so happens the error is on the first row.

**Comment by davars** [comment]
What do you think about this example?
```
SELECT version_id, is_applied from goose_db_version ORDER BY id DESC
```

When the table doesn't exist, I would expect Query to return `ERROR: relation "goose_db_version" does not exist`.  This is what the goose migration library expects, at least.

I need to call Next & Scan in order to get the error with pgx.

**Comment by jackc** [comment]
`Query` only sends the query to the server. It doesn't attempt to read any results. So as long as there isn't an error sending it over the wire (or in an implicit prepare if there are arguments) it won't return an error until `Next` and `Scan`.

Changing this would require `Query` to block until the first row or error is returned. I'd prefer not to require that.

**Comment by WilliamG-LORA** [comment]
I put a fmt.Println("hi") right after calling `Query`. No error message but the print is never reached. Any ideas on how to troubleshoot?

**Comment by jackc** [comment]
> I put a fmt.Println("hi") right after calling Query. No error message but the print is never reached. Any ideas on how to troubleshoot?

- Use dlv and step through until it hangs.
- Use ctrl+\ to cancel your program and dump the stack trace.
- Pass a context with a timeout. If the timeout does break out of the call it almost certainly is a network issue.
