### ISSUE TITLE
replication connection queries

### ISSUE THREAD

**Issue by mkabilov** [jackc/pgx#435]
looks like starting from postgresql 10.0 it is possible to run queries using replication connections:

pg 9.6:
```
$ psql -At "host=localhost user=postgres dbname=postgres replication=database" -c "select * from pg_type limit 1"
ERROR:  42601: syntax error
LOCATION:  replication_yyerror, repl_scanner.l:216
```

pg 10.0:
```
$ psql -At "host=localhost user=postgres dbname=postgres replication=database" -c "select * from pg_type limit 1"
bool|11|10|1|t|b|B|t|t|,|0|0|1000|boolin|boolout|boolrecv|boolsend|-|-|-|c|p|f|0|-1|0|0|[null]|[null]|[null]
```

so the lines https://github.com/jackc/pgx/blob/master/conn.go#L383-L387 don't make any sense in case of postgresql 10

**Comment by jackc** [comment]
I suppose we could check the version the server sent back to decide whether to run that code or not. But that change alone would not allow running queries from replication connections. The `ReplicationConn` type doesn't expose query methods. That would have to change as well.

But before going down that path I question what is the purpose of running queries on the same connection that is receiving replication data? At first thought it seems to add the potential for quite a bit of difficult to reason about behavior.

**Comment by ikitiki** [comment]
in my case I need to create a temporary logical replication slot and in the same transaction access a table

**Comment by jackc** [comment]
Well, I guess I'm open to merging a change that allows this, but I think it might be tricky to get to work.
