### ISSUE TITLE
CopyFrom ignore conflicts

### ISSUE THREAD

**Issue by chrboe** [jackc/pgx#437]
When doing an insert, one can simply specify `on conflict do nothing` to ignore unique constraint violations. I was wondering if there's anything I can do to achieve the same behavior while utilizing the much faster `CopyFrom` protocol.

**Comment by jackc** [comment]
To my knowledge the copy protocol does not have any such functionality.

If you are working with a large number of records at once it may be faster to copy to a temporary table, then insert from the temporary table to the real table with `on conflict do nothing`.
