### ISSUE TITLE
Table Relationship Support Documentation?

### ISSUE THREAD

**Issue by valarauca** [jackc/pgx#440]
Could this be documented somewhere? I was wondering if [`preload` like calls are needed like `gorm`](http://doc.gorm.io/associations.html#has-one) or how it functions in `pgx`? 

I couldn't find the term "related", "foreign key", or "primary key" in the code base. So even doing deep dives into the code proved fruitless.

**Comment by jackc** [comment]
pgx is a database driver. It doesn't have any ORM tools like query building or struct mapping. It's more like lib/pq than gorm.

**Comment by valarauca** [comment]
thanks!
