### ISSUE TITLE
inconsistent CommandTag and SQL

### ISSUE THREAD

**Issue by leslie-qiwa** [jackc/pgx#441]
After upgrading to ubuntu 18.04, postgres 10.0 and PGX v3.1.0. One of our test failed, and return this message `Prepared statement "" requires 0 parameters, but 1 were provided`

I can not reproduce using simple program, but below is debug message. Seems like problem happens because of inconsistent commandTag and SQL `INFO[0000] Exec                                          args="[]" commandTag=ROLLBACK pid=16708 sql=begin time="11.442µs"`. Tag shows ROLLBACK, but actual SQL is begin. 

By adding some debug message, I found out after above suspicious `Begin`, `QueryRow` will call ` (c *Conn) sendPreparedQuery` by passing `length of PreparedStatement.ParameterOIDs = 0`, which then throw above error message.

```
  func (c *Conn) sendPreparedQuery(ps *PreparedStatement, arguments ...interface{}) (err error) {
    if len(ps.ParameterOIDs) != len(arguments) {
      return errors.Errorf("Prepared statement \"%v\" requires %d parameters, but %d were provided", ps.Name, len(ps.ParameterOIDs), len(arguments))
    }
```

I'm still troubleshooting, but due to lack of deep knowledge, I think it might worth publishing what I found so far, and hope to get your help so that I don't spend time on other wrong directions.

```
INFO[0000] Exec                                          args="[]" commandTag=BEGIN pid=16708 sql=begin time="66.584µs"
INFO[0000] Query                                         args="[true]" pid=16708 rowCount=1 sql="select count(*) from queue_items where running=$1" time="429.279µs"
INFO[0000] Exec                                          args="[]" commandTag=ROLLBACK pid=16708 sql=rollback time="63.158µs"
INFO[0000] Exec                                          args="[]" commandTag=BEGIN pid=16708 sql=begin time="25.436µs"
INFO[0000] Query                                         args="[false]" pid=16708 rowCount=1 sql="select count(*) from queue_items where running=$1" time="142.76µs"
INFO[0000] Exec                                          args="[]" commandTag=ROLLBACK pid=16708 sql=rollback time="67.204µs"
INFO[0000] Exec                                          args="[]" commandTag=BEGIN pid=16708 sql=begin time="52.158µs"
INFO[0000] Query                                         args="[]" pid=16708 rowCount=13 sql="select proname, oid from pg_catalog.pg_proc\nwhere proname in (\n'lo_open',\n'lo_close',\n'lo_create',\n'lo_unlink',\n'lo_lseek',\n'lo_lseek64',\n'lo_tell',\n'lo_tell64',\n'lo_truncate',\n'lo_truncate64',\n'loread',\n'lowrite')\nand pronamespace = (select oid from pg_catalog.pg_namespace where nspname = 'pg_catalog')" time="605.415µs"
INFO[0000] Exec                                          args="[]" commandTag=COMMIT pid=16708 sql=commit time=5.640613ms
INFO[0000] Exec                                          args="[]" commandTag=BEGIN pid=16708 sql=begin time="127.105µs"
INFO[0000] Query                                         args="[true]" pid=16708 rowCount=1 sql="select count(*) from queue_items where running=$1" time="280.202µs"
INFO[0000] Exec                                          args="[]" commandTag="SELECT 1" pid=16708 sql=rollback time="19.921µs"
INFO[0000] Exec                                          args="[]" commandTag=ROLLBACK pid=16708 sql=rollback time="56.347µs"
INFO[0000] Exec                                          args="[]" commandTag=ROLLBACK pid=16708 sql=begin time="11.442µs"
ERRO[0000] Query                                         args="[false]" pid=16708 sql="select count(*) from queue_items where running=$1"
INFO[0000] Exec                                          args="[]" commandTag= pid=16708 sql=rollback time="14.278µs"
INFO[0000] Exec                                          args="[]" commandTag=ROLLBACK pid=16708 sql=rollback time="6.909µs"
```

**Comment by jackc** [comment]
That's very odd. Nothing immediately jumps out to me, but here's a few ideas.

1. Try the master branch of pgx. There are some bug fixes in it that aren't in the latest tagged release.
2. `begin` returning `ROLLBACK` as command tag does seem to be an error. But sometimes the command tag can be unexpected. For example, calling `commit` on a broken transaction will return the command tag of `ROLLBACK`. Probably not what's going on here, but worth keeping in mind.

**Comment by leslie-qiwa** [comment]
Thanks for looking into it. Regarding #2, actually this causes one SQL error `Prepared statement "" requires 0 parameters, but 1 were provided`. I'll try master and see if it can be reproduced.

**Comment by leslie-qiwa** [comment]
Seems like master branch can not reproduce the issue. Just wonder when you are going to have new release. Then probably I can try again.

**Comment by jackc** [comment]
Guess it has been a while since I tagged a stable release ... Okay, just pushed 3.2.0.
