### ISSUE TITLE
How do I replicate db.SetConnMaxLifetime() behavior?

### ISSUE THREAD

**Issue by perrito666** [jackc/pgx#442]
I am migrating from a different driver and ORM to an in house package using pgx, while moving my config I find that I am not sure how to replicate the behavior of `db.SetConnMaxLifetime(time.Minute)` for pgx connections in a pool to prevent `querying database: write tcp xx.xx.xx.xx:yyyyy->xx.xx.xx.xx:yyyyy: write: broken pipe `

**Comment by perrito666** [comment]
In a follow up of this question, after setting a dialer with a custome keepalive to mitigate this i am starting to think the problem is caused by a query containing 650 arguments, has the pgx driver been tested with large amount of args?

**Comment by jackc** [comment]
To answer your first question, at the moment the pgx connection pool does not support max lifetime for connections.

As far as large numbers of arguments, pgx is tested with the protocol maximum of 65,535 parameters: https://github.com/jackc/pgx/blob/master/conn_test.go#L1385

**Comment by perrito666** [comment]
Tx for both, ill be researching a bit into this, i have implemented a parallell version of the connection logic to use stdlib to see of indeed the connection time is a problem. If the issue is with the query ill make sure to submit a test case and possibly a fix

**Comment by jackc** [comment]
It definitely would be useful. Just not something anyone has dedicated time to make happen yet.

**Comment by brianchizhang** [comment]
This would be great to have, making migration from other libraries much easier when you have additional components controlling the lifecycle of connections.

**Comment by jackc** [comment]
This is implemented in `v4` (currently prerelease).
