### ISSUE TITLE
Return DSN string from ConnConfig

### ISSUE THREAD

**Issue by mohanraj-r** [jackc/pgx#445]
Is there the counterpart of `func ParseDSN(s string) (ConnConfig, error)` that returns a DSN string from a `ConnConfig`? Would be helpful to create `ConnConfig` object and pass its corresponding DSN string to `sql.Open()` rather than mucking around with constructing a DSN string directly from conn params.

**Comment by jackc** [comment]
Sorry, there is not. However, you might be able to use stdlib.OpenDB if you are on Go 1.10+. You'll need to be on master or pgx 3.2.0 (just released today) to have access to it.

**Comment by mohanraj-r** [comment]
Yes I am using `stdlib.OpenDB()`. Thanks.
