### ISSUE TITLE
I have Valuer type implemented, but pgtype.JSONB is used and it does not use Value() when assigning value to a jsonb column

### ISSUE THREAD

**Issue by MOZGIII** [jackc/pgx#449]
I have an issue with jsonb type.

I have custom variant of encoding (in the json format) that I want to use to store the record in the database.

I implement `database/sql/driver.Valuer` (and `Scanner`) and assign the value to the jsonb column (via `ExecEx` and `INSERT INTO table SET val=$1`, where `val` is `jsonb`).

What pgx does, is it, at some point, calls `chooseParameterFormatCode`, there it detects that it's a jsonb type column (from OID) and assigns `pgtype.JSONB` to do the encoding. Unfortunately, instead of calling `Valuer()` function on my type, `JSONB` calls `MasrshalJSON`.

How can I enforce my `Valuer` func to be called? It generates valid json too, but just using a different encoder (`github.com/golang/protobuf/jsonpb`).

My idea is to add proper support for `Valuer` in the `pgtype.JSON`.

**Comment by jackc** [comment]
Hmm. Do you have some sample code? I would expect it to work the way you want.

Also, not sure if this may interact with your use case, but FYI `jsonb` doesn't preserve JSON formatting -- so one JSON encoder should have the same end result as another.

**Comment by jackc** [comment]
Should be working now.

**Comment by MOZGIII** [comment]
Works great, thanks!
