### ISSUE TITLE
Potential issue with JSON encoder

### ISSUE THREAD

**Issue by MOZGIII** [jackc/pgx#450]
Consider this code:

https://github.com/jackc/pgx/blob/aa561b8f3c545aad9e0b5fb1514e440d330dd016/pgtype/json.go#L72-L80

On line 76 we have:

https://github.com/jackc/pgx/blob/aa561b8f3c545aad9e0b5fb1514e440d330dd016/pgtype/json.go#L76

I think it should be `*v = ""`, as currently it just seems to do nothing.

**Comment by jackc** [comment]
I think your right that the current code incorrectly does nothing. But I don't think that it should assign empty string. Other types return an error when when assigning a non-Present PgType to a simple value.

**Comment by MOZGIII** [comment]
Doing nothing explicitly is ok too

**Comment by jackc** [comment]
As of 302c74f21445c64df9877e9fff960e305b255233 calling pgtype.JSON.AssignTo(*string) when the value is NULL will return an error. This brings it into conformity with pgtype.Text.AssignTo behavior.
