### ISSUE TITLE
Get SQL Error Detail

### ISSUE THREAD

**Issue by lzambarda** [jackc/pgx#452]
When running a query causing an error, PostgreSQL usually gives you both the ERROR message and the DETAIL message, which contains a more specific message about what is going on.

Is it possible to get such DETAIL message whenever an SQL query fails?

**Comment by jackc** [comment]
Errors that are returned by the server are returned as the [PgError](https://godoc.org/github.com/jackc/pgx#PgError) type. That should have what you want.

**Comment by lzambarda** [comment]
Ah I didn't spot that at a first glance, thank you!

**Comment by bravecow** [comment]
@lzambarda hi. Can you helps please to get Detail of 'err = tx.Commit(ctx)' error? It is returned as `error`, but not `PgError` type.
