### ISSUE TITLE
FieldDescription Modifier

### ISSUE THREAD

**Issue by ikitiki** [jackc/pgx#457]
`FieldDescription`.`Modifier` should be a signed int, currently it is [uint32](https://github.com/jackc/pgx/blob/master/messages.go#L27)

https://www.postgresql.org/docs/current/static/catalog-pg-attribute.html: "...the value will generally be -1 for types that do not need atttypmod."

**Comment by cbandy** [comment]
The [docs for `RowDescription`](https://www.postgresql.org/docs/current/static/protocol-message-formats.html) message also say Int32.

**Comment by jackc** [comment]
Good catch. Fixed in 897e90f.
