### ISSUE TITLE
Rows.FieldDescriptions() and SimpleProtocol

### ISSUE THREAD

**Issue by cbandy** [jackc/pgx#459]
Knowing that the [Simple Query flow](https://www.postgresql.org/docs/current/static/protocol-flow.html) sends a `RowDescription` message, I expected the following to work:

```go
options := &pgx.QueryExOptions{SimpleProtocol: true}
rows, err := conn.QueryEx(context.Background(), `SELECT 1 AS n`, options)
log.Print(err, rows.FieldDescriptions())
```

However, the result is an empty slice:

```
2018/09/18 15:44:31 <nil> []
```

It is only after calling `rows.Next()` that fields are populated:

```go
rows.Next()
log.Print(rows.FieldDescriptions())
```
```
2018/09/18 15:44:31 [{n 0 0 23 4 int4 4294967295 0}]
```

The documentation for `Rows.FieldDescriptions()` doesn't mention this relationship. Should a call to this method work before any call to `Rows.Next()`?

**Comment by jackc** [comment]
Hmm... That's interesting. It probably _should_ work. The query functions send the query and return without waiting for a response. In the normal query flow they already have the row description from the prepare.

This could be tricky.

One possibility would be for the query method to wait for the RowDescription message before returning. But I haven't thought through the implications of what that would mean if multiple queries were supplied or a non set returning query -- even though those aren't a good idea, a hang is undesirable.
 
I suppose it would be better for the Rows.FieldDescriptions to know that it hasn't received the RowDescription message and block until it gets it. Not sure what the side-effects of that would be.

**Comment by bfontaine** [comment]
Four years later, is this issue still relevant?

**Comment by jackc** [comment]
It's fixed. Not sure if this happened in pgx v4 or v5 but it definitely works now.

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(ctx)

	rows, err := conn.Query(ctx, "select 1 as n", pgx.QueryExecModeSimpleProtocol)
	if err != nil {
		log.Fatal(err)
	}

	log.Print(rows.FieldDescriptions())
}
```

```
jack@glados ~/dev/pgx_issues/pgx-459 ±master⚡ » go run .
2022/11/12 05:08:25 [{n 0 0 23 4 -1 0}]
```
