### ISSUE TITLE
should there be a separate type for LSN?

### ISSUE THREAD

**Issue by mkabilov** [jackc/pgx#462]
as an alias for `uint64`

**Comment by jackc** [comment]
I don't know. What do you see as the benefits or liabilities?

**Comment by ikitiki** [comment]
basically it can improve code readability and type checks.
There's already `OID` type, why not to have `LSN` one as well

**Comment by jackc** [comment]
Seems reasonable.

Only issue is it would be a minor breaking change if we used it in some existing public functions. It looks like `FormatLSN` and `ParseLSN` are the only ones. I guess they could be deprecated. Or it's a really tiny change that would only affect a tiny number of people... maybe it would be worth making the change in a minor release.

Also, if we wanted them to be full citizens of the pgtype package we would need a raw value and a nullable type like we have for `OID` and `OIDValue`.

**Comment by ikitiki** [comment]
I guess it's better to break it now as there only around [1](https://github.com/hasura/pgdeltastream)[0](https://github.com/ikitiki/logical_backup) [p](https://github.com/pagarme/warp-pipe)[r](https://github.com/chobostar/pg_listener)[o](https://github.com/wal-g/wal-g)[j](https://github.com/Juniper/contrail)[e](https://github.com/rvenkatesh25/dibileaks)[c](https://github.com/silviucm/pgtogogen)[t](https://github.com/nickelser/pg_warp)[s](https://github.com/cbandy/pgbarrel) on github which use `FormatLSN` and/or `ParseLSN` functions at the moment. And I'm pretty sure there will be more in the future.

**Comment by jackc** [comment]
All right. I'm convinced. If you want to make this change I'll merge it.

**Comment by jackc** [comment]
I think it is too late now to do this for pgx `v3`. But in `v4` the logical replication support has been extracted to a separate package (https://github.com/jackc/pglogrepl) and this change was made there.
