### ISSUE TITLE
Fetching from the end of a cursor does not return ErrNoRows 

### ISSUE THREAD

**Issue by galdor** [jackc/pgx#465]
If I create a cursor (`DECLARE test CURSOR FOR ...`) then read it (`FETCH 100 FROM test`), I get multiple rows as expected. However once all data have been read, `Query()` continues to return a valid `*Rows` value with zero row available from it and no error, instead of returning `ErrNoRows` as expected.

This is a problem because I have a function which uses a cursor to read data from a query passed as parameter, and execute a callback for each batch read. Since I cannot detect that all results have been read, each callback has to return how many rows were actually read to be able to stop the loop.

Is that on purpose ? Is there something I can do to detect that no row was read by the `FETCH` instruction ?

Thank you in advance.

**Comment by galdor** [comment]
The following program reproduces the problem:

```go
package main

import (
	"fmt"
	"log"

	"github.com/jackc/pgx"
)

func main() {
	cfg := pgx.ConnConfig{Host: "localhost", Database: "test"}
	conn, err := pgx.Connect(cfg)
	if err != nil {
		log.Fatalf("cannot connect: %v", err)
	}

	tx, err := conn.Begin()
	if err != nil {
		log.Fatalf("cannot begin transaction")
	}

	_, err = tx.Exec(`DECLARE test CURSOR FOR
		     SELECT * FROM (VALUES (1), (2)) AS data (i)`)
	if err != nil {
		log.Fatalf("cannot create cursor: %v", err)
	}

	fetchRows(tx, 2)
	fetchRows(tx, 2)
}

func fetchRows(tx *pgx.Tx, n int) {
	rows, err := tx.Query(fmt.Sprintf("FETCH %d FROM test", n))
	if err == pgx.ErrNoRows {
		log.Printf("no available rows")
		return
	} else if err != nil {
		log.Fatalf("cannot fetch rows: %v", err)
	}

	dumpRows(rows)
}

func dumpRows(rows *pgx.Rows) {
	n := 0

	for rows.Next() {
		var i int
		if err := rows.Scan(&i); err != nil {
			log.Fatalf("cannot read row: %v", err)
		}

		log.Printf("row: %d", i)

		n++
	}

	log.Printf("read %d rows", n)
}
```

**Comment by jackc** [comment]
`Query` should never return `pgx.ErrNoRows`.

```go
// ErrNoRows occurs when rows are expected but none are returned.
var ErrNoRows = errors.New("no rows in result set")
```

The key thing is rows are not always expected from `Query`. An empty result set is perfectly valid. `QueryRow` expects a row so it will return an error on an empty result set. This behavior mimics `database/sql`.

It would be a significant breaking change for `Query` to return an error on an empty result set. I think that for cursors it will be necessary to manually read the result set and notice when there were no rows. If you use cursors frequently I imagine that a fairly simple wrapper could simplify this logic.

**Comment by galdor** [comment]
It makes sense :) Thank you !
