### ISSUE TITLE
Unix sockets in database uri

### ISSUE THREAD

**Issue by Mic92** [jackc/pgx#472]
I have a postgresql with a local unix socket:

https://github.com/jackc/pgx/blob/master/conn_test.go#L346

How can I pass unix sockets using ParseURI?
I have seen only tcp examples so far: https://github.com/jackc/pgx/blob/master/conn_test.go#L354

**Comment by Mic92** [comment]
fixed in https://github.com/jackc/pgx/pull/473

**Comment by justinclift** [comment]
@jackc This can be closed now. :smile:
