### ISSUE TITLE
Error codes helper function

### ISSUE THREAD

**Issue by MOZGIII** [jackc/pgx#474]
How about adding a helper function like this:

```go
func ErrorCode(err error) (string, bool) {
	pgerr, ok := err.(pgx.PgError)
	if !ok {
		return "", false
	}
	return pgerr.Code, true
}
```

The reason for this proposal it that I end up creating such helper function in most of my codebases, and it seems to be reasonable to just include it in the pgx package itself.

**Comment by jackc** [comment]
How is this generally used? Presumably the application still has to handle cases where it is not a PgError. Does this function shorten the normal error handling?

**Comment by MOZGIII** [comment]
Actually, the implementation can be a bit more concise:
```go
func ErrorCode(err error) string {
	pgerr, ok := err.(pgx.PgError)
	if !ok {
		return ""
	}
	return pgerr.Code
}
```

The bool is not really meaningful, as in the most used case in my code if often just check for code equality with some non-empty string. `ok` is not useful then.

**Comment by jackc** [comment]
Given your example, I think it's simpler to just use the type assertion directly.

```go
val, err := MyModelCall(ctx, arg1, arg2, etc) /* does pgx request internally */
if err != nil {
  if err, ok := err.(pgx.PgError); ok && err.Code == pgerr.UniqueViolation /* or just == "23505" */ {
    return ErrMeaningfulApplicationLayerError
  }
  return err /* any generic pg error that doen't need to be handled specially by the higher level code layer */
}

/* use val */
return nil
```

`pgx.PgError` is designed to be a direct translation of the PostgreSQL error data: https://www.postgresql.org/docs/10/protocol-error-fields.html. I don't think there is much risk of that changing such that a wrapper function is needed.

**Comment by MOZGIII** [comment]
Yeah, but the thing is `err, ok := err.(pgx.PgError); ok && err.Code == pgerr.UniqueViolation` is a lot of typing, and there's some logic to it that writer can make a mistake in.

Essentially, the thing I'm proposing is one step forward after putting `err, ok := err.(pgx.PgError); ok && err.Code == code` in a function.
I.e.:
```go
func IsErrCode(err error, code string) bool {
    pgerr, ok := err.(pgx.PgError)
    return ok && pgerr.Code == code
}
```

Again, the pattern I repetitively observe is this one `err, ok := err.(pgx.PgError); ok && err.Code == pgerr.UniqueViolation`, and after screwing up with it (yep, maybe it's just me, but the I sometimes do mistakes in the things even simple like this) I decided to do something with it, and that's how I extracted that function. One immediate benefit that I got was much less typing (with autocompletion it's really just a few keystrokes) - and that quickly became even more valuable that it prevents errors. I admit I'm lazy. :)

I don't think there's more to it, it's up to decide whether it worth adding or not. If you like it I'll create a PR.

**Comment by MOZGIII** [comment]
Btw, the pattern was inspired by the similar thing at grpc package: https://github.com/grpc/grpc-go/blob/d27440de3ff4bcac15a44957845d2b7c1042ad35/status/status.go#L181-L194

**Comment by jackc** [comment]
I think I still prefer the type assertion style, so I'm going to pass on this for now.

**Comment by mofirouz** [comment]
@jackc Sorry to pry open an old discussion - but as a side note where is the package that contains `pgerr.UniqueViolation` in your example above?

**Comment by jackc** [comment]
Check out https://github.com/jackc/pgerrcode/

**Comment by mrg0lden** [comment]
@jackc Is this still usable with v4? I'm trying to find a way to handle errors more properly, but I couldn't find `pgx.PgError` 😓

**Comment by jackc** [comment]
Yes. The pgerrcode library is still usable -- it is only contains constants so it is not tied to any particular library. As far as `pgx.PgError`, that type was moved to the `pgconn` underlying library in `v4.

**Comment by mrg0lden** [comment]
Is there a way to access it through the outer API (Query, Exec, QueryRow...)?

**Comment by jackc** [comment]
Those functions can return a `*pgconn.PgError`.

**Comment by mrg0lden** [comment]
Well, that's great! Thanks!

**Comment by pantuchy** [comment]
Hello Jackc.

I have spent few hours to make this code work with **PgError**:

```
tx, err := pool.Begin(context.Background())

	if err != nil {
		log.Printf("Failed to begin transaction: %v\n", err)
		return nil, grpc_status.Errorf(grpc_codes.FailedPrecondition, "Failed to begin transaction: %v", err)
	}

	defer tx.Rollback(context.Background())

	query1 := `
		INSERT INTO users (first_name, last_name, email, password, birthdate, status)
		VALUES ($1, $2, lower ($3), $4, $5, $6)
		RETURNING id
	`

	var id uint32

	err = tx.QueryRow(
		context.Background(),
		query1,
		req.GetFirstName(),
		req.GetLastName(),
		req.GetEmail(),
		string(passHash),
		req.GetBirthdate(),
		req.GetStatus().String(),
	).Scan(&id)

	if err != nil {
		if err, ok := err.(pgx.PgError); ok && err.Code == pgerrcode.UniqueViolation {
			// Handle error
		}

		return err
	}
```

But it does not work. Error not parsing to **PgError**. I am using connection pool: **pgxpool.Pool**
May be there might be a problem? As far as I understood, PgError works great with **pgconn** but not with pooling.

Could You please confirm that?
Thank you.

**Comment by jackc** [comment]
1. The error is `*PgError` not `PgError`.
2. Use error unwrapping rather than a direct type assertion.

See https://github.com/jackc/pgx/wiki/Error-Handling

**Comment by pantuchy** [comment]
> 1. The error is `*PgError` not `PgError`.
> 2. Use error unwrapping rather than a direct type assertion.
> 
> See https://github.com/jackc/pgx/wiki/Error-Handling

Thank you 🙏 That helps me a lot!

**Comment by themsay** [comment]
>     1. The error is `*PgError` not `PgError`.
> 
>     2. Use error unwrapping rather than a direct type assertion.
> 
> 
> See https://github.com/jackc/pgx/wiki/Error-Handling

@jackc any idea how to use below pgx native error handling in pgx using database/sql?
```
var pgErr *pgconn.PgError
if errors.As(err, &pgErr) {
}
```

Thanks for your time!

**Comment by jackc** [comment]
> @jackc any idea how to use below pgx native error handling in pgx using database/sql?

It should work the same.

**Comment by themsay** [comment]
> > @jackc any idea how to use below pgx native error handling in pgx using database/sql?
> 
> It should work the same.

@jackc using pgx with database/sql in an error handling doesn't work with ```pgconn.PgError```.

In an even ```if err != nil``` is true

solution 1: failed
```
var pgErr *pgconn.PgError
if errors.As(err, &pgErr) {
    switch pgErr.Code {
            pgercode.NoData:   // I want something like this
               //
    }
}
```
Solution 2: basic go interface passed 
```
switch err {
   sql.ErrNoRows:
     //
}
```

But, I want use solution 1 with pgx with database/sql.

Please, any documentation will be super helpful. Thanks in advance!

**Comment by jackc** [comment]
It works for me with `database/sql`.

```go
package main

import (
	"database/sql"
	"errors"
	"log"
	"os"

	"github.com/jackc/pgconn"
	"github.com/jackc/pgerrcode"
	_ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
	db, err := sql.Open("pgx", os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatalln(err)
	}
	defer db.Close()

	var n int
	err = db.QueryRow("select 1/0").Scan(&n)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) {
			switch pgErr.Code {
			case pgerrcode.DivisionByZero:
				log.Println("correctly matched division by zero error")
				os.Exit(0)
			}
		}
	}
	log.Fatalln("did not match error", err)
}
```

Output:

```
jack@glados ~/dev/pgx_issues/pgx-474 ±master⚡ » go run main.go
2020/07/13 07:43:08 correctly matched division by zero error
```

**Comment by themsay** [comment]
@jackc fellowing your example code.

I'm still can't get it to work using database/sql with error code `pgercode.NoData` and did not try other error code.

```go
package main

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgconn"
	"github.com/jackc/pgerrcode"
	"github.com/jackc/pgx/v4"
	"github.com/jackc/pgx/v4/stdlib"
	_ "github.com/jackc/pgx/v4/stdlib"
)

var db *sql.DB

type config struct {
	PostgresName     string
	PostgresHost     string
	PostgresPort     int
	PostgresUser     string
	PostgresPassword string
	PostgresTLSMode  string
}

func initDB(ctx context.Context) (func(), error) {
	var err error
	cfg := config{
		PostgresName:     "mydb",
		PostgresHost:     "127.0.0.1",
		PostgresPort:     5432,
		PostgresUser:     "appuser",
		PostgresPassword: "development",
		PostgresTLSMode:  "disable",
	}
	db, err = postgres(ctx, cfg)
	if err != nil {
		log.Fatalln(err)
		os.Exit(0)
	}

	return func() { defer db.Close() }
}

func postgres(ctx context.Context, cfg config) (*sql.DB, error) {
	config, _ := pgx.ParseConfig("")
	config.Database = cfg.PostgresName
	config.Host = cfg.PostgresHost
	config.Port = uint16(cfg.PostgresPort)
	config.User = cfg.PostgresUser
	config.Password = cfg.PostgresPassword

	if cfg.PostgresTLSMode != "disable" {
		//config.TLSConfig = *tls.Config // // TODO: implementation of TLS
	}
	// Logger
	config.LogLevel = pgx.LogLevelDebug
	//config.Logger = zapadapter.NewLogger()   // TODO: implementation of logger

	db := stdlib.OpenDB(*config)

	// Verify that we can communicate and authenticate
	// with the Postgres and ping connection is alive.
	c, err := db.Conn(ctx)
	if err != nil {
		return nil, fmt.Errorf("postgres: database connection failed->: %v", err)
	}
	defer c.Close()

	if err := c.PingContext(ctx); err != nil {
		return nil, fmt.Errorf("postgres: connection ping failed->: %v", err)
	}
	return db, nil
}

func main() {
	ctx := context.Background()

	stop := initDB(ctx) // Initialize database
	defer stop()

	c, err := db.Conn(ctx)
	if err != nil {
		log.Println("postgres connect failed error")
		os.Exit(0)
	}

	// Test pgx pgconn.PgError code by first create a table 'test'
	_, err = c.ExecContext(ctx, "create table mytable(id int);")
	if err != nil {
		log.Println("table test insert failed error")
		os.Exit(0)
	}
	defer func() {
		// clean-up delete test table and close connection
		_, err = c.ExecContext(ctx, "drop table mytable;")
		if err != nil {
			log.Println(err)
		}
		c.Close()
	}()

	var n int
	//err = c.QueryRowContext(ctx, "select 1/0").Scan(&n)
	err = c.QueryRowContext(ctx, "select id from mytable").Scan(&n)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) {
			switch pgErr.Code {
			// case pgerrcode.DivisionByZero:
			// 	log.Println("correctly matched division by zero error")
			// 	os.Exit(0)

			case pgerrcode.NoData:
				log.Println("correctly matched no data error")
				os.Exit(0)
			}
		}
	}
	log.Println("did not match error")

	if err == sql.ErrNoRows {
		log.Println("but did match database/sql sql.ErrNoRows error->:", err)
	}
}
```

Output:

```
[develop]user@dev:staffservice$ go run main.go
2020/07/13 16:36:27 did not match error
2020/07/13 16:36:27 but did match database/sql sql.ErrNoRows error->: sql: no rows in result set
```

I think I'm using the wrong error code or something else?

**Comment by jackc** [comment]
PostgreSQL doesn't return an error for no rows found. It is `database/sql` returning `sql.ErrNoRows` from `QueryRow`.

**Comment by themsay** [comment]
> PostgreSQL doesn't return an error for no rows found. It is `database/sql` returning `sql.ErrNoRows` from `QueryRow`.

If I understand you correctly, you mean all `QueryRow` errors in database/sql are different from internal PostgreSQL or just 'no rows found' error only? Any idea of error code match for `pgerrcode.NoData`.

Super helpful tips thanks!

**Comment by jackc** [comment]
Any error reported by PostgreSQL will be returned. So you can totally get PostgreSQL errors from `QueryRow`.

But `sql.ErrNoRows` is distinctly a `database/sql` concept. As far as PostgreSQL is concerned a query returning zero rows is not an error. 

`pgerrcode.NoData` exists because it is listed on https://www.postgresql.org/docs/current/errcodes-appendix.html. But as far as I can tell from a quick look at the PostgreSQL source code it is never actually used.

**Comment by themsay** [comment]
> Any error reported by PostgreSQL will be returned. So you can totally get PostgreSQL errors from `QueryRow`.
> 
> But `sql.ErrNoRows` is distinctly a `database/sql` concept. As far as PostgreSQL is concerned a query returning zero rows is not an error.
> 
> `pgerrcode.NoData` exists because it is listed on https://www.postgresql.org/docs/current/errcodes-appendix.html. But as far as I can tell from a quick look at the PostgreSQL source code it is never actually used.

You nailed it for me. Thank you so much!

**Comment by austincollinpena** [comment]
Coming on this thread was a life saver. Thanks Jack for all your hard work!

**Comment by openwhalereef** [comment]
how could one get hold of pgError when using pgxpool.Pool exec? That seems to return only an error string message -- https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool#Conn.Exec ?

**Comment by jackc** [comment]
> how could one get hold of pgError when using pgxpool exec? That seems to return only an error string message

Not sure what you mean. `Exec` returns a `(pgconn.CommandTag, error)` not a string and the error can be unwrapped to a `*pgconn.PgError` if that's what the underlying error is.

**Comment by NOPR9D** [comment]
> @jackc how could one get hold of pgError when using pgxpool exec? That seems to return only an error string message -- https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool#Conn.Exec ?
> 
> Exec returns a string. Wrapping doesn't seem to work either.
> 
> ```
> if err != nil {
> 		var pgErr *pgconn.PgError
> 		if errors.As(err, &pgErr) {
> 			fmt.Println(pgErr.Message) // => syntax error at end of input
> 			fmt.Println(pgErr.Code)    // => 42601
> 		}
>      }
> ```

Same issue here

With this go.mod part:

```
	github.com/jackc/pgerrcode v0.0.0-20220416144525-469b46aa5efa // To try wih case pgerrcode.InvalidTextRepresentation
	github.com/jackc/pgtype v1.8.1 
	github.com/jackc/pgx/v4 v4.13.0 // Used to query sql
	github.com/jackc/pgx/v5 v5.4.1   // cause the doc say to use v5 for "github.com/jackc/pgx/v5/pgconn" import with var pgErr *pgconn.PgError
```

**Comment by zsbahtiar** [comment]
i try with this, and solve
```go
import (
"github.com/jackc/pgx/v5/pgconn"
)
 if data, ok := err.(*pgconn.PgError); ok && data.Code == "23505" {
            switch data.ConstraintName {
            }
 }
```
