### ISSUE TITLE
Scan/Values one row multiple times

### ISSUE THREAD

**Issue by mvrhov** [jackc/pgx#478]
I'd like to reuse some structs in multiple queries, but making all fields pointers or null is out of the question.
So I thought I'd call rows.Values first, check if the 2nd item in slice is not nil and then call Scan on the same. row, 
This seems to fail with panic nil pointer dereference as it seems that "stream" Scan/Values read from is one way.

**Comment by jackc** [comment]
`rows.Scan` and `rows.Values()` consume the underlying data as they read it. There isn't presently any way to rewind / reread values.

**Comment by jackc** [comment]
Yeah, it'd probably be a good idea to have a more meaningful error. Though a panic with a meaningful error message might be even better. In the current version of pgx it is always a bug to read the same row twice so nothing meaningful could be done with a normal error.

I'm not really sure if there is a better way to handle your use case. Perhaps if you had a single wide struct (or loose values) in your Next/Scan loop and inspected that to decide what other structs are needed. Something roughly like:

```go
for rows.Next() {
  var a, b, c, d, e, f pgtype.Int4 // etc
  err := rows.Scan(&a, &b, &c, &d, &e, &f)
  // error handling omitted

  if b == something {
    // create some struct
  } else if c == somethingelse {
    // create some other struct
  }
}
```

But maybe I'm not understanding what you are trying to do...

**Comment by mvrhov** [comment]
That's the way I solved it at the end. But would prefer a way without defining a ton of temp variables.

**Comment by jackc** [comment]
This is supported in `v4`.
