### ISSUE TITLE
Access to `pgxDriver` in `stdlib` package to use datadog tracing 

### ISSUE THREAD

**Issue by platelk** [jackc/pgx#481]
Hi !

On our project we came with a little issue with the use of `gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql` with `pgx`, this package require to "wrap" a `sql.Driver` like this

```go
import sqltrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql"

// ...

sqltrace.Register(
		"pgutils-trace",
		driver,
		sqltrace.WithServiceName(conf.Database),
	)

// ...
```
But as far as I look in the `stdlib` package of `pgx` I can't see a way of accessing to `pgxDriver` or to instantiate "nicely" a new Driver without trying to instantiate private struct member.

Is there is a way of doing this ? or should I add a new function to retrieve this driver ?

**Comment by jackc** [comment]
There isn't a way to do this now. Changing pgx this var in some way is one solution. But as of Go 1.10 I believe there is a better solution available. Go 1.10 added the [OpenDB](https://golang.org/pkg/database/sql/#OpenDB) function. This allows constructing `*sql.DB` directly without using `sql.Register` and `sql.Open`.

I think the DataDog extension could be implemented in terms of OpenDB and not require the underlying driver object to be exposed.

**Comment by jackc** [comment]
I haven't used the datadog extension, but looking at it a little closer it looks like it just needs a database/sql/driver.Driver. Can you just create a new one?

```
driver := stdlib.Driver{}
```

A don't think it needs any initialization in this case.

**Comment by ahajimir** [comment]
@platelk Were experiencing something similar with our projects. What approach did you end up taking? And how did it work out?

Cheers

**Comment by rakshans1** [comment]
@platelk How to integrate with ddtrace? can you provide a code sample
