### ISSUE TITLE
stdlib and COPY

### ISSUE THREAD

**Issue by GLeBaTi** [jackc/pgx#485]
Hello. Does this library support COPY instruction?

By "database/sql" i do this:

> tx.Prepare(`COPY "Table1" ("Col1", "Col2", "Col3", "Col4", "Col5") FROM STDIN;`)
> tx.Exec(1,2,3,4,5)

And get this:

> sql: expected 0 arguments, got 5

**Comment by jackc** [comment]
Copy is only supported through the native interface. You can use AcquireConn and ReleaseConn to get a *pgx.Conn from the database/sql pool.

**Comment by GLeBaTi** [comment]
Thanks

**Comment by bobowuji** [comment]
V1.3.3 has the same problem when using “INSERT INTO ON DUPLICATE KEY UPDATE”

**Comment by rianrais** [comment]
> Copy is only supported through the native interface. You can use AcquireConn and ReleaseConn to get a *pgx.Conn from the database/sql pool.

Sorry I'm still relatively new to Golang, I still don't understand what we should do in this then to achieve what the original poster wants. Any help would be appreciated, thank you.
