### ISSUE TITLE
Query sanitizer in internal package

### ISSUE THREAD

**Issue by BlueMagma2** [jackc/pgx#489]
The sql query sanitizer is inside an internal package : pgx/internal/sanitize

It would be very useful to be able to access these methods as they provide a mean to validate a query generator in tests

For example, I would like to be able to do this:

```
func Test_QueryMaker(t *testing.T) {
	var obj MyObj
	query, args, err := obj.MakeInsertQuery()
	_, err = sanitize.SanitizeSQL(query, args...)
	if err != nil {
		t.Errorf("MakeInsertQuery didn't return a valid sql query: %v, %v", query, args)
	}
}
```

**Comment by jackc** [comment]
Well, I'm not totally opposed to making it public but I'm not sure if it actually would do what you want _and_ there is a good reason for pgx that it is private.

`SanitizeSQL` doesn't validate the query is valid SQL. It uses a **very** simple parser to separate `$1`, `$2`, etc. from the regular text then escape and interpolate the query arguments. There are only a few error cases it will detect such as the query text including more `$` placeholders than arguments were passed to the function.

But the big reason for pgx to keep it private is it is only safe to use when the PostgreSQL connection is configured appropriately: `standard_conforming_strings = on` and `client_encoding = UTF8`. If those preconditions are not met then the function is not safe. pgx ensures theses preconditions are met. But if the function was public, it could expose unsuspecting users to a security vulnerability.
