### ISSUE TITLE
how do I write JSONB[] using the stdlib adapter?

### ISSUE THREAD

**Issue by dwalker-va** [jackc/pgx#490]
I'm using the stdlib adapter.

How am I supposed to insert JSONB[]?
I tried serializing it myself, but while I was able to insert that output from the postgres instance, I got an error while inserting that same value from golang/pgx (`Array value must start with \"{\" or dimension information.`). I imagine this might be a double quoting issue because the value I logged was the value I passed to the sql driver, not necessarily what went over the wire after the sql driver took over.
My next thought was to try to pass a slice of map[string]interface, because if the library is doing the marshalling, then map[string]interface is probably what it wants for JSON. That didn't work because `converting argument $2 type: unsupported type []interface {}, a slice of interface`.

For postgres beginners like myself there are not a lot of hints in this repo so I'm just looking for guidance here - it feels like I'm missing something obvious.

A note about my use case: This is for replicating data, and as such the shape of the data is dynamic, so it is not desirable for me to define json-tagged structs like most of the examples use. Using the standard driver was ideal because the same program also replicates data to mysql, and so a minor amount of code reuse is possible if I can continue using the standard driver for the postgres implementation.

**Comment by jackc** [comment]
Off the top of my head I would try to serialize the data to JSON in a `[]byte` (or possibly `string`) and send that. IIRC, at least `[]byte` should be passed unmodified.

**Comment by codenoid** [comment]
how

**Comment by laskoviymishka** [comment]
It's not implemented yet

**Comment by lzap** [comment]
This works fine for us, we are on pgx/v4 through stdlib. As @jackc mentioned, you have to serialize into JSON first. Another reason why we would like to rewrite our DAO to pgx/scanny:

```go
type AWSReservation struct {
	Reservation

	// Pubkey ID.
	PubkeyID int64 `db:"pubkey_id" json:"pubkey_id"`

	// Source ID.
	SourceID string `db:"source_id" json:"source_id"`

	// The ID of the aws reservation which was created.
	AWSReservationID string `db:"aws_reservation_id" json:"aws_reservation_id"`

	// The ID of the image from which the instance is created. AMI's must be prefixed with 'ami-'.
	ImageID string `db:"image_id" json:"image_id"`

	// Detail information is stored as JSON in DB
	Detail *AWSDetail `db:"detail" json:"detail"`
}

type AWSDetail struct {
	Region string `json:"region"`

	// Optional instance name
	Name *string `json:"name"`

	// AWS Instance type.
	InstanceType string `json:"instance_type"`

	// Amount of instances to provision of type: Instance type.
	Amount int32 `json:"amount"`

	// Immediately power off the system after initialization
	PowerOff bool `json:"poweroff"`
}

// TODO: Use pgx native driver with scany library instead of sqlx
func (detail *AWSDetail) Value() (driver.Value, error) {
	result, err := json.Marshal(detail)
	if err != nil {
		return nil, fmt.Errorf("unable to unmarshal reservation detail: %w", err)
	}
	return result, nil
}

// TODO: Use pgx native driver with scany library instead of sqlx
var ReservationDetailScanTypeErr = errors.New("type assertion to []byte failed")

func (detail *AWSDetail) Scan(value interface{}) error {
	b, ok := value.([]byte)
	if !ok {
		return ReservationDetailScanTypeErr
	}

	err := json.Unmarshal(b, &detail)
	if err != nil {
		return fmt.Errorf("unable to marshal reservation detail: %w", err)
	}
	return nil
}
```

**Comment by bfontaine** [comment]
This issue has been opened for more than 4 years; is it still relevant today?
