### ISSUE TITLE
[Question] connection pool MIN size?

### ISSUE THREAD

**Issue by hellower** [jackc/pgx#492]
Thank you for  great library.

connection_pool_minsize (not max)

Could you add this option?

I'm not considering pgbouncer.

sorry  for poor english.

**Comment by jackc** [comment]
At the moment, the connection pool is probably the weakest part of the library. Min pool size is something that would make sense to add in the future when the connection pool gets rewritten. But I don't think it would make any difference now because the pool never automatically closes idle connections.

**Comment by hellower** [comment]
Ok. Thanks!

**Comment by hellower** [comment]
not implemented in v4?

**Comment by jackc** [comment]
It could be added to the new `pgxpool` fairly cleanly -- just no one has done it yet.

**Comment by ellulpatrick** [comment]
Hi @jackc  . I was thinking of adding this functionality.
My plan was to have the HealthChecker check current size against desired minimum and then create a new connection for the gap.
However, I can't see a way to force puddle to create a new resource as opposed to returning an existing idle one. How do you recommend minConns could be achieved?
Thanks for your time.

**Comment by jackc** [comment]
To force creation of a new resource you need to call `Acquire` when the pool is empty. A simple approach would be to loop over calling `Acquire` until the pool stats indicated the proper number of connections -- then be sure to release them all of course.

**Comment by ellulpatrick** [comment]
Thanks @jackc. A little convoluted and not optimal but would certainly do the trick. You would consider an AcquireNew() on puddle that would force the new resource creation?

**Comment by jackc** [comment]
A function to force the creation of a new resource would be fine. Not sure about calling it `AcquireNew()` though. I'm assuming users of this function would not actually want to acquire it -- they simply want to to be created -- Maybe a signature like:

 `func (p *Pool) CreateResource(ctx context.Context) (error)`

**Comment by ellulpatrick** [comment]
Yes that sounds good. I'll have a crack at a PR.
Thanks again.

**Comment by Hello71** [comment]
seems this should be closed by #674?

**Comment by jackc** [comment]
I think your right.
