### ISSUE TITLE
PrepareEx with same name, different text yields Postgres error

### ISSUE THREAD

**Issue by johngibb** [jackc/pgx#496]
To reproduce, prepare two different queries using the same name:

```go
var conn *pgx.Conn // acquire somehow
_, err = conn.PrepareEx(ctx, "MyQuery", "select 1;", nil)
assert.Must(t, err)
_, err = conn.PrepareEx(ctx, "MyQuery", "select 2;", nil)
assert.Must(t, err)
```

In the second assertion, the following error is returned:
```
ERROR: prepared statement "MyQuery" already exists (SQLSTATE 42P05)
```

I realize that this is completely an erroneous use case. However, I noticed that _some_ care is taken to handle the situation: https://github.com/jackc/pgx/blob/4618730e71353189c1ae1632cb7d166613a882eb/conn.go#L1070

As it's not exactly obvious from the error message what's going on (since `PrepareEx` claims to be idempotent), I think it'd be nice to provide the user with a more clear error in that case, e.g.

> pgx: attempt to redefine prepared statement with different sql

If you prefer that, I'd be happy to submit a PR with this behavioral change!

**Comment by jackc** [comment]
> If you prefer that, I'd be happy to submit a PR with this behavioral change!

Sounds good! Please do.

**Comment by bfontaine** [comment]
Was a PR eventually submitted or should this issue stay open?

**Comment by bfontaine** [comment]
I’m closing this since nobody seems to be actively working on it.
