### ISSUE TITLE
may I get Rows's values [][]byte?

### ISSUE THREAD

**Issue by zgr126** [jackc/pgx#497]
I'm try to write myself scan, so I wan't to get raw [][]btye from postgresql in one row, how can I do it?

**Comment by jackc** [comment]
It might be a bit awkward but you can Scan each field into a []byte to get the raw data and go from there.

Or if you don't mind living on the bleeding edge, check out `v4-dev` branch and look at the `pgconn` subdirectory. The plan is for v4 of pgx to be built on that new package -- and it implements exactly the interface you want.

**Comment by zgr126** [comment]
ok,I get,3q
