### ISSUE TITLE
can $1 be inserted by a table name?

### ISSUE THREAD

**Issue by eruca** [jackc/pgx#498]
```go
ct, err := pool.Exec("delete from $1 where id = 1", tabler.TableName())
```

I always get the error: syntax error at or near "$1" (SQLSTATE 42601)

**Comment by jackc** [comment]
No, PostgreSQL bind variables must be values not identifiers. However, you could use [pgx.Identifier.Sanitize](https://godoc.org/github.com/jackc/pgx#Identifier.Sanitize) to safely interpolate into a SQL string.
