### ISSUE TITLE
Is it possible to configure underlying ChunkReader with custom MinBufLen?

### ISSUE THREAD

**Issue by furdarius** [jackc/pgx#502]
As I can see, it's not possible to use `NewFrontend` with custom `ChunkReader` https://github.com/jackc/pgx/blob/f4396b2e23b1e53a3047c86eb025b682344eaa56/conn.go#L331

And beside that, it's even not possible to use custom `Frontend` in `Conn.connect`.

If you find it useful to give the ability to configure `ChunkReader`, I can create patch.

Maybe I'm missing something and it's possible to configure `MinBufLen` for `ChunkReader`?

**Comment by furdarius** [comment]
Okey, got it. I'll try to collect metrics some metrics which this setting may affect.
Prepared a fork for experimentation: #508

**Comment by jackc** [comment]
This is doable through the pgconn connection now.
