### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by philtay** [jackc/pgx#505]
Could you please add `go.mod` and `go.sum` files in the repository root?
Worth reading in this case: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

Thanks!

**Comment by jackc** [comment]
I've just tagged the first v4 prerelease with support for Go modules.

**Comment by mrg0lden** [comment]
@jackc will you update the module name so it doesn't have the /v4 anymore? or will you keep it as is?

**Comment by jackc** [comment]
It will remain `github.com/jackc/pgx/v4`. The latest non Go module version (`v3`) will remain available at `github.com/jackc/pgx`. `v4` is a breaking change so it needs to be a separate import path.
