### ISSUE TITLE
opentracing/tracing?

### ISSUE THREAD

**Issue by k1ng440** [jackc/pgx#507]
Hello,
I can't figure out how to do tracing. the conn.OnNotice is might be good for logging but it cant be used with tracers because it does not give you the context.

thanks

**Comment by k1ng440** [comment]
i understand. 

I have not got a chance to play with this library because I need tracing support and I am using the stdlib.

does the logger interface give you the context?

**Comment by jackc** [comment]
No, but you can set the logger per request and your custom logger could contain the context. Somewhat awkward, but possible anyway.

Adding context to logger would be a good change, but unfortunately it would be a breaking change. Might be good for v4.

**Comment by k1ng440** [comment]
it does not have to be a breaking change. you can add context to data map[string]interface{} so we can retrieve it like data["context"].(context.Context)

**Comment by jackc** [comment]
The recently released `v4` `Logger` interface now includes a `context.Context`.
