### ISSUE TITLE
Replication Example ?

### ISSUE THREAD

**Issue by deletexl** [jackc/pgx#510]
Hello there. Is a complete sample available for replication? I want to send select queries to a database, write queries to a database.

**Comment by jackc** [comment]
Sorry, the only examples are the tests.

**Comment by k1ng440** [comment]
@jackc how to achieve this?


writes -> master
reads -> replicas

**Comment by jackc** [comment]
@k1ng440 pgx doesn't have built in support that and probably never can. It has no way of knowing if a given query is a write or not (even if it parsed the query string -- a `select` can cause a write).

You would need to establish different pools for the master and replicas and determine which pool to issue the command to at a higher level than pgx.

**Comment by k1ng440** [comment]
@jackc thanks for your response. i have solved the issue with a simple wrapper which provides

Master() - master
Slave() - random slave
Random() - master slave random

with this i have much freedom
