### ISSUE TITLE
Cannot connect to pgbouncer in 3.2.0 and later

### ISSUE THREAD

**Issue by danielnelson** [jackc/pgx#512]
After upgrading to v3.2.0 it is no longer possible to connect to pgbouncer, sql.Open returns:
```
ERROR: unsupported pkt type: 80 (SQLSTATE 08P01)
```

Here is a link to the configuration and open calls:
https://github.com/influxdata/telegraf/blob/03776088f135b040d8af93db4ee09f8bba1a5de7/plugins/inputs/postgresql/service.go#L112-L136

Git bisect indicates that it is caused by d9f21d02a5bcf904c2cd59d81c8645645f18b92a overwriting the `PreferSimpleProtocol` in the `pgx.ConnConfig`.

**Comment by jackc** [comment]
I think this should be fixed on master now.

**Comment by danielnelson** [comment]
Thanks, I can verify that it is working for me now.

**Comment by danielnelson** [comment]
@jackc Apologies if this is documented somewhere, but do you have a date in mind for the next release?  I'm trying to decide if I should wait for the next release or just pin to a commit sha on the next Telegraf release (scheduled for the end of May).

**Comment by jackc** [comment]
Just tagged v3.4.0.
