### ISSUE TITLE
Inconsistent log level in connection configuration

### ISSUE THREAD

**Issue by devcrust** [jackc/pgx#516]
The log level within the connection configuration is of type int but the logger interface itself is using the more consistent LogLevel type. In my opinion, both should use the LogLevel type.

**Comment by jackc** [comment]
I agree. It's technically a change of the public interface, but it seems extremely unlikely that it would cause any problems to change (and the problems would be trivial to fix). And the mismatch could be considered a bug of sorts, so I decided to push this change to the current major version.
