### ISSUE TITLE
"invalid input syntax for integer (SQLSTATE 22P02)" error with pgtype.NumericArray

### ISSUE THREAD

**Issue by dpifke** [jackc/pgx#519]
`pgtype.NumericArray.Value()` seems to produce strings like `'{1e0,2e0,3e0}'`, which my version of PostgreSQL (10.6-0ubuntu0.18.04.1) doesn't accept:

```
lsb=> create temporary table numbers (numbers bigint[]);
CREATE TABLE
lsb=> insert into numbers values ('{1e0,2e0,3e0}');
ERROR:  invalid input syntax for integer: "1e0"
LINE 1: insert into numbers values ('{1e0,2e0,3e0}');
                                    ^
```

Dropping the exponent part seems to work:

```
lsb=> insert into numbers values ('{1,2,3}');
INSERT 0 1
```

**Comment by jackc** [comment]
The Go type `pgtype.NumericArray` maps to the Postgresql type `numeric[]`. Exponent format is an accepted format for that.

```
pgx-519=# select '{1e0, 2e0, 3e0}'::numeric[];
 numeric 
─────────
 {1,2,3}
(1 row)
```

Since you are trying to write to PostgreSQL type `bigint[]` I would recommend using Go type `pgtype.Int8Array` instead.

**Comment by sanyamsinghal** [comment]
hey, @jackc i have been to use **CopyFrom()** for many formats(csv, space-separated etc) except for a case when columns are tab-separated in a row.
I couldn't figure out the reason it is giving this error:
`panic: ERROR: invalid input syntax for integer: "1   name1" (SQLSTATE 22P02)`

code is like
```
conn.PgConn().CopyFrom(ctx, freader, fmt.Sprintf(`COPY employees from STDIN  with DELIMITER E'\t'`))
```

can you please help me with how can I do it for TSV(tab-separated values)

**Comment by jackc** [comment]
I suspect there is something corrupt in the file. I would try it with `psql` to confirm. You also might get more details from the error message by extracting the `*pgconn.PgError`. Sometimes there is additional information.
