### ISSUE TITLE
context.Context not supported when opening connection via database/sql

### ISSUE THREAD

**Issue by sidh** [jackc/pgx#524]
When using pgx via database/sql, context is ignored when opening new connection - code [here](https://github.com/jackc/pgx/blob/master/stdlib/opendb.go#L50).

This is because net.Dial is used instead of net.DialContext [here](https://github.com/jackc/pgx/blob/master/conn.go#L62) and [here](https://github.com/jackc/pgx/blob/master/conn.go#L295).

Timeout can be set via custom DialFunc with custom driver config but it is very inconvenient because you cannot set it per call to database/sql and generally unable to use context facility for timeout and cancellation.

**Comment by jackc** [comment]
Unfortunately, that interface predates context being introduced into Go. I plan on updating it in the next major release.

**Comment by timbunce** [comment]
Any estimate, even a rough one, for when the next major release might be? (E.g. weeks or months?)

**Comment by jackc** [comment]
I hope to have a more or less feature complete and working v4 pre-release in a month or two. But given that there are significant internal changes and some substantial interface changes I'd like to have a lengthy test period to squash any bugs and especially to ensure that the public interfaces are correct. I'd allow another month or two from initial pre-release to final v4.0.0 release.

**Comment by jackc** [comment]
This is implemented in v4 (currently prerelease).
