### ISSUE TITLE
Cannot encode []string in simple protocol

### ISSUE THREAD

**Issue by Luummii** [jackc/pgx#534]
When insert a record string array

       config, err := pgx.ParseURI(os.Getenv("DATABASE_URL"))
       if err != nil {
           log.Fatal(err)
       }
       db, err := pgx.Connect(config)
       if err != nil {
	      log.Fatal(err)
       }
       defer conn.Close()
       strArr:= []string{"asd", "asd", "asd", "asd"}
       insertData:= "INSERT INTO site (id, styles) VALUES ($1, $2)"
       _, err := db.Exec(insertData, id, strArr)
       if err != nil {
	     log.Panic(err)
       }

I get error: 
Cannot encode []string in simple protocol - []string must implement driver.Valuer, pgtype.TextEncoder, or be a native type

Explain how to fix it! Or an example of working with arrays.

**Comment by jackc** [comment]
Is there something else going on with the connection? Because the simple protocol should never be used unless you specifically request it.

And it works for me...

```go
package main

import (
	"log"
	"os"

	"github.com/jackc/pgx"
)

func main() {
	config, err := pgx.ParseURI(os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}
	db, err := pgx.Connect(config)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	_, err = db.Exec("create temporary table site(id serial primary key, styles text[])")
	if err != nil {
		log.Panic(err)
	}

	strArr := []string{"asd", "asd", "asd", "asd"}
	insertData := "INSERT INTO site (styles) VALUES ($1)"
	_, err = db.Exec(insertData, strArr)
	if err != nil {
		log.Panic(err)
	}

	rows, err := db.Query("select * from site")
	if err != nil {
		log.Panic(err)
	}

	for rows.Next() {
		var id int32
		var ary []string
		err = rows.Scan(&id, &ary)
		if err != nil {
			log.Panic(err)
		}

		log.Println(id, ary)
	}
}
```

Output:

```
jack@happy:~/go/src/github.com/jackc/pgx-534$ go run main.go 
2019/05/17 13:38:18 1 [asd asd asd asd]
```

**Comment by Luummii** [comment]
It's simple. In the far distant part of the code there is this - config.PreferSimpleProtocol = true

**Comment by rskumar** [comment]
But how to get it working in case of `PreferSimpleProtocol=true`, as I need to use PGBouncer and that will not work with binary wire proto.

**Comment by jackc** [comment]
@rskumar Advanced types are somewhat limited in the simple protocol because pgx doesn't know what the PostgreSQL type is. In the `[]string` case there are at least 2 different text formats (`text[]` and `varchar[]` vs `json` and `jsonb`). You will need to use `pgtype.TextArray` of `pgtype.JSON` instead of `[]string` to tell pgx how to encode the value.

> I need to use PGBouncer and that will not work with binary wire proto.

This is true for how pgx uses it now. But as far as I know it is possible with a careful use of the unnamed prepared statement and the sync message. I'm hoping to pgx can support this in the future.
