### ISSUE TITLE
Listen / notify interface

### ISSUE THREAD

**Issue by jackc** [jackc/pgx#553]
Determine if listen / notify should have a pgx wrapper or if the preferred usage will be through pgconn.

**Comment by tsingson** [comment]
this v3 notify working good, v4 should keep it and enhance for more thread-safe.

**Comment by jackc** [comment]
Can you expand on what you mean by more thread safe?

**Comment by AlexanderEkdahl** [comment]
Unless I am mistaken there is no thread-safe way to subscribe to a channel using a connection acquired from a pool? With the new `v4` API I would have to access the `pgconn` and set the `OnNotification` callback?

**Comment by jackc** [comment]
> Unless I am mistaken there is no thread-safe way to subscribe to a channel using a connection acquired from a pool?

Regardless of whether it is thread-safe to subscribe to a channel from a pool it is not a good idea. The connection might be closed for some reason and you would have no way of knowing. If an application is using multiple connections one should be dedicated to listen to notifications. The only place it makes sense to execute queries and listen for notifications concurrently is when the application is only using a single connection.

> With the new v4 API I would have to access the pgconn and set the OnNotification callback?

That's the question this issue is trying to decide. Does it make the most sense to reach down to the lower `pgconn` level or should the `v3` interface be carried forward (it should be simple to implement in terms of `pgconn` for `v4`) or is there maybe a different interface then either of those two that would be easier to use.

**Comment by AlexanderEkdahl** [comment]
@jackc Thank you for taking your time to respond and developing this excellent library!

> Regardless of whether it is thread-safe to subscribe to a channel from a pool it is not a good idea. The connection might be closed for some reason and you would have no way of knowing.

Is this true even if I use `conn, _ := pool.Acquire(...)` and `conn.Release()` when I am done listening? Is your suggestion to separate the queries+notification using a pool with a dedicated connection for `LISTEN`? I understand that listening will consume a connection so it is not scalable to hundreds of listeners.

**Comment by jackc** [comment]
It is fine to use a checked out query for listening and to release it when done. What I mean is it would not be safe to checkout a connection, start listening, release it to the pool and still expect to receive notifications.

**Comment by jackc** [comment]
I have implemented listen / notify in `v4` with the same interface as `v3`. It can be overridden by setting the `pgconn.OnNotification` callback, but out of the box it should behave the same as `v3`.

**Comment by Braeder** [comment]
I just walked into the problem. Is there an example I can see to solve this exact same issue?
