### ISSUE TITLE
concurrent r/w on pgx.ReplicationConn

### ISSUE THREAD

**Issue by kingluo** [jackc/pgx#557]
Does it safe to do concurrent r/w on `pgx.ReplicationConn` or `pgx.Conn`?

For example,  `WaitForReplicationMessage()` and `SendStandbyStatus()` at the same time. 

The doc said it's unsafe, but I check the codes, it seems ok. Could you clarify it more?

**Comment by jackc** [comment]
To be honest, I don't know. The replication support was a contributed feature. My input on it has only been reviewing how it fits into pgx as a whole. That said, if it is specifically documented as unsafe it probably was for a reason...

I plan on taking a hard look at the replication support sometime before v4 is released, but I can't promise any time frame on that.

**Comment by jackc** [comment]
Logical replication has been extracted into the package https://github.com/jackc/pglogrepl. I can now answer the question regarding concurrent r/w.

In the *specific* case you gave, doing the analog in pglogrepl would be safe (and presumably is also safe in `v3`). However, I wouldn't recommend it. It would be clearer use a loop and a context timeout to alternate between listening to replication messages and sending updates to the server. Something like the following:

```go
for {
  if time.Now().After(nextStandbyMessageDeadline) {
    err = pglogrepl.SendStandbyStatusUpdate(context.Background(), conn, pglogrepl.StandbyStatusUpdate{WALWritePosition: clientXLogPos})
    // handle error
    nextStandbyMessageDeadline = time.Now().Add(standbyMessageTimeout)
  }

  ctx, cancel := context.WithDeadline(context.Background(), nextStandbyMessageDeadline)
  msg, err := conn.ReceiveMessage(ctx)
  cancel()
  // handle error
  
  // handle message from server
}
```

See the pglogrepl repo for a more full example.
