### ISSUE TITLE
How would convert numeric(8,2) to Golang?

### ISSUE THREAD

**Issue by nkev** [jackc/pgx#56]
I'm relatively new to Golang and need to use a currency column (numeric(8,2)) in my PostGres 9.4 database. What is common pgx practice for this?

Also, I want to later use the new Postgres jsonb datatype (converted to a string in Go is ok). I would appreciate guidance with that too.

**Comment by jackc** [comment]
For what it's worth, in 9f9a9779ac794e885f6fbb04935724f03149f092 I added compatibility with the standard database/sql.Scanner and database/sql/driver.Valuer interfaces for custom types. This means you can use https://github.com/shopspring/decimal as a type that maps to PostgreSQL numeric. See https://github.com/jackc/pgx/blob/master/query_test.go#L913 for an example.

**Comment by jayd3e** [comment]
Thanks for adding this!  It's going to majorly help me out on this latest project.
