### ISSUE TITLE
Prepared / described statement interface

### ISSUE THREAD

**Issue by jackc** [jackc/pgx#560]
Consider executing prepared statements via a new method instead of the using the SQL text as the key to look up in the map of prepared statements.

On one hand this could be more elegant, but there are several difficulties.

1. How are statements connected to the underlying connection?
2. How does this work with a connection pool?
3. Does the statement work on any connection by implicitly preparing itself if it didn't originate on that connection? (like database/sql) How would this work with batches?
4. It's convenient that a string can let callers be oblivious to whether a query is SQL text or a prepared statement name.

**Comment by mattes** [comment]
Coming from [lib/pq](https://github.com/lib/pq) I was expecting some sort of [database/sql/#Stmt.Query](https://golang.org/pkg/database/sql/#Stmt) func in `pgx`, see also https://github.com/jackc/pgx/issues/294, so I'm a +1 on this feature request.

> 3. Does the statement work on any connection by implicitly preparing itself if it didn't originate on that connection? (like database/sql)

From a user's perspective, I'd support this behavior. If I create a prepared statement, I would want it to work across all connections.

> 4. It's convenient that a string can let callers be oblivious to whether a query is SQL text or a prepared statement name.

Or in other words "using the SQL text as the key to look up in the map of prepared statements". I found that rather surprising. I also couldn't find documentation for this behavior in the docs (unless I missed it).

**Comment by jackc** [comment]
A few more ideas or issues that would need to be hashed out to make this a reality:

How would this work for batch operations? Might be a little tricky to handle sending a batch operation that included a prepared statement that isn't available on the connection (so it would need to implicitly prepared before the batch could be sent).

Using the SQL argument as key for prepared statement lookup might be a little surprising, but it also lets any code the executes SQL transparently work with prepared statements as well. That can be really convenient. 

Another trick is what the execution interface would be. I prefer the idea of a connection executing a prepared statement rather than the prepared statement executing itself. i.e. `conn.Exec(ctx, preparedStatement, ...)` rather than `preparedStatement.Exec(ctx, ...)`. The fits better with pgx's more explicit concept of a connection. But I don't want to make separate versions of `Exec`, `Query`, and `QueryRow`. But without doing that, the `sqlOrPreparedStatement` argument ends up being a `interface{}` so we lose some compile time safety. 

Hmm... another interface idea might be splitting the sending of the query from the reading of the results. We could have `SendSimple`, `SendExtended`, and `SendPrepared` to send different types of queries, but they all would return a result that could have `Exec`, `Query`, or `QueryRow` called on it. But I try to stay close to `database/sql style` -- that probably diverges too much.

**Comment by jackc** [comment]
I decided to sidestep the whole issue. Why should the user have to manually prepare statements at all? pgx `v4` now automatically prepares and caches statements. See #559.

The interface for explicit prepared statements will remain the same in `v4` as `v3`, but will rarely ever be used.
