### ISSUE TITLE
Null bytes in pgx#Identifier.Sanitize (possible security vuln)

### ISSUE THREAD

**Issue by mattes** [jackc/pgx#562]
Postgres doesn't allow null bytes in identifiers (see [4.1.1. Identifiers and Key Words](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)):

> Quoted identifiers can contain any character, except the character with code zero.

[lib/pg#QuoteIdentifier](https://github.com/lib/pq/blob/master/conn.go#L1502) is correctly removing null bytes, see [tests](https://github.com/lib/pq/blob/master/conn_test.go#L1537).

pgx's [Sanitize](https://github.com/jackc/pgx/blob/master/conn.go#L307) func is similar to the one above, but doesn't remove null bytes.

**Comment by jackc** [comment]
Thanks for the report. Fixed now.
