### ISSUE TITLE
Functionnement of implicitly prepared queries

### ISSUE THREAD

**Issue by Succo** [jackc/pgx#564]
I was my impression that pgx implicitly prepares statement, as in if you exec twice the same sql with different argument, the query will be prepared once and it is the prepared query that will be executed the second time.

However experiments as shown that explicitly preparing queries on first call gets my better performance (for a query with ~ 100ms of plannig time and ~ 30ms of execution time according to postgreSQL I went from an average runtime of 130ms to an average runtime of 30~40ms)

Looking at the code it seems that prepareEx gets called with "" as it's name argument https://github.com/jackc/pgx/blob/master/conn.go#L2090 when the sql is not the name of prepared query.

So the second time it won't be found in the map of prepared queries.

Is it expected behaviour or did I miss something ?

**Comment by jackc** [comment]
pgx does not automatically prepare statements. The unnamed prepared statement is how the PostgreSQL wire protocol exposes parameterized queries.

Implicitly preparing and caching prepared statements might be a useful feature, but it would need more thought as to how it would be controlled (max cache size, expiration of items, disabling for specific queries, etc.)

The preferred approach now is to call `Prepare` before the query every time. `Prepare` is a no-op if the statement already exists. So if you put the prepare immediately before the query it will only perform the prepare the first time.

**Comment by Succo** [comment]
Ok I see.

Thanks.
