### ISSUE TITLE
How do I store this JSON?

### ISSUE THREAD

**Issue by 9mm** [jackc/pgx#566]
I'm trying to see how to set the following JSON field. It differs from the example in the docs becuase the JSON field is a of the structure: `[{...}, {...}]`. Each inner `{}` is an `Ad{}`.

So for example the field would contain `[{"image": 1, "title": 2, "url": 3}, {"image": 1, "title": 2, "url": 3}]`

heres basically what im doing, and it returns empty structs. Im not sure how to actually set them? `hash` and `addedAt` are getting set properly

```
type Ad struct {
	image string `json:"image"`
	title string `json:"title"`
	url   string `json:"url"`
}

type Impression struct {
	hash    string
	ads     []*Ad
	addedAt time.Time
}

impression := Impression{}
setImpression(tx, &req, &impression, true)

func setImpression(tx *pgx.Tx, req *AdRequest, imp *Impression, lock bool) {
	tx.QueryRow("lockImpression", req.hash).Scan(&imp.hash, &imp.ads, &imp.addedAt)
}

```

**Comment by jackc** [comment]
I'm not sure if there is anything else going on, but one problem is the fields of the `Ad` struct are not public.

**Comment by 9mm** [comment]
Awesome, that fixed it
