### ISSUE TITLE
Backend.ReceiveStartupMessage does not support CancelRequest

### ISSUE THREAD

**Issue by felixge** [jackc/pgx#568]
I'm using the excellent `pgx/pgproto3` to build a PostgreSQL proxy server, and it's working great!

However, one problem I ran into is that it's currently hard to support [query cancelation](https://www.postgresql.org/docs/11/protocol-flow.html#id-1.10.5.7.9) because the [Backend.ReceiveStartupMessage](https://github.com/jackc/pgx/blob/39bbc98d99d7b666759f84514859becf8067128f/pgproto3/backend.go#L43) doesn't support that the initial message might be of type [CancelRequest](https://www.postgresql.org/docs/11/protocol-message-formats.html). In fact, pgproto3 currently doesn't implement a `CancelRequest` message at all.

Would you be interested in a patch that adds support for CancelRequest?

If yes, would you be okay with changing the signature from `ReceiveStartupMessage() (*StartupMessage, error)` to `ReceiveStartupMessage() (FrontendMessage, error)` so that either a `*StartupMessage` or `*CancelRequest` can be returned?

Thanks again for this amazing library!

**Comment by jackc** [comment]
Glad you're finding it useful.

Yes, I'd be interested in that functionality with a couple of qualifications.

pgproto3 is moving into its own project in the next major release of pgx. As this is a breaking interface change this change should be made there: https://github.com/jackc/pgproto3

Second, I'd like to avoid making it more difficult to support SSL connections in the future. I don't think your proposed change would impact this, but the PG startup protocol is a little weird.

**Comment by jackc** [comment]
I just added support for `CancelRequest` and `SSLRequest` to https://github.com/jackc/pgproto3.

**Comment by felixge** [comment]
@jackc sorry for not following up on this earlier, I didn't have a chance to work on my side project again until now. I just checked out the `CancelRequest` and `SSLRequest` implementation and it looks beautiful! I'll try to upgrade to `jackc/pgproto3` and let you know how it works for me in practice!
