### ISSUE TITLE
Deferred unique constraint violation ignored by pgx

### ISSUE THREAD

**Issue by Heanthor** [jackc/pgx#570]
I'm seeing an issue with update statements interacting with deferred constraints and `Query`. If as part of the update a constraint is violated, the error is never returned by pgx, even if rows are read from. My constraint is `deferrable initially DEFERRED` because I want to allow duplicates during the execution of the query, but not after it is complete. If I use a normal unique constraint, pgx returns errors as you'd expect.

```golang
	pool, err := pgx.NewConnPool(pgx.ConnPoolConfig{...},
		MaxConnections: 5,
		AcquireTimeout: time.Duration(10) * time.Second,
	})
	if err != nil {
		panic(err)
	}

	_, err = pool.Exec(`create table if not exists public.repro (
		pk_id SERIAL PRIMARY KEY,
		second_id int NOT NULL,
		unique_date date,
		UNIQUE (second_id, unique_date) deferrable initially DEFERRED 
	)
	`)
	if err != nil {
		panic(err)
	}

	_, err = pool.Exec(`insert into public.repro (second_id, unique_date) values
		(1, '2019-08-12'),
		(2, '2019-08-13'),  -- incrementing this by one day will cause a constraint violation
		(2, '2019-08-14')
	`)
	if err != nil {
		panic(err)
	}

	rows, err := pool.Query(`update public.repro
		set unique_date = unique_date + interval '1' day
		where unique_date < '2019-08-14'
		returning pk_id, second_id, unique_date
	`)
	if err != nil {
		panic(err)
	}

	defer rows.Close()

	for rows.Next() {
		var (
			pkID, secondID int
			uniqueDate     time.Time
		)

		err = rows.Scan(&pkID, &secondID, &uniqueDate)
		fmt.Printf("pk %d, second %d, date %v\n", pkID, secondID, uniqueDate)
		if err != nil {
			panic(err)
		}
	}

	if err = rows.Err(); err != nil {
		panic(err)
	}
```

This produces output: 
```
pk 1, second 1, date 2019-08-13 00:00:00 +0000 UTC
pk 2, second 2, date 2019-08-14 00:00:00 +0000 UTC
```

But, the table's state after that query is:
```
pk_id | second_id | unique_date
-- | -- | --
1 | 1 | 8/12/19
2 | 2 | 8/13/19
3 | 2 | 8/14/19
```
You can see that the change was never committed, because the unique constraint prevented it after the statement was complete.

If I run the same update query from above in a console, I get the expected error:
```
ERROR:  duplicate key value violates unique constraint "repro_second_id_unique_date_key"
DETAIL:  Key (second_id, unique_date)=(2, 2019-08-14) already exists.
SQL state: 23505
```

Also of note: if I repeat this process but on a `pgx.Tx` instead of a `pgx.ConnPool`, the error is returned as expected on commit.

**Comment by jackc** [comment]
Hmm... This is an interesting one. PostgreSQL sends the `CommandComplete` message as if everything worked and then sends an `ErrorResponse` message (which I suppose makes sense in this case because the error occurs on the implicit transaction commit...). 

But `rows.Next()` stops reading when it gets `CommandComplete`. So at first glance `rows.Next()` needs to keep reading until it gets the `ReadyForQuery` message. But that would conflict with how batches are handled... This will take a little thought...

**Comment by Heanthor** [comment]
Awesome, thanks for the quick fix ❤️ and thank you for the great library!

**Comment by mrg0lden** [comment]
Hey @jackc, I think I'm facing a similar issue with Pgx v4. I'm using `pgxpool.Query()` to insert some values and return id of the new row. When inserting a duplicate entry in a unique column I see the error level entry from Pgx's log, but it's never returned. However, when I use `pgxpool.Exec()` the error is returned. 

`Query()`'s insert log
```time="2020-03-24T23:55:47+03:00" level=error msg=Query args="[ ss 3]" pid=71 sql="INSERT INTO \"testing\" (\"name\", \"nullable\", \"unique_num\") VALUES ($1, $2, $3)"```

`Exec()`s insert log
```time="2020-03-24T23:47:34+03:00" level=error msg=Exec args="[ ss 3]" err="ERROR: duplicate key value violates unique constraint \"testing_unique_num_key\" (SQLSTATE 23505)" pid=71 sql="INSERT INTO \"testing\" (\"name\", \"nullable\", \"unique_num\") VALUES ($1, $2, $3)"```

**Comment by jackc** [comment]
Are you reading the result from Query? You need to call `rows.Next()` until it returns false or call `rows.Close()` directly. Then you need to check `rows.Err()`.

**Comment by mrg0lden** [comment]
@jackc Thanks, it worked! Not only do you maintain this package and introduce new features, but you also provide support for package users that's second to none! I wish I could show my appreciation and gratitude for your efforts. Have a wonderful day!
