### ISSUE TITLE
Simplify batch interface

### ISSUE THREAD

**Issue by jackc** [jackc/pgx#571]
`Queue` parameters `parameterOIDs` and `resultFormatCodes` are necessary due to the one round trip nature of a batch.

However, if we allowed a batch operation to take 2 round trips it would be possible to eliminate the need for the those arguments. The first round trip could describe / prepare all the queries.

Somewhat related to #558, #559, and #560.

**Comment by fuintis** [comment]
Hello:

Just at this moment i trying to do a model layer using pgx as base. All things going ok but it was difficult to me figure it out how to use the batch interface. The last of the doubts that left: Is mandatory pass resultFormatCodes parameter for batch? What happends if i not pass it? The batch query execution still works, but i like to know if without this param is necesary an additional round trip. Is this place ok for doing this kind of question?

Many thanks in advance.

**Comment by jackc** [comment]
It is not necessary if you are sending a prepared statement. Otherwise, I think it will default to the text format (slower depending on the data types of the results) if you do not pass it.

It will not take an additional round trip either way. That's actually what this issue is considering though -- it *may* be better to take 2 round trips if necessary to use the binary format and significantly simplify the interface.

**Comment by fuintis** [comment]
> It is not necessary if you are sending a prepared statement.

I can't send prepared statements because all querys are dinamically created (and different each other) by the data layer that i construct.

>  I think it will default to the text format (slower depending on the data types of the results) if you do not pass it.

That's are pretty good news, because simplifies my design.

>  That's actually what this issue is considering though

Yes, i understand the issue. I consider a very good tradeoff add an aditional round trip to simplifies the Batch interface.


Many thanks for your time and efforts.

**Comment by jackc** [comment]
With automatic statement caching now in place `parameterOIDs` and `resultFormatCodes` are now handled internally and no longer necessary for the user to provide. The interface is now much simpler:

`func (b *Batch) Queue(query string, arguments ...interface{})`
