### ISSUE TITLE
COPY FROM for map and sync.Map

### ISSUE THREAD

**Issue by reezer** [jackc/pgx#573]
The current interface from CopyFrom makes it hard to copy from a map and especially sync.Map without having to copy the map's values, which might be a problem for large datasets.

Since one is a builtin and the other is part of the standard libary, maybe it would make sense to come up with efficient implementations for these which could be part of pgx.

**Comment by jackc** [comment]
Can you give me an example of what you mean? The copy functionality in pgx uses (almost) the same serialization logic as the normal query path. So I wouldn't expect specific difficulties with copy.

**Comment by reezer** [comment]
I mean the fact that neither a regular map nor a [sync.Map](https://golang.org/pkg/sync/#Map) are easy to transform into something fitting the `CopyFromSource` type. This is because of the lack of something to fit the `Next()` function.

While for a regular map you could for example count against `len(map)` this is not possible for `sync.Map`, which doesn't have a length and only comes with a `Range(f func(key, value interface{}) bool)` function.

Therefor I would suggest adding for example means to do so for example by adding a way to incrementally add more data and in the end manually calling end. Here an example (with bad namings, excluding error handling for brevity)

```
// Maybe here one could specify a buffer size that causes additions to block
// Maybe it would also be an option to set the table name and column names
copier := pgx.NewCopier()

syncMap.Range(func(key, val interface{}) bool {
  // more code creating the row
  copier.Add(tableName Identifier, columnNames []string, singleRow []{}interface)
})

copier.Finish()
``` 

This would also map well with `for ... range` loops, so regular maps.

Maybe I am missing something though. How would you approach such a case, when syncMap is huge?

**Comment by jackc** [comment]
I might be misunderstanding what you are trying to do. Are you wanting to use a map as a single column value or are you wanting to use it as an entire row where the key/values are used as the column values?

**Comment by reezer** [comment]
The latter, using the individual key/value pairs as rows, or something that will become a row, so they key could be the id and and the value a Person struct with firstname, lastname, email fields for example, each being individual columns.

**Comment by jackc** [comment]
Oh... okay, that's actually different from either of the two things I thought you might have been trying to do. But I think I finally get it.

My first thought is I would just do the naive copy to a `[][]interface{}` and use `CopyFromRows`. The entire data set already is in memory and I would assume most of the memory would be referenced and not copied (`string`, `[]byte`, and pointers).

Until it actually became a problem I would do it the simple way -- premature optimization and all that.

But if as you mention in your original post you have a case that that additional memory usage is unacceptable it is still possible to do what you want. The fundamental problem is basically the difference between an external and internal iterator. A for/range loop or the sync.Map Range functions are internal iterators and the Next() pattern that `CopyFromSource` uses is external iteration.

The internal iteration needs to be converted to external iteration. That can be done by running the for/range loop in a Go routine and sending the results over a channel. When the for/range loop completes it closes the channel. The `CopyFromSource` implementation would read from that channel in `Next()` and return false when the channel is closed.

**Comment by reezer** [comment]
Yes. that's my current approach (and yes it makes a significant difference).

However it feels like a use case of copy that might be beneficial for a lot of people (building up a big database), so maybe it's something that might make sense to consider doing in the library. After all copy is frequently used to build up large (and small) databases. It also seems typical for a use case where one would use a library that in general has a strong focus on performance.

While the API described above is just a quick shot, I wonder whether this is something you consider a fit and would implement or accept pull requests for.

**Comment by jackc** [comment]
> Yes. that's my current approach (and yes it makes a significant difference).

From context it isn't clear to me if you mean that you currently make a copy of the entire data set or if you are using a goroutine and channel.  If the former, then I suggest trying the latter first. If you are already using a goroutine and channel then I would try sending slices of rows through the channel and/or making the channel buffered.

I would be very surprised if the overhead from sending slices of a few hundred records at a time through a buffered channel was of any significance. 

> While the API described above is just a quick shot, I wonder whether this is something you consider a fit and would implement or accept pull requests for.

I'd prefer not to have two different ways of doing the same thing. That said, I would be open to a PR if it was demonstrated that it provided a measurable performance improvement that couldn't be duplicated with the existing interface.
