### ISSUE TITLE
batch update

### ISSUE THREAD

**Issue by vendelin8** [jackc/pgx#574]
Hi,

I was looking for some batch update, and I found this:
https://stackoverflow.com/questions/7019831/bulk-batch-update-upsert-in-postgresql#answer-20224370

I tried to apply it with pgx, like this:
```
qry := "UPDATE pages SET ordr = data_table.field FROM (SELECT UNNEST(ARRAY[$1, $2]) AS cond, UNNEST(ARRAY[$3, $4]) AS field) AS data_table WHERE ID = data_table.cond"
values := []interface{}{2 1 10 20}
DB.Exec(ctx, qry, values...)
```
And I got this error: `ERROR: operator does not exist: integer = text (SQLSTATE 42883)`. When I run the same sql in pgadmin4 with inserting the values directly, it runs fine. This error suggests me that the args are treated as strings, but they are ints. How could I fix this?
Thanks!

**Comment by jackc** [comment]
I'm not sure what that exact SQL is attempting to do, but generally errors such as you describe can be resolved by using a typecast in your SQL so PG knows what type to expect. e.g. `ARRAY[$1::int, $2::int]`

**Comment by vendelin8** [comment]
It works fine, thanks! :)
