### ISSUE TITLE
Query hangs

### ISSUE THREAD

**Issue by 9mm** [jackc/pgx#575]
Hey, I can't figure out why this just hangs indefinitely...? If I cancel the go server, it finanally writes to the DB, but not while its hanging. `req.Hash` is a string column, and the `"[]"` is a JSON field, and the `time` column is a datetime

	if _, err := pool.Exec("updateImpression", "[]", time.Now().UTC(), req.Hash); err != nil {
		return
	}

Also, I noticed that when I use ZapLogger if something errors it doesnt seem to write the actual error, it just looks like this, so I can't really see what is actually wrong when theres an error. Do you know how I can fix that?

```
2019-08-10T22:26:54.512-0700	WARN	pgx@v3.5.0+incompatible/conn_pool.go:172	waiting for available connection
github.com/jackc/pgx/log/zapadapter.(*Logger).Log
	/Users/zesty/.go/pkg/mod/github.com/jackc/pgx@v3.5.0+incompatible/log/zapadapter/adapter.go:34
github.com/jackc/pgx.(*ConnPool).acquire
	/Users/zesty/.go/pkg/mod/github.com/jackc/pgx@v3.5.0+incompatible/conn_pool.go:172
github.com/jackc/pgx.(*ConnPool).Acquire
	/Users/zesty/.go/pkg/mod/github.com/jackc/pgx@v3.5.0+incompatible/conn_pool.go:108
github.com/jackc/pgx.(*ConnPool).Exec
	/Users/zesty/.go/pkg/mod/github.com/jackc/pgx@v3.5.0+incompatible/conn_pool.go:356
```

Heres my config:

```
	dbLogger, _ := zap.NewDevelopment() // NewProduction
	defer dbLogger.Sync()

	connPoolConfig := pgx.ConnPoolConfig{
		ConnConfig: pgx.ConnConfig{
			Host:     "127.0.0.1",
			User:     "zesty",
			Password: "",
			Database: "zamp_email_go_dev",
			Logger:   zapadapter.NewLogger(dbLogger),
		},
		MaxConnections: 5,
		AcquireTimeout: 1 * time.Second,
		AfterConnect:   afterConnect,
	}
```

**Comment by 9mm** [comment]
Ah, issue one was because I started a transaction with `tx` and then used `pool` on accident without the transaction.

**Comment by 9mm** [comment]
I'll just ask this here too so I dont spam the issues with a bunch of comments

How do I write to a json column with an empty `[]`? Right now I'm passing an empty `[]User` slice but its writing it as `null` instead of `[]`

**Comment by jackc** [comment]
What is the definition of `Ad`? And have you checked what `fmt.Printf("%#v\n", imp.Ads)` reveals to ensure it is what you think?

**Comment by 9mm** [comment]
Hmm... it is this for the whole `data` object `{Ads:[]main.Ad(nil)}`

What does (nil) even mean there? I should probably just check if nil anyway in case there is bad response from server, so that will fix it, but i am curious from learning perspective what go is doing here 🤔

**Comment by 9mm** [comment]
```
type Ad struct {
	Title string `xml:"Heading"  json:"title"`
	Image string `xml:"MediaURL" json:"image"`
	Url   string `xml:"URI"      json:"url"`
}
```

**Comment by jackc** [comment]
The nil means that that slice isn't empty it actually is nil. An empty slice and a nil slice are different. That is why pgx is saving null to the database -- that is what nil maps to.

**Comment by 9mm** [comment]
Oh I see. Thanks for explaining I’ll research that more. Do you happen to know the issue with the error logger?

I’ll close this issue when I get home. Thanks again

**Comment by jackc** [comment]
Based on the snippet you provided I suspect the reason no log was emitted was that the problem was a panic not an error. pgx is designed to only panic in case of bug -- internal or user caused -- so it doesn't try to catch, log, or handle them. They are basically fatal.

**Comment by 9mm** [comment]
Hmm I see, I think. Ok - thanks for your help!
