### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by titanous** [jackc/pgx#58]
Would you be open to running tests on [Travis CI](https://travis-ci.org/)? If so, I'm happy to implement the config, you'll just need to toggle the hook on in the Travis settings.

**Comment by jackc** [comment]
The tests might need a little tweaking to skip or setup the different connection authentication tests. But yes, I'm happy to happy it on Travis CI. I turned it on on Travis.

**Comment by titanous** [comment]
Great, which versions of postgres and Go would you like to run against

`pq` runs against Go 1.1-tip and postgres 8.4-9.4, but I think running against old Go versions is overkill (I run against the most recent release version and tip usually).

I only care about the latest version of postgres and the previous, but I assume others care about older versions?

**Comment by jackc** [comment]
I think most recent version and tip for Go is sufficient. Go has such good upward compatibility that I don't see there being demand to run on old versions.

For PostgreSQL, I think it is fair to test against all currently supported versions. So I would test against against 9.0 to 9.4.
