### ISSUE TITLE
error in examples/url_shortener/main.go

### ISSUE THREAD

**Issue by mistralbkru** [jackc/pgx#585]
go run url_shortener/main.go 

url_shortener/main.go:109:4: cannot use log15.New("module", "pgx") (type log15.Logger) as type pgx.Logger in field value:
        log15.Logger does not implement pgx.Logger (missing Log method)

Please, change row 110 from 
Logger:   log.New("module", "pgx"),
to
Logger:   log15adapter.NewLogger(log.New("module", "pgx")),

**Comment by jackc** [comment]
Where are you seeing this? That doesn't line up with what I'm seeing on the `master` or `v4` branches.

**Comment by mistralbkru** [comment]
Yes. It is my mistake. from old branch
