### ISSUE TITLE
[v4]about config.createdByParseConfig in conn.go

### ISSUE THREAD

**Issue by tsingson** [jackc/pgx#588]
pgx v3, our project use TOML to set pgx connect config like Host / Port / User / Password / Database  

try to upgrade to v4,  in conn.go 
```
	// Default values are set in ParseConfig. Enforce initial creation by ParseConfig rather than setting defaults from
	// zero values.
	if !config.createdByParseConfig {
		panic("config must be created by ParseConfig")
	}
```

why it's must  parse  "host=127.0.0.1 port=5432 user=postgres password=postgres database=test"  or "postgres://postgres:postgres@127.0.0.1:5432/test" .................

when I use this:

```
      // 
	pgxConfig := &pgx.ConnConfig{
		Config: pgconn.Config{
			Host:     cfg.Host,
			Port:     cfg.Port,
			User:     cfg.User,
			Password: cfg.Password,
			Database: cfg.Database,
		},
		LogLevel: pgx.LogLevelDebug,
	}

 

pgxConfig.Logger = zapadapter.NewLogger(log)  // log is *zap.Logger 

	conn, err := pgx.ConnectConfig(ctx, cfg)  

```
 
it's no working now.

**Comment by tsingson** [comment]
thanks for clarify.

**Comment by Sledro** [comment]
Hey @jackc 

We were using your example above to connect. but we are trying to swap to connection pooling.

config, _ := pgxpool.ParseConfig("") does not have these params? Host, Port and so on? We also cannot use a url.

Thanks

**Comment by jackc** [comment]
The pgxpool.Config includes a pgx.Config. You would need to access it via that attribute. e.g.

```go
config, _ := pgxpool.ParseConfig("")
config.ConnConfig.Host = cfg.Host
// ...
```
