### ISSUE TITLE
Proposal: Check if connection is alive during pool.Aquire()

### ISSUE THREAD

**Issue by mkorolyov** [jackc/pgx#590]
Hi,

I won't to add check if conn.IsAlive() before returning it in pool.Aquire(), is it something you can accept as PR?

Usecase: I have low latency API's. Sometimes connection hangs, pings takes to long( > 100ms), I want remove such conns from the pool with e.g. conn.Close() in custom logic in AfterConnect callback.

WDYT?

**Comment by jackc** [comment]
This is possible in `v4`. There is a `BeforeAcquire` callback that you can use to do what you want.

**Comment by jackc** [comment]
`v4` is now released and has this functionality through `BeforeAcquire`.
