### ISSUE TITLE
Batch scanning 

### ISSUE THREAD

**Issue by rushib1** [jackc/pgx#592]
Is it possible to do scanning/get records in batches instead of querying using .next() and scaning it for every single record. My database is in different server and the number of round trips will become huge if I get the records 1 by 1.

Example: I have a million records to fetch. I can process them in batches of 1000 instead of getting each row one at a time or all million rows at a time which is really bad for memory.

Thanks for helping in advance.

**Comment by jackc** [comment]
`Next` doesn't cause a round trip. PostgreSQL sends all the results for a query in response to the initial request. `Next` only readies the next row for scanning. Internally, pgx reads off the wire in 8K chunks (which not coincidentally is the same size chunks that the PostgreSQL server will send).

The normal `Next`/`Scan` loop should already approach optimal for minimizing round trips and minimizing client memory usage.

**Comment by rushib1** [comment]
Thanks for clearing my doubt. Is there any official documentation when I can learn about it?

**Comment by rushim1** [comment]
@jackc Is there any way to get all the records in one go? Such that there are no round trips?

**Comment by jackc** [comment]
> Thanks for clearing my doubt. Is there any official documentation when I can learn about it?

The official docs for the wire protocol are here: https://www.postgresql.org/docs/current/protocol.html. How pgx operates is a natural result of the underlying protocol. 

> Is there any way to get all the records in one go? Such that there are no round trips?

Well, there's always going to be at least one round trip... the client sends the query to the server and the server responds with the results. But in most cases there will only be one round trip (especially with `v4`).

But ultimately, you really shouldn't have to worry about this. The default way of using pgx with Query, Next, and Scan is pretty much optimal. It will make a single network round trip to the server. But the results will be processed one row at a time so the amount of memory pgx is using at any one time should not be affected by the number of rows in the result set.

**Comment by rushib1** [comment]
I have done some benchmarking with 1lakh records with different amounts of latencey so to get all records it was taking about 10-20 seconds when the latency is normal, But when a 2 second latency is added it is taking about 2+minutes. So I was wondering what is taking so much time?

**Comment by jackc** [comment]
> 1lakh records

100K ?

> But when a 2 second latency is added

How are you introducing latency?

**Comment by rushib1** [comment]
> 100K ?

Yes 100k records. Just iterating without any processing. 
 
> How are you introducing latency?

used ngrok to make the tcp port global and followed this article to add latency to network interface [http://bencane.com/2012/07/16/tc-adding-simulated-network-latency-to-your-linux-server/](http://bencane.com/2012/07/16/tc-adding-simulated-network-latency-to-your-linux-server/)

**Comment by jackc** [comment]
It's probably occurring at the TCP level, not the PostgreSQL protocol level. You'd have to do a packet capture to see exactly what is happening but I can venture an educated guess.

There is a limit as to how much data can be in flight without acknowledgement (see TCP window size). Your huge result set is larger than that window. The PG server tries to send the whole result set, but it it blocks after filling the window until it gets an receipt acknowledgement from the client. With a latency of 2 seconds, the PostgreSQL server will spend a lot of time waiting for room to send data.

**Comment by rushib1** [comment]
> There is a limit as to how much data can be in flight without acknowledgement (see TCP window size). Your huge result set is larger than that window. The PG server tries to send the whole result set, but it it blocks after filling the window until it gets an receipt acknowledgement from the client. With a latency of 2 seconds, the PostgreSQL server will spend a lot of time waiting for room to send data.

So basically If I somehow try to increase the window size to a certain limit, then there won't be such delay?

**Comment by jackc** [comment]
Presumably.

**Comment by rushib1** [comment]
Great! I have done some testing on this by following these links
[https://stackoverflow.com/questions/3604485/does-tcp-send-a-syn-ack-on-every-packet-or-only-on-the-first-connection](https://stackoverflow.com/questions/3604485/does-tcp-send-a-syn-ack-on-every-packet-or-only-on-the-first-connection)
[https://www.cyberciti.biz/faq/linux-tcp-tuning/](https://www.cyberciti.biz/faq/linux-tcp-tuning/)
[https://www.techrepublic.com/blog/linux-and-open-source/tuning-the-linux-kernel-for-more-aggressive-network-throughput/](https://www.techrepublic.com/blog/linux-and-open-source/tuning-the-linux-kernel-for-more-aggressive-network-throughput/)

I was able to reduce the time from 140 seconds and 70 seconds and I see this as huge success. Thanks for the help and knowledge transfer, thank you so much. @jackc
