### ISSUE TITLE
Cannot connect to local database

### ISSUE THREAD

**Issue by procyclinsur** [jackc/pgx#596]
Importing the following:
```go
import "github.com/jackc/pgx/v4"
```

Using the following connect:
```go
pgx.Connect(context.Background(), os.Getenv("PG_URL"))
```

Where `PG_URL` is:
```bash
export PG_URL=postgresql://localhost:5432
```

I receive the following error.
```
{"level":"fatal","ts":1568082163065,"msg":"Failed to connect to Postgres: failed to connect to `host=/tmp user=procyclinsur database=`: dial error (dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory)"}
```

Is this expected behaviour? am I doing something wrong?

**Comment by jackc** [comment]
It would seem that the URL is not being parsed as expected. It's trying to connect via Unix socket which is the default on some platforms if a host is not specified.

Try using `pgx.ParseConfig` and inspect the resulting config object.

**Comment by procyclinsur** [comment]
I seem to be receiving the following.

```
CFG: &{{/tmp 5432  procyclinsur  <nil> 0x6dce30 0xa06920 map[] [] <nil> <nil> <nil> <nil> true} <nil> info 0xa8c0b0 false true} ERR: <nil>
```

Is it suppose to use a socket? I just want to connect to my port-forwarded kubernetes service.

**Comment by procyclinsur** [comment]
looking at the `pgconn` [code](https://github.com/jackc/pgconn/blob/2f6b8f3f5665228c0800e66b05e797ef119f3ef2/config.go#L153-L166).

```go
	if connString != "" {
		// connString may be a database URL or a DSN
		if strings.HasPrefix(connString, "postgres://") {
			err := addURLSettings(settings, connString)
			if err != nil {
				return nil, &parseConfigError{connString: connString, msg: "failed to parse as URL", err: err}
			}
		} else {
			err := addDSNSettings(settings, connString)
			if err != nil {
				return nil, &parseConfigError{connString: connString, msg: "failed to parse as DSN", err: err}
			}
		}
	}
```

It seem that it is not following the libpq [connection string format](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING).

```
postgresql://
```

So my URL isn't being parsed correctly.

**Comment by jackc** [comment]
pgx now supports `postgres://` and `postgresql://`.
