### ISSUE TITLE
Missing ReplicationConn Documentation.

### ISSUE THREAD

**Issue by meetme2meat** [jackc/pgx#601]
Ok I'm sure does this issue belongs over here. As of lately pgx (godoc) documentation does not reflect the `ReplicationConn` related stuff. 

For now I have using cache documents to read the ReplicationConn related stuff. 

If the issue does not belong here I'll create a separate issue at the correct github repo.(Please do let me know the correct repo)

The documentation, I'm talking about is this https://godoc.org/github.com/jackc/pgx

**Comment by jackc** [comment]
This is a frustrating side effect of Go modules. The godoc system does not appear to have support for modules (https://github.com/golang/go/issues/26827). It only shows the master branch.

pgx `v4` has recently been released and replication support has been spun off to an independent package: https://github.com/jackc/pglogrepl.

The docs can still be accessed by checking out the `v3` branch and running godoc locally.

**Comment by meetme2meat** [comment]
Thanks jackx, I have another issue that I had noticed earlier related to replication where should I add it. here or `pglogrepl` branch

**Comment by jackc** [comment]
If it's a fix for `v3` it would go here, otherwise https://github.com/jackc/pglogrepl.
