### ISSUE TITLE
github.com/jackc/pgx/v4 ? -- missing url ?

### ISSUE THREAD

**Issue by hellower** [jackc/pgx#603]
[go@ssdnodes01:/usr/GO]
$ go get  github.com/jackc/pgx

[go@ssdnodes01:/usr/GO]
$ cat a.go 
package main

import (
        "context"
        "fmt"
        "os"

        "github.com/jackc/pgx/v4"
)

func main() {
        conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
        if err != nil {
                fmt.Fprintf(os.Stderr, "Unable to connection to database: %v\n", err)
                os.Exit(1)
        }
        defer conn.Close(context.Background())

        var name string
        var weight int64
        err = conn.QueryRow(context.Background(), "select name, weight from widgets where id=$1", 42).Scan(&name, &weight)
        if err != nil {
                fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
                os.Exit(1)
        }

        fmt.Println(name, weight)
}
[go@ssdnodes01:/usr/GO]

[go@ssdnodes01:/usr/GO/a]
$ go build
a.go:8:2: cannot find package "github.com/jackc/pgx/v4" in any of:
        /usr/GO/go/src/github.com/jackc/pgx/v4 (from $GOROOT)
        /usr/GO/GOPATH/src/github.com/jackc/pgx/v4 (from $GOPATH)
[go@ssdnodes01:/usr/GO/a]

$ go get github.com/jackc/pgx/v4
package github.com/jackc/pgx/v4: cannot find package "github.com/jackc/pgx/v4" in any of:
        /usr/GO/go/src/github.com/jackc/pgx/v4 (from $GOROOT)
        /usr/GO/GOPATH/src/github.com/jackc/pgx/v4 (from $GOPATH)
[go@ssdnodes01:/usr/GO/a]

**Comment by jackc** [comment]
You need Go modules enabled to access `v4`.

**Comment by hellower** [comment]
Thanks!
