### ISSUE TITLE
Missing pgmock in version 4.0.0

### ISSUE THREAD

**Issue by farverio** [jackc/pgx#607]
In previous versions, there has always been an existing folder github.com/jackc/pgx/pgmock, but this seems to be removed in the latest release four days ago. However, it still exists in the documentation.

Is it possible to provide some guidance -- is this logic now removed or has it been migrated somewhere?

This was unfortunately causing a breaking change for our team so any help would be greatly appreciated!

**Comment by tsingson** [comment]
https://github.com/jackc/pgmock

**Comment by jackc** [comment]
> https://github.com/jackc/pgmock

Correct. In addition, if you needed to use the previous version it's still accessible at the original import path.
