### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by eapikat** [jackc/pgx#613]
I'm probably being obtuse here, but:

$ go get github.com/jackc/pgx

yields ....
package github.com/jackc/chunkreader/v2: cannot find package "github.com/jackc/chunkreader/v2" in any of:
	/usr/local/go/src/github.com/jackc/chunkreader/v2 (from $GOROOT)
	/Users/xxx/GitHub/go/src/github.com/jackc/chunkreader/v2 (from $GOPATH)
package github.com/jackc/pgproto3/v2: cannot find package "github.com/jackc/pgproto3/v2" in any of:
	/usr/local/go/src/github.com/jackc/pgproto3/v2 (from $GOROOT)
	/Users/xxx/GitHub/go/src/github.com/jackc/pgproto3/v2 (from $GOPATH)
package github.com/jackc/pgx/v4/internal/sanitize: cannot find package "github.com/jackc/pgx/v4/internal/sanitize" in any of:
	/usr/local/go/src/github.com/jackc/pgx/v4/internal/sanitize (from $GOROOT)
	/Users/xxx/GitHub/go/src/github.com/jackc/pgx/v4/internal/sanitize (from $GOPATH)

**Comment by eapikat** [comment]
Answering my own issue .... this new version requires go v 12 or better.

**Comment by eapikat** [comment]
... but puddle isn't automatically installed

**Comment by jackc** [comment]
It requires Go modules.

**Comment by peterstace** [comment]
I ran into this issue as well and unfortunately am not in a position to use Go modules at this time.

I worked around this by using [v3.5.0](https://github.com/jackc/pgx/releases/tag/v3.5.0) instead of the latest version. This is the last version prior to pgx requiring the use of Go modules.

**Comment by jackc** [comment]
I've added a note to the readme regarding the Go modules requirement. Also, FYI v3.6.0 is currently the latest release on the v3 branch.
