### ISSUE TITLE
Error 22023 not caught by tx.Query?

### ISSUE THREAD

**Issue by lzambarda** [jackc/pgx#619]
Hello everyone,

I think I may have found a bug in the library but am not sure, therefore I've decided to open an issue to talk about it.
Take this test query:

```sql
SELECT json_array_elements(j->'prop')
FROM (
	VALUES (
		(json_build_object('prop',null::int[])),
		(json_build_object('prop',array[1,2,3]::int[]))
	)
) t(j)
```

Which, if run, will return:
```
ERROR:  cannot call json_array_elements on a scalar
SQL state: 22023
```
Due to postgreSQL being unable to infer the type of the column. (it works fine if I swap rows in `VALUES`).
Whenever I run this via pgx with `tx.Query`, the error variable remains `null` and no rows elements are returned.

Am I missing something or such call should return an error?
Thanks for your time!

**Comment by jackc** [comment]
You will need to check the `rows.Err()` method after `rows.Next()` returns false. `Query` only sends the query to the PG server. It doesn't wait for a response. So it will only report an error if there is a problem sending the query. The error will only be reported when attempting to read the result set.

You always should check `rows.Err()` when reading a query as it is also possible an error may have occurred after receiving some rows but before the query has completed.

**Comment by lzambarda** [comment]
Thanks for your reply, I wasn't checking `rows.Err()` !
