### ISSUE TITLE
Batches seem to choke on +400,000 record inserts

### ISSUE THREAD

**Issue by ldelossa** [jackc/pgx#624]
Hello,

We are inserting large amounts of records at once into a very flat table and pgx reports a Connection close issue. 

```
read tcp 172.18.0.4:44010->172.18.0.2:5432: use of closed network connection
```

We will review our code but we do not seem to be closing the connection ourselves. 

Any known limits to batch sizes?

**Comment by jackc** [comment]
I don't know of any limits. I just ran a test that successfully executed 500,000 inserts.

I suspect the close is coming from https://github.com/jackc/pgconn/blob/master/pgconn.go#L1360. If an error occurs while writing the data to the server the connection is closed -- it would be difficult to safely do anything else. But of course, that produces a rather unhelpful error message.

The PostgreSQL server log might help.

**Comment by ldelossa** [comment]
@jackc  

I would agree that the error is coming from that code location. I am not sure however if it's from a write error or if a batch request takes longer the the CTX we call SendBatch with. The CTX we use is pretty liberal (30 seconds and 1 minute in testing). 

It appears that network latency causes the batches to error more frequently. When we test locally on our machines we can batch rather large inserts, but when we move to hosted env like GCP we must batch in significantly smaller groups.

**Comment by jackc** [comment]
A context timeout could cause this error. It would set a deadline which would cause a write error.

One other thought is if all the queries in the batch are inserts to a single table, then using `CopyFrom` would almost certainly have better performance.

**Comment by ldelossa** [comment]
@jackc 
We need to perform some upset logic on our inserts. What *could* work is a CopyFrom into a temporary table and then perform a query against the temp table into the target table with the upsert logic.

Is this pattern possible with pgx?

**Comment by jackc** [comment]
That should work. You'd have to test to see which performed better though.
