### ISSUE TITLE
stuck in ClientRead state [v4]

### ISSUE THREAD

**Issue by mvrhov** [jackc/pgx#625]
I don't know if this is specific to v4 or the v3 behaviour is the same (it's a bit hard to switch between apis) but we are getting queries stuck in ClientRead state. 
According to the Postgresql specification this means that the Postgresql is waiting for the client to send data.

**Comment by mvrhov** [comment]
I've downgraded the pgx to v3 and the problem is the same.

If it helps I don't do prepared queries upfront.. I always use Exec/Query/QueryRow. The Postgresql is v11 and running on different virtual machine on the same physical server.

The logs don't show anything, and I'm unable to reproduce this on development machine. So any Idea on how to debug this would help.

**Comment by jackc** [comment]
> The logs don't show anything, and I'm unable to reproduce this on development machine.

That's going to make this pretty tricky...

Is it any query in particular?  Do it always happen in a specific spot or randomly?

It wasn't clear if the logs you referenced were the PostgreSQL logs or the pgx logs. But it might be helpful to enable pgx logging of queries. With that when a connection gets stuck you could see what queries were run beforehand.

**Comment by mvrhov** [comment]
The postgresql log is empty. I do have the pgx log setup and I don't see
anything out of order in there.

It's the same set of queries every time. A mix of update and select ones.
They do query/update the same tables but the postgresql doest report a
lock. Just that the queries are 'stuck" in clientread state.
The same queries are run from different go routines and from multiple
processes at the same time.

**Comment by jackc** [comment]
Presumably, if something is stuck on the server then there is a corresponding connection stuck on the client. Maybe use context to timeout queries after a few seconds? That might reveal if any particular query is always involved. Also, with logging enabled it would be useful to look at the previous query that executed on a connection before it hangs.

Maybe also try using the race detector.

**Comment by mvrhov** [comment]
The issue was in my code where I forgot to read from the stop channel multiple times. 
However what implied that the pgx is at fault is that when the connection is put back to pool the postgresql still show last executed query in pg_stat_activity for quite a long time 
The service is pretty idle ATM but the pg_stat_activity still shows the query that has been executed more than 30 minutes ago and with the following values _wait_event_type = Client, wait_event = ClientRead, state = idle_
