### ISSUE TITLE
How do I use array functions in select?

### ISSUE THREAD

**Issue by mindscratch** [jackc/pgx#629]
There are a bunch of [array functions](https://www.postgresql.org/docs/11/functions-array.html) and I'm wondering how to craft the query.

For example, if I have an array column `names text[]` and I want to see if some set of names is in any rows, I might do: `SELECT * FROM table WHERE names && ARRAY['foo', 'bar', 'baz']`

In my code, if I have a `[]string` do I have to build a string that looks like the `ARRAY[...]` portion or can I give the string slice to the pgx library somehow to do it for me?

**Comment by jackc** [comment]
pgx can do it for you. Something like the following should work:

```go
names := []string{"foo", "bar", "baz"}
conn.Query(context.Background(), "select * from table where names && $1", names)
```

**Comment by mindscratch** [comment]
That worked, thanks.
