### ISSUE TITLE
TestQueryRowErrors wrong error returned on postgres 9.1 and 9.0

### ISSUE THREAD

**Issue by titanous** [jackc/pgx#63]
```text
--- FAIL: TestQueryRowErrors (0.01s)
	query_test.go:478: 4. Expected error to contain Cannot encode int into oid 3926 - int must implement Encoder or be converted to a string, but got ERROR: type "int8range" does not exist (SQLSTATE 42704) (sql -> select $1::int8range, queryArgs -> [705])
```

**Comment by jackc** [comment]
Failure was for a test incidentally used a type that isn't available in older versions of PostgreSQL. Changed to use an available type in 651d976ea6c607122b3ac30f526fba416f5edd41. Enabled Travs CI testing against older PostgreSQL in cf674c6958a5e04a2210e36e367ccd19ba4332db.
