### ISSUE TITLE
Upgrading from 3.5 to 4.1 what is pgx.ConnPool.Prepare replaced with?

### ISSUE THREAD

**Issue by blagojts** [jackc/pgx#632]
The pgxpool.Pool struct doesn't have the method. What is an equivalent?

**Comment by jackc** [comment]
The nearest equivalent is to prepare all statements in the after connect hook.

But explicit prepared statements are typically unnecessary in `v4`. By default `v4` automatically prepares and caches prepared statements. My recommendation is to *not* explicitly prepare statements unless you have very unusual / specific requirements.
