### ISSUE TITLE
`$*` variables does not work while `create server foreign data wrapper`

### ISSUE THREAD

**Issue by jney** [jackc/pgx#634]
Hi,

I was expecting `$*` variables to work everywhere, but this doesn't work:

```
	if _, err := pool.Exec(context.Background(), `
		create extension if not exists postgres_fdw;
		create server if not exists server
		foreign data wrapper postgres_fdw
		options (host $1, port $2, dbname $3)`, host, port, db); err != nil {
		// do something
	}
```

I had to do this

```
	if _, err := pool.Exec(context.Background(), fmt.Sprintf(`
		create extension if not exists postgres_fdw;
		create server if not exists server
		foreign data wrapper postgres_fdw
		options (host '%s', port '%s', dbname '%s')`, host, port, db)); err != nil {
		// do something
	}
```

Any reason why?

**Comment by jackc** [comment]
Exec uses the PostgreSQL extended protocol by default when there are query arguments. This means it is basically using a (potentially ephemeral) prepared statement. 

However, prepared statements do not support multiple statements in a single query string. They also only supports SELECT, INSERT, UPDATE, DELETE, or VALUES statements.

When Exec has no arguments it uses the simple protocol which simply sends the SQL string to the server.

So your second example would be the correct way to do this -- with the caveat that you are responsible for sanitizing your parameters.
