### ISSUE TITLE
Pgx v4 doesn't return all rows

### ISSUE THREAD

**Issue by sm4ll-3gg** [jackc/pgx#639]
I have the table that contains around 300k rows satisfying this query (when I send it to the db directly):
```sql
SELECT 
	b.id, pri.provider
FROM
	bookings AS b JOIN provider_information AS pri ON b.id = pri.id
WHERE
	pri.provider_info->>'supplier_id' = 'ID'
```

But when I do that via pgx, I retrieve about 3k rows:
```go
config, err := pgxpool.ParseConfig(dbinfo)
if err != nil {
	return nil, err
}
config.ConnConfig.PreferSimpleProtocol = true
config.MaxConns = 80
pool, err := pgxpool.ConnectConfig(context.Background(), config)
if err != nil {
	return nil, err
}

const query = `SELECT 
		b.id, pri.provider_data
	FROM
		bookings AS b JOIN provider_information AS pri ON b.id = pri.id
	WHERE
		pri.provider_info->>'supplier_id' = 'ID'`


rows, err := pool.Query(context.Background(), query)
if err != nil {
	panic(errors.Wrap(err, "query bookings"))
}

for rows.Next() {
	if err := rows.Err(); err != nil {
		log.Println("next row", err)
		continue
	}

	// some code
}
```

**Comment by jackc** [comment]
Do you have a reproducible case? The nearest I could come up with worked for me.

```go
package main

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v4/pgxpool"
)

func main() {
	config, err := pgxpool.ParseConfig("")
	if err != nil {
		fmt.Println(err)
		return
	}

	config.ConnConfig.PreferSimpleProtocol = true
	config.MaxConns = 80
	pool, err := pgxpool.ConnectConfig(context.Background(), config)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer pool.Close()

	query := `select n, ('{"foo": ' || n::text || '}')::jsonb from generate_series(1, 300000) n`

	rows, err := pool.Query(context.Background(), query)
	if err != nil {
		fmt.Println(err)
		return
	}

	rowsCount := 0
	for rows.Next() {
		var n int64
		var m map[string]interface{}

		err := rows.Scan(&n, &m)
		if err != nil {
			fmt.Println(err)
			return
		}

		rowsCount += 1
	}

	if rows.Err() != nil {
		fmt.Println(rows.Err())
		return
	}

	fmt.Printf("Total rows returned: %d\n", rowsCount)
}
```

Results:

```
jack@glados ~/dev/pgx_639 ±master⚡ » go run main.go
Alias tip: gor main.go
Total rows returned: 300000
```

**Comment by small-egg** [comment]
Such case reproduces for my DB, but I have no idea how to generate a test data set that'll do so.
Could I receive any information from pgx which help you to investigate?
@jackc

**Comment by jackc** [comment]
Here are some things to check.

Are you checking `rows.Err()` after the `for rows.Next()` loop? Any errors?

Is it always the same number of rows that are returned?

Do you have an `order by` clause?

Putting these questions together then leads to the question is it the same the same row that it stops at each time. Try using an offset to skip some rows. Do you get the same number of rows back. In other words determine if the problem occurs after some number of rows or if the problem occurs when encountering a specific row.

I expect that answering the above questions will either give us more information or lead to the solution directly. If not then maybe the PostgreSQL log would. Lastly, you could do a packet capture on the connection -- but I think that is only worth trying if everything else is inconclusive.

**Comment by Dbilzerian** [comment]
I tried the same functionality using pgx and creating a new connection every time a request comes in. It is returning all the rows even for multiple requests back to back. Although it takes more time to cater to all the requests compared to other drivers and also will increase the cost as it will have to create a new connection for each request.

Please find my pgxpool code below and please let me know if I missed anything or otherwise how I can resolve the SSL renegotiation issue:

package main

import (
	"context"
	"io/ioutil"
	"net/http"
	"encoding/json"
	"log"
	"fmt"
	"time"
	"github.com/jackc/pgx/pgxpool"
)

var pool *pgxpool.Pool

func generateConnPool() {
	connStr := ""
	config, err := pgxpool.ParseConfig(connStr)
	if err != nil {
		log.Fatal("Error configuring the database: ", err)
	}

	pool, err = pgxpool.ConnectConfig(context.Background(), config)
	if err != nil {
		log.Fatal("Error connecting to the database: ", err)
	}
}

func QueryHandler(w http.ResponseWriter, r *http.Request) {
	var query string
	var result []string
	var params map[string]string
	var cols = "sn"

	st := time.Now()
	c, err := pool.Acquire(context.Background())
	if err != nil {
		log.Fatalf("Cannot acquire connection")
	}

	body, _ := ioutil.ReadAll(r.Body)
	if err := json.Unmarshal(body, &params); err != nil {
		panic(err)
	}

	query = fmt.Sprintf("SELECT %v FROM %v where lt > %v limit 5000", cols, params["tn"], params["tp"])

	rows, err := c.Query(context.Background(), query)
	if err != nil {
		log.Fatal("Error querying DB: ", err)
	}
	defer rows.Close()
	c.Release()

	stat := pool.Stat()
	fmt.Printf("MC: %v TC: %v IC: %v EAC: %v AC: %v, AD: %v, AConn: %v TT: %v\n", stat.MaxConns(), stat.TotalConns(), stat.IdleConns(), stat.EmptyAcquireCount(), stat.AcquireCount(), stat.AcquireDuration(), stat.AcquiredConns(), time.Now().Sub(st))
	for rows.Next() {
		var tn string
		if err := rows.Scan(&tn); err != nil {
			log.Fatal(err)
		}
		result = append(result, tn)
	}
	fmt.Println(len(result))
	if rows.Err() != nil {
        fmt.Println(rows.Err())
    }

	js, err := json.Marshal(map[string][]string{"sns": result})
	if err != nil {
		log.Fatal("Error marshalling result: ", err)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(js)
}

func main() {
	generateConnPool()
	mux := http.NewServeMux()
	// Routes consist of a path and a handler function.
	mux.HandleFunc("/", QueryHandler)

	// Bind to a port and pass our router in
	err := http.ListenAndServe(":8080", mux)
	 if err != nil {
		 log.Fatal("Server failed to start: ", err)
	}
}

**Comment by jackc** [comment]
You could try running

```sql
select n from generate_series(1, 1000000000) n
```

and see how many rows are returned. If it always fails with same number of rows thats would be an indicator it is a problem with SSL renegotiation.

I don't actually know how to work around it if that is the issue though -- aside from closing connections before it hits the renegotiation limit. Originally Go had no support for renegotiation, supposedly it does have some now. Possible a custom tls.Config would resolve it.

**Comment by Dbilzerian** [comment]
I tried out the query you mentioned and this is the result I got:
```bash
*pgxpool.Pool
MC: 4 TC: 4 IC: 0 EAC: 1 AC: 2, AD: 7.190363ms, AConn: 1 TT: 6.78099ms
MC: 4 TC: 4 IC: 0 EAC: 3 AC: 4, AD: 33.866007ms, AConn: 3 TT: 18.143683ms
MC: 4 TC: 4 IC: 0 EAC: 3 AC: 4, AD: 33.866007ms, AConn: 3 TT: 25.141813ms
MC: 4 TC: 4 IC: 0 EAC: 4 AC: 5, AD: 55.275771ms, AConn: 4 TT: 30.256643ms
0
read tcp : i/o timeout
0
read tcp : i/o timeout
0
read tcp : i/o timeout
0
read tcp : i/o timeout
```
I am not sure why it gave this error for it. Please shed some light on that.

Also, I am planning to use this code in a private network and hence concerned about the security aspect of it. So, could you please expand on where to write a custom tls.Config to disable SSL renegotiation

**Comment by jackc** [comment]
The idea with the query

```sql
select n from generate_series(1, 1000000000) n
```

is to run it on a *pgx.Conn directly and count how many rows actually are returned. If it is always exactly the same then that implies that something is breaking the connection after X bytes are transferred. It's still just my guess that SSL renegotiation. The ultimate way to test that would be to see if the problem persists without using SSL.

As far as `tls.Config`, that is a member of the `ConnConfig` struct. Configuring that is just standard Go, there is nothing pgx specific about it.

**Comment by Dbilzerian** [comment]
```go
connStr := "user=xxx password=xxx host=abc.amazonaws.com port=5439 dbname=dev sslmode=disable"
```
I had **sslmode = disable** and also I verified that in the Redshift server "**require_SSL**" is set to **false**. In this case, the connection is not encrypted.
Do you still think this might be SSL renegotiation issue? If yes, then should I modify tls.Connfig in this way:
```go
connStr := "user=xxx password=xxx host=abc.amazonaws.com port=5439 dbname=dev sslmode=disable TLSConfig=&tls.Config{InsecureSkipVerify: true}
```
If not, what else could be the issue and how can we debug it?

**Comment by jackc** [comment]
If it still doesn't work with SSL disabled then it is not SSL renegotiation. But I have no idea what it would be.

**Comment by cazunzap** [comment]
Any solution to this problem?
Today 2021.05.13, using "github.com/jackc/pgx/v4", i got the same isue, the query with this library/driver/connector retrieve less rows than in fact must return

**Comment by DronM** [comment]
I had the same issue retrieving 50 rows. The driver returns only 30 rows, rows.Err() gives "DataRow body is invalid", If I use offset I can get next rows, but no more than 30. select n from generate_series(1, 100000000) n works fine I use connection pgxpool

**Comment by jackc** [comment]
Do you have a case that will reproduce this issue?

**Comment by DronM** [comment]
Sorry to bother, found my mistake, turned out I acquired and released pgxpool.Conn in one function and iterated rows in another. It worked fine on small datasets, bigger generated DataRow body is invalid/tcp read errors
