### ISSUE TITLE
Problem inserting []int64 trying to convert to Int4Array

### ISSUE THREAD

**Issue by JohnnyQQQQ** [jackc/pgx#642]
I'm migrating a project from lib/pq to pgx. Works quite good so far but I face now the problem that pgx tries to put an `[]int64` into an `Int4Array`. 

The postgres column is an `INTEGER[]`, does converting from 32 to 64 bit not work with arrays?

```
      Error Trace:	common_service_test.go:67
      Error:      	Received unexpected error:
        	         cannot convert [] to Int4Array:
        	            github.com/jackc/pgtype.(*Int4Array).Set
        	            /go/pkg/mod/github.com/jackc/pgtype@v1.0.3/int4_array.go:99
```

**Comment by JohnnyQQQQ** [comment]
I just tried with an empty `[]int32` array and the test is passing. I'm not sure if this is really a bug because the 64 bit might not always fit in the 32 bit ..

**Comment by JohnnyQQQQ** [comment]
I tried now with a schema where I use `BIGINT` instead of `INTEGER` and it is still trying to convert it to `Int4Array`, so I think this is a bug, as a `int64` array should convert to a `Int8Array` and not an `int4Array`.

**Comment by JohnnyQQQQ** [comment]
To reproduce the problem

```sql
CREATE TABLE public.test_int_array (
  my_data INTEGER[]
);
```

```golang
pool, _ := ...
_, err := pool.Exec(context.Background(), "INSERT INTO test_int_array (my_data) VALUES ($1)", []int64{})
if err != nil {
    fmt.Println(err)
}

```

**Comment by jackc** [comment]
It's not so much a bug as a missing feature.  There's no automatic conversion between numeric types in Go or the PostgreSQL binary wire format. So any non-exact match in numeric types needs to have the conversion explicitly specified. At the moment a PostgreSQL `[]int` is compatible with Go `[]int32` and `[]uint32`.

**Comment by JohnnyQQQQ** [comment]
@jackc thanks for the clarification.

Is there any suggested way to do it right now or just converting before the query?

I have over 500 queries to migrate, perhaps it would be worth to implement it, I could spin up a MR if I get a bit of guidance where to start.

**Comment by jackc** [comment]
I *think* it would a small change to the array code generator script. See https://github.com/jackc/pgtype/blob/master/typed_array_gen.sh. That adding to the `go_array_types` argument would be sufficient to make the code change. Maybe add some simple tests to validate that the conversion works as well.

**Comment by JohnnyQQQQ** [comment]
Okay, so basically we can assume that as long as the passed golang type is equal or bigger than the postgresql type, it can be used for conversion, right?

**Comment by jackc** [comment]
The opposite actually. A Go `[]int16` is guaranteed to fit in a PostgreSQL `int[]` but a Go `[]int64` is not. But you don't need to worry about that for this change. The generated code calls `Set` on the underlying element type -- and it will error if the number will not fit.

**Comment by JohnnyQQQQ** [comment]
I spun up a PR, I hope this is kinda of what you thought about 😄
