### ISSUE TITLE
v4: Add back `stdlib.GetDefaultDriver`

### ISSUE THREAD

**Issue by johanbrandhorst** [jackc/pgx#645]
`v3` exposed the convenience function [stdlib.GetDefaultDriver](https://github.com/jackc/pgx/blob/23388fecf653ddfce2a4149acf71313b87d64e3d/stdlib/sql.go#L131), which was useful when wrapping the driver to add metrics and tracing (see https://github.com/opencensus-integrations/ocsql and https://github.com/luna-duclos/instrumentedsql). `v4` removed this function, but I would argue that it is still useful to users, and would like to have it back.

There is a workaround, which is to create an `sql.DB` with `stdlib.OpenDB` or `sql.Open` and calling `sql.Driver()`, before closing the `DB` again. This is, of course, quite grotesque.

I'd be happy to implement this if this proposal is accepted.

**Comment by jackc** [comment]
Sure, didn't realize that was still used. I'm fine with adding it back.
