### ISSUE TITLE
replace for OpenFromConnPool in v4

### ISSUE THREAD

**Issue by alikhil** [jackc/pgx#647]
I want to use pgxpool with sqlx and I am trying to adapt example from [this comment](https://github.com/jackc/pgx/issues/81#issuecomment-296446179) for version v4. But seems like there is no `stdlib.OpenFromConnPool` method now. 

How I can get `sql.DB` from `*pgxpool.Pool` ?

Thank you!

**Comment by jackc** [comment]
There is no exact analog in `v4` or `v3` of pgx. `stdlib.OpenFromConnPool` goes back to `v2`. In `v2` it was used to configure pgx specific settings that can't be set through a connection string as well as it use the pgx pool underneath the database/sql pool.

In `v4` custom pgx config can be used with `stdlib.OpenDB` to get a *sql.DB directly or with `stdlib.RegisterConnConfig` (only on master at the moment) to register a config that can be accessed by name.

But sharing the pgx connection pool with the database/sql connection pool is no longer supported.

If you need to use both `database/sql` and native pgx functionality at the same time the current recommendation would be to do one of the following:

1. Use the database/sql pool. Use `stdlib.AcquireConn` or `database/sql.Conn.Raw` when you need to use native pgx functionality.
2. Use a database/sql pool and a pgxpool.Pool.

**Comment by nordicdyno** [comment]
> But sharing the pgx connection pool with the database/sql connection pool is no longer supported.

Thank you for your explanation! Could you please explain why this decision was made?

**Comment by jackc** [comment]
https://github.com/jackc/pgx/issues/1065#issuecomment-1001639521
