### ISSUE TITLE
Question: parameter limit

### ISSUE THREAD

**Issue by marconi** [jackc/pgx#65]
Does this have the same parameter limit that you encounter with `pq`? 

    pq: got xxxx parameters but PostgreSQL only supports 65535 parameters

Thanks for a great library btw. :)

**Comment by jackc** [comment]
Yes, it is a PostgreSQL limitation. The PostgreSQL wire protocol uses 16-bit integers for count of parameters in the bind message (http://www.postgresql.org/docs/9.4/static/protocol-message-formats.html). Previously, pgx would fail with a misleading error message in this case. I have added better error detection for this.
