### ISSUE TITLE
4.1.2 not work: func (o *LargeObjects) Open(...) (*LargeObject, error)

### ISSUE THREAD

**Issue by bash77** [jackc/pgx#651]
in code use Prepare queries
but in function "func (q *Query) Sanitize(args ...interface{}) (string, error)" return error "unused argument: 0"
as in:
```
len(q.Parts) == 1
q.Parts[0] == "lo_open"
```
this is true for all functions in large_objects.go

**Comment by jackc** [comment]
Sorry, I don't understand what you mean.

**Comment by bash77** [comment]
oh my english, i create code: [https://github.com/bash77/pgx_bug](url)
sorry for repo name 'bug' ))

**Comment by jackc** [comment]
Thanks for the good example. The problem was an incompatibility between prefer simple protocol and large objects. It has been fixed and test cases added.
