### ISSUE TITLE
Batch queries with Transaction fail in case of constraint violation

### ISSUE THREAD

**Issue by Ice3man543** [jackc/pgx#653]
While trying to create a transaction and issue multiple inserts using a batch statement, the rest of the inserts fail if one of the statement gets a constraint violation.

The code i'm using is like this 

```go
tx, err := db.Begin(ctx)
if err != nil {
	return nil, err
}

batch := &pgx.Batch{}
for _, data := range sample {
	batch.Queue("INSERT INTO sample (name, nameid) VALUES ($1, $2);", data.Name, data.ID)
}

batchResults := tx.SendBatch(ctx, batch)

var ids []int64
for _, data := range sample {
	_, err := batchResults.Exec()
	if err != nil {
		if db.ParseError(err) == db.UniqueViolation {
			continue
		}
		return nil, err
	}
	ids = append(ids, host.ID)
}
```

What i basically aim to do is, do a bunch of insert in batch, get the results and iterate through them looking for ones that were successful. 

The table looks like this - 

```
CREATE TABLE IF NOT EXISTS sample (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	nameid BIGINT NOT NULL,
	UNIQUE (name, nameID)
);
```

The issue seems like https://github.com/jackc/pgx/blob/9cb58fc969f149eccdbd07612b13883a8504265f/batch.go#L54-L64

Here, if the next statement resulted in an error, then the further iteration is stopped, which seems not what i imagined would occur. Is there some way around this. 

Thanks!

**Comment by Ice3man543** [comment]
It seems like this code is responsible for reading the error and not advancing if any error code is found. 
https://github.com/jackc/pgconn/blob/3e503b7b1a3beb8466a0ef126b87c209c5dc91e6/pgconn.go#L1088-L1109

I'd like if there was a way we could ignore errors per statement and allow us to advance the execution of other statements. I can fork and add the feature if you give me some ideas on how it would be doable and if its actually possible!

**Comment by jackc** [comment]
This could be a useful feature, but it may be more difficult to implement than it appears.

At the PostgreSQL extended protocol level there is an implicit transaction when multiple queries are sent before a `Sync` message. So it's not just a matter of changing how pgx / pgconn read the results, what is sent also needs to change. The possible changes would be to send a `Sync` after each query or to send a `begin;` and `commit;` around each query. Each of those would require different changes to how pgx / pgconn reads the results.

`begin; ...; commit;` would require a fair amount of change to the batch processing code. But using extra `Sync` messages would change the underlying assumption that the connection is busy if waiting for a `ReadyForQuery` message and ready when it receives one. Now it would need to keep track of how many `ReadyForQuery` messages it is expecting before it is _really_ ready. Prior to `v4` pgx did do this, but it was tricky and error prone logic that I was happy to eliminate...

**Comment by Ice3man543** [comment]
Thanks for the insight. I would appreciate it if there was a way to send SQL directly to the server without preprocessing. Basically I'd require a raw interface like psql where we can send queries. That'd make my work happen.

**Comment by Ice3man543** [comment]
What would you suggest for importing large amount of data which may contain duplicates in batch. I could deduplicate it prior to insert, but seems like unnecessary overhead and letting the db do the deduplication task.

**Comment by jackc** [comment]
> I would appreciate it if there was a way to send SQL directly to the server without preprocessing.

At the simple protocol level it is possible to send multiple statements in a single string. pgconn exposes this with the `Exec` method. But the simple protocol has an implicit transaction. 

> Basically I'd require a raw interface like psql where we can send queries. 

You might be surprised what psql actually does.  When you send a file to psql and some statements work and some don't it appears psql is parsing the input and sending each statement individually. i.e. psql isn't as raw an interface as it may seem.

If you *really*, *really* want to go low-level / raw -- pgconn exposes the underlying net.Conn. You can use the pgproto3 library to construct the over the wire messages to send. I wouldn't recommend doing that if you have an alternative -- but that escape hatch is there to ensure nothing that PostgreSQL allows is impossible -- only inconvenient.

> What would you suggest for importing large amount of data which may contain duplicates in batch. I could deduplicate it prior to insert, but seems like unnecessary overhead and letting the db do the deduplication task.

If you are on a recent enough version of PostgreSQL then the `on conflict` clause would be ideal.

**Comment by Ice3man543** [comment]
@jackc thanks for the reply and a very happy new year. It makes sense for my use case to deduplicate on another service and insert with `on conflict do nothing` clause in batch. I'll do that then. Thanks for the help. Closing this now as i don't see further work that can be done on this!
