### ISSUE TITLE
Panic in Exec method if pass more arguments than expected

### ISSUE THREAD

**Issue by malstoun** [jackc/pgx#656]
I catch a panic, when trying to make a query using `Exec` method: 
`panic: runtime error: index out of range [1] with length 1`

pgx version is 4.1.2 and it also reproduces in the master branch.

The code that reproduces the error:
```golang
poolConn, _ := pgxpool.ParseConfig("host=127.0.0.1 user=pgx")
poolConn.MaxConns = 10
pool, _ := pgxpool.ConnectConfig(context.Background(), poolConn)

var (
	test1 int
	test2 string
)

_, err = pool.Exec(context.Background(), "SELECT id FROM pdata WHERE age=$1 LIMIT 1", test1, test2)
if err != nil {
	log.Println(err)
}
```

I did a little digging and it looks like a length check (like in Query method) was forgotten:
```golang
if len(sd.ParamOIDs) != len(args) {
	rows.fatal(errors.Errorf("expected %d arguments, got %d", len(sd.ParamOIDs), len(args)))
	return rows, rows.err
}
```

I added this check to the `execPrepared` method to fix the panic. I chose `execPrepared` because there are two branches with statement description in the upper `exec` method.

I can add some tests and send a PR for review if that's ok

**Comment by jackc** [comment]
> I can add some tests and send a PR for review if that's ok

Please do.

> I added this check to the execPrepared method to fix the panic. I chose execPrepared because there are two branches with statement description in the upper exec method.

Not sure, but at first glance it might be better added to `execParamsAndPreparedPrefix`.
