### ISSUE TITLE
Terminate query on context cancel

### ISSUE THREAD

**Issue by olomix** [jackc/pgx#659]
I see request canceling on context canceling was removed in https://github.com/jackc/pgconn/commit/444bd6deaf2065c0d108dadfa042df36af88ea57 and I can't find an explanation why (can't see any reference to issue in commit).Early there was a convenient behaviour: long queries were terminated when user canceling http request. Now http user of our web service can terminate request, connection to DB is closed and PostgreSQL continues to process query for another ~20 minutes before trying to reply to client and see that connection is closed. 

I see two ways to workaround this: set statement timeout before each request or call `pgconn.PgConn.CancelRequest` explicitly after each such context timeout error. But it requires to replace all cals to database or wrap them in helper methods. 

What would be the best way to stop database from processing queries on context timeout?

**Comment by jackc** [comment]
The reasoning behind jackc/pgconn@444bd6d is described in #517. But in short, recovering a connection from a canceled query was sometimes impossible and always error prone. That was what led to making context cancellation close the connection.

But apparently I didn't consider that a running query could continue as a zombie after the Go side of the connection was closed. Hmmm...

Okay, I think this is resolved now jackc/pgconn@98b3c57584a2bde785c3f706afcd3d371d6faec3. It should automatically try to cancel any in-progress query asynchronously.

The next tagged release should be in the next few weeks, but if you want to try it now you can pull in pgconn master.

**Comment by olomix** [comment]
Thant you for your fast answer and commit. Unfortunately it seems to me, it doesn't work as expected.

In function PgConn.receiveMessage on these lines, you asyncClose a connection only if it is NOT a timeout error. https://github.com/jackc/pgconn/blob/98b3c57584a2bde785c3f706afcd3d371d6faec3/pgconn.go#L431
```
		if err, ok := err.(net.Error); !(ok && err.Timeout()) {
			pgConn.ayncClose()
		}
```
But when context timeout occurs, IT IS a timeout error, and query does not cancels as expected.

**Comment by jackc** [comment]
> In function PgConn.receiveMessage on these lines, you asyncClose a connection only if it is NOT a timeout error.

`asyncClose` is called by `ResultReader.receiveMessage` or `MultiResultReader.receiveMessage`. `PgConn.receiveMessage` can't do it because a timeout is allowed under certain circumstances such as `WaitForNotification`.

There is a test case that appears to be working (https://github.com/jackc/pgconn/blob/master/pgconn_test.go#L1511). Do you have a case that still exhibits the problem?

**Comment by olomix** [comment]
I've checked only manually. Have run this code and ensured on postgres side, that query is still running.

```
	db, err := sql.Open("pgx", "user=postgres host=localhost database=test sslmode=disable")
	if err != nil {
		panic(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10 * time.Second)
	defer cancel()

	_, err = db.ExecContext(ctx, "select pg_sleep(30)")
	if err != nil {
		panic(err)
	}
```

At first glance your test looks almost the same as my case. Give me some time, I'll try to figure out where the difference is, may be I missed something...

**Comment by olomix** [comment]
Well, this is my bad. Your solution works fine and test is OK. In my case I call panic on error, and as `ayncClose` calls `CancelRequest` in another goroutine, it has no chance to complete statement cancelation. Thank you again. 

BTW, are you deliberately named method `ayncClose` or it is a typo of `asyncClose`?

**Comment by jackc** [comment]
> BTW, are you deliberately named method ayncClose or it is a typo of asyncClose?

Whoops. Definitely a typo.

**Comment by MSadeghzadehG** [comment]
Does it terminate prepared statements after its context timeout? I have the same problem with sqlx, it only closes the connection from the server but the statement is still running on the Postgresql side.
