### ISSUE TITLE
Connection mode changes from TCP to UNIX socket if directory with the same name is present in working directory

### ISSUE THREAD

**Issue by lwalejko** [jackc/pgx#661]
Given following code:
```go
package main

import (
	"fmt"
	"github.com/jackc/pgx"
)

func main() {
	dsn := "host=db port=5432"
	cfg, _ := pgx.ParseConnectionString(dsn)
	_, err := pgx.Connect(cfg)
	fmt.Println(err)
}
```

expected output is:
```
dial tcp: lookup db: no such host
```

but if `db` directory is present in working directory, we get following output:
```
dial unix db/.s.PGSQL.5432: connect: no such file or directory
```

Bug is caused by `ConnConfig::networkAddresses()` method assuming that if `os.Stat(cc.Host)` returns no error, given host is in fact socket file.

This error can easily occur in Docker environments, where host such as `db` are common for database containers.

**Comment by lwalejko** [comment]
This is probably the underlying cause of #453

**Comment by jackc** [comment]
Can you try version 4 `github.com/jackc/pgx/v4`? That changed the logic for discriminating between host names and socket paths to require sockets be absolute paths like libpq does.

**Comment by lwalejko** [comment]
I can confirm that the following code

```go
package main

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v4"
)

func main() {
	dsn := "host=db port=5432"
	_, err := pgx.Connect(context.Background(), dsn)
	fmt.Println(err)
}
```

works as expected:

```
failed to connect to `host=db user=lwalejko database=`: hostname resolving error (lookup db: no such host)
```

**Comment by flcl42** [comment]
I had a directory in the project named exactly like host, pgx counted it as a reason to use unix sockets instead of TCP/IP ones. I changed hostname for the database and it works now.
