### ISSUE TITLE
pgxpool returns partial rows intermittently.

### ISSUE THREAD

**Issue by rleiwang** [jackc/pgx#663]
I am running into an issue where pgxpool returns partial rows. I am using pgx v4.1.2

```
<nil> ERR Query args=[0,1679380636000,["otelcol"]] module=pgx pid=268 sql="SELECT ..."                                                                                                                                             <nil> INF Dialing PostgreSQL server host=postgresql module=pgx
63.623616 INF Query args=[0,1679380636000,["otelcol"]] module=pgx pid=271 rowCount=126 sql="SELECT ..." 
<nil> ERR Query args=[0,1679380636000,["otelcol"]] module=pgx pid=271 sql="SELECT ..."
<nil> INF Dialing PostgreSQL server host=postgresql module=pgx
```
I turned on trace, but pgx only print ERR, nothing else.

```go
	poolConfig, err := pgxpool.ParseConfig(dburl)
	if err != nil {
		return nil, err
	}

	poolConfig.ConnConfig.LogLevel = pgx.LogLevelTrace
	poolConfig.ConnConfig.Logger = zerologadapter.NewLogger(zerolog.New(zerolog.NewConsoleWriter()))

	return pgxpool.ConnectConfig(ctx, poolConfig)
```
query code:
```go
	conn, err := pool.Acquire(ctx)
	if err != nil {
		log.Err(err).Msg("error acquire db connection from pool")
		return nil
	}
	defer conn.Release()

	var chunks []string // blobs of the index, note: last one is the time delta
	err = conn.QueryRow(ctx, `SELECT chunks::json FROM header WHERE hid = $1`, hid).Scan(&chunks)
	if err != nil {
		log.Err(err).Msg("select bucket chunks error")
		return nil
	}
	return chunks
```

The only thing I noticed is, every ERR followed by this log file.
```
<nil> INF Dialing PostgreSQL server host=postgresql module=pgx
```

Any pointers on how to debug the error?

**Comment by jackc** [comment]
Could it be a context cancellation? That terminates the connection and so would explain an immediate redial after an error.

**Comment by rleiwang** [comment]
It's very unlikely context is cancelled, since the context is also used with GRPC call after database retrieval. GRPC execution is fine. Could you point me to where pgx logs the following line.
```
<nil> ERR Query args=[0,1679380636000,["otelcol"]] module=pgx pid=271 sql="SELECT ..."
```
I set log LEVEL to trace, other than partial rows returned and "ERR" string in the log, I am unable to find out more info? Is there network buffer limit setting?

**Comment by jackc** [comment]
That log message appears to be coming from rows.go:144. However, I just noticed you are using `QueryRow`. That only ever returns one row. Perhaps you want `Query`.
