### ISSUE TITLE
Support nil Receiver for Close() Function

### ISSUE THREAD

**Issue by ablox-ethan** [jackc/pgx#671]
It would be useful if the `connRows` struct's implementation of the `Close()` function would support a nil receiver without panicking.

I recommend implementing this functionality with
```
	if rows == nil || rows.closed {
		return
	}
```
As the first line of code in the function.
This will allow callers of your API to safely write
```
	res, err := a.db.Query(ctx, myQuery)
	defer res.Close() 
```
as opposed to 
```
	res, err := a.db.Query(ctx, myQuery)
	defer func() {
		if res != nil {
			res.Close()
		}
	}()
```

**Comment by jackc** [comment]
The state you describe should never occur. From the docs:

```
// Query executes sql with args. If there is an error the returned Rows will be returned in an error state.
```

`Query` should never return a `nil` `Rows`. If that is occurring then that is a bug that should be fixed. I took a quick look at `Query`'s implementation and I didn't see any way for it to happen -- but if you can supply a reproducible case I can take a look at it.
