### ISSUE TITLE
If stdlib.ReleaseConn is called with a conn that's got an open transaction, it's returned to the pool in that state

### ISSUE THREAD

**Issue by alex** [jackc/pgx#673]
Code to reproduce with:

```go
package main


import (
	"context"

	"github.com/jmoiron/sqlx"
	"github.com/jackc/pgx/v4/stdlib"
)

func main() {
	ctx := context.Background()

	db, err := sqlx.Open("pgx", "postgres://postgres:@localhost:5432/test")
	if err != nil {
		panic(err)
	}
	db.SetMaxIdleConns(8)
	_, err = db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS t(id int)`)
	if err != nil {
		panic(err)
	}
	_, err = db.ExecContext(ctx, `TRUNCATE t`)
	if err != nil {
		panic(err)
	}

	pgxConn, err := stdlib.AcquireConn(db.DB)
	if err != nil {
		panic(pgxConn)
	}
	pgxTxn, err := pgxConn.Begin(ctx)
	if err != nil {
		panic(err)
	}
	if false {
		pgxTxn.Rollback(ctx)
	}
	err = stdlib.ReleaseConn(db.DB, pgxConn)
	if err != nil {
		panic(err)
	}

	_, err = db.ExecContext(ctx, `INSERT INTO t VALUES(12)`)
	if err != nil {
		panic(err)
	}
}
```

Run with `go run main.go ; and echo "select * from t" | psql -h localhost -U postgres test` and you'll see that no rows end up in `t` in the database.

If you flip `if false` to `if true`, rows end up in the DB.

This appears to be a bug in `stdlib.go`.

`ReleaseConn` calls `tx.Rollback` (https://github.com/jackc/pgx/blob/master/stdlib/sql.go#L569), however here `tx` is a `fakeTx` which means that `Rollback` doesn't actually do anything.

Allowing the release of in-transaction connection back to the pool leads to tremendously difficult to debug issues.

**Comment by alex** [comment]
I think the easiest fix would be to replace `tx.Rollback()` in `ReleaseConn` with `conn.Exec("rollback")`

**Comment by jackc** [comment]
This is a specific case of the more general problem of a connection being returned in a "busy" state. Following precedent from pgxpool any "busy" connections are closed when returned rather that trying to recover from an unknown state.

**Comment by alex** [comment]
Thanks!
