### ISSUE TITLE
is *Pgx.conn blocking?

### ISSUE THREAD

**Issue by mrg0lden** [jackc/pgx#675]
As the title states, is `*Pgx.conn` blocking (can perform a single query at a time) while `*Pgxpool.pool` isn't?

**Comment by jackc** [comment]
It would be more correct to say that `*pgx.Conn` is not concurrency safe and `*pgxpool.Pool` is concurrency safe. A particular cal to a `*pgxpool.Pool` method may block, but it is safe to call into it concurrently from multiple goroutines.

**Comment by mrg0lden** [comment]
Thank you for your input!

**Comment by jerroldgao** [comment]
> A particular call to a *pgxpool.Pool method may block
Can you make it more specific? I have trouble understanding why SQL clients need to be concurrency safe.

**Comment by jackc** [comment]
A pgxpool method may block if no connections are available. It will also block while waiting for the network.

> I have trouble understanding why SQL clients need to be concurrency safe.

A PostgreSQL session can only do one thing at a time.
