### ISSUE TITLE
ErrNoRows in QueryRow from pgxpool

### ISSUE THREAD

**Issue by igor-semenov** [jackc/pgx#677]
I'm using **pgxpool**, and when I call **QueryRow** with query returning no rows, comparison with **pgx.ErrNoRows** is not working:
```
conn, err := pgxpool.ConnectConfig(context.Background(), cfg)
// ...........................
err := conn.QueryRow(context.Background(), Query).Scan(....)
if err != nil {
	if err == pgx.ErrNoRows {
		return nil
	}
	return err
}
```
The code above returns err, which is _"no rows in result set"_. But **err == pgx.ErrNoRows** is **false**. For now I made dirty fix:
`if err.Error() == pgx.ErrNoRows.Error() {`
But this doesn't look like good code.

**Comment by jackc** [comment]
I am unable to duplicate the issue. I added a successful test case (8c9d1cc15b7307d515d4ff1e1e80776b4b6d1fcc).

**Comment by igor-semenov** [comment]
I've done more investigation and looks like it's all my fault. Sorry.
Problem was in my imports (I just switched go 1.10 -> 1.13):
```
import (
	"github.com/jackc/pgx"
	"github.com/jackc/pgx/v4/pgxpool"
)
```
After I fixed it to
```
import (
	"github.com/jackc/pgx/v4"
	"github.com/jackc/pgx/v4/pgxpool"
)
```
problem gone away.
Sorry once again, it's not an issue.

**Comment by Zamiell** [comment]
I ran across the exact same issue today. It happens because `goimports` (or `goreturns`) will automatically import `github.com/jackc/pgx` instead of `github.com/jackc/pgx/v4`.

Is it possible for pgx to inform `goimports` on how to import it somehow? Not really sure if there's an easy fix for this.

**Comment by edisonspencer** [comment]
I was having something similar, leaving it for future reference.

In my case I was using `sql.ErrNoRows` (defines the string `sql: no rows in result set`), when I should be using `pgx.ErrNoRows` (defines the string `no rows in result set`). Because of this, it would never match what is being returned by pgx's QueryRow.

**Comment by UlasSAYGINIM** [comment]
i have the similar problem in v5. i think this bug didnt corrected by changing imports because i use these.
```
import (
	"context"
	"errors"

	"log/slog"

	"github.com/jackc/pgx/v5"

	"github.com/jackc/pgx/v5/pgxpool"
)
```

**Comment by medcelerate** [comment]
I'm actually encountering this issue and am doing the correct imports. In my case when I run a query. pgx.ErrNoRows is not matching when no rows are returned.
```
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
```

**Comment by medcelerate** [comment]
Additionally, Query and QueryRows in this case return no error even with scan.

**Comment by jflambert** [comment]
Hi @medcelerate  what version are you using? I'm also not getting `ErrNoRows` even though I expect it. `github.com/jackc/pgx/v5 v5.7.1`

**Comment by JustJordanT** [comment]
Getting the same here 
`github.com/jackc/pgx/v5 v5.7.2 `

**Comment by Skeeve** [comment]
Me too with `github.com/jackc/pgx/v5 v5.7.2`

**Comment by jflambert** [comment]
yeah definitely a regression @jackc

**Comment by fiantyogalihp** [comment]
also error here with :
 ```github.com/jackc/pgx/v5 v5.7.5```

```go version go1.24.4 linux/amd64```

```
// using database/sql
conn, err := sql.Open("pgx", dsn)
...

...
fmt.Printf("equal? %v\n", err.Error() == pgx.ErrNoRows.Error())
fmt.Printf("equal? %v\n", errors.Is(err, pgx.ErrNoRows))
...
```

output :
```
equal? true
equal? false
```

**Comment by jackc** [comment]
@fiantyogalihp If your using database/sql then you should be comparing to https://pkg.go.dev/database/sql#ErrNoRows not a pgx value.
