### ISSUE TITLE
How to log batched SQL queries?

### ISSUE THREAD

**Issue by benjamin-bader** [jackc/pgx#680]
Hi there!

I'm working with logging at the moment, and noticing that in the v4 `Logger` interface, I see SQL text in the `data` map under the "sql" key.  For batched queries, unfortunately, it seems that this field is always the literal value `"batch query"`.

Is there a way, in pgx, to log the individual statements that make up a batch?

My log configuration code, in essence:

```go
func (la *LogAdapter) Log(ctx context.Context, level pgx.LogLevel, msg string, data map[string]interface{}) {
  if sql, ok := data["sql"]; ok {
    la.logger.Infof("Executing SQL: %s", sql)
  }
}

config, err := pgxpool.ParseConfig(...)
// error handling omitted
config.ConnConfig.Logger = &LogAdapter{...}
```

**Comment by jackc** [comment]
There's currently no way do this. The `batchResults` struct doesn't know what was sent to the server. I suppose it could keep a reference to the original batch and match up based on the order the results come back. The timing measurements would still be off though.

**Comment by benjamin-bader** [comment]
That's a good point re:timing; I hadn't considered that since we usually get query timings from other sources, e.g. pg_stat_statements.

Would you be open to a PR that added this logging?  Naively, it seems like a simple-enough bit of state-threading.

**Comment by jackc** [comment]
> Would you be open to a PR that added this logging?

Sure.
