### ISSUE TITLE
How do I CopyFrom a slice?

### ISSUE THREAD

**Issue by GAZ082** [jackc/pgx#684]
Hey there.

I have a slice of records of a custom type and I'm trying to insert the data in a PostgreSQL database using pgx:

```
type Sample struct{
    name string
    age int
}

func inertDataToDB(inputData *[]Sample){
    rows := ???
    copyCount, err := IDB.CopyFrom(pgx.Identifier{"public.table"},
                      []string{"name", "age"}, pgx.CopyFromRows(rows))
}
```
The docs says I have to get the rows in an empty, 2D array interface but dont' get it (I'm not used to interfaces):

```
rows := [][]interface{}{
    {"John", int32(36)},
    {"Jane", int32(29)},
}
```
Any sample code would be helpful, could not find any, not even in Github. 

I'm using CopyFromRows but the data is already on memory, perhaps I'd use CopyFromSource? However, I also dont get it.

Thanks!

**Comment by jackc** [comment]
The test cases might be helpful: https://github.com/jackc/pgx/blob/710ddf713465161120dcfbed62e23b4135b96326/copy_from_test.go#L15

**Comment by GAZ082** [comment]
Thanks!
