### ISSUE TITLE
QueryRow() may wait/hang when passed an empty SQL string

### ISSUE THREAD

**Issue by grollojbv** [jackc/pgx#687]
I found this behavior through an what's definitely an application-level issue, but thought it was worth raising in case the driver could or should offer better protection against. 

The underlying issue is that if QueryRow() is called with an empty sql string, there's no return from the QueryRow() call. 

For example: `conn.QueryRow(context.Background(), "")` 

It seems to effectively hang (or perhaps, wait for further input somehow). However, if the configuration has "true" for `PreferSimpleProtocol`, QueryRow() fails with a "no rows in result set" error. 

I've attached a short code example to illustrate the two cases. Run without any arguments, execution appears to stop on the QueryRow() call. Run with a `-simple` argument, the `PreferSimpleProtocol` flag is enabled and we see a "no rows in result set" error on the call to QueryRow().

[main.go.txt](https://github.com/jackc/pgx/files/4277696/main.go.txt)

**Comment by jackc** [comment]
Fixed in https://github.com/jackc/pgconn/commit/911e727d78134c87d39b064aaee2bfda30f7afde.
