### ISSUE TITLE
Exposing PgError information from PGX

### ISSUE THREAD

**Issue by niksajakovljevic** [jackc/pgx#690]
Existing implementation is hiding underlying error information.
It would be useful for me to peek into `PgError` but  `connectError` wrapper is private.

I think a lot of times in your client code you want to make some decisions based on PG error codes.
The only workaround I currently see is working directly with `pgconn`, but would be nice to have the same possibility on the higher/pgx level.

Thoughts?

**Comment by niksajakovljevic** [comment]
Hmm actually just figured out that `pgconn` wraps all the errors in `connectError`... Any recommended workarounds this?

Is this the only workaround:
```
	if e, ok := err.(interface{ SafeToRetry() bool }); ok {
		return e.SafeToRetry()
```

What is the reason not to make `connectError` public but have `PGError` public.

**Comment by jackc** [comment]
`connectError` implements `Unwrap`. You can use `errors.Is` and `errors.As`.

**Comment by niksajakovljevic** [comment]
Ohhh I missed that! Great, thanks

**Comment by redbaron** [comment]
@niksajakovljevic , would you mind closing this issue if you feel your question was answered?

**Comment by paulquerna-okta** [comment]
some docs about this might be helpful - in prototyping a migration from lib/pq, it was hard to find how to detect a  unique_violation vs other errors... but found this ticket:
```
	if pqerr, ok := err.(*pq.Error); ok && pqerr.Code.Name() == "unique_violation" {
            ....
	}

	var pgxerr *pgconn.PgError
	if errors.As(err, &pgxerr) {
		if pgxerr.Code == pgerr_unique_violation {
                   .....
		}
	}
```
