### ISSUE TITLE
Example in the README doesn't run and installation is not obvious to someone new

### ISSUE THREAD

**Issue by AddictArts** [jackc/pgx#694]
Something about modules needed, but no explanation. Would you consider a complete example, because as someone new to go, I can't get the driver installed and example code running. Thanks for the help. And a simple Google search is not leading to the as simple as

```
go get <package>...
```

type solution.

Also an example DATABASE_URL would help, of course I figured that out quickly but, someone totally new could be lost.

Something like this via docker?
```
$ docker run --rm -d --name postgres -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=mypass -e POSTGRES_DB=postgres postgres
d1a2eb0fb44da9c3488184f5296da28d1c7f88bd32bd4ec81fc254f006886b03
```

```
database url postgresql://postgres:mypass@localhost:5432/postgres
```

**Comment by jackc** [comment]
There are a few complete examples in the `examples` directory (https://github.com/jackc/pgx/tree/master/examples). In particular the `todo` example is about the simplest example that actually does something.

**Comment by AddictArts** [comment]
Thanks @jackc

Yes, the examples and godoc are great; However, they make the assumption you can actually use modules. I was lost at `go mod init some.dot.com.or.github.that.I.don't.want.to.setup` why no local development?

The issue for someone new is this line right here, or it was for me.

`go mod init example.com/your/pkg/path/example`

I don't own example.com, or have a website / server there. It makes a newbee think they need a github.com repo or some server at some dot com address. In fact almost all examples when you Google make this assumption. It really made me question golang. That is not pgx's issue. But wow, I thought all modules needed to be hosted at some URL and you couldn't do local dev.

Now I have since learned that you can do

```sh
go mod init
# or
go mod init example
```

I don't completly know the difference with go mod init and no name or the second. I used the second. I also had working project and once I did the go mod init ... it broke my local packages that were working using import "./mypackage".

You may also wish to consider GO11MODULE=off env way of installing or recommend against it.

My issue is resolved, you may close this and thanks for the help, the module, and considering my comments
