### ISSUE TITLE
Wrapping entire tests in transactions.

### ISSUE THREAD

**Issue by minight** [jackc/pgx#697]
I've been using https://github.com/DATA-DOG/go-txdb so far for testing database/sql functions and queries. 

`go-txdb` wraps an existing database/sql driver, where on `sql.Open` it creates a `sql.Tx` using the designated underlying driver and on `sql.Close()` it rollbacks the entire `sql.Tx`. Upon interim calls to `sql.Begin()`, txdb either ignores the `Begin` statement if the database does not support savepoints, or sets up a `SAVEPOINT` that is rolled back to on `ROLLBACK` or saved on `COMMIT`;

**Question**: Is it possible to do something similar to go-txdb for testing functions where a `*pgxpool.Conn` or `*pgx.Conn` is provided as an argument with native pgx?.

I understand that native pgx supports nested transactions that allow for similar functionality. However, this requires the functions to accept an already started transaction (i.e. `db *pgx.Tx`). 

Although stdlib can be used with database/sql to leverage `go-txdb`, I have some functions that require using `CopyFrom` which as far as i'm aware, isn't supported in stdlib. 

e.g. The current testing I'm performing is something like 

```go
package main

import (
	"database/sql"
	"testing"

	"github.com/DATA-DOG/go-txdb"
	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/suite"
	_ "github.com/lib/pq"
)

type TestSuite struct {
	DB  *sql.DB
	DBx *sqlx.DB

	suite.Suite
}

func (suite *TestSuite) SetupSuite() {
	txdb.Register("txdb", "postgres", "DSN")
}

func (suite *TestSuite) SetupTest() {
	var err error
    // Txdb opens a transaction internally here. 
	suite.DB, err = sql.Open("txdb", uuid.New().String())
	suite.DBx = sqlx.NewDb(suite.DB, "postgres")
	assert.Nil(suite.T(), err)
}

func (suite *TestSuite) TearDownTest() {
	suite.DB.Close()
	suite.DBx.Close()
}

func Query(db *sqlx.DB) error {
	_, err := db.Exec("select 1")
	return err
}

func (suite *TestSuite) TestInsert() {
	err := Query(suite.DBx)
	assert.Nil(suite.T(), err)
}

func TestTestSuite(t *testing.T) {
	suite.Run(t, new(TestSuite))
}
```

Can the same be done for a function like below?
```go
func Query(db *pgxpool.Conn) error {
	_, err := db.Exec(context.Background(), "select 1")
	return err
}
```

**Comment by jackc** [comment]
There's a few possibilities to do what you want.

First, `CopyFrom` isn't supported from `stdlib` but you can use `stdlib.AcquireConn` get a native `*pgx.Conn` from `stdlib` and do the `CopyFrom` with that. Not sure how that would interact with the testing libraries you are using though.

The second is to write your application in terms of interfaces instead of structs. I typically define an interface like the following:

```go
type DBConn interface {
	Begin(ctx context.Context) (pgx.Tx, error)
	Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, optionsAndArgs ...interface{}) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, optionsAndArgs ...interface{}) pgx.Row
}
```

This interface is satisfied by a `pgx.Tx`, `*pgx.Conn`, and `*pgxpool.Pool`. You can add `CopyFrom` and other less commonly used shared methods as needed.

Then I a test helper function that automatically connects to the database, starts a transaction, and rolls back when done. I imagine this could be adapted a bit to work with the test suite concept.

```go
func TestSomethingTransactionally(t *testing.T) {
	testutil.WithTx(t, func(ctx context.Context, tx pgx.Tx) {
		// Since tx satisfies the interface used by application code and it
		// emulated nested transactions with savepoints it can even test
		// application code that uses transactions.
	})
}
```

**Comment by minight** [comment]
Thanks! I think migrating to the structs might help if i end up refactoring to use pgx. I also appreciate the helper functions that wrap the application code. I think this will be an easier way of implementing something similar. 

I've tried setting up AcquireConn for stdlib testing, however it appears that when `AcquireConn` is called, it internally tries to start a transaction. However, `txdb` is registered as the SQL Driver, thus when calling into `txdb`'s `BeginTx()` which only ends up performing an `Exec("SAVEPOINT")` with the `pgx` driver, instead of passing a `BeginTx` to pgx. This results in `pgx.BeginTx` being unable to set the `*pgx.conn` from the `AcquireConn` ctx and hence failing.

**Comment by jackc** [comment]
Hmm... Yeah, `AcquireConn` abuses the `database/sql` transaction system to work. That might be a blocker of that path.

Another option might be the `database/sql` functions `Conn()` and `Raw()`. Those should provide the same functionality as `AcquireConn`, but I haven't personally tried it. (In case you're wondering the reason `AcquireConn` exists when the Go standard seems to provide equivalent functionality is `AcquireConn` predates that addition to `database/sql`.
