### ISSUE TITLE
Batch operation improve 

### ISSUE THREAD

**Issue by ruslanBik4** [jackc/pgx#705]
Hi. 
I have 2 ideas:
1. Implements batch operation using pgxpool.Pool 
2. Add method Len to batch 
3. Add method CopyLast(args) to batch. 

Q:
-What is mind of error “no result”? It is end of batch operation or error of one of them?
We must to try repeat operation or break our work?

for ct, err := br.Exec(); err !=nil; {
	// do something 
}

OR

for {
 ct, err := br.Exec();
 If err !=nil {
 If err.Error() == “no result” {
 Continue
}
Break
}
}

**Comment by jackc** [comment]
> Implements batch operation using pgxpool.Pool

`pgxpool.Pool` already supports `SendBatch`.

> Add method Len to batch

`Len` is already a method on `Batch`.

> Add method CopyLast(args) to batch.

I don't understand what this would do.

> What is mind of error “no result”?

This error occurs if you read from the batch results too many times. e.g. If you send 2 queries this error will occur on the 3rd read.
