### ISSUE TITLE
Help with EncodeBinary on Custom Type

### ISSUE THREAD

**Issue by james-andrewsmith** [jackc/pgx#707]
Hi @jackc, first, thanks for PGX. It's awesome. 

I've implemented custom types and all is working great, however I would like to optimise this further by adding `EncodeBinary` to the type. 

I am getting stuck when it comes to separating the properties within a type,as the type itself has multiple columns as I don't known enough about the wire protocol.

Are you able to help guide on how I would convert the `EncodeText` func below into the equivalent `EncodeBinary`? Much appreciated, thank you. 

```sql
CREATE TYPE type_key_added AS
(
	document_id uuid,
	document_type text,
	document_key_id text,
	document_store text,
	shard_id int
)
```

```go
type typeKeyAdded struct {
	DocumentID    pgtype.Text
	DocumentType  pgtype.Text
	DocumentKeyID pgtype.Text
	DocumentStore pgtype.Text
	ShardID       int16
}
 
func (td typeKeyAdded) EncodeText(ci *pgtype.ConnInfo, buf []byte) ([]byte, error) {

	var err error
	buf = append(buf, '(')
	buf, err = td.DocumentID.EncodeText(ci, buf)
	if err != nil {
		return nil, err
	}

	buf = append(buf, ',')

	buf, err = td.DocumentType.EncodeText(ci, buf)
	if err != nil {
		return nil, err
	}
	buf = append(buf, ',')

	buf, err = td.DocumentKeyID.EncodeText(ci, buf)
	if err != nil {
		return nil, err
	}
	buf = append(buf, ',')

	buf, err = td.DocumentStore.EncodeText(ci, buf)
	if err != nil {
		return nil, err
	}

	buf = append(buf, ',')
	buf = append(buf, strconv.FormatInt(int64(td.ShardID), 10)...)
	return append(buf, ')'), nil
}
```

**Comment by jackc** [comment]
Sadly, the binary format is not well documented. I've used a combination of sending a binary request and inspecting the raw bytes and looking at the PostgreSQL source code.

For example, here is how I approach an unknown type.

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

func main() {
	config, err := pgx.ParseConfig(os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatalln(err)
	}

	conn, err := pgx.ConnectConfig(context.Background(), config)
	if err != nil {
		log.Fatalln(err)
	}
	defer conn.Close(context.Background())

	_, err = conn.Exec(context.Background(), `drop type if exists custom; create type custom as (a int, b text);`)
	if err != nil {
		log.Fatalln(err)
	}

	genericBinary := &pgtype.GenericBinary{}
	err = conn.QueryRow(context.Background(), `select '(42,foo)'::custom`, pgx.QueryResultFormats{pgx.BinaryFormatCode}).Scan(genericBinary)
	if err != nil {
		log.Fatalln(err)
	}

	fmt.Println(genericBinary.Bytes)

}
```

Here is the output:

`[0 0 0 2 0 0 0 23 0 0 0 4 0 0 0 42 0 0 0 25 0 0 0 3 102 111 111]`

Based on that output it appears that custom composite types have the same format as `record`.

The first 4 bytes are the number of fields - 2
Then for each field:
4 bytes - OID
4 bytes - length of value
x bytes - value

`record` can be decoded by `pgtype.Record`. You can probably adapt its `DecodeBinary` method for your purposes.

**Comment by james-andrewsmith** [comment]
Well it's great to confirm I wasn't missing something obvious.

Thank you for the snippet, really appreciated!
