### ISSUE TITLE
Unnecessary goroutine spawn in pool destructor function

### ISSUE THREAD

**Issue by georgysavva** [jackc/pgx#708]
I think there are an unnecessary goroutine spawn in the pool destructor:
https://github.com/jackc/pgx/blob/43c2113f90d711e967891da44cea130d41f3b3d6/pgxpool/pool.go#L173-L179
You pass a function that spawn a goroutine when called. But in the puddle pool implementation when you call the destructor function you always call it in a separate goroutine:
[here](https://github.com/jackc/puddle/blob/fc71d04d41f85bc3393394390f79628b713bd5a0/pool.go#L151), [here](https://github.com/jackc/puddle/blob/fc71d04d41f85bc3393394390f79628b713bd5a0/pool.go#L409) and [here](https://github.com/jackc/puddle/blob/fc71d04d41f85bc3393394390f79628b713bd5a0/pool.go#L422).
So you do a double "go". And when on `pool.Close()` you wait for all resource to be destructed: [p.destructWG.Wait()](https://github.com/jackc/puddle/blob/fc71d04d41f85bc3393394390f79628b713bd5a0/pool.go#L159)
You don't actually "wait" for them because every call to the destructor function will return right away and trigger the [p.destructWG.Done()](
https://github.com/jackc/puddle/blob/fc71d04d41f85bc3393394390f79628b713bd5a0/pool.go#L456)
I think `pgx` should pass destructor function without `go` statement.

**Comment by jackc** [comment]
Good catch. You are correct.
