### ISSUE TITLE
Question: How do I retrieve database generated primary key value?

### ISSUE THREAD

**Issue by sptrakesh** [jackc/pgx#711]
Hello,

Based on example, it appears that the `Exec` function is to be used to insert rows into a table.  I want to use statement of the form `INSERT INTO table_name VALUES (...) RETURNING id INTO id`.  Looking at the CommandTag type, I do not see how I can get the id value (perhaps scan it from the string representation?).

Any recommendation on handling this will be much appreciated.

Thanks
Rakesh

**Comment by jackc** [comment]
Use `QueryRow`. A `returning` clause causes an `insert` to return a result set like a `select.
