### ISSUE TITLE
Disable automatic prepared statements 

### ISSUE THREAD

**Issue by georgysavva** [jackc/pgx#714]
I want to disable automatic prepared statement. My queries will be dynamically generated and I think prepared statements will degrade  the performance. I found this setting:
https://github.com/jackc/pgx/blob/7a9efdefde6ff653e2b5179bc35822f58e336b9d/conn.go#L32-L34 And from the comment it sounds like it's what I need. But If understand the code correctly even if this setting is nil. Pgx will automatically call .Prepare() and save it to the `.preparedStatements` map:
https://github.com/jackc/pgx/blob/7a9efdefde6ff653e2b5179bc35822f58e336b9d/conn.go#L468-L484
So how to disable prepared statements completely and what is the difference between the `.preparedStatements` and `.stmtcache` ?

**Comment by jackc** [comment]
`.preparedStatements` is a store of the statements that have explicitly been prepared by the application (i.e. by calling `*Conn.Prepare()`). `stmtcache` is a cache for the implicitly prepared statements. 

```go
sd, err := c.Prepare(ctx, "", sql)
```

The prepared statement with the name of `""` is special in the PostgreSQL wire protocol. It is a ephemeral statement to enable using the extended protocol (which gives us binary format values and no need to do client side argument interpolation and sanitization). Using the extended protocol in this way _does_ entail 2 round trips though. That is why the prepared statement cache is so valuable.

If you want to disable it all then you need to force usage of the simple protocol. This can be done per query or it can be set as default by setting `ConnConfig.PreferSimpleProtocol = true`.

But I would suggest running benchmarks before and after. I suspect even with a fair dynamic SQL that using the statement cache would be faster.

**Comment by georgysavva** [comment]
Thanks. Now I get it. I found out that cache has a capacity and always cleanup old statements it should be efficient. And I can disable implicit caching for particular dynamic queries and have it enabled by default for everything else.

**Comment by georgysavva** [comment]
Quick follow up question. If I do switch on simple protocol I will have no option to use golang native []string and will need to wrap it with pgtype.TextArray ?

**Comment by jackc** [comment]
I believe that `[]string` should still work.

**Comment by georgysavva** [comment]
Here is my code part where I try to pass []string as a parameter:
```golang
	ctx := context.Background()
	cfg, err := pgxpool.ParseConfig("postgresql://localhost:5432/postgres")
	cfg.ConnConfig.PreferSimpleProtocol = true
	pool, err := pgxpool.ConnectConfig(ctx, cfg)
	connectionIDs := []string{"a", "b"}
	_, err = pool.Query(ctx, "select * from connections where connection_id != all($1)", connectionIDs)
	if err != nil {
		panic(err)
	}
```
Results in `Cannot encode []string in simple protocol - []string must implement driver.Valuer, pgtype.TextEncoder, or be a native type`
The error is the same if I do SimpleProtocol for particular query:
```golang
	ctx := context.Background()
	cfg, err := pgxpool.ParseConfig("postgresql://localhost:5432/postgres")
	pool, err := pgxpool.ConnectConfig(ctx, cfg)
	connectionIDs := []string{"a", "b"}
	_, err = pool.Query(ctx, "select * from connections where connection_id != all($1)", pgx.QuerySimpleProtocol(true), connectionIDs)
	if err != nil {
		panic(err)
	}
```

**Comment by jackc** [comment]
Ah, you're right. I'd forgotten exactly how the simple protocol path works. With the extended protocol we know the PostgreSQL type and convert to that. But in the simple protocol we don't know what it on the PostgreSQL side. So there is a different encoding path that needs to support native Go types -- we can't rely on the pgtype types to automatically figure it out.

Try now. I added support for native Go string and number slices to map to arrays in the simple protocol in be9ceaefe6665b64da6b570725ae33294889a438.

**Comment by georgysavva** [comment]
Thanks. Now it works.
Correct me if I am wrong: we can't also add support for map[string]interface{} type because we don't know should it be json or jsonb postgres type?

**Comment by jackc** [comment]
> Correct me if I am wrong: we can't also add support for map[string]interface{} type because we don't know should it be json or jsonb postgres type?

The text format of `json` and `jsonb` is identical is that wouldn't be a problem. The question would more be if `map[string]interface{}` should always be converted to JSON at all. `hstore` is still out there, though I imagine its use is greatly reduced by now. With the extended protocol we know what the destination type is in PostgreSQL and can correctly convert `map[string]interface{}` to JSON or `hstore` as appropriate. With the simple protocol we either have to choose one or force the user to explicitly use a pgtype.

**Comment by georgysavva** [comment]
Ok got it. Makes sense. Thanks for a quick patch. Closing the issue.
