### ISSUE TITLE
How to list tables

### ISSUE THREAD

**Issue by VineethReddy02** [jackc/pgx#720]
Is there any way I can list the tables from postgres db using pgx client?

When I try?
`b, err := a.Query("SHOW TABLES")`
It results in error
panic: ERROR: unrecognized configuration parameter "tables" (SQLSTATE 42704)

**Comment by jackc** [comment]
That is a MySQL command...

https://stackoverflow.com/questions/769683/show-tables-in-postgresql gives a few different queries that will work in PostgreSQL.
