### ISSUE TITLE
How to learn well pgx?

### ISSUE THREAD

**Issue by frederikhors** [jackc/pgx#721]
I'm new to Go, to database/sql and to pgx.

Is there something like this: https://jmoiron.github.io/sqlx/ for `pgx`?

Is there something to learn very well?

Thanks for your amazing work!

**Comment by jackc** [comment]
Sadly, I don't know of any tutorials that are that extensive for pgx. Hopefully, I can get to it at some point...

**Comment by GAZ082** [comment]
Hey there. The tests code are a useful source of examples.

**Comment by awsom82** [comment]
@frederikhors also don't forget about docs https://pkg.go.dev/github.com/jackc/pgx/v4?tab=doc

**Comment by jackc** [comment]
There is now some additional introductory material on the [wiki](https://github.com/jackc/pgx/wiki).
