### ISSUE TITLE
How to query multi-dimensional array

### ISSUE THREAD

**Issue by b3j0f** [jackc/pgx#725]
Hello.

I am trying to query this type of data: [][]double precision

When I call the method rows.Values(), I discover items of type pgtype.Float8Array

Are there a way to automatically convert those values to my multi-dimensional array ?

**Comment by jackc** [comment]
> Are there a way to automatically convert those values to my multi-dimensional array ?

Sorry, there is not. You would need to read the construct it manually from the `Elements` and `Dimensions` fields of `pgtype.Float8Array`.

**Comment by b3j0f** [comment]
Would you integrate the code if I write it here ?
