### ISSUE TITLE
[QUESTION] Comparison with lib/pq

### ISSUE THREAD

**Issue by pires** [jackc/pgx#73]
Can you please describe the differences between this project and [`lib/pq`](https://github.com/lib/pq)?

**Comment by jackc** [comment]
pgx has a native interface the does not go through database/sql (it also supports database/sql). This native interface allows access to more PostgreSQL features and potentially better performance. For example, pgx supports slice to PostgreSQL array mapping, transaction isolation levels, large objects, and binary protocol support (can be much faster).

**Comment by pires** [comment]
This is very valuable information. You should add it to the landing page so others can quickly tell the differences.

Another question, does it support Unix sockets?

**Comment by jackc** [comment]
Yes. Just use the socket directory as the Host parameter.
