### ISSUE TITLE
Best practice for multiple go routines listening for a Postgres notification.

### ISSUE THREAD

**Issue by threeaccents** [jackc/pgx#735]
I'm trying to get multiple go routines listen to PG events using `conn.WaitForNotification`.

The issue I'm running into is If `conn.WaitForNotification` gets called within the same connection more than once it errs with `conn busy`. I'm trying to set up a program that has 10 go routines (workers) listening for events. Something like:

```go

func launchWorkers(conn *pgx.Conn) {
	for i := 0; i < 10; i++ {
		i := i
		go func() {
			for {
				notification, err := conn.WaitForNotification(context.Background())
				if err != nil {
					// handler err
				}
				// handle payload
			}
		}()
	}
}
```

What would be the best way to go about this? Kind of a silly idea but should I just ignore the `conn busy` errors? And keep as is. Since `WaitForNotification` is blocking I was kind of just hoping the blocks the for loop for continuing until a notification is sent. So the for loop doesn't keep looping for ever.

**Comment by threeaccents** [comment]
So I'm new to this package just realized I the connection pool is a sub package. However, pgxpool doesn't have the listener `WaitForNotification` helper func.

**Comment by jackc** [comment]
I would suggest using a single connection to listen for notifications. Then this notification can be put in a channel that your workers read from.

**Comment by threeaccents** [comment]
I gotcha so something more along the lines of 
```go
func listenForEvents(pool *pgxpool.Pool) {
	if _, err := pool.Exec(context.Background(), "listen jobs_status_channel"); err != nil {
		panic(err)
	}

	conn, err := pool.Acquire(context.Background())
	if err != nil {
		panic(err)
	}

	notificationCh := make(chan *pgconn.Notification)

	go func() {
		for {
			notification, err := conn.Conn().WaitForNotification(context.Background())
			if err != nil {
				panic(err)
			}
			notificationCh <- notification
		}
	}()

	for i := 0; i < 10; i++ {
		launchWorker(notificationCh)
	}
}

func launchWorker(notificationCh chan *pgconn.Notification) {
	go func() {
		for {
			select {
			case n := <-notificationCh:
				fmt.Printf("Payload %s\n", n.Payload)
			default:
				// could sleep for a bit
			}
		}
	}()
}

```

**Comment by jackc** [comment]
Execute the `listen` on the acquired conn not on the pool. Otherwise you have no guarantee the listen was executed on the same conn that will wait for notification.

**Comment by jackc** [comment]
Also, this has nothing to do with pgx but: 

```go
func launchWorker(notificationCh chan *pgconn.Notification) {
	go func() {
		for {
			select {
			case n := <-notificationCh:
				fmt.Printf("Payload %s\n", n.Payload)
			default:
				// could sleep for a bit
			}
		}
	}()
}
```

You wouldn't want a default sleep. Waiting on a blocked channel read is already efficient. You probably would want an additional channel to signal cancellation and just select between those.

**Comment by threeaccents** [comment]
Thank you so much!

**Comment by threeaccents** [comment]
@jackc BTW have you considered turning on GitHub sponsor? I wanted to find a way to support you and your project.

**Comment by jackc** [comment]
Thanks, I haven't really thought about it. But a couple people have mentioned it recently so maybe I will look into when I have a chance.

**Comment by benedictjohannes** [comment]
@jackc Will `WaitForNotification` in a for loop as suggested not be subjected to the `MaxConnLifetime` config of the pool? Or, it would last as long as the context, which in case of `context.Background()`, lasts for the lifetime of the `main` goroutine?  
Forgive my ignorance, I'm worried that the listener is killed due to `MaxConnLifetime` being reached resulting in missed out notification.

**Comment by jackc** [comment]
`MaxConnLifetime` is only enforced when the connection is in the pool -- and what you probably want is to acquire one connection from the pool and never release it.
