### ISSUE TITLE
can't scan into dest[0]: unable to assign to *db.test

### ISSUE THREAD

**Issue by CarterScadden** [jackc/pgx#736]
`
	rows, err := conn.Query(
		context.Background(),
		`
			SELECT (
				post_id,
				post_title
			)
			FROM posts
			WHERE post_type = $1
			ORDER BY post_date ASC
			OFFSET $2
			LIMIT 10
		`,
		postType,
		start,
	)

	if err != nil {
		return posts, err
	}

	type Post struct {
		PostID int
		PostTitle string
	}

	for rows.Next() {
		fmt.Printf("NEXT\n")
		
		post := &Post{}
                // Error happening here
		err := rows.Scan(post)
		if err != nil {
			return posts, err
		}
                fmt.Printf("post: %v\n", post)
	}
`

As the title suggest, I am completely lost,
If there's any pointers or fixed please let me know.

**Comment by jackc** [comment]
Scan into the fields, not the struct as a whole. e.g.

```go
err := rows.Scan(&post.PostID, &post.PostTitle)
```

**Comment by CarterScadden** [comment]
> Scan into the fields, not the struct as a whole. e.g.
> 
> ```go
> err := rows.Scan(&post.PostID, &post.PostTitle)
> ```

Okay did this but recieved the error:
`number of field descriptions must equal number of destinations, got 1 and 2`
I only changed the line qouted, running the query on my phAdmin3 gives me a valid response of
(1, "Dummy Title")

**Comment by CarterScadden** [comment]
Turns out my  ( ) was messing up the query and returing only one item wrapped in (), Sorry, Ill close this now. Thank you.
