### ISSUE TITLE
unable to assign to pq.StringArray

### ISSUE THREAD

**Issue by CarterScadden** [jackc/pgx#738]
Maybe this should be posted over on pq,
But I'm wondering whats wrong with this

`
			array_to_string(
					array(
						select
							(
								comment_date::TEXT,
								comment_content,
								comment_username
							)
						from comments c
						where c.comment_post_id = $1
					),
					',',
					'*'
				) as tag_arr
`
...
```
		err := rows.Scan(
	                ...,
			pq.StringArray(post.Comments),
		)
```
Gives the error in the title.
I am able to remove array_to_string and leave a simple array, while this 'works' I then have to parse the array for the comment values. Which causes a massive security / parsing risk of users entering characters interfere with the parsing.
Thank you for any and all help :)

Edit: to add the post.Comments is of type []string

**Comment by jackc** [comment]
I have no idea what `pq.StringArray` array does.

But in `pgx` native you can directly scan into a `*[]string`. You can also use `pgtype.TextArray` if you are using `database/sql`.
