### ISSUE TITLE
"bind message has N result formats but query has M columns"

### ISSUE THREAD

**Issue by atombender** [jackc/pgx#747]
I'm unable to reproduce this in an isolated test case that runs the exact same queries, so I suspect this is something being screwed up in the connection protocol.

Here's from our log:

```
18:20 DBG Exec args=[] commandTag=QkVHSU4= pid=11678 sql=begin
18:20 DBG Query args=["test"] pid=11678 rowCount=1 sql="SELECT id, name, COALESCE(class, ''), immutable, squashed, squash_scheduled, search_store_version FROM namespaces WHERE name = $1 "
18:20 DBG Exec args=[1,false] commandTag=REVDTEFSRSBDVVJTT1I= pid=11678 sql="DECLARE c1 CURSOR FOR SELECT d.id, d.type, d.revision_id, d.version, d.deleted, n.name, pg_column_size(d.attributes), d.attributes FROM documents d JOIN namespaces n ON n.id = d.namespace_id WHERE d.namespace_id = $1 AND d.deleted = $2"
18:20 ERR Query args=[] pid=11678 sql="FETCH 1000 FROM c1"
```

We call `Query()` and get back a `Rows` value. `rows.Next()` then immediately returns false, and then `Err()` returns the error:

```
ERROR: bind message has 9 result formats but query has 8 columns (SQLSTATE 08P01)
```

This is odd, because we haven't even called `Scan()` yet.

The exact same code worked fine with 3.6.2. Trying to upgrade to 4.6.0, I can't get the above to work at all.

I've tried to create an isolated test case that executes the exact same stuff, but I am unable to provoke the bug there.

**Comment by jackc** [comment]
Hmm. The logged command tags look wrong. Not sure if that is related. Might be worth building with the race detector enabled.

But the next thing that jumps to mind is if cursors are compatible with the prepared statement cache. Try disabling it with `statement_cache_capacity=0`.

**Comment by atombender** [comment]
`statement_cache_capacity=0` fixed it, thanks. Didn't realize there was caching going on now.
