### ISSUE TITLE
doc.go: Correction of the error interpretation

### ISSUE THREAD

**Issue by abclogin** [jackc/pgx#749]
doc.go contains an error in code example immediately after this text:

> Query Interface
> pgx implements Query and Scan in the familiar database/sql style

If another variable err is used in the loop. Then query's error value will be returned in condition after loop. But not rows's error. Although the condition may have a different meaning.

For example:

```
rows, err := conn.Query(context.Background(), "select generate_series(1,$1)", 10)
if err != nil {
    return err
}
// Let err is nil
defer rows.Close()

for rows.Next() {
    var n int32
    // Original was "err = rows.Scan(&n)"
    // But we will use new variable. Because we use ":=" but not "="
    err: = rows.Scan(&n)
    if err != nil {
        // Let err is not nil
        return err
    }
    sum += n
}

if rows.Err() != nil {
    return err
}
```

Let we not have query's error. But we have rows's error
Then "rows.Err()" returns not nil value. And the condition will be met.
But function returns err == nil

Correct code is
```
err = rows.Err()
if err != nil {
    return err
}
```

**Comment by jackc** [comment]
Thanks! Good catch.
