### ISSUE TITLE
Follow up on https://github.com/jackc/pgx/pull/751

### ISSUE THREAD

**Issue by georgysavva** [jackc/pgx#752]
I added a few comment In the original PR after the merge. Decided to summarise them in a new issue:

I think I made a mistake in the PR. Right now `pgx.Conn` doesn't store the config as is, it stores a copy that is modified in the `pgx.connect()` function:
https://github.com/jackc/pgx/blob/b19811bbebf7e1211acaa4f804ec12b6cd859285/conn.go#L178-L195
If user has a `pgx.Conn`: `conn1` and later he wants to establish a new `pgx.Conn`: `conn2` using config from the `conn1`.
`conn1.Config()` will return config with `.OnNotification` set and it won't be reset for the conn2 in `pgx.connect()` function. This can lead to unexpected behaviour. `pgx.Conn` should store the original config before patching it.
BTW this is not a problem for the `Pool` because it saves config before `pgx.connect()` will modify it.

Apart from that, I think It would be better if `Config` had something like `.Copy()` method that returns a smart copy of the config. 
Let's Imagine the situation that you have a pool and you want to establish a new one with the same config, but to a different logical database. You call `pool.Config()` and since it's a pointer to the original config you don't want to modify it directly and try to make a copy of it:
```golang
newConfig := &pgxpool.Config{}
*newConfig = *pool.Config()
newConfig.ConnConfig.Database = "another_db"
```
But this won't copy the nested `ConnConfig` struct since it's also a pointer and you will still end up modifying the original config. 
Deep copy libraries that do it via reflection are not an option too, since they don't copy private fields and it means that `.createdByParseConfig` will be set to `false` for the new config.
I think the possibility to get a copy of the config should be builtin in the library. 

Tell me what you think, if you agree I can implement it.

**Comment by jackc** [comment]
I think your correct about the need for a deep copy. I'm not sure if it needs to be a public method though. I think the `Config()` methods on `Conn` and `Pool` should automatically return a copy that is safe to use.

**Comment by georgysavva** [comment]
Okay, I agree. And what do you think about the first part?

**Comment by jackc** [comment]
You mean regarding storing the the original config prior to modification? I agree that is necessary.

**Comment by georgysavva** [comment]
Great. I will prepare the fix then.
