### ISSUE TITLE
What library is compatible for migrations with pgx?

### ISSUE THREAD

**Issue by ashu8912** [jackc/pgx#753]

**Comment by jackc** [comment]
Migrations are somewhat orthogonal to a database driver. Any standalone migration system will work.

My own particular take on migrations is reflected in [tern](https://github.com/jackc/tern). It is primary designed to be used as a standalone CLI tool, but the entire migration system is a separate package. Personally, I prefer migrations to be separate from the application, but if you want to embed migrations in your app and you are using pgx then the tern migrate package is probably a decent place to start.
