### ISSUE TITLE
Hstore scanning possibly unknown issues

### ISSUE THREAD

**Issue by Fattouche** [jackc/pgx#754]
This may be just me not noticing my imports but this issue took me a little while to figure out why hstore wasn't parsing with 

```
Unknown Error: can't scan into dest[0]: unknown oid 476581 cannot be scanned into *pgtype.Hstore
```

It's because I was importing `github.com/jackc/pgx/pgtype` instead of `github.com/jackc/pgtype`. Not sure if there is any way to fix this, but figured I would make an issue so other people don't waste time like I did.

Thanks for the repo!

**Comment by bfontaine** [comment]
I’m closing this since there is nothing actionable. Feel free to make a PR if you think the documentation could be improved.
