### ISSUE TITLE
Receiving multiple result sets via the simple protocol

### ISSUE THREAD

**Issue by jordanlewis** [jackc/pgx#756]
Thanks for your great work on pgx. We're trying to switch to using it more in some client code for https://github.com/cockroachdb/cockroach, as we like the way its Postgres-protocol abstractions are built.

There's one issue I'm running into, which is that it doesn't seem currently possible to run a query via the Simple protocol that returns multiple result sets. Am I missing something? If I look at the code in `Conn.Query`, there's a special case for the simple protocol that's run, but it doesn't seem to pay attention if there were multiple result sets returned by the server.

The `connRows` that's returned from `Conn.Query` in fact has a handle on the `multiResultReader` that could be queried to get the remaining result sets from the server, but as far as I can tell the `Query` abstraction isn't designed for multiple result sets and so that `multiResultReader` isn't really used in this context.

On the other hand, if we use the `ExecBatch` method on `Conn`, there's only the option of running via the extended protocol.

The difficulty is that the Simple protocol actually does let you send a batch in a single query, and it returns multiple result sets - and some things that we've made depend on this functionality. Ideally, the `ExecBatch` interface could allow you to pass in a single, compound query, and respect the `PreferSimpleProtocol` setting if you've asked for it. The reason that this is hard to work around is that in order to use the extended protocol in this case, we'd have to parse the query and split it up into component semicolon-separated queries on the client, which we'd rather not do.

----

Sorry for the long winded intro. I'd like to propose concretely that `ExecBatch` be able to send queries via the simple protocol. Is that something that you're amenable to? I'm happy to contribute a patch.

Cheers,
Jordan

**Comment by jackc** [comment]
I'm agree with adding some means of letting the simple protocol be used for multiple result sets. 

Extending `ExecBatch` is probably the best way to do that but I'm not sure. There are a few possible issues that come to mind.

1. The batch system has some expectations of knowing how many queries were queued and what they were.
2. The batch system relies on the implicit transactional nature of the extended query protocol. This means at the very least that simple queries couldn't be mixed with other queries.

Other options that come to mind:

1. A parallel system to the batch system solely for executing simple protocol / multiple query statements.
2. The batch system could internalize enough of a SQL parser to automatically split queries into individual statements. It wouldn't need to parse all of SQL -- just enough to ignore semicolons in quotes or comments. I suppose it would also need to handle splitting which arguments go to which queries.
3. Use `pgconn.Exec()` to send the query and build an adapter to convert a `MultiResultReader` into a `BatchResults`.
