### ISSUE TITLE
How to disable prepare statement on stdlib.AcquireConn(db) connection

### ISSUE THREAD

**Issue by themsay** [jackc/pgx#758]
Thanks for great work!

I just switched from pq to pgx library, but still using database/sql through stdlib not fully native pgx due to our code base.

But, I having difficult time with default prepared statement while using multi query. I wouldn't like to disable it by default.

Reading through the documentation I came across `QueryExOptions` per query option when used with `ExecEx()`, but it don't exist in `stdlib.AcquireConn(db)` connection.

Any idea how to disable prepare statement per-query using pgx `stdlib.AcquireConn(db)` or suggestion with code sample will be supper helpful?

**Comment by jackc** [comment]
First of all, be sure you are using and looking at the docs for v4. `ExecEx` doesn't exist any more.

The settings you want to look into are `Config.PreferSimpleProtocol` which can disable the prepared statements everywhere and passing `pgx.QuerySimpleProtocol(true)` as an argument to individual queries to choose on a per query basis.

**Comment by themsay** [comment]
@jackc thank you so kindly. I mess-up fulltime reading v3 doc, while using v4 your suggestion work great! I'll close the ticket now.

Thanks once again for assistance.
