### ISSUE TITLE
Does pgx support scanning into structs?

### ISSUE THREAD

**Issue by mrdulin** [jackc/pgx#760]
something like: https://godoc.org/github.com/jmoiron/sqlx#StructScan

And struct tags like this:

```go
type TenantModule struct {
	Id   string `db:"id"`
	Name string `db:"type"`
        Channels Channel `json:"channels"`
}
type Channel struct {
	Channels []string
}
```

Or this:

```go
type TenantModule struct {
	Id   string `sql:"id"`
	Name string `sql:"type"`
}
```

I didn't find any information on https://github.com/jackc/pgx/blob/master/query_test.go file and documentation.
There are only examples which scan into the basic data type like `int`, `float`

Please give an example of how to scan rows into a struct. Thanks

**Comment by jackc** [comment]
pgx does not have anything like sqlx. But you can use sqlx with pgx when pgx is used as a database/sql driver.

**Comment by mvrhov** [comment]
Also the [sqlc](https://github.com/kyleconroy/sqlc) in next version will do what you need albeit in a bit different way that you expect.

**Comment by georgysavva** [comment]
@mrdulin here is the library exactly for what you asked: https://github.com/georgysavva/scany
It's feature-rich and supports pgx native interface.

**Comment by omsec** [comment]
Well, well..this should really be part of the core, since its fundamentals. Yet another dependecy to a private person.

**Comment by BigBoulard** [comment]
maybe there ... https://github.com/randallmlough/pgxscan

**Comment by bfontaine** [comment]
See also [`pgx.RowToStructByPos`](https://pkg.go.dev/github.com/jackc/pgx/v5#RowToStructByPos).

**Comment by elllot** [comment]
In addition to the API @bfontaine pointed out, [pgx.RowToStructByName](https://pkg.go.dev/github.com/jackc/pgx/v5#RowToStructByName) is available in pgx v5.

**Comment by tamis-laan** [comment]
@elllot  How do I apply `pgx.RowToStructByName` onto a single row returned by `QueryRow`?

**Comment by elllot** [comment]
It's been a while since I was looking into this, but you could use a combination of `Query` &  `RowToAddrOfStructByName` (variant of `RowToStructByName`) for a single row:

```
// Supplied from somewhere.
var dbPool *pgxpool.Pool
rows, err := dbPool.Query(context.Background(), someQuery, ...someQueryArgs)
if err != nil {
  return nil, err
}

// Assumes the returned row only has a single hit. StructToFill is the target struct. 
p, err := pgx.CollectOneRow(rows, pgx.RowToAddrOfStructByName[StructToFill])
```

You can check the API definitions to see what the differences are between the API variants. I might be misremembering, but I remember there wasn't a way to use `QueryRow` with `RowToStructByName`.

**Comment by tamis-laan** [comment]
@elllot yup that's how I'm using it now, tried looking for a way to use a single row `QueryRow` but couldn't find any. Thanks for affirming.

**Comment by jackc** [comment]
@tamis-laan  

As mentioned by @elllot `Query` + `CollectOneRow` is the way in `v5`. But you can make it a little more concise. You can skip checking the error from `Query` and only check the error from `CollectOneRow`. When `Query` returns an error it always still returns a `Rows` with that error, and `CollectOneRow` will return that original error. e.g.

 ```go
// Supplied from somewhere.
var dbPool *pgxpool.Pool
rows, _ := dbPool.Query(context.Background(), someQuery, ...someQueryArgs)
// Assumes the returned row only has a single hit. StructToFill is the target struct. 
p, err := pgx.CollectOneRow(rows, pgx.RowToAddrOfStructByName[StructToFill])
if err != nil {
  return nil, err
}
```

Also, for an even higher level interface, check out [SelectRow](https://pkg.go.dev/github.com/jackc/pgxutil#SelectRow) from my personal pgx utility library.
