### ISSUE TITLE
Is there a way to use stdlib as a driver and it's public functions in the same package?

### ISSUE THREAD

**Issue by dosco** [jackc/pgx#762]
Say you have a package called `example` in this package there are two files `one.go` and `two.go`. 

1. In `one.go` you initialize an `sql.DB` connection using `stdlib` as the driver.
2. In `two.go` you make use of `stdlib.AcquireConn`.
3. You get `panic: sql: Register called twice for driver pgx`

It is not possible to do this relatively simple task. I feel calling `sql.Register` in an init function is a an idea that should have been called out earlier in go. I understand it is sort of the standard now. I feel people would much prefer just calling `sql.Register("pgx", pgxDriver)` over the magic of init functions.

**Comment by dosco** [comment]
The only solution I found was to extract out the `acquireConn` and `releaseConn` functions into a separate package.

```go
package stdutils

import (
	"context"
	"database/sql"
	"sync"
	"time"

	errors "golang.org/x/xerrors"

	"github.com/jackc/pgx/v4"
)

type ctxKey int

var ctxKeyFakeTx ctxKey = 0

var errNotPgx = errors.New("not pgx *sql.DB")

var (
	fakeTxMutex sync.Mutex
	fakeTxConns map[*pgx.Conn]*sql.Tx
)

func acquireConn(db *sql.DB) (*pgx.Conn, error) {
	var conn *pgx.Conn
	ctx := context.WithValue(context.Background(), ctxKeyFakeTx, &conn)
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	if conn == nil {
		if err := tx.Rollback(); err != nil {
			return nil, err
		}
		return nil, errNotPgx
	}

	fakeTxMutex.Lock()
	fakeTxConns[conn] = tx
	fakeTxMutex.Unlock()

	return conn, nil
}

func releaseConn(db *sql.DB, conn *pgx.Conn) error {
	var tx *sql.Tx
	var ok bool

	if conn.PgConn().IsBusy() || conn.PgConn().TxStatus() != 'I' {
		ctx, cancel := context.WithTimeout(context.Background(), time.Second)
		defer cancel()
		conn.Close(ctx)
	}

	fakeTxMutex.Lock()
	tx, ok = fakeTxConns[conn]
	if ok {
		delete(fakeTxConns, conn)
		fakeTxMutex.Unlock()
	} else {
		fakeTxMutex.Unlock()
		return errors.Errorf("can't release conn that is not acquired")
	}

	return tx.Rollback()
}
```

**Comment by jackc** [comment]
It works for me. See this example: https://github.com/jackc/pgx_issues/tree/master/pgx-762

If I had to guess, I would say that in one file you are importing `github.com/jackc/pgx/v4/stdlib` and in the other you are importing `github.com/jackc/pgx/stdlib`.

**Comment by dosco** [comment]
You're totally correct. After years of GO I tripped up on an auto import. I feel dumb i'll be closing this issue now and re-reading the docs on how `init` works 😄
