### ISSUE TITLE
ColumnTypes on a query of an empty table

### ISSUE THREAD

**Issue by johnnyb** [jackc/pgx#766]
I don't know if this is possible, but I am curious if it would be possible to get ColumnTypes on a query returning now rows.

The reason for this is that I'm writing a new ActiveRecord-like ORM, and I was wanting to use the standard database/sql interface as much as possible.  In any case, to do introspection on the database, I'm just doing "SELECT * FROM tablename LIMIT 1" and checking the resulting types.  However, if there are no rows, this gives nothing in the resulting ColumnTypes.

Anyway, I couldn't figure out whether this was a pgx problem or a database/sql problem, or where it would lie.  I'm happy to pitch in, but don't know exactly where to go.

**Comment by jackc** [comment]
It definitely is possible at the PostgreSQL wire protocol level. And it should work in both native pgx and database/sql but I haven't tried it. You might need to try to call `Next()` first though.

**Comment by neilotoole** [comment]
@jackc I see the same problem with an empty table, and calling `Next()` first does not help.

**Comment by jackc** [comment]
It should work without even calling `Next()` as of `v4.9.0`.

Example:

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v4"
)

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close(ctx)

	_, err = conn.Exec(ctx, "create temporary table pgx766(a text, b text, c text)")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create temporary table: %v\n", err)
		os.Exit(1)
	}

	rows, err := conn.Query(ctx, "select * from pgx766")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Query failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Println(len(rows.FieldDescriptions()), "columns")
	for _, fd := range rows.FieldDescriptions() {
		fmt.Println(string(fd.Name))
	}

	rows.Close()
	if rows.Err() != nil {
		fmt.Fprintf(os.Stderr, "rows.Err(): %v\n", rows.Err())
		os.Exit(1)
	}

}
```

Output:
```
3 columns
a
b
c
```
