### ISSUE TITLE
Cannot pass []byte to an int column

### ISSUE THREAD

**Issue by hgl** [jackc/pgx#767]
I'm using the stdlib package, and I can get the value of an int column out as `[]byte` like this:

```go
var id []byte
db.QueryRow("SELECT intCol FROM foo").Scan(&id)
```

But I cannot pass it back in
```go
db.QueryRow("SELECT 1 FROM foo WHERE intCol = $1", id)
```

It'll fail with `cannot convert [49] to Int4` if `intCol` contains integer 1.

Is this asymmetry intended?

If not, I'd expect the byte slice to be converted into a string and passed as literal to pg. Not suggesting pgx should follow lib/pq, but just for informational sake, this works in in lib/pq, and it   enables a data structure to easily use `[]byte` as integer based id, making it easier to port to uuid based id down the road for example.

**Comment by jackc** [comment]
To be honest I'm not sure how even the read example is working. The non-database/sql interface supports reading any value to a `[]byte`, but it would be the raw binary data which would be `[0 0 0 1]` not the string representation of the value. My guess is `database/sql` is doing a conversion itself.

As far as passing a `[]byte` as an argument for any type, I am reluctant to try to support that case. It introduces ambiguity regarding whether the `[]byte` contains an already formatted value or it needs to be converted to the underlying PostgreSQL type.

For your use case of a single Go type that can handle multiple PostgreSQL primary key types I would recommend using a type specifically for that purpose. (possibly `pgtype.GenericBinary` would work for you).

**Comment by hgl** [comment]
Makes sense, thanks for the tip.

**Comment by hgl** [comment]
@jackc sorry to resurrect, but it seems `pgtype.GenericBinary` can not handle multiple primary key types? I tried to scan an `int` column into a `pgtype.GenericBinary`, and it failed with `Scan error on column index 0, name "id": cannot scan int64`

**Comment by jackc** [comment]
Oh, right... I forgot one of the details of how the `database/sql` interface works. By the time it gets to Scan it already is an `int64`.

Hmmm... Well, if all you want is to round trip PKs regardless of their type I guess you could make a type that implements `Scan` and `Value` and all it does is store the value it is given in `Scan` in a `interface{}`.

**Comment by hgl** [comment]
That's a good tip. Thanks!
