### ISSUE TITLE
How to use github.com/sirupsen/logrus?

### ISSUE THREAD

**Issue by sevaho** [jackc/pgx#770]
Hi

I'm trying to make use of https://github.com/sirupsen/logrus but I don't fully grasp how your library and logrus connect.

I've searched and found https://github.com/rassakhatsky/logrus-pgx, but it is 3 years old and another dependency.

I found your adapter: https://godoc.org/github.com/jackc/pgx/log/logrusadapter and tried to work with it but can't seem to grasp how it should work with logrus. I see you need an entitiy of type 'FieldLogger' but my logrus instance is not of this type.

This FieldLogger instance has been changed in this commit: https://github.com/jackc/pgx/pull/340/files, but I don't see anything on logrus where I can get an instance of FieldType.

what I have:

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/log/logrusadapter"
	"github.com/jackc/pgx/v4/pgxpool"
	"github.com/sirupsen/logrus"
)

var db *pgxpool.Pool
var log = logrus.New()

func main() {
	poolConfig, err := pgxpool.ParseConfig(os.Getenv("DATABASE_URL"))
	if err != nil {
		fmt.Errorf("Unable to parse DATABASE_URL", "error", err)
		os.Exit(1)
	}

        // does not work just dummy code to show what I did
	poolConfig.ConnConfig.Logger = logrusadapter.NewLogger(logrus.FieldLogger)

	db, err = pgxpool.ConnectConfig(context.Background(), poolConfig)
	if err != nil {
		fmt.Errorf("Unable to create connection pool", "error", err)
		os.Exit(1)
	}
	defer db.Close()
}
```

Any ideas on how to hook up pgx with logrus?

**Comment by jackc** [comment]
I think Go module versioning is the issue.

```go
	"github.com/jackc/pgx/log/logrusadapter"
	"github.com/jackc/pgx/v4/pgxpool"
```

You're using v4 of pgx but getting the pre Go modules version of the log package.

**Comment by sevaho** [comment]
changing to

```
	"github.com/jackc/pgx/v4/log/logrusadapter"
```

Fixed the issue!

Thx!
