### ISSUE TITLE
Support StringArray?

### ISSUE THREAD

**Issue by hgl** [jackc/pgx#771]
I know `UntypedTextArray` and `TextArray` exist, but they are quite cumbersome to use. 

If there is a `type StringArray []string`, I could directly scan into a string slice like this:

```go
var strs []string
Scan((*pgtype.StringArray)(&strs))
```

With `UntypedTextArray`, I have to define a new variable and assign `.Elements` to `strs`. With `TextArray`, it will be even more verbose.

**Comment by jackc** [comment]
In the native pgx interface you can already scan directly to a `[]string`.

**Comment by hgl** [comment]
Thanks for the heads up, I'm using the stdlib though. Currently I'm still using `pq.StringArray`, Wish I could completely transition to pgx by eliminating the final lib/pq piece that I rely on.

**Comment by sashayakovtseva** [comment]
I am using stdlib as well, because sqlx works with `sql.DB`.
When doing `sqlx.Select` into a struct, selecting postgres array into []string fails with the following error: `unsupported Scan, storing driver.Value type string into type *[]string`.
`pgtype.TextArray` works, though it is not really convenient.

**Comment by nmccready** [comment]
Please add this somewhere.... maybe pgtype helpers?

```
import (
	. "github.com/jackc/pgtype"
)

type Strings []string

func (strings Strings) Array() TextArray {
	// this API for types is awful
	length := int32(len(strings))

	txtArray := TextArray{
		Elements:   []Text{},
		Dimensions: []ArrayDimension{{Length: length, LowerBound: 1}},
		Status:     Present,
	}

	for i := range strings {
		txtArray.Elements = append(txtArray.Elements, Text{
			String: strings[i],
			Status: Present,
		})
	}
	return txtArray
}
```

**Comment by tchap** [comment]
I am having the same issue just selecting int `[]int32` and getting `unsupported Scan, storing driver.Value type string into type *[]int32`. The OID being sent from Postgres seems to be `1007`, which is `Int4ArrayOID`. Not sure what I am doing wrong, it seems scanning into a Go slice simply does not work?

**Comment by tchap** [comment]
Oh, I am using `stdlib`, does that make any difference and why?

**Comment by jadeydi** [comment]
> In the native pgx interface you can already scan directly to a `[]string`.

var tags []string 
err := row.Scan(&tags)

I use native pgx interface but tags is empty. any example for that?

**Comment by bfontaine** [comment]
Is this 3-years-old issue still relevant today?

**Comment by CoreFloDev** [comment]
no `pgtype.Array[string]` does the job

**Comment by 0xShamil** [comment]
@CoreFloDev Could you kindly share a working example here? I have been facing this error and can't seem to figure it out.

I am trying the following, using `pgx` (`v5`) through `database/sql` (Go `1.21.3`):
```go
row := db.QueryRowContext(ctx, query)

var arn string
var resArray pgtype.Array[string]

if err := row.Scan(
    &arn,
    &resArray,
); err != nil {
    // ...
}
```
End up getting this error:
```
sql: Scan error on column index 2, name "resources": unsupported Scan, storing driver.Value type string into type *pgtype.Array[string]
```

The `resources` column is: `VARCHAR(128)[]`

**Comment by CoreFloDev** [comment]
I don't remember why it ended like this but after multiple refactor my code doesn't use `pgtype.Array[string]` anymore and the column type switched to `text[] NOT NULL DEFAULT '{}'::text[]`.

With those changes, you can directly use a go []string

**Comment by 0xShamil** [comment]
Are you using the `pgx` directly or through the `database/sql` ?

**Comment by CoreFloDev** [comment]
I am using it directly

**Comment by andrerav** [comment]
pgtype.Array[string] does not work with text[] when using GORM.

**Comment by davenewza** [comment]
Shouldn't [this function](https://github.com/jackc/pgx/blob/78b22c3d2f2aa4029e7b3a8b3062fc656fb34c2b/stdlib/sql.go#L665) also support `pgtype.TextArrayOID` so that we can scan to a `[]map[string]any`?

**Comment by ringerc** [comment]
`pgtype.TextArray` no longer exists in v5.

Trying to scan with a `sql.DB` into a `ptype.Array[string]` or `pgtype.FlatArray[string]` both fail with `unsupported Scan, storing driver.Value type string into type *pgtype.Array[string]` and `unsupported Scan, storing driver.Value type string into type *pgtype.FlatArray[string]` respectively, when scanning a `text[]` column from a query.

**Comment by ringerc** [comment]
`pgtype.TextArray` no longer exists in v5.

Trying to scan with a `sql.DB` into a `ptype.Array[string]` or `pgtype.FlatArray[string]` both fail with `unsupported Scan, storing driver.Value type string into type *pgtype.Array[string]` and `unsupported Scan, storing driver.Value type string into type *pgtype.FlatArray[string]` respectively, when scanning a `text[]` column from a query.

The solution is to use `pgtype.NewMap()`'s `SQLScanner(...)`; to adapt the example given above, one would:

```
import (
  _ "github.com/jackc/pgx/v5/stdlib"
  "github.com/jackc/pgx/v5/pgtype"
)

func something(...) {
  row := db.QueryRowContext(ctx, query)

  var arn string
  var resArray pgtype.Array[string]

  m := pgtype.NewMap()
  if err := row.Scan(
      &arn,
      m.SQLScanner(&resArray),
  ); err != nil {
      // ...
  }
}
```

This was confusing to figure out because the godoc for pgx/pgtype is for a very old version; it's necessary to ensure you're looking at pgx/v5/pgtype and pgx/v5/stdlib:

* https://pkg.go.dev/github.com/jackc/pgx/v5/stdlib
* https://pkg.go.dev/github.com/jackc/pgx/v5/pgtype#Array

**Comment by DSkrzypiec** [comment]
> `pgtype.TextArray` no longer exists in v5.
> 
> Trying to scan with a `sql.DB` into a `ptype.Array[string]` or `pgtype.FlatArray[string]` both fail with `unsupported Scan, storing driver.Value type string into type *pgtype.Array[string]` and `unsupported Scan, storing driver.Value type string into type *pgtype.FlatArray[string]` respectively, when scanning a `text[]` column from a query.
> 
> The solution is to use `pgtype.NewMap()`'s `SQLScanner(...)`; to adapt the example given above, one would:
> 
> ```
> import (
>   _ "github.com/jackc/pgx/v5/stdlib"
>   "github.com/jackc/pgx/v5/pgtype"
> )
> 
> func something(...) {
>   row := db.QueryRowContext(ctx, query)
> 
>   var arn string
>   var resArray pgtype.Array[string]
> 
>   m := pgtype.NewMap()
>   if err := row.Scan(
>       &arn,
>       m.SQLScanner(&resArray),
>   ); err != nil {
>       // ...
>   }
> }
> ```
> 
> This was confusing to figure out because the godoc for pgx/pgtype is for a very old version; it's necessary to ensure you're looking at pgx/v5/pgtype and pgx/v5/stdlib:
> 
> * https://pkg.go.dev/github.com/jackc/pgx/v5/stdlib
> * https://pkg.go.dev/github.com/jackc/pgx/v5/pgtype#Array

Thanks mate, that saved me a lot of time! I was a bit confused by pgtype docs version also...

**Comment by alexeightsix** [comment]
> m.SQLScanner(&resArray)

Ty this worked
