### ISSUE TITLE
ERROR: bind message has 2 result formats but query has 1 columns

### ISSUE THREAD

**Issue by goku321** [jackc/pgx#773]
I get this error when using `pgx` with `database/sql` or `sqlx`:
`pgx.PgError(pgx.PgError{Severity:"ERROR", Code:"08P01", Message:"bind message has 2 result formats but query has 1 columns", Detail:"", Hint:"", Position:0, InternalPosition:0, InternalQuery:"", Where:"", SchemaName:"", TableName:"", ColumnName:"", DataTypeName:"", ConstraintName:"", File:"pquery.c", Line:643, Routine:"PortalSetResultFormat"})`

The thing that's confusing me is that it just works fine sometimes.

**Comment by jackc** [comment]
Do you code that reproduces this issue? Also, I think that error message is from pgx `v3`. Probably want to use `v4`.

**Comment by goku321** [comment]
I've posted it here: https://github.com/jmoiron/sqlx/issues/633#issuecomment-644537215

BTW, I changed my import from `github.com/jackc/pgx/stdlib` to `github.com/jackc/pgx/v4/stdlib` and I don't see the above error anymore(sorry, my mistake) but the tests are running slow as compared to when I use `lib/pq`. With `lib/pq` my tests run in half the time as compared to `pgx`. I'm using both of these drivers with `database/sql`. Is there anything I can do to improve the performance?

**Comment by jackc** [comment]
`pgx`with `stdlib` should be as fast or faster than `lib/pq`. Do you have a benchmark that compares the two?

**Comment by goku321** [comment]
I just did a benchmark on a single db method and there's almost no difference(`pgx` was a bit faster). Need to do more comprehensive benchmark with multiple db methods running concurrently.

**Comment by goku321** [comment]
Hi @jackc I've done a benchmark with `pgx` for a single query running it 1 million times. It takes around 20 minutes. I get the same results with `sqlx + lib/pq`. Benchmark was done on an EC2 instance and the database is hosted on citus.

Here's the code that executes the query: [code](https://github.com/goku321/golang/blob/d62a41d6a450866abe22785dd92dac95ff1bdf34/exercises/database/prepared-statement/preparedstatement.go#L76)
Here's the benchmark code: [Benchmark](https://github.com/goku321/golang/blob/d62a41d6a450866abe22785dd92dac95ff1bdf34/exercises/database/prepared-statement/preparedstatement_test.go#L38)
CPU profile binary for pgx: [pgx cpu profile](https://github.com/goku321/golang/blob/master/exercises/database/prepared-statement/cpu_pgx_1000000.out)
CPU profile binary for `sqlx + lib/pq`: [lib/pq cpu profile](https://github.com/goku321/golang/blob/master/exercises/database/prepared-statement/cpu_nocache_1000000.out)

Also, the query plan says that it will be a sequential scan and the table has around 0.1 million rows.
Any suggestions on improving the performance would be helpful.

**Comment by jackc** [comment]
Based on your benchmark and the environment you are running it in, very similar performance between `lib/pq` and `pgx` is to be expected for the following reasons:

`pgx` is usually faster at processing result rows. But with only one result row this advantage is minimal.

`database/sql` adds a significant amount of overhead. Under many cases this will erase the advantage `pgx` has in its native interface.

But most significantly, with only one result row the driver processing time is insignificant relative to network latency and server processing time. In my benchmarks I can run a simple select where the application is on the same host as the DB in ~20μs. But the same query run on with the application server and database in the same data center takes ~170μs. So I strongly suspect your benchmark is is dominated by network latency.

**Comment by goku321** [comment]
Thanks for the valuable insight and explanation. I really appreciate your time and efforts.
