### ISSUE TITLE
Context only possible in Windows

### ISSUE THREAD

**Issue by AlexanderKAdams** [jackc/pgx#774]
While using pgx on Windows, I have no issues using the library as the documentation instructs with context.Background(). However, when using the library on either a Mac or Ubuntu 18.04 machine, pgx no longer accepts context. As well, there seem to be other discrepencies, such as pgx.ParseConfig not being found. When importing pgx, I noticed it says "v3.6.2+incompatible," and can't seem to import any later version. I am running go 1.14 on all machines.

**Comment by jackc** [comment]
It sounds like you are importing `v3` where it isn't working. Check your import statements for the `/v4`

**Comment by AlexanderKAdams** [comment]
Ah, I was trying /tree/v4 instead of /v4. Just v4 in the import works fine, thanks! Is there any reason why import github.com/jackc/pgx doesn't default to 4?

**Comment by jackc** [comment]
Go Modules encourages / requires that incompatible versions have different import paths. v3 predated Go modules so it still has the base URL.
