### ISSUE TITLE
struct with Scanner interface: Scan not called

### ISSUE THREAD

**Issue by azhang** [jackc/pgx#777]
I have a struct `Pair` that is serialized/deserialized as `text` from the db.

```golang
func (p *Pair) Value() (driver.Value, error) {
	log.Info("Pair: Value() called")
	return driver.Value(p.String()), nil
}

func (p *Pair) Scan(src interface{}) error {
	log.Fatal("Pair: Scan() called")
	switch src.(type) {
	case string:
		*p = NewPairFromString(src.(string))
	case []byte:
		*p = NewPairFromString(string(src.([]byte)))
	default:
		return errors.New("Incompatible type for Pair")
	}
	return nil
}
```

`Value` is called successfully when it's written, but `Scan` is never called when it's read. Is this expected behavior? 

Traced function calls:

`*Text AssignTo`
-> `GetAssignToDstType`, where `dstVal.Kind() == reflect.Struct` isn't handled

https://github.com/jackc/pgtype/blob/41a185b6112f3e3a1d0aa867d766f8f6c2db2af2/convert.go#L395-L434

**Comment by azhang** [comment]
oh, I see that the following was added to the readme recently. Is this the preferred interface? In any case, I would think `Scan` would be called as a fallback to keep backwards compatibility?

https://github.com/jackc/pgx/blob/173227a6e314f2691e1fc4de04152a45498e07c0/doc.go#L168-L202

**Comment by azhang** [comment]
Ah I see what's going on. Inside `ConnInfo.PlanScan`,

https://github.com/jackc/pgtype/blob/41a185b6112f3e3a1d0aa867d766f8f6c2db2af2/pgtype.go#L796-L819

scanPlanReflection{} is never reached since `dt` will always be defined for the `text` type. 

This would be fixed if the functionality inside scanPlanReflection.Scan is implemented for ConnInfo.PlanScan.

Not sure if I should move this issue to https://github.com/jackc/pgtype because I think this is specific to when pgx is used in conjunction with pgtype

**Comment by jackc** [comment]
But if `dt` is defined it shouldn't https://github.com/jackc/pgtype/blob/41a185b6112f3e3a1d0aa867d766f8f6c2db2af2/pgtype.go#L809-L811 handle implementors of `sql.Scanner`?

Do you have a standalone case that can reproduce this?

**Comment by azhang** [comment]
You are correct in that it would handle implementators of sql.Scanner, but only if `dst = *MyStruct` rather than `dst = **MyStruct`.

```
		if _, ok := dst.(sql.Scanner); ok {
			return (*scanPlanDataTypeSQLScanner)(dt)
		}
```

If I deref it and set `dst = *MyStruct`, the subsequent `scanPlan.Scan()` call uses ` **MyStruct` as the `dst` arg again and fails again at 
https://github.com/jackc/pgtype/blob/41a185b6112f3e3a1d0aa867d766f8f6c2db2af2/pgtype.go#L523

`scanPlanReflection.Scan` solves this by dereferencing the **MyStruct into *MyStruct, and wrapping the `plan.Scan` using the deref'ed dst.

Local changes to make it work on my end: https://github.com/azhang/pgtype/commit/2f56df469e2d4ac1b315ed8c4a981dcaef8dfdd8

I unfortunately do not have a standalone case yet but will try to create one if the explanation isn't enough

**Comment by jackc** [comment]
> You are correct in that it would handle implementators of sql.Scanner, but only if dst = *MyStruct rather than dst = **MyStruct.

Are you using `database/sql` mode or pgx native? I'm not sure if it is possible to properly support what you want in `database/sql`.  But if you are using native pgx you should implement the `Encode(Text|Binary)` and `Decode(Text|Binary)` methods instead.

Still might be worth supporting the allocation of Scanner implementing structs, but I think it would need to go somewhere else. azhang/pgtype@2f56df4 means every call of `PlanScan` will pay the cost of testing for the `database/sql` interface. But in pgx native, that is the least likely thing to scan into.

**Comment by azhang** [comment]
>  every call of PlanScan will pay the cost of testing for the database/sql interface

Ah that's a good point that I didn't realize! I'm using pgx native so I'll look into implementing the Encode/Decode methods instead. 

Thanks for the help!
