### ISSUE TITLE
Is it optional to release connection after using it in pgxpool?

### ISSUE THREAD

**Issue by sangholim0** [jackc/pgx#778]
In `pgxpool.Exec`, I see that connection gets released after it is used. `defer c.Release()` is invoked.

https://github.com/jackc/pgx/blob/master/pgxpool/pool.go#L398

However, in `pgxpool.QueryRow`, I do not see that happening, and `c.Release()` is not getting called.

https://github.com/jackc/pgx/blob/master/pgxpool/pool.go#L418

`pgxpool.Query` also releases the connections, but `pgxpool.SendBatch` does not.

I was wondering if there is any reason why `QueryRow` wouldn't be releasing connection after acquiring/using it?

**Comment by jackc** [comment]
It is not optional, but responsibility is passed to other code. For example, `pgxpool.Rows` releases the connection after it is closed. https://github.com/jackc/pgx/blob/1f68908da6eaf0b27009ab43f1127970303ba1fd/pgxpool/rows.go#L37

**Comment by sangholim0** [comment]
I see, thanks.
