### ISSUE TITLE
Is it possible to use  pgx as drop in replacement of libpq ?

### ISSUE THREAD

**Issue by acnologia000** [jackc/pgx#786]

**Comment by DavidArchibald** [comment]
According to the [README](https://github.com/jackc/pgx/tree/11428bbc02a720cf612d528ae07ab7aa8422ba18#compatibility-with-databasesql) pgx has full support for `database/sql` and should be possible to be used as a drop in replacement. It is also listed under the [SQLDrivers wiki](https://github.com/golang/go/wiki/SQLDrivers#drivers) that the [`database/sql` documentation](https://golang.org/pkg/database/sql/) references. You can read up more at the resources linked.
