### ISSUE TITLE
sqlx compatibility issue with string slices

### ISSUE THREAD

**Issue by SecretGibbon** [jackc/pgx#790]
Hello, i have migrated our application from **pq** to **pgx** pretty much successfully but I still cannot solve one issue, when calling (simplified)

```
arg := []string{"test"}
db.Select(&data, `
SELECT a.*, y.x
FROM table_a a
LEFT JOIN LATERAL (
    SELECT JSON_AGG(JSON_BUILD_OBJECT(...)) "x",
           (ARRAY_AGG(DISTINCT LOWER(b.code)) @> lower($1::text)::text[] OR $1::text[] IS NULL) AS contains_searched_b
    FROM table_b b
    ) "y" ON true
WHERE ($1::text[] IS NULL OR contains_searched_b)`, arg)
```

but i keep getting error "sql: converting argument $1 type: unsupported type []string, a slice of string"

what can i do? With **pq** it worked just fine. I have tried using **pgtype.TextArray** but with no success.

connection is created as follows:
`conn, err := sqlx.Connect("pgx", config.DBConn)`

**Comment by jackc** [comment]
I don't know about sqlx, but I just implemented a change that should allow any argument type that pgx native supports to work through database/sql. e.g. passing a `[]string`. Try this on master and see if it works.

**Comment by SecretGibbon** [comment]
> I don't know about sqlx, but I just implemented a change that should allow any argument type that pgx native supports to work through database/sql. e.g. passing a `[]string`. Try this on master and see if it works.

Thank you very much, I will try it on Monday and report back. Thumbs up for great response time!
And very good job on the library!

**Comment by SecretGibbon** [comment]
Ok, i have tried it right away :)

i removed github.com/jackc/pgx@v3.6.2 from go.mod and run "go get github.com/jackc/pgx@master"
it downloaded (according to go mod): github.com/jackc/pgx v3.5.1-0.20190831180101-c72417a9584c+incompatible
which is kind of wierd.
I have tried it at it still gives the same error.

Was my approach wrong?
I can try downloading the files directly from github but I would rather use something via go.mod :)

**Comment by SecretGibbon** [comment]
No the command did not get the latest version, in the downloaded files there is no "TestConnSimpleSlicePassThrough" which was added in the latest commit.

**Comment by SecretGibbon** [comment]
I got it, it has to be pgx/v4 for newest version. Sorry for spamming, if anyone wonders its `go get github.com/jackc/pgx/v4@4ebf1d2e0baa87ab6afbbf6a0947c9fb8a30e9d4` for this current version

**Comment by SecretGibbon** [comment]
@jackc Ok, i have tried the newest version, and it does not give the same error but another one:
```
cannot convert [test] to Text:
  github.com/jackc/pgtype.(*Text).Set
    .../github.com/jackc/pgtype@v1.4.1/text.go:47
```

the pgtype lib in v4 is downloaded separately as version 1.4.1
i was using it in previous version to get mapping of array of IDs as []int64, because without **pgtype.NumericArray** i was getting it as json in []uint8

**Comment by jackc** [comment]
```go
package main

import (
	"database/sql"
	"log"

	_ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
	db, err := sql.Open("pgx", "")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	var n int64
	err = db.QueryRow("select cardinality($1::text[])", []string{"a", "b", "c"}).Scan(&n)
	if err != nil {
		log.Fatal(err)
	}

	log.Println(n)
}
```

Output: 

```
jack@glados ~/dev/pgx_issues/pgx-790 ±master⚡ » go run main.go
2020/07/18 18:43:35 3
```

**Comment by SecretGibbon** [comment]
I hoped it will work with SQLX taht we are currently using, I will try rewriting some part to direct use of QueryRow and see how it goes

**Comment by SecretGibbon** [comment]
I am sorry for being such a chore...

I have tried (still using sqlx) to encapsulate the []string into pgtype.textArray and it seems like that the object is created successfully
![image](https://user-images.githubusercontent.com/14081335/87921876-7622c600-ca7b-11ea-8d21-1e2a8defc5b4.png)

but the DB then returns `invalid byte sequence for encoding "UTF8": 0x00`
it seems like it gives the ending 0x00 of the string to the DB as well

**Comment by SecretGibbon** [comment]
Ok so the error was (expectedly) on my side. There was aggregation function inside the select taht was converting the []string array to ::text. I fixed that and it works just fine with sqlx. I have just one more question @jackc :
I am mapping result to structure that contains *[]int64 where is stored a list of IDs that is pulled by lateral join using `SELECT ARRAY_AGG(DISTINCT table.id) AS table_ids` with pq this worked and the result could be mapped to []int64 slice inside of result structure. With pgx it is not working with error `unsupported Scan, storing driver.Value type int64 into type *[]int64`. Is there a simpler way to do this than using pgtype.NumericArray?
Because NumericArray has one unfortunate feature, when it is not specifically set to nil (via **Set(nil)**) it does not count as nil and cannnot be assigned do *[]int64, and if i use *pgtype.NumericArray it panics on nil pointer dereference

I am sorry if I am asking stupid questions. But

**Comment by SecretGibbon** [comment]
Also unlike pq.Int64Array it is not unmarshalled automatically from json to field of pgtype.NumericArray

**Comment by jackc** [comment]
That I don't know. Passing slices in was made possible by implementing `CheckNamedValue` in a way which tells `database/sql` to pass all parameters through unmodified to pgx.

But I don't know of a way to do that for Scan. Presumably if it works in lib/pq there is a way to do it... but I don't know what it is.

**Comment by SecretGibbon** [comment]
Thank you very much for responses and bearing with me. If i find the way around or how to implement it i will let you know.
I will close this issue since the original problem as solved.

Thank you!!
