### ISSUE TITLE
Getting postgres error codes

### ISSUE THREAD

**Issue by psankar** [jackc/pgx#792]
This feature probably already exists but I could not find in the documentation or via google and so asking this here.

I want a way to get the postgres error codes. For example:

```
conn, _ := pgx.Connect(context.Background(), dbURL)

value := "example"
_, _ := conn.Exec ("INSERT INTO table (uniqueKey) VALUES ($1)", value)
_, err := conn.Exec("INSERT INTO table (uniqueKey) VALUES ($1)", value)
if err != nil {
   // How  to find out that the error is because of a unique constraint violation here from err ?
}
```

**Comment by jackc** [comment]
https://github.com/jackc/pgx/wiki/Error-Handling and https://github.com/jackc/pgerrcode/ for Go constants for the SQLSTATE error codes.

**Comment by psankar** [comment]
Thank you a lot @jackc . I will close the issue.
