### ISSUE TITLE
Doc for composite type handling

### ISSUE THREAD

**Issue by yasushi-saito** [jackc/pgx#793]
The doc for pgx suggests using `pgtype.Record` to decode composite types. 
But the custom_composite_test.go in pgtype uses `CompositeFields`. 
Am I correct in understanding that CompositeFields is the canonical way to handle composite types? I'm happy to create a pull request to fix the pgx doc if so.

**Comment by jackc** [comment]
I guess the docs are a little out of date / incomplete.

`pgtype.Record` is the default decoder for anonymous composites. e.g. The `record` type that is returned from the `row()` constructor.

`pgtype.CompositeFields` can decode anonymous composites as well as named composite types. It also has some ability to encode composite types. There's nothing wrong with `pgtype.Record`, but I suppose `pgtype.CompositeFields` is basically a superset of its functionality so it wouldn't hurt to prefer its use.

But for named composite types the best solution is registering a `pgtype.CompositeType`.
