### ISSUE TITLE
Defer Close connection vs manual Close connection

### ISSUE THREAD

**Issue by RobertoOrtis** [jackc/pgx#796]
Hello,

I am trying to use

```
defer conn.Close(context.Background())
```

but the connection is closing before I expected it to.

So, is it ok to manually close it `conn.Close(context.Background())` after I finish all the needed queries. or should I still use `defer` ?

**Comment by jackc** [comment]
You should use `defer` to ensure it gets cleaned up even if there is a panic. But you are free to manually close the connection as well. Calling `Close` on an already closed connection is safe.

But the connection closing before you expect -- that should probably be investigated -- not papered over.

**Comment by RobertoOrtis** [comment]
Yes, I would also like doing it with defer...

This is the actual code I am using at the moment:

```
func (db Connection) User(boolReturn ...bool) (u model.User, err error) {
	if len(boolReturn) > 0 && boolReturn[0] == false {
		return u, nil
	}

	updatedAtNull := pgtype.Timestamptz{}

	err = db.row.Scan(&u.ID, &u.Name, &u.Age, &u.Active, &u.CreatedAt, &updatedAtNull)

	db.conn.Close(context.Background())

	if err != nil {
		return
	}
	u.UpdatedAt = u.CreatedAt
	return u, nil
}

func (db Connection) Create(data []interface{}, query string) Connection {
	dbcon := getConnection()
	r := dbcon.QueryRow(context.Background(), query, data...)

	db.row = r
	db.conn = dbcon
	
	return db
}
```

Where should I place `defer dbcon.Close(context.Background())`?

**Comment by jackc** [comment]
To be honest, I do not understand how that code is organized at all.

In most situations, you should use a connection pool that has the life of your program.

If you are manually managing a connection's lifetime then generally the defer close would exist at the scope as the connect.

e.g.

```go
func dosomething(...) {
  conn, err := pgx.Connect(...)
  // handle err
  defer conn.Close(...)

  // Do your stuff with conn here

  // conn is closed when function exits
}
```
