### ISSUE TITLE
Do I need to acquire conn from pgxpool for consequent queries?

### ISSUE THREAD

**Issue by a1tus** [jackc/pgx#797]
Hello.

I'm trying to use pgxpool that is connecting to pgbouncer (and it works).
In app code I have 1 base query and 2 consequent ones that are using results of previous ones (only reads).
Smth like that:

```
// pool is *pgxpool.Pool
a, _ := pool.Query(context.Background(), "SELECT ...")
b, _ := pool.Query(context.Background(), "SELECT ...", a)
c, _ := pool.Query(context.Background(), "SELECT ...", b)
// some processing
```

... which gives us 3 calls of `Acquire/Release` under the hood.

Is it better to get conn via `pool.Acquire` manually and call `Query` from it?
It seems like I should but I can't see performance impact when benching on local computer.

And one more thing that I'm not quite sure about. Are these `Query` calls initialize goroutines that are sleeping while waiting for pgbouncer answer? Or they are just executed synchronously and I can try to `go` them manually for expensive queries in order not to block thread?

Thank you.

**Comment by jackc** [comment]
There are no background goroutines. The reads can occur when you call `rows.Next()` or `rows.Close()`.

You can send multiple queries through pgxpool and interleave the reads on the returned `pgx.Rows`. It will use a different underlying connection for each simultaneous query. But if there are dependencies between them you would want to ensure that the earlier queries had completed before sending the dependent one(s).

But your best option is probably to use [SendBatch](https://pkg.go.dev/github.com/jackc/pgx/v4?tab=doc#Conn.SendBatch) to send all queries in one network round trip on one connection.

**Comment by a1tus** [comment]
I've simplified my example too much I suppose =)
I have 3 functions that make `pool.Query`, then for-scan rows and return some data (that is used to filter next query).
So they can only be executed consequently.
In this case I think I can save some resources if use 1 `acquire` call for all of them?

And one more thing if you don't mind. My service creates pgxpool before starting listening for http connections and lives until terminated. Do I need to `defer pool.close()` or smth like that (as I said we use pgbouncer)?

**Comment by jackc** [comment]
> In this case I think I can save some resources if use 1 acquire call for all of them?

Yes. But typically the gain would be minuscule.

> My service creates pgxpool before starting listening for http connections and lives until terminated. Do I need to defer pool.close()

It doesn't matter on the Go side. But it might matter to the server. I'm not sure how quickly PgBouncer or PostgreSQL server would notice the dead connections. A `Close()` will explicitly terminate all the connections.

**Comment by a1tus** [comment]
Thank you! Great lib btw 👍
