### ISSUE TITLE
Question || Purpose of Context in DB queries/connection

### ISSUE THREAD

**Issue by Sahil624** [jackc/pgx#799]
Hi,

Sorry I'm new to go lang and just started using this library. 
I just could not understand purpose of context in all functions.

Ex :- 
``` go
pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
```

And almost every function.

PS :- Sorry for raising question is issue section.

**Comment by jackc** [comment]
The primary purpose of context use in pgx is canceling a network operation.

For example, when trying to connect to the PostgreSQL database the network connection could fail in such a way that the connect hangs indefinitely. Context can be used to put a time limit on how long to wait.

**Comment by ceoshikhar** [comment]
Hey Jack!

I'm new to Context as well. Do we have to pass new instance of context every time? What if we create one global context.Background() while creating a connection Pool and re-use that context everywhere else, would that work the same?

Sorry if this is very noob question and not the right place to ask.

**Comment by jackc** [comment]
@ceoshikhar Using context.Background() everywhere would work, you just wouldn't be able to cancel or timeout queries with the context. That is usually fine for things like CLI tools, but if you are working on the web you would typically pass in the request context.
