### ISSUE TITLE
[potential bug] invalid pg(decimal) -> golang(big.Int) conversion 

### ISSUE THREAD

**Issue by HaySayCheese** [jackc/pgx#801]
## The problem
Seems like internal implementation of the decimal -> big.Int is broken and returns invalid values on the go's side.

## How to reproduce?
1. Create the schema

```sql
drop table transactions cascade;
create table if not exists transactions (
    id bigserial primary key,
    constraint id_gte_zero check (id >= 0),

    source_amount decimal not null,
    constraint source_amount_gt_zero
        check (source_amount > 0)
);
```

2. Insert test data
```sql
insert into transactions (source_amount) values (10);
```

3. Fetch data
```
query := fmt.Sprintf("SELECT id, source_amount")
rows, err := h.connection.Query(context.Background(), query)
if err != nil {
	return
}
```

4. Map the data
```
values, err := rows.Values()

// ...
```

## What is expected to be?
`values[0]` must contain `*big.Int` set to 10.

## What is the exact result?
`values[0]` contains big.Int that is set to 1.

## Any proofs?
![image](https://user-images.githubusercontent.com/528635/89185057-478c0b80-d5a2-11ea-899b-edeae0824ad4.png)

![image](https://user-images.githubusercontent.com/528635/89185548-1829ce80-d5a3-11ea-9595-404fe2a12436.png)

**Comment by jackc** [comment]
You missed the `Exp` field. `Int` must be raised to `Exp`. Sadly, Go does not have a builtin `decimal` type so pgx returns the result in this less than ideal form. However, pgx does have support for https://github.com/shopspring/decimal. It's in a separate package to avoid a 3rd party dependency. See https://github.com/jackc/pgx/wiki/Numeric-and-decimal-support.

**Comment by HaySayCheese** [comment]
Oh, thanks a lot for the clarification.
Another solution that I was found is to use `numeric` type on a postgres's side, specify the precision and take care of it on a go's side. Not too perfect, but works fine. 

Thanks again for the links.
