### ISSUE TITLE
how to use libpgx as standard sql/db driver as using pgx drivername is giving import error on runtime ( forgot to import driver ?)

### ISSUE THREAD

**Issue by acnologia000** [jackc/pgx#804]
am using pgx through sql/db package as drop in replacement but i am not able find how to do so 
i am avoiding using it as pgx connection mode for obvious reasons ( coming here from libpq)

connection, err := sql.Open("pgx", "database=dexchange username=postgres password=postgres") 
//pgx.Connect(context.Background(), "postgresql://localhost/dexchange?user=postgres&password=postgres")

**Comment by jackc** [comment]
Have you seen the getting started guide on the wiki?

https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql

**Comment by acnologia000** [comment]
> 
> 
> Have you seen the getting started guide on the wiki?
> 
> https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql
 
please add wiki link to readme.md as github wiki link is hard to notive ( obviously i missed it , kind of sorry for that too ) 
and my code editor is reporting when using it in pgx connection mode 
![image](https://user-images.githubusercontent.com/36767190/89567906-1a5c8900-d840-11ea-81bf-ad9406c8f6b8.png)

also , pgx through sql.db is thread safe right ( goroutine safe)
