### ISSUE TITLE
Cannot use (pgx.Identifier literal) (value of type pgx.Identifier) as pgx.Identifier value in argument to IDB.CopyFrom

### ISSUE THREAD

**Issue by GAZ082** [jackc/pgx#805]
Hi. I opened a stackoverflow about this but did not have much luck. With a code similar to this:

```go
func DoStuff(input []Resource) {
    rowsToken := [][]interface{}{}
    for _, data := range input {
        rowsToken = append(rowsToken, []interface{}{data.TokenID, data.Class})
    }
    _, err := IDB.CopyFrom(ctx, pgx.Identifier{"someTable"},
        []string{"id", "localization_id"}, pgx.CopyFromRows(rowsToken))
    tool.CheckError(err, "info")
}
```

I'm getting:

`Cannot use (pgx.Identifier literal) (value of type pgx.Identifier) as pgx.Identifier value in argument to IDB.CopyFrom`

A guy in SO suggested something about dependencies. I have two packages in the same project using PGX and in package A the CopyFrom is working with no issues but package B is doing this. I'm puzzled! Any tips?

Thanks!

**Comment by jackc** [comment]
Possibly both `github.com/jackc/pgx` and `github.com/jackc/pgx/v4` are imported and the mismatch is which package `pgx.Identifier` is coming from.

**Comment by GAZ082** [comment]
> Possibly both `github.com/jackc/pgx` and `github.com/jackc/pgx/v4` are imported and the mismatch is which package `pgx.Identifier` is coming from.

I think that's the case. I'll check in a few hours and report back. Thanks!
