### ISSUE TITLE
Cannot determine the type of Point from the PostGIS plugin

### ISSUE THREAD

**Issue by virtumonde** [jackc/pgx#806]
I am using Go with the pgx library to query a Postgres database with the PostGIS plugin but I am not able to determine the type of Point from PostGIS, or better said, into what type does it fit in Golang.

Code:
```
	rows, err := db.conn.Query(context.Background(), "select * from point")
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		var uuid string
		var coordinate []float32
		err = rows.Scan(&uuid, &coordinate)
		if err != nil {
			log.Println(uuid)
			log.Println(coordinate)
		}
	}

	return rows.Err()
```

As expected, I am getting the following error:
```
can't scan into dest[1]: cannot assign &{{2 2} 2} to *[]float32
```
The error occurs because coordinate is a PostGIS Point, not an array of float32. What kind of type can it be attributed to in Go?

**Comment by virtumonde** [comment]
I have used both postgis.Point type from cridenour/go-postgis and the Point from pgx docs but it doesn't work. In the case of the type from the documentation (the Point struct), it says "can't scan into dest[1]: cannot assign &{{2 2} 2} to *main.Point"

**Comment by jackc** [comment]
AFAIK, the PostgreSQL point type and the PostGIS point types are separate types. pgx has built in support for the PostgreSQL point type, but not the PostGIS type.

The error message you are seeing indicates that pgx was able to understand and decode the value from PostgreSQL but was unable to translate it into the type you wanted to scan into. I don't think you would see that error with the PostGIS type. Perhaps the database type is erroneously a PostgreSQL point.

**Comment by virtumonde** [comment]
@jackc, yes indeed it was a native Postgres type. I did not know it has points by default. I used your type for the native Postgres point and everything worked.
