### ISSUE TITLE
How to format the use of containment operator (@>)

### ISSUE THREAD

**Issue by phtdacosta** [jackc/pgx#807]
Hello, first of all thank you @jackc for this prime work. Wish you all the best in this life for the effort you put in this library.

I am trying to write a SQL statement where I make use of @> operator to check if a jsonb column contains another json but I am a bit lost on how to format it properly. For now I am use as follows:

```
	err := pg.Pool.QueryRow(
		context.Background(),
		`SELECT supplier FROM suppliers WHERE alias = $1 AND data @> '{"personnel":{"carriers":[{"identifier": $2, "mobile": $3}]}}'`,
		carrier.Alias, carrier.Identifier, carrier.Mobile).Scan(&supplier)
```

but it is not working at all. I digged Google for any site with tutorials but had no success, so I came here. Sorry for opening an issue on that, that seems to be very shallow, but I would love if someone could help me on that. Thanks a lot in advance!

**Comment by jackc** [comment]
`$2` and `$3` are inside of a string literal. They are not being treated as bind variables. You can either pass in a single value for the entire json value such as a `map[string]interface{}` or use `json(b)_build_object` to build it from your separate bind variables.

**Comment by phtdacosta** [comment]
Thank you for the help @jackc. Great advice that I will follow next time I need. Could you implement this "pay me a coffee" in your project page? I would gladly contribute with some bucks as a way to support your lovely work on this project.

**Comment by bfontaine** [comment]
See https://github.com/jackc/pgx/issues/1167 for the donations (the issue is still open though).
