### ISSUE TITLE
Batch does not seem to work for delete queries

### ISSUE THREAD

**Issue by cyberb** [jackc/pgx#808]
I am trying to delete 100 records using a batch of 10, but it deletes only last one in each batch.

```
batch := &pgx.Batch{}
batch.Queue("delete from test where id = $1", 1)
batch.Queue("delete from test where id = $1", 2)
br := conn.SendBatch(context.Background(), batch)
```
Only second will be deleted.
Are batch deletes not supported?

**Comment by jackc** [comment]
No, batch deletes should work fine. Do you have a small case that reproduces this behavior?

**Comment by cyberb** [comment]
Sorry, my bad, something was wrong in my code.
