### ISSUE TITLE
Hooks for metrics/tracing

### ISSUE THREAD

**Issue by utrack** [jackc/pgx#814]
Hi! I want to inject my metrics/tracing to Conn, but I don't see any exposed hooks that would let me do that.

Is there any proper way to inject those? Or should I just wrap *Conn with my own proxy struct?

**Comment by jackc** [comment]
You can inject your own logger. But if that is not sufficient you would have wrap it.

**Comment by utrack** [comment]
Got it, thanks :)

**Comment by Lundis** [comment]
I came straight here from Google. I'd like to point out for others, who do the same, that pgx now has context-compliant before/after hooks configurable using config.ConnConfig.Tracer.
