### ISSUE TITLE
How does pgx infer types

### ISSUE THREAD

**Issue by Tarang** [jackc/pgx#815]
I have a statement such as 

```
db.Exec(ctx, `INSERT INTO tab (somedata) VALUES ($1);`, someval)
```

If `someval` is a `string` with value `A`, but the sql column type of `somedata` is `integer`. The error I get back is `strconv.ParseInt: parsing "A": invalid syntax`.

Since the error is about type conversion in Go (not SQL), as `strconv.Parseint` is a Go function. How does pgx know that the column type of `somedata` is an `integer` and not `text`.

I guess the second layer of my question is there aren't two queries sent to Postgres, one to infer the column type, and the second to insert the data. As this means there is a layer of computational expense on my database.

**Comment by jackc** [comment]
pgx uses prepared statements internally by default. That is how it knows the type the database is expecting.

**Comment by Tarang** [comment]
With the way pgx does a prepared statement isn't the type inferred from my Go variable? What i'm confused about is how the type was inferred from the column types at the Go level instead of the SQL level as would be in a prepared statement.

**Comment by Tarang** [comment]
To put it another way the `someval` i'n my example is a string, but Go somehow knows the column type is an Integer while trying to create the prepared statement. I would have expected the error to be an SQL error (Go tells sql the wrong datatype) instead of a Go error (Go knows the correct data type by reading the columns out in 2 database round trips)

**Comment by jackc** [comment]
You don't have to provide data types to create a prepared statement. You can simply provide the SQL text and PostgreSQL will return the types it expects.  This is how the Go side knows it needs to convert a string to an int.

**Comment by jackc** [comment]
As far as the number of round trips. There are two round trips the first time a query is executed. But pgx caches prepared statements by default, so subsequent queues should only take 1 round trip.

**Comment by Tarang** [comment]
That's quite clear. Thank you
