### ISSUE TITLE
Randomized host choice when specifying multiple hosts in URL/DSN

### ISSUE THREAD

**Issue by horgh** [jackc/pgx#819]
Hello!

I have multiple standby servers, and I'm hoping to balance across them by randomly choosing one when creating each new connection. Currently when specifying multiple hosts, the first one that succeeds is used. I use `pgx/stdlib` to create an `sql.DB`, so randomizing the URL when calling `stdlib.OpenDB()` means all connections will get the same order generated the first time.

I think I could achieve what I want by implementing a `driver.Connector` and calling `pgx.Connect()` each time with a randomly chosen host, and passing that to `sql.OpenDB()`. Do you think there is a better way?

I wonder as well whether an option for this would fit in `pgx/stdlib` or somewhere similar.

Thank you!

**Comment by vtolstov** [comment]
Use math/random and use resulted random server. I dont think that this feature needs to be in this lib

**Comment by horgh** [comment]
Thank you for the ideas!

Yes, I think a custom DialFunc would work! However it'll make the fallback behaviour work strangely I think. For example if I initialize the pool with 2 hosts, pgx will think it's trying the 2 hosts in order, yet each attempt could pick the same one, and I could see errors because of that. That's making me reconsider whether I should go this route.

Another thing I'm hoping to achieve is to re-read my list of standby hosts for each connection attempt. This is because we periodically swap them out for maintenance and the like. I've stuck this in my custom DialFunc right now, but it'll have a similar issue with the fallback behaviour.

**Comment by horgh** [comment]
A colleague had an idea that I could try multiple hosts within the same DialFunc call. That seems like it'd work for this use case. Not ideal perhaps but :-).

**Comment by jackc** [comment]
> A colleague had an idea that I could try multiple hosts within the same DialFunc call. That seems like it'd work for this use case. Not ideal perhaps but :-).

Correct. That is what I was thinking when I mentioned `DialFunc` and `LookupFunc`. With those two functions you can override the host selection and dialing system. A little hacky perhaps, but I don't see any better places to allow completely overriding that behavior.

**Comment by horgh** [comment]
I see. Makes sense. Thank you for the help!
