### ISSUE TITLE
catching a "40001 serialization_failure" error

### ISSUE THREAD

**Issue by ldelossa** [jackc/pgx#824]
Hello,

I'm creating a transaction in "serviceability" isolation mode transaction. In my application I want to catch a "40001 serialization_failure" when trying to commit and do some custom action. 

Is this possible?

**Comment by jackc** [comment]
I've never heard of `serviceability` isolation mode. I assume you mean `serializable`.

Yes, the error will be returned when you commit. See the test case that exercises this functionality if you want an example. 

https://github.com/jackc/pgx/blob/a8abb800825d7ff6f1cab9fc935ba394f494cd74/tx_test.go#L146
