### ISSUE TITLE
Database server patch causes pgx client conns to fail with TLS error

### ISSUE THREAD

**Issue by masroorhasan** [jackc/pgx#825]
Client: jackc/pgx/v4 @ 4.6.0 (native)
Server: CockroachDB v20.1.1 (3 node secure cluster on k8s)

I've setup a simple CRDB 3-node secure cluster as per CRDB docs. The nodes are fronted by k8s service that will load balance traffic to healthy servers. 

On the client side, I'm using `pgxpool` to setup connection pointed to k8s service fronting the CRDB cluster:
```go
cfg, err = pgxpool.ParseConfig(os.getenv("DB_URL") 
if err != nil {
	return nil, err
}
cfg.ConnConfig.TLSConfig.ServerName = "cockroachdb-public"
cfg.MaxConns = int32(100)                             // default: 4
cfg.MinConns = int32(50)                              // default: 0
cfg.MaxConnLifetime = time.Duration(60 * time.Second) // default: 1h
cfg.MaxConnIdleTime = time.Duration(30 * time.Second) // default: 30m

dbpool, err := pgxpool.ConnectConfig(ctx, cfg)
if err != nil {
	return nil, err
}
```

While running a small load test with around ~100 RPS of reads and ~50 RPS of writes, I patched one of the servers in the cluster (i.e. delete one of the statefulset pods) and observed the following errors bubbled back to client:
1/ `io.ErrUnexpectedEOF` from the server - these are all from TXN write ops. To me, this is totally expected and up to the application logic to handle specific server-side `EOF` error responses with some appropriate retry strategy. 

2/ TLS errors from both read and write operations. This one is not clear on why the client (pgconns within pgxpool) attempts to re-connect to a server that is gracefully shutting down and not accepting client connections anymore. 
```
failed to connect to `host=cockroachdb-public user=cockroachdb database=REDACTED`: tls error (server refused TLS connection)
```
I believe the error is bubbling from individual pgconn within the pool from here: https://github.com/jackc/pgconn/blob/v1.6.0/pgconn.go#L215

The server healthchecks are configured @ 30s intervals, but even if that is dropped down to 5s that would still run into the same issue within connections establishing under 5s.

The dirty way to handle this is basically string match on the errors from Query / Exec response and add a layer of retry at application level - but this is def not the first choice. There could also be a combination of BeforeAcquire / AfterConnect hooks that I could leverage that may resolve this but I'm not sure yet. 

However, I’m wondering whether this is expected for secure connections and if the library may consider wrapping this specific scenario with a consistent & custom error type.

**Comment by jackc** [comment]
I'm afraid I don't have any experience with CockroachDB and k8s. But it looks like all your connection attempts are going to the same endpoint and it is responsible for routing it to the correct underlying server. If that's the case I think the root issue is with whatever is doing the routing.

Also, as far as pgxpool reconnecting -- just to clarify -- there isn't really a reconnect concept. pgxpool creates new conns when it needs them, it doesn't specifically try to replace dead ones. So there is no mechanism where it is trying to replace a specific dead connection and perhaps borrowing some connection config info from it to establish the new connection.

As far as a string match for this error goes, at the very least it would be better to have a specific marker that the query is safe to retry. See `pgconn.SafeToRetry(err)` for how this is done on existing connections. It might have to be extended somehow to handle a connection failure though.
