### ISSUE TITLE
Scanning json into a map type

### ISSUE THREAD

**Issue by dankinder** [jackc/pgx#829]
When using pgx/stdlib, should the following query work?

```
var dest map[string]interface{}
if err := db.QueryRow(`SELECT '{}'::json`).Scan(&dest); err != nil {
    return nil, fmt.Errorf("failed: %w", err)
}
```

This is failing for me with the following error: `failed: sql: Scan error on column index 0, name \"jsonb\": unsupported Scan, storing driver.Value type []uint8 into type *map[string]interface {}`

The pgx docs say JSON/JSONB mapping should be built-in, so I assumed this should work.

I don't think it's relevant but in this case I'm using cockroachdb as the database, and sqlx.

**Comment by jackc** [comment]
That only works with the native pgx interface.

Unfortunately, I do not know of any way of extending scan support in `database/sql` aside from implementing `Scan` on the destination type.

**Comment by dankinder** [comment]
Got it, thanks. 

I realize now that your comment under https://github.com/jackc/pgx#choosing-between-the-pgx-and-databasesql-interfaces explains this, but it wasn't obvious until I read it carefully.

I'm using sqlx as well so moving to the native pgx interface is non-trivial.

For others googling this issue, I worked around this issue for now by making a custom type that implements Scan:
```
type StringInterfaceMap map[string]interface{}                                                                              
                                                                                                                            
func (m *StringInterfaceMap) Scan(value interface{}) error {                                                                
    b, ok := value.([]byte)                                                                                                 
    if !ok {                                                                                                                
        return errors.New("failed type assertion to []byte")                                                                
    }                                                                                                                       
    return json.Unmarshal(b, &m)                                                                                            
}
```
