### ISSUE TITLE
Hstore type not supported

### ISSUE THREAD

**Issue by maxp36** [jackc/pgx#833]
I am making a select from a table that has a column of type hstore, but the value is parsed as a string.

I checked the code and there is the following:

- hstore type is not registered in the function `pgtype.NewConnInfo()`
- but the `pgtype.InitializeDataTypes` function through which the type can also be registered is not called
- when the `(rows *connRows) Values() ([]interface{}, error)` function is called because the type value is not registered, the value is parsed as `pgtype.GenericText`

Help me if i'm wrong.
Thanks

**Comment by jackc** [comment]
You can use the `pgtype.Hstore` type directly as a scan target. However, it needs to be manually registered in the connection if you are going to use `hstore` without `pgtype.Hstore` (such as scanning into a `map[string]string`). The reason for this is that the `hstore` type is installed via extension and therefore does not have a fixed OID. The application needs to look up the `hstore` OID at runtime.

See https://github.com/jackc/pgx/wiki/UUID-Support for an example of runtime type registration. You'll also need to query PostgreSQL to get the `hstore` OID.

**Comment by maxp36** [comment]
Thanks a lot
