### ISSUE TITLE
How to read the data from refcursors returned from the stored function?

### ISSUE THREAD

**Issue by kogan69** [jackc/pgx#834]
Hi!
I have a stored function that returns a refcursor. 
I'm calling the function as follows:
rows, err := conn.Query(context.Background(), "select all_clients();")

and then I do:
for rows.Next() {
		var c1 string
		err = rows.Scan(&c1)
		fmt.Println(c1)
}
The output says:
<unnamed portal 1>
This is clearly the name of the cursor, but how can I get to the actual data?
Any help would be much appreciated!!!

Thanks a lot,
Leonid Kogan

**Comment by jackc** [comment]
I haven't done much with cursors, but I think the issue is you need to execute the SQL [FETCH](https://www.postgresql.org/docs/current/sql-fetch.html) command with the cursor name.

**Comment by kogan69** [comment]
Thanks for the reply! 
Here's my code where I do the fetch:

func (dal *Dal) AllClients() {
	ctx := context.Background()
	tx, err := dal.conn.Begin(ctx)

	refRows, err := tx.Query(context.Background(), "select all_clients($1);", "allClients")

	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		tx.Rollback(ctx)
		return
	}


	var c string
	refRows.Close()
	for refRows.Next() {
		err = refRows.Scan(&c)
		fmt.Println(c)
	}


	rows, err := tx.Query(context.Background(), fmt.Sprintf("FETCH ALL from allClients;"))


	if err != nil {
		tx.Rollback(ctx)
	}

	for rows.Next() { // NOTHING IS IN HERE!!!
		client := common.Client{}
		err = rows.Scan(&(client.Id), &(client.Name))
		fmt.Println(client.Id)
	}
	tx.Commit(ctx)
}

The problem is that I'm not getting any rows from it while the ones in the DB.

Here's the source of my stored procudure:

CREATE OR REPLACE FUNCTION public.all_clients(ref refcursor)
 RETURNS refcursor
 LANGUAGE plpgsql
AS $function$
    DECLARE
      --ref refcursor;                                                     -- Declare a cursor variable
    BEGIN
      OPEN ref FOR SELECT * FROM clients;   -- Open a cursor
      RETURN ref;                                                       -- Return the cursor to the caller
    END;
    $function$
;


If I run the following from the dBeaver, I'm getting the result set just OK:
BEGIN;
   select all_clients('allClients');
   FETCH ALL from "allClients";
COMMIT;

And here's my table:

CREATE TABLE public.clients (
	"clientId" uuid NOT NULL,
	"name" text NOT NULL,
	email text NOT NULL,
	siteurl text NULL,
	CONSTRAINT clients_pkey PRIMARY KEY ("clientId")
);
CREATE UNIQUE INDEX clients_name_idx ON public.clients USING btree (name);


Thanks a lot again!
Leonid Kogan

**Comment by kogan69** [comment]
Hi Jack!
I've figured out it! This how it shall be called:

**Comment by ncduongg** [comment]
> Hi Jack! I've figured out it! This how it shall be called: rows, err := tx.Query(ctx, `FETCH ALL "allClients"`)
> 
> Thanks a lot again! Cheers, LK

Hello, 
Can you give me the full code reference, can you guys handle it?
