### ISSUE TITLE
store enum array as string array

### ISSUE THREAD

**Issue by tobiges** [jackc/pgx#835]
Is it possoble to store a custom enum array as a varchar(255)[] ?
I implemented the database/sql scanner and value interface but it still doesn't work.
Is there any way to do this?

**Comment by jackc** [comment]
I don't understand your question. Both `enum` and `varchar(255)` are PostgreSQL types, not Go.

**Comment by tobiges** [comment]
By go "enum" I ment
````
type GoEnum string
const (
	Val1 GoEnum = "Val1"
	Val2 GoEnum = "Val2"
	Val3 GoEnum = "Val3"
	Val4 GoEnum = "Val4"
)

func (e GoEnum) IsValid() bool {
	switch e {
	case Val1, Val2, Val3, Val4:
		return true
	}
	return false
}

// Scan - Implement the database/sql scanner interface
func (e *GoEnum) Scan(value interface{}) error {
	if value == nil {
		return errors.New("failed to scan GoEnum(cannot be nil)")
	}
	if v, ok := value.(string); ok && GoEnum(v).IsValid() {
		*e = GoEnum(v)
		return nil
	}
	return errors.New("failed to scan GoEnum(invalid value)")
}

// Value - Implementation of valuer for database/sql
func (e GoEnum) Value() (driver.Value, error) {
	return string(e), nil
}
````

I want to use it like this in my struct:
```
type Thing struct {
    ImplementedTypes []GoEnum
}

```
and atore it as a `varchar(255)[]`
Is this possible or do I need to have a `type EnumArray []GoEnum` and implement the scan and value interface for this type?
I don't want that, my current workaround is to store it as jsonb.

**Comment by jackc** [comment]
> Is this possible or do I need to have a type EnumArray []GoEnum and implement the scan and value interface for this type?

You would need the EnumArray type.

**Comment by tobiges** [comment]
OK thanks then I will implement that.
