### ISSUE TITLE
DB URL escaping

### ISSUE THREAD

**Issue by NorthlaneKek** [jackc/pgx#836]
Im trying to provide connect to DB, but always got some errors. If my connect url consist of special symbols such as '#' or '%' then pgx can't parse url and it stops (with error: failed to parse as URL). Unfortunatelly, password of DB consists of this symbols. I've tried to use url.QueryEscape() and it bone me to another error: failed to parse as DSN (invalid dsn)
How can I avoid these kind of problems? Changing password is not the way

**Comment by jackc** [comment]
If it is in URL format it may need to be URL encoded. If it is in DSN format it may need to be backslash escaped.

**Comment by NorthlaneKek** [comment]
@jackc thanks for advice. Problem has been solved by using DSN format instead of simple URL
