### ISSUE TITLE
too many clients already (SQLSTATE 53300)

### ISSUE THREAD

**Issue by mhewedy** [jackc/pgx#839]
I am trying to load test my api that uses pgx and got:

```failed to connect to `host=dbserver user=myuser database=mydb`: server error (FATAL: sorry, too many clients already (SQLSTATE 53300))```

here's my setup:

```
func New() *sql.DB {

	var (
		host     = conf.Get("db.host")
		port     = conf.GetInt("db.port")
		user     = conf.Get("db.user")
		password = env.Get("DB_PASSWORD", "123456")
		dbname   = conf.Get("db.dbname")
	)

	dsn := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
		host, port, user, password, dbname)

	c, err := pgx.ParseConfig(dsn)
	if err != nil {
		panic(err)
	}
	return stdlib.OpenDB(*c)
}
......
......

func main() {
	db = dbconn.New()
	defer db.Close()
......
}
```

As show, I need to use `database/sql ` interface.

**My question here is, What is the default size of the connection pool used in my case? and how to change it?**

**Comment by mhewedy** [comment]
I am changed the setup code to be identical to the one here https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql however same issues still exist

**Comment by jackc** [comment]
When using database/sql pgx doesn't control the size of the pool at all. You probably want: https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns

**Comment by mhewedy** [comment]
Thanks for clarification
