### ISSUE TITLE
connection local statement cache does not correctly invalidate

### ISSUE THREAD

**Issue by ethanpailes** [jackc/pgx#841]
# Description of Issue

`pgx` appears to maintain a [connection-local cache](https://github.com/jackc/pgx/blob/2a8ae6f269e17c44d25cd0f713eaa6356547206e/conn.go#L653) of prepared statements that are automatically used for queries performed by `sql.DB.QueryContext`.[1] This cache does not appear to handle the case when the underlying database schema has changed, invalidating the prepared statement.

At first blush, the database schema changing out from under a prepared statement seems pretty weird, so I'll explain how we've seen it being an issue in practice. When doing a deploy of an existing service, there is often a database migration along with a code change that accounts for the new schema. If the migration runs first, the old application servers will still be running with the old code and caches hanging around. Before the servers can be gracefully restarted with new code, the old code will begin experiencing issues because of the cached prepared statements.

# Minimum Replication

The following program demonstrates the issue:

```go
package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"log"

	_ "github.com/jackc/pgx/v4/stdlib"
)

// run `createdb pgx_mucking`
func main() {
	ctx := context.Background()

	db, err := sql.Open("pgx", "postgres://localhost/pgx_mucking?sslmode=disable")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer db.Close()

	// Grab a single connection on which to perform the SELECT statements so we can be
	// sure to reproduce the bug in this toy example. The bug will be intermittent if we
	// instead just call the QueryContext method on the `*sql.DB`.
	conn, err := db.Conn(ctx)
	if err != nil {
		log.Fatal(err)
	}

	_, err = db.ExecContext(ctx, `
        DROP TABLE IF EXISTS drop_cols;
        CREATE TABLE drop_cols (
            id SERIAL PRIMARY KEY NOT NULL,
            f1 int NOT NULL,
            f2 int NOT NULL
        );
    `)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("connected to db")

	// insert some data (probably not needed for replication)
	_, err = db.ExecContext(ctx, "INSERT INTO drop_cols (f1, f2) VALUES (1, 2)");
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("inserted values")

	getSQL := "SELECT * FROM drop_cols WHERE id = ANY($1)"

	// populate pgx's internal prepared statement cache
	_, err = conn.QueryContext(ctx, getSQL, 1)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("populated stmtcache")

	// change the schema (in a more realistic example, this would mean running a
	// migration while the application server is still running).
	_, err = db.ExecContext(ctx, "ALTER TABLE drop_cols DROP COLUMN f1")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("altered schema")

	// run the query again, causing us to use a bad prepared statement
	_, err = conn.QueryContext(ctx, getSQL, 1)
	if err != nil {
		log.Fatalf("dies with: %s", err.Error())
	}
	fmt.Println("never prints")
}
```

The output of that program is as follows:

```
connected to db
inserted values
populated stmtcache
altered schema
2020/10/05 10:55:02 dies with: ERROR: cached plan must not change result type (SQLSTATE 0A000)
```

# Potential Fixes

I can see two possible fixes:
1. When Query is called via the `database/sql` interfaces, never use the cache. This would follow the principle of least surprise in my view, but I can definitely see now wanting to give up any perf wins that caching gives.
2. If there is an error when calling Next to get the first row, attempt to recover by invalidating the cache for that statement and retrying the query. This may be a little annoying because the error shows up in [the first Next call](https://github.com/jackc/pgx/blob/2a8ae6f269e17c44d25cd0f713eaa6356547206e/stdlib/sql.go#L360-L364) rather than the call to actually query the db.

I'm happy to try to put together a patch for either one of these approaches. Just let me know which one you prefer.

[1]: This is somewhat surprising because the `sql.DB` interface contains dedicated interfaces for creating prepared statements, so I would not expect the normal Query interfaces to create prepared statements. That said, if there are big perf wins, I can't see how to realize those for people who want to use `sql.DB` directly rather than layering some sort of framework on top of it, so the choice `pgx` makes seems reasonable in that context.

**Comment by jackc** [comment]
There can be a significant performance win with the statement cache. But it can be disabled with the connection string option `statement_cache_capacity=0`.

Invalidating the cache / recovering from `SQLSTATE 0A000` would be ideal, but I'm not sure if it can be done reliably. There are at least two places is would be impossible or difficult -- when a transaction is in progress and when the prepared statement is part of a batch operation. There may be more places as well. And the potential solutions tend to involve some sort of automatic retry logic -- and that is something I have been very reluctant to add due to the multiple of ways that can go wrong.

A simple improvement might be to flush the cache or even kill the connection when `SQLSTATE 0A000` occurs. That would at least make sure nothing got stuck in a broken state.

Some other options -- most likely at the application layer -- might be something with listen / notify or an event trigger on DDL.

**Comment by ethanpailes** [comment]
@jackc is there a way to explicitly flush the cache from the application layer today (ideally going through a `*sql.DB` or `*sql.Tx`)? If so I could use that as a workaround, though I do think some step should probably be take to address this bug.

What about this as a solution: in the case of `SQLSTATE 0A000`, `pgx` invalidates the cache but then returns the error without retrying. Additionally, `pgx` exposes a new routine `IsSQLState0A000Error` which allows detection of this error (of course we can grep the output of `.Error()` right now, but text based error formats are generally not considered part of a stable public API). I'm happy to bikeshed the name (`IsInvalidCachedStatementPlanError` also seems like a fine choice). This way the application layer can handle the error in a manner appropriate to the current situation (so it could abort the transaction if it is in the middle of a transaction, or retry the statement if it is not).

**Comment by jackc** [comment]
That's the general approach I recommend, but there's a few details to be determined.

1. Does the entire cache get invalidated or just the statement that failed?

2. When does this invalidation happen? If we are in a broken transaction we can't even `deallocate` a statement.

```
jack@[local:/private/tmp]:5432 isoquote_dev=# prepare s1 as select 1;
PREPARE
jack@[local:/private/tmp]:5432 isoquote_dev=# begin;
BEGIN
jack@[local:/private/tmp]:5432 isoquote_dev=# select 1 / 0;
ERROR:  division by zero
jack@[local:/private/tmp]:5432 isoquote_dev=# deallocate s1;
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

For this to be reliable we would need to mark the cache as pending deallocation, but the deallocating of the statements would have to wait until the next query executed after the transaction was rolled back.

3. I'm not necessarily opposed to a `IsInvalidCachedStatementPlanError` function, but it is not necessary to avoid relying on the error text. Any error that originated with the PostgreSQL server is a `*pgconn.PgError`. You can read the `SQLSTATE` directly from there. See https://github.com/jackc/pgx/wiki/Error-Handling. In addition, https://github.com/jackc/pgerrcode/ has constants for errors -- in this case `0A000` is `pgerrcode.FeatureNotSupported`. Hmmm... "feature not supported" sounds like it might be used by more than a bad plan... And a quick look at the PostgreSQL source code shows that it is. So maybe a helper function is necessary and it will have to do the string inspection...

**Comment by ethanpailes** [comment]
For (1) I would think it would be better to just deallocate the statement that failed. If the schema for `foos` changes, but most of the cached prepared statements have to do with the tables `bazes`, `bars`, and `quxes` they would continue to be valid. That seems to be a common case for a service with a good sized schema where migrations are getting run on one or two tables.

WRT (2), my understanding was that prepared statements are a connection local thing. Is there no real distinction between a connection handle and a transaction handle at the wire protocol layer? If so, it sounds like we would need to set up a completion sink of some sort in the connection struct.

It sounds like we are mostly on the same page about this, so I may start poking at things to try to come up with a patch. No guarantees I'll be able to make progress though :slightly_smiling_face:

**Comment by jackc** [comment]
1. I imagine that is the way most people would be doing migrations. But the other case exists too. I have a project that keeps views and functions in one schema so every deploy completely drops and recreates it. (This sidesteps dependency issues where view A depends on B depends on C).

2. There is no concept of a transaction handle at the wire protocol layer. It is a state of the connection.

**Comment by ethanpailes** [comment]
> But the other case exists too. I have a project that keeps views and functions in one schema so every deploy completely drops and recreates it. (This sidesteps dependency issues where view A depends on B depends on C).

That makes a lot of sense. It almost seems like connections should expose explicit hooks to flush the statement cache. The default could be to just invalidate a single statement on error, but for cases like that were you can know ahead of time that there will be a lot of thrash you can use the hook to head that off.

**Comment by timnewsham** [comment]
Are there any hooks an application can use to automatically retry a query after such an 0A000 error? I'm using pgx with gorm, and I get these kinds of errors during migrations (as expected). I would love to have a general solution that lets me retry the operation after pgx gets this error and clears the statement cache. I can't find any information about any callbacks in gorm or pgx that would allow me to do this, but I did notice in some other pgx issue logs some discussion about possibly supporting such a hook.

**Comment by jackc** [comment]
There is not presently any sort of automatic retry functionality and it is very difficult or even impossible to handle in the general case. The biggest problem is that any PG error breaks the transaction the query is running in. A more narrowly focused application level wrapper over pgx would be more plausible, but I am not aware of any.

**Comment by ethanpailes** [comment]
https://github.com/opendoor/pggen is a database codegen framework I wrote that will automatically retry these errors when performing the default queries. It hasn't been updated in a while but that's because it is pretty much "done" more than anything else.
