### ISSUE TITLE
String truncated while inserting

### ISSUE THREAD

**Issue by pragyanaryal** [jackc/pgx#850]
Hello, I am facing issue while inserting data. The string type in golang is getting truncated even if the sufficient length is specified in the postgres side. I tried specifying varchar with upto 150 length and also text. But still my insert is getting truncated. However, if i try to insert the data from datagrip or pgadmin it is successfull. Here is the log of my insert sql commad. The first link is the string to be inserted, but only 64 characters get inserted out of 90.

![image](https://user-images.githubusercontent.com/36224537/96252801-4596ed80-0fd2-11eb-9cff-fd792c561508.png)

Here is the table structure defined,
![image](https://user-images.githubusercontent.com/36224537/96252580-e9cc6480-0fd1-11eb-9023-a3dc951db2a4.png)

**Comment by jackc** [comment]
Is it definitely truncated in the database? The screen shot you posted is of the log -- and it is only the log output that is truncated -- not what is stored in the database.

**Comment by pragyanaryal** [comment]
Lol, thank you. In database its getting saved correct. Why did it show truncate there, any reason ? Anyway thankyou. ;)

**Comment by jackc** [comment]
> Why did it show truncate there, any reason ?

To avoid bloating the logs when using long `string` or `[]byte` values.
