### ISSUE TITLE
How to log queries?

### ISSUE THREAD

**Issue by mystdeim** [jackc/pgx#855]
I couldn't find it documentation how to log queries if I use pool. For example I have created pool like this:

```
func DB() *pgxpool.Pool {
	connStr := os.Getenv("DATABASE_URL")
	conn, err := pgxpool.Connect(context.Background(), connStr)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
	return conn
}
```
Please tell me how to log my queries then?

**Comment by jackc** [comment]
Use `ParseConfig` to get a `*pool.Config` object. Then set the `ConnConfig.Logger` field. Then use `ConnectConfig` with that config object.

The log directory contains adapters for several popular loggers.

**Comment by mystdeim** [comment]
Thanks a lot!
