### ISSUE TITLE
Close() hangs on large(ish) batch insert

### ISSUE THREAD

**Issue by KirksFletcher** [jackc/pgx#857]
I am creating a batch insert with 1000 rows (only 2 columns though) and using pgxpool.Connect. After creating the connection I defer a conn.Close(). However I have noticed that unless i add a sleep of 100 - 200 ms as part of the defer func, Close() will just hang and nothing is inserted.

Obviously this is absolutely horrid and do not want a sleep in my defer function. Why is the function returning before the statement is complete? This for some reason causes Close to just hang, no error at all just a full hang and that function never completes.

If i have a global pool and use the acquire and release method i get the same issue. I have to add a sleep in the defer Release() func.

Postgres is sat behind pgbouncer with 1000 max connections on one hell of a beefy server so not a hardware bottle neck.

**Comment by KirksFletcher** [comment]
> Are you closing the batch results first?
> 
> https://pkg.go.dev/github.com/jackc/pgx/v4#BatchResults

From what I can tell (and obviously you'll know more than me :-) ) Is that just retrieving batch results? This is my current code.

`func (p *postgresDBConnection) BatchInsert(kws []KwInsert) {
	pg, err := PostgresDB.db.Acquire(context.Background())
	if err != nil {
		log.Fatalln(err)
	}

	defer func() {
		time.Sleep(200 * time.Millisecond)
		pg.Release()
	}()

	batch := &pgx.Batch{}

	for _, kw := range kws {
		batch.Queue("INSERT INTO client_1.keywords (unix_date_added, keyword) VALUES ($1, $2)", kw.TStamp, kw.Keyword)
	}

	ct, err := pg.SendBatch(context.Background(), batch).Exec()

	if err != nil {
		log.Fatalln(err)
	}
	fmt.Println(ct.RowsAffected())
}`


Im sure I am just missing something silly, just can't seen to nail this down.

**Comment by jackc** [comment]
`SendBatch` returns a `BatchResults`. You need to call `Close()` on it.

**Comment by KirksFletcher** [comment]
> `SendBatch` returns a `BatchResults`. You need to call `Close()` on it.

Perfect! Got lazy chaining requests. Works perfectly now
