### ISSUE TITLE
driver.RowsNextResultSet interface support for stdlib.Driver in github.com/jackc/pgx/v4/stdlib

### ISSUE THREAD

**Issue by muravjov** [jackc/pgx#858]
Hi, 

I see that the database/sql driver doesn't support driver.RowsNextResultSet interface, 
while [Conn](https://pkg.go.dev/github.com/jackc/pgx/v4@v4.9.0#Conn) in github.com/jackc/pgx/v4  
has explicit SendBatch()/Exec() analogue.

Is there a plan to support RowsNextResultSet interface in database/sql driver?
What issues against do you see to make it real?

**Comment by jackc** [comment]
I don't know of any blocking architectural issues. It's a matter of someone doing the work. I'd be happy to have the feature, but it's not something I am personally planning on working on in the near future.

**Comment by bfontaine** [comment]
I’m closing this since nobody is working on it.
