### ISSUE TITLE
Expose sanitize package / functions

### ISSUE THREAD

**Issue by dahu33** [jackc/pgx#868]
In our quest to fully replace lib/pq by pgx we are looking for some sanitization functions, primarily [QuoteIdentifier](https://godoc.org/github.com/lib/pq#QuoteIdentifier) and [QuoteLiteral](https://godoc.org/github.com/lib/pq#QuoteLiteral).

pgx seems to have a sanitize package with similar functions (`QuoteString` and `QuoteIdentifier`) but this package is 'internal'. 

I think it would be beneficial to have some exposed sanitize functions available in pgx and maintained by the pgx community. Making the sanitize package non-internal or creating a new non-internal sanitize package would be very welcome by many.

**Comment by jackc** [comment]
The reason those are internal is it is not guaranteed to be safe to escape a value unless `standard_conforming_strings="on"` and `client_encoding="UTF8"`. The outer layer checks those preconditions. 

Identifiers can be escaped with the `pgx.Identifier` types `Sanitize` method.

But Literals can be escaped with the underlying `PgConn.EscapeString` (it escapes, but _doesn't_ quote).

To be absolutely safe the logic for escaping a literal needs to know the connection variables.

That can be a bit awkward to work with though when using `pgxpool` (which I assume most everyone is). In theory, someone could have messed with a particular connection settings... Extremely unlikely to be sure, but it pays to be paranoid where security is concerned.

I'm open to improvements in the interface, but the underlying capability is exposed one way or another now.

**Comment by dahu33** [comment]
Thanks for the explanation. Unfortunately, we have to stick with the `database/sql` interface so `PgConn.EscapeString` is not a realistic option.
