### ISSUE TITLE
add support for inet and cidr column types

### ISSUE THREAD

**Issue by gucki** [jackc/pgx#87]

**Comment by jackc** [comment]
PostgreSQL inet and cidr include address and network mask, so it appears that the correct mapping would be to [net.IPNet](https://golang.org/pkg/net/#IPNet). Does this make sense to you?

**Comment by alaska** [comment]
That makes perfect sense. I've been meaning to implement this myself, actually. Hadn't gotten around to it. You might also consider allowing [net.IP](http://golang.org/pkg/net/#IP) input and casting it automatically to a net.IPNet with /32 or /64

**Comment by gucki** [comment]
Sounds good! :+1:

**Comment by apaxa-io** [comment]
While Postgres does not have separate type for IP address only it is common case to use inet for storing it. So why not to allow scan for net.IP (if netmask is 32/128)?

**Comment by jackc** [comment]
I think this is reasonable. You want to open a new issue?

**Comment by apaxa-io** [comment]
Ok.
[issue](https://github.com/jackc/pgx/issues/137)
