### ISSUE TITLE
Handling custom data types (protobuf values)

### ISSUE THREAD

**Issue by jamesthegiantpeach** [jackc/pgx#871]
Greetings,

What is the recommended way for dealing with custom data types? For example:

My structs are protobuf 

```
type User struct {
	// Output only.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User mutable.
	//  The User's email. This also functions as a globally unique ID.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// The User's given name.
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// The User's surname.
	LastName string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// The sub field in the oidc protocol.
	OidcSubject string   `protobuf:"bytes,5,opt,name=oidc_subject,json=oidcSubject,proto3" json:"oidc_subject,omitempty"`
	RoleNames   []string `protobuf:"bytes,6,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	// Output only.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only.
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}
```

The timestamp.Timestamp are just wrappers around unix int64 timestamps, and I would like to easily convert between this timestamp and the timestampz wire format. What is the recommended way to do something like this with this lib?

Also, generally, what is a good way of scanning joins into more complex, nested structs? For instance, with the above struct, I have an exploded struct that looks like
```
type UserExploded struct {
	Id string 
	Email string
	FirstName string
	LastName string
	OidcSubject string 
	RoleName string
	CreateTime *timestamp.Timestamp
	UpdateTime *timestamp.Timestamp
}
```
and then use a hashmap and a loop to fill a []*User with nested role list. This gets very hairy for my more complex types.

**Comment by jackc** [comment]
I don't have first hand experience with protobuf.

With regards to special timestamp types, you can implement `EncodeText`/`EncodeBinary` is using pgx directly or implement `Value` if using the `database/sql` interface.

With regards to scanning entire complex nested, structs, pgx doesn't have any specific functionality for that. Personally I tend to build bespoke mapping code. But there are a number of third party libraries that may help. I do not have first hand experience with any of these options -- but when using the `database/sql` interface you can use any of the normal Go libraries like sqlx or gorm. When using pgx directly [github.com/georgysavva/scany](https://github.com/georgysavva/scany) may do what you want.

**Comment by jamesthegiantpeach** [comment]
EncodeBinary looks like it works perfectly. 

Scany looks neat. I ended up using json_agg and json_build_object to scan into a complex, nested struct. 

Is pgx intended to be able to scan queries where some of the columns in the result set are regular aggregated arrays? 

Thanks

**Comment by jackc** [comment]
Arrays are just another type to pgx. They can be supported with `(En|De)code(Text|Binary)`. Out of the box pgx supports the standard array types.

For arrays of structs / custom types look using `pgtype.CompositeType` and / or `pgtype.ArrayType`. Those types are how pgx tries to handle entirely new types.

However, you mentioned json -- if you can tolerate the small overhead of json encoding and decoding -- that is by far the easiest way of getting complex structures out of PG. That's what I've been doing lately myself (in fact decoding in pgx becomes moot because I'm building the entire desired JSON doc in PostgreSQL and just shipping the bytes over the wire). But pgx also will automatically unmarshal JSON when scanning a JSON(B) value into a struct.

**Comment by jamesthegiantpeach** [comment]
```
Arrays are just another type to pgx. They can be supported with (En|De)code(Text|Binary). Out of the box pgx supports the standard array types.
```
Rad.

```
However, you mentioned json -- ...
```
Ok i'll keep going down this path of building the json doc in PG. Oh! It looks like [this](https://godoc.org/github.com/golang/protobuf/jsonpb) package will automatically de/encode an RFC3339 timestamp from json to the protobuf *timestamp.Timestamp type (looks like this is just a wrapper around a unix int64 timestamp). Looks like building up the JSON doc on the PG server side reduces this problem to a few lines of code. 

For inserting/updating nested structs do you typically just wrap multiple inserts in a transaction, or is there a fancy JSON thing that can be done here as well?

Thanks for all of these clean PG libraries btw they've been really helpful.

**Comment by jamesthegiantpeach** [comment]
Closing thanks for advice!

**Comment by jackc** [comment]
> For inserting/updating nested structs do you typically just wrap multiple inserts in a transaction, or is there a fancy JSON thing that can be done here as well?

Depends on the situation. Sometimes I use multiple inserts, sometimes I use a server side function that takes the JSON and handles the inserts internally.
