### ISSUE TITLE
Type assert or get the values from []interface{} returned by pgx.Rows.Values() or from [][]byte returned by pgx.Row.RawValues()

### ISSUE THREAD

**Issue by ar-daniel** [jackc/pgx#873]
**Description**
How to Type assert or get the values from []interface{} returned by pgx.Rows.Values() or 
get values from [][]byte returned by pgx.Row.RawValues()

**Code for referenced used -**

```
....
// working connection link already made and is present in  'conn' variable
        rows, err := conn.Query(context.Background(), "SELECT user_id, first_name, last_name, department FROM tbl_test_profile")
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()

	type rowValueTemplate struct {
		UserId     string
		FirstName  string
		LastName   string
		Department string
	}
        rowValues, _ := rows.Values()

        for _, eachRowValue := range rowValues {
	        _, err := fmt.Println(eachRowValue.(rowValueTemplate)) // passing the struct as type didnt work
		if err != nil {
			fmt.Fprintf(os.Stderr, "Rows value print failed: %v\n", err)
		}
		// _, err := fmt.Printf("%T\n", eachRowValue)  // tired to get the type of value contained in interface{} , but didnt work 
	}
....
```
The complier panics and crashes.
Simliarly tired to get the values from the [][]byte returned by rows.RawValues(). This time it didnt panic, but there was no result.

```
....
	rowValues := rows.RawValues()  // now rowValues contain [][]byte
	var eachRowUnmarchalledValue rowValueTemplate

	for _, eachRowValue := range rowValues {
		json.Unmarshal(eachRowValue, &eachRowUnmarchalledValue)
		_, err := fmt.Println(eachRowUnmarchalledValue)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Rows value print failed: %v\n", err)
		}

	}
....
```

Note - I've already used rows.Scan() and conn.QueryRow().Scan() 
and they ve worked.

I wanted to analyse the row values returned by the query. Please assist.

**Comment by jackc** [comment]
There's nothing special about the values returned from `Values()`. Normal Go type assertions and checks should work.

For example:

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v4"
)

func main() {
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close(context.Background())

	rows, _ := conn.Query(context.Background(), "select 'foo', 42")
	for rows.Next() {
		values, err := rows.Values()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Values error: %v\n", err)
			os.Exit(1)
		}

		for _, v := range values {
			fmt.Printf("%T\n", v)
		}
	}

	if err := rows.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "Query error: %v\n", err)
		os.Exit(1)
	}
}
```

Output:

```
$ go run main.go                                                                                                                                             
string
int32
```

**Comment by ar-daniel** [comment]
Ok. I see that rows.Next() is used to loop through the result and rows.Values() returns the result of one particular row as []interface{} with each individual cell value as interface{} in the array. 

I've mistook the entire result set of all rows was returned as []interface{}.

Working Code - 
for rows.Values()
```
....
	rows, err := conn.Query(context.Background(), "SELECT user_id, first_name, last_name, department FROM test_profile")
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()

	result := []rowValueTemplate{}

	for rows.Next() {
		rowValues, _ := rows.Values()
		result = append(result, rowValueTemplate{
			UserId:     rowValues[0].(string),  // or rowValues[0].(int)  whichever suitable as per datatype
			FirstName:  rowValues[1].(string),
			LastName:   rowValues[2].(string),
			Department: rowValues[3].(string),  
		})
	}

	fmt.Println("Printing the entire result")
	fmt.Printf("%+v\n", result)
....
```

for rows.RawValues()
```
....
        result := []rowValueTemplate{}

	for rows.Next() {
		rowValues := rows.RawValues()
		result = append(result, rowValueTemplate{
			UserId:     string(rowValues[0]),
			FirstName:  string(rowValues[1]),
			LastName:   string(rowValues[2]),
			Department: string(rowValues[3]),
		})
	}

....
```
Thanks, 
on side note what would you say, to have a result of a row as a struct ( returned from say, rows.StructValue() ) which can be assigned directly to a struct variable instead of individually assigning each field.

**Comment by jackc** [comment]
> on side note what would you say, to have a result of a row as a struct ( returned from say, rows.StructValue() ) which can be assigned directly to a struct variable instead of individually assigning each field.

What fields would this struct have?

**Comment by ar-daniel** [comment]
The struct would have the same column names ( or alias name) queried of postgres table/ table joins as fieldnames of the struct and its associated data type being corresponding to column data type of postgres table(s) that are direct mapped with golang types ( and pgtypes lib of this repo for more types )

the result could be something like this,
```
....
        result := []struct{
             field1 string
             field2 int
             ....
        }{}

	for rows.Next() {
		rowStructValue := rows.StructValue()
		result = append(result, rowStructValue)
        }
....
```

**Comment by jackc** [comment]
> The struct would have the same column names ( or alias name) queried of postgres table/ table joins as fieldnames of the struct and its associated data type being corresponding to column data type of postgres table(s) that are direct mapped with golang types ( and pgtypes lib of this repo for more types )

That would require generating new struct types at runtime. I don't think Go does that, at least without a serious amount reflect magic. Even if that could be solved, that would mean that function would not return a fixed type -- it would have to return `interface{}`. But since the type was generated at runtime you couldn't type assert to it either. So all access would have to be through reflect as well. 😞

I think pretty much all the Go struct mapping libraries resolve this by passing the varying type in as an argument rather than returning it.

Maybe take a look at https://github.com/georgysavva/scany.

**Comment by ar-daniel** [comment]
I agree with your point. As I was browsing through yesterday, found this library for conversion of interface to struct. Just wanted to share.
https://golangbyexample.com/interface-to-struct/
https://github.com/mitchellh/mapstructure
I haven't tried it though.


> Maybe take a look at https://github.com/georgysavva/scany.

But what you've suggested looks good, also having support for pgx native interface, will try it out.
