### ISSUE TITLE
Allow destroying idle connections in a pool

### ISSUE THREAD

**Issue by cevian** [jackc/pgx#876]
Adding a Destroy method to the Pool's connection would allow people to acquire idle connections and then destroy them.

This is useful if, for example, you lost the leader lock in a system and know that you will be not doing much for a while.

Thanks for all the great work.

**Comment by jackc** [comment]
This can be done now with one additional call.

Use `(*pgxpool.Pool).AcquireAllIdle()` to get all idle connections. For each connection call `(*pgxpool.Conn).Conn().Close()` and then `(*pgxpool.Conn).Release()`. The pool will detect the connection is dead and will remove it from the pool.

**Comment by cevian** [comment]
Thanks!
