### ISSUE TITLE
COPY from stdin failed: cannot convert to Text

### ISSUE THREAD

**Issue by rrb3942** [jackc/pgx#877]
I'm refactoring a project to use use COPY to speed up inserts, but can't seem to figure out why it wont work.

I keep getting the following error message:

`Copy Error: ERROR: COPY from stdin failed: cannot convert {{INVITE 2}} to Text (SQLSTATE 57014)`

All values are embedded pgtypes, so they should support EncodeBinary.

> //Text Extension to pgtype.Text
type Text struct {
        pgtype.Text
}

Copy command looks like:

> rows := [][]interface{}{}
                                        for _, row := range records {
                                                rows = append(rows, row.DBVals)
                                        }
                                        if _, err := conn.CopyFrom(context.Background(), table, fields, pgx.CopyFromRows(rows)); err != nil {

Calls to Exec with an insert query work fine:

> for _, record := range records {
    if result, ok := conn.Exec(context.Background(), query, record.DBVals...); ok != nil {
                                                                                        log.Println("DB:",ok,":",result);
 }
 }

Not sure why it would work with Exec, but not CopyFrom

**Comment by jackc** [comment]
If I had to guess I would say that it might be something with `Type` vs `*Type`. I think `Exec` might be more flexible / forgiving. I'd also experiment with just `pgtype` types. If that works then there must be something with the application types.

**Comment by rrb3942** [comment]
Thanks for the response.

I tried using the embedded type directly when building the rows of []interface{}

> //Return our embedded pgtype value for use with DB Driver
func (myval *Text) DBValue() interface{} {
        return myval.Text
}

Also tried just rebuilding and returning as a plain pgtype
> //Return plain pgtype value for use with DB Driver
func (myval *Text) DBValue() interface{} {
        var text pgtype.Text
        text.Set(myval.String)
        return text
}

But still I get a conversion error:

`ERROR: COPY from stdin failed: cannot convert {INVITE 2} to Text (SQLSTATE 57014)`

**Comment by rrb3942** [comment]
Pretty sure I figured it out. 

I had some old imports to "github.com/jackc/**pgx**/pgtype" from before v4 instead of "github.com/jackc/pgtype". Everything else worked, but this was broken.

Sorry for the trouble!
