### ISSUE TITLE
SendBatch and transactions

### ISSUE THREAD

**Issue by JacksonAllan** [jackc/pgx#879]
Hello. I apologize if this question is a silly one or has been answered elsewhere.

The documentation for SendBatch states "All queries are run in an _implicit transaction_ unless explicit transaction control statements are executed". Does this mean that, when using SendBatch to make changes to the database, if one command fails the other commands in the batch are automatically rolled back? I noticed that Tx has an explicit Rollback function that should typically be run deferred when using it, whereas Batch has no such mechanism.

Thanks!

**Comment by jackc** [comment]
> Does this mean that, when using SendBatch to make changes to the database, if one command fails the other commands in the batch are automatically rolled back?

Yes, unless you included `begin` / `commit` as part of your batched SQL statements. This behavior is an intrinsic part of the PostgreSQL extended protocol. See https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY for more details.

**Comment by redbaron** [comment]
Does it meant that Batch behaviour change in regards to transaction when simple protocol is selected or pgx maintains parity by inserting explicit `BEGIN`/`COMMIT` implicitly ?

**Comment by jackc** [comment]
> Does it meant that Batch behaviour change in regards to transaction when simple protocol is selected or pgx maintains parity by inserting explicit BEGIN/COMMIT implicitly ?

@redbaron Neither. The behavior is the same but pgx doesn't do anything special. All statements are sent in a single string. When you send a single SQL string with multiple statements to PostgreSQL it also has implicit transactional behavior.

This is somewhat surprising if you are expecting psql behavior. psql actually parses the string and sends each statement separately.

**Comment by makalaaneesh** [comment]
Hi @jackc , can you pls confirm if this pattern is safe? 
1. We're calling `conn.BeginTx/tx.Commit`, not sending explicit BEGIN/COMMIT as part of the batch. 
2. We're calling `conn.SendBatch` (as opposed to `tx.SendBatch`). We assume this to be safe based on [this comment of yours](https://github.com/jackc/pgx/issues/1627#issuecomment-1574893553)
3. We're executing other statements as part of the same tx. Our expectation is that all the statements (part of batch and also the individual statements executed as `tx.Exec`) will all be part of a single transaction. 

Apologies if this is too specific, but we're facing a weird issue of missing Inserts/updates/deletes (that isn't reproducible when we use normal `tx.Exec()` as opposed to `SendBatch()`, so just wanted to rule this out.

```
tx, err := conn.BeginTx(ctx, pgx.TxOptions{})
...
br := conn.SendBatch(ctx, &batch) 
... 
res, err = tx.Exec(ctx, "INSERT INTO ...")
...
err = tx.Commit(ctx)
```

**Comment by jackc** [comment]
@makalaaneesh 

Assuming `conn` is a `*pgx.Conn` then it should work. However, it's not a great pattern. You can really get confusing issues when `conn` is actually a `*pgxpool.Pool`. Then it would fail. And that's a real easy mistake to make.

I would certainly not intentionally do what your example code is doing. But it should work.
