### ISSUE TITLE
Proposal: Convenience function `CopyFromSlice`

### ISSUE THREAD

**Issue by egonelbre** [jackc/pgx#882]
Currently `CopyFromRows` is rather cumbersome to use and similarly implementing a custom type is often annoying. Usually the values people want to insert are in a slice, so a helper for such situation would be neat.

It could work similarly how some `sort` API-s work. e.g.

```
_, err := conn.CopyFrom(ctx,
	pgx.Identifier{"users"},
	[]string{"name", "age"},
	pgx.CopyFromSlice(len(users), func(i int) []interface{} {
		u := &users[i]
		return []interface{}{u.Name, u.Age}
	}),
)
```

Alternatively, it could be a more efficient version that avoids allocating `[]interface{}`:

```
_, err := conn.CopyFrom(ctx,
	pgx.Identifier{"users"},
	[]string{"name", "age"},
	pgx.CopyFromSlice(len(users), func(e *pgx.RowEncoder) error {
		e.String(u.Name)
		e.Int32(u.Age)
		e.Any(u.Misc)
		return nil
	}),
)
```

**Comment by jackc** [comment]
I think using `CopyFromSource` interface is similar to using the `sort.Sort` interface. But I suppose that your proposal would be analogous to `sort.Slice`.

I'm open to this idea. I prefer the interface of the first one better. I doubt that one allocation per row will make a big difference. In the rare case it does matter there is always still the option of implementing `CopyFromSource`.

**Comment by egonelbre** [comment]
Yes, I meant something like `sort.Slice`. I'll make a PR.
