### ISSUE TITLE
cannot use context.Background() (type context.Context) as type string in argument to conn.QueryRow

### ISSUE THREAD

**Issue by dpthegrey** [jackc/pgx#883]
![Screenshot 2020-11-29 at 9 48 11 PM](https://user-images.githubusercontent.com/49444980/100547441-c9f4b580-328c-11eb-8b8f-ad3a81eb2c3d.png)

I am trying to select the id from the `user_account` table where the email is equal to the email mentioned on line 34. 
The go compiler is complaining that we cannot use `context.Background()` which is of `type context.Context` as `type string` in argument to `conn.QueryRow `

I have seen examples which does in the same manner. I don't know what wrong I am trying to do. Can anyone please teach me how it should be done?

**Comment by jackc** [comment]
Ensure you are importing github.com/jack/pgx/v4. If I had to guess I would say you are using an old version.

**Comment by dpthegrey** [comment]
yes you guessed it right. the go tools imported the older version which I was not aware of. It automatically imported the correct new version in main.go but somehow it didn't worked on this file. Thank you.
