### ISSUE TITLE
SET ROLE statement does not evaluate placeholders (pgx v4.9.2, postgresql v9.6.16)

### ISSUE THREAD

**Issue by yobert** [jackc/pgx#884]
I'm really scratching my head with this bug. It seems like pgx (as of 4.9.2) doesn't evaluate placeholders correctly for some types of statements. Here's my minimal program that shows the crash:

```go
package main

import (
	"fmt"
	"context"

	"github.com/jackc/pgx/v4"
)

func main() {
	ctx := context.Background()

	conn, err := pgx.Connect(ctx, "")
	if err != nil {
		fmt.Println(err)
		return
	}

	if _, err := conn.Exec(ctx, "SET ROLE $1;", "myrole"); err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("success")
}
```

It throws this error for me:

    ERROR: syntax error at or near "$1" (SQLSTATE 42601)

I can work around by changing line 19:

```go
	if _, err := conn.Exec(ctx, "SET ROLE $1;", pgx.QuerySimpleProtocol(true), "myrole"); err != nil {
```

SELECT and INSERT statements seem to work fine without specifying the query protocol.

**Comment by jackc** [comment]
Yeah, that's could be a little surprising. At the protocol level a `SET` statement cannot be parametized. But pgx uses prepared statements / the extended protocol by default. You'd get  the same error in psql:

```
jack@[local]:5432 jack=# prepare s as set role $1;
ERROR:  syntax error at or near "set"
LINE 1: prepare s as set role $1;
                     ^
```

Forcing the simple protocol for that type query or even using `fmt.Sprintf` (obviously your inputs are trusted if you are setting a new role) is the correct solution.

**Comment by yobert** [comment]
Ah, that makes sense. This must be something that my previous client (perl library) did automatically. Thanks for explaining. And thanks for such a great library!
