### ISSUE TITLE
How to work with functions ?

### ISSUE THREAD

**Issue by udf2457** [jackc/pgx#887]
Is there some sort of secret I'm missing to working with PL/pgSQL functions ? pgx is driving me nuts.  Is there some sort of transactioning going on ?!!?

The behaviour I am seeing is that I have a function that `RETURNS boolean`

In my Go debug logging, I can see that (a) the function is called (b) it returns "true". So the queries are _theoretically_ operating as expected.

However, going back and checking Postgres, I only ever see one entry.  That one entry just gets overwritten every time the function is called (the function is a simple wrapper for a single INSERT query).

First I tried with pgxpool.
Then I tried with pgx (because I'm only writing a simple CLI tool)
Then I tried replacing the `db.PGXConn.QueryRow` with `db.PGXConn.Exec` (I know I loose the function return, but I wanted to rule out QueryRow)

The syntax I'm using looks like:
```
_,err := db.PGXConn.Exec(context.Background(),
		"select foo($1,$2,$3,$4,$5,$6)",
		metadata.a,
		metadata.b,
		metadata.c,
		metadata.d,
		metadata.e,
		metadata.f)
	if err != nil {
		log.Fatal().Err(err).Send()
	}

```

`db.PGXConn` is from a struct because I'm (potentially) working with multiple databases :
```
type DBSet struct {
	PebbleDB *PebbleDB
	PGXConn  *pgx.Conn
}
```

PGXConn is established in main() and doesn't get closed until program end (I know this works because of debug logging).

So what am I missing here ?

**Comment by jackc** [comment]
It's not at all clear to me what you are asking...

`Exec` is the proper way to execute a statement (including calling a function) when you don't care about the result. And it sounds like it is executing. I would guess there is something odd in your server side function.
