### ISSUE TITLE
Version and Questions

### ISSUE THREAD

**Issue by Pymann** [jackc/pgx#889]
I just did go get github.com/jackc/pgx and installed it with go install...

Then I removed every v4 subpath from import statements and your examples work.
Is this correct!? I didnt recognize any v4 subfolder in the package? So your examples maybe need an update?

Another question is: 
Can I use the pool for concurrency support with the https://golang.org/pkg/database/sql/ package?

**Comment by jackc** [comment]
If you are using import path `github.com/jackc/pgx` then you are using `v3`. I'm not sure if you are using native pgx or using it as a `database/sql` driver but many of the native `pgx` interfaces are the same from `v3` to `v4` and the `database/sql` stuff is almost entirely unchanged. But you if this is a new project you really should be using `v4`.

pgx uses Go modules so it doesn't need a `v4` subdirectory.

> Can I use the pool for concurrency support with the https://golang.org/pkg/database/sql/ package?

`database/sql` has its own pool so it is not necessary to use pgxpool.

**Comment by Pymann** [comment]
I have an idea for your package, you can maybe enable support for struct-tags, they basically work like this (used with sqlite3 from mattn):

```
package main

import (
"fmt"
"reflect"
"database/sql"
_ "github.com/mattn/go-sqlite3"
)

var db *sql.DB

type User struct {
ID  int `sql:"id"`
  Name      string `sql:"name"`
Password  string `sql:"password"`
}

func main() {
s := User{0, "", ""}
fmt.Println(GetCSTagsOfInterface(s, "sql"))

Open("test.db")

users, err_u := GetInterfaceFromTable(s, "users")
if err_u == nil {
fmt.Printf("%v", users)
} else {
fmt.Printf("%s\n", err_u.Error())
}

}

func GetInterfaceFromTable(v interface{}, table string) ([]User, error) {
abp := []User{}
sqlStmt := fmt.Sprintf("select %s from %s", GetCSTagsOfInterface(v, "sql"), table)
rows, err := db.Query(sqlStmt)
if err != nil {
return abp, err
}
defer rows.Close()
for rows.Next() {
var a User
addr_slice := GetAdressSliceFromInterface(&a)
err = rows.Scan(addr_slice...)
if err != nil {
return abp, err
}
abp = append(abp, a)
}
err = rows.Err()
if err != nil {
return abp, err
}
return abp, nil
}

func GetCSTagsOfInterface(v interface{}, tag string) string {
st := reflect.TypeOf(v)
fieldtags := ""
for i := 0; i < st.NumField(); i++ {
field := st.Field(i)
fieldtags += field.Tag.Get(tag) + ", "
}
return fieldtags[:len(fieldtags)-2]
}

func GetAdressSliceFromInterface(v interface{}) []interface{} {
s := reflect.ValueOf(v).Elem()
typeV := s.Type()
//s = s.Convert(typeV)
/*stval_el.Field(0).SetInt(77)
stval_el.Field(1).SetString("Sunset Strip")
stval_el.Field(2).SetString("Sunset Strip")*/
//stval := reflect.TypeOf(v)
addr_slice := []interface{}{}
for i := 0; i < typeV.NumField(); i++ {
field := s.Field(i)
fmt.Printf("Field %s\n", typeV.Field(i).Name)
if !field.CanSet() {
fmt.Printf("Field %d not to set\n", i)
}

if !field.IsValid() {
fmt.Printf("Field %d not valid\n", i)
}
if field.CanAddr() {
addr_slice = append(addr_slice, field.Addr().Interface())
 } else {
fmt.Printf("Field %d not addressable\n", i)
}
}
return addr_slice
}



func Open(db_path string) error {
var err error
db, err = sql.Open("sqlite3", db_path)
if err != nil {
return err
}
sqlStmt := `create table if not exists users (id integer primary key autoincrement, name text, password text);`
_, err = db.Exec(sqlStmt)
if err != nil {

return err
}
//alter table users add column areas integer not null default 255;
sqlStmt = `insert into users(name, password) values('EhrhardtN', 'wauwau');`
_, err = db.Exec(sqlStmt)
if err != nil {

return err
}
return nil
}
```

**Comment by Pymann** [comment]
> If you are using import path `github.com/jackc/pgx` then you are using `v3`. I'm not sure if you are using native pgx or using it as a `database/sql` driver but many of the native `pgx` interfaces are the same from `v3` to `v4` and the `database/sql` stuff is almost entirely unchanged. But you if this is a new project you really should be using `v4`.
> 
> pgx uses Go modules so it doesn't need a `v4` subdirectory.
> 
> > Can I use the pool for concurrency support with the https://golang.org/pkg/database/sql/ package?
> 
> `database/sql` has its own pool so it is not necessary to use pgxpool.

When I dont remove v4 in import path I get:
psql.go:8:2: cannot find package "github.com/jackc/pgx/v4" in any of:
	/usr/local/go/src/github.com/jackc/pgx/v4 (from $GOROOT)
	/home/nikolai/go/src/github.com/jackc/pgx/v4 (from $GOPATH)

so what to do?

**Comment by jackc** [comment]
It sounds like your project doesn't have a go.mod file.

See https://github.com/jackc/pgx/wiki/Getting-started-with-pgx for a complete getting started guide with native pgx and https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql for a getting started guide with database/sql.

**Comment by Pymann** [comment]
Mh Understood, works now.

What do you think about my idea...

**Comment by Pymann** [comment]
I miss some clear documentation of $1 or $2, it is a replacment for sql/driver's '?' and enumerated?

**Comment by jackc** [comment]
Regarding struct tags, it's an intentional decision to leave that to third party libraries to keep the core driver as simple as possible and to allow for multiple approaches to the data mapping problem. See https://github.com/georgysavva/scany for a pgx native interface solution. See https://github.com/jmoiron/sqlx and https://github.com/go-gorm/gorm for database/sql options.

Regarding `$1` and `$2`, that is standard PostgreSQL syntax for parametized queries. See https://www.postgresql.org/docs/current/sql-prepare.html for examples.
