### ISSUE TITLE
Incorrect example usage in README.MD

### ISSUE THREAD

**Issue by crodwell** [jackc/pgx#890]
The example in README.MD appears to be out of date:
```
conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
```
as pgx.Connect only accepts pgx.ConnConfig as a parameter.

**Comment by jackc** [comment]
That was the case with `v3` but it is not the case with `v4`. See https://pkg.go.dev/github.com/jackc/pgx/v4#Connect.

**Comment by crodwell** [comment]
Yes, I think the quick start examples in the readme should show v4?

**Comment by jackc** [comment]
It does... That's what I'm saying. If it is not working for you you are probably accidentally using `v3`.

**Comment by crodwell** [comment]
oops, sorry. Spot on.. gomodules 👎
