### ISSUE TITLE
Detecting dead pgxpool ?

### ISSUE THREAD

**Issue by udf2457** [jackc/pgx#891]
I can't seem to find the correct way to detect a dead pgxpool ?  i.e. one that has been disconnected through `pgxpool.Pool 
 pgConn.Close`.

I have tried all of the following:
pgConn = nil
pgConn.Stat().TotalConns() == 0
pgConn.Stat().IdleConns() == 0

But I always end up with `closed pool` error being thrown.

Basically I'm looking to re-establish the pool if it's been closed (but avoid running the re-establishment code if the pool is already open).

**Comment by jackc** [comment]
Your examples seem to be mixing a closed connection vs. a closed pool... But you can try to acquire a connection as a test of the pool. If you get the `closed pool` error then the pool is closed.

**Comment by udf2457** [comment]
Thanks @jackc but doesn't trying to acquire a new connection establish a new pool ?  _"Connect creates a new Pool and immediately establishes one connection."_ 

Surely I want to avoid trying to create a new pool if one already exists ? Or does your code take care of that internally ?

**Comment by jackc** [comment]
I think their might be some misunderstanding about the purpose / suggested use of a connection pool. A connection pool handles the creation and destruction of individual connections so the developer doesn't have to. Typically, you should create one connection pool at the beginning of the program and use that for the lifetime of the program. It is very rare to need to close and recreate the pool.

The "immediately establishes on connection" refers to what the pool does on creation. It establishes a single connection immediately to validate that it is possible to connect to the database server.
