### ISSUE TITLE
PKeys from FieldDescriptions

### ISSUE THREAD

**Issue by rodgarcialima** [jackc/pgx#892]
Hey guys, is it possible to get PKeys information from FieldDescriptions, if the PKeys are being returned by the query select?

You guys are doing an amazing job. Thank you

**Comment by jackc** [comment]
I don't think that is possible -- it does not appear to be included in the wire protocol. See https://www.postgresql.org/docs/current/protocol-message-formats.html `RowDescription` message.

**Comment by rodgarcialima** [comment]
I see, thank you very much.
