### ISSUE TITLE
Support driver only settings

### ISSUE THREAD

**Issue by asdine** [jackc/pgx#893]
Certain standard Postgres settings are only meant to be used by the driver and not be sent to the server. I'm thinking of [fallback_application_name ](https://www.postgresql.org/docs/9.6/libpq-connect.html#LIBPQ-CONNECT-FALLBACK-APPLICATION-NAME) for example.

As an example, here is how lib/pq does this:

https://github.com/lib/pq/blob/master/conn.go#L1094-L1120

**Comment by bfontaine** [comment]
ping @jackc for feedback

**Comment by jackc** [comment]
pgx already has the same concept of settings that are not sent to the server.

https://github.com/jackc/pgx/blob/a86acf61e03274a208bbf44a5fe6d70df850e8d6/pgconn/config.go#L281-L300

As far as fallback_application_name in particular, I'd be happy to accept a PR adding support.
