### ISSUE TITLE
Request for a method to get number rows returned from Query

### ISSUE THREAD

**Issue by markandpathak** [jackc/pgx#899]
Thank you for this wonderful library. 

This is a feature request. The rows data type already holds information regarding the fields in the FieldDescription struct. It'll be helpful in numerous situations to get the number of rows returned by the query.

Expected behavior:
Consider the following query:
`select * from table_name where condition;`
There can  be a function which returns the total number of rows returned by the query.
`row_count := rows.RowCount()`

**Comment by jackc** [comment]
There is no way to know how many rows are returned until the query is completely read. But after that you can get the number of rows from the `CommandTag()` method.
