### ISSUE TITLE
Documentation: The return value of PGConn.TxStatus() is not documented

### ISSUE THREAD

**Issue by lamg** [jackc/pgx#900]
`PGConn.TxStatus()` can return `'I'`, `'T'` or `'E'` according [this](https://github.com/jackc/pgx/blob/b6648918538573919deaf55ec6f9f3c29e34412b/pgxpool/pool_test.go#L490-L500) test. The meaning of those values is not specified there or in a reference to the PostgreSQL documentation.

**Comment by jackc** [comment]
Added in https://github.com/jackc/pgconn/commit/e276d9b832bfd155cb35b9080b21827bc5d0f996
