### ISSUE TITLE
Should the same context be used for all requests in a transaction?

### ISSUE THREAD

**Issue by saesols** [jackc/pgx#902]
Hi. Should the same context be used for all interactions with a database in a transaction? Or it's completely fine to use new context on every function call? 

Is it necessary to somehow Release the underlying connection, or rollback/commit release it automatically?
 
```
tx, _ := c.hub.Pool.BeginTx(context.Background(), txOptions)
var newSpaceUUID string
err := tx.QueryRow(context.Background(), "insert into ... returning id", c.id).Scan(&newSpaceUUID)
if err != nil {
_ = tx.Rollback(context.Background())
}
_ = tx.Commit(context.Background())`
```

**Comment by jackc** [comment]
You can use the same context or use a new one at your convenience. The context passed to `BeginTx` is only used to execute the `begin` statement.

Rollback and commit release the underlying connection automatically.

**Comment by saesols** [comment]
Thank you for your comment.
