### ISSUE TITLE
[question] how to send repeat tuple values?

### ISSUE THREAD

**Issue by nvcnvn** [jackc/pgx#903]
Given a table with composite primary key, given an example select statements using `IN (...)`  
```sql
SELECT * FROM table WHERE (a, b) IN ((1, 2), (3, 4), (5, 6), (7, 8), (9, 10))
```
Currently I'm doing an ugly for loop with string builder:
```go
type Key struct {
  A int
  B int
}

var placeHolders []string
counter := 1
var args []int
for _, key := range keys {
  placeHolders = append(placeHolders, printf("($%d, $%d)", counter, counter + 1)
  args =  append(args, key.A, key.B)
  counter += 2
}

query := printf(`SELECT * FROM table WHERE (a, b) IN (%s)`, strings.Join(placeHolders, ","))
// SELECT * FROM table WHERE (a, b) IN (($1, $2), ($3, $4), ($5, $6), ($7, $8), ($9, $10))
db.Exec(ctx, query, args...)
```

I wonder if pgx have any Array type of "tuple" data so I can easy send these data like an TextArray?
```sql
SELECT * FROM table WHERE (a, b) = ANY($1)
```

**Comment by jackc** [comment]
Hmmm...

I don't think that's even possible at the protocol level - at least in the binary format. That would be an array of generic record. I don't think generic record can be used as a parameter in binary.

It might be possible in the text format... Maybe with a combination of `pgtype.CompositeType` and `pgtype.ArrayType` and forcing it to use text encoding...

But if it is possible it's not going to be pretty. A string builder approach is probably the best solution for this problem.

**Comment by nvcnvn** [comment]
OK, thanks you!
Just need to hear from an expert like you to make sure, I will go with string builder approach.
