### ISSUE TITLE
Cannot see table

### ISSUE THREAD

**Issue by rltheis27** [jackc/pgx#904]
I have written a few golang scripts. This is my first attempt trying to connect to a database. I'm trying to insert data into a table. I getting this error message: ERROR: relation "energy" does not exist (SQLSTATE 42P01)

My version of golang: go version go1.15.6 linux/amd64
My version of Postgresql: 11.9
Linux version: Mint 12

I am using the same user id from the command line and my script. The script I'm using is included below. I'm using the select from Information_schema.tables to help debug my script. It showing my script is not seeing my table.

What am I doing wrong?

Logging into postgres directly, I ran the following command from my database (results follow)
$ psql -d solar
psql (11.9 (Debian 11.9-0+deb10u1))
solar=> select table_catalog, table_schema, table_name, table_type from information_schema.tables;
table_catalog |    table_schema    |              table_name               | table_type 
---------------+--------------------+---------------------------------------+------------
 solar         | public             | energy                                | BASE TABLE
 solar         | public             | energy2                               | BASE TABLE
 solar         | pg_catalog         | pg_foreign_table                      | BASE TABLE
 solar         | pg_catalog         | pg_roles                              | VIEW
 solar         | pg_catalog         | pg_settings                           | VIEW
 solar         | pg_catalog         | pg_subscription                       | BASE TABLE
 solar         | pg_catalog         | pg_statio_all_indexes                 | VIEW

Running the same command from my go script, I get:
$ go run insertSolar.go Tesla/2020/Feb/28.csv 
solar	pg_catalog	pg_statistic	BASE TABLE
solar	pg_catalog	pg_foreign_table	BASE TABLE
solar	pg_catalog	pg_authid	BASE TABLE
solar	pg_catalog	pg_shadow	VIEW
solar	pg_catalog	pg_roles	VIEW

################# script #################
package main

import (
    "context"
    "fmt"
    "bufio"
    "io"
    "os"
    "strings"

    pgx "github.com/jackc/pgx"

 )

func main () {
   if len (os.Args [1:]) != 1 {
       fmt.Println ("Syntax error: Need a file name and share precision")
       os.Exit (1)
    }
   filename := os.Args [1]
   filename = strings.TrimSpace (filename)
 
   inFile, error := os.Open (filename)
   if error != nil {
       panic (error)
       os.Exit (1)
    }

   var sql string

	dbConnect := "postgresql://userName@serverName:portNumber/solar"

	conn, err := pgx.Connect (context.Background(), dbConnect)
	if err != nil {
		panic (err)
    }
   
	res, err := conn.Query (context.Background(), "select table_catalog, table_schema, table_name, table_type from information_schema.tables;")
//	res, err := conn.Query (context.Background(), "SHOW search_path")
	if err != nil {
		panic (err)
    }
for res.Next() {
	var (
	   col1 string
	   col2  string
	   col3 string
	   col4 string
	 )
   err = res.Scan(&col1, &col2, &col3, &col4)
   fmt.Printf ("%s\t%s\t%s\t%s\n", col1, col2, col3, col4)
//   err = res.Scan(&col1)
//   fmt.Printf ("%s\n", col1)
}
   
   trans, err := conn.Begin (context.Background())
   if err != nil {
       panic (err)
    }
// Rollback is safe to call even if the tx is already closed, so if
// the trans commits successfully, this is a no-op
   defer trans.Rollback(context.Background())

   inBuf := bufio.NewReader(inFile)
   for {
   	 line, err := inBuf.ReadString ('\n') 
       if err != nil || err == io.EOF {
           break
        }
       line = strings.TrimSpace (line)

       lineItems := strings.Split (line, ",")

       sql = fmt.Sprintf (`insert into energy (eventDate, house, solar, powerwall, grid) 
                           values (%s, %.1f, %.1f, %.1f, %.1f)`,
                           "strings.TrimSpace (lineItems [0])", strings.TrimSpace (lineItems [1]),
                           strings.TrimSpace (lineItems [2]), strings.TrimSpace (lineItems [3]),
                           strings.TrimSpace (lineItems [4]))

       _, err = trans.Exec (context.Background(), sql)
       if err != nil {
           panic (err)
        }

    } // Closes for loop
   err = trans.Commit(context.Background())
   if err != nil {
       panic (err)
    }
   inFile.Close ()
   conn.Close   (context.Background())
 } // Closes main function

**Comment by jackc** [comment]
Here's a few ideas:

1. Make sure you are using pgx `v4`. It looks like you are on `v3`. Shouldn't make any difference here but you still want to use the latest version.
2. Trim this script down to something that just prints the results of your query. There's a lot of extra stuff that may be distracting from the underlying problem.
3. I suspect the problem is you aren't connected to the database you think you are (or something with search_path, but it looks like you already looked into that) Run `select current_database();` in your Go program. Try creating a table in your Go program and see if you can find it with `psql`.

**Comment by cfeng-wm** [comment]
Hello,
I am having same error when executing tx.CopyFrom( ctx, pgx.Identifier{"a3.user"}, []string{....}, rowSrc) using v5.
Any help would be appreciated.
