### ISSUE TITLE
How to work with Savepoints?

### ISSUE THREAD

**Issue by obitech** [jackc/pgx#911]
Hey,

first of all thank you so much for this library, it's been really nice to work with and I appreciate your work and time on this 🎉 

Excuse me this beginner question but how can I work with savepoints inside of a transaction with `pgx`? I assume I have to launch a sub-transaction but I can't figure it out. Basically I want to deal with the following scenario:

1. Start transaction
2. Create savepoint
3. Do some manipulating `Exec` (update, insert, whatever)
4. 💥  Postgres returns an error, something failed
4. Rollback to Savepoint created in 2.
5. ✅  Do stuff again, this time it succeeds
6. Commit transaction

How would this be possible with `pgx` inside a single transaction? I can't seem to figure it out 😞  If someone could give me some pointers, I'd be happy to extend the "Getting started" guide with a PR.

Thanks! ✌️

**Comment by jackc** [comment]
The `Tx` interface includes a `Begin` method that simulates sub-transactions with savepoints. Calling `Begin` on a `Tx` creates a savepoint and returns a new Tx. On that new `Tx` `Commit` and `Rollback` operate on the savepoint.

See the tests for example usage:

`TestTxNestedTransactionCommit`
https://github.com/jackc/pgx/blob/210a217818576dcd21659594d289917b05ee7654/tx_test.go#L303

`TestTxNestedTransactionRollback`
https://github.com/jackc/pgx/blob/210a217818576dcd21659594d289917b05ee7654/tx_test.go#L375
