### ISSUE TITLE
Does pgxpool cache database DNS?

### ISSUE THREAD

**Issue by ivanduka** [jackc/pgx#913]
Hi,

I wonder how pgxpool would behave if connecting to a High Availability AWS RDS Instance and a failover happens.
According to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html, AWS changes the database IP to a stand by instance of a DB.

However, JVM, for example, caches the DB DNS for 60 seconds by default, so a configuration change needed to reduce this TTL.

The question is, does pgxpool cache DNS->IP, and if yes, for how long, and if yes, is this changeable and how to change it.

Thanks!

**Comment by jackc** [comment]
pgxpool uses the Go standard library by default and does not do any DNS caching of its own. DNS lookup can also be customized by changing the `LookupFunc` field of the `pgconn.Config` struct.
