### ISSUE TITLE
net.IP and pg Inet

### ISSUE THREAD

**Issue by spyroot** [jackc/pgx#914]
Hi Folks,

It a bit unclear how to use Inet, and generally, should will driver cast / convert PG INET type directly to 
go net.IP datatype or not.  My initial understanding was It should work without doing anything special.  
So Inet pg type will be translated to net.IP, but it doesn't.  

So my initial understanding Exec will automatically do conversation to net.IP to Inet and vice versa.  
stmt.Get(&t, args...) will translate Inet to net.IP.  As far I understood it was a wrong assumption. 

I based that on the fact if do something like address.String() for net.IP data type, 
it does insert the correct value so the Inet type in PG, but when data selected 
via stmt.Get(&t, args...)  where T is MyType address field holds 
a garbage value.

Below is the struct.

```
type MyType struct {
	Address net.IP `db:"address" yaml:address json:"address"`
..
...
}

// error handling etc removed for a sake of example.
func foo(ctx context, address *net.IP) {
             do_insert(ctx, "INSERT INTO X(address) VALUES($1,) ON CONFLICT (address) DO NOTHING", address)
}

func do_insert(ctx context.Context, sqlStmt string)
        stmt, err := tx.Prepare(sqlStmt)
        stmt.Exec(args...)
```

Now, If I change to the following construct 

```
type MyType struct {
	Address pgtype.Inet `db:"address" yaml:address json:"address"`
..
...
}
```
What is not clear to me.  How I can construct that because of net.IP is Inet pg type but CIDR 
is a different type, in go it IPnet,   Bug pgtypes use net.IPnet for both cases whereas as 
IP doesn't contain Mask/CIDR section. 

It just a 32/128-bit number, and you can't assume a value for a subnet mask if you don't have it 
or don't need it. 

I think that one of the reasons why pg has two types because in the first case, you might just have an IPv4 or IPv6 address
and no knowledge about subnet mask.  (that my case), and In the second case, you know a subnet mask, and in that case, you can use the CIDR data type. For example, if two networks overlap etc.  So it two different use cases.

So, my question How should it work?

For example now if I have Inet record 192.168.1.1 and use pgtype.Inet as a data type for a member of my struct.
I get back 192.168.1.1/32.  /32 is unnecessary and added by pgtype, with IPv6 
it creates even more issues.  

Now consider, if I need to create a struct instead of a net.IP, I forced to create net.IPNet
parse that and append CIDR/Subnet mask to IP address that I have no prior knowledge
about it subnet nor mask. 

I understand that type of mapping is a painful process but for instance, I think it should be two types

pgtype.Inet,   pgtype.CIDR

pgtype.Inet mapped to net.IP
pgtype.CIDR mapped to net.IPNet

**Comment by jackc** [comment]
> It a bit unclear how to use Inet, and generally, should will driver cast / convert PG INET type directly to
go net.IP datatype or not.

It does in the native pgx interface, but not through `database/sql`. It looks like you are using `database/sql`. You'll need to use `pgtype.Inet` and `pgtype.CIDR`.

The reason `pgtype.Inet` uses net.IPNet is that the PostgreSQL type `inet` includes a subnet mask.  See https://www.postgresql.org/docs/current/datatype-net-types.html.

Here's an example: 

```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	"github.com/jackc/pgtype"
	_ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
	db, err := sql.Open("pgx", "")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	_, err = db.Exec("create temporary table t (id serial primary key, ip inet not null);")
	if err != nil {
		log.Fatal(err)
	}

	var paramIP pgtype.Inet
	err = paramIP.Set("10.0.0.0/16")
	if err != nil {
		log.Fatal(err)
	}

	_, err = db.Exec("insert into t (ip) values ($1);", paramIP)
	if err != nil {
		log.Fatal(err)
	}

	var resultIP pgtype.Inet
	err = db.QueryRow("select ip from t").Scan(&resultIP)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(resultIP.IPNet)
}
```

**Comment by spyroot** [comment]
Hi Jack,

I guess you right.  I just notice.   Thank you for checking that!

**Section 8.9.1. inet**

"The inet type holds an IPv4 or IPv6 host address, and optionally its subnet, all in one field"
 
 So subnet is optional,  my initial understanding was PostgreSQL inet use inet for IP 
address and no subnet information (i.e 32 or 128-bit number) and CIDR when you do need subnet information. : -)))

Thank you,
MB>
