### ISSUE TITLE
Circular Dependency

### ISSUE THREAD

**Issue by ImXron** [jackc/pgx#917]
Hi,

I was attempting to import **pgx** (as well as all the jackc packages the are required for v4) into our in-house build / dependency resolution system at work and ran into a circular dependency issue.

Looking at some of the **go.mod** files I see that [**pgx** ](https://github.com/jackc/pgx/blob/v4.10.1/go.mod#L11)depends on **pgtype**, but [**pgtype** ](https://github.com/jackc/pgtype/blob/v1.6.2/go.mod#L9)depends on **pgx**?

Similar with [**pgconn**](https://github.com/jackc/pgconn/blob/v1.8.0/go.mod#L8), it depends on **pgmock**, but [**pgmock** ](https://github.com/jackc/pgmock/blob/master/go.mod#L6)depends on **pgconn**?

I got around **pgconn's** dependency on **pgmock** by disabling some tests (which is common when importing open source packages into our system). But looks like **pgconn** uses **pgx** in a [**non test file**](https://github.com/jackc/pgtype/blob/376361f53ddd86ad4381ee4e5d5a802fa33c3de7/pgxtype/pgxtype.go#L14-L15).

Any suggestions on how to work around this? Is the [**pgtype/pgxtype** ](https://github.com/jackc/pgtype/blob/376361f53ddd86ad4381ee4e5d5a802fa33c3de7/pgxtype/pgxtype.go)package required? 

Thanks!

**Comment by jackc** [comment]
go.mod files include tests. pgtype doesn't depend on pgx, but its tests use pgx to test round tripping values to a real server.

The pgtype/pgxtype package is not required. It's basically just some helper methods to deal with custom types.

**Comment by ImXron** [comment]
Ah, good to know.

Thanks!
