### ISSUE TITLE
Use cloudsqlproxy dialer

### ISSUE THREAD

**Issue by pcriv** [jackc/pgx#920]
Is it possible to use pgx with the google cloud proxy dialer?

https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/dialers/postgres/hook_test.go

**Comment by jackc** [comment]
No, it is hard-coded to `lib/pq`.

https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/4dfde25b991c55993b761ae9d202d7db400971f8/proxy/dialers/postgres/hook.go#L31

But my guess is it would only take a few changes to make it use pgx instead.

**Comment by pcriv** [comment]
Hmm, not sure if they would be up for changing it but I could give it a try 
Thanks for your reply!

**Comment by pcriv** [comment]
Looks like there is a discussion already going on: https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/433
