### ISSUE TITLE
pgxpool.Acquire() not creating connections

### ISSUE THREAD

**Issue by bkeroackdsc** [jackc/pgx#922]
I'm probably misunderstanding how pgxpool works, but I'm following a pattern of using `pgxpool.Acquire()` to get a conn to perform long-running "LISTEN <channel>" queries, in addition to more conventional short-lived DB queries (SELECT, INSERT, etc) using `pgxpool.Exec/Query`.

I've noticed that I have to set `config.MinConns` to the maximum number of concurrent operations my application might expect, otherwise the LISTEN code sometimes fails to obtain a connection and returns an error.

I was under the assumption that Acquire() would create new connections as needed as long as total connections stay under `config.MaxConns`. If this is not the case, is the best practice to create new connections outside of the pool for the LISTEN queries?

**Comment by jackc** [comment]
`Acquire` should create a connection as needed. And I think you have the right idea for `LISTEN`. Acquiring a connection long-term should be fine. `config.MinConns` shouldn't have anything to do with it.

Do you have example code that exhibits this issue?

**Comment by bkeroackdsc** [comment]
I took a look again at my code and it turns out I wasn't setting MaxConns at all, so with that fix I can leave MinConns at a low number and Acquire() seems to be creating new connections on demand. Thanks for the clarification.
