### ISSUE TITLE
How to keep a pool open with zero connections?

### ISSUE THREAD

**Issue by dan-lovelace** [jackc/pgx#923]
I'm building an API using AWS Lambda and trying to figure out how to reuse pools between executions without keeping an idle connection between invocations. The execution environment stays active for about 15 minutes and my current implementation retains one open connection per environment for the entire 15 minutes. I'd like to see these connections closed after use while keeping the pool active for subsequent invocations. Here's my initialization method:

```go
// db.go
var cachedPool *pgxpool.Pool

func GetDBPool(ctx context.Context, secret string) (*pgxpool.Pool, error) {
    if cachedPool != nil {
	return cachedPool, nil
    }

    config, err := pgxpool.ParseConfig(secret)
    if err != nil {
	return nil, err
    }

    config.MaxConns = 1
    config.LazyConnect = true

    dbpool, err := pgxpool.ConnectConfig(ctx, config)
    if err != nil {
        return nil, err
    }

    cachedPool = dbpool
    return cachedPool, nil
}
```

At this point I expect there to be zero connections if I call `GetDBPool`. Here's an example of how I create new connections

```go
// handler.go
func List(ctx context.Context, event LambdaEvent) LambdaResponse {
    pool, err := GetDBPool(ctx, secret)
    if err != nil {
	return LambdaResponse{Error: err.Error()}
    }

    querier, err := pool.Acquire(ctx)
    if err != nil {
	return LambdaResponse{Error: err.Error()}
    }
    defer querier.Release()

    // app logic...
    qErr := pgxscan.Select(ctx, querier, &rows, sql, args...)
    // more app logic...

    return LambdaResponse{Data: "done"}
}
```

When I run this, I expect `Acquire` to create the very first connection and then release it when the `List` function returns - putting the open connection stat to `0`. However, when I check my connections at the database level, I see one open connection until the Lambda environment itself is destroyed, about 15 minutes after the function is invoked.

Now, I realize I never call `dbpool.Close()` but that's because I don't actually want to close it. I'd like the pool to remain available for the duration of the execution context, at least 15 minutes, without keeping an open connection the whole time.

I've dug around and I found something in v3 that looks like it could be promising: https://godoc.org/gopkg.in/jackc/pgx.v3#ConnPool.Reset - `ConnPool.Reset`:

> Reset closes all open connections, but leaves the pool open.

I was thinking I could call something like this at the end of each execution to release connections between invocations but nothing like this seems to be available in v4. Any idea how I might achieve this?

I also found this recent-ish ticket from someone else that sounds like maybe they're trying to do something similar: https://github.com/jackc/pgx/issues/891

**Comment by jackc** [comment]
You probably want to set the `pgxpool.Config` fields `HealthCheckPeriod` and `MaxConnIdleTime` to a short duration. That would allow the the connection to be reused if another request comes in quickly, but not keep the connection open for a long period.

On the other hand, if you _really_ want to close and reopen a connection each time then you could open and close connections directly instead of using a pool.

**Comment by dan-lovelace** [comment]
Thanks @jackc. This ended up being caused by how AWS handles the Lambda environment itself. It is not possible to implement a health check as on a typical server. The solution is to use some kind of proxy, in my case AWS RDS Proxy: https://aws.amazon.com/rds/proxy/.
