### ISSUE TITLE
Scanning value into sql.NullString converts value to scientific notation.

### ISSUE THREAD

**Issue by lesovsky** [jackc/pgx#925]
Hi, found the behavior which confuses me a bit. When I scan value into `sql.NullString` variable it then stored in scientific notation. Scanning into `sql.NullFloat64` or builtin `string` keep value as is.

```
CREATE TABLE tt (a numeric)
INSERT INTO tt SELECT 0.051426;
```

This code below prints `{51426e-6 true}`:
```
var v sql.NullString
_ = conn.QueryRow("SELECT a FROM tt LIMIT 1").Scan(&v))
fmt.Println(v) 
```

This prints `0.051426`:
```
var v string
_ = conn.QueryRow("SELECT a FROM tt LIMIT 1").Scan(&v))
fmt.Println(v)
```

This prints `{0.051426 true}`:
```
var v sql.NullFloat64
_ = conn.QueryRow("SELECT a FROM tt LIMIT 1").Scan(&v))
fmt.Println(v)
```

Is it possible to keep origin value when scanning into sql.NullString?

**Comment by jackc** [comment]
The original value is the PostgreSQL numeric binary format. i.e. It is not a `string` or a `float64`. It has to be converted to the other types. Apparently, the different conversion paths format strings differently.

**Comment by lesovsky** [comment]
I think this is specific to pgx.Scan() implementation. Using sql.Scan() with sql.NullString keep numbers as is, without conversion to scientific notation.

**Comment by jackc** [comment]
It also depends on whether pgx is being used through `database/sql` or directly. For compatibility with `database/sql` the types that use the binary format are restricted in `database/sql`. `numeric` is one of the types that has to be transferred in text format.

See for list of binary types:

https://github.com/jackc/pgx/blob/922508c785f7cc4ffe97a802ef8c4b202a05802e/stdlib/sql.go#L89-L103
