### ISSUE TITLE
Syntax not being highlighted when using JetBrains IDE

### ISSUE THREAD

**Issue by leviinz** [jackc/pgx#926]
The SQL syntax is not being highlighted in code when using GoLand (or any JetBrains IDE that supports it.) I'm not sure if there's a way to fix it on my end or if it's an issue with PGX. I did notice that many of the Go functions (like QueryContext: https://golang.org/pkg/database/sql/#Conn.QueryContext) has the query variable named as "query" whereas pgx has it named "sql". I'm unsure if this is the issue or not. A temporary fix is to inject SQL into a specific string but it doesn't do it for every function call.

**Comment by LeviDevs** [comment]
Somewhat of a workaround is by adding "// language PostgreSQL" or "// language psql" above the line with the query. I would still like to know if there's a permanent solution though.

I also noticed that every driver seems to not highlight the syntax, my mistake if this isn't an issue with this project directly. I'm curious if anyone has a permanent solution.

**Comment by kunKun-tx** [comment]
`// language=PostgreSQL` works for me in GoLand.
