### ISSUE TITLE
Why does the chat example uses connection pooling + how to asynchronously WaitForNotification?

### ISSUE THREAD

**Issue by Sjoerd82** [jackc/pgx#928]
Hi, I am trying to understand how to build a listen/notify program that forwards PostgreSQL notifications over SSE (a http connection). For this, I am looking at the chat example, and have two questions (I hope this the right place, I couldnt find a forum/discord/...).

[The "Chat" example](https://github.com/jackc/pgx/tree/master/examples/chat)

_First_, I wonder why it uses a connection pool? The program only ever uses one connection. Why is a connection pool chosen over a 'normal' connect? About pooling: [Getting started with gpx](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx)

_Second_, is there a way to asynchronously wait/listen for notifications to come in?
I have a working version that uses the `libs/pq` library (see below), but that library is not actively maintained, so I prefer to use this `jackc/pgx` library.

In  libs/pq, one can set up a listener like so:
`listener := pq.NewListener(conninfo, 10*time.Second, time.Minute, reportProblem)`

In pgx, we have:
`conn.WaitForNotification` as described by [Listen and Notify](https://pkg.go.dev/github.com/jackc/pgx/v4/#hdr-Listen_and_Notify).
How can we use it asynchronously in a loop?

This is what I have now, using libs/pq. I have only started in Go since a few days, so I may approach this all wrong...?

```
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"
	"bytes"
	"database/sql"
	"encoding/json"
	"github.com/subchord/go-sse"
	"github.com/lib/pq"
)

type API struct {
	broker *net.Broker
}

func main() {
	sseClientBroker := net.NewBroker(map[string]string{
		"Access-Control-Allow-Origin": "*",
	})
	
	api := &API{broker: sseClientBroker}

	http.HandleFunc("/sse", api.sseHandler)
	
	var conninfo string = "dbname=mydb user=postgres password=REDACTED sslmode=disable"
	_, err := sql.Open("postgres", conninfo)
	if err != nil {
		panic(err)
	}

	reportProblem := func(ev pq.ListenerEventType, err error) {
		if err != nil {
			fmt.Println(err.Error())
		}
	}

	listener := pq.NewListener(conninfo, 10*time.Second, time.Minute, reportProblem)
	err = listener.Listen("events")
	if err != nil {
		panic(err)
	}

	fmt.Println("Start monitoring PostgreSQL...")	
	// I think "go func()" starts a concurrent function (?)
	go func() {
		for {		
			select {
			case n := <-listener.Notify:
				fmt.Println("Received data from channel [", n.Channel, "] :")
				
				// Prepare notification payload for pretty print
				api.broker.Broadcast(net.StringEvent{
					Event: "message",
					Data:  string([]byte(n.Extra)),
				})
			case <-time.After(90 * time.Second):
				fmt.Println("Received no events for 90 seconds, checking connection")
				go func() {
					listener.Ping()
				}()
			}		
		}
	}()

	fmt.Println("Starting server at port 81...")
	log.Fatal(http.ListenAndServe(":81", http.DefaultServeMux))

}

func (api *API) sseHandler(writer http.ResponseWriter, request *http.Request) {
	client, err := api.broker.Connect(fmt.Sprintf("%v", time.Now().Unix()), writer, request)
	if err != nil {
		log.Println(err)
		return
	}
	<-client.Done()
	log.Printf("connection with client %v closed", client.Id())
}

```

**Comment by jackc** [comment]
> First, I wonder why it uses a connection pool? The program only ever uses one connection.

It uses two connections. One to listen for messages and one to send notify messages.

https://github.com/jackc/pgx/blob/922508c785f7cc4ffe97a802ef8c4b202a05802e/examples/chat/main.go#L38
https://github.com/jackc/pgx/blob/922508c785f7cc4ffe97a802ef8c4b202a05802e/examples/chat/main.go#L51

> Second, is there a way to asynchronously wait/listen for notifications to come in?

Run `WaitForNotification` in a goroutine like how the listener is in the example.

https://github.com/jackc/pgx/blob/922508c785f7cc4ffe97a802ef8c4b202a05802e/examples/chat/main.go#L22

**Comment by Sjoerd82** [comment]
Thanks for clarifying, this is very helpful for me to scale that initial Go learning curve 👍.

Just for my understanding, what if you only need one connection (in my case, I'm only listening, never sending), should you still use a pool (are there still benefits left?) or should you use the "simple" connect?

Second, yes that `go listen()` is working, I receive asynch. notifications, but now, how to get these back into the main loop (where the SSE broker is). I'm reading that Go has a thing called "channels", and looking at the libs/pq code above, I get the feeling that `pq.NewListener` returns data via a channel, as indicated by:
```
			select {
			case n := <-listener.Notify:
				fmt.Println("Received data from channel [", n.Channel, "] :")
```
Any advice, or perhaps an example on how to make the listen() function channeling the pgx notifications?
Or am I totally going in the wrong direction with channels?

This is the listen function:
```
func listen() {
	conn, err := pool.Acquire(context.Background())
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error acquiring connection:", err)
		os.Exit(1)
	}
	defer conn.Release()

	_, err = conn.Exec(context.Background(), "listen events")
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error listening to chat channel:", err)
		os.Exit(1)
	}

	for {
		notification, err := conn.Conn().WaitForNotification(context.Background())
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error waiting for notification:", err)
			os.Exit(1)
		}

		fmt.Println("PID:", notification.PID, "Channel:", notification.Channel, "Payload:", notification.Payload)

	}
}
```

**Comment by jackc** [comment]
> Just for my understanding, what if you only need one connection (in my case, I'm only listening, never sending), should you still use a pool (are there still benefits left?) or should you use the "simple" connect?

No need to use a pool in that case.

> Second, yes that go listen() is working, I receive asynch. notifications, but now, how to get these back into the main loop (where the SSE broker is). I'm reading that Go has a thing called "channels"

Yes, channels are how you would connect this to the rest of your program. You would write to the channel in your listen loop and read from it in the rest of your program. The exact details would depend on your program.

**Comment by Sjoerd82** [comment]
Thanks, I've got it all working now. While learning about channels I started to understand that this is actually not required as variables from the calling function are available in concurrent goroutines:

```
package main

import (
	"fmt"
	"log"
	"time"
	"context"
	"os"
	"net/http"

	"github.com/subchord/go-sse"
	//"github.com/jackc/pgx/v4/pgxpool" // Connection pooling
	"github.com/jackc/pgx/v4"
)

//var pool *pgxpool.Pool
var conn *pgx.Conn

type API struct {
	broker *net.Broker
}

func main() {
	// DATABASE
	var err error
	// when using more than one connection, use Connection Pooling.
	//pool, err = pgxpool.Connect(context.Background(),"postgresql://myuser:secret@myhost:5432/mydb") //os.Getenv("DATABASE_URL")
	conn, err = pgx.Connect(context.Background(),"postgresql://myuser:secret@myhost:5432/mydb") //os.Getenv("DATABASE_URL")
	if err != nil {
		fmt.Fprintln(os.Stderr, "Unable to connect to database:", err)
		os.Exit(1)
	}
	
	// SSE
	sseClientBroker := net.NewBroker(map[string]string{
		"Access-Control-Allow-Origin": "*",
	})
	api := &API{broker: sseClientBroker}
	http.HandleFunc("/sse", api.sseHandler)
	
	// Concurrent loop: LISTEN
	fmt.Println("Start monitoring PostgreSQL...")
	go func() {
		//conn, err := pool.Acquire(context.Background()) // Connection pooling
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error acquiring connection:", err)
			os.Exit(1)
		}
		//defer conn.Release() <---- this or similar needed for a single connection???

		_, err = conn.Exec(context.Background(), "listen last_modified")
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error listening to 'last_modified' channel:", err)
			os.Exit(1)
		}

		_, err = conn.Exec(context.Background(), "listen user_tx")
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error listening to 'user_tx' channel:", err)
			os.Exit(1)
		}

		for {
			//notification, err := conn.Conn().WaitForNotification(context.Background()) // Connection pooling
			notification, err := conn.WaitForNotification(context.Background())
			if err != nil {
				fmt.Fprintln(os.Stderr, "Error waiting for notification:", err)
				os.Exit(1)
			}

			fmt.Println("PID:", notification.PID, "Channel:", notification.Channel, "Payload:", notification.Payload)
			api.broker.Broadcast(net.StringEvent{
				Event: notification.Channel,
				Data:  notification.Payload,
			})

		}
	}()

	// Start server (ListenAndServe blocks until an error is received)
	fmt.Println("Starting server at port 81...")
	log.Fatal(http.ListenAndServe(":81", http.DefaultServeMux))
}

func (api *API) sseHandler(writer http.ResponseWriter, request *http.Request) {
	client, err := api.broker.Connect(fmt.Sprintf("%v", time.Now().Unix()), writer, request)
	if err != nil {
		log.Println(err)
		return
	}
	<-client.Done()
	log.Printf("connection with client %v closed", client.Id())
}
```
This works.
