### ISSUE TITLE
Does Acquire return the same connection used in BeforeAcquire?

### ISSUE THREAD

**Issue by YNWA** [jackc/pgx#929]
Hello, 

could you please provide some clarification about the `pgxpool.Config.BeforeAcquire` callback?
We tried to use it to check a connection health by making a ping inside the `BeforeAcquire`.

```
func (p *Pool) Acquire(ctx context.Context) (*Conn, error) {
	for {
		res, err := p.p.Acquire(ctx)
		if err != nil {
			return nil, err
		}

		cr := res.Value().(*connResource)
		if p.beforeAcquire == nil || p.beforeAcquire(ctx, cr.conn) {
			return cr.getConn(p, res), nil
		}

		res.Destroy()
	}
}
```

I'm pretty new to go, so maybe my assumptions are wrong... looks like `pgxpool.Pool.Acquire` after calling `p.beforeAcquire(ctx, cr.conn)` actually returns another connection from the pool, not the one we've just checked. It kind of makes the ping thing useless.

Could it be possible to return the very same connection that was passed to `p.beforeAcquire (ctx, cr.conn)`?

**Comment by jackc** [comment]
> Could it be possible to return the very same connection that was passed to p.beforeAcquire (ctx, cr.conn)?

It already does.

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/jackc/pgx/v4"
	"github.com/jackc/pgx/v4/pgxpool"
)

func main() {
	poolConf, err := pgxpool.ParseConfig(os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatal(err)
	}

	poolConf.BeforeAcquire = func(ctx context.Context, conn *pgx.Conn) bool {
		log.Printf("BeforeAcquire conn: %p\n", conn)
		return true
	}

	pool, err := pgxpool.ConnectConfig(context.Background(), poolConf)
	if err != nil {
		log.Fatal(err)
	}
	defer pool.Close()

	conn, err := pool.Acquire(context.Background())
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Release()

	log.Printf("Acquire conn: %p\n", conn.Conn())
}
```

```
jack@glados ~/dev/pgx_issues/pgx-929 ±master⚡ » go run main.go
2021/02/04 19:29:42 BeforeAcquire conn: 0xc00012afc0
2021/02/04 19:29:42 Acquire conn: 0xc00012afc0
```

**Comment by YNWA** [comment]
Hey, thanks for the reply.
Sorry, I should've given more details about how we ended up with different connections.

```go
// CheckConn is a draft of our BeforeAcquire function
func (d *DB) CheckConn(ctx context.Context, pgc *pgx.Conn) bool {
	if err := pgc.Ping(ctx); err != nil {
		attempt := 0
		ticker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()

		for range ticker.C {
			if attempt >= maxRetry {
				d.log.Info().Msg("postgres: max reconnect attempt")
				return false
			}
			attempt++

			d.log.Info().Msg("postgres: try to reconnect")

			newPgc, connErr := d.Pool.Acquire(ctx)
			if connErr != nil {
				d.log.Error().Err(err).Msg("postgres: lost connection")
				continue
			}

			pgc = newPgc.Conn()
			break
		}
	}

	return pgc != nil
}
```


If the connection has died, we try to acquire another connection from the pool until we get a good one.
Since the connection is passed by pointer, I thought that reassignment might work `pgc = newPgc.Conn()`, but in this case we get a different connection that runs the actual query.
Is there any way to handle this?

**Comment by jackc** [comment]
That's totally not how `BeforeAcquire` is designed to be used. All you have to do is return false if the connection is not acceptable. The pool handles acquiring another connection.

See https://github.com/jackc/pgx/blob/922508c785f7cc4ffe97a802ef8c4b202a05802e/pgxpool/pool.go#L373.

Your 5 second timeout could be handled by passing a context to `Acquire`.

**Comment by YNWA** [comment]
Can't argue with that. The approach I described above doesn't look good to me either.

What I'm trying to achieve in general is reconnection with an exponential backoff after a network failure.
In that case everything stops right here
https://github.com/jackc/pgx/blob/922508c785f7cc4ffe97a802ef8c4b202a05802e/pgxpool/pool.go#L375-L378

I think I'd better open another issue to discuss that.

So BeforeAcquire is fine, thanks for your answers.
