### ISSUE TITLE
Is there no conn.IsAlive? (autoreconnect)

### ISSUE THREAD

**Issue by Sjoerd82** [jackc/pgx#930]
I'm seeing references (on the internet and in past issues) to a method called `IsAlive()` on the `pgx.Conn` structure, however, it seems to not exist anymore. It's not in the documentation and when used I get an error:

`conn.IsAlive undefined (type *pgx.Conn has no field or method IsAlive)`

Is there a replacement for this? I'm attempting to make my code a bit more robust by reconnecting after a connection drops:

```
		for {
			notification, err := conn.WaitForNotification(context.Background())
			if err != nil {
				fmt.Fprintln(os.Stderr, "Error waiting for notification:", err)
				//os.Exit(1) // bad!! keep me alive!
				connected := conn.IsAlive()
				for connected != true { // reconnect if we lost connection
					log.Print("Connection to Postgres was lost. Waiting for 30s...")
					conn.Close()
					time.Sleep(30 * time.Second)
					log.Print("Reconnecting...")
					conn = connectToDb()
					connected = conn.IsAlive()
				 }
			}

			fmt.Println("PID:", notification.PID, "Channel:", notification.Channel, "Payload:", notification.Payload)
			api.broker.Broadcast(net.StringEvent{
				Event: notification.Channel,
				Data:  notification.Payload,
			})

		}
	}()
```

This is connectToDB:

```
func connectToDB() *pgx.Conn {
	conn, err := pgx.Connect(context.Background(),"postgresql://user:secret@host:5432/mydb") 
	if err != nil {
		log.Print(err)
		log.Print("Could not connect to Postgres.")
		return &pgx.Conn{}
	}
	return conn
}
```

Since this runs on a VPS somewhere out of sight, I'd like for this to be as stable as possible.

**Comment by jackc** [comment]
`IsAlive` was in `v3`. But it was a bit ambiguous regarding whether the connection was alive at last usage or it should actually test the connection.

In `v4` [IsClosed](https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.IsClosed) indicates if the connection has been closed (possibly due to error). [Ping](https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.Ping) tests the connection by pinging the server.

**Comment by Sjoerd82** [comment]
It seems that pinging a database that has been brought back online still fails. So, in any case I need to do a connect() first. What would be the added benefit of a Ping when I can simply attempt reconnects like this:

```
package main

import (
	"fmt"
	"log"
	"time"
	"context"
	"os"
	"net/http"

	"github.com/subchord/go-sse"
	"github.com/jackc/pgx/v4"
)

var conn *pgx.Conn

type API struct {
	broker *net.Broker
}

func main() {
	// DATABASE
	conn = connectToDB()
	if conn == nil {
		fmt.Fprintln(os.Stderr, "Unable to connect to database:")
		os.Exit(1)
	}
	
	// SSE
	sseClientBroker := net.NewBroker(map[string]string{
		"Access-Control-Allow-Origin": "*",
	})
	api := &API{broker: sseClientBroker}
	http.HandleFunc("/sse", api.sseHandler)
	
	// Concurrent loop: LISTEN
	fmt.Println("Start monitoring PostgreSQL...")
	go func() {
		for {
			// Blocking
			notification, err := conn.WaitForNotification(context.Background())
			if err != nil {
				fmt.Fprintln(os.Stderr, "Error waiting for notification:", err)
				//os.Exit(1)

				//Perhaps check isClosed?
				//fmt.Println(conn.IsClosed())
			
				for {
					time.Sleep(5 * time.Second)
					log.Print("Reconnecting...")
					conn = connectToDB()
					if conn != nil {
						break // we're reconnected, stop the retry loop
					}
				}
			} else {
				fmt.Println("PID:", notification.PID, "Channel:", notification.Channel, "Payload:", notification.Payload)
				api.broker.Broadcast(net.StringEvent{
					Event: notification.Channel,
					Data:  notification.Payload,
				})
			}
		}
	}()

	// Start server (ListenAndServe blocks until an error is received)
	fmt.Println("Starting server at port 81...")
	log.Fatal(http.ListenAndServe(":81", http.DefaultServeMux))
}

func connectToDB() *pgx.Conn {
	conn, err := pgx.Connect(context.Background(),"postgresql://REDACTED")
	if err != nil {
		log.Print(err)
		log.Print("Could not connect to database")
		//return &pgx.Conn{}	// causes panic: runtime error: invalid memory address or nil pointer dereference
		//return conn           // causes panic: runtime error: invalid memory address or nil pointer dereference
		return nil
	} else {
		log.Print("Connected!")
	
		_, err = conn.Exec(context.Background(), "listen last_modified")
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error listening to 'last_modified' channel:", err)
			os.Exit(1) // what reasons could exist for this to happen??
		}

		_, err = conn.Exec(context.Background(), "listen user_tx")
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error listening to 'user_tx' channel:", err)
			os.Exit(1) // what reasons could exist for this to happen??
		}

		return conn
	}
}

func (api *API) sseHandler(writer http.ResponseWriter, request *http.Request) {
	client, err := api.broker.Connect(fmt.Sprintf("%v", time.Now().Unix()), writer, request)
	if err != nil {
		log.Println(err)
		return
	}
	<-client.Done()
	log.Printf("connection with client %v closed", client.Id())
}
```

This reconnect works when bring the db up/down, but perhaps there are situations for which it won't work?

**Comment by jackc** [comment]
> What would be the added benefit of a Ping

I've never used it directly. It's more something that can be used as part of a health check.

But I would use a pgxpool rather than dealing with reconnecting manually. You would still have a loop to retry after a connection loss but the actual establishing of a new connection would be handled by the pool.

**Comment by Sjoerd82** [comment]
While playing with this, I'm noticing the following:

- I do not need to set up a new pgxpool.Connect, a pool.Acquire is enough to "reconnect" with the database.
- It seems that each .Acquire is its own database session. If I do an Acquire to issue a `LISTEN channel` and later do an Acquire to WaitForNotification, it's not receiving any NOTIFY's.

Are the above correct?

So, I reached the following conclusion on how to pool/auto-reconnect
in main():
1. Create pool/connection: pool, err = pgxpool.Connect (and exit if it fails)
2. Call a function ("`acquireListenConn`") that Acquires a connection, issue the LISTEN's and pass the `conn` variable back to main.
3. Start infinite loop:
4. Call WaitForNotification, using the `conn` variable (blocks).
4a. Success => handle it
4b. Fail => Wait 5s and call "`acquireListenConn`" to retry to acquire a new connection, including issued LISTEN's.

Is a `defer conn.Release()` required? I have put it after the infinite loop, but I doubt is does anything useful.

In the end, this seems to work (and I learned a lot over the last few days), but I would really appreciate it if you could take a few minutes to see if I didn't make any blatant mistakes (any tips for improvement would also be appreciated, but it seems this issue board is quite overwhelming, so I def understand time constraints on your part).

```
package main

import (
	"fmt"
	"log"
	"time"
	"context"
	"os"
	"net/http"

	"github.com/subchord/go-sse"
	"github.com/jackc/pgx/v4/pgxpool"
)

var pool *pgxpool.Pool

type API struct {
	broker *net.Broker
}

func main() {
	// DATABASE
	var err error
	pool, err = pgxpool.Connect(context.Background(),"postgresql://REDACTED")
	if err != nil {
		fmt.Fprintln(os.Stderr, "Unable to connect to database:", err)
		os.Exit(1)
	}
	// Acquire Conn and subscribe to PostgreSQL NOTIFY event channels
	conn := acquireListenConn()
	if conn == nil {
		fmt.Fprintln(os.Stderr, "Unable to acquire a connection")
		os.Exit(1)
	}
	
	// SSE
	sseClientBroker := net.NewBroker(map[string]string{
		"Access-Control-Allow-Origin": "*",
	})
	api := &API{broker: sseClientBroker}
	http.HandleFunc("/sse", api.sseHandler)
	
	// Concurrent loop: LISTEN
	fmt.Println("Start monitoring PostgreSQL...")
	go func() {
		for {
			notification, err := conn.Conn().WaitForNotification(context.Background()) // Blocks
			if err != nil {
				fmt.Fprintln(os.Stderr, "Error waiting for notification:", err)
				for {
					time.Sleep(5 * time.Second)
					conn = acquireListenConn()
					if conn != nil {
						break // we're reconnected, stop the retry loop
					}
				}
			} else {
				// Handle received notification
				fmt.Println("PID:", notification.PID, "Channel:", notification.Channel, "Payload:", notification.Payload)
				api.broker.Broadcast(net.StringEvent{
					Event: notification.Channel,
					Data:  notification.Payload,
				})
			}
		}
		defer conn.Release()
	}()

	// Start server (ListenAndServe blocks until an error is received)
	fmt.Println("Starting server at port 81...")
	log.Fatal(http.ListenAndServe(":81", http.DefaultServeMux))
}

func acquireListenConn() *pgxpool.Conn {
	conn, err := pool.Acquire(context.Background())
	if err != nil {
		fmt.Fprintln(os.Stderr, "Could not acquire a connection: ", err)
		//return &pgx.Conn{}	// causes panic: runtime error: invalid memory address or nil pointer dereference
		//return conn           // causes panic: runtime error: invalid memory address or nil pointer dereference
		return nil
	} else {
		log.Print("Connected to PostgreSQL")
	
		// #TODO: make this more dynamic: array of channels+loop
		_, err = conn.Exec(context.Background(), "listen last_modified")
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error listening to 'last_modified' channel:", err)
			os.Exit(1) // what reasons could exist for this to happen??
		}

		_, err = conn.Exec(context.Background(), "listen user_tx")
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error listening to 'user_tx' channel:", err)
			os.Exit(1) // what reasons could exist for this to happen??
		}
		log.Print("Subscribed to: last_modified, user_tx")

		return conn
	}
}

func (api *API) sseHandler(writer http.ResponseWriter, request *http.Request) {
	client, err := api.broker.Connect(fmt.Sprintf("%v", time.Now().Unix()), writer, request)
	if err != nil {
		log.Println(err)
		return
	}
	<-client.Done()
	log.Printf("connection with client %v closed", client.Id())
}
```

**Comment by jackc** [comment]
> I do not need to set up a new pgxpool.Connect, a pool.Acquire is enough to "reconnect" with the database.
    It seems that each .Acquire is its own database session. If I do an Acquire to issue a LISTEN channel and later do an Acquire to WaitForNotification, it's not receiving any NOTIFY's.

Correct.

> Is a defer conn.Release() required? I have put it after the infinite loop, but I doubt is does anything useful.
>
> In the end, this seems to work (and I learned a lot over the last few days), but I would really appreciate it if you could take a few minutes to see if I didn't make any blatant mistakes (any tips for improvement would also be appreciated, but it seems this issue board is quite overwhelming, so I def understand time constraints on your part).

The overall approach is reasonable. But the current implementation can leak connections if a panic occurs in your goroutine or the WaitForNotification returns an error. The `defer.Release` should definitely not be at the bottom -- it will never be called there. It should be somewhere else.

Off the top of my head I'm not sure the exact structure I would use but I probably would restructure the goroutine such that the initial connection acquire occurs inside of it. I'd probably move the core logic into another function called by the goroutine so defer could be used more effectively.

**Comment by Sjoerd82** [comment]
Thanks, I'll have to sit on that restructure, but that's outside the scope of the question.

**Comment by ansel1** [comment]
Following up on this, the pq notify/listen example has a curious thing where they periodically Ping() the conn if they haven't received a message for a while.  I assume that's because pq won't notice the conn is dead and close the notification channel unless you actively Ping() from time to time.

Does pgx require something similar?  The notify/listen example just calls WaitForNotification and potentially blocks forever.  If the conn goes stale in the background, will WaitForNotification return, or should I Ping() the connection once and a while to check its health?

**Comment by jackc** [comment]
`WaitForNotification` does not do any automatic pinging.
