### ISSUE TITLE
Question about identifying connection errors

### ISSUE THREAD

**Issue by mxmauro** [jackc/pgx#933]
Hi, I have a question

Is it possible to identify/differentiate connection errors from others?

I would like to retry the operation if the link to the server is lost, else stop.

Can search for the `write failed` (of `writeError` struct) or `failed to connect` (from `connectError`) but not sure how reliable because strings can change in the future.

Thanks,
Mauro.

**Comment by jackc** [comment]
You can use `errors.Is` or `errors.As` and see if the underlying error is a `net.Error`.

**Comment by mxmauro** [comment]
Excellent. Thanks for the answer.

Kind regards :)
