### ISSUE TITLE
connection hangs forever on db failover

### ISSUE THREAD

**Issue by donkeyx** [jackc/pgx#936]
I have a simple script which I am monitoring the failover timing on a postgres instance between aws AZ's.  To do this I need to be able to re-establish the connection on any failures. Anyway, when the db failover happens the connection will start but never allow progress past that point. How/what should I be doing differently for this connection to fail on any connection issues fast? 

On the failure loop it will never get to the "after connect" part of the code and will never fail. The only thing that is unique is this function is run in a routine, but i don't think that is related? 

pgx verison : "github.com/jackc/pgx/v4"
go version :  go1.13.8 linux/amd64

`
	dburi := fmt.Sprintf("postgres://%v:%v@%v/template1", params.dbuser, params.dbpass, params.dbhost)

	for {
		time.Sleep(2 * time.Second)
		fmt.Println("before connect")
		conn, err := pgx.Connect(context.Background(), dburi)
		fmt.Println("after connect")
		if err != nil {
			logger.Error("Unable to connect to database", err)
			continue
		}
		defer conn.Close(context.Background())

		var version string
		err = conn.QueryRow(context.Background(), "select version()").Scan(&version)
		if err != nil {
			logger.Error(err)
			continue
		}
		conn.Close(context.Background())

		logger.WithFields(logger.Fields{
			"type": "postgres",
		}).Info(version)

	} //end for
`

**Comment by donkeyx** [comment]
Not sure if this should still remain an issue, but i have resolved with a context for the moment : 
```
		ctx, cancel := context.WithTimeout(context.Background(), time.Duration(2)*time.Second)
		defer cancel()
		conn, err := pgx.Connect(ctx, dburi)

```

**Comment by jackc** [comment]
> How/what should I be doing differently for this connection to fail on any connection issues fast?

> Not sure if this should still remain an issue, but i have resolved with a context for the moment :

That is the correct way to try to connect but abort quickly rather than wait indefinitely.

**Comment by donkeyx** [comment]
so @jackc, are you suggesting I should just handle the connection timeouts etc with the context, and this is not something that the Connect method should handle by default? Happy to close/resolve if you think that is ok behaviour?

**Comment by jackc** [comment]
Yes, I think context is the correct place to handle timeouts and cancellations.

**Comment by donkeyx** [comment]
thanks for clearing up
