### ISSUE TITLE
Export the Scan per value on Rows?

### ISSUE THREAD

**Issue by kataras** [jackc/pgx#937]
Hello @jackc ,

Is there a better way to scan a specific value to a destination? So far I use the ConnInfo but I need to acquire and release a connection to get that info, the `connRows` contains a `connInfo` which contains the scan plan and scan but it's not exported, can you provide an API for that or just export that connRows.connInfo.Scan to a single method of ScanValue or something?

Here is my current solution:
```go
// SelectSingleQuery returns a database record of the specific dest's entity table
// based on a custom query (if it's empty then it selects all fields).
// Note that it will panic if the field cannot be set to a result.
// Use the `Select` method instead if the query returns values from more than one table.
func (db *DB) SelectSingleQuery(ctx context.Context, destPtr interface{}, query string, args ...interface{}) error {
	queryCtx, cancel := db.Options.Context(ctx)
	defer cancel()

	ptrVal := reflect.ValueOf(destPtr) // ptr val.
	val := indirectValue(ptrVal)
	typ := val.Type()

	td, err := db.schema.extract(typ)
	if err != nil {
		return err
	}

	if query == "" || query == "*" {
		query = fmt.Sprintf(`SELECT * FROM "%s"."%s" LIMIT 1;`, db.Options.Schema, td.Name)
		args = nil
	}

	// We need a special API for scanning per value
	// which is not exported by Pool, neither by rows,
	// this information is in the conn info which is only available if we acquire and release
	// the connection manually; see /rows.go#L194 of the underline postgres driver.
	c, err := db.Pool.Acquire(queryCtx)
	if err != nil {
		return fmt.Errorf("select single: %w", err)
	}
	connInfo := c.Conn().ConnInfo()
	c.Release()

	scanner := func(rows Rows) error {
		for rows.Next() { // bind only fields that exist in the entity's schema.
			values := rows.RawValues()

			for _, c := range td.Definition {
				for i, f := range rows.FieldDescriptions() { // values and field descs are in the same indexes.
					if c.Name == string(f.Name) {
						valField := val.FieldByIndex(c.fieldIndex)
						// This is not possible:
						// valField.Set(reflect.ValueOf(values[i]))
						// We need to scan per value and bind it to the field's ptr:
						valFieldPtr := valField.Addr().Interface()
						err = connInfo.Scan(f.DataTypeOID, f.Format, values[i], valFieldPtr)
						if err != nil {
							return fmt.Errorf("select single: %w", err)
						}
					}
				}
			}
		}

		return rows.Err()
	}

	rows, err := db.Query(queryCtx, query, args...)
	if err != nil {
		return err
	}
	defer rows.Close()

	return scanner(rows)
}
```

EDIT: I know I can use the same connection to do the `.Query` too, but this is an example code, the original contains custom logic on `.Query` based on the database instance, so we must keep in mind that it always acquires a new connection.

Thanks,
Gerasimos Maropoulos. Author of [Iris](https://github.com/kataras/iris)

**Comment by jackc** [comment]
I'm not sure I understand exactly what you are trying to do, but I think you could use `rows.Scan` directly. Right now your example loops through the result columns and scans each value individually. Instead, I would suggest looping through once to build a slice of the values to scan and then call `rows.Scan`. It should be a bit simpler and maybe a bit faster.

**Comment by kataras** [comment]
@jackc it can't be done directly with `rows.Scan` otherwise I wouldn't ask for this :) 

>  I would suggest looping through once to build a slice of the values to scan and then call rows.Scan.

This is not always the same slice, it depends on the returning values from the custom query (!) and the struct field tags. How can I pre-calculate what values I need from the query without looping each returning value from the query itself?

**Comment by jackc** [comment]
> @jackc it can't be done directly with rows.Scan otherwise I wouldn't ask for this :)

Then I guess I don't quite understand what you are trying to do because I think it _should_ be possible to do everything `ConnInfo.Scan` does through `Rows.Scan`.

I would see your innermost loop that is doing the `connInfo.Scan` instead accumulating a slice of values to pass to `rows.Scan`.
