### ISSUE TITLE
Query parameter not recognized when inside single quotes

### ISSUE THREAD

**Issue by peter9207** [jackc/pgx#939]
i have a pretty simple query that looks like this where i want to do a partial search on the name
```
SELECT
	id,
	first_name,
	last_name,
	birthdate,
	email,
	account_id
FROM
	users
WHERE last_name like '$1%'
```

but it seems that the $ parameter is not being parsed while inside single quotes, when i run it it gives the error ` "message": "expected 0 arguments, got 1",`

if i change the query to `where last_name = $1` the query works fine.
do i need to escape the string somehow?

**Comment by jackc** [comment]
Bind variables cannot be used within literal values. Change `'$1%'` to `$1 || '%'`.
