### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by NadeemAlam1** [jackc/pgx#941]
HI all running into the following error when running the hello.go example

go: finding module for package github.com/jackc/pgx/v4/pgxpool
go: found github.com/jackc/pgx/v4/pgxpool in github.com/jackc/pgx/v4 v4.10.1
go: github.com/jackc/pgx/v4@v4.10.1 requires
github.com/jackc/pgtype@v1.6.2 requires
github.com/jackc/pgx/v4@v4.6.1-0.20200606145419-4e5062306904 requires
github.com/jackc/pgtype@v1.3.1-0.20200606141011-f6355165a91c requires
github.com/jackc/pgx/v4@v4.6.1-0.20200510190926-94ba730bb1e9 requires
github.com/jackc/pgtype@v1.3.1-0.20200510190516-8cd94a14c75a requires
github.com/jackc/pgx/v4@v4.5.0 requires
github.com/jackc/pgtype@v1.2.0/go.mod: verifying module: github.com/jackc/pgtype@v1.2.0/go.mod: malformed record data

My go version is  1.15.7

**Comment by omikronsc** [comment]
Hi!  I'm getting similar:

```
$> go get github.com/jackc/pgx/v4
go: github.com/jackc/pgx/v4 upgrade => v4.10.1
go get: github.com/jackc/pgx/v4@v4.10.1 requires
	github.com/jackc/pgconn@v1.8.0 requires
	github.com/jackc/pgmock@v0.0.0-20190831213851-13a1b77aafa2 requires
	github.com/jackc/pgtype@v0.0.0-20190828014616-a8802b16cc59 requires
	github.com/jackc/pgx/v4@v4.0.0-pre1.0.20190824185557-6972a5742186 requires
	github.com/kr/pty@v1.1.8/go.mod: verifying module: github.com/kr/pty@v1.1.8/go.mod: malformed record data

```

**Comment by NadeemAlam1** [comment]
@omikronsc  that worked for me too! Thank you
