### ISSUE TITLE
Cannot convert <nil> to Time

### ISSUE THREAD

**Issue by sklyar** [jackc/pgx#942]
Hey! I found strange behavior in the Set method for the Time type.
The problem is the nil value of the time.Time.

The switch statement does not handle the *time.Time type, as it does for other types.

How to reproduce:

```go
var t pgtype.Time
err := t.Set((*time.Time)(nil))
```

**Comment by jackc** [comment]
Fixed in https://github.com/jackc/pgtype/commit/abeb337246854b40048ee995343b94dad92867d8.
