### ISSUE TITLE
Pool Query not returning error when user has no grant on table

### ISSUE THREAD

**Issue by poltro90** [jackc/pgx#943]
I have my pool defined as:

```go
pool := pgxpool.ConnectConfig(ctx, config)
```

I perform a query as follows:

```go
query := "SELECT * from table_name WHERE ..."
rows, err := pool.Query(ctx, query, args)
if err != nil {
  // Handle error
}
```

When the database connection is using a database user with no `SELECT` permissions on `table_name`, the query is not returning any error.

The error is instead correctly returned when using `QueryRow`.

**Comment by jackc** [comment]
You need to check `rows.Err()`.

**Comment by poltro90** [comment]
Thanks @jackc for the hint. What would be the use of that `err` then?

**Comment by jackc** [comment]
Query could return an error if the command failed to send. You might want to consider using `QueryFunc` instead. That simplifies the interface a bit. It's only on `master` at the moment, but it should be in the next minor release.

**Comment by Alexfilus** [comment]
> You need to check `rows.Err()`.

I tried, it's now not working. 
I made simple test for v4 and v5 https://github.com/Alexfilus/pgx-test
Table data is not empty, but if user pgx_test has permissions to schema and no permissions to read the table I don't see any error. Even pgx.ErrNoRows

**Comment by Alexfilus** [comment]
Update: `config.ConnConfig.PreferSimpleProtocol = true`
For v4 can solve problem. "ERROR: permission denied for table data" is returning in err. 
How I can enable it for v5?

**Comment by jackc** [comment]
@Alexfilus Are you closing the `rows` before you check `rows.Err()`?

**Comment by G2G2G2G** [comment]
> v5 config.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol

Thanks for this, I see no mention of the new simple protocol and we require it so we don't have to convert 10000 ids to strings every query lol

**Comment by Alexfilus** [comment]
@jackc No https://github.com/Alexfilus/pgx-test/blob/main/main.go#L48

**Comment by jackc** [comment]
@Alexfilus That's a problem. You need to close the rows before it is guaranteed that `rows.Err()` is present. You can do that by calling `rows.Next()` until it returns false or directly calling `rows.Close()`.

From the [docs](https://pkg.go.dev/github.com/jackc/pgx/v5#Conn.Query):

> Err() on the returned Rows must be checked after the Rows is closed to determine if the query executed successfully.

**Comment by Alexfilus** [comment]
rows.Close() is often using with defer what makes calling rows.Err() inconvenient. But checking after rows.Next() loop is working fine. Thank you!
