### ISSUE TITLE
 ERROR: could not determine data type of placeholder $2 (SQLSTATE 22023)

### ISSUE THREAD

**Issue by onthegit** [jackc/pgx#944]
Hello,  thanks for the effort you are putting into the project. I am experiencing the following error when I am trying to run this query:
units Table:
ID BYTES
Quantity DECIMAL (10,4)
tstamp int64
```sql
UPDATE units SET quantity=cn.pqd,tstamp=cn.ptn FROM (values($1,$2,$3)) AS cn(pqid,pqd,ptn) WHERE cn.pqid=ID
```
The database server is CockroachDB  v20.1.3

 ERROR: could not determine data type of placeholder $2 (SQLSTATE 22023)

**Comment by onthegit** [comment]
I tried also the following query :
```sql
UPDATE units SET quantity=cn.pqd,tstamp=cn.ptn FROM (values($1::BYTES,$2::DECIMAL(14,4),$3::INT64)) AS cn(pqid,pqd,ptn) WHERE cn.pqid=ID
```

**Comment by jackc** [comment]
I think you are running into this issue: https://github.com/cockroachdb/cockroach/issues/60907
