### ISSUE TITLE
unexpected EOF during insert with JSONB casue empty collumn

### ISSUE THREAD

**Issue by TomasVojacek** [jackc/pgx#946]
I have poor connection to server.
pgx and psql return  "unexpected EOF"
If call:
```
for i:=0;i<2;i+{
 _,err:= pool.Exec(ctx, `INSERT INTO mytable
		  (utc_time,mqtt_topic,payload,myerror) VALUES('2021-02-25 19:13:01.433004','topic','{"payload": "test payload"}','{
      "error": "invalid character 'e' in literal null (expecting 'u')",
      "Details": {
          "Offset": 2
      },
      "error_type": "*json.SyntaxError"
  }') ;
if err!=nil{
   fmt.Print(err)
}
time.Sleep(time.Second)
}
```
in console i can see "unexpected EOF" 
and database two new rows are inserted
first row has myerror null, rest is as expected.
second row contain all fields as expected (unexpected EOF does not occur this time)
Program has retry loop calling same statement one again. In example replaced by simple for.

I have added null constrain to column error.
pgx output is the same.
But on database i have got error:
```
ERROR:  null value in column "myerror" violates not-null constraint
timescaledb_1  | 2021-02-25 19:22:06.810 GMT [163971] DETAIL:  Failing row contains (utc_time, mqtt_topic, payload) = (2021-02-25 19:21:56.97828, ble/pm8243, {"payload": "test payload"}).
timescaledb_1  | 2021-02-25 19:22:06.810 GMT [163971] STATEMENT:  INSERT INTO unknown_messages
timescaledb_1  | 			(utc_time,mqtt_topic,payload) VALUES($1,$2,$3);
```

My table is:
```
CREATE TABLE public.unknown_messages
(
    id integer NOT NULL DEFAULT nextval('unknown_messages_id_seq'::regclass),
    utc_time timestamp without time zone NOT NULL,
    mqtt_topic text COLLATE pg_catalog."default" NOT NULL,
    payload jsonb NOT NULL,
    myerror jsonb NOT NULL,
    CONSTRAINT unknown_messages_pkey PRIMARY KEY (id, utc_time, mqtt_topic)
)

```

---- after modification of table ----
```
CREATE TABLE public.unknown_messages
(
    id integer NOT NULL DEFAULT nextval('unknown_messages_id_seq'::regclass),
    utc_time timestamp without time zone NOT NULL,
    mqtt_topic text COLLATE pg_catalog."default" NOT NULL,
    payload jsonb NOT NULL,
    jsonb_error jsonb,
    error text COLLATE pg_catalog."default",
    CONSTRAINT unknown_messages_pkey PRIMARY KEY (id, utc_time, mqtt_topic)
)
```
```
for i:=0;i<2;i++{
_, err := app.database.Exec(ctx, `INSERT INTO unknown_messages
(utc_time,mqtt_topic,payload,jsonb_error) VALUES($1,$2,$3,$4) ;`,
	&utcTime,msg.Topic(), jsonError,jsonPayload)
fmt.Print(err)
}
```
in database I can see:	
45489	"2021-02-25 19:51:42.122503"	"ble/pm8243"	"{""payload"": ""test jsonb5""}"		
45488	"2021-02-25 19:51:42.122433"	"ble/pm8243"	"{""error"": ""invalid character 'e' in literal true (expecting 'r')"", ""Details"": {""Offset"": 2}, ""error_type"": ""*json.SyntaxError""}"		"{""payload"": ""test jsonb5""}"

go.mod
```
	github.com/jackc/pgconn v1.8.0
	github.com/jackc/pgerrcode v0.0.0-20190803225404-afa3381909a6
	github.com/jackc/pgproto3/v2 v2.0.7 // indirect
	github.com/jackc/pgx/v4 v4.10.1
```

**Comment by TomasVojacek** [comment]
changing  
column    payload type from jsonb to text
resolved the problem.

**Comment by califlower** [comment]
I had the same problem. The general recommendation is not to use the JSONB type directly. See below

https://github.com/jackc/pgx/issues/952#issuecomment-803725093

Depending on your use case, the string type or directly unmarshaling into a struct is a better idea
