### ISSUE TITLE
RegisterConnConfig reuses data source names for different connection options

### ISSUE THREAD

**Issue by andy-kimball** [jackc/pgx#947]
Repro:
1. Call `RegisterConnConfig`.
2. Call `UnregisterConnConfig` on the result of #1.
3. Call `RegisterConnConfig` again, but with different connection options.

EXPECTED: The connection string returned by #3 should be different than #1.
ACTUAL: #3 reuses the same connection string used by #1.

This would be easy to fix, by using a separately incrementing counter rather than `len(d.configs)` in `Driver.registerConnConfig`. It would then make building tooling easier. In my particular case, I'm doing some pooling of connections in [https://github.com/cockroachdb/copyist](https://github.com/cockroachdb/copyist). That pooling relies on the reasonable assumption that two connections with the same data source name are connecting to the same backend database. This works great with every other driver I've tried, and even works well with `pgx`, unless `RegisterConnConfig` is used.

I'd be happy to create a PR to fix this, if it's something you're open to merging.

**Comment by jackc** [comment]
> I'd be happy to create a PR to fix this, if it's something you're open to merging.

Sure.
