### ISSUE TITLE
Logging question

### ISSUE THREAD

**Issue by SkipUFO** [jackc/pgx#949]
I have a backend application that implements web server with Postgres RDBMS. I use zap logger and push logs through fluentd to elastic both on frontend and backend. 
When I initialize pgxpool I set ConnConfigLogger = zapadapter.NewLogger(). 
When I Query, QueryRow, etc with level debug - I have logs from pgxpool. I would like to mark logs with request-id (trace-id) to have transparent logs through user requests. Is there some simple way to do this?

**Comment by SkipUFO** [comment]
One way is write logadapter with store: 
1. when Acquire connection from pool set trace-id to this conn
2. when log get trace-id from logadapter by conn
3. when release conn to pool free object in store that connects trace-id and conn

Is it interesting to get into pgx repo?

**Comment by jackc** [comment]
Probably better pass request id through the context.

**Comment by SkipUFO** [comment]
Thanks! It's the best way.
