### ISSUE TITLE
Using RegisterDefaultPgType on custom type based on int2

### ISSUE THREAD

**Issue by jschaf** [jackc/pgx#953]
I'm having trouble registering a decoder for custom number type based on int2:

```go
package custom_types

import (
	"context"
	"github.com/jschaf/pggen/internal/pgtest"
	"testing"
)

const schema = `
-- New base type my_int.
-- https://stackoverflow.com/a/45190420/30900
CREATE TYPE my_int;

CREATE FUNCTION my_int_in(cstring) RETURNS my_int
  LANGUAGE internal
  IMMUTABLE STRICT PARALLEL SAFE AS
'int2in';

CREATE FUNCTION my_int_out(my_int) RETURNS cstring
  LANGUAGE internal
  IMMUTABLE STRICT PARALLEL SAFE AS
'int2out';

CREATE FUNCTION my_int_recv(internal) RETURNS my_int
  LANGUAGE internal
  IMMUTABLE STRICT PARALLEL SAFE AS
'int2recv';

CREATE FUNCTION my_int_send(my_int) RETURNS bytea
  LANGUAGE internal
  IMMUTABLE STRICT PARALLEL SAFE AS
'int2send';

CREATE TYPE my_int (
  INPUT = my_int_in,
  OUTPUT = my_int_out,
  RECEIVE = my_int_recv,
  SEND = my_int_send,
  LIKE = smallint,
  CATEGORY = 'N',
  PREFERRED = FALSE,
  DELIMITER = ',',
  COLLATABLE = FALSE
);`

func TestCustomType(t *testing.T) {
	conn, cleanup := pgtest.NewPostgresSchemaString(t, schema)
	defer cleanup()
	conn.ConnInfo().RegisterDefaultPgType(int16(0), "my_int")
	conn.ConnInfo().RegisterDefaultPgType(int64(0), "my_int")
	conn.ConnInfo().RegisterDefaultPgType((*int16)(nil), "my_int")
	conn.ConnInfo().RegisterDefaultPgType((*int64)(nil), "my_int")

	t.Run("scan *int", func(t *testing.T) {
		row := conn.QueryRow(context.Background(), `SELECT '5'::my_int as int5`)
		val := int(0)
		err := row.Scan(&val)
		if err != nil {
			t.Error(err)
		}
	})

	t.Run("scan *int64", func(t *testing.T) {
		row := conn.QueryRow(context.Background(), `SELECT '5'::my_int as int5`)
		val := int64(0)
		err := row.Scan(&val)
		if err != nil {
			t.Error(err)
		}
	})

	t.Run("scan *int16", func(t *testing.T) {
		row := conn.QueryRow(context.Background(), `SELECT '5'::my_int as int5`)
		val := int16(0)
		err := row.Scan(&val)
		if err != nil {
			t.Error(err)
		}
	})
}

```

This test errors with:

```
=== RUN   TestCustomType
    custom_test.go:47: created schema: pggen_test_888516172
--- FAIL: TestCustomType (0.02s)
=== RUN   TestCustomType/scan_*int
    custom_test.go:59: can't scan into dest[0]: unknown oid 16581 cannot be scanned into *int
    --- FAIL: TestCustomType/scan_*int (0.00s)
=== RUN   TestCustomType/scan_*int64
    custom_test.go:68: can't scan into dest[0]: unknown oid 16581 cannot be scanned into *int64
    --- FAIL: TestCustomType/scan_*int64 (0.00s)
=== RUN   TestCustomType/scan_*int16
    custom_test.go:77: can't scan into dest[0]: unknown oid 16581 cannot be scanned into *int16
    --- FAIL: TestCustomType/scan_*int16 (0.00s)
FAIL
```

**Comment by jackc** [comment]
You need to call `RegisterDataType`. You probably won't need `RegisterDefaultPgType`.

`RegisterDefaultPgType` maps Go types that do not implement `(Encode|Decode)(Text|Binary)` to a PostgreSQL type name, but it doesn't implement the encoding and decoding itself.

**Comment by jschaf** [comment]
> You need to call RegisterDataType. You probably won't need RegisterDefaultPgType.

Ah, thank you. I have it working with this addition:

```go
	row := conn.QueryRow(context.Background(), texts.Dedent(`
		SELECT pt.oid
		FROM pg_type pt
			JOIN pg_namespace pn ON pt.typnamespace = pn.oid
		WHERE typname = 'my_int'
			AND pn.nspname = current_schema()
		LIMIT 1;
	`))
	oidVal := pgtype.OIDValue{}
	err := row.Scan(&oidVal)
	require.NoError(t, err)

	conn.ConnInfo().RegisterDataType(pgtype.DataType{
		Value: &pgtype.Int2{},
		Name:  "my_int",
		OID:   oidVal.Uint,
	})
```


---

One wrinkle is that I have to fetch the OID first for `my_int`. For the decode path, it seems like having the type name alone should be sufficient to get the appropriate `Value` and decode the Postgres wire format.

**Feature request**: would be okay to modify [PlanScan](https://github.com/jackc/pgtype/blob/master/pgtype.go#L808) from the following. I couldn't figure out what the `oid == 0` guards against. The benefit is you can register a `Value` by type name without the OID.

```go
	if oid == 0 {
		if dataType, ok := ci.DataTypeForValue(dst); ok {
			dt = dataType
		}
	} else {
		if dataType, ok := ci.DataTypeForOID(oid); ok {
			dt = dataType
		}
	}
```
 
to the following which first checks by the OID and then by the dest value.

```go
	if dataType, ok := ci.DataTypeForOID(oid); ok {
		dt = dataType
	} else if dataType, ok := ci.DataTypeForValue(dst); ok {
		dt = dataType
	}
```

**Comment by jackc** [comment]
> One wrinkle is that I have to fetch the OID first for my_int. For the decode path, it seems like having the type name alone should be sufficient to get the appropriate Value and decode the Postgres wire format.

Results over the wire do not include the type name. Only the type OID.

**Comment by jschaf** [comment]
> Results over the wire do not include the type name. Only the type OID.

Yes, I bungled that explanation. Really the situation is I know how to decode the type and I don't need the OID or type name. The problem I've run into is that pgx requires the OID to pick a `Value` to decode the wire type.

What'd I like is to pick the `Value` based on the destination type using `ci.DataTypeForValue(dst)`. But that code path is only hit when `oid == 0` (is that only anonymous types?)

```go
	if oid == 0 {
		if dataType, ok := ci.DataTypeForValue(dst); ok {
			dt = dataType
		}
	} else {
		if dataType, ok := ci.DataTypeForOID(oid); ok {
			dt = dataType
		}
	}
```

The proposed patch allows "blind" decoding without knowing the OID in advance.

```go
	if dataType, ok := ci.DataTypeForOID(oid); ok {
		dt = dataType
	} else if dataType, ok := ci.DataTypeForValue(dst); ok {
		dt = dataType
	}
```

**Comment by jackc** [comment]
To be honest my recollection is a little fuzzy on the oid == 0 path but I believe it is only for composite fields in the text format. In that case we know what the type is on the client side but do not have OIDs.

The change you are suggesting seems to be safe. But I'm not sure that encouraging a code path that uses DataTypeForValue is a good idea for performance. It's a reflection heavy method. So for best performance it should be registered by OID.

But on another note... I actually would have expected to be able to scan unknown PostgreSQL number types into a Go number without registering it at all. It's an unknown type which meant it would use the text format. It would seem logical for scanning into a number to try to parse the text. If that were working you wouldn't need to register anything at all.
