### ISSUE TITLE
insert inside a with statement that fails, does not return an error, returns an empty result set

### ISSUE THREAD

**Issue by kfirufk** [jackc/pgx#957]
Hi

I use Go 1.16 with pgx v4.10.1 on MacOS Big Sur 11.2.2 on Mac Pro Late 2013.

I noticed that if i insert a row and returning a value inside `with` statements, and the insert fails because of unique index, i don't get an error, instead i get am empty result set.

this is the query that I tested:

```
with res as (
select $1::int as added_by, c.id as cocktail_id,$2 as comment,
$3::int as parent_comment_id from mycocktailworld.cocktails c
                            join mycocktailworld.users u on u.id= c.added_by
where u.profile_dir=$4 and c.name=$5 and c.is_publish
  and u.id != $6::int),
     ins as (
         insert into mycocktailworld.cocktail_comments(added_by, cocktail_id, comment, parent_comment_id)
             select added_by, cocktail_id, comment, parent_comment_id from res returning id is not null as is_valid)
select coalesce((select is_valid from ins),false);
```

I use `*pgxpool.Pool` `Query()` to execute the query.

**Comment by jackc** [comment]
Are you checking `rows.Err` after reading the results?

**Comment by kfirufk** [comment]
actually.. i never check rows.Err, i just check the error from the query itself. thank you so much! it seems i was missing some basic checks in go! thank you so much. this issue is resolved.
