### ISSUE TITLE
"Received unknown message type: C" when executing a SELECT FOR UPDATE

### ISSUE THREAD

**Issue by uberbrodt** [jackc/pgx#96]
The above error doesn't seem to happen all the time; only after a process has been running under load for awhile. I'm using a pgx ConnPool for the query.

**Comment by jackc** [comment]
What branch/commit are you running on? I added some additional code in the last week to detect and prevent a single connection from being used concurrently. If you're running an older version please try master and let me know if there is any change.

Are we talking about failing after a few minutes, hours, or days? Is there a reproducible case I can look it?

One other idea, could you try running your failing case with the race detector enabled?

**Comment by uberbrodt** [comment]
This it the version I'm running: 			
                         "ImportPath": "github.com/jackc/pgx",
			"Comment": "v2.5.0-1-g784d12c",
			"Rev": "784d12cbbcfc11c637d8f7931dd87a3f236e5c4d"

I'm upgrading to latest and I'll do some more testing with it and the race detector enabled. It seems to fail after running for hours/days. I'll see if I can't create an isolated test case you can look at (I'm getting it when doing a fully integrated load test of the application) It almost seems like the pool gets exhausted and doesn't replace "bad" connections, since the program still continues to run and make some successful queries.

**Comment by uberbrodt** [comment]
Upgrading seemed to have made the issue go away. Closing
