### ISSUE TITLE
Example and/or documentation about how to handle Large Object

### ISSUE THREAD

**Issue by kahlys** [jackc/pgx#963]
I may miss something, but I have no idea how to use this lib to import à file.

For the record I am trying to write in Golang a similar function of [PHP `pg_lo_import`](https://www.php.net/manual/fr/function.pg-lo-import.php)

**Comment by mitar** [comment]
@kahlys Any success? Could you share your code?

**Comment by jackc** [comment]
@mitar The tests might be useful as examples: https://github.com/jackc/pgx/blob/master/large_objects_test.go

**Comment by mitar** [comment]
@jackc Yes, I used that at the end, but documentation would still be useful. :-)
