### ISSUE TITLE
No Listen/Notify for pgxpool.Pool ?

### ISSUE THREAD

**Issue by supermuesli** [jackc/pgx#968]
The code snippet below was taken from the docs [here](https://pkg.go.dev/github.com/jackc/pgx/v4#hdr-Listen_and_Notify)
```
_, err := conn.Exec(context.Background(), "listen channelname")
if err != nil {
    return nil
}

if notification, err := conn.WaitForNotification(context.Background()); err != nil {
    // do something with notification
}
```
My backend is connected to Postgres via **pgxpool.Pool** for concurrency reasons. Am I supposed open another connection to Postgres via **pgx.Connect** and call **WaitForNotification** from there or can this be done with **pgxpool.Pool** as well?

**Comment by jackc** [comment]
I would `Acquire` the connection for listen/notify from `pgxpool.Pool` and never return it.

**Comment by supermuesli** [comment]
But [pgxpool.Pool.Acquire](https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool#Pool.Acquire) returns a [pgxpool.Conn](https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool#Conn). which does not implement **WaitForNotification**. Only **pgx.Conn** [does](https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.WaitForNotification).
Am I missing something?

**Comment by jackc** [comment]
You can call `Conn()` on the `pgxpool.Conn` to get the underlying connection.

**Comment by supermuesli** [comment]
You are right.  So why not implement a func ```pgxpool.Conn.WaitForNotification``` that does exactly that? Something like:
``` 
func (p *Pool) WaitForNotification(ctx context.Context) (*pgconn.Notification, error) {
	// Get an unused connection from the pool
	c := p.Acquire().Conn()
	
	var n *pgconn.Notification

	// Return already received notification immediately
	if len(c.notifications) > 0 {
		n = c.notifications[0]
		c.notifications = c.notifications[1:]
		return n, nil
	}

	err := c.pgConn.WaitForNotification(ctx)
	if len(c.notifications) > 0 {
		n = c.notifications[0]
		c.notifications = c.notifications[1:]
	}
	return n, err
}
```

If you want I can fork the project and make a pull request.

**Comment by supermuesli** [comment]
You are right.  So why not implement a func ```pgxpool.Conn.WaitForNotification``` that does exactly that? Something like:
``` 
func (pc *Conn) WaitForNotification(ctx context.Context) (*pgconn.Notification, error) {
	// Get the underlying connection
	c := pc.Conn()
	
	var n *pgconn.Notification

	// Return already received notification immediately
	if len(c.notifications) > 0 {
		n = c.notifications[0]
		c.notifications = c.notifications[1:]
		return n, nil
	}

	err := c.pgConn.WaitForNotification(ctx)
	if len(c.notifications) > 0 {
		n = c.notifications[0]
		c.notifications = c.notifications[1:]
	}
	return n, err
}
```

If you want I can fork the project and make a pull request.

**Comment by jackc** [comment]
The reason the pool types don't have `WaitForNotification` is for there to be a notification, the connection first has to `listen`. That doesn't make sense at the pool level, only on a specific connection. And a listening connection should never be returned to the pool as it could keep listening and it would essentially leak memory by buffering all received notifications.

**Comment by supermuesli** [comment]
Yea, it seems you're right again. 
Learned a lot today, 
love connection pools, 
love your project.
