### ISSUE TITLE
oid type support

### ISSUE THREAD

**Issue by hellower** [jackc/pgx#97]
"select dataid from pg_stat_activity limit"  - dataid column => oid type
error occurred!

So, I modified source. (2 places)
Can you apply my patch?
sorry for my poor english!

---------- query.go ---
func (rows *Rows) Values() ([]interface{}, error) {
    if rows.closed {
        return nil, errors.New("rows is closed")
    }

    values := make([]interface{}, 0, len(rows.fields))

    for _, _ = range rows.fields {
        vr, _ := rows.nextColumn()

        fmt.Printf("\n>><[%d](%s)-%d>", rows.columnIdx, vr.Type().Name,vr.Type().FormatCode)
        if vr.Len() == -1 {
            values = append(values, nil)
            continue
        }

        switch vr.Type().FormatCode {
        // All intrinsic types (except string) are encoded with binary
        // encoding so anything else should be treated as a string
        case TextFormatCode:
            values = append(values, vr.ReadString(vr.Len()))
        case BinaryFormatCode:
            switch vr.Type().DataType {
            case BoolOid:
                values = append(values, decodeBool(vr))
            case ByteaOid:
                values = append(values, decodeBytea(vr))
            case Int8Oid:
                values = append(values, decodeInt8(vr))
            case Int2Oid:
                values = append(values, decodeInt2(vr))
            case OidOid:                         <---------------------------------- !!!!!!!!!!!!!!!!!!!!!
                values = append(values, decodeInt4(vr))                <--  !!!!!!!!!!!!!!!!!!!!!!!
            case Int4Oid:
                values = append(values, decodeInt4(vr))
            case Float4Oid:
                values = append(values, decodeFloat4(vr))

---------- values.go  ---
func decodeInt4(vr *ValueReader) int32 {
    if vr.Len() == -1 {
        vr.Fatal(ProtocolError("Cannot decode null into int32"))
        return 0
    }

 //   if vr.Type().DataType != Int4Oid {     <------------- remove this line !!!!!!!!
    if (vr.Type().DataType != Int4Oid)&&(vr.Type().DataType != OidOid) {  <--------- !!!!!!!!!!!!!!!!!!!!!!
        vr.Fatal(ProtocolError(fmt.Sprintf("Cannot decode oid %v into int32", vr.Type().DataType)))
        return 0
    }

    if vr.Type().FormatCode != BinaryFormatCode {
        vr.Fatal(ProtocolError(fmt.Sprintf("Unknown field description format code: %v", vr.Type().FormatCode)))
        return 0
    }

**Comment by jackc** [comment]
It looks like you were specifically interested in the Values() method supporting Oid types. I added this support in 7dfdc9285588607e8b2de8d89450f63bc31b187a. If this isn't what you need then you can reopen this issue.

**Comment by hellower** [comment]
thank you!
