### ISSUE TITLE
PgBouncer and pgxpool

### ISSUE THREAD

**Issue by pmorelli92** [jackc/pgx#970]
Hello! I want to start saying that this is not an issue, but more of a seeking for guidance. 

Let's say I am running PgBouncer with `pool_mode = transaction` as I don't have any prepared statements but I want to have transactions in certain parts of the code and I set `statement_cache_mode=describe` on the connection string.

My gut feeling tells me that I should stick with `pgx` and not use `pgx.pool` as having a doble pooling does not seem like it is going to work, or at least when I am trying to use `transaction` on pgbouncer.

Am I right?

**Comment by jackc** [comment]
If your application is going to use more than one connection at a time you would want to use `*pgxpool.Pool`.

**Comment by pmorelli92** [comment]
Hi @jackc, thanks for your answer! Do you mind elaborating your argument? 

In my head I imagine that if pgbouncer is doing the pooling, then I should not have a pooling on top that may possible mess up with the lifecycle of a connection that pgbouncer intended to manage. But maybe I am just overthinking and this does not happen.

I have an idea of doing a load testing on an API that exposes a POST endpoint for inserting some data using transactions. Then measure this using `pgx -> pgbouncer -> postgres` and `pgx.pool -> pgbouncer -> postgres`.

I can share my results here but I will probably do that next week :)

**Comment by jackc** [comment]
A `pgx.Conn` is not concurrency safe. If you plan on handling more than one request at a time you should use a pool in the application layer.

**Comment by torkelrogstad** [comment]
@pmorelli92 would you be able to expand on your findings?

I'm trying out PgBouncer on my server to solve some connection slot limit issues. Am I doing something strange if I'm using `pgxpool` AND PgBouncer? And if I want to use both, how would I go about that?

**Comment by pmorelli92** [comment]
Hi @torkelrogstad, at the end we ended up using `pgbouncer` and `pgxpool` and evverything worked fine. I tried with `pool_mode = session` however and not with `transaction` as there were some services that I could not get rid of prepared statements (as I did not have ownership to do so).

**Comment by bfontaine** [comment]
I believe this question got a response. Feel free to reopen if that’s not the case.

**Comment by adityapatel-00** [comment]
I'm just trying to understand.
If I'm using pgBouncer as my pooler on the database side. If I use singleton design for establishing a connection using pgx.Conn, how it is going to handle the database operations?
Will it handle them concurrently?or will it put them in a queue?

**Comment by jackc** [comment]
@adityapatel-00 From your application's point of view, PgBouncer allows you to have more connections established at once and may be quicker at establishing connections. That's it. a pgx.Conn is still not concurrency safe. If you want multiple operations to be concurrent you need multiple connections at the application level. That is, you should use pgxpool.Pool.

**Comment by adityapatel-00** [comment]
@jackc Thanks a lot for the reply. But the reason behind using pgBouncer is..
I have multiple other clients(applications) accessing the database. In this case I either need to setup pgxpool.Pool in every application or pgBouncer at the database.

Or can I use both server and client side pooling?

The actual problem was.. if I put pgBouncer and pgx.Conn.. I had to establish connection for every request to the application and close it at end of request . This would be very costly right?.

What would you suggest in this case?

**Comment by jackc** [comment]
@adityapatel-00 

> Or can I use both server and client side pooling?

Yes.

> What would you suggest in this case?

You should use pgxpool.

**Comment by adityapatel-00** [comment]
Is there any concept of pipe which is established between application and database, through which we will perform all database operations. 
Technically we are looking to implement a design pattern where a single instance of connection manager is created and reused throughout the lifetime of the application. 
This pipe should only be closed when application is dead. Do you think we are attempting to create another pgxpool with this approach?

**Comment by jackc** [comment]
@adityapatel-00 

> Do you think we are attempting to create another pgxpool with this approach?

Yes. That is typically how pgxpool is used.

**Comment by adityapatel-00** [comment]
@jackc Understood. Thank you.
