### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by ronanbarrett** [jackc/pgx#972]
We are looking forward to using the new pool BeforeConnect hook in master https://github.com/jackc/pgx/blob/80147fd7cc44d4fe05f92554cc66ef225bb51a63/pgxpool/pool.go#L74 but there hasn't be a pgx release since December 2020. When is the next scheduled release?

**Comment by jackc** [comment]
Today 😄 

https://github.com/jackc/pgx/releases/tag/v4.11.0

**Comment by ronanbarrett** [comment]
Thanks for the excellent support!
