### ISSUE TITLE
insufficient permissions for table did not result in error being propagated in Query()

### ISSUE THREAD

**Issue by boindil** [jackc/pgx#973]
When selecting from a table on which the connected user has no permissions, no error is returned and all coding runs fine (except that there is neither data nor error returned).

```
var conn *pgx.Conn

# connect to db

rows, err := conn.Query(
	context.Background(),
	`SELECT ...
		FROM ...
		WHERE ...
		LIMIT ...`,
	...,
)
```

I would expect this to return an error in go as postgres does return one.

```
ERROR:  permission denied for table ...
SQL state: 42501
```

**Comment by jackc** [comment]
You must finish reading the rows and check `rows.Err()` at the end.

Or, as of `v4.11.0` you can use https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.QueryFunc for a simpler interface with only one place to check errors.

**Comment by boindil** [comment]
Well, thats kind of unexpected.

Still the problem is solvable this way. Thanks for your support. 

By the way: Great library! Thanks for all your hard work!
