### ISSUE TITLE
Question: Can the pgx interface be used when application is using other database/sql  drivers?

### ISSUE THREAD

**Issue by ddebrunner** [jackc/pgx#976]
The README.md has this:
```
It is recommended to use the pgx interface if:

The application only targets PostgreSQL.
No other libraries that require database/sql are in use.
```

I'm trying to understand what's behind 2. It is saying, for example, that if I'm also using the MySQL driver (`github.com/go-sql-driver/mysql`) then I should not use the `pgx` interface?

If what's the reasoning behind it, does `pgx` "modify" database/sql in some way?

I looked at the history of the term in the README, but it seems to be an early addition when the README.md was first written,  not tied to an issue specific to this.

**Comment by jackc** [comment]
Yes, you can use other `database/sql` drivers at the same time as the native pgx interface. The meaning of 2 is that if you are using some library that expects a `database/sql` interface (e.g. sqlx or gorm) it won't work with the native pgx interface.

**Comment by ddebrunner** [comment]
Thanks for the quick response!
