### ISSUE TITLE
oid type support - by row.Scan method()

### ISSUE THREAD

**Issue by hellower** [jackc/pgx#98]
/---------------  good -------------------------------------------------/
	l_sqltext = `select 100::oid`

	rows, err := conn.Query(l_sqltext)
	if err != nil {
		fmt.Println("conn.Query failed: ", err)
	}

	for rows.Next() {
		values, err := rows.Values()
		if err == nil {
			fmt.Println(values)
			fmt.Printf("%+v\n", values)
		} else {
			fmt.Println(err)
		}
	}

output => [100]  // correct

/-------------- bad ---------------------------------------------/
	for rows.Next() {
		var l_oid int32 // int32 !!!!!
		err = rows.Scan(&l_oid)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println("###", l_oid)
	}

output => Cannot decode oid 26 into int32 // error!!!!!
### 0
/--------------- bad --------------------------------------------/

	for rows.Next() {
		var l_oid string // string !!!!
		err = rows.Scan(&l_oid)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println("###", l_oid)
	}

output=> ### d  // not correct // not correct!!!!
/----------------------------------------------------------------/

sorry for poor english.

**Comment by jackc** [comment]
That's because oid actually is a separate type from int32. Use pgx.Oid as the type.

**Comment by hellower** [comment]
It works good. thanks!
