### ISSUE TITLE
cannot convert []int to Int4

### ISSUE THREAD

**Issue by enzofoucaud** [jackc/pgx#980]
Hello,

I do a program in Golang for an API and i had a problem ..

> SELECT * FROM a WHERE id = ANY ($1) AND time >= $2 AND time <= $3
> All good with this SQL select

Now I need to do a query with LEFT JOIN and I have this following query and i have an error .. 
> SELECT a.time FROM a LEFT JOIN b ON a.id = b.id WHERE a.id IN ($1) AND a.time >= $2 AND a.time <= $3;"
> err : cannot convert [21001 20004 20001 20005] to Int4

I noticed that the problem arose when joining between the two tables and when i changed the ANY to IN.
To skip this problem I do a func who take the query and transform it, however I would like to be able not to do this function to solve the problem.

main func :
```
query := `
	SELECT a.time 
	FROM a
	LEFT JOIN b ON a.id = b.id 
	WHERE a.id IN (🆔) AND a.time >= $2 AND a.time <= $3;`
sql, err := printIDs(query, location)
```
sub func :
```
func printIDs(sql string, locations []int) (string, error) {
	if l := convertIDs(locations); len(l) > 0 {
		return strings.Replace(strings.Replace(sql, "\n\t", "", -1), "🆔", l, -1), nil
	}
	return "", errors.New("no ID")
}
func convertIDs(location []int) string {
	placeholders := make([]string, len(location))
	for i := range location {
		placeholders[i] = strconv.Itoa(location[i])
	}
	return strings.Join(placeholders, ",")
}
```

**Comment by jackc** [comment]
Try it directly in psql with prepared statements and you will get the same result. `IN` takes a comma separated list of `T`. `ANY` takes a `T[]`. That's just how SQL works.
