### ISSUE TITLE
suggestion: application_name feature

### ISSUE THREAD

**Issue by hellower** [jackc/pgx#99]
---------------------------------------------------------------------------------------
use application name - use SQL configuration statement or variable in connection string or environment variable

SET application_name = 'myapp';
or
postgresql://other@localhost/otherdb?connect_timeout=10&application_name=myapp

--->  
type ConnConfig struct {
	Host              string // host (e.g. localhost) or path to unix domain socket directory (e.g. /private/tmp)
	Port              uint16 // default: 5432
	Database          string
	User              string // default: OS user name
	Password          string
	TLSConfig         *tls.Config // config for TLS connection -- nil disables TLS
	UseFallbackTLS    bool        // Try FallbackTLSConfig if connecting with TLSConfig fails. Used for preferring TLS, but allowing unencrypted, or vice-versa
	FallbackTLSConfig *tls.Config // config for fallback TLS connection (only used if UseFallBackTLS is true)-- nil disables TLS
	Logger            Logger
	LogLevel          int
	Dial              DialFunc
    Application_name string   // !!!!!!!!!!!!!!!!!
} 

sorry for poor english!

**Comment by jackc** [comment]
I added generalized run-time parameter setting (including application_name) in 5b0550c.

See https://github.com/jackc/pgx/blob/master/conn_test.go#L393 for an example.

**Comment by hellower** [comment]
Great!
