### ISSUE TITLE
use case issue

### ISSUE THREAD

**Issue by mokvetch** [jackc/pgx#991]
если вы публикуете библиотеку, поцчему не предоставляете качественную документацию и примеры использования?

**Comment by segfault88** [comment]
There is pretty extensive documentation here: https://pkg.go.dev/github.com/jackc/pgx/v4 as well as examples here: https://github.com/jackc/pgx/tree/master/examples - if you have a problem with the documentation, why don't you contribute some improvements where you think they are lacking?

Also, using English will probably get a better response.
