### ISSUE TITLE
[QUESTION] Handling duplicate records using the COPY protocol

### ISSUE THREAD

**Issue by dhh93** [jackc/pgx#992]
Hello,

Was wondering if there was way to ignore unique constraint violations when using the `CopyFrom` method similar to the `ON CONFLICT DO NOTHING` clause when using traditional `INSERT` statements?

**Comment by jackc** [comment]
Not as far as I know.

**Comment by pashagolub** [comment]
No, there is no such opportunity. Details: https://www.postgresql.org/docs/current/sql-copy.html

**Comment by pashagolub** [comment]
Good choice. It's not hackey, it's how it's done in a real world :-)

**Comment by segfault88** [comment]
Just to add on a bit to this, I do this.

Create a temporary table:
```sql
CREATE TEMPORARY TABLE _temp_upsert_members (LIKE members INCLUDING ALL) ON COMMIT DROP
```
Then run an upsert to the real table by doing `INSERT INTO ... SELECT <columns> FROM _temp_upsert_members` with `ON CONFLICT DO UPDATE ...`.

The `(LIKE <realtable>` is useful there.

**Comment by dhh93** [comment]
Elegant solution, appreciate you sharing it!

**Comment by adi-kmt** [comment]
@dhh93 @segfault88 Would you still do this for 4 tables? i.e. Have 4 staging tables and so on ...

**Comment by pashagolub** [comment]
@adi-kmt What is wrong with 4 temp tables?

**Comment by adi-kmt** [comment]
@pashagolub only want to know if it is worth the speed-up for about 8k rows bulk insert each?

**Comment by pashagolub** [comment]
Another solution would be to create `UNLOGGED` table(s) and use it every time you want to bulk insert and `TRUNCATE` at the end of operation. This was one don't need to CREATE/DELETE temp tables every time

**Comment by adi-kmt** [comment]
Fair enough, thanks for the reply. Will evaluate both the options and pick one!!
