### ISSUE TITLE
Send pg_dump to postgres using pgx (ERROR: syntax error at or near "\" (SQLSTATE 42601))

### ISSUE THREAD

**Issue by taosx** [jackc/pgx#993]
I've been working for the last couple of weeks with postgres and found this amazing library for which I thank you!

While writing my tests I've encountered a scenario where I would like to pass complete sql files generated by the pg_dump utility in postgres, unfortunately postgres is having trouble parsing the COPY FROM STDIN ./ command.

`ERROR: syntax error at or near "\" (SQLSTATE 42601)`
which relates to:
```
--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.schema_migrations (version, dirty) FROM stdin;
1	f
\.
```

I've tried using the SimpleProtocol with:
```
raw.Conn().Config().PreferSimpleProtocol = true
```
But I still get the above error.

Is this possible currently using pgx or underlying lower level libraries?

Note: I'm trying to extract the functionality from the psql utility, do you think it would be worth it to include it as a lower level command in pgx or in one of the lower level libraries, also could I get some direction?

**Comment by jackc** [comment]
I don't think that will be (easily) possible. I think psql is actually parsing the input file and sending each query separately. It's not sending the entire file as a single simple query. Copy commands actually have a different low level protocol from regular queries. So without a SQL parser client side I don't think it will be doable.

**Comment by taosx** [comment]
Yeah, realized that after the comment, it's pretty far from my initial goal but in the context of learning I started building a simple sql parser (more like pgdump parser) in order to afterward execute the requests using pgx.
