### ISSUE TITLE
batch update err 

### ISSUE THREAD

**Issue by ChanKunggc** [jackc/pgx#994]
![image](https://user-images.githubusercontent.com/56463479/115710430-ec56af00-a3a4-11eb-9ae9-835df1ffc6ca.png)
![image](https://user-images.githubusercontent.com/56463479/115710472-f8db0780-a3a4-11eb-8414-46b8b6015d57.png)
what's happened ?
sql is correct , did the '?' be replaced fail ?

**Comment by ChanKunggc** [comment]
![Uploading image.png…]()

**Comment by jackc** [comment]
I don't know what `sqlx` is or is supposed to do, but neither PostgreSQL or pgx have any support for `?` as a placeholder value. PostgreSQL and pgx use `$1`, `$2`, `$3`, etc as placeholders.

**Comment by oschwald** [comment]
You can easily write that same query without using `sqlx` by using `any($1)`, e.g.:

```
update device_profile set rm_flag = true where id = any($1)
```

**Comment by ChanKunggc** [comment]
> You can easily write that same query without using `sqlx` by using `any($1)`, e.g.:
> 
> ```
> update device_profile set rm_flag = true where id = any($1)
> ```

That's good advice

**Comment by ChanKunggc** [comment]
i
