### ISSUE TITLE
How to make custom enum types in a record work

### ISSUE THREAD

**Issue by andreacab** [jackc/pgx#995]
Hi, 

I am trying to decodeBinary a row where one column is a custom enum type with no success so far. I am not sure what I am doing wrong. Debugging I could see that in a map where the oid are registered, there isn't the oid for the custom enum type.

Do I have to call `RegisterDataType` if so I fail to see how I would know the oid when deploying to a new infrastructure for example. 

Here some snippets of what I am trying to achieve. With some db:
```
CREATE SCHEMA misc;

CREATE TYPE misc.device_type AS ENUM (
	'phy5',
	'phy6',
	'other'
);

CREATE TABLE misc.devices (
    id int,
    name varchar,
    typ misc.device_type
);

INSERT INTO misc.devices(id,name,typ) VALUES(1, 'cool device', 'phy5');
```
And the go code:
```
type Device struct {
	ID   int
	Name string
	Typ  pgtype.EnumType // tried with string too but no luck
}

func (d *Device) DecodeBinary(ci *pgtype.ConnInfo, src []byte) (err error) {
	r := pgtype.Record{
		Fields: []pgtype.Value{
			&pgtype.Int4{},
			&pgtype.EnumType{},
			&pgtype.Varchar{},
		},
	}
	if err := r.DecodeBinary(ci, src); err != nil {
		log.Println("Could not decode record misc.devices", err, src)
		return err
	}

	if r.Status != pgtype.Present {
		return errors.New("Decoding should not be called on NULL values")
	}

	id := r.Fields[0].(*pgtype.Int4)
	name := r.Fields[1].(*pgtype.Varchar)
	typ := r.Fields[2].(*pgtype.EnumType)

	if err = id.AssignTo(&d.ID); err != nil {
		return err
	}

	if err = name.AssignTo(&d.Name); err != nil {
		return err
	}

	if err = typ.AssignTo(&d.Typ); err != nil {
		return err
	}

	return err
}

func main() {
	conn, err := pgx.Connect(context.Background(), "postgresql://gaitup:gaitup@localhost:5000/gaitup_test")
	if err != nil {
		log.Fatalln(err)
	}
	defer conn.Close(context.Background())

	var device Device
	err = conn.QueryRow(context.Background(), "select ROW(d.*) from misc.devices d where id=1").Scan(&device)
	if err != nil {
		log.Fatalln(err)
	}

	log.Println(device)
```
It fails with the error `unknown oid while decoding record: 16691`

Thanks for your help.

Also thanks for the work on the library, very appreciated!

**Comment by andreacab** [comment]
After another attempt and just following the error, I registered the custom enum type by using the `RegisterDataType` method and finding the oid dynamically by using a SQL query. Is that how I am supposed to do it?

**Comment by jackc** [comment]
> After another attempt and just following the error, I registered the custom enum type by using the RegisterDataType method and finding the oid dynamically by using a SQL query. Is that how I am supposed to do it?

Yes. Each enum has its own oid so when using it in a context where the oid matters (such as part of a composite) often requires registering the type.
